### ISSUE TITLE
Error lifting on json converted xml fails with class cast exception

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#10000]
**Description:**
Following error lifting scenario fails.

```ballerina
import ballerina/io;
function main (string... args) {
    Contact contact = {};
    xml xml1 = xml `<entry>
                    <id>1234</id>
                    <updated>yes</updated>
                    <title>Some</title>
                   </entry>`;

    json json1 = xml1.toJSON({});
    contact = check <Contact>json1;
    string|error str = contact!entry!id;
    io:println(str);
}

type Entry record {
    string|error id;
};

type Contact record {
    Entry|error entry;
};

```

Error from the compiler.

```
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol
        at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:2283)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:2247)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2232)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2202)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:873)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1943)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1735)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1918)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1144)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1918)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:539)
        at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:91)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:555)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1943)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:429)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1950)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:295)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:255)
        at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:196)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:167)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:87)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:66)
```

**Comment by Shan1024** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12507.
