### ISSUE TITLE
VM crashes when string values in a type def aren't within quotes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#10233]
**Description:**
Consider the following:
```ballerina
type forwarded enable|transition;
```
A program with a type def as above crashes the BVM and gives the following compile error as well.
```
error: ./rec3.bal:20:1: cyclic type reference in '[BLangTypeDefinition: forwarded]'
```
Note the Java level info in the error message above. This should be improved to exclude any Java level info.

The ballerina-internal.log contains the following log entry:
```
[2018-08-29 09:32:28,484] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFields(SymbolEnter.java:846)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:206)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:142)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:170)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:163)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:388)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:282)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:147)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:148)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:259)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:94)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:61)
```

**Comment by pubudu91** [comment]
PR #10681 partially resolves this issue
