### ISSUE TITLE
EmptyStackException when typedesc is used in a conditional expression

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#10355]
**Description:**
The following code snippet results in an `EmptyStackException`.
```ballerina
function test(any x) {
    if (typedesc x == int) {
        io:println(x);
    }
}
```
The output for the above contains the following compile error as well:
```
error: ./rec4.bal:68:20: mismatched input '=='. expecting {',', ')'}
```
The log in the ballerina-internal.log file:
```
[2018-09-11 15:12:24,049] ERROR {org.ballerinalang.launcher.Main} - null 
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.createBinaryExpr(BLangPackageBuilder.java:1164)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitBinaryEqualExpression(BLangParserListener.java:1905)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$BinaryEqualExpressionContext.exitRule(BallerinaParser.java:10014)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:536)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:109)
	at org.wso2.ballerinalang.compiler.parser.Parser.lambda$parse$0(Parser.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:84)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:407)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:277)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:147)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:148)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:259)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:94)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:61)
```

**Comment by MaryamZi** [comment]
Getting the following compilation errors as expected with master,
```
error: .::test.bal:6:13: invalid token 'x'
error: .::test.bal:6:15: mismatched input '=='. expecting {',', ')'}
error: .::test.bal:7:22: invalid token ';'
error: .::test.bal:7:22: extraneous input ';'
error: .::test.bal:9:1: mismatched input '}'. expecting {'but', ';', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '&', '^', '...', '|', '?:', '..<'}
```
with the source code
```bal
public function main() {
    test(5);
}

function test(any x) {
    if (typedesc x == int) {
        io:println(x);
    }
}
```
