### ISSUE TITLE
NoSuchMethod error in IDEA plugin

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10580]
**Description:**
```
com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.UnknownFeature.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
java.lang.NoSuchMethodError: com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.UnknownFeature.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
	at io.ballerina.plugins.idea.inspections.LSPluginInstallationNotificationProvider.createExtensionFeature(LSPluginInstallationNotificationProvider.java:141)
	at io.ballerina.plugins.idea.inspections.LSPluginInstallationNotificationProvider.isIgnored(LSPluginInstallationNotificationProvider.java:107)
	at io.ballerina.plugins.idea.inspections.LSPluginInstallationNotificationProvider.createNotificationPanel(LSPluginInstallationNotificationProvider.java:83)
	at io.ballerina.plugins.idea.inspections.LSPluginInstallationNotificationProvider.createNotificationPanel(LSPluginInstallationNotificationProvider.java:52)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NipunaRanasinghe** [comment]
Fixed with #10738 and therefore closing the issue.
