### ISSUE TITLE
Exception occurred after select data from database to table within a transaction

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#10588]
**Description:**
After selecting data using below select function and error [1] can be observed in the log.

table dt = check bankDB->select("SELECT COUNT(*) AS COUNT FROM ACCOUNT WHERE ID = ?", (), accId);

**Steps to reproduce:**

Refer https://github.com/ballerina-guides/managing-database-transactions

The sample will be failed with above error log.

[1] **Execption stacktrace**

[2018-09-26 18:15:15,889] ERROR {org.ballerinalang.util.transactions.TransactionResourceManager} - error in abort the transaction, 0efff304-1bb3-410f-8d0d-415bc82a42e6:1:transaction rollback failed:Streaming result set com.mysql.jdbc.RowDataDynamic@5aa62ee7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries. 
org.ballerinalang.util.exceptions.BallerinaException: transaction rollback failed:Streaming result set com.mysql.jdbc.RowDataDynamic@5aa62ee7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
	at org.ballerinalang.database.sql.SQLTransactionContext.rollback(SQLTransactionContext.java:65)
	at org.ballerinalang.util.transactions.TransactionResourceManager.notifyAbort(TransactionResourceManager.java:185)
	at io.ballerina.transactions.AbortResourceManagers.execute(AbortResourceManagers.java:48)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:393)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:264)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:408)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:159)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:86)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:324)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:271)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:250)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:193)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:186)
	at org.ballerinalang.util.transactions.TransactionUtils.invokeCoordinatorFunction(TransactionUtils.java:92)
	at org.ballerinalang.util.transactions.TransactionUtils.notifyTransactionEnd(TransactionUtils.java:60)
	at org.ballerinalang.bre.bvm.CPU.endTransaction(CPU.java:2670)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:432)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:159)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:86)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:324)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:271)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:250)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:193)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:117)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:75)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:152)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:144)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:277)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)

**Comment by warunalakshitha** [comment]
We can close the table to fix this issue. 

ex.dt.close()

But it will be better to fix this by inside select statement as closing dt by developer will be a overhead.

**Comment by anupama-pathirage** [comment]
This is investigated further and found this is the expected behavior. The table will automatically closed only if the table or converted json/xml fully consumed/iterated. But here it is not fully iterated, so dt.close() should call explicitly. Anyway there is an issue where the error within transaction cannot be logged. It is captured by the issue https://github.com/ballerina-platform/ballerina-lang/issues/8873
Hence closing this issue.
