### ISSUE TITLE
Too many open files issue in OpenJDK

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10594]
**Description:**
```
2018-09-27T14:41:42.5970926Z [INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ language-server-core ---
2018-09-27T14:41:42.6089412Z [INFO] 
2018-09-27T14:41:42.6128016Z [INFO] -------------------------------------------------------
2018-09-27T14:41:42.6150843Z [INFO]  T E S T S
2018-09-27T14:41:42.6176475Z [INFO] -------------------------------------------------------
2018-09-27T14:41:43.2333883Z [INFO] Running TestSuite
2018-09-27T14:41:44.8536660Z SLF4J: Class path contains multiple SLF4J bindings.
2018-09-27T14:41:44.8553255Z SLF4J: Found binding in [jar:file:/home/vsts/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2018-09-27T14:41:44.8572576Z SLF4J: Found binding in [jar:file:/home/vsts/.m2/repository/org/slf4j/slf4j-simple/1.7.22/slf4j-simple-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2018-09-27T14:41:44.8592816Z SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2018-09-27T14:41:44.9117959Z SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2018-09-27T14:42:07.6359763Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/userDefinedFunctionsEmptyLine.bal
2018-09-27T14:42:07.6457633Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/emptyLinePrimitiveDataTypes.bal
2018-09-27T14:42:07.6501282Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/nonEmptyLinePrimitiveDataTypes.bal
2018-09-27T14:42:07.6754341Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/matchExpressionSuggestions.bal
2018-09-27T14:42:07.6822169Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/matchExpressionSuggestions.bal
2018-09-27T14:42:07.7062034Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/commonCompletionBlocks.bal
2018-09-27T14:42:07.7128188Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/commonCompletionBlocks.bal
2018-09-27T14:42:07.7188020Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/commonCompletionBlocks.bal
2018-09-27T14:42:07.7241656Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/commonCompletionBlocks.bal
2018-09-27T14:42:07.7298496Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/function/source/commonCompletionBlocks.bal
2018-09-27T14:42:07.8302747Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/resource/source/emptyLinePrimitiveDataTypes.bal
2018-09-27T14:42:07.8371719Z 2018-09-27 14:42:07 ERROR BallerinaTextDocumentService:553 - Error while opening file:/home/vsts/work/1/s/language-server/modules/langserver-core/src/test/resources/completion/resource/source/nonEmptyLinePrimitiveDataTypes.bal
2018-09-27T14:42:08.5610831Z java.io.FileNotFoundException: /tmp/testng8542865611691021801fileStringBuffer (Too many open files)
2018-09-27T14:42:08.5629518Z 	at java.io.FileOutputStream.open0(Native Method)
2018-09-27T14:42:08.5648736Z 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
2018-09-27T14:42:08.5664762Z 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
2018-09-27T14:42:08.5682127Z 	at java.io.FileWriter.<init>(FileWriter.java:107)
2018-09-27T14:42:08.5701098Z 	at org.testng.reporters.FileStringBuffer.flushToFile(FileStringBuffer.java:114)
2018-09-27T14:42:08.5718399Z 	at org.testng.reporters.FileStringBuffer.toWriter(FileStringBuffer.java:79)
2018-09-27T14:42:08.5737122Z 	at org.testng.reporters.XMLStringBuffer.toWriter(XMLStringBuffer.java:356)
2018-09-27T14:42:08.5755422Z 	at org.testng.internal.Utils.writeUtf8File(Utils.java:117)
2018-09-27T14:42:08.5773386Z 	at org.testng.reporters.jq.Main.generateReport(Main.java:89)
2018-09-27T14:42:08.5787272Z 	at org.testng.TestNG.generateReports(TestNG.java:1076)
2018-09-27T14:42:08.5801833Z 	at org.testng.TestNG.run(TestNG.java:1001)
2018-09-27T14:42:08.5815806Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
2018-09-27T14:42:08.5829351Z 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
2018-09-27T14:42:08.5846168Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
2018-09-27T14:42:08.5859103Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
2018-09-27T14:42:08.6041149Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
2018-09-27T14:42:08.6053607Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
2018-09-27T14:42:08.6067108Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)

```

**Steps to reproduce:**
OpenJDK 1.8

**Affected Versions:**

**OS, DB, other environment details and versions:**
Ubuntu 16.04
OpenJDK (8) (openjdk version "1.8.0_181")

**Comment by Shan1024** [comment]
Yes, this issue occurred due to the limits being too low. This was resolved after increasing the limits.
