### ISSUE TITLE
Importing the wso2/soap package throws compile time error

### ISSUE THREAD

**Issue by Seralahthan** [ballerina-platform/ballerina-lang#10619]
**Description:**
I have been testing soap messaging related guides, which use wso2/soap package with ballerina 0.982.0.  Since wso2/soap package is not supported with ballerina 0.982.0 (got some errors). I reverted and switched back to the older version 0.981.0 which was working previously. Unfortunately now when i run with the older version i am getting the following compiler error. 
 
**Steps to reproduce:**
Run the https://github.com/Seralahthan/ballerina-by-guide/tree/master/consuming-a-soap-service/guide/consuming_a_soap_service following package with 0.982.0 version and clear the cache and run with the 0.981.0 version. The following error is thrown.

```
/usr/lib/ballerina/ballerina-0.981.0/bin/ballerina run consuming_a_soap_service
        wso2/soap:0.3.10 [central.ballerina.io -> home repo]                
ballerina: Oh no, something really went wrong. Bad. Sad.
```

I got the following stack trace in the ballerina-internal.log

```
[2018-09-29 13:01:13,638] ERROR {org.ballerinalang.launcher.Main} - invalid END header (bad central directory offset) 
java.util.zip.ZipError: invalid END header (bad central directory offset)
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1045)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.initFS(ZipConverter.java:67)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.pathWithinZip(ZipConverter.java:56)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.resolveIntoArchive(ZipConverter.java:44)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.validBaloPath(ZipConverter.java:109)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.lambda$latest$344(ZipConverter.java:84)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.latest(ZipConverter.java:88)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.latest(ZipConverter.java:30)
	at org.wso2.ballerinalang.compiler.packaging.Patten.lambda$convert$33(Patten.java:66)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.packaging.RepoHierarchy.resolve(RepoHierarchy.java:40)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageEntity(PackageLoader.java:201)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:325)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:302)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:78)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:173)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$69(SymbolEnter.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:196)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:173)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:166)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:388)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:282)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$45(Compiler.java:147)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:148)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:260)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:94)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
```
**Affected Versions:**
Ballerina 0.981.0, 0.982.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
This issue is due to the **wso2/package-soap** does not supports Ballerina v0.982.0. It is now fixed with the package version 0.3.11 [1] with the PR [2].

[1] https://central.ballerina.io/wso2/soap/0.3.11
[2] https://github.com/wso2-ballerina/package-soap/pull/25/files
