### ISSUE TITLE
Intermittent issue | Transaction block retrying to commit multiple times after successful commit

### ISSUE THREAD

**Issue by SaubhagyaW** [ballerina-platform/ballerina-lang#10611]
**Description:**
This is an intermittent issue. After successful commit to the MySQL database, the transaction block tries to commit again and again causing below error. The database is successfully updated.

**Steps to reproduce:**
```
function upsertDataIntoSfDb(map organizedDataMap, string uuid) {
    foreach key, value in organizedDataMap{

        log:printInfo("Upserting transaction starting for jira key : " + key);
        // Start transaction
        transaction with retries = 3, oncommit = onUpsertCommitFunction, onabort = onUpsertAbortFunction {
            match getBatchStatus() {
                BatchStatus bs => {
                    if (bs.uuid != uuid) {
                        log:printWarn(string `UUID has changed from {{uuid}} to {{bs.uuid}}
                                . Another process has taken over`);
                        abort;
                    } else {
                        match getRecordStatusWithLock(key) {
                            RecordStatus => {
                                log:printDebug(string `RecordsStatus table row locked for key: {{key}}`);
                                // TODO Change record status to IN_PROGRESS

                                foreach opportunity in check <json[]>value {
                                    //Inserting to Account table
                                    var accountResult = mysqlEP->update(QUERY_TO_INSERT_VALUES_TO_ACCOUNT,
                                        opportunity[ACCOUNT][ID].toString(),
                                        opportunity[ACCOUNT][NAME].toString(),
                                        opportunity[ACCOUNT][RATING].toString(),
                                        opportunity[ACCOUNT][CLASSIFICATION].toString(),
                                        opportunity[ACCOUNT][OWNER].toString(),
                                        opportunity[ACCOUNT][TECHNICAL_OWNER].toString(),
                                        opportunity[ACCOUNT][INDUSTRY].toString(),
                                        opportunity[ACCOUNT][PHONE].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][CITY].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][COUNTRY].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][GEOCODEACCURACY].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][LATITUDE].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][LONGITUDE].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][POSTAL_CODE].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][STATE].toString(),
                                        opportunity[ACCOUNT][BILLING_ADDRESS][STREET].toString(),
                                        opportunity[ACCOUNT][RECORD_TYPE].toString());

                                    match accountResult {
                                        int c => {
                                            if (c < 0) {
                                                log:printError("Unable to insert account for jira key: " + key);
                                                abort;
                                            } else {
                                                log:printDebug("Inserted new row to Account");
                                            }
                                        }
                                        error e => {
                                            retry;
                                        }
                                    }

                                    //Inserting to Opportunity table
                                    var oppResult = mysqlEP->update(QUERY_TO_INSERT_VALUES_TO_OPPORTUNITY,
                                        opportunity[ID].toString(),
                                        opportunity[ACCOUNT][ID].toString());

                                    match oppResult {
                                        int c => {
                                            if (c < 0) {
                                                log:printError("Unable to insert opportunity for jira key: " + key);
                                                abort;
                                            } else {
                                                log:printDebug("Inserted new row to Opportunity");
                                            }
                                        }
                                        error e => {
                                            retry;
                                        }
                                    }

                                    //Inserting to OpportunityProducts table
                                    log:printDebug(string `Inserting {{lengthof opportunity[OPPORTUNITY_LINE_ITEMS]}} OpportunityProducts`);
                                    foreach lineItem in opportunity[OPPORTUNITY_LINE_ITEMS] {
                                        sql:Parameter startDate = {
                                            sqlType: sql:TYPE_DATE,
                                            value: null
                                        };

                                        sql:Parameter endDate = {
                                            sqlType: sql:TYPE_DATE,
                                            value: null
                                        };

                                        if (lineItem[START_DATE] != ()){
                                            startDate = {
                                                sqlType: sql:TYPE_DATE,
                                                value: lineItem[START_DATE].toString()
                                            };
                                        }

                                        if (lineItem[END_DATE] != ()){
                                            endDate = {
                                                sqlType: sql:TYPE_DATE,
                                                value: lineItem[END_DATE].toString()
                                            };
                                        }

                                        // Splitting profiles from OpportunityProduct name
                                        string[] splittedArray;
                                        string profile = "Not Specified";
                                        if (lineItem[PRODUCT].toString().contains("Profile") && lineItem[PRODUCT].toString().contains(":")){
                                            splittedArray = lineItem[PRODUCT].toString().split(":");
                                            profile = splittedArray[SECOND_ELEMENT].replace("Profile", "");
                                        }

                                        var lineItemsResult = mysqlEP->update(QUERY_TO_INSERT_VALUES_TO_OPPORTUNITY_PRODUCTS,
                                            lineItem[ID].toString(),
                                            opportunity[ID].toString(),
                                            lineItem[PRODUCT].toString(),
                                            profile,
                                            lineItem[QUANTITY].toString(),
                                            lineItem[ENVIRONMENT].toString(),
                                            startDate,
                                            endDate);

                                        match lineItemsResult {
                                            int c => {
                                                if (c < 0) {
                                                    log:printError("Unable to insert opportunity product: " + lineItem.toString());
                                                    abort;
                                                }
                                            }
                                            error e => {
                                                retry;
                                            }
                                        }
                                    }
                                    log:printDebug("Inserted opportunity products");

                                    foreach supportAccount in opportunity[SUPPORT_ACCOUNTS] {
                                        //Inserting to SupportAccount table
                                        sql:Parameter startDate = {
                                            sqlType: sql:TYPE_DATE,
                                            value: null
                                        };

                                        sql:Parameter endDate = {
                                            sqlType: sql:TYPE_DATE,
                                            value: null
                                        };

                                        if (supportAccount[START_DATE] != ()) {
                                            startDate = {
                                                sqlType: sql:TYPE_DATE,
                                                value: supportAccount[START_DATE].toString()
                                            };
                                        }

                                        if (supportAccount[END_DATE] != ()){
                                            endDate = {
                                                sqlType: sql:TYPE_DATE,
                                                value: supportAccount[END_DATE].toString()
                                            };
                                        }

                                        var supportAccResult = mysqlEP->update(QUERY_TO_INSERT_VALUES_TO_SUPPORT_ACCOUNT,
                                            supportAccount[ID].toString(), opportunity[ID].toString(),
                                            supportAccount[JIRA_KEY].toString(), startDate, endDate);

                                        match supportAccResult {
                                            int c => {
                                                if (c < 0) {
                                                    log:printError("Unable to insert support account: " + supportAccount.toString());
                                                    abort;
                                                } else {
                                                    log:printDebug("Inserted new row to SupportAccount");
                                                }
                                            }
                                            error e => {
                                                retry;
                                            }

                                        }
                                    }
                                }

                                //Update record completed time
                                log:printDebug("All done for Jira key " + key + ". Updating record status");
                                var result = mysqlEP->update(QUERY_UPDATE_RECORD_STATUS, key);

                                match result {
                                    int c => {
                                        if (c < 0) {
                                            log:printError("Unable to update record status for jira key: " + key);
                                            abort;
                                        } else {
                                            log:printDebug("Updated record status for jira key: " + key);
                                        }
                                    }
                                    error e => {
                                        retry;
                                    }
                                }
                            }
                            () => {
                                log:printDebug(string `Unable to lock RecorsStatus table row for key: {{key}}`);
                                retry;
                            }
                            error e => {
                                log:printError("Error occured when getting the row lock for key: " + key, err = e);
                                retry;
                            }
                        }
                    }
                }
                () => {
                    log:printWarn("No batch status found. Aborting");
                    abort;
                }
                error e => {
                    log:printError("Unable to get batch status. Aborting", err = e);
                    retry;
                }
            }
        }
        onretry {
            log:printWarn("Retrying transaction to insert records...");
        }
    }
}
```

Error log:
```
2018-09-28 16:50:50,906 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
error: ballerina/runtime:CallFailedException, message: call failed
	at wso2/dbSync:0.1.0:dataSyncService.syncSalesforceData(dbSync_services.bal:117)
caused by ballerina/runtime:CallFailedException, message: call failed
	at wso2/dbSync:0.1.0:syncSfDataForJiraKeys(dbSync_salesforce_utils.bal:80)
caused by error, message: error: ballerina/runtime:CallFailedException, message: call failed
	at ballerina/transactions:endTransaction(transaction_block.bal:108)
caused by error, message: connection close failed:Connection is closed
	at ballerina/transactions:twoPhaseCommit(2pc_transaction.bal:66)

	at wso2/dbSync:0.1.0:upsertDataIntoSfDb(dbSync_salesforce_utils.bal:631)

2018-09-28 16:53:03,039 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:53:03,040 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:53:03,040 ERROR [ballerina/transactions] - Auto-commit of participated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe failed : {message:"hazard", cause:null} 
2018-09-28 16:54:03,041 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:54:03,042 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:54:03,042 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 16:55:03,043 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:55:03,043 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:55:03,044 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 16:56:03,045 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:56:03,045 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:56:03,046 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 16:57:03,047 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:57:03,048 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:57:03,048 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 16:58:03,049 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:58:03,050 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:58:03,050 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 16:59:03,051 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:59:03,051 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 16:59:03,051 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 17:00:03,052 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 17:00:03,053 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 17:00:03,053 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
2018-09-28 17:01:03,055 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 17:01:03,055 INFO  [wso2/dbSync:0.1.0] - Successful! Upsertion transaction comitted with transaction ID: c96bf026-b9b3-4c34-9635-6af8779646fe:11 
2018-09-28 17:01:03,055 INFO  [ballerina/transactions] - Auto-committed initiated transaction: c96bf026-b9b3-4c34-9635-6af8779646fe. Result: committed 
```

ballerina-internal.log
```
[2018-09-28 16:50:50,915] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed
[2018-09-28 16:53:03,039] ERROR {org.ballerinalang.util.transactions.TransactionResourceManager} - error in commit the transaction, c96bf026-b9b3-4c34-9635-6af8779646$
org.ballerinalang.util.exceptions.BallerinaException: transaction commit failed:Connection is closed
        at org.ballerinalang.database.sql.SQLTransactionContext.commit(SQLTransactionContext.java:54)
        at org.ballerinalang.util.transactions.TransactionResourceManager.notifyCommit(TransactionResourceManager.java:150)
        at io.ballerina.transactions.CommitResourceManagers.execute(CommitResourceManagers.java:48)
        at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
        at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:389)
        at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:260)
        at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:411)
        at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:153)
        at org.ballerinalang.bre.bvm.BLangScheduler$WorkerExecutor.run(BLangScheduler.java:256)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
0.980.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Saubhy** [comment]
Furthermore, the issue occurs only when the SQL queries are inside the match block. In the above code, there is a match block inside the transaction block and the SQL queries are inside that match block. When the code containing the SQL queries is moved outside of the match block, it works as expected.

**Comment by anupama-pathirage** [comment]
@SaubhagyaW It seems that transaction block is not required here. The whole purpose of transaction in this scenario is to catch the errors in select queries. So no point of using transactions to group two select queries. Also we have analyzed the issue and it seems there is an issue when there are two select queries within that. We will fix it, but better to update the code properly.

**Comment by anupama-pathirage** [comment]
Simple code to reproduce the issue:
```ballerina
function testFoo() returns (int, int) {
    endpoint jdbc:Client testDB {
        url: "jdbc:mysql://localhost:3306/testdb",
        username: "root",
        password: "root",
        poolOptions: { maximumPoolSize: 5 },
        dbOptions: { useSSL: false }
    };

    _ = testDB->update("Insert into student (age,name) values (10, 'Clerk')");
    _ = testDB->update("Insert into student (age,name) values (10, 'Clerk')");

    int returnVal = 0;
    int count =0;

    transaction {
        table dt = check testDB->select("Select COUNT(*) as countval from student", ResultCount
        );
        dt.close();
        table dt2 = check testDB->select("Select COUNT(*) as countval from student", ResultCount
        );
        dt.close();

    } onretry {
        returnVal = -1;
    }
    //check whether update action is performed

    testDB.stop();
    return (returnVal, count);
}
```
