### ISSUE TITLE
Select all (*) is failing in native Ballerina Streams Implementation

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#10678]
**Description:**
$subject

**Steps to reproduce:**
I have used below query. It is a passthrough query hence I have used select all (*) to project all the attributes from the input stream.

```
function testSelectQuery() {

    forever {
        from inputStream where inputStream.age > 25
        select *
        => (TeacherOutput[] emp) {
            outputStream.publish(emp);
        }
    }
}
```
but, it resulted with below error.
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.getFieldListInSelectClause(StreamingCodeDesugar.java:1292)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.createSimpleSelectStatement(StreamingCodeDesugar.java:638)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:367)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangSelectClause.accept(BLangSelectClause.java:85)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:207)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangStreamingQueryStatement.accept(BLangStreamingQueryStatement.java:47)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.lambda$desugar$41(StreamingCodeDesugar.java:189)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar$$Lambda$152/616443292.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.desugar(StreamingCodeDesugar.java:189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:500)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:51)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1964)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1974)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:570)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1964)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:450)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1981)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:303)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:140)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:211)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:178)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:145)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:112)
	at org.wso2.ballerinalang.compiler.Compiler$$Lambda$91/1177072083.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:276)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:217)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:199)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:116)
	at org.ballerinalang.test.streaming.BallerinaStreamsV2Test.setup(BallerinaStreamsV2Test.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

**Affected Versions:**
0.982.1

**Suggested Assignees (optional):**
@grainier

**Comment by mohanvive** [comment]
worst case, we should give a compilation error if it is cannot be supported.
