### ISSUE TITLE
NullPointerException while looping on select result

### ISSUE THREAD

**Issue by ponsilva** [ballerina-platform/ballerina-lang#10767]
**Description:**
While looping on select result without casting on custom type, a NullPointerException happens

**Steps to reproduce:**
```
type MyRec record {    
    int id,
    string name,
    int age,    
    float rank,
};

function main(string... args) {    
    
    //var selectRet = testDB->select("SELECT id, name, age, rank FROM balTest", MyRec);    
    var selectRet = testDB->select("SELECT id, name, age, rank FROM balTest", null);    
    io:println("statement executed");
           
    //table<MyRec> dt;
    table dt;
    match selectRet {
        table tableReturned => dt = tableReturned;           
        error err => io:println("Select data from balTest table failed: " + err.message);
    }    

    foreach x in dt {
        io:println(x);
    }        
}
```
If I use the MyRec cast, it works fine

**Affected Versions:**
ballerina-0.981.1

**OS, DB, other environment details and versions:**
windows 

**ballerina-internal.log**
[2018-10-10 12:14:56,214] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageInfoWriter.writeInstructions(PackageInfoWriter.java:604)
	at org.wso2.ballerinalang.programfile.PackageInfoWriter.writePackageInfo(PackageInfoWriter.java:209)
	at org.wso2.ballerinalang.programfile.PackageInfoWriter.getPackageBinary(PackageInfoWriter.java:147)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getPackageBinaryContent(CodeGenerator.java:3655)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:366)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:212)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:180)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:142)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:109)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:260)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:94)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

**Comment by Manuri** [comment]
This is fixed in 0.982.0 release with https://github.com/ballerina-platform/ballerina-lang/pull/10352
