### ISSUE TITLE
Ballerina Stream join does not work without 'on' condition

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#10766]
**Description:**
$subject

**Steps to reproduce:**
Please consider below query. 

```
forever {
        from stockStream window lengthWindow(1)
        join twitterStream window lengthWindow(1)
        select stockStream.symbol as symbol, twitterStream.tweet as tweet, stockStream.price as price
        => (StockWithPrice[] emp) {
            foreach e in emp {
                stockWithPriceStream.publish(e);
            }
        }
    }
```
It result with below error,

java.lang.IllegalStateException: Compilation Failed:
ERROR: .::streamingv2-join-test.bal:52:9:: extraneous input 'select'
ERROR: .::streamingv2-join-test.bal:52:16:: mismatched input 'stockStream'. expecting {'as', 'on', 'where'}
ERROR: .::streamingv2-join-test.bal:52:35:: extraneous input 'as'
ERROR: .::streamingv2-join-test.bal:53:35:: missing token '=' before '{'
ERROR: .::streamingv2-join-test.bal:54:21:: missing token '(' before 'e'
ERROR: .::streamingv2-join-test.bal:54:23:: mismatched input 'in'. expecting {'but', '.', ',', ')', '[', '?', '+', '-', '*', '/', '%', '!', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '&', '^', '@', '...', '|', '?:', '..<'}

	at org.ballerinalang.launcher.util.BRunUtil.invokeFunction(BRunUtil.java:201)
	at org.ballerinalang.launcher.util.BRunUtil.invoke(BRunUtil.java:187)
	at org.ballerinalang.launcher.util.BRunUtil.invoke(BRunUtil.java:247)
	at org.ballerinalang.test.streaming.BallerinaStreamsV2JoinTest.testStreamJoinQuery(BallerinaStreamsV2JoinTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

**Suggested Assignees (optional):**
@gimantha @grainier @mohanvive

**Comment by mohanvive** [comment]
It seems, we have to improve the grammar as well.
