### ISSUE TITLE
Testerina throws a null pointer exception when processing a XML payload

### ISSUE THREAD

**Issue by Seralahthan** [ballerina-platform/ballerina-lang#10780]
**Description:**
Testerina throws a null pointer exception when processing a XML payload received from a HTTP Service. The ballerina compiler crashes with the following exception.

`[2018-10-11 15:16:32,176] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.setTaintedStatus(TaintAnalyzer.java:1436)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitAssignment(TaintAnalyzer.java:512)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.updateArgTaintedStatus(TaintAnalyzer.java:1994)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.updateArgTaintedStatus(TaintAnalyzer.java:1957)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeInvocation(TaintAnalyzer.java:1925)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:930)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:108)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:889)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangIndexBasedAccess.accept(BLangIndexBasedAccess.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeInvocation(TaintAnalyzer.java:1932)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:930)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:108)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:1023)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:62)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:831)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangArrayLiteral.accept(BLangArrayLiteral.java:45)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:384)
	at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:90)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:436)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.lambda$visit$9(TaintAnalyzer.java:595)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:593)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:582)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:582)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.lambda$visit$9(TaintAnalyzer.java:595)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:593)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:1641)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:1590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeAllParamsUntaintedReturnTaintedStatus(TaintAnalyzer.java:1566)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitInvokable(TaintAnalyzer.java:1521)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:330)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.lambda$visit$0(TaintAnalyzer.java:271)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:270)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:140)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyze(TaintAnalyzer.java:255)
	at org.wso2.ballerinalang.compiler.CompilerDriver.taintAnalyze(CompilerDriver.java:203)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:168)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:145)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:112)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:276)
	at org.ballerinalang.launcher.util.BCompileUtil.compileWithTests(BCompileUtil.java:237)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$compileAndBuildSuites$4(BTestRunner.java:172)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.ballerinalang.testerina.core.BTestRunner.compileAndBuildSuites(BTestRunner.java:160)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:99)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:83)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:71)
	at org.ballerinalang.testerina.core.TestCmd.execute(TestCmd.java:158)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)` 

**Steps to reproduce:**
1. Clone the https://github.com/Seralahthan/exposing-soap-services repository
2. Deploy the back-end axis2 services https://github.com/Seralahthan/exposing-soap-services/blob/master/UnsecureBankingService.zip in WSO2-EI.
3. Navigate **exposing-soap-services/guide/**
4. Run **`ballerina test`**

**Affected Versions:**
Ballerina-0.982.0

**OS, DB, other environment details and versions:**
Ubuntu-16.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaSenanayaka** [comment]
Hi

We are further investigating this issue and we could narrow down the issue til the Ballerina language error. Furthermore, issue happens when xml manipulating in func call directly inside the if statement.

E.g.
....
function func(string s) {}
...
if(1 == 1) {
    func(axis.accountHolderName);
}
...
