### ISSUE TITLE
[HTTP] NoSuchElementException get thrown when load test for passthrough scenario

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#10796]
**Description:**
An error occurred while a load testing with Ballerina HTTP/1.1 passthrough scenario. It is observed that only the ERROR message is displayed at ballerina-internal.log but the process can be continued.

**Steps to reproduce:**
This was reproducible for 100 concurrency with a 8KB JSON payload after invoking for around 2 minutes. _Ballerina service_ doesn't consume the payload of the request, which is '8KB'. And it responds with a small payload of '15 bytes'.

The following would be the scenario:
_Jmeter Client -> Ballerina passthrough service -> Ballerina service._

**Ballerina passthrough service**
```
import ballerina/http;
import ballerina/log;

endpoint http:Listener passthroughEP {
    port:9090
};

endpoint http:Client nyseEP {
    url:"http://localhost:9191"
};

@http:ServiceConfig {basePath:"/passthrough"}
service<http:Service> passthroughService bind passthroughEP {

    @http:ResourceConfig {
        path:"/"
    }
    passthrough (endpoint outboundEP, http:Request clientRequest) {
        var response = nyseEP -> forward("/nyseStock/stocks", clientRequest);
        match response {
            http:Response httpResponse => {
                _ = outboundEP -> respond(httpResponse);
            }
            error e => {
                http:Response errorResponse = new;
                log:printError("Error", err = e);
                json errMsg = {"error":"error occurred while invoking the service"};
                errorResponse.setJsonPayload(errMsg);
                _ = outboundEP -> respond(errorResponse);
            }
        }
    }
}
```

**Ballerina service**
```
import ballerina/http;
import ballerina/runtime;
import ballerina/io;

endpoint http:Listener passthroughEP {
    port:9191
};

@http:ServiceConfig {basePath:"/nyseStock"}
service<http:Service> nyseStockQuote bind passthroughEP {

    @http:ResourceConfig {
        path:"/stocks"
    }
    stocks (endpoint outboundEP, http:Request clientRequest) {
        http:Response res = new;
	var payload = clientRequest.getJsonPayload();
        match payload {
            json j => res.setJsonPayload(j);
            error err => io:println(err);
        }
        _ = outboundEP -> respond(res);
    }
}
```

**Observations**
The following error message get printed in `ballerina-internal.log` at the _Ballerina passthrough service_.
```
[2018-10-12 14:07:24,951] WARN  {io.netty.util.concurrent.DefaultPromise} - An exception was thrown by org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1$$Lambda$249/1397477578.operationComplete() 
java.util.NoSuchElementException: targetHandler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1089)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
	at org.wso2.transport.http.netty.contractimpl.sender.channel.TargetChannel.setEndPointTimeout(TargetChannel.java:155)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.prepareTargetChannelForHttp(DefaultHttpClientConnector.java:229)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.startExecutingOutboundRequest(DefaultHttpClientConnector.java:200)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.lambda$null$0(DefaultHttpClientConnector.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.lambda$onSuccess$1(DefaultHttpClientConnector.java:186)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:832)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
**Affected Versions:**
Ballerina-Platform-0.982.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Suggested Labels (optional):**
Component/stdlib
Type/Bug
Component/HTTP

**Suggested Assignees (optional):**
@chamil321

**Comment by chamil321** [comment]
Fixed by https://github.com/wso2/transport-http/pull/285, Hence closing the issue
