### ISSUE TITLE
Error when compiling function type definition

### ISSUE THREAD

**Issue by IanWold** [ballerina-platform/ballerina-lang#10887]
Hello all, I'm new to Ballerina, please advise me if this issue has been covered already and I missed it, or if I'm otherwise in error.

**Description:**

I have a program with a single Ballerina file (*main.bal* - included below in "steps to reproduce") with a type definition for a function (string -> int), and this type definition is resulting in a compile-time error (below). The definition in question is the following:

```Ballerina
type MyType function (string) returns int;
```

For two reasons (on which I might be incorrect - please let me know) I believe that this is not the intended behavior of the compiler. First, and less importantly, the linter included with the Ballerina package for VS Code does not tell me I have input anything syntactically incorrect. Second, the language specification draft (0.980, 018/7/12) leads me to believe that this is allowed by the language - specifically the grammar specified in 8.Type Definitions and 5.Type Descriptors.

When I run `ballerina build` I get an error that something really went wrong, that it is bad and sad, and then the compiler outputs the following to a log file:

```
[2018-10-17 18:56:21,573] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:345)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:122)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:327)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:192)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:140)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:158)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:402)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:296)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:147)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:149)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:165)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:89)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:85)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:95)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

Commenting out the definition (as shown in my code below in "steps to reproduce") results in a happy compiler.

**Steps to reproduce:**

1. *main.bal* resulting in compile error:

```Ballerina
import ballerina/io;

type MyType function (string) returns int;

public function main() {
    MyType func = function (string s) returns int {
        var len = lengthof s;
        return len + 10;
    };

    io:println(func("hello"));
}
```

2. *main.bal* resulting in success:

```Ballerina
import ballerina/io;

//type MyType function (string) returns int;

public function main() {
    var func = function (string s) returns int {
        var len = lengthof s;
        return len + 10;
    };

    io:println(func("hello"));
}
```

**Affected Versions:**

0.980 is all I have been able to test this on.

**OS, DB, other environment details and versions:**

OS: Windows 10 1803

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12540
