### ISSUE TITLE
Intermittent Test failure in VS code plugin tests

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#10909]
**Description:**
Tests related to the VS code plugin are failing intermittently with below stack trace.
```
> ballerina@0.982.1-SNAPSHOT test /home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode
> npm run compile && node ./node_modules/vscode/bin/test


> ballerina@0.982.1-SNAPSHOT compile /home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: /home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode
Downloading VS Code into "/home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode/.vscode-test/stable" from: https://vscode-update.azurewebsites.net/1.28.2/linux-x64/stable
Running extension tests: /home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode/.vscode-test/stable/VSCode-linux-x64/code /home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode/out/test --extensionDevelopmentPath=/home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode --extensionTestsPath=/home/travis/build/ballerina-platform/ballerina-lang/tool-plugins/vscode/out/test
Xlib:  extension "RANDR" missing on display ":99.0".

[90m[main 7:41:55 AM][0m update#setState idle

xdg-settings: unknown desktop environment

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell



[0m[0m

[0m  Ballerina Extension Core Tests[0m

  [32m  âœ“[0m[90m Test isValidBallerinaHome[0m

  [32m  âœ“[0m[90m Test autoDitectBallerinaHome[0m[31m (112ms)[0m

  [32m  âœ“[0m[90m Test getBallerinaVersion[0m

[0m  Ballerina Debug Adapter[0m

[0m    vscode debugger integration tests[0m

    [32m  âœ“[0m[90m Initialize request[0m[31m (532ms)[0m

    [32m  âœ“[0m[90m launch request[0m[31m (3453ms)[0m

    [32m  âœ“[0m[90m should stop on a breakpoint, main function[0m[31m (2734ms)[0m

    [32m  âœ“[0m[90m should stop on a breakpoint, hello world service[0m[31m (3516ms)[0m

    [31m  1) should stop on a breakpoint, hello world service - package[0m

    [32m  âœ“[0m[90m step In, hello world service - package[0m[31m (3445ms)[0m

[92m [0m[32m 8 passing[0m[90m (15s)[0m

[31m  1 failing[0m

[0m  1) Ballerina Debug Adapter
       vscode debugger integration tests
         should stop on a breakpoint, hello world service - package:
[0m[31m     Uncaught Error: socket hang up[0m[90m
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
[0m

Tests exited with code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ballerina@0.982.1-SNAPSHOT test: `npm run compile && node ./node_modules/vscode/bin/test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ballerina@0.982.1-SNAPSHOT test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-10-19T07_42_18_853Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by pahans** [comment]
This occurs only in travis build. I am looking in to this

**Comment by kaviththiranga** [comment]
@pahans any update on this?
