### ISSUE TITLE
[Ballerina Streams Desugar] Issue in passing method variables to lambda function used for Streaming Action

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#10970]
**Description:**
$subject

**Steps to reproduce:**
Check below query.  It fails with the exception

```
import ballerina/runtime;
import ballerina/io;
import ballerina/streams;
import ballerina/reflect;

type Teacher record {
    string name;
    int age;
    string status;
    string batch;
    string school;
};

type TeacherOutput record {
    string name;
    int age;
    int sumAge;
    int count;
};

int index = 0;
TeacherOutput[] globalTeacherOutputArray = [];

function startAggregationWithGroupByQuery() returns TeacherOutput[] {

    Teacher[] teachers = [];
    Teacher t1 = { name: "Mohan", age: 30, status: "single", batch: "LK2014", school: "Hindu College" };
    Teacher t2 = { name: "Raja", age: 45, status: "single", batch: "LK2014", school: "Hindu College" };
    teachers[0] = t1;
    teachers[1] = t2;
    teachers[2] = t2;
    teachers[3] = t1;

    stream<Teacher> inputStream;
    stream<TeacherOutput> outputStream;
    createAggregationQueryWithGroupby(inputStream, outputStream);

    outputStream.subscribe(printTeachers);
    foreach t in teachers {
        inputStream.publish(t);
    }

    int count = 0;
    while(true) {
        runtime:sleep(500);
        count += 1;
        if((lengthof globalTeacherOutputArray) == 4 || count == 10) {
            break;
        }
    }
    return globalTeacherOutputArray;
}


//  ------------- Query to be implemented -------------------------------------------------------
//  from inputStream where inputStream.age > 25
//  select inputStream.name, inputStream.age, sum (inputStream.age) as sumAge, count() as count
//  group by inputStream.name
//      => (TeacherOutput [] o) {
//            outputStream.publish(o);
//      }
//

function createAggregationQueryWithGroupby(stream<Teacher> inStream, stream<TeacherOutput> outStream) {
    forever {
        from inStream where inStream.age > 25 as input
        select input.name, input.age, sum (input.age) as sumAge, count() as count
        group by input.name
        => (TeacherOutput[] teachers) {
            foreach t in teachers {
                outStream.publish(t);
            }
        }
    }
}

function printTeachers(TeacherOutput e) {
    addToGlobalEmployeeArray(e);
}

function addToGlobalEmployeeArray(TeacherOutput e) {
    globalTeacherOutputArray[index] = e;
    index = index + 1;
}
```

Below is the exception.

```
2018-10-23 15:35:14 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 15402891141029aad28eb-0f87-44ad-97c0-0e67378eed74
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:175)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.ballerinalang.util.exceptions.BLangRuntimeException: error: ballerina/runtime:CallFailedException, message: call failed
	at $lambda$streaming4(streamingv2-aggregate-with-groupby-test.bal:82)
caused by ballerina/runtime:CallFailedException, message: call failed
	at ballerina/streams:process(filter.bal:35)
caused by ballerina/runtime:CallFailedException, message: call failed
	at ballerina/streams:process(select.bal:75)
caused by ballerina/runtime:CallFailedException, message: call failed
	at ballerina/streams:process(output-processor.bal:41)
caused by ballerina/runtime:CallFailedException, message: call failed
	at $lambda$streaming0(streamingv2-aggregate-with-groupby-test.bal:85)
caused by ballerina/runtime:NullReferenceException
	at $lambda$0(streamingv2-aggregate-with-groupby-test.bal:86)






	at org.ballerinalang.util.program.BLangFunctions.handleError(BLangFunctions.java:470)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:365)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:305)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:284)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:227)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:220)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:172)
	... 9 more
```

**Affected Versions:**
0.982.0

**Suggested Assignees (optional):**
@gimantha @mohanvive @grainier

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19656
