### ISSUE TITLE
Error when trying to get the access token for Ballerina Central the first time you perform a ballerina push

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#11219]
**Description:**
The following error is given when trying to get the access token for Ballerina Central if the 'Settings.toml' does not contain the access token or if the Settings.toml file is missing:

[2018-11-05 16:41:32,327] ERROR {org.ballerinalang.launcher.Main} - main function not found in  'null' 
org.ballerinalang.util.exceptions.BallerinaException: main function not found in  'null'
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:64)
	at org.ballerinalang.cli.utils.ExecutorUtils.executeFunction(ExecutorUtils.java:54)
	at org.ballerinalang.cli.utils.BVMEmbeddedExecutor.executeFunction(BVMEmbeddedExecutor.java:69)
	at org.ballerinalang.packerina.PushUtils.checkAccessToken(PushUtils.java:190)
	at org.ballerinalang.packerina.PushUtils.pushPackages(PushUtils.java:136)
	at org.ballerinalang.packerina.cmd.PushCommand.execute(PushCommand.java:77)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)

**Steps to reproduce:**

- Delete the Settings.toml file from your home repository (./ballerina) 
- Try pushing the module using 'ballerina push <module-name>'

**Affected Versions:**
0.983

**Comment by NatashaWso2** [comment]
Closing this issue since it has been fixed with #11225
