### ISSUE TITLE
Cannot filter table using lamba function. - Bad Sad

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#11251]
**Description:**
$subject . No way to filter table.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/io;

table<Review> tbReviews = table {
        { id, review },
        [ { "B1", "Review of book1" },
          { "B2", "Review of book2" },
          { "B3", "Review of book3" }
        ]
    };

endpoint http:Listener bookReviewEP {
    port: 7070
};

@http:ServiceConfig {
    basePath: "/review"
}
service<http:Service> reviewService bind bookReviewEP {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/{bookId}"
    }
    getReview (endpoint caller, http:Request request, string bookId) {
        http:Response reviewResponse = new;
        function (Review r) returns (boolean) getReview =
                                                (r) => r.id == bookId;
        table<Review> bookReview = tbReviews.filter(getReview);
        if (bookReview.count() == 1) {
            json reviewJson = check <json>bookReview;
            io:println(reviewJson[0]);
            reviewResponse.setTextPayload(reviewJson[0].review.toString());
        } else {
            reviewResponse.setTextPayload("(no reviews found)");
        }
        _ = caller -> respond(reviewResponse);
    }
}
```

Invoke as `curl http://0.0.0.0:7070/review/B1`.

Error log:
```
[2018-11-06 23:22:37,533] ERROR {org.ballerinalang.launcher.Main} - Index: 0, Size: 0 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.ballerinalang.compiler.desugar.ASTBuilderUtil.generateArgExprs(ASTBuilderUtil.java:377)
	at org.wso2.ballerinalang.compiler.desugar.ASTBuilderUtil.createInvocationExpr(ASTBuilderUtil.java:399)
	at org.wso2.ballerinalang.compiler.desugar.ASTBuilderUtil.createInvocationExpr(ASTBuilderUtil.java:390)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.generateFilter(IterableCodeDesugar.java:770)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.generateOperationCode(IterableCodeDesugar.java:727)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.lambda$generateStreamingIteratorBlock$1(IterableCodeDesugar.java:318)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.generateStreamingIteratorBlock(IterableCodeDesugar.java:318)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.generateIteratorFunction(IterableCodeDesugar.java:221)
	at org.wso2.ballerinalang.compiler.desugar.IterableCodeDesugar.desugar(IterableCodeDesugar.java:126)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visitIterableOperationInvocation(Desugar.java:1898)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1167)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:108)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1949)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:560)
	at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:90)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:576)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1964)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1974)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:570)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1964)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:512)
	at org.wso2.ballerinalang.compiler.tree.BLangResource.accept(BLangResource.java:30)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1981)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:470)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:209)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1981)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:302)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:140)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1924)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:211)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:178)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:145)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:112)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:299)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:118)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:277)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
 

```
**Affected Versions:**
0.982.0
0.983.0

**OS, DB, other environment details and versions:**
Mac

**Comment by anupama-pathirage** [comment]
Currently we don't have a collect() operation. So we can't use filter operation with any collection without an aggregate function like average(). We need to give a proper error message for this.

We will send a fix with proper error message.  Meantime you can use following to get the required data.
```ballerina
table<Review> selected = from tbReviews where id == "B1" select *;
```

**Comment by hemikak** [comment]
Using queries also didnt work unless I hardcode the value into the query. - https://github.com/ballerina-platform/ballerina-lang/issues/11252

**Comment by pubudu91** [comment]
Shouldn't this properly return a filtered table? True we don't have a collect() operation. But the same holds true for other iterable types as well, and filter works on them (e.g., maps, records).

**Comment by hasithaa** [comment]
This is fixed in SLP1 with the new Table design.
