### ISSUE TITLE
Crash during simple twitter code test

### ISSUE THREAD

**Issue by ghost** [ballerina-platform/ballerina-lang#11680]
**Description:**
I am trying to execute twitter example as per YouTube ref: https://www.youtube.com/watch?v=67v7mjlSHWI&t=29s and almost used same code but it is failing at my end. There are 2 issues

First , it is reporting error around type Person . Error:
   error: .::twiter.bal:14:13: extraneous input '{'
  error: .::twiter.bal:15:10: extraneous input 'name'

Second, It is crashing on both windows and linux(ubuntu 16).

  root@bd5dfe74a247:/# ballerina build twiter.bal
Compiling source
    twiter.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

Errorlog:

root@bd5dfe74a247:/# cat ballerina-internal.log
[2018-11-22 16:53:20,707] ERROR {org.ballerinalang.launcher.Main} - java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
java.io.UncheckedIOException: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.PackageLoader.createInMemoryCompiledPackage(PackageLoader.java:468)
        at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:419)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:309)
        at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
        at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:171)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
        ... 37 more

[2018-11-22 16:59:42,003] ERROR {org.ballerinalang.launcher.Main} - java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
java.io.UncheckedIOException: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.PackageLoader.createInMemoryCompiledPackage(PackageLoader.java:468)
        at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:419)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:309)
        at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
        at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:171)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
        ... 37 more

[2018-11-22 17:19:46,821] ERROR {org.ballerinalang.launcher.Main} - java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
java.io.UncheckedIOException: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.PackageLoader.createInMemoryCompiledPackage(PackageLoader.java:468)
        at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:419)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:309)
        at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
        at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:171)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
        ... 37 more

[2018-11-22 17:20:53,259] ERROR {org.ballerinalang.launcher.Main} - java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
java.io.UncheckedIOException: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.PackageLoader.createInMemoryCompiledPackage(PackageLoader.java:468)
        at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:419)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:309)
        at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
        at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.nio.file.FileSystemException: /./proc/1/map_files: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:171)
        at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
        ... 37 more

root@bd5dfe74a247:/#

**Steps to reproduce:**

- mkdir twitter;
- cp twiter.bal twitter
- ballerina build twitter/

**Affected Versions:**
root@bd5dfe74a247:/# ballerina version
Ballerina 0.983.0

root@bd5dfe74a247:/#

**OS, DB, other environment details and versions:**
root@bd5dfe74a247:/# uname -a
Linux bd5dfe74a247 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by symantec-shailendersingh** [comment]
//https://www.youtube.com/watch?v=67v7mjlSHWI&t=29s - YouTube reference for this code reference

import ballerina/config;
import ballerina/io;
import wso2/twitter;
import ballerina/http;
import ballerina/runtime;
//import ballerina/time;

endpoint http:Listener listener {
   port:9090
};
//Some how it is not detecting type and reporting error around it
//type Person {
//  string name;
//};
endpoint twitter:Client tweeter {
    clintId: config:getAsString("CLIENT_ID"),
	clientSecret: config:getAsString("CLIENT_SECRET"),
	accessToken: config:getAsString("ACCESS_TOKEN"),
	accessTokenSecret: config:getAsString("ACCESS_TOKEN_SECRET"),
    clientConfig: {}
};

@http:ServiceConfig {
   basePath: "/"
}
service<http:Service> hello bind listener {
         @http:ResourceConfig {
         basePath: "/",
         methods: ["POST"],
         body: "person",
         consumes: ["application/json"],
         produces: ["application/json"]
      }
      hi (endpoint caller, http:Request request) {
      //hi (endpoint caller, http:Request request, Person person) {
      string payload_body = check request.getTextPayload();
      var status = check tweeter ->tweet("Hello" + payload_body + "PacktPub #ballerina example" );
      int id = status.id;
      string createdAt = status.CreatedAt;
      json jason_content = {
         twitterID: id,
         createdAt: createdAt,
         key: "value"
      };
      _ = caller -> respond(jason_content);
   }
}

**Comment by symantec-shailendersingh** [comment]
FYI... I ran it on docker ubuntu container as well as on my laptop but still it was giving same error.

**Comment by hasithaa** [comment]
Given syntax is no longer valid. Hence resolving this issue.
