### ISSUE TITLE
Some errors that should result in panic, now logged to the ballerina-internal.log incorrectly

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#12253]
**Description:**
```ballerina
import ballerina/io;

public function main(){
    any[2] i = [1, 2];
    add(i);
}

function add(any[] i) {
    i[4] = 3;
}
```

Output with 0.983.0 
```cmd
error: ballerina/runtime:CallFailedException, message: call failed
        at main(freeze.bal:5)
caused by error, message: array index out of range: index: 4, size: 2
        at add(freeze.bal:9)
```

Output with df_endpoint_change
```cmd
ballerina: array index out of range: index: 4, size: 2
```
and the ballerina-internal.log contains:
```txt
[2018-12-02 20:52:23,263] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - array index out of range: index: 4, size: 2 
org.ballerinalang.util.exceptions.BallerinaException: array index out of range: index: 4, size: 2
	at org.ballerinalang.util.exceptions.BLangExceptionHelper.getRuntimeException(BLangExceptionHelper.java:58)
	at org.ballerinalang.model.values.BNewArray.rangeCheck(BNewArray.java:98)
	at org.ballerinalang.model.values.BNewArray.prepareForAdd(BNewArray.java:80)
	at org.ballerinalang.model.values.BValueArray.add(BValueArray.java:210)
	at org.ballerinalang.model.util.ListUtils.execListAddOperation(ListUtils.java:100)
	at org.ballerinalang.bre.bvm.BVM.execStoreOpcodes(BVM.java:1700)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:329)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:180)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:156)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:148)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:278)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
```

This seems to be due to the removal of the [outer try-catch block](https://github.com/ballerina-platform/ballerina-lang/blob/v0.983.0/bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java#L779) in the CPU (now BVM) class's tryExec (now execute) method.

**Comment by MaryamZi** [comment]
Non-ref value array stores handle the errors [as they occur](https://github.com/ballerina-platform/ballerina-lang/blob/df_endpoint_change/bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java#L1664), but not RASTORE.

Similarly, all instructions which relied on the previous catch block for correct behaviour would now have different behaviour.

**Comment by lankavitharana** [comment]
These needs to be handled at the instruction level, we had a try catch wrapping the whole instruction space, and we have removed that, because ideally our type system should guarantee that there won't be so many runtime failures, so the places where there can be runtime failures need to be handled individually,(having a try catch wrapping the whole instruction space may cause actual BVM errors to go unnoticed)
