### ISSUE TITLE
Error lifting operator on xml type makes the compiler crash

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#12308]
**Description:**
Man, it took me a few hours to isolate this compiler crash from a fairly complex project, but I finally did it!
This is the smallest sample of code reproducing the crash, just type `ballerina build compiler_crash.bal` to get this
````
Compiling source
    compiler_crash.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
````

**Steps to reproduce:**
Here is the file `compiler_crash.bal`
```
function crash(xml obj) {
    _ = obj!getTextValue();
}
```
and the generated `ballerina-internal.log`
```
[2018-12-03 23:58:26,676] ERROR {org.ballerinalang.launcher.Main} - org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:2337)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:2299)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2284)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2254)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:865)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:2044)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:638)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1825)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:2019)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1223)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:108)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:2019)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:666)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:2044)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:638)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:526)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2051)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:403)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:211)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:178)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:145)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:112)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

**Affected Versions:**
0.983.0
0.983.1-SNAPSHOT (Dec 01, 2018)

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**
Issues #6693 and #10000

**Suggested Labels (optional):**
Type/Bug, Component/Compiler

**Comment by SupunS** [comment]
Fixed with #12507

**Comment by davebaol** [comment]
Thanks.
Looks like the same problem affects also error lifting operator on json type.
Does #12507 fix this too?

**Comment by SupunS** [comment]
Yes, it will fix for all types :)

**Comment by davebaol** [comment]
Great! :)
