### ISSUE TITLE
create with a function call crashes

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#12358]
**Description:**
The following code crashes 
```
import ballerina/io;

public function main() {
    var choice = int.create(io:readln("Enter choice 1 - 5: "));
}
```
with the following internal.log:
```
[2018-12-04 15:33:45,045] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - 3 
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2350)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:601)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:180)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:156)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:148)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:278)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
[2018-12-04 15:33:45,065] ERROR {org.ballerinalang.launcher.Main} - java.lang.ArrayIndexOutOfBoundsException: 3 
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:180)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:156)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:148)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:278)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2350)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:601)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 8 more
 

```

**Comment by warunalakshitha** [comment]
As a workaround we can use,
    string s = io:readln("Enter choice 1 - 5: ");
    var choice = int.convert(s);

It seems to be issue when using  io:readline method  as parameter to convert method. Function calls seems working.
function getString(string s) returns string  {
    return s;
}

   var choice = int.convert(getString("2"));

**Comment by SupunS** [comment]
This issue is when the argument is `any` type.
```ballerina
function getString(any s) returns string {
    return "5";
}
```
