### ISSUE TITLE
Issue in safe navigation

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12495]
**Description:**
```ballerina
function test(json obj) {
    _ = obj!toString();
}
```

```
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1358)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1150)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BErrorType.accept(BErrorType.java:43)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getConversionOperator(Types.java:882)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveConversionOperator(SymbolResolver.java:285)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:3636)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:3559)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:3495)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:3468)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1518)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:89)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3234)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2765)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:3209)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2012)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:112)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:3209)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1059)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3234)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3241)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:208)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:171)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:133)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:326)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:238)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:205)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:217)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:117)
	at org.ballerinalang.test.access.AccessLevelsNegativeTest.testPrivateAccessLevel(AccessLevelsNegativeTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by SupunS** [comment]
Related: https://github.com/ballerina-platform/ballerina-lang/issues/10000

**Comment by Shan1024** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12507.
