### ISSUE TITLE
Non-terminating recursive functions crashes the BVM

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12627]
Consider the following:
```ballerina
public function main() {
    test();
}

function test() {
    test();
}
```

Running the above crashes the runtime since this results in a stack over flow. This should've given a runtime error to the user instead. The ballerina-internal.log contains the following:
```
[2018-12-07 13:46:02,317] ERROR {org.ballerinalang.launcher.Main} - java.lang.ArrayIndexOutOfBoundsException: 2000 
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2000
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:180)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:168)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:160)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2000
	at org.ballerinalang.bre.bvm.Strand.pushFrame(Strand.java:93)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:855)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:433)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 8 more
```

**Comment by pubudu91** [comment]
Fixed with PR #12642. Hence closing this.
