### ISSUE TITLE
NPE thrown when accessing service variable

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#12657]
**Description:**
Following code returns `ballerina: Oh no, something really went wrong. Bad. Sad.`.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/runtime;

public function main(string... args) {
    http:WebSocketClient wsClient = new(
        "ws://0.0.0.0:9090/websocketServer",
        config = {callbackService: callbackWebsocketServerService, readyOnConnect: true}
    );
    //Send a message
    _ = wsClient->pushText("hey", finalFrame=true);
    //Wait some time for a reply
    runtime:sleep(5000);
    //Check the reply received
    io:println("received:", callbackWebsocketServerService.wsReply);
}

service callbackWebsocketServerService = @http:WebSocketServiceConfig {} service {
    public string wsReply = "";
    resource function onText(http:WebSocketClient callbackWebsocketServerServiceEp, string text) {
        io:println("---------------callback-----------------");
        self.wsReply = text;
    }
};
```
**Error Log:**
```
[2018-12-07 19:34:49,291] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupMemberSymbol(SymbolResolver.java:793)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveStructField(SymbolResolver.java:631)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkStructFieldAccess(TypeChecker.java:2358)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkFieldAccessExpr(TypeChecker.java:2601)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:872)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:57)
```

**Comment by MaryamZi** [comment]
Fields are no longer allowed in services with https://github.com/ballerina-platform/ballerina-lang/pull/17408. 

However, trying to do the same as well as invoke a service object method cause bad, sad errors. This is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/17903.
