### ISSUE TITLE
RunTimeException when trying to access a map in streaming desugar code

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#12744]
**Description:**
I was trying to write a desugar code to access a map via field based access, but I get an exception like this

`InherentTypeViolation {"message":"invalid map insertion: expected value of type 'anydata', found 'ballerina/streams:StreamEvent'"}`

Full log-
`2018-12-13 10:06:56 INFO  BrokerImpl:663 - Starting message delivery threads.
2018-12-13 10:06:56 INFO  TaskExecutorService:198 - Starting task manager. Task count 0
2018-12-13 10:06:56 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154467581662183ee7e06-2ac5-438f-ad93-80432d6938c1
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina}InherentTypeViolation {"message":"invalid map insertion: expected value of type 'anydata', found 'ballerina/streams:StreamEvent'"}
	at $lambda$streaming1(streamingv2-select-test.bal:69)
	   ballerina/streams:process(simple-select.bal:33)
	   $lambda$streaming2(streamingv2-select-test.bal:68)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:188)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
2018-12-13 10:06:56 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154467581662183ee7e06-2ac5-438f-ad93-80432d6938c1
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina}InherentTypeViolation {"message":"invalid map insertion: expected value of type 'anydata', found 'ballerina/streams:StreamEvent'"}
	at $lambda$streaming1(streamingv2-select-test.bal:69)
	   ballerina/streams:process(simple-select.bal:33)
	   $lambda$streaming2(streamingv2-select-test.bal:68)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:188)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
2018-12-13 10:06:56 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154467581662183ee7e06-2ac5-438f-ad93-80432d6938c1
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina}InherentTypeViolation {"message":"invalid map insertion: expected value of type 'anydata', found 'ballerina/streams:StreamEvent'"}
	at $lambda$streaming1(streamingv2-select-test.bal:69)
	   ballerina/streams:process(simple-select.bal:33)
	   $lambda$streaming2(streamingv2-select-test.bal:68)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:188)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more`

**Affected Versions:**
ballerina 0.990.0

**Comment by LahiruJayasekara** [comment]
This was because the map access returns an anydata. So have to call the `setInvocationToRecordKeyValue()` method in streamingCodeDesugar class to cast this to the necessary type.
