### ISSUE TITLE
Non-existent window function usage throws ClassCastException

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#12747]
**Description:**
I am trying to invoke the following function.

```ballerina
function initRealtimeProductionAlert() returns () {
    // Whenever the `materialUsageStream` stream receives an event from the streaming rules defined in the `forever`
    // block, the `printMaterialUsageAlert` function is invoked.
    materialUsageStream.subscribe(printMaterialUsageAlert);


    // Gather events related to raw materials through the `rawMaterialStream` stream and production related events
    // through the `productionInputStream`. The raw materials usage and production outcome for the last
    // 10 seconds are calculated and an alert is triggered if the raw material usage is 5% higher than the
    // production outcome. This `forever` block is executed once, when initializing the service. The processing happens
    // asynchronously each time the `requestStream` or `productionInputStream` receives an event.
    forever {
        from productionInputStream window time(10000) as p
        join rawMaterialStream window time(10000) as r
        on r.name == p.name
        select r.name, sum(r.amount) as totalRawMaterial,
                sum(p.amount) as totalConsumption
        group by r.name
        having ((totalRawMaterial - totalConsumption) * 100.0 /
                totalRawMaterial) > 5
        => (MaterialUsage[] materialUsages) {
        // `materialUsages` is the output that matches the defined streaming rules. It is published to the `materialUsageStream` stream.
        // The selected clause should match the structure of the `MaterialUsage` type.
            foreach var usage in materialUsages {
                materialUsageStream.publish(usage);
            }
        }
    }
}
```

When I try to compile above code, the below error is thrown

```java
[2018-12-13 11:00:55,641] ERROR {org.ballerinalang.launcher.Main} - org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.getInvokableSymbol(StreamingCodeDesugar.java:1442)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:1345)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangWindow.accept(BLangWindow.java:48)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:1205)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangStreamingInput.accept(BLangStreamingInput.java:128)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:1022)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangJoinStreamingInput.accept(BLangJoinStreamingInput.java:93)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:262)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangStreamingQueryStatement.accept(BLangStreamingQueryStatement.java:47)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.lambda$desugar$0(StreamingCodeDesugar.java:230)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.desugar(StreamingCodeDesugar.java:230)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:582)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:51)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3234)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3241)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:208)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:171)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:133)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:318)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:134)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:281)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

```
**Affected Versions:**
0.990.1-SNAPSHOT and previous
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Fix for https://github.com/ballerina-platform/ballerina-lang/pull/12793...
