### ISSUE TITLE
NullPointer exception when trying to access method local variable inside streaming query

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#12758]
**Description:**
```
function testSelectQuery() {
    int simpleVar = 80;
    forever {
        from inputStream
        select simpleVar as simVar
        => (TeacherOutput[] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
    }
}
```
When trying to execute the above streaming query it gives a null pointer exception as follows.

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/lahiru/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/lahiru/.m2/repository/org/slf4j/slf4j-jdk14/1.7.22/slf4j-jdk14-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/lahiru/.m2/repository/org/slf4j/slf4j-simple/1.7.22/slf4j-simple-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2018-12-13 13:11:42 INFO  BrokerImpl:663 - Starting message delivery threads.
2018-12-13 13:11:42 INFO  TaskExecutorService:198 - Starting task manager. Task count 0
2018-12-13 13:11:42 ERROR BVMScheduler:75 - 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-13 13:11:42 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154468690212284204e09-7d68-4b46-b414-38c4c387e88c
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 12 more
2018-12-13 13:11:42 ERROR BVMScheduler:75 - 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-13 13:11:42 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154468690212284204e09-7d68-4b46-b414-38c4c387e88c
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 12 more
2018-12-13 13:11:42 ERROR BVMScheduler:75 - 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-13 13:11:42 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 154468690212284204e09-7d68-4b46-b414-38c4c387e88c
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2435)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 12 more
```
But if the variable declaration is outside the method like follows, it works fine.

```
int simpleVar = 80;
function testSelectQuery() {
    forever {
        from inputStream
        select simpleVar as simVar
        => (TeacherOutput[] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
    }
}
```

**Affected Versions:**
Ballerina 0.990.0 (with ballerina native streaming)

**Comment by mohanvive** [comment]
Closurevars are not getting added; that is causing the above issue.  https://github.com/ballerina-platform/ballerina-lang/issues/9353
