### ISSUE TITLE
Users should not be able to use input streams attributes in having and orderby clauses

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#12756]
**Description:**
Only the output attributes should be visible in having and orderby clauses. Using input stream's field should give a proper error saying that the input stream fields cannot be used in order by and having clauses. Even if I try to use an input stream field, I get the below error, which is wrong (exposing internal details)

```java
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:456)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:57)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:123)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.lambda$visit$3(StreamsPostSelectDesugar.java:117)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:116)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBracedOrTupleExpr.accept(BLangBracedOrTupleExpr.java:48)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:123)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:123)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.lambda$visit$3(StreamsPostSelectDesugar.java:117)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:116)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBracedOrTupleExpr.accept(BLangBracedOrTupleExpr.java:48)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:92)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.visit(StreamsPostSelectDesugar.java:123)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
	at org.wso2.ballerinalang.compiler.desugar.StreamsPostSelectDesugar.rewrite(StreamsPostSelectDesugar.java:81)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:1526)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangHaving.accept(BLangHaving.java:38)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:629)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangSelectClause.accept(BLangSelectClause.java:85)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:256)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangStreamingQueryStatement.accept(BLangStreamingQueryStatement.java:47)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.lambda$desugar$0(StreamingCodeDesugar.java:233)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.desugar(StreamingCodeDesugar.java:233)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:582)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:51)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3239)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3246)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:219)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:182)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:328)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:239)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:206)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:218)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:118)
	at org.ballerinalang.launcher.util.BServiceUtil.setupProgramFile(BServiceUtil.java:61)
	at org.ballerinalang.launcher.util.BServiceUtil.setupProgramFile(BServiceUtil.java:77)
	at org.ballerinalang.test.streaming.BallerinaStreamsV2AlertsWithServices.setup(BallerinaStreamsV2AlertsWithServices.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```
**Affected Versions:**
0.990.1-SNAPSHOT

**Comment by mohanvive** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/12870 by Gimantha.
