### ISSUE TITLE
If the output attribute alias does not match with any output record field, a NPE is thrown

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#12755]
**Description:**
Consider the following streams query. note that the select clause has `... as someField` which does not match with any attribute in output record field.

```ballerina
forever {
        from productionInputStream window timeWindow(10000) as p
        join rawMaterialStream window timeWindow(10000) as r
        on r.name == p.name
        select r.name, sum(r.amount) as someField,
        sum(p.amount) as totalConsumption
        group by r.name
        having ((totalRawMaterial - totalConsumption) * 100.0 / totalRawMaterial) > 5
        => (MaterialUsage[] materialUsages) {
        // `materialUsages` is the output that matches the defined streaming rules. It is published to the `materialUsageStream` stream.
        // The selected clause should match the structure of the `MaterialUsage` type.
            foreach var usage in materialUsages {
                materialUsageStream.publish(usage);
            }
        }
    }
```

Try to run the above code, the below exception is thrown.

```java
2018-12-13 12:45:01 INFO  ServerConnectorBootstrap$HttpServerConnector:206 - HTTP(S) Interface starting on host 9090 and port 9090
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
2018-12-13 12:45:01 ERROR BVMScheduler:75 - 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2470)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-13 12:45:01 ERROR TaskExecutorService$DefaultExceptionHandler:282 - Error occurred while processing task. Task id 1544685301020f780c306-f908-41e6-b263-6afeff33cf70
org.ballerinalang.util.exceptions.BallerinaException: Error delivering event to subscriber: 
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:181)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:89)
	at io.ballerina.messaging.broker.core.MessageDeliveryTask.call(MessageDeliveryTask.java:30)
	at io.ballerina.messaging.broker.core.task.TaskHolder.executeTask(TaskHolder.java:77)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:86)
	at io.ballerina.messaging.broker.core.task.TaskProcessor.call(TaskProcessor.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.model.values.BStream$StreamSubscriber.send(BStream.java:178)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2470)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:604)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 12 more
```
**Affected Versions:**
0.990.1-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Fix for https://github.com/ballerina-platform/ballerina-lang/pull/12822..
