### ISSUE TITLE
Using any output attribute in select clause throws ClassCastException

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#12753]
**Description:**
Consider the below query

```ballerina
forever {
        from productionInputStream window timeWindow(10000) as p
        join rawMaterialStream window timeWindow(10000) as r
        on r.name == p.name
        select name, sum(r.amount) as totalRawMaterial,
        sum(p.amount) as totalConsumption
        group by r.name
        having ((totalRawMaterial - totalConsumption) * 100.0 / totalRawMaterial) > 5
        => (MaterialUsage[] materialUsages) {
        // `materialUsages` is the output that matches the defined streaming rules. It is published to the `materialUsageStream` stream.
        // The selected clause should match the structure of the `MaterialUsage` type.
            foreach var usage in materialUsages {
                materialUsageStream.publish(usage);
            }
        }
    }
```
Lets assume by a mistake, I typed `select name ..` instead `select r.name..`. Then I try to compile and the below NPE is thrown.

```java
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess

	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.getFieldListInSelectClause(StreamingCodeDesugar.java:1685)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.addOutputObjectCreationStmt(StreamingCodeDesugar.java:818)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.createAggregatorLambdaBody(StreamingCodeDesugar.java:787)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.createAggregatorLambda(StreamingCodeDesugar.java:767)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.createSelectStatementWithGroupBy(StreamingCodeDesugar.java:652)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:634)
	at org.wso2.ballerinalang.compiler.tree.clauses.BLangSelectClause.accept(BLangSelectClause.java:85)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.visit(StreamingCodeDesugar.java:256)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangStreamingQueryStatement.accept(BLangStreamingQueryStatement.java:47)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.lambda$desugar$0(StreamingCodeDesugar.java:233)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.desugar.StreamingCodeDesugar.desugar(StreamingCodeDesugar.java:233)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:582)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:51)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3239)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3246)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:219)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:182)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:328)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:239)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:206)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:218)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:118)
	at org.ballerinalang.launcher.util.BServiceUtil.setupProgramFile(BServiceUtil.java:61)
	at org.ballerinalang.launcher.util.BServiceUtil.setupProgramFile(BServiceUtil.java:77)
	at org.ballerinalang.test.streaming.BallerinaStreamsV2AlertsWithServices.setup(BallerinaStreamsV2AlertsWithServices.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)

```
**Steps to reproduce:**

**Affected Versions:**
0.990.1-SNAPSHOT and previous

**Comment by mohanvive** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/12870 by Gimantha.
