### ISSUE TITLE
Bad. Sad. error for object's abstract init function

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#12812]
**Description:**
There is a `Bad. Sad.` error on build when an object has an abstract init function. Internal error log is as below.

```
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:840)
	at org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode.accept(BLangObjectTypeNode.java:70)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1044)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:286)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:122)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1044)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.lambda$visit$1(DataflowAnalyzer.java:252)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1044)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:235)
	at org.wso2.ballerinalang.compiler.CompilerDriver.dataflowAnalyze(CompilerDriver.java:207)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:162)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:171)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:92)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:98)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:98)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
```
There is no compilation issues for `__init` function of an object being an abstract function. 

**Steps to reproduce:**
build given sample ballerina code. 
```ballerina
type ObjectName object {
    public int a;
    public function __init();
};

function ObjectName.__init() {
    self.a = 0;
}
```

**Affected Versions:**
0.990.0

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12868
