### ISSUE TITLE
Bad sad error when there is no alias for streaming aggregate functions

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#12836]
**Description:**
```
forever {
        from inputStream
        select inputStream.name as teacherName, count()
        => (TeacherOutput[] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
    }
```
This query without alias to count aggregator gives a bad sad error.

Following is the ballerina-internal-log

```
[2018-12-18 16:56:00,051] ERROR {org.ballerinalang.launcher.Main} - org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.resolveSelectFieldName(StreamsQuerySemanticAnalyzer.java:657)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.checkOutputAttributesWithOutputConstraint(StreamsQuerySemanticAnalyzer.java:614)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.visit(StreamsQuerySemanticAnalyzer.java:189)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:48)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.analyzeNode(StreamsQuerySemanticAnalyzer.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.analyzeNode(StreamsQuerySemanticAnalyzer.java:155)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.StreamsQuerySemanticAnalyzer.analyze(StreamsQuerySemanticAnalyzer.java:147)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1692)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:48)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1683)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1650)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1646)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$32(SemanticAnalyzer.java:1009)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1009)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1683)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1650)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1646)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:277)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1683)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1650)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1642)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$4(SemanticAnalyzer.java:215)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:215)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:195)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:195)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:152)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:137)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 
```
**Affected Versions:**
Ballerina 0.990.0 (ballerina native streaming)

**Comment by mohanvive** [comment]
Fixed by Gimantha..
