### ISSUE TITLE
Function literal as closure compiles but not works

### ISSUE THREAD

**Issue by mhmxs** [ballerina-platform/ballerina-lang#12925]
**Description:**
I tried to use the following code:
```
import ballerina/io;

public function main() {
    string currency = "USD";

// Closure works :)
    var closure = function (string key) { io:println(currency); };
    closure.call("key");

    map<int> currencies = { USD: 318, EUR: 322, GBP: 400 };
// Anonyme functions works as function literal :)
    currencies.keys().foreach(function (string key) { io:println(key); });
    currencies.foreach(function ((string, int) pair) { io:println(pair); });
// But closure, which reads variable from outside of function, not :(
    currencies.foreach(function ((string, int) pair) { io:println(currency); });
}
```

The code compiles, but in runtime it fails.
```
// Closure works :)
USD
// Anonyme functions works as function literal :)
USD
EUR
GBP
("USD", 318)
("EUR", 322)
("GBP", 400)
// But closure, which reads variable from outside of function, not :(
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

The log:
```
[2018-12-21 17:08:05,510] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - 20 
java.lang.ArrayIndexOutOfBoundsException: 20
	at org.ballerinalang.bre.bvm.BVM.copyArgValues(BVM.java:958)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:852)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:433)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:168)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:160)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 
[2018-12-21 17:08:05,523] ERROR {org.ballerinalang.launcher.Main} - java.lang.ArrayIndexOutOfBoundsException: 20 
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 20
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:183)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:168)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:160)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20
	at org.ballerinalang.bre.bvm.BVM.copyArgValues(BVM.java:958)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:852)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:433)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 8 more
 ```

As 
**Steps to reproduce:**
`ballerina run test.bal`

**Affected Versions:**
Ballerina 0.990.0

**OS, DB, other environment details and versions:**
macOs Mojave 10.14.1

**Comment by pubudu91** [comment]
Unfortunately closures are not yet supported with iterable operations. Related issues: #9353, #9354, #10149, #12910
