### ISSUE TITLE
NullPointer exception when string library functions are used in ballerina native streaming querries

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#13016]
**Description:**
```
from inputStream
        select inputStream.name.toLower() as name
        => (TeacherOutput[] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
```
In the above query `toLower()` a builtin string library function is used. This gives the following error in compilation.

```
error: .::streamingv2-filter-test.bal:70:16: invalid streaming 'Aggregator' type 'toLower' found
error: .::streamingv2-filter-test.bal:70:16: undefined function 'toLower'
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

```
Internal-log is as follows-

```
[2019-01-07 11:03:41,943] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:764)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangMapLiteral.accept(BLangRecordLiteral.java:180)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:556)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:563)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:525)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.processWorker(CodeGenerator.java:1803)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visitInvokableNode(CodeGenerator.java:1742)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:513)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.lambda$visit$2(CodeGenerator.java:426)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:426)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1523)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generatePkgNode(CodeGenerator.java:377)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:366)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:227)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:187)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:137)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)

``` 

**Affected Versions:**
0.990.2

**Suggested Assignees (optional):**
@mohanvive , @gimantha , @grainier

**Comment by grainier** [comment]
Fixed in #13125
