### ISSUE TITLE
[HTTP] Connection reset by peer Exception thrown during load test

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#13014]
**Description:**
>Connection reset by peer Exception thrown during load test with KeepAlive:NEVER backend. Remote host closes the connection soon after sending the data. The connection is getting closed at the client side at RequestCompleted state. That means data is not received before the channelInactive() is called.

>Load test.
>Passthrough scenario
>Payload: 8k
>Backend echo back the payload and keepAlive config is NEVER

**Steps to reproduce:**

>Passthru_service.bal
```ballerina
import ballerina/io;
import ballerina/http;

endpoint http:Listener ep {
    port: 9090
};

endpoint http:Client clientEP {
  url: "http://localhost:9095"
};
service<http:Service> h bind ep {
    say (endpoint caller, http:Request request) {
        http:Response resp = check clientEP-> forward("/hello/sayHello", request);
        _ = caller -> respond(resp);
    }
}
```
>Backend.bal
```ballerina
import ballerina/io;
import ballerina/http;

endpoint http:Listener ep {
    port: 9095,
    keepAlive: http:KEEPALIVE_NEVER
};

service<http:Service> hello bind ep {
    sayHello (endpoint caller, http:Request request) {
        http:Response response = new;
        string payload = check request.getTextPayload();
        response.setTextPayload(untaint payload);
         _ = caller -> respond(response);
    }
}
```
>Following error is logged in the server.
```
Error at passthrough service : {ballerina/http}HTTPError {message:"Remote host closed the connection before initiating inbound response"}
```
>Following error is logged in the ballerina-internal-log.
``` 
[2018-09-09 21:31:07,625] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-09-09 21:31:07,764] ERROR {org.wso2.transport.http.netty.sender.TargetHandler} - Exception occurred in TargetHandler for channel 2816adfffe4938d3-000066fa-000003aa-a431c600b17db37d-af9099e8 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 ```

**Affected Versions:**
0.990.0

**Comment by shafreenAnfar** [comment]
This is expected with the given back-end. What happens is before client receives the FIN, client sends data which results in given error. That is why usually servers let client close the connection. 

You can reproduce the same thing. Just by doing a jmeter load test to back-end who behaves the same way.
