### ISSUE TITLE
Nested type guards on error type make the compiler crash

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#13110]
**Description:**
Nesting type guards on error and a derived type of error makes the compiler crash

**Steps to reproduce:**
````ballerina
public type HttpError error<string, record { int status = 500; }>;

function test_1(any|error e) {
    if (e is error) {
    }
}
function test_2(any|error e) {
    if (e is HttpError) {
    }
}
function test_3(any|error e) {
    if (e is error) {
        if (e is HttpError) { // <-- this makes the compiler crash
        }
    }
}

public function main() {
    // Nothing to do here
}
````
Compiling the code above produces this `ballerina-internal.log`
````
[2019-01-09 11:37:07,875] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1371)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1163)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BErrorType.accept(BErrorType.java:43)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getCastOperator(Types.java:883)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveCastOperator(SymbolResolver.java:288)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:3658)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.defineTypeGuards(Desugar.java:4484)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1429)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3239)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1430)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3239)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3229)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3246)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3189)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:219)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:182)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:74)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:176)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
````

**Affected Versions:**
0.990.2

**OS, DB, other environment details and versions:**
Windows 10

**Suggested Labels (optional):**
Type/Bug, Component/Compiler

**Comment by davebaol** [comment]
A quick update.... I think this is another situation causing the same crash
````ballerina
public type HttpError error<string, record { int status = 500; }>;

function test(error e) {
    if (e is HttpError) { // <-- this makes the compiler crash
    }
}

public function main() {
    // Nothing to do here
}
````
It seems to suggest that the issue with nested type guards on error types is in fact the effect of a more generic issue i.e. **a single type guard on a derived error type when the compiler already knows that the type is error**.
