### ISSUE TITLE
Error when trying to call library functions on aggregate functions

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#13149]
**Description:**
```
forever {
        from inputStream
        select sumInString(inputStream.age).toUpper() as count
        => (TeacherOutput [] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
    }

```
Above sumInString is a custom aggregate function which gives the sum in  string format.
This gives following error.

```
java.lang.IllegalStateException: Compilation Failed:
ERROR: .::streamingv2-aggregate-with-groupby-test.bal:84:16:: too many arguments in call to 'sumInString()'
ERROR: .::streamingv2-aggregate-with-groupby-test.bal:85:9:: fields defined in select clause, incompatible with output fields in type 'TeacherOutput', expected '[count]' but found '[count]'


	at org.ballerinalang.launcher.util.BRunUtil.invokeFunction(BRunUtil.java:210)
	at org.ballerinalang.launcher.util.BRunUtil.invoke(BRunUtil.java:196)
	at org.ballerinalang.launcher.util.BRunUtil.invoke(BRunUtil.java:267)
	at org.ballerinalang.stdlib.streams.BallerinaStreamsV2AggregatorWithGroupByTest.testSelectQuery(BallerinaStreamsV2AggregatorWithGroupByTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```
Custom aggregator - 
```
public type SumInString object {

    public int iSum = 0;
    public float fSum = 0.0;

    public function __init() {

    }

    public function process(anydata value, streams:EventType eventType) returns anydata {
        if (value is int) {
            if (eventType == "CURRENT") {
                self.iSum += value;
            } else if (eventType == "EXPIRED"){
                self.iSum -= value;
            } else if (eventType == "RESET"){
                self.iSum = 0;
            }
            return "sum is " + self.iSum;
        } else if (value is float) {
            if (eventType == "CURRENT") {
                self.fSum += value;
            } else if (eventType == "EXPIRED"){
                self.fSum -= value;
            } else if (eventType == "RESET"){
                self.fSum = 0.0;
            }
            return "sum is " + self.fSum;
        } else {
            error e = error("Unsupported attribute type found");
            panic e;
        }
    }

    public function copy() returns streams:Aggregator {
        SumInString sumAggregator = new();
        return sumAggregator;
    }
};

public function sumInString() returns streams:Aggregator {
    SumInString sumAggregator = new();
    return sumAggregator;
}
```

**Affected Versions:**
0.990.2

**Suggested Assignees (optional):**
@mohanvive , @gimantha , @grainier

**Comment by gimantha** [comment]
> @mohanvive Can you have a look on this?

we will have a look

**Comment by gimantha** [comment]
Hi all,
For now we will hold this.. This requires some grammar changes. As a workaround, you can wrap the result of the aggregator and cast it to string and call the toUpper on that. E.g. 

```ballerina
forever {
        from inputStream
        select getStringValue(sumInString(inputStream.age)) as count
        => (TeacherOutput [] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }
    }

...

function getStringValue(anydata value) returns string {
    string str = <string> value;
    return str.toUpper()
}

```
