### ISSUE TITLE
Adding a value at the maximum allowed index causes an OOM

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13159]
Consider the following program:
```ballerina
public function main(string... args) {
    int[] a = [];
    a[2147483647-9] = 10; 
}
```
The above program causes an out of memory error. 
```
[2019-01-12 01:05:10,301] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - Java heap space 
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at org.ballerinalang.model.values.BValueArray.grow(BValueArray.java:513)
	at org.ballerinalang.model.values.BNewArray.ensureCapacity(BNewArray.java:122)
	at org.ballerinalang.model.values.BNewArray.prepareForAdd(BNewArray.java:82)
	at org.ballerinalang.model.values.BValueArray.add(BValueArray.java:210)
	at org.ballerinalang.bre.bvm.BVM.execStoreOpcodes(BVM.java:1769)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:330)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at org.ballerinalang.launcher.Main$$Lambda$8/1510067370.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 
[2019-01-12 01:05:10,317] ERROR {org.ballerinalang.launcher.Main} - java.lang.OutOfMemoryError: Java heap space 
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at org.ballerinalang.model.values.BValueArray.grow(BValueArray.java:513)
	at org.ballerinalang.model.values.BNewArray.ensureCapacity(BNewArray.java:122)
	at org.ballerinalang.model.values.BNewArray.prepareForAdd(BNewArray.java:82)
	at org.ballerinalang.model.values.BValueArray.add(BValueArray.java:210)
	at org.ballerinalang.bre.bvm.BVM.execStoreOpcodes(BVM.java:1769)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:330)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at org.ballerinalang.launcher.Main$$Lambda$8/1510067370.accept(Unknown Source)
	... 2 more
```

**Comment by Nadeeshan96** [comment]
This `OutOfMemoryError` comes even when the same is written in java. For example see the following cases and their outputs written as comments.
```
int[] arr = new int[2147483648]; // cannot compile 
int[] arr = new int[2147483647]; //can compile, but gives a runtime error - Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
The above needs 8 GB for int array, and 16 GB for long array.
int[] arr = new int[2147483647-10]; or int[] arr = new int[2147483637]; //although these can be compiled, it gives a runtime error - Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
int[] arr = new int[2147483647-2000000000]; // this can be compiled and run
```
In the ballerina language the following cases can be seen.
```
int[] a = [];
a[2147483647-9] = 10; // cannot compile , if this is written in this way,  a[2147483638] = 10; can be compiled.
a[2147483647] = 10; //error: {ballerina/lang.array}IndexOutOfRange {"message":"array index out of range: index: 2,147,483,647, size: 0"} //here the java error doesn’t come because there is a check to compare with 2147483639, the maxSize of an array and it throws this
a[2147483637] = 20; //SEVERE {b7a.log.crash} - Java heap space java.lang.OutOfMemoryError: Java heap space // the case in the issue.
a[147483637] = 20; //can be compiled and run
```
