### ISSUE TITLE
Maximum value of array indices are limited to 2,147,483,647

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13156]
In the current array implementation, the maximum no. of elements that can be indexed is 2,147,483,647 which is the max positive value of 32-bit signed integers. Since we are using 64-bit integers in Ballerina, ideally the array indices shouldn't be limited to 2,147,483,647.

**Comment by 13Ax0** [comment]
I don't know how to fix this, I just want to understand what's happening.

This piece of code works:

```ballerina
public function main() {
    int[2147483647] a;
}
```

And this piece of code fails:

```ballerina
public function main() {
    int[2147483648] a;
}
```

Producing the following error message and log file:

Error message:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

Log file (ballerina-internal.log):
```
[2019-01-11 15:53:34,153] ERROR {org.ballerinalang.launcher.Main} - For input string: "2147483648" 
java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitArrayTypeNameLabel(BLangParserListener.java:644)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ArrayTypeNameLabelContext.exitRule(BallerinaParser.java:3038)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:491)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:126)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:434)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:304)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:112)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 ```

Is this correct?

**Comment by pubudu91** [comment]
Ah this should not have happened! The issue is, when trying to parse the array size `2147483648`, `Integer.parseInt()` is used instead of `Long.parseLong()`. This is a separate issue. Can you open one for this?

**Comment by 13Ax0** [comment]
Of course. Thanks for explaining.

**Comment by Kishanthan** [comment]
The first issue mentioned is a limitation with jBallerina as array size uses java int underneath.

**Comment by Nadeeshan96** [comment]
The current maximum Ballerina array size is `2147483637`. When an array with larger size than that is defined, a proper compilation error is given.
```bal
public function main() {
    int[2147483638] a;
}
```
gives
```
Compiling source
        array.bal
ERROR [array.bal:(2:9,2:19)] array length greater that '2147483637' not yet supported
error: compilation contains errors
```
Larger array sizes cannot be supported because jBallerina uses java arrays underneath which have a maximum size of `2147483647`. Hence closing the issue. Please reopen if you have further queries.
