### ISSUE TITLE
Compiler crash on build command

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#13394]
**Description:**
An empty main like that
````ballerina
public function main() {
}
````
is enough to make the compiler crash on `ballerina build`
````
> ballerina build
Compiling source
    main.bal
Generating executables
    ./target/main.balx
        @awslambda:Function:
ballerina: Oh no, something really went wrong. Bad. Sad.

blah blah blah....
````
This is the generated `ballerina-internal.log`
````
[2019-01-29 14:20:19,245] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 51: jar:file:/C:/devel/ballerina_test/target/\aws-ballerina-lambda-functions.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 51: jar:file:/C:/devel/ballerina_test/target/\aws-ballerina-lambda-functions.zip
	at java.net.URI.create(Unknown Source)
	at org.ballerinax.awslambda.AWSLambdaPlugin.generateZipFile(AWSLambdaPlugin.java:330)
	at org.ballerinax.awslambda.AWSLambdaPlugin.codeGenerated(AWSLambdaPlugin.java:309)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.lambda$writeExecutableBinary$0(BinaryFileWriter.java:121)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeExecutableBinary(BinaryFileWriter.java:120)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeExecutableBinary(BinaryFileWriter.java:102)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:86)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.write(Compiler.java:111)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:111)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:98)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 51: jar:file:/C:/devel/ballerina_test/target/\aws-ballerina-lambda-functions.zip
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	... 14 more
````
 
**Affected Versions:**
0.990.3-SNAPSHOT (Jan 28, 2019)

**OS, DB, other environment details and versions:**
Windows 10

**Suggested Labels (optional):**
Type/Bug, Component/Compiler

**Comment by Shan1024** [comment]
I think this issue should get fixed by https://github.com/ballerinax/awslambda/pull/5.

@lafernando might be able to provide more insight into this.

**Comment by lafernando** [comment]
@Shan1024 ballerinax/awslambda#5 is not related to this. It seems to be a path issue in Windows. I've sent a possible fix with https://github.com/ballerinax/awslambda/pull/6. I can't personally verify this in Windows, but it should most probably fix the problem.

**Comment by lafernando** [comment]
Thanks, that would be great!. This will come with the upcoming RC2.

**Comment by davebaol** [comment]
Build command works with Nightly 0.990.3-SNAPSHOT (Feb 01, 2019).
Not sure if this is the aforementioned RC2.
Closing this issue, anyways.

**Comment by lafernando** [comment]
Thanks @davebaol for the verification.
