### ISSUE TITLE
Bad. Sad. error on `is` check as `future`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#13423]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main(string... args) {
    any a = 1;
    if (a is future<int>) {
        // 
    }
}
```

```cmd
$ ballerina run test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.
...
```

The `ballerina-internal.log` contains:
```
[2019-01-31 10:55:27,752] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:1387)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:62)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:557)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:564)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:525)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:2714)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:66)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:525)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.processWorker(CodeGenerator.java:1810)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visitInvokableNode(CodeGenerator.java:1749)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:513)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.lambda$visit$2(CodeGenerator.java:426)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:426)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1530)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generatePkgNode(CodeGenerator.java:377)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:366)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:227)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:187)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:144)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:112)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
```

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT

**Comment by MaryamZi** [comment]
This is now fixed on master.
