### ISSUE TITLE
WebSubContentTypeSupportTestCase fails intermittently

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#13499]
**Description:**
```
[ERROR] Tests run: 419, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 856.401 s <<< FAILURE! - in TestSuite
[ERROR] testAuthenticatedTextContentReceiptForInternalHub(org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase)  Time elapsed: 45.018 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriber: Text update for internal Hub
	at org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase.testAuthenticatedTextContentReceiptForInternalHub(WebSubContentTypeSupportTestCase.java:160)

[ERROR] testUnauthenticatedTextContentReceiptForInternalHub(org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase)  Time elapsed: 45.003 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriberTwo: Text update for internal Hub
	at org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase.testUnauthenticatedTextContentReceiptForInternalHub(WebSubContentTypeSupportTestCase.java:170)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   WebSubContentTypeSupportTestCase.testAuthenticatedTextContentReceiptForInternalHub:160 Â» BallerinaTest
[ERROR]   WebSubContentTypeSupportTestCase.testUnauthenticatedTextContentReceiptForInternalHub:170 Â» BallerinaTest
[INFO] 
[ERROR] Tests run: 419, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by shafreenAnfar** [comment]
This still fails intermittently. I have attache.d the log file.

[rhwdbvrw5uxtu-console-log.txt](https://github.com/ballerina-platform/ballerina-lang/files/4762780/rhwdbvrw5uxtu-console-log.txt)

**Comment by Bhashinee** [comment]
Closing the issue as these tests are rewritten.
