### ISSUE TITLE
[IDEA] Issue in signature helper

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13527]
**Description:**
```
java.lang.sendMessageResponse: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$signatureHelp$1(EditorEventManager.scala:207)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$signatureHelp$1(EditorEventManager.scala:207)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NipunaRanasinghe** [comment]
@Shan1024 Could you please provide a code sample which can be used to reproduce the issue?

**Comment by Shan1024** [comment]
@NipunaRanasinghe - Unfortunately any code examples are not available. Since one of the error is `IndexOutOfBoundsException`, the fix should be straight forward and might get an idea about how to reproduce it.
