### ISSUE TITLE
NPE in BVM

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13671]
**Description:**
```
[2019-02-16 04:37:51,993] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : Participant2pcService with context /balcoordinator/participant/2pc  
[2019-02-16 04:37:51,997] INFO [org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector] - HTTP(S) Interface starting on host 35817 and port 35817  
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:35817
[2019-02-16 04:37:51,998] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : InitiatorService with context /balcoordinator/initiator  
2019-02-16 04:37:51,999 INFO [ballerina/transactions] - Created transaction: 86f82bdc-d948-468a-838f-e924a45d0a43 
2019-02-16 04:37:51,999 INFO [ballerina/transactions] - Running 2-phase commit for transaction: 86f82bdc-d948-468a-838f-e924a45d0a43:$anon$.$6 
[2019-02-16 04:37:52,000] INFO [org.ballerinalang.util.transactions.TransactionResourceManager] - Transaction prepare (participants): success  
    byte-value-runtime-negative.bal
    byte-shift-operators-negative.bal
    byte-value-negative.bal
    record-variable-reference.bal
    record-variable-reference-negative.bal
    transaction_stmt.bal
    transaction_stmt_negative.bal
[2019-02-16 04:37:53,279] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : Participant2pcService with context /balcoordinator/participant/2pc  
[2019-02-16 04:37:53,282] INFO [org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector] - HTTP(S) Interface starting on host 33445 and port 33445  
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:33445
[2019-02-16 04:37:53,283] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : InitiatorService with context /balcoordinator/initiator  
2019-02-16 04:37:53,283 INFO [ballerina/transactions] - Created transaction: 94bd0b6d-8dd2-40f5-92c2-99d25b6b241b 
2019-02-16 04:37:53,284 INFO [ballerina/transactions] - Created transaction: 0a3cc8bb-6ca5-4f94-be3f-b0e010d06b30 
2019-02-16 04:37:53,284 INFO [ballerina/transactions] - Marked initiated transaction for abortion 
2019-02-16 04:37:53,285 INFO [ballerina/transactions] - Created transaction: 765d6cfc-c2f8-4787-9c85-54d0c16d940a 
2019-02-16 04:37:53,285 INFO [ballerina/transactions] - Running 2-phase commit for transaction: 765d6cfc-c2f8-4787-9c85-54d0c16d940a:$anon$.$13 
[2019-02-16 04:37:53,285] INFO [org.ballerinalang.util.transactions.TransactionResourceManager] - Transaction prepare (participants): success  
[2019-02-16 04:37:53,287] ERROR [org.ballerinalang.bre.bvm.BVMScheduler] - null 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2499)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:605)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.stdlib.task.TaskExecutor.execute(TaskExecutor.java:51)
	at org.ballerinalang.stdlib.task.timer.Timer.callTriggerFunction(Timer.java:75)
	at org.ballerinalang.stdlib.task.timer.Timer.lambda$new$0(Timer.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 
[2019-02-16 04:37:53,291] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : Participant2pcService with context /balcoordinator/participant/2pc  
[2019-02-16 04:37:53,295] INFO [org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector] - HTTP(S) Interface starting on host 33573 and port 33573  
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:33573
[2019-02-16 04:37:53,296] INFO [org.ballerinalang.net.http.HTTPServicesRegistry] - Service deployed : InitiatorService with context /balcoordinator/initiator  
2019-02-16 04:37:53,297 INFO [ballerina/transactions] - Created transaction: 19960361-377c-417d-af50-7a6b4fa5771e 
2019-02-16 04:37:53,297 INFO [ballerina/transactions] - Created transaction: b278d903-6190-4ecc-872a-3e33b11d91de 
2019-02-16 04:37:53,298 INFO [ballerina/transactions] - Marked initiated transaction for abortion 
2019-02-16 04:39:54,280 INFO [ballerina/transactions] - Running 2-phase commit for transaction: 19960361-377c-417d-af50-7a6b4fa5771e:$anon$.$11 
[2019-02-16 04:39:54,281] INFO [org.ballerinalang.util.transactions.TransactionResourceManager] - Transaction prepare (participants): success  
2019-02-16 04:39:54,281 INFO [ballerina/transactions] - Auto-committed initiated transaction: 19960361-377c-417d-af50-7a6b4fa5771e. Result: committed 
```

**Comment by pubudu91** [comment]
This is a unit test right? We can try and identify in which test this is happening by running the tests with the following line uncommented: https://github.com/ballerina-platform/ballerina-lang/blob/2a27fa2ba8178911a88b0e6b9cef1661a68546fc/tests/ballerina-unit-test/src/test/resources/testng.xml#L26

**Comment by Shan1024** [comment]
A similar issue occurred again in another build. 

Complete log - [Log-NPE-BVM.txt](https://github.com/ballerina-platform/ballerina-lang/files/3012978/Log-NPE-BVM.txt).
