### ISSUE TITLE
VSCode module fails with an error in maven exec plugin on windows

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#13715]
**Description:**
$Subject observed in appveryor build.

```bash
main:
27238[INFO] Executed tasks
27239[INFO] 
27240[INFO] --- maven-javadoc-plugin:3.0.1:jar (attach-javadocs) @ plugin-vscode ---
27241[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
27242[INFO] 
27243[INFO] --- exec-maven-plugin:1.6.0:exec (vsix-package) @ plugin-vscode ---
27244
27245> ballerina@0.990.4 package C:\projects\ballerina-lang\tool-plugins\vscode
27246> vsce package "--out" "target/ballerina-vscode-plugin-0.990.4-SNAPSHOT.vsix"
27247
27248 ERROR  You should not depend on 'vscode' in your 'dependencies'. Did you mean to add it to 'devDependencies'?
27249npm ERR! code ELIFECYCLE
27250npm ERR! errno 1
27251npm ERR! ballerina@0.990.4 package: `vsce package "--out" "target/ballerina-vscode-plugin-0.990.4-SNAPSHOT.vsix"`
27252npm ERR! Exit status 1
27253npm ERR! 
27254npm ERR! Failed at the ballerina@0.990.4 package script.
27255npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
27256
27257npm ERR! A complete log of this run can be found in:
27258npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2019-02-18T15_56_02_448Z-debug.log
27259[ERROR] Command execution failed.
27260org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
27261	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
27262	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
27263	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
27264	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
27265	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
27266	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
27267	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
27268	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
27269	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
27270	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
27271	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
27272	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
27273	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
27274	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
27275	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
27276	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
27277	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
27278	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
27279	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
27280	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
27281	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
27282	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27283	at java.lang.reflect.Method.invoke(Method.java:498)
27284	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
27285	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
27286	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
27287	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
27288[INFO] ------------------------------------------------------------------------
27289[INFO] Reactor Summary:
27290
```

Please find the attached log.
[vscode-failure.txt](https://github.com/ballerina-platform/ballerina-lang/files/2883190/vscode-failure.txt)

**Comment by kaviththiranga** [comment]
@manuri, are you getting this with the latest HEAD?
There was an issue due to dependabot changes and we fixed it in https://github.com/ballerina-platform/ballerina-lang/pull/13700

**Comment by Manuri** [comment]
I will re-trigger this. This was triggered on 18th. I supposed the fix was added later.
