### ISSUE TITLE
Intermittent issue - java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13854]
**Description:**
```
[2019-02-22 12:44:49,997] ERROR [org.ballerinalang.bre.bvm.BVMScheduler] - Task java.util.concurrent.FutureTask@7b58fcdf rejected from java.util.concurrent.ThreadPoolExecutor@3784a4df[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34279] 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7b58fcdf rejected from java.util.concurrent.ThreadPoolExecutor@3784a4df[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34279]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.ballerinalang.bre.bvm.BVMScheduler.schedule(BVMScheduler.java:62)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:938)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:1253)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:535)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.stdlib.task.TaskExecutor.execute(TaskExecutor.java:51)
	at org.ballerinalang.stdlib.task.timer.Timer.callTriggerFunction(Timer.java:75)
	at org.ballerinalang.stdlib.task.timer.Timer.lambda$new$0(Timer.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by MaryamZi** [comment]
Did this fail on Jenkins or Travis? And when?

Was it after https://github.com/ballerina-platform/ballerina-lang/pull/13783 was merged?

**Comment by Shan1024** [comment]
This failed in both Jenkins and Travis earlier.

Now it failed in Travis. I don't think #13783 changes were in the PR. I'll merge the master and see if this fail again.

**Comment by MaryamZi** [comment]
Can we close this now? IINM, we haven't observed this failure after #13783 was merged.

**Comment by Shan1024** [comment]
Haven't observed this recently. Will reopen if needed.
