### ISSUE TITLE
BVM crashes when assigning function pointer with function which returns sub type

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#13881]
**Description:**

```
function bar() returns string {
     return "12";
}

function alpha() {
    function () returns any ff = bar;
    any s = ff.call();
}

```

Following error can be seen in the log.

[2019-02-25 11:57:58,729] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - null
java.lang.NullPointerException
        at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:714)
        at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
        at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
        at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
        at org.ballerinalang.BLangProgramRunner.runMainFunc(BLangProgramRunner.java:75)
        at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:160)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:267)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:63)

[2019-02-25 11:57:58,752] ERROR {org.ballerinalang.launcher.Main} - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
        at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
        at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
        at org.ballerinalang.BLangProgramRunner.runMainFunc(BLangProgramRunner.java:75)
        at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:160)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:267)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:63)
Caused by: java.lang.NullPointerException
        at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:714)
        at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
        ... 8 more

**Comment by Kishanthan** [comment]
This is a different issue in jBallerina where function sub typing is not supported.

```ballerina
public function main(string... args) {
   alpha();
}

function bar() returns string {
     return "12";
}

function alpha() {
    function () returns any ff = bar;
    any s = ff();
}
```
