### ISSUE TITLE
Intermittent failure - port not open issue

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#14734]
**Description:**
```
[ERROR] Tests run: 530, Failures: 24, Errors: 0, Skipped: 489, Time elapsed: 2,195.003 s <<< FAILURE! - in TestSuite
[ERROR] start(org.ballerinalang.test.service.http.HttpBaseTest)  Time elapsed: 122.764 s  <<< FAILURE!
java.lang.RuntimeException: Port '7000' is not open
	at org.ballerinalang.test.service.http.HttpBaseTest.start(HttpBaseTest.java:49)

[ERROR] start(org.ballerinalang.test.service.resiliency.HttpResiliencyTest)  Time elapsed: 243.212 s  <<< FAILURE!
java.lang.RuntimeException: Port '7001' is not open
	at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.start(HttpResiliencyTest.java:76)

[ERROR] cleanup(org.ballerinalang.test.service.resiliency.HttpResiliencyTest)  Time elapsed: 243.318 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
	at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.cleanup(HttpResiliencyTest.java:410)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.cleanup(HttpResiliencyTest.java:410)

[ERROR] setup(org.ballerinalang.test.channel.ChannelsResourcesTest)  Time elapsed: 364.433 s  <<< FAILURE!
java.lang.RuntimeException: Port '7002' is not open
	at org.ballerinalang.test.channel.ChannelsResourcesTest.setup(ChannelsResourcesTest.java:52)

[ERROR] testTransactionRollbackOnCancelledFuture(org.ballerinalang.test.future.CancelledFuturesWithTrxTest)  Time elapsed: 1.193 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Matching log not found prior to server shutdown for: Marked initiated transaction for abortion
	at org.ballerinalang.test.future.CancelledFuturesWithTrxTest.testTransactionRollbackOnCancelledFuture(CancelledFuturesWithTrxTest.java:58)

[ERROR] start(org.ballerinalang.test.service.http2.Http2BaseTest)  Time elapsed: 121.273 s  <<< FAILURE!
java.lang.RuntimeException: Port '7003' is not open
	at org.ballerinalang.test.service.http2.Http2BaseTest.start(Http2BaseTest.java:44)

[ERROR] start(org.ballerinalang.test.auth.AuthBaseTest)  Time elapsed: 248.554 s  <<< FAILURE!
java.lang.RuntimeException: Port '7004' is not open
	at org.ballerinalang.test.auth.AuthBaseTest.start(AuthBaseTest.java:49)

[ERROR] start(org.ballerinalang.test.filter.FilterTestCommons)  Time elapsed: 368.705 s  <<< FAILURE!
java.lang.RuntimeException: Port '7005' is not open
	at org.ballerinalang.test.filter.FilterTestCommons.start(FilterTestCommons.java:46)

[ERROR] start(org.ballerinalang.test.transaction.MicroTransactionTestCase)  Time elapsed: 488.869 s  <<< FAILURE!
java.lang.RuntimeException: Port '7006' is not open
	at org.ballerinalang.test.transaction.MicroTransactionTestCase.start(MicroTransactionTestCase.java:65)

[ERROR] stop(org.ballerinalang.test.transaction.MicroTransactionTestCase)  Time elapsed: 488.878 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
	at org.ballerinalang.test.transaction.MicroTransactionTestCase.stop(MicroTransactionTestCase.java:71)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.ballerinalang.test.transaction.MicroTransactionTestCase.stop(MicroTransactionTestCase.java:71)

[ERROR] start(org.ballerinalang.test.transaction.RemoteParticipantTransactionTest)  Time elapsed: 608.959 s  <<< FAILURE!
java.lang.RuntimeException: Port '7007' is not open
	at org.ballerinalang.test.transaction.RemoteParticipantTransactionTest.start(RemoteParticipantTransactionTest.java:59)

[ERROR] stop(org.ballerinalang.test.transaction.RemoteParticipantTransactionTest)  Time elapsed: 608.965 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
	at org.ballerinalang.test.transaction.RemoteParticipantTransactionTest.stop(RemoteParticipantTransactionTest.java:73)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.ballerinalang.test.transaction.RemoteParticipantTransactionTest.stop(RemoteParticipantTransactionTest.java:73)

[ERROR] start(org.ballerinalang.test.service.websocket.WebSocketTestCommons)  Time elapsed: 729.097 s  <<< FAILURE!
java.lang.RuntimeException: Port '7008' is not open
	at org.ballerinalang.test.service.websocket.WebSocketTestCommons.start(WebSocketTestCommons.java:52)

[ERROR] start(org.ballerinalang.test.service.grpc.sample.GrpcBaseTest)  Time elapsed: 849.259 s  <<< FAILURE!
java.lang.RuntimeException: Port '7009' is not open
	at org.ballerinalang.test.service.grpc.sample.GrpcBaseTest.start(GrpcBaseTest.java:51)

[ERROR] setup(org.ballerinalang.test.observability.tracing.TracingTestCase)  Time elapsed: 120.15 s  <<< FAILURE!
java.lang.RuntimeException: Port '7010' is not open
	at org.ballerinalang.test.observability.tracing.TracingTestCase.setup(TracingTestCase.java:77)

[ERROR] setup(org.ballerinalang.test.security.HTTPResponseXMLSecurityTestCase)  Time elapsed: 240.253 s  <<< FAILURE!
java.lang.RuntimeException: Port '7011' is not open
	at org.ballerinalang.test.security.HTTPResponseXMLSecurityTestCase.setup(HTTPResponseXMLSecurityTestCase.java:50)

[ERROR] cleanup(org.ballerinalang.test.security.HTTPResponseXMLSecurityTestCase)  Time elapsed: 240.256 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
	at org.ballerinalang.test.security.HTTPResponseXMLSecurityTestCase.cleanup(HTTPResponseXMLSecurityTestCase.java:56)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.ballerinalang.test.security.HTTPResponseXMLSecurityTestCase.cleanup(HTTPResponseXMLSecurityTestCase.java:56)

[ERROR] setup(org.ballerinalang.test.service.websub.basic.WebSubServiceExtensionTestCase)  Time elapsed: 360.342 s  <<< FAILURE!
java.lang.RuntimeException: Port '7012' is not open
	at org.ballerinalang.test.service.websub.basic.WebSubServiceExtensionTestCase.setup(WebSubServiceExtensionTestCase.java:100)

[ERROR] init(org.ballerinalang.test.service.websub.basic.WebSubBaseTest)  Time elapsed: 480.414 s  <<< FAILURE!
java.lang.RuntimeException: Port '7013' is not open
	at org.ballerinalang.test.service.websub.basic.WebSubBaseTest.init(WebSubBaseTest.java:42)

[ERROR] init(org.ballerinalang.test.service.websub.advanced.WebSubAdvancedBaseTest)  Time elapsed: 600.559 s  <<< FAILURE!
java.lang.RuntimeException: Port '7014' is not open
	at org.ballerinalang.test.service.websub.advanced.WebSubAdvancedBaseTest.init(WebSubAdvancedBaseTest.java:46)

[ERROR] setup(org.ballerinalang.test.data.streaming.TableToXMLStreamingTestCase)  Time elapsed: 726.008 s  <<< FAILURE!
java.lang.RuntimeException: Port '7015' is not open
	at org.ballerinalang.test.data.streaming.TableToXMLStreamingTestCase.setup(TableToXMLStreamingTestCase.java:64)

[ERROR] cleanup(org.ballerinalang.test.data.streaming.TableToXMLStreamingTestCase)  Time elapsed: 726.014 s  <<< FAILURE!
org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
	at org.ballerinalang.test.data.streaming.TableToXMLStreamingTestCase.cleanup(TableToXMLStreamingTestCase.java:95)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.ballerinalang.test.data.streaming.TableToXMLStreamingTestCase.cleanup(TableToXMLStreamingTestCase.java:95)

[ERROR] start(org.ballerinalang.test.socket.SocketBaseTest)  Time elapsed: 846.111 s  <<< FAILURE!
java.lang.RuntimeException: Port '7016' is not open
	at org.ballerinalang.test.socket.SocketBaseTest.start(SocketBaseTest.java:57)

[ERROR] start(org.ballerinalang.test.messaging.artemis.ArtemisTestCommons)  Time elapsed: 969.014 s  <<< FAILURE!
java.lang.RuntimeException: Port '7017' is not open
	at org.ballerinalang.test.messaging.artemis.ArtemisTestCommons.start(ArtemisTestCommons.java:61)
```

Complete log - [port-not-open.txt](https://github.com/ballerina-platform/ballerina-lang/files/3012493/port-not-open.txt)

**Comment by wggihan** [comment]
These test failures are not related to StdLibs. Mainly this cause due to a single test fails and the rest of the test gets affected due to current test framework implementation.
