### ISSUE TITLE
Intermittent test failures in HttpStatusCodeTest

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#14809]
**Description:**
in HttpStatusCodeTest there are two test cases are failing intermittently in Travis.... 

Test cases
```
[ERROR]org.ballerinalang.test.service.resiliency.HttpResiliencyTest.httpStatusCodesTest(org.ballerinalang.test.service.resiliency.HttpResiliencyTest)

[ERROR] Run 1: HttpResiliencyTest.httpStatusCodesTest:254->verifyResponses:403 Response code mismatched expected [503] but found [500]

[ERROR] Run 2: HttpResiliencyTest.httpStatusCodesTest:254->verifyResponses:403 Response code mismatched expected [503] but found [500]
```

Log
```
[ERROR] httpStatusCodesTest(org.ballerinalang.test.service.resiliency.HttpResiliencyTest) Time elapsed: 1.216 s <<< FAILURE! java.lang.AssertionError: Response code mismatched expected [503] but found [500] at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.verifyResponses(HttpResiliencyTest.java:403) at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.httpStatusCodesTest(HttpResiliencyTest.java:254) 

[ERROR] httpStatusCodesTest(org.ballerinalang.test.service.resiliency.HttpResiliencyTest) Time elapsed: 0.019 s <<< FAILURE! java.lang.AssertionError: Response code mismatched expected [503] but found [500] at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.verifyResponses(HttpResiliencyTest.java:403) at org.ballerinalang.test.service.resiliency.HttpResiliencyTest.httpStatusCodesTest(HttpResiliencyTest.java:254)
``` 

**OS, DB, other environment details and versions:**

* Next-Release branch

**Comment by chamil321** [comment]
Similar test failure log : [resiliencyTypicalBackend.txt](https://github.com/ballerina-platform/ballerina-lang/files/3027040/resiliencyTypicalBackend.txt)

**Comment by chamil321** [comment]
This issue occurred due to a change in HTTP transport (https://github.com/wso2/transport-http/commit/740022a0ca856353b174e70e4b97a549c81276a0). Later we reverted the change. Hence closing this issue as it is no longer valid.
