### ISSUE TITLE
Parser crashing with EmptyStackException

### ISSUE THREAD

**Issue by Flakesz** [ballerina-platform/ballerina-lang#15031]
**Description:**
BallerinaParser is crashing while trying to parse an import from the same module. The attached zip contains a minimal project to reproduce and the `ballerina-internal.log` in case it cannot be reproduced.

```
ERROR {org.ballerinalang.launcher.Main} - null 
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.addExpressionStmt(BLangPackageBuilder.java:2590)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitExpressionStmt(BLangParserListener.java:1827)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ExpressionStmtContext.exitRule(BallerinaParser.java:9308)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
...
```

**Steps to reproduce:**
Attached minimal project to reproduce, just run `ballerina run main.bal`.

**Affected Versions:** 0.990.3

**OS, DB, other environment details and versions:** Ubuntu 18.04
[bal_crash_proj.zip](https://github.com/ballerina-platform/ballerina-lang/files/3076770/bal_crash_proj.zip)

**Comment by Shan1024** [comment]
Similar issue https://github.com/ballerina-platform/ballerina-lang/issues/4878.
