### ISSUE TITLE
NPE when try to access fields via table variable

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#15329]
**Description:**

NPE when try to access fields via table

**Steps to reproduce:**

**Sample code:**

```ballerina
import ballerina/io;

type Employee record {
    int id;
    string name;
    float salary;
};

public function main() {
    table<Employee> tbEmployee = table {
        { key id, name, salary },
        [ { 1, "Mary",  300.5 },
          { 2, "John",  200.5 },
          { 3, "Jim", 330.5 }
        ]
    };
    
    foreach var emp in tbEmployee {
        //Instead of io:println(emp.id); following line is used. It gives the error
        io:println(tbEmployee.id); 
    }
    
}
```
**Output:**
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

```

**Internal log file:**

```
[2019-05-16 19:41:55,566] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:462)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:57)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:1326)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:62)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:698)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangArrayLiteral.accept(BLangArrayLiteral.java:45)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getFuncOperands(CodeGenerator.java:1952)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getFuncOperands(CodeGenerator.java:1915)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:1253)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:112)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:3244)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:527)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:2661)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:527)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:2676)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangWhile.accept(BLangWhile.java:65)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:527)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:527)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.processWorker(CodeGenerator.java:1735)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visitInvokableNode(CodeGenerator.java:1674)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:515)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.lambda$visit$2(CodeGenerator.java:428)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:428)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1457)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generatePkgNode(CodeGenerator.java:379)
	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:368)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:233)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:193)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:150)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:107)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:189)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:194)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:77)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:303)
	at org.ballerinalang.launcher.LauncherUtils.runBal(LauncherUtils.java:384)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:106)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:267)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:63)
 
```
**Affected Versions:**

0.991.0

**Comment by grainier** [comment]
Fixed and now result in;
- `io:println(tbEmployee["id"]); `: invalid operation: type 'table<grainier/test:0.1.0:Employee>' does not support indexing

- `io:println(tbEmployee.id); `: invalid operation: type 'table<grainier/test:0.1.0:Employee>' does not support field access

- `io:println(tbEmployee?.id); `: invalid operation: type 'table<grainier/test:0.1.0:Employee>' does not support optional field access
