### ISSUE TITLE
Error when casting filtered array

### ISSUE THREAD

**Issue by danielrearden** [ballerina-platform/ballerina-lang#15405]
**Description:**
Code fails to compile when I explicitly cast the results calling filter on an array of a union type.

```
[2019-05-23 20:40:48,534] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.semantics.model.types.BTypeVisitor.visit(BTypeVisitor.java:67)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BIntermediateCollectionType.accept(BIntermediateCollectionType.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:202)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:528)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:366)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeCastOperator(Types.java:988)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeCastOperator(SymbolResolver.java:291)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:1887)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:62)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:210)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1970)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1935)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1927)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1214)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1970)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1935)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1931)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$34(SemanticAnalyzer.java:1202)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1202)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1970)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1935)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1931)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:285)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1970)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1935)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1927)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$4(SemanticAnalyzer.java:223)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:223)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:203)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:201)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:158)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:150)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:107)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:189)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:194)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:77)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:303)
	at org.ballerinalang.launcher.LauncherUtils.compileModule(LauncherUtils.java:445)
	at org.ballerinalang.launcher.LauncherUtils.runBal(LauncherUtils.java:387)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:106)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:267)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:63)
```

**Steps to reproduce:**

Minimal code to reproduce:

```
type Foo record {|
  string foo;
|};
type Bar record {|
  string bar;
|};
type FooBar Foo | Bar;

function doSomething() {
  FooBar?[] foobars = [];
  Foo[] foos = <Foo[]> foobars.filter(function (FooBar foobar) returns boolean {
    return foobar is Foo;
  });
}
```

Current workaround:

```
  FooBar[] result = foobars.filter(function (FooBar foobar) returns boolean {
    return foobar is Foo;
  });
  Foo[] foos = <FooBar[]> result;
```

**Affected Versions:**
0.991.0

**OS, DB, other environment details and versions:**
macOS 10.14.5

**Comment by pubudu91** [comment]
Tried the following example on master.
```ballerina
import ballerina/io;

type Foo record {|
    string foo;
|};

type Bar record {|
    string bar;
|};

type FooBar Foo|Bar;

public function main() {
    FooBar?[] foobars = [{foo: "F1"}, {foo: "F2"}, {bar: "Bar"}];
    
    Foo[] foos = <Foo[]> foobars.filter(function (FooBar? foobar) returns boolean {
        return foobar is Foo;
    }).cloneReadOnly();

    io:println(foos);
}
```
This prints
```
foo=F1 foo=F2
```
Note the call to `cloneReadOnly()`. If the array is not immutable, the cast would fail at run time since the returned array may later be modified to by adding `Bar` records as well.
