### ISSUE TITLE
Record values cannot be initialized as a global variable in JBallerina

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#15433]
Consider the below code

```ballerina
type Employee record {
    int id = 0;
    string name = "";
};
Employee globalEmployee = {};

function testGlobalStream() returns int {
    return 4;
}
```
Compiling and running the above code using JBallerina backend throws the below exception.

```java
java.lang.RuntimeException: Error while invoking function '___init_'
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:580)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:548)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:590)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:132)
        at org.ballerinalang.test.types.stream.BStreamValueTest2.setup(BStreamValueTest2.java:38)

        Caused by:
        java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:578)
            ... 4 more

            Caused by:
            java.lang.NoSuchFieldError: #0
                at ___init.___init_(.:12)
                ... 9 more

```

Note that if we remove the line "`Employee globalEmployee = {};`" then code compiles and runs without any error.

**Comment by SupunS** [comment]
This is fixed
