### ISSUE TITLE
Record fields are not populated in JBallerina

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#15453]
Executing the below code in JBallerina fails.

`int timeInMilis = time:curerntTime().time`

Executing the above code will throw Following exception

```java
 org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina}KeyNotFound {"message":"cannot find key 'time'"}
        at testStreamsPublishingForStructurallyEquivalentRecords(stream-value.bal:299)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:354)
        at org.ballerinalang.test.util.BRunUtil.invokeOnJBallerina(BRunUtil.java:268)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:854)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:252)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:912)
        at org.ballerinalang.test.types.stream.BStreamValueTest.testStreamsPublishingForStructurallyEquivalentRecords(BStreamValueTest.java:248)

        Caused by:
        org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina}KeyNotFound {"message":"cannot find key 'time'"}
                at testStreamsPublishingForStructurallyEquivalentRecords(stream-value.bal:299)

```

**Comment by SupunS** [comment]
Fixed
