### ISSUE TITLE
[jBallerina] jballerina run is broken

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#16127]
**Description:**
`jballerina run hello_world.bal` command throws following error.

`[2019-07-01 11:15:27,612] ERROR {org.ballerinalang.launcher.Main} - Compiled binary jar is not found 
java.lang.RuntimeException: Compiled binary jar is not found
        at org.ballerinalang.launcher.LauncherUtils.compileAndRunJar(LauncherUtils.java:444)
        at org.ballerinalang.launcher.LauncherUtils.runBal(LauncherUtils.java:373)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:132)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:261)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:63)`

**Comment by SupunS** [comment]
works on master as of today.
