### ISSUE TITLE
[JBallerina] WaitForAllActionsTest fails intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#16171]
**Description:**

https://github.com/ballerina-platform/ballerina-lang/pull/16170 disables `org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest16`  test case since it fails intermittently. Please refer the below error log:

```shell
ballerina-test-suite > jballerina-test > org.ballerinalang.test.worker.WaitForAllActionsTest > waitTest16 FAILED
    org.testng.internal.thread.ThreadTimeoutException: Method org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest16() didn't finish within the time-out 120000
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
        at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
        at org.ballerinalang.jvm.Scheduler.run(Scheduler.java:193)
        at org.ballerinalang.jvm.Scheduler.runSafely(Scheduler.java:180)
        at org.ballerinalang.jvm.Scheduler.start(Scheduler.java:172)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:538)
        at org.ballerinalang.test.util.BRunUtil.invokeOnJBallerina(BRunUtil.java:332)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1195)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:295)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:1253)
        at org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest16(WaitForAllActionsTest.java:233)
```

**Comment by ldclakmal** [comment]
**waitTest 15**

```shell
ballerina-test-suite > jballerina-test > org.ballerinalang.test.worker.WaitForAllActionsTest > waitTest15 FAILED
    org.testng.TestException: 
    The exception was thrown with the wrong message: expected "error: err from panic \{\}.*" but got "Method org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest15() didn't finish within the time-out 120000"

        Caused by:
        org.testng.internal.thread.ThreadTimeoutException: Method org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest15() didn't finish within the time-out 120000
            at sun.misc.Unsafe.park(Native Method)
            at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
            at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
            at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
            at org.ballerinalang.jvm.Scheduler.run(Scheduler.java:193)
            at org.ballerinalang.jvm.Scheduler.runSafely(Scheduler.java:180)
            at org.ballerinalang.jvm.Scheduler.start(Scheduler.java:172)
            at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:538)
            at org.ballerinalang.test.util.BRunUtil.invokeOnJBallerina(BRunUtil.java:332)
            at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1195)
            at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:295)
            at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:1253)
            at org.ballerinalang.test.worker.WaitForAllActionsTest.waitTest15(WaitForAllActionsTest.java:228)
```

**Comment by vinok88** [comment]
Enabled in https://github.com/ballerina-platform/ballerina-lang/pull/17057
