### ISSUE TITLE
[HTTP] ProxyServerTest fails intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#16415]
**Description:**
#16361 disables ProxyServerTest case since it fails intermittently.

Please refer the below log:

```shell
jBallerina-Test-Suite > ballerina-http-tests > org.ballerinalang.test.service.http.sample.ProxyServerTest > testHttpProxy FAILED
    org.ballerinalang.test.context.BallerinaTestException: Matching log not found prior to server shutdown for: Backend server sent response
        at org.ballerinalang.test.context.LogLeecher.waitForText(LogLeecher.java:105)
        at org.ballerinalang.test.service.http.sample.ProxyServerTest.testHttpProxy(ProxyServerTest.java:46)
```

**Comment by Bhashinee** [comment]
This cannot be reproduced.
