### ISSUE TITLE
[JBallerina] ArgumentParserPositiveTest fails intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#16414]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/16361 disables org.ballerinalang.test.main.ArgumentParserPositiveTest case since few tests fail intermittently.

Please refer the below log for sample.
```shell
ballerina-test-suite > jballerina-test > org.ballerinalang.test.main.function.ArgumentParserPositiveTest > testJsonArg[4](true) FAILED
    org.testng.internal.thread.ThreadTimeoutException: Method org.ballerinalang.test.main.function.ArgumentParserPositiveTest.testJsonArg() didn't finish within the time-out 120000
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
        at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
        at org.ballerinalang.jvm.Scheduler.run(Scheduler.java:193)
        at org.ballerinalang.jvm.Scheduler.runSafely(Scheduler.java:180)
        at org.ballerinalang.jvm.Scheduler.start(Scheduler.java:172)
        at ___init.main(.)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ballerinalang.test.util.BCompileUtil.runMain(BCompileUtil.java:706)
        at org.ballerinalang.test.main.function.ArgumentParserPositiveTest.runMain(ArgumentParserPositiveTest.java:312)
        at org.ballerinalang.test.main.function.ArgumentParserPositiveTest.testJsonArg(ArgumentParserPositiveTest.java:90)
```

**Comment by MaryamZi** [comment]
Closing since this test has been enabled with https://github.com/ballerina-platform/ballerina-lang/pull/17158, and no test failures were observed since.

Please reopen if this fails again.
