### ISSUE TITLE
Running `jballerina run` on a file with compile error crashes the compiler

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#16547]
```
[2019-07-13 12:13:52,901] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:51)
	at org.ballerinalang.util.BootstrapRunner.createClassLoaders(BootstrapRunner.java:145)
	at org.ballerinalang.launcher.LauncherUtils.compileAndRunJar(LauncherUtils.java:437)
	at org.ballerinalang.launcher.LauncherUtils.runBal(LauncherUtils.java:373)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:132)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:261)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:63)
```

**Comment by pubudu91** [comment]
Closing this since now standalone files can be executed using `ballerina run`
