### ISSUE TITLE
ClassCastException when using `runtime:sleep()`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17163]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/runtime;

type Foo record {
    string s;
};

public function main() {
    stream<Foo> sf = new;
    sf.subscribe(one);
    sf.subscribe(two);

    Foo f = {
        s: "old value"
    };
    sf.publish(f);

    runtime:sleep(15000);
}

function one(Foo f) {
    io:println(1, ": ", f);
    runtime:sleep(2000);
    f.s = "new value";
    io:println(1, ": ", f);
}

function two(Foo f) {
    io:println(2, ": ", f);
    runtime:sleep(5000);
    io:println(2, ": ", f);
}
```

Code after the sleeps isn't executed. Works when the sleeps are removed.

```cmd
$ ballerina run --experimental error_test.bal 
1: s=old value
2: s=old value
```

ballerina-internal.log
```
[2019-07-30 20:43:47,795] ERROR {org.ballerinalang.jvm.Scheduler} - Strand died 
java.lang.ClassCastException: oneFrame cannot be cast to twoFrame
	at error_test.two(error_test.bal:32)
	at error_test.two$lambda$(error_test.bal)
	at org.ballerinalang.jvm.values.FPValue.accept(FPValue.java:59)
	at org.ballerinalang.jvm.streams.DefaultStreamSubscription.execute(DefaultStreamSubscription.java:43)
	at org.ballerinalang.jvm.streams.StreamSubscriptionManager.update(StreamSubscriptionManager.java:86)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.ballerinalang.jvm.streams.StreamSubscription.send(StreamSubscription.java:44)
	at org.ballerinalang.jvm.streams.StreamSubscriptionManager.lambda$sendMessage$2(StreamSubscriptionManager.java:72)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.ballerinalang.jvm.streams.StreamSubscriptionManager.sendMessage(StreamSubscriptionManager.java:72)
	at org.ballerinalang.jvm.values.StreamValue.publish(StreamValue.java:124)
	at org.ballerinalang.langlib.stream.Publish.publish(Publish.java:42)
	at ballerina.lang_stream.stream.publish(stream.bal:21)
	at error_test.main(error_test.bal:16)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.SchedulerItem.execute(Scheduler.java:453)
	at org.ballerinalang.jvm.Scheduler.run(Scheduler.java:216)
	at org.ballerinalang.jvm.Scheduler.runSafely(Scheduler.java:187)
	at java.lang.Thread.run(Thread.java:745)
```

**Affected Versions:**
0.992.0-m8

Possibly related to https://github.com/ballerina-platform/ballerina-lang/issues/17162

**Comment by vinok88** [comment]
Try creating a Scheduler with one thread. `new Scheduler(1, false)`

**Comment by gimantha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19951
