### ISSUE TITLE
Windows Pack broken 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#17329]
`ballerina run hello.bal` fails with the following error. 
```
[2019-08-02 12:54:52,583] ERROR {org.ballerinalang.tool.Main} - com.google.common.net.HostAndPort.getHost()Ljava/lang/String;
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHost()Ljava/lang/String;
        at com.spotify.docker.client.DockerHost.<init>(DockerHost.java:85)
        at com.spotify.docker.client.DockerHost.fromEnv(DockerHost.java:172)
        at org.ballerinax.docker.generator.models.DockerModel.<init>(DockerModel.java:66)
        at org.ballerinax.docker.models.DockerDataHolder.<init>(DockerDataHolder.java:38)
        at org.ballerinax.docker.models.DockerContext.addDataHolder(DockerContext.java:47)
        at org.ballerinax.docker.DockerPlugin.process(DockerPlugin.java:71)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$1(CompilerPluginRunner.java:133)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:133)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:124)
        at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:333)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:295)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:262)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:175)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:181)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:54)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:275)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by SupunS** [comment]
FIxed
