### ISSUE TITLE
NPE when getting the listner suggestions in VSCode plugin

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17350]
**Description:**

Below npe is thrown when typing the following code.

```ballerina
import ballerina/http;

listener http:Listener httpListner = new()
```
```
[Error - 3:06:42 PM] Operation 'text/signature' failed! {uri: /Volumes/work/Ballerina/TestBallerina/TestAlpha/BBG/testProject/restful-service/guide/restful-service/src/restful_service/order_mgt_service.bal, line: 3, col:42, error: java.lang.NullPointerException}
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$signatureHelp$4(BallerinaTextDocumentService.java:255)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
**Steps to reproduce:**

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/16300038/62360899-80307980-b537-11e9-8731-2c790eb0854a.png">

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master and hence closing the issue
