### ISSUE TITLE
Source pruning failed for broken code

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#17552]
**Description:**
Below broken code causes not showing of hover help text. Getting a NPE.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/file;

service serviceName on new http:Listener(8080) {
    resource function newResource(http:Caller caller, http:Request request) {
        (string|error) textPayload = request.getTextPayload();
        if (textPayload is string) {
            http:Response response = new http:Res
            http:Response response2 = new();
        }
    }
}
```

Throws below exception;
```
[Error - 7:09:44 PM] Operation 'text/hover' failed! {uri: /Users/rasika/Desktop/bbg/src/module1/services.bal, line: 9, col:21, error: Compilation failed!}
org.ballerinalang.langserver.compiler.exception.CompilationFailedException: Compilation failed!
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:197)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackages(LSModuleCompiler.java:165)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.compileModulesAndFindReferences(ReferencesUtil.java:98)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:209)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitVariableDefinitionStatement(BLangParserListener.java:1131)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$VariableDefinitionStatementContext.exitRule(BallerinaParser.java:4992)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:479)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:126)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:459)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:329)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$2(Compiler.java:167)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:169)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:181)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:192)
	... 9 more
```

But compiling the same project with `ballerina build` only throws correct error;

```
Compiling source
    rasika/module3:0.0.1
    rasika/module2:0.0.1
    rasika/module1:0.0.1
error: rasika/module1:0.0.1::services.bal:8:42: mismatched input 'http'. expecting {'is', ';', '(', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '===', '!==', '&', '^', '...', '|', '?:', '->>', '..<', '.@'}
```
**Affected Versions:**
1.0.0-alpha

**Comment by nadeeshaan** [comment]
This is not thrown from the source pruner and we do not use source pruner for hover operation at the moment. Since this exact source is being parsed from the compiler. Hence closing the issue. This is expected since we currently provide hover support for syntactically valid sources
