### ISSUE TITLE
NPE thrown when mysql driver is not found

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17630]
**Description:**

```
error: invoking main method failed due to error {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost/testdb:No suitable driver cause=null
Exception in thread "Thread-3" java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.jvm.util.RuntimeUtils.handleRuntimeThrowable(RuntimeUtils.java:114)
	at ___init$SignalListener.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at ___init.___stop_(.:15)
	at ___init.$lambda$___stop_$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:414)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:198)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:169)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:156)
```

**Steps to reproduce:**
Run any ballerina service with jdbc client *without* dropping the jdbc driver in the `bre/lib/` folder
```ballerina
jdbc:Client dbClient = new({
    url: "jdbc:mysql://localhost/testdb",
    username: "root",
    password: "root",
    poolOptions: { maximumPoolSize: 10 },
    dbOptions: { useSSL: false }
});
```
**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Tested on top of PR https://github.com/ballerina-platform/ballerina-lang/pull/17873.

This is fixed now. Gets the following compile error:
```
error: {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: com/zaxxer/hikari/HikariConfig:com.zaxxer.hikari.HikariConfig
	at ballerinax.java_jdbc:createClient(jdbc_client.bal:88)
	   ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
	   ..<init>(.:4)
```
