### ISSUE TITLE
IDE error occurred from the ballerina IntelliJ plugin

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#17710]
**Description:**
Following IDE error occurred from the ballerina IntelliJ plugin, while writing a ballerina file.

```
From listener io.ballerina.plugins.idea.preloading.BallerinaPreloadingActivity$$Lambda$752/0x0000000840cbd440@3f383903 (class io.ballerina.plugins.idea.preloading.BallerinaPreloadingActivity$$Lambda$752/0x0000000840cbd440)

java.lang.AssertionError: Already disposed: Project (Disposed) test
at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:286)
at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:284)
at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:277)
at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:182)
at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:44)
at io.ballerina.plugins.idea.sdk.BallerinaSdkUtils.getBallerinaSdkFor(BallerinaSdkUtils.java:222)
at io.ballerina.plugins.idea.preloading.BallerinaPreloadingActivity.updateBallerinaPathModificationTracker(BallerinaPreloadingActivity.java:197)
at io.ballerina.plugins.idea.preloading.BallerinaPreloadingActivity.lambda$preload$0(BallerinaPreloadingActivity.java:83)
at com.intellij.openapi.project.impl.ProjectManagerImpl.canClose(ProjectManagerImpl.java:865)
at io.ballerina.plugins.idea.sdk.BallerinaSdkUtils.lambda$showRestartDialog$3(BallerinaSdkUtils.java:502)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)

```

**Affected Versions:**
IntelliJ plugin 1.0.0-beta-SNAPSHOT

**Comment by NipunaRanasinghe** [comment]
Closing hence fixed by #19215
