### ISSUE TITLE
VSCode plugin - No suggestions within the brackets

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17778]
**Description:**

My target is to write the below code.

```ballerina
function equationOfCenter(float solarAnomaly) returns float {
    float annomalyInRad = solarAnomaly * ( math:PI / 180 );
    return annomalyInRad;
}
```

But suggestions for the `math:` are not shown within the brackets as shown below. If we write without brackets, it gives the suggestions. 
 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/16300038/63092201-94846580-bf7e-11e9-8ccf-47982a720843.png">

```
[Error - 5:03:25 PM] Operation 'text/completion' failed! {uri: /Volumes/work/Ballerina/Code/BetaHackathon/SunProject/src/suntime/utils.bal, line: 12, col:49, error: java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)}
java.lang.NullPointerException
	at org.ballerinalang.langserver.completions.TreeVisitor.visit(TreeVisitor.java:222)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)
	at org.ballerinalang.langserver.completions.TreeVisitor.acceptNode(TreeVisitor.java:905)
	at org.ballerinalang.langserver.completions.TreeVisitor.visit(TreeVisitor.java:186)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.resolveSymbols(CompletionUtil.java:58)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:180)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This has been fixed and shipped with v1.0.0, hence closing the issue and please re-open if the issue still exists.
