### ISSUE TITLE
Local variables are not suggested as function arguments

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17785]
**Description:**

My code is as follows.

```ballerina
import ballerina/math;

function equationOfCenter(float solarAnomaly) returns float {
    float annomalyInRad = solarAnomaly * ( math:PI / 180 );
    float anomalySin = math:sin(annomalyInRad);
    float anomaly2Sin = math:sin( 2 *  )
    return annomalyInRad;
}
```

Local variables such as `annomalyInRad` ,  `anomalySin` etc are not gives as suggestions as function arguments.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/16300038/63092659-11640f00-bf80-11e9-8644-ebadba469803.png">

```
[Error - 5:12:16 PM] Operation 'text/completion' failed! {uri: /Volumes/work/Ballerina/Code/BetaHackathon/SunProject/src/suntime/utils.bal, line: 14, col:39, error: java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)}
java.lang.NullPointerException
	at org.ballerinalang.langserver.completions.TreeVisitor.visit(TreeVisitor.java:222)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)
	at org.ballerinalang.langserver.completions.TreeVisitor.acceptNode(TreeVisitor.java:905)
	at org.ballerinalang.langserver.completions.TreeVisitor.visit(TreeVisitor.java:186)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.resolveSymbols(CompletionUtil.java:58)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:180)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This is a limitation when we get completion within the function arguments. In order to get the completions, you have to add the semicolon at the end

**Comment by nadeeshaan** [comment]
closing since the fix has been merged, please reopen if the issue still exists
