### ISSUE TITLE
Ballerina Inter-op if class not found gives a Bad Sad while code gen.

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17800]
**Description:**
Ballerina Inter-op if class not found gives a Bad Sad while code gen. Ideally the build should fail with a error.

```
[2019-08-15 19:13:09,767] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
error: cannot find function definition for : jo/jyaml/yamlObj 
        at ballerina.compiler_backend_jvm:getExternalFunctionWrapper(interop/external_method_gen.bal:223)
           ballerina.compiler_backend_jvm:genJMethodForBExternalFunc(interop/external_method_gen.bal:33)
           ballerina.compiler_backend_jvm:generateMethod(jvm_method_gen.bal:28)
           ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:200)
           ballerina.compiler_backend_jvm:generateJarBinary(main.bal:74)
           ballerina.compiler_backend_jvm:main(main.bal:50) 
[2019-08-15 19:13:09,779] ERROR {org.ballerinalang.tool.Main} - cannot find function definition for : jo/jyaml/yamlObj 
java.lang.RuntimeException: cannot find function definition for : jo/jyaml/yamlObj
        at org.ballerinalang.util.BootstrapRunner.generateJarBinaryViaCompiledBackend(BootstrapRunner.java:140)
        at org.ballerinalang.packerina.task.CreateJarTask.execute(CreateJarTask.java:65)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:361)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: error cannot find function definition for : jo/jyaml/yamlObj 
        at ballerina.compiler_backend_jvm.interop-external_method_gen.getExternalFunctionWrapper(interop/external_method_gen.bal:223)
        at ballerina.compiler_backend_jvm.interop-external_method_gen.genJMethodForBExternalFunc(interop/external_method_gen.bal:33)
        at ballerina.compiler_backend_jvm.jvm_method_gen.generateMethod(jvm_method_gen.bal:28)
        at ballerina.compiler_backend_jvm.jvm_package_gen.generatePackage(jvm_package_gen.bal:200)
        at ballerina.compiler_backend_jvm.main.generateJarBinary(main.bal:74)
        at ballerina.compiler_backend_jvm.main.main(main.bal:50)
        at ballerina.compiler_backend_jvm.___init.$lambda$main$(compiler_backend_jvm)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:452)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:228)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:198)
        at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
Example code
```ballerina

function yamlObj() returns handle = @java:Constructor {
    class: "org.yaml.snakeyamls.Yaml"
} external;
```
**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**Comment by hevayo** [comment]
Fixed in SL
