### ISSUE TITLE
NullPointer when trying to access a public listener from different module

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#17827]
**Description:**
$subject.

**Steps to reproduce:**

1. Create a project and add two modules. (i.e `core_module`, `service_module`)
2. Add the following in `core_module`s source;
```ballerina
import ballerina/http;

public listener http:Listener server_listener = new(9090);
```
3. Add the following in `service_module`s source;
```ballerina
import ballerina/http;
import ballerina/io;
import core_module;

# A service is a network-accessible API
# Advertised on '/hello', port comes from listener endpoint
service hello on core_module:server_listener {

    # A resource is an invokable API method
    # Accessible at '/hello/sayHello
    # 'caller' is the client invoking this resource 

    # + caller - Server Connector
    # + request - Request
    resource function sayHello(http:Caller caller, http:Request request) {

        // Send a response back to caller
        // -> indicates a synchronous network-bound call
        error? result = caller->respond("Hello Ballerina!");
        if (result is error) {
            io:println("Error in responding", result);
        }
    }
}
```
4. Build and run the service, and it will throw a NullPointer

**OS, DB, other environment details and versions:**
Windows, VSCode, 1.0.0-Beta

**Comment by MaryamZi** [comment]
ballerina-internal.log
```
[2019-08-29 13:53:19,553] ERROR {org.ballerinalang.tool.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIROptimizer.visit(BIROptimizer.java:124)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:369)
	at org.wso2.ballerinalang.compiler.bir.BIROptimizer.lambda$visit$2(BIROptimizer.java:86)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.BIROptimizer.visit(BIROptimizer.java:86)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:346)
	at org.wso2.ballerinalang.compiler.bir.BIROptimizer.optimizePackage(BIROptimizer.java:67)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:272)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:225)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:341)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:305)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:262)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:169)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:298)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
