### ISSUE TITLE
Bad, Sad error when using `typeof` inline with annotation access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17936]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
annotation foo on type;

@foo
type Bar record {
    int i;
};

public function main() {
    Bar b = { i: 1 };
    boolean? f = (typeof b).@foo; // works if first assigned to a typedesc and then called
}
```

ballerina-internal.log
```
[2019-08-18 13:28:42,475] ERROR {org.ballerinalang.tool.Main} - null 
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.createAnnotAccessNode(BLangPackageBuilder.java:3844)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitAnnotAccessExpression(BLangParserListener.java:2371)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$AnnotAccessExpressionContext.exitRule(BallerinaParser.java:12002)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:478)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:126)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:461)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:331)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$2(Compiler.java:167)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:169)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:180)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:298)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by MaryamZi** [comment]
Possibly related to https://github.com/ballerina-platform/ballerina-lang/issues/17938.
