### ISSUE TITLE
Ballerina files can't be renamed through refactor menu IntelliJ Idea plugin

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#17941]
**Description:**
When I try to rename a ballerina file using `refactor->rename` menu in the IntelliJ Idea, it causes an error and does not allow to refactor the file.

This only occurs for ballerina files. Other files in the same project works fine.

> Following is the error message:
```
Access is allowed from event dispatch thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@6df0fa39
Current thread: Thread[ApplicationImpl pooled thread 280,4,Idea Thread Group] 2111748742
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2#IC-192.5728.98 IDEA, eap:false, os:Mac OS X 10.14.5, java-version:JetBrains s.r.o 11.0.3+12-b304.10 2019.2#IC-192.5728.98 IDEA, eap:false, os:Mac OS X 10.14.5, java-version:JetBrains s.r.o 11.0.3+12-b304.10,6,Idea Thread Group] 412268988
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1068)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1057)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedEditorWithProvider(FileEditorManagerImpl.java:1332)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedEditor(FileEditorManagerImpl.java:1324)
	at org.wso2.lsp4intellij.contributors.rename.LSPRenameProcessor.canProcessElement(LSPRenameProcessor.java:60)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.forElement(RenamePsiElementProcessor.java:151)
	at com.intellij.refactoring.rename.RenameUtil.findUsages(RenameUtil.java:82)
	at com.intellij.refactoring.rename.RenameProcessor.findUsages(RenameProcessor.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRun$0(BaseRefactoringProcessor.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
Try to rename a ballerina file inside the ballerina-org repository.

**OS, DB, other environment details and versions:**
> OS: OSX Mojave
> IntelliJ Idea version: Community 2019.2
> Ballerina Idea Plugin: 1.0.0-alpha

**Comment by ThisaruGuruge** [comment]
This is fixed in alpha 3 pack. Hence closing the issue.
