### ISSUE TITLE
TimerSchedulerTest > testListenerTimerStop fails intermittently 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17991]
**Description:**
Failed on travis a couple of times
```
ballerina-task-test-suite > ballerina-task-tests > org.ballerinalang.stdlib.task.scheduler.TimerSchedulerTest > testListenerTimerStop FAILED
    org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.ballerinalang.stdlib.task.scheduler.TimerSchedulerTest that uses org.ballerinalang.test.util.CompileResult was not fulfilled within 10000 milliseconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
        at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
        at org.ballerinalang.stdlib.task.scheduler.TimerSchedulerTest.testListenerTimerStop(TimerSchedulerTest.java:93)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.util.concurrent.FutureTask.get(FutureTask.java:205)
            at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:91)
            ... 5 more
```

**Comment by chamil321** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/18056, Hence closing issue
