### ISSUE TITLE
Bad, sad error with workers as variable references - NPE in BIRInstructionWriter

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18024]
**Description:**
```ballerina
public function main() {
    worker w1 {
        future<int> fi = w2; // fails for this
    }

    worker w2 returns int {
        future<()> fn = w1;
        return 2;
    }
}
```

ballerina-internal.log
```
[2019-08-20 13:59:07,366] ERROR {org.ballerinalang.tool.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:424)
	at org.wso2.ballerinalang.compiler.bir.model.BIROperand.accept(BIROperand.java:36)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:464)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNonTerminator$FPLoad.accept(BIRNonTerminator.java:591)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$visit$1(BIRInstructionWriter.java:81)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:81)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:369)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:72)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:72)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:280)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$5(BIRBinaryWriter.java:187)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:187)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:89)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:273)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:225)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:341)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:305)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:262)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:175)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:180)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:298)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by rdhananjaya** [comment]
Reopening as disallowing these worker references is a spec deviation.
