### ISSUE TITLE
Bad, sad error with table data type when inserting duplicate records

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18038]
**Description:**

$title
**Steps to reproduce:**

```ballerina
type Person record {
    int id;
    int age;
    float salary;
    string name;
    boolean married;
};

public function main() {
    testTableAddOnConstrainedTableWithViolation();
}

function testTableAddOnConstrainedTableWithViolation() {
    Person p1 = { id: 1, age: 30, salary: 300.50, name: "jane", married: true };
    Person p2 = { id: 1, age: 30, salary: 300.50, name: "jane", married: true };

    table<Person> t1 = table {
        { key id, salary, name, age, married },
        [p1, p2]
    };
}

```
ballerina-internal.log
```
[2019-08-20 16:56:53,457] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
org.ballerinalang.jvm.util.exceptions.BallerinaException: execute update failed: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.TABLE_PERSON_0(ID) [1, 30, 300.5, 'jane', TRUE]"; SQL statement:
INSERT INTO TABLE_PERSON_0 (id ,age ,salary ,name ,married ) values (?,?,?,?,?) [23505-199]
	at org.ballerinalang.jvm.TableUtils.prepareAndExecuteStatement(TableUtils.java:104)
	at org.ballerinalang.jvm.TableProvider.prepareAndExecuteStatement(TableProvider.java:322)
	at org.ballerinalang.jvm.TableProvider.insertData(TableProvider.java:113)
	at org.ballerinalang.jvm.values.TableValue.addData(TableValue.java:244)
	at org.ballerinalang.jvm.values.TableValue.insertInitialData(TableValue.java:370)
	at org.ballerinalang.jvm.values.TableValue.<init>(TableValue.java:111)
	at irshadnilam.examples.main.testTableAddOnConstrainedTableWithViolation(main.bal:17)
	at irshadnilam.examples.main.main(main.bal:10)
	at irshadnilam.examples.___init.$lambda$main$(examples)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:452)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:228)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:198)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.TABLE_PERSON_0(ID) [1, 30, 300.5, 'jane', TRUE]"; SQL statement:
INSERT INTO TABLE_PERSON_0 (id ,age ,salary ,name ,married ) values (?,?,?,?,?) [23505-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:131)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546)
	at org.h2.command.dml.Insert.insertRows(Insert.java:180)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:250)
	at org.ballerinalang.jvm.TableUtils.prepareAndExecuteStatement(TableUtils.java:102)
	... 12 more
```
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3520301/ballerina-internal.log)

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**
MacOs 10.14.5
java version "1.8.0_212"

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This should've been a panic. Seems the exception is not wrapped in `ErrorValue`. Hence it ends up in the crash log.
