### ISSUE TITLE
java.lang.IllegalStateException: illegal function invocation

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#18223]
**Description:**
Above exception logged in `ballerina-internal.log` when sending a request to the following simple service.

```ballerina
import ballerina/config;
import ballerina/http;
import ballerina/log;

// Endpoint for the backend service.
http:Client healthcareEndpoint = new("https://reqres.in");
// Constants for request paths.
const BACKEND_EP_PATH = "/api/users";

@http:ServiceConfig {
    basePath: "/laboratory"
}
service scienceLabService on new http:Listener(config:getAsInt("LISTENER_PORT")) {
    // Schedule an appointment.
    @http:ResourceConfig {
        methods: ["POST"],
        path: "/user"
    }
    resource function addUser(http:Caller caller, http:Request request) {
        // Extract payload from the request.
        xml|error requestPayload = request.getXmlPayload();

        if (requestPayload is xml) {
            // Transform the payload into the json which is required by the backend service.
            json|error modifiedPayload = {
                "name": requestPayload.name.getTextValue(),
                "job": requestPayload.job.getTextValue()
            };

            if (modifiedPayload is json) {
                // Create new request to call the back-end service with the modified payload.
                http:Request backendRequest = new();
                backendRequest.setPayload(<@untainted> modifiedPayload);
                // Define new response
                http:Response|error backendResponse = new();
                backendResponse = healthcareEndpoint->post(BACKEND_EP_PATH, backendRequest);

                if (backendResponse is http:Response) {
                    // Get json payload from the backend response.
                    json|error resJson = backendResponse.getJsonPayload();

                    if (resJson is json) {
                        // Convert the json payload to xml.
                        string id = resJson.id.toString();
                        string name = resJson.name.toString();
                        string job = resJson.job.toString();
                        string created = resJson.createdAt.toString();

                        xml|error resXml = xml `<response>
                            <status>successful</status>
                            <id>${id}</id>
                            <name>${name}</name>
                            <job>${job}</job>
                            <createdAt>${created}</createdAt>
                        </response>`;

                        if (resXml is xml) {
                            respondAndHandleError(caller, http:STATUS_OK, resXml);
                        } else {
                            log:printError("Converting backend json response to xml failed.", err = resXml);
                            respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, 
                                "Converting backend json response to xml failed.");
                        }

                    } else {
                        log:printError("Invalid response from backend service.", err = resJson);
                        respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, 
                            "Invalid response from backend service.");
                    }

                    // Send response to the caller.
                    var respond = caller->respond(backendResponse);
                    if (respond is error) {
                        log:printError("Error occurred while responding", err = respond);
                    }
                } else {
                    log:printError("Error in sending request to backend service.", err = backendResponse);
                    respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, 
                        "Error in sending request to backend service.");
                }

            } else {
                log:printError("Transforming xml to json failed.", err = modifiedPayload);
                respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, "Transforming xml to json failed.");
            }

        } else {
            log:printError("Invalid request payload.", err = requestPayload);
            respondAndHandleError(caller, http:STATUS_BAD_REQUEST, "Invalid request payload.");
        }
    }
}

// Function to send the response back to the client and handle the error.
function respondAndHandleError(http:Caller caller, int resCode, json|xml|string payload) {
    http:Response res = new;
    res.statusCode = resCode;
    res.setPayload(payload);
    var respond = caller->respond(res);
    if (respond is error) {
        log:printError("Error occurred while responding", err = respond);
    }
}
```

**Steps to reproduce:**
1. Create a file named request.xml with the following content:
```xml
<user>
     <name>Sam</name>
     <job>Scientist</job>
</user>
```
2. Invoke the service with the following request. Use an HTTP client like cURL.
```curl
curl -X POST -d @request.xml  http://localhost:9092/laboratory/user  -H "Content-Type: text/xml"
```
3. Check `ballerina-internal.log`
```
[2019-08-27 12:28:52,139] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
java.lang.IllegalStateException: illegal function invocation
	at org.ballerinalang.net.http.HttpUtil.methodInvocationCheck(HttpUtil.java:1041)
	at org.ballerinalang.net.http.HttpUtil.checkFunctionValidity(HttpUtil.java:1036)
	at org.ballerinalang.net.http.nativeimpl.connection.Respond.nativeRespond(Respond.java:77)
	at ballerina.http.http_connection.nativeRespond(http_connection.bal:166)
	at ballerina.http.Caller.respond(http_connection.bal:54)
	at ballerina.http.Caller.call(http_connection.bal)
	at wso2.xml_to_json_transformation.scienceLabService__service_0.addUser(main.bal:88)
	at wso2.xml_to_json_transformation.scienceLabService__service_0.call(main.bal)
	at org.ballerinalang.jvm.values.connector.Executor.lambda$submit$0(Executor.java:91)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:414)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:198)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:169)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:156)
	at wso2.xml_to_json_transformation.___init.main(xml_to_json_transformation)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.packerina.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:194)
	at org.ballerinalang.packerina.task.RunExecutableTask.execute(RunExecutableTask.java:163)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:257)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
Ballerina 1.0.0-alpha
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
@pramodya1994 In a HTTP service, execution path should only have one respond() function invocation. In the following code, you respond first within if- else type guard which checks for XML. And then your execution path has another respond (var respond = caller->respond(backendResponse)) which throw the exception. 

```ballerina
 	if (resXml is xml) {
            respondAndHandleError(caller, http:STATUS_OK, resXml);
        } else {
            log:printError("Converting backend json response to xml failed.", err = resXml);
            respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, 
                "Converting backend json response to xml failed.");
        }

    } else {
        log:printError("Invalid response from backend service.", err = resJson);
        respondAndHandleError(caller, http:STATUS_INTERNAL_SERVER_ERROR, 
            "Invalid response from backend service.");
    }

    // Send response to the caller.
    var respond = caller->respond(backendResponse);
    if (respond is error) {
        log:printError("Error occurred while responding", err = respond);
    }
```
Can you fix the code and check?
We will be doing a refactoring soon on exception throwing. So hope to refactor the error message accordingly.

**Comment by pramodya1994** [comment]
After refactoring the code as you suggested fixes the problem. Thanks for the help.

**Comment by chamil321** [comment]
As per the above comment, closing the issue
