### ISSUE TITLE
Missing closing double quotes in string arguments gives a bad sad error

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18225]
**Description:**
Can be reproduced with below code. It is missing a " at the end of first parameter for the function.

output

```
error: .::timetest.bal:5:56: invalid token 'yyyy'
error: .::timetest.bal:5:74: mismatched input ':'. expecting {'(', '[', '?', '|'}
error: .::timetest.bal:5:77: mismatched input '.'. expecting '='
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

```
[2019-08-27 12:42:49,564] ERROR {org.ballerinalang.tool.Main} - null
java.util.EmptyStackException
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.addErrorDetailBinding(BLangPackageBuilder.java:870)
        at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitErrorDetailBindingPattern(BLangParserListener.java:997)
        at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ErrorDetailBindingPatternContext.exitRule(BallerinaParser.java:7550)
        at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
        at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
        at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:478)
        at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:129)
        at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:101)
        at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:489)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:383)
        at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$1(Compiler.java:161)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:163)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:298)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```
**Steps to reproduce:**

```ballerina
import ballerina/io;
import ballerina/time;

public function main(string... args) {
    var b = time:parse("2019-08-26T17:59:43.907+0530, "yyyy-MM-dd'T'HH:mm:ss.SSSX");
    io:println(b);
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/18214 should fix this
