### ISSUE TITLE
[Observability] org.ballerinalang.test.observability.metrics.MetricsTestCase > testMetrics fails Intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#18372]
**Description:**

Logs of iteration 1:
```shell
jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.metrics.MetricsTestCase > testMetrics STANDARD_ERROR
    [2019-08-30 07:29:27,800] SEVERE {org.ballerinalang.test.observability.metrics.MetricsTestCase} - [1mtestMetrics: [31m[1mFAILED -> Connection refused (Connection refused)[0m 

jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.metrics.MetricsTestCase > testMetrics FAILED
    java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at org.ballerinalang.test.util.HttpClientRequest.executeRequestWithoutRequestBody(HttpClientRequest.java:197)
        at org.ballerinalang.test.util.HttpClientRequest.executeRequestWithoutRequestBody(HttpClientRequest.java:181)
        at org.ballerinalang.test.util.HttpClientRequest.doGet(HttpClientRequest.java:57)
        at org.ballerinalang.test.util.HttpClientRequest.doGet(HttpClientRequest.java:83)
        at org.ballerinalang.test.observability.metrics.MetricsTestCase.testMetrics(MetricsTestCase.java:76)
```

Logs of iteration 2:
```shell
jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.metrics.MetricsTestCase > testMetrics FAILED
    java.lang.AssertionError: expected [[{"PRODUCTID":1, "PRODUCTNAME":"WSO2-IAM"}, {"PRODUCTID":3, "PRODUCTNAME":"WSO2-EI"}]] but found []
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at org.ballerinalang.test.observability.metrics.MetricsTestCase.testMetrics(MetricsTestCase.java:76)

jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.metrics.MetricsTestCase STANDARD_ERROR
    [2019-08-30 08:27:59,626] SEVERE {org.ballerinalang.test.observability.metrics.MetricsTestCase} - [1mtestMetrics: [31m[1mFAILED -> expected [[{"PRODUCTID":1, "PRODUCTNAME":"WSO2-IAM"}, {"PRODUCTID":3, "PRODUCTNAME":"WSO2-EI"}]] but found [][0m 
    [2019-08-30 08:27:59,627] INFO {org.ballerinalang.test.context.BServerInstance} - Stopping server.. 
    [2019-08-30 08:28:00,647] INFO {org.ballerinalang.test.context.BServerInstance} - Server Stopped Successfully 
```

**Comment by Anoukh** [comment]
Closing this issue since fix is merged https://github.com/ballerina-platform/ballerina-lang/pull/18373
