### ISSUE TITLE
Java stacktrace appears for address already in use situations

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#18502]
Just look at the following error I've got. Looks like we've treated this as a panic. This is not a Ballerina level panic IMO. The listener start method should return an error for such cases. 

```
2019-09-03 11:54:04,341 ERROR [inalang.net.http.HttpConnectorPortBindingListener] - Error in http endpoint
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
2019-09-03 11:54:04,343 ERROR [inalang.jvm.scheduling.Scheduler] - Strand died
error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.Listener:start(service_endpoint.bal:98)
	   ballerina.http.Listener:__start(service_endpoint.bal:37)
	   .<start>(.:11) 
error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.Listener:start(service_endpoint.bal:98)
	   ballerina.http.Listener:__start(service_endpoint.bal:37)
	   .<start>(.:11)
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090```

**Comment by vinok88** [comment]
This is introduced with the changes requested from the issue https://github.com/ballerina-platform/ballerina-lang/issues/17884

**Comment by riyafa** [comment]
Based on the fix for that issue shouldn't the trace log be printed only  if `b7a.log.console.loglevel` is set?
Otherwise only the user level logs need to be printed.

**Comment by vinok88** [comment]
NO, It's log level can be configured using `b7a.log.console.loglevel`. By default it is set to WARN log as per the StdLib team's request.
