### ISSUE TITLE
Getting a bad-sad error when there are compile errors in the project

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#18505]
**Description:**

Project structure:
```
project
├── Ballerina.toml
└── src
    ├── foo
    │   └── src
    │       └── foo
    │           ├── annotation.bal
    │           └── api_gateway_cache.bal
    │
    └── bar
        └── src
            └── some-directory
                ├── interceptors
                ├── listeners.bal
                │
                └── token_revocation_extension.bal
```
When the above project is built using `ballerina build` command, there were compile errors in the `foo` module. Along with the compile errors, there was a bad-sad error as well, that was logged.

ballerina-internal.log contains the following:
```
[2019-09-04 09:30:39,431] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:51)
	at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:68)
	at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:48)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:388)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)

```

**Affected Versions:**
v1.0-pre-beta (next-release branch for beta)

**Source code:**
[api-gateway.zip](https://github.com/ballerina-platform/ballerina-lang/files/3631003/api-gateway.zip)

**Comment by hevayo** [comment]
Will it be possible to share the code ?

**Comment by SupunS** [comment]
@hevayo Added the source code.

However, tested this on v1.0.0, and now its giving the bad-sad error during the symbol enter phase.

```
[2019-09-19 17:12:29,305] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:275)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:242)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:204)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:481)
	at org.wso2.ballerinalang.compiler.PackageLoader.parseAndDefine(PackageLoader.java:476)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:448)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:475)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:204)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:262)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:255)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:242)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:204)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:481)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:399)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$1(Compiler.java:165)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:167)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:146)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:62)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
```

**Comment by pubudu91** [comment]
Related issue #18449. When trying out the scenario mentioned in #18449, came across the same NPE issue @SupunS has mentioned above.
