### ISSUE TITLE
Unnecessary native logs printed for valid panics

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18524]
Consider a case where you try to run a service on an already bound port. Currently, you get the following output.
```
$ ballerina run service.bal
[2019-09-04 12:03:15,033] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.Listener:start(service_endpoint.bal:98)
	   ballerina.http.Listener:__start(service_endpoint.bal:37)
	   .<start>(.:9) 
error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.Listener:start(service_endpoint.bal:98)
	   ballerina.http.Listener:__start(service_endpoint.bal:37)
	   .<start>(.:9)
[2019-09-04 12:03:15,036] ERROR {org.ballerinalang.net.http.HttpConnectorPortBindingListener} - Error in http endpoint 
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:473)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
 
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
```
In the above case, there is no need for any native level logs. It only should've printed the panic as follows:
```
$ ballerina run service.bal
error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.Listener:start(service_endpoint.bal:98)
	   ballerina.http.Listener:__start(service_endpoint.bal:37)
	   .<start>(.:9)
[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
```

**Comment by pubudu91** [comment]
The unnecessary log on the HTTP part seems to be due to this unnecessary log line.
https://github.com/ballerina-platform/ballerina-lang/blob/3455650ddf9923d712cc4ae7e1216a22d6831c5e/stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConnectorPortBindingListener.java#L62

**Comment by chamil321** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/18647
