### ISSUE TITLE
HikariCP error stacktraces are printed when errors occur in jdbc module

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#18631]
**Description:**
eg:

```bash
2019-09-05 15:18:56,729 ERROR [.hikari.pool.HikariPool] - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinax.jdbc.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:248)
	at org.ballerinax.jdbc.datasource.SQLDatasource.init(SQLDatasource.java:57)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.createAndInitDatasource(PoolOptionsWrapper.java:75)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.lambda$retrieveDatasource$1(PoolOptionsWrapper.java:68)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.retrieveDatasource(PoolOptionsWrapper.java:67)
	at org.ballerinax.jdbc.functions.CreateClient.createSQLDBClient(CreateClient.java:75)
	at org.ballerinax.jdbc.functions.CreateClient.createClient(CreateClient.java:48)
	at ballerinax.java_jdbc.jdbc_client.createClient(jdbc_client.bal:88)
	at ballerinax.java_jdbc.$value$Client.__init(client_endpoint.bal:27)
	at ballerinax.java_jdbc.$value$Client.call(client_endpoint.bal)
	at ___init.___init_(.:6)
	at ___init.$moduleInit(.:65535)
	at ___init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:475)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:235)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:205)
	at java.lang.Thread.run(Thread.java:748)

error: {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to initialize pool: Public Key Retrieval is not allowed:Public Key Retrieval is not allowed
	at ballerinax.java_jdbc:createClient(jdbc_client.bal:88)
	   ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
	   ..<init>(.:6)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Manuri** [comment]
Same issue is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/18502

Hence closing.
