### ISSUE TITLE
Table with decimal fields cannot convert to string

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18716]
**Description:**

Table with decimal fields in the record will give bad sad error as follows when converting to string.
```ballerina
import ballerina/io;

type Person record {
    int id;
    int age = -1;
    decimal salary;
    string name;
    boolean married;
};

public function main() {
    table<Person> personTable = table{
        { key id, age, salary, name, married },
        [ { 1, 30,  300.5, "Mary", true },
          { 2, 20,  300.5, "John", true }
        ]
    };

    io:println(personTable);
}

```

```
[2019-09-06 15:31:20,251] SEVERE {b7a.log.crash} - java.math.BigDecimal cannot be cast to org.ballerinalang.jvm.values.RefValue
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to org.ballerinalang.jvm.values.RefValue
        at org.ballerinalang.jvm.TypeChecker.getType(TypeChecker.java:217)
        at org.ballerinalang.jvm.values.MapValueImpl.stringValue(MapValueImpl.java:469)
        at org.ballerinalang.jvm.values.TableValue.createStringValueDataEntry(TableValue.java:129)
        at org.ballerinalang.jvm.values.TableValue.stringValue(TableValue.java:122)
        at org.ballerinalang.jvm.values.RefValue.stringValue(RefValue.java:44)
        at org.ballerinalang.jvm.values.TableValue.toString(TableValue.java:118)
        at org.ballerinalang.stdlib.io.nativeimpl.PrintlnAny.println(PrintlnAny.java:52)
        at ballerina.io.print.println(print.bal:23)
        at test.main(test.bal:19)
        at ___init.$lambda$main$(.)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:472)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:235)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:205)
        at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
This is fixed already. Tested with 1.0.1 version and hence closing the issue.
