### ISSUE TITLE
Async remote calls results in BAD. SAD error

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18752]
**Description:**
Please consider following from `asyncronous-invocation` guide.

```ballerina
import ballerina/http;
import ballerina/log;

listener http:Listener asyncServiceEP = new(9090);

# Service is to be exposed via HTTP/1.1.
@http:ServiceConfig {
    basePath:"/quote-summary"
}
service AsyncInvoker on asyncServiceEP {

    # Resource for the GET requests of quote service.
    #
    # + caller - Represents the remote client's endpoint
    # + req - Represents the client request
    @http:ResourceConfig {
        methods:["GET"],
        path:"/"
    }
    resource function getQuote(http:Caller caller, http:Request req) {
        // Endpoint for the stock quote backend service
        http:Client nasdaqServiceEP = new("http://localhost:9095");
        http:Response finalResponse = new;
        string responseStr = "";

        log:printInfo(" >> Invoking services asynchrnounsly...");

        // 'start' allows you to invoke a functions  asynchronously. Following three
        // remote invocation returns without waiting for response.

        // Calling the backend to get the stock quote for GOOG asynchronously
        future<http:Response|error> f1 = start nasdaqServiceEP->get("/nasdaq/quote/GOOG");

        log:printInfo(" >> Invocation completed for GOOG stock quote! Proceed without
        blocking for a response.");

        // Calling the backend to get the stock quote for APPL asynchronously
        future<http:Response|error> f2 = start nasdaqServiceEP->get("/nasdaq/quote/APPL");

        log:printInfo(" >> Invocation completed for APPL stock quote! Proceed without
        blocking for a response.");

        // Calling the backend to get the stock quote for MSFT asynchronously
        future<http:Response|error> f3 = start nasdaqServiceEP->get("/nasdaq/quote/MSFT");

        log:printInfo(" >> Invocation completed for MSFT stock quote! Proceed without
        blocking for a response.");

        // Initialize empty json to add results from backed call
        json responseJson = ();

        // ‘wait` blocks until the previously started async function returns.
        // Append the results from all the responses of stock data backend
        var response1 = wait f1;
        if (response1 is http:Response) {
            var payload = response1.getTextPayload();
            if (payload is string) {
                responseStr = payload;
            } else {
                log:printError("Failed to retrive the payload");
            }
            // Add the response from /GOOG endpoint to responseJson file
            json goog = { GOOG: responseStr};
            responseJson = checkpanic responseJson.mergeJson(goog);
        } else {
            string errorMsg = <string>response1.detail()["message"];
            log:printError(errorMsg);
            json goog = { GOOG: errorMsg};
            responseJson = checkpanic responseJson.mergeJson(goog);
        }

        var response2 = wait f2;
        if (response2 is http:Response) {
            var payload = response2.getTextPayload();
            if (payload is string) {
                responseStr = payload;
            } else {
                log:printError("Failed to retrive the payload");
            }
            // Add the response from /APPL endpoint to responseJson file
            json appl = { APPL: responseStr};
            responseJson = checkpanic responseJson.mergeJson(appl);
        } else {
            string errorMsg = <string>response2.detail()["message"];
            log:printError(errorMsg);
            json appl = { APPL: errorMsg};
            responseJson = checkpanic responseJson.mergeJson(appl);
        }

        var response3 = wait f3;
        if (response3 is http:Response) {
            var payload = response3.getTextPayload();
            if (payload is string) {
                responseStr = payload;
            } else {
                log:printError("Failed to retrive the payload");
            }
            // Add the response from /MSFT endpoint to responseJson file
            json msft = { MSFT: responseStr};
            responseJson = checkpanic responseJson.mergeJson(msft);
            

        } else {
            string errorMsg = <string>response3.detail()["message"];
            log:printError(errorMsg);
            json msft = { MSFT: errorMsg};
            responseJson = checkpanic responseJson.mergeJson(msft);
        }

        // Send the response back to the client
        finalResponse.setJsonPayload(<@untainted> responseJson);
        log:printInfo(" >> Response : " + responseJson.toString());
        var result = caller -> respond(finalResponse);
        if (result is error){
            log:printError("Error sending response", err = result);
        }
    }
}

function remoteMethod(http:Client serviceEP, string path) returns future<http:Response|error> {
    return start invoke(serviceEP, path);
}

function invoke(http:Client serviceEP, string path) returns http:Response|error {
    return serviceEP->get(path);
}
```

Running this results in a bad sad error with 
```
[2019-09-07 09:01:36,371] SEVERE {b7a.log.crash} - Illegal method name "$Client.get$lambda$0$" in class bal-org/stock_quote_summary_service/$value$AsyncInvoker__service_0 
java.lang.ClassFormatError: Illegal method name "$Client.get$lambda$0$" in class bal-org/stock_quote_summary_service/$value$AsyncInvoker__service_0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bal-org.stock_quote_summary_service.___init.bal-org_stock_quote_summary_service_0_1_0__init_(stock_quote_summary_service:10)
	at bal-org.stock_quote_summary_service.___init.$moduleInit(stock_quote_summary_service:65535)
	at bal-org.stock_quote_summary_service.___init.$lambda$$moduleInit$(stock_quote_summary_service)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:475)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:235)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:205)
	at java.lang.Thread.run(Thread.java:748)
```

If I take `nasdaqServiceEP->get("/nasdaq/quote/GOOG");` and wrap it in a function and call that function async then it works fine.

This relates to https://github.com/ballerina-platform/ballerina-lang/issues/17345
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Verified to be fixed.
