### ISSUE TITLE
Bad, sad error when invoking a valid nil-returning anonymous function passed as an argument for a non-nil returning param 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19046]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    xyz(function () { }); // function () returns () { } also crashes
}

public function xyz(function() returns any|error func) {
    var result = func();
}
```

ballerina-internal.log
```
[2019-09-16 11:16:14,083] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.jvm.values.FPValue.apply(FPValue.java:58)
	at abc.xyz(abc.bal:6)
	at abc.main(abc.bal:2)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:483)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by SupunS** [comment]
Fixed with #19589
