### ISSUE TITLE
Issue running generated jar file

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#19110]
**Description:**

When I tried to run the generated jar file, got the following error on the log file.

But program can be executed using `ballerina run main.bal` command.

The program has a client endpoint which uses `ballerina.home` which seem to be causing the issue. Got this code from a BBE - https://v1-0.ballerina.io/learn/by-example/secured-service-with-basic-auth.html.

```ballerina
http:Client httpEndpoint = new ("http://IP_HERE", {
    auth: {
        authHandler: outboundBasicAuthHandler
    },
    secureSocket: {
        trustStore: {
            path: "${ballerina.home}/bre/security/ballerinaTruststore.p12",
            password: "ballerina"
        }
    }
});
```

I think undefined properties should be handled properly in the runtime.

```
[2019-09-19 03:01:47,924] SEVERE {b7a.log.crash} - System property ballerina.home is not specified
java.lang.RuntimeException: System property ballerina.home is not specified
	at org.wso2.transport.http.netty.contractimpl.common.Util.substituteVariables(Util.java:570)
	at org.wso2.transport.http.netty.contract.config.SslConfiguration.setTrustStoreFile(SslConfiguration.java:81)
	at org.ballerinalang.net.http.HttpUtil.populateSSLConfiguration(HttpUtil.java:1278)
	at org.ballerinalang.net.http.HttpUtil.populateSenderConfigurations(HttpUtil.java:1161)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:101)
	at ballerina.http.client_endpoint.createSimpleHttpClient(client_endpoint.bal:259)
	at ballerina.http.$value$HttpClient.__init(http_client.bal:32)
	at ballerina.http.$value$HttpClient.call(http_client.bal)
	at ballerina.http.http_client.createClient(http_client.bal:204)
	at ballerina.http.$value$HttpSecureClient.__init(http_secure_client.bal:35)
	at ballerina.http.$value$HttpSecureClient.call(http_secure_client.bal)
	at ballerina.http.http_secure_client.createHttpSecureClient(http_secure_client.bal:267)
	at ballerina.http.$value$HttpCachingClient.__init(caching/http_caching_client.bal:94)
	at ballerina.http.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:324)
	at ballerina.http.client_endpoint.checkForRetry(client_endpoint.bal:400)
	at ballerina.http.client_endpoint.initialize(client_endpoint.bal:369)
	at ballerina.http.$value$Client.__init(client_endpoint.bal:47)
	at ballerina.http.$value$Client.call(client_endpoint.bal)
	at ___init.___init_(.:13)
	at ___init.$moduleInit(.:65535)
	at ___init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:194)
	at ___init.main(.)

[2019-09-19 03:01:47,933] SEVERE {b7a.log.crash} - System property ballerina.home is not specified
java.lang.RuntimeException: System property ballerina.home is not specified
	at org.wso2.transport.http.netty.contractimpl.common.Util.substituteVariables(Util.java:570)
	at org.wso2.transport.http.netty.contract.config.SslConfiguration.setTrustStoreFile(SslConfiguration.java:81)
	at org.ballerinalang.net.http.HttpUtil.populateSSLConfiguration(HttpUtil.java:1278)
	at org.ballerinalang.net.http.HttpUtil.populateSenderConfigurations(HttpUtil.java:1161)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:101)
	at ballerina.http.client_endpoint.createSimpleHttpClient(client_endpoint.bal:259)
	at ballerina.http.$value$HttpClient.__init(http_client.bal:32)
	at ballerina.http.$value$HttpClient.call(http_client.bal)
	at ballerina.http.http_client.createClient(http_client.bal:204)
	at ballerina.http.$value$HttpSecureClient.__init(http_secure_client.bal:35)
	at ballerina.http.$value$HttpSecureClient.call(http_secure_client.bal)
	at ballerina.http.http_secure_client.createHttpSecureClient(http_secure_client.bal:267)
	at ballerina.http.$value$HttpCachingClient.__init(caching/http_caching_client.bal:94)
	at ballerina.http.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:324)
	at ballerina.http.client_endpoint.checkForRetry(client_endpoint.bal:400)
	at ballerina.http.client_endpoint.initialize(client_endpoint.bal:369)
	at ballerina.http.$value$Client.__init(client_endpoint.bal:47)
	at ballerina.http.$value$Client.call(client_endpoint.bal)
	at ___init.___init_(.:13)
	at ___init.$moduleInit(.:65535)
	at ___init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:194)
	at ___init.main(.)

[2019-09-19 03:01:47,935] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at ___init.___stop_(.:28)
	at ___init.$lambda$___stop_(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:483)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:194)
	at ___init.$moduleStop(.)
	at ___init$SignalListener.run(Unknown Source)

[2019-09-19 03:01:47,936] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at ___init.___stop_(.:28)
	at ___init.$lambda$___stop_(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:483)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:194)
	at ___init.$moduleStop(.)
	at ___init$SignalListener.run(Unknown Source)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Runtime Exception throws inside http module when replacing system variables in the path.  So, it should be handled  inside there. Ballerina get crashed due to not setting property at initiation. IMO behavior might be ok since error log clear state property not set and we can't proceed with that. Need to check with stdlib guys.

**Comment by Bhashinee** [comment]
Fixed from above PR
