### ISSUE TITLE
Error when adding a module from module template in Windows

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#19337]
**Description:**
The following error is occurring when trying to add a module using a module template in Windows. This works fine in OS X.
```
[2019-10-09 09:35:37,361] SEVERE {b7a.log.crash} - Illegal character in opaque part at index 11: jar:file:C:\Users\wso2\.ballerina\balo_cache\wso2\hello_world_service\1.0.0\hello_world_service-2019r3-any-1.0.0.balo 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\Users\wso2\.ballerina\balo_cache\wso2\hello_world_service\1.0.0\hello_world_service-2019r3-any-1.0.0.balo
	at java.net.URI.create(URI.java:852)
	at org.ballerinalang.packerina.cmd.AddCommand.applyBaloTemplate(AddCommand.java:265)
	at org.ballerinalang.packerina.cmd.AddCommand.createModule(AddCommand.java:249)
	at org.ballerinalang.packerina.cmd.AddCommand.execute(AddCommand.java:198)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\wso2\.ballerina\balo_cache\wso2\hello_world_service\1.0.0\hello_world_service-2019r3-any-1.0.0.balo
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 5 more
```

**Affected Versions:**
Ballerina 1.0.1

**OS, DB, other environment details and versions:**
Windows

**Suggested Assignees (optional):**
@hevayo 
@hemikak

**Comment by hevayo** [comment]
Please find the attached jar with the fix
[Fix19337.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716850/Fix19337.zip)

**Comment by asozio** [comment]
> Please find the attached jar with the fix
> [Fix19337.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716850/Fix19337.zip)

Tested with WSO2 Enterprise Integrator 7.0.0 on Windows 10 and resolves my issue.
Thanks @hevayo

**Comment by hevayo** [comment]
Thanka @asozio for letting us know. 

PR is merged hence closing.

**Comment by ahmedamer85** [comment]
@hevayo i getting same exception, i just installed Visual Studio Code and Ballerina, 
please let me know where to put the referenced zip

**Comment by hasithaa** [comment]
@ahmedamer85 You can use replace the original jar file with the attached zip file (it seems like it was given to Ballerina 1.0.1, but it should work for Ballerina 1.0.0 as well.). Btw, we are almost finalized with 1.0.2 release, Hopefully, we should be able to release it today. :)
