### ISSUE TITLE
In a multi-module project when third-party module gets imported the "Bad. Sad" error gets thrown if we do not use --skip-tests flag along with -a

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#19362]
**Description:**
In a multi-module project which imports a third-party custom module the "bad. Sad." error gets thrown if we build the project with the following command.

`ballerina build -a`

But the project can be successfully built if we skip the tests.

`ballerina build -a --skip-tests`

The stack trace of the error which appears in the "ballerina-internal.log" file is as follows,

`[2019-10-11 13:14:53,447] SEVERE {b7a.log.crash} - org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException 
org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.BTestRunner.formatErrorMessage(BTestRunner.java:819)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$34(BTestRunner.java:664)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:638)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:81)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:146)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.entity.TestSuite.start(TestSuite.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$34(BTestRunner.java:660)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.jvm.MapUtils.handleMapStore(MapUtils.java:49)
	at ballerina.test.$value$TestConfig.TestConfig__init_(annotations.bal:26)
	at ballerina.test.$value$TestConfig.$init(annotations.bal)
	at ballerina.test.$value$TestConfig.<init>(annotations.bal)
	at wso2.utils.tests.main_test.$annot_func$1(tests/main_test.bal:19)
	at wso2.utils.utils.$annot_func$1$lambda$(utils)
	at org.ballerinalang.jvm.values.FPValue.apply(FPValue.java:58)
	at wso2.utils.utils.wso2_utils_0_1_0__testinit_(utils:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:130)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:422)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:201)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:174)
	at java.lang.Thread.run(Thread.java:748)
 `

**Steps to reproduce:**
Download and extract the attached zip file ([blockchain-iam-group-chat.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716150/blockchain-iam-group-chat.zip)) , change directory to "blockchain-iam-group-chat" folder, and issue `ballerina build -a`. You may also have to change the path of the platform.libraries entry of the Ballerina.toml file to match with your environment. The corresponding "utils.jar" is located on the directory "utils-dir".

**Affected Versions:**
Ballerina 1.0.2-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Related Issues (optional):**
IMO, this issue is very similar to #19163 . However, the stack traces have slight difference.

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Outdated issue please re-open if it is exists in 1.2.x latest
