### ISSUE TITLE
Bad, sad error when incorrectly using checkpanic with a worker receive that does not evaluate to error

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19389]
**Description:**
$title.

Happens with both send and sync send.

**Steps to reproduce:**
```ballerina
public function main() {
    worker w1 {
        "hello" -> w2;
    }

    worker w2 {
        string s = checkpanic <- w1;
    }
}
```

ballerina-internal.log
```
[2019-10-14 13:56:07,974] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getSafeAssignErrorPattern(Desugar.java:5021)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:4158)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4129)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckPanickedExpr.accept(BLangCheckPanickedExpr.java:44)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:4845)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:876)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4820)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:913)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4820)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4860)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:4870)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4820)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4860)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:650)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4820)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4877)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:531)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4820)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:328)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:291)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:254)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:216)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:178)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:268)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.1
Language specification 2019R3
```

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19491.
