### ISSUE TITLE
ballerina add template exception

### ISSUE THREAD

**Issue by ahmedamer85** [ballerina-platform/ballerina-lang#19535]
**Description:**
[2019-10-22 16:47:31,174] SEVERE {b7a.log.crash} - Illegal character in opaque part at index 11: jar:file:C:\Users\AAmer\.ballerina\balo_cache\wso2\healthcare_service\0.1.0\healthcare_service-2019r3-any-0.1.0.balo 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\Users\AAmer\.ballerina\balo_cache\wso2\healthcare_service\0.1.0\healthcare_service-2019r3-any-0.1.0.balo
	at java.net.URI.create(URI.java:852)
	at org.ballerinalang.packerina.cmd.AddCommand.applyBaloTemplate(AddCommand.java:265)
	at org.ballerinalang.packerina.cmd.AddCommand.createModule(AddCommand.java:249)
	at org.ballerinalang.packerina.cmd.AddCommand.execute(AddCommand.java:198)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\AAmer\.ballerina\balo_cache\wso2\healthcare_service\0.1.0\healthcare_service-2019r3-any-0.1.0.balo
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 5 more

**Steps to reproduce:**
run the following command 
$ ballerina add -t wso2/healthcare_service healthcare_service

**Affected Versions:**
Ballerina 1.0.1
 
**OS, DB, other environment details and versions:**
Windows 10 Pro
64-bit

**Comment by hasithaa** [comment]
This is a known issue https://github.com/ballerina-platform/ballerina-lang/issues/19337 and Fixed in 1.0.x branch. This fix will be available with Ballerina 1.0.2 release.
