### ISSUE TITLE
(bug?)java.lang.NoClassDefFoundError: org/ballerinalang/stdlib/time/nativeimpl/CurrentTime

### ISSUE THREAD

**Issue by chenjianxin** [ballerina-platform/ballerina-lang#19562]
version: 1.0.1
OS: WSL 2 Ubuntu

I test the Time example of  ballerina by example 
**ballerina build time
 java -jar target/bin/time.jar**
output: 
```
[2019-10-24 13:50:42,174] SEVERE {b7a.log.crash} - org/ballerinalang/stdlib/time/nativeimpl/CurrentTime 
java.lang.NoClassDefFoundError: org/ballerinalang/stdlib/time/nativeimpl/CurrentTime
	at ballerina.time.timelib.currentTime(timelib.bal:158)
	at elecbuggy.time.main.main(main.bal:6)
	at elecbuggy.time.___init.$lambda$main$(time)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:493)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:238)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:208)
	at java.lang.Thread.run(Thread.java:748)
**Caused by: java.lang.ClassNotFoundException: org.ballerinalang.stdlib.time.nativeimpl.CurrentTime**
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
But if I directly run:
**ballerina  run   time**
it output : 
```
Current system time in milliseconds: 1571896393287
Created Time: 2017-03-28T23:42:45.554-05:00
Parsed Time: 2017-06-26T09:46:22.444-05:00
Current system time in ISO format: 2019-10-24T13:53:13.287+08:00
Current system time in custom format: 2019-10-24-Thu
Year: 2019
Month: 10
Day: 24
Hour: 13
Minute: 53
Second: 13
Millisecond: 287
Weekday: THURSDAY
Date: 2019:10:24
Time: 13:53:13:287
After adding a duration: 2020-11-24T13:53:14.287+08:00
After subtracting a duration: 2018-09-24T13:53:12.287+08:00
Before converting the time zone: 2017-03-28T23:42:45.554-05:00
After converting the time zone: 2017-03-29T10:12:45.554+05:30
```

**Comment by warunalakshitha** [comment]
I tried the time example with build and jar (ubuntu) and i didn't observe any issue.

```
$ ballerina -v
Ballerina 1.0.1
Language specification 2019R3

$ ballerina build time.bal
Compiling source
	time.bal

Generating executables
	time.jar
waruna@warunaj:time$ java -jar time.jar 
Current system time in milliseconds: 1572510224519
Created Time: 2017-03-28T23:42:45.554-05:00
Parsed Time: 2017-06-26T09:46:22.444-05:00
Current system time in ISO format: 2019-10-31T13:53:44.519+05:30
Current system time in custom format: 2019-10-31-Thu
Year: 2019
Month: 10
Day: 31
Hour: 13
Minute: 53
Second: 44
Millisecond: 519
Weekday: THURSDAY
Date: 2019:10:31
Time: 13:53:44:519
After adding a duration: 2020-11-30T13:53:45.519+05:30
After subtracting a duration: 2018-09-30T13:53:43.519+05:30
Before converting the time zone: 2017-03-28T23:42:45.554-05:00
After converting the time zone: 2017-03-29T10:12:45.554+05:30
```

**Comment by SupunS** [comment]
@chenjianxin Are you still facing this issue?

**Comment by SupunS** [comment]
Update: This issue arise when you compile the sample as a module.

Looks like this happens because the current module name `time` is same as one of the imported module names `ballerina/time`. The org-name seems to be ignored. If I change the module name of the sample to something else, then it works fine.

**Comment by MaryamZi** [comment]
> Update: This issue arise when you compile the sample as a module.
> 
> Looks like this happens because the current module name `time` is same as one of the imported module names `ballerina/time`. The org-name seems to be ignored. If I change the module name of the sample to something else, then it works fine.

The same was reported in https://github.com/ballerina-platform/ballerina-lang/issues/19927 and should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/20261. @grainier

**Comment by grainier** [comment]
#20261 only fixes compile time issue. But even after that, I'm getting; 
```
grainier@Grainiers-MacBook-Pro  ~/Desktop/timetest/target/bin > java -jar time.jar
error: java.lang.NoClassDefFoundError message=org/ballerinalang/stdlib/time/nativeimpl/ExternMethods cause=error java.lang.ClassNotFoundException message=org.ballerinalang.stdlib.time.nativeimpl.ExternMethods
	at ballerina.time:externCurrentTime(timelib.bal:65535)
	   ballerina.time:currentTime(timelib.bal:288)
	   grainier.time:main(main.bal:5)
```

**Comment by hevayo** [comment]
Closing since this issue is no longer relevant in SL
