### ISSUE TITLE
Error coming while using Jeager (Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by ShanJayaweera** [ballerina-platform/ballerina-lang#19582]
**Description:**
I m using your default Ballerina APIs for tracing and use jaeger as the default tracing client. But while using jaeger it gives an unexpected error after we run the program for some time.

Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at com.uber.jaeger.reporters.protocols.JaegerThriftSpanConverter.buildLogs(JaegerThriftSpanConverter.java:71)
	at com.uber.jaeger.reporters.protocols.JaegerThriftSpanConverter.convertSpan(JaegerThriftSpanConverter.java:53)
	at com.uber.jaeger.senders.ThriftSender.append(ThriftSender.java:55)
	at com.uber.jaeger.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:149)
	at com.uber.jaeger.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:182)
	at java.lang.Thread.run(Thread.java:748)

![Screenshot from 2019-10-25 10-58-11](https://user-images.githubusercontent.com/51467737/67545467-c81a0380-f716-11e9-834d-152f2a5a3ab0.png)

![Screenshot from 2019-10-25 11-02-38](https://user-images.githubusercontent.com/51467737/67545504-f39cee00-f716-11e9-8375-c0b9650accd5.png)

Hope Jaeger version should be upgraded. 

**Steps to reproduce:**

**Affected Versions:**
1.0.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/jaegertracing/jaeger-client-java/issues/334

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
This is due to a bug in the jaeger client version 0.27.0, we have used.  (Related issues: https://github.com/jaegertracing/jaeger-client-java/issues/363, https://github.com/jaegertracing/jaeger-client-java/issues/334). We will upgrade the jaeger client version and add the fix in the upcoming patch release.

**Comment by pubudu91** [comment]
Closing this since it has been fixed in #19801
