### ISSUE TITLE
[WebSub] ConcurrentModificationException from the Hub

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19591]
**Description:**
$title.

Need to check all the hub methods.

**Steps to reproduce:**
```cmd
[2019-10-24 20:15:18,786] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.ballerinalang.net.websub.hub.Hub.unregisterSubscription(Hub.java:161)
	at org.ballerinalang.net.websub.hub.Hub.registerSubscription(Hub.java:132)
	at org.ballerinalang.net.websub.nativeimpl.AddSubscription.addSubscription(AddSubscription.java:47)
	at ballerina.websub.natives.addSubscription(natives.bal:46)
	at ballerina.websub.hub_service.verifyIntentAndAddSubscription(hub_service.bal:329)
	at ballerina.websub.$value$_anonService_0__service_1.hub(hub_service.bal:95)
	at ballerina.websub.$value$_anonService_0__service_1.call(hub_service.bal)
	at org.ballerinalang.jvm.values.connector.Executor.lambda$submit$0(Executor.java:71)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:496)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:238)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:208)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:195)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:139)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.entity.TestSuite.start(TestSuite.java:319)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$34(BTestRunner.java:660)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:638)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:81)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
```

**Affected Versions:**
1.0.1 with the WebSub JARs.

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/19677, hence closing
