### ISSUE TITLE
Disabled a unit test in ClosedRecordEquivalencyTest

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#19665]
**Description:**
In order to pass all the tests cases in PR #19540, the unit test org.ballerinalang.test.record.ClosedRecordEquivalencyTest.testEqOfPublicStructs is disabled. This test fails only in the Travis. But it works fine in local machine.

**Steps to reproduce:**

**Affected Versions:**
v1.0.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
What does the error log say?

**Comment by KavinduZoysa** [comment]
This is the error log. According to that, it is a conversion error.

```
ballerina-test-suite > jballerina-test > org.ballerinalang.test.record.ClosedRecordEquivalencyTest > testEqOfPublicStructs FAILED
    org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina/lang.typedesc}ConversionError 
    	at ballerina.lang_typedesc:constructFrom(typedesc_lib.bal:48)
    	   testorg.closed-rec-equiv:testEqOfPublicStructs(closed_record_equivalency.bal:81)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:405)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1104)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:159)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:1148)
        at org.ballerinalang.test.record.ClosedRecordEquivalencyTest.testEqOfPublicStructs(ClosedRecordEquivalencyTest.java:60)

        Caused by:
        org.ballerinalang.util.exceptions.BLangRuntimeException: error: {ballerina/lang.typedesc}ConversionError 
        	at ballerina.lang_typedesc:constructFrom(typedesc_lib.bal:48)
        	   testorg.closed-rec-equiv:testEqOfPublicStructs(closed_record_equivalency.bal:81)
```

**Comment by MaryamZi** [comment]
Enabled in https://github.com/ballerina-platform/ballerina-lang/commit/7bcaabd540d43aedc414fb984c78e8f4f27caa4c, merged via https://github.com/ballerina-platform/ballerina-lang/pull/30506.
