### ISSUE TITLE
[NATS] Program crashes on invalid server URL

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19740]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/nats;
 
nats:Connection conn = new("/localhost:4222"); // invalid
 
listener nats:Listener lis = new(conn);
 
@nats:SubscriptionConfig {
    subject: "demo"
}
service demo on lis {
    resource function onMessage(nats:Message msg, string data) {
        io:println(data);
    }
 
    resource function onError(nats:Message msg, nats:Error err) {
        io:println(err);
    }
}
```

ballerina-internal.log
```
[2019-11-04 08:25:49,823] SEVERE {b7a.log.crash} - Bad server URL: /localhost:4222 
java.lang.IllegalArgumentException: Bad server URL: /localhost:4222
	at io.nats.client.Options$Builder.servers(Options.java:717)
	at org.ballerinalang.nats.connection.Init.init(Init.java:103)
	at ballerina.nats.$value$Connection.init(connection/connection.bal:33)
	at ballerina.nats.$value$Connection.call(connection/connection.bal)
	at ballerina.nats.$value$Connection.__init(connection/connection.bal:30)
	at ballerina.nats.$value$Connection.call(connection/connection.bal)
	at ___init.___init_(.:4)
	at ___init.$moduleInit(.:65535)
	at ___init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: unable to parse server URI: /localhost:4222
	at io.nats.client.Options.parseURIForServer(Options.java:1509)
	at io.nats.client.Options$Builder.servers(Options.java:715)
	... 12 more
 
[2019-11-04 08:25:49,828] SEVERE {b7a.log.crash} - Bad server URL: /localhost:4222 
java.lang.IllegalArgumentException: Bad server URL: /localhost:4222
	at io.nats.client.Options$Builder.servers(Options.java:717)
	at org.ballerinalang.nats.connection.Init.init(Init.java:103)
	at ballerina.nats.$value$Connection.init(connection/connection.bal:33)
	at ballerina.nats.$value$Connection.call(connection/connection.bal)
	at ballerina.nats.$value$Connection.__init(connection/connection.bal:30)
	at ballerina.nats.$value$Connection.call(connection/connection.bal)
	at ___init.___init_(.:4)
	at ___init.$moduleInit(.:65535)
	at ___init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: unable to parse server URI: /localhost:4222
	at io.nats.client.Options.parseURIForServer(Options.java:1509)
	at io.nats.client.Options$Builder.servers(Options.java:715)
	... 12 more
 
[2019-11-04 08:25:49,836] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at ___init.___stop_(.:6)
	at ___init.$lambda$___stop_(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:178)
	at ___init.$moduleStop(.)
	at ___init$SignalListener.run(Unknown Source)
 
[2019-11-04 08:25:49,840] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at ___init.___stop_(.:6)
	at ___init.$lambda$___stop_(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:178)
	at ___init.$moduleStop(.)
	at ___init$SignalListener.run(Unknown Source)
```

**Affected Versions:**
1.0.3

**Comment by kalaiyarasiganeshalingam** [comment]
NPE error needs to be fix in the jballerina. Please reffer [#20274 ]
