### ISSUE TITLE
Receiving a ballerina-internal.log during project build time

### ISSUE THREAD

**Issue by SabinaPrasadhi** [ballerina-platform/ballerina-lang#19766]
**Description:**
I received a ballerina-internal.log during the build time of a sample project which I've created which includes a sample module.

**Steps to reproduce:**
1. Navigate inside the project directory using the terminal
2. Type command 'ballerina build -a'

**Affected Versions:**
Ballerina v1.0.1

**OS, DB, other environment details and versions:**
OS - Ubuntu

The compressed zip folder of the sample project:
[sample1.zip](https://github.com/ballerina-platform/ballerina-lang/files/3803201/sample1.zip)

![Screenshot from 2019-11-04 12-27-27](https://user-images.githubusercontent.com/38970634/68109156-da165600-ff0f-11e9-9a98-38dccc73721b.png)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Copying the error from the internal log attached.

```
[2019-11-04 12:27:12,361] SEVERE {b7a.log.crash} - java.lang.RuntimeException: Class 'prasadhi.sample1_1.sample1.1' cannot be loaded in-memory 
org.ballerinalang.util.exceptions.BallerinaException: java.lang.RuntimeException: Class 'prasadhi.sample1_1.sample1.1' cannot be loaded in-memory
	at org.ballerinalang.testerina.core.BTestRunner.lambda$processProgramFile$6(BTestRunner.java:316)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.processProgramFile(BTestRunner.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$buildSuites$4(BTestRunner.java:285)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.ballerinalang.testerina.core.BTestRunner.buildSuites(BTestRunner.java:273)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:156)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:81)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: java.lang.RuntimeException: Class 'prasadhi.sample1_1.sample1.1' cannot be loaded in-memory
	at org.ballerinalang.testerina.util.TestarinaClassLoader.loadClass(TestarinaClassLoader.java:69)
	at org.ballerinalang.testerina.core.BTestRunner.packageProcessed(BTestRunner.java:380)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$processProgramFile$6(BTestRunner.java:311)
	... 12 more
Caused by: java.lang.ClassNotFoundException: prasadhi.sample1_1.sample1.1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.ballerinalang.testerina.util.TestarinaClassLoader.loadClass(TestarinaClassLoader.java:67)
	... 14 more
 ```

@SabinaPrasadhi could you please try renaming your module to have a name that does not contain periods (`.`), as a workaround, until this issue is fixed?

**Comment by hevayo** [comment]
Unable to reproduce in 1.2.13 please re-open if this issue still exists
