### ISSUE TITLE
Unable to retreive User-Defined Types (UDT) through data clients

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#19773]
**Description:**
As I checked the user defined types with insert and update statements in oracle[1] and postgresql[2] databases. In both database, I could be able to insert the UDT data. Also I could be able to retrieve the UDT data in oracle. But in Postgresql, when retrieving I'm getting the error as in [3] at line [4]. For this I checked the type of the data returned, in Oracle I'm getting the udt as oracle.sql.STRUCT type and in postgresql, I'm getting it as org.postgresql.util.PGobject type.

[1]
```
import ballerina/io;
import ballerinax/java.jdbc;
import ballerina/jsonutils;

jdbc:Client testDB = new({
    url: "jdbc:oracle:thin:@localhost:49161:xe",
    username: "system",
    password: "oracle",
    poolOptions: { maximumPoolSize: 1 }
});

public function main() {

    var ret = testDB->update("CREATE TYPE Address_Type AS OBJECT (
                                 street_addr VARCHAR2(50),
                                 city VARCHAR2(50),
                                 state VARCHAR2(50)
                              );");
    handleUpdate(ret, "Create Type");

    ret = testDB->update("CREATE TABLE people (
                                  id number(10),
                                  name VARCHAR2(50),
                                  home_address Address_Type
                              )");
    handleUpdate(ret, "Create Table");

     jdbc:Parameter para0 = { sqlType: jdbc:TYPE_INTEGER, value: 3 };
     jdbc:Parameter para1 = { sqlType: jdbc:TYPE_VARCHAR, value: "Tom Kyte" };
     jdbc:Parameter para2 = { sqlType: jdbc:TYPE_VARCHAR, value: "3 Street" };
     jdbc:Parameter para3 = { sqlType: jdbc:TYPE_VARCHAR, value: "R" };
     jdbc:Parameter para4 = { sqlType: jdbc:TYPE_VARCHAR, value: "VA" };

    ret = testDB->update("INSERT INTO people VALUES (?, ?, Address_Type(?, ?, ?))", para0, para1, para2, para3, para4);
    handleUpdate(ret, "update Table");

    var selectRet = trap testDB->select("SELECT * FROM people", ());
    table<record {}> dt;
    if (selectRet is table<record {}>) {
        json jsonConversionRet = jsonutils:fromTable(selectRet);
        io:print("JSON: ");
        io:println(jsonConversionRet.toJsonString());
    } else {
        error err = selectRet;
        io:println("Select data from people table failed: ", <string> err.detail()["message"]);
    }

    var stopRet = testDB.stop();
    if (stopRet is error) {
        io:println(stopRet.detail()["message"]);
    }
}

function handleUpdate(jdbc:UpdateResult|error returned, string message) {
    if (returned is jdbc:UpdateResult) {
        io:println(message + " status: " + io:sprintf("%s", returned.updatedRowCount));
    } else {
        io:println("Message: ", returned.detail()["message"]);
    }
}
```
[2]
```
import ballerina/io;
import ballerinax/java.jdbc;
import ballerina/jsonutils;

jdbc:Client testDB = new({
    url: "jdbc:postgresql://localhost:13800/udt",
    username: "postgres",
    password: "docker",
    poolOptions: { maximumPoolSize: 5 }
});

public function main() {

    var ret = testDB->update("CREATE TYPE Address_Type AS (
                                 street_addr VARCHAR,
                                 city VARCHAR,
                                 state VARCHAR,
                                 zip_code INT
                              );");
    handleUpdate(ret, "Create Type");

    ret = testDB->update("CREATE TABLE people (
                                  id serial PRIMARY KEY,
                                  name VARCHAR,
                                  home_address Address_Type
                              );");
    handleUpdate(ret, "Create Table");

    jdbc:Parameter para0 = { sqlType: jdbc:TYPE_INTEGER, value: 2 };
    jdbc:Parameter para1 = { sqlType: jdbc:TYPE_VARCHAR, value: "Tom Kyte" };
    jdbc:Parameter para2 = { sqlType: jdbc:TYPE_VARCHAR, value: "2 Street" };
    jdbc:Parameter para3 = { sqlType: jdbc:TYPE_VARCHAR, value: "R" };
    jdbc:Parameter para4 = { sqlType: jdbc:TYPE_VARCHAR, value: "VA" };
    jdbc:Parameter para5 = { sqlType: jdbc:TYPE_INTEGER, value: 46 };

    ret = testDB->update("INSERT INTO people VALUES (?, ?, ROW(?,?,?,?))", para0, para1, para2, para3, para4, para5);

    var selectRet = trap testDB->select("SELECT * FROM people", ());
    table<record {}> dt;
    if (selectRet is table<record {}>) {
        json jsonConversionRet = jsonutils:fromTable(selectRet);
        io:print("JSON: ");
        io:println(jsonConversionRet.toJsonString());
    } else {
        error err = selectRet;
        io:println("Select data from people table failed: ", <string> err.detail()["message"]);
    }

    var stopRet = testDB.stop();
    if (stopRet is error) {
        io:println(stopRet.detail()["message"]);
    }
}

function handleUpdate(jdbc:UpdateResult|error returned, string message) {
    if (returned is jdbc:UpdateResult) {
        io:println(message + " status: " + io:sprintf("%s", returned.updatedRowCount));
    } else {
        io:println("Message: ", returned.detail()["message"]);
    }
}
```
[3]
```
[2019-11-04 11:28:52,532] SEVERE {b7a.log.crash} - org.postgresql.util.PGobject cannot be cast to java.sql.Struct
java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to java.sql.Struct
at org.ballerinalang.jvm.values.TableIterator.getStruct(TableIterator.java:168)
at org.ballerinalang.jvm.values.TableValue.getStruct(TableValue.java:277)
at org.ballerinalang.jvm.TableJSONDataSource.constructJsonData(TableJSONDataSource.java:155)
at org.ballerinalang.jvm.TableJSONDataSource.access$100(TableJSONDataSource.java:43)
at org.ballerinalang.jvm.TableJSONDataSource$DefaultJSONObjectGenerator.transform(TableJSONDataSource.java:113)
at org.ballerinalang.jvm.TableJSONDataSource.next(TableJSONDataSource.java:76)
at org.ballerinalang.jvm.values.StreamingJsonValue.serialize(StreamingJsonValue.java:97)
at org.ballerinalang.jvm.JSONGenerator.serialize(JSONGenerator.java:284)
at org.ballerinalang.jvm.values.ArrayValue.getJSONString(ArrayValue.java:894)
at org.ballerinalang.jvm.values.utils.StringUtils.getJsonString(StringUtils.java:109)
at org.ballerinalang.langlib.value.ToJsonString.toJsonString(ToJsonString.java:43)
at ballerina.lang_value.value.toJsonString(value.bal:94)
at Postgresql_Update.main(Postgresql_Update.bal:44)
at ___init.$lambda$main$(.)
```
[4]
https://github.com/ballerina-platform/ballerina-lang/blob/416d346397c06ae3cdf4ebaeadd8be3353800614/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java#L168
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
@niveathika Is this valid with new impl? Shall we close issue if it is not valid?

**Comment by niveathika** [comment]
@mohanvive Yes, this is valid. Revamped SQL connector still doesn't have UDT support. We will add this in one of the coming sprints.
