### ISSUE TITLE
[JBallerina] LocksInMainTest fails intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#19778]
**Description:**
$subject in `ballerina-1.0.x` branch. Please refer the below log:

```
ballerina-test-suite > jballerina-test > org.ballerinalang.test.lock.LocksInMainTest > testThrowErrorInsideTryCatchFinallyInsideLock FAILED
    java.lang.AssertionError: expected [worker 2 sets the string after try catch finally inside lock] but found [hello]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at org.ballerinalang.test.lock.LocksInMainTest.testThrowErrorInsideTryCatchFinallyInsideLock(LocksInMainTest.java:132)
```

Complete log: [log-fail-lockinmaintest.txt](https://github.com/ballerina-platform/ballerina-lang/files/3807576/log-fail-lockinmaintest.txt)

**Comment by ldclakmal** [comment]
Closing the issue since this is no longer valid and `ballerina-1.0.x` is not maintained.
