### ISSUE TITLE
Bad Sad Error When Running a Module

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#19826]
**Description:**
When I try to run any of the three modules other than the _webserver_ module from this project [blockchain-iam-group-chat](https://github.com/ballerina-platform/ballerina-lang/files/3818705/blockchain-iam-group-chat-Nov-7-2019.zip) I get Bad Sad Error. The _ballerina-internal.log_ file contains the following error message when I try to run holder module with the command `ballerina run target/bin/holder.jar`,

```
[2019-11-07 14:32:50,820] SEVERE {b7a.log.crash} - ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object; 
java.lang.NoSuchMethodError: ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object;
	at wso2.holder.___init.$moduleInit(holder:65535)
	at wso2.holder.___init.$lambda$$moduleInit$(holder)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:422)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:201)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:174)
	at java.lang.Thread.run(Thread.java:748)
 
[2019-11-07 14:32:50,824] SEVERE {b7a.log.crash} - ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object; 
java.lang.NoSuchMethodError: ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object;
	at wso2.holder.___init.$moduleInit(holder:65535)
	at wso2.holder.___init.$lambda$$moduleInit$(holder)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:422)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:201)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:174)
	at java.lang.Thread.run(Thread.java:748)
```
Note that this error does not get thrown in Ballerina 1.0.2 version. All the modules successfully run with Ballerina 1.0.2 version.

**Steps to reproduce:**
Download and extract the attached zip file [blockchain-iam-group-chat](https://github.com/ballerina-platform/ballerina-lang/files/3818705/blockchain-iam-group-chat-Nov-7-2019.zip) , change directory to "blockchain-iam-group-chat" folder.

Next, issue the command,

`ballerina build -a --skip-tests`

Then run the module holder by issuing,

`ballerina run target/bin/holder.jar
`

**Affected Versions:**
Ballerina 1.0.3

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Is dependency in the toml `/home/miyurud/git/ballerina-eth-utils/target/bin/utils.jar` an executable created from a another ballerina module?
If so, whats the version it was compiled from?

**Comment by miyurud** [comment]
The `utils.jar` file you mentioned has been built with some older version of Ballerina. This was the cause for this error. I got this issue solved by rebuilding the project [ballerina-eth-utils](https://github.com/miyurud/ballerina-eth-utils) with Ballerina 1.0.3 (this created a new utils.jar file). Now all the four modules of the above project runs successfully.
