### ISSUE TITLE
Bad Sad when error destrucuring assigment with in other binding patterns

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#19827]
**Description:**
Originally stated at https://github.com/ballerina-platform/ballerina-lang/issues/19619#issuecomment-546919416

```ballerina
public function main() {
    string r;
    string? message;
    int i;

    error e = error("r2", message = "msg");
    [i, error(r, message = message)] = [1, e];
}
```

Result in:
```
2019-10-28 17:43:43,277] SEVERE {b7a.log.crash} - $type$ 
java.lang.NoSuchFieldError: $type$
	at xyz.main(xyz.bal:7)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:408)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:202)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:175)
	at java.lang.Thread.run(Thread.java:748)
 
[2019-10-28 17:43:43,282] SEVERE {b7a.log.crash} - $type$ 
java.lang.NoSuchFieldError: $type$
	at xyz.main(xyz.bal:7)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:408)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:202)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:175)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

**Affected Versions:**
1.0.2
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/19660
