### ISSUE TITLE
Testerina broken in 1.0.3

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#19889]
**Description:**
Test cases in a ballerina module run fine in 1.0.2 and when upgraded to 1.0.3 the test cases crash with a nullpointer.
Following is found in the ballerina-internal.log
```
[2019-11-14 09:50:21,932] SEVERE {b7a.log.crash} - org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException 
org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.BTestRunner.formatErrorMessage(BTestRunner.java:811)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:656)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:630)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:79)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:394)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:146)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.entity.TestSuite.start(TestSuite.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:652)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.jvm.AnnotationUtils.processFPValueAnnotations(AnnotationUtils.java:91)
	at choreo.api.api.choreo_api_0_1_0__testinit_(api:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:130)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```
**Steps to reproduce:**
Can be reproduced by using mysql in the code and shutting down mysql server before building the code.

**Affected Versions:**
1.0.3

**Comment by warunalakshitha** [comment]
@riyafa  Can u attach some sample code for this?
