### ISSUE TITLE
BAD Sad: Issue with compiling a module in version 1.0.3

### ISSUE THREAD

**Issue by JanakaSandaruwan** [ballerina-platform/ballerina-lang#19914]
**Description:**
The attached ballerina module can be compiled with ballerina 1.0.0. But it gives following error in ballerina-internal.log file with ballerina 1.0.3. 

> [2019-11-15 11:58:58,095] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:434)
	at org.wso2.ballerinalang.compiler.bir.model.BIROperand.accept(BIROperand.java:36)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:477)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNonTerminator$FPLoad.accept(BIRNonTerminator.java:591)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$visit$1(BIRInstructionWriter.java:81)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:81)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:363)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:72)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:72)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:280)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$5(BIRBinaryWriter.java:187)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:187)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:89)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:236)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:295)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:259)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:216)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:178)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:60)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:394)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)

**Affected Versions:**
ballerina version 1.0.3
[CustomerService.zip](https://github.com/ballerina-platform/ballerina-lang/files/3850183/CustomerService.zip)

**Comment by rdhananjaya** [comment]
Error repro:
```ballerina
public function main() {
    int|string s;
    transaction with retries = 1 {
      s = "empty";
    }
}
```

Workaround - When we initialize the variable `s` this issue seems to go away.

Note: This looks like a closure related issue, even just touching the variable before the transaction block would stop the compiler from going into BAD-SAD state.
