### ISSUE TITLE
Error when running a module which uses modules from a different Ballerina version

### ISSUE THREAD

**Issue by MalshaL** [ballerina-platform/ballerina-lang#20068]
**Description:**
Display an error indicating the version incompatibility in the following scenario instead of the generic (bad sad) error message. 

When building and running a Ballerina module which imports modules built in other Ballerina versions, following error is thrown in the internal log.

```
[2019-11-26 14:00:30,575] SEVERE {b7a.log.crash} - org.ballerinalang.jvm.types.BRecordType.<init>(Ljava/lang/String;Lorg/ballerinalang/jvm/types/BPackage;IZI)V 
java.lang.NoSuchMethodError: org.ballerinalang.jvm.types.BRecordType.<init>(Ljava/lang/String;Lorg/ballerinalang/jvm/types/BPackage;IZI)V
	at ballerina.lang_annotations.___init.$createTypeInstances(lang.annotations)
	at ballerina.lang_annotations.___init.$createTypes(lang.annotations)
	at ballerina.lang_annotations.___init.$currentModuleInit(lang.annotations)
	at ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(lang.annotations:65535)
	at malsha.upload_to_ftp.___init.$moduleInit(upload_to_ftp:65535)
	at malsha.upload_to_ftp.___init.$lambda$$moduleInit$(upload_to_ftp)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at java.lang.Thread.run(Thread.java:748)
```

The error is resolved when all imported modules are also built in the same Ballerina version.

**Steps to reproduce:**

1. Create a Ballerina project and a module `testmodule` with one Ballerina version (e.g. 1.0.4).
2. Import a module built in a previous Ballerina version (e.g. import `wso2/ftp` version 0.3.1 which is built in Ballerina 1.0.0)
3. Build and run the `testmodule`. Above error is thrown.

**Affected Versions:**
1.0.3, 1.0.4

**Related Issues (optional):**
#19826 

**Suggested Labels (optional):**
Priority/High

**Comment by azinneera** [comment]
With the package resolution design in Swan lake, this is not reproducible.
