### ISSUE TITLE
Intermittent Nullpointer exception happens while building a micro-gw project

### ISSUE THREAD

**Issue by hasuniea** [ballerina-platform/ballerina-lang#20137]
**Description:**
An intermittent exception occurs while trying to build a micro-gw project.

[2019-11-26 08:54:15,233] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:51)
at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:79)
at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:84)
at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:53)
at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
at java.util.Optional.ifPresent(Optional.java:159)
at org.ballerinalang.tool.Main.main(Main.java:59)

**Steps to reproduce:**
1. Try to build micro-gw which relies on ballerina 1.0.0 

**Affected Versions:**
ballerina 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/18316

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Outdated issue please re-open if it exists in 1.2.x latest
