### ISSUE TITLE
Issue in building ballerina xslt module with external dependencies 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#20172]
**Description:**
Build fails when building the ballerina-xslt module after migrating the native functions to java interop, although the dependencies are added to the toml file. 
 ```
    [[platform.libraries]]
    artifactId = "axiom-api"
    version = "1.2.22"
    path = "./lib/axiom-api-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-impl"
    version = "1.2.22"
    path = "./lib/axiom-impl-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-dom"
    version = "1.2.22"
    path = "./lib/axiom-dom-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]
```

```
[2019-12-03 10:30:26,486] SEVERE {b7a.log.crash} - org/apache/axiom/om/OMDocument 
java.lang.NoClassDefFoundError: org/apache/axiom/om/OMDocument
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.ballerinalang.nativeimpl.jvm.interop.JMethodResolver.getExecutables(JMethodResolver.java:527)
	at org.ballerinalang.nativeimpl.jvm.interop.JMethodResolver.resolveByMethodName(JMethodResolver.java:114)
	at org.ballerinalang.nativeimpl.jvm.interop.JMethodResolver.resolve(JMethodResolver.java:84)
	at org.ballerinalang.nativeimpl.jvm.interop.JInteropMethodValidator.resolveJMethod(JInteropMethodValidator.java:74)
	at org.ballerinalang.nativeimpl.jvm.interop.JInteropMethodValidator.validateAndGetJMethod(JInteropMethodValidator.java:61)
	at ballerina.jvm.$value$InteropValidator.validateAndGetJMethod(interop.bal:90)
	at ballerina.jvm.$value$InteropValidator.call(interop.bal)
	at ballerina.compiler_backend_jvm.interop.interop_method_gen.createJMethodWrapper(interop/interop_method_gen.bal:135)
	at ballerina.compiler_backend_jvm.interop.interop_method_gen.createJInteropFunctionWrapper(interop/interop_method_gen.bal:127)
	at ballerina.compiler_backend_jvm.interop.external_method_gen.createExternalFunctionWrapper(interop/external_method_gen.bal:180)
	at ballerina.compiler_backend_jvm.jvm_package_gen.generateClassNameMappings(jvm_package_gen.bal:477)
	at ballerina.compiler_backend_jvm.jvm_package_gen.generatePackage(jvm_package_gen.bal:149)
	at ballerina.compiler_backend_jvm.main.generateJarBinary(main.bal:86)
	at ballerina.compiler_backend_jvm.main.main(main.bal:60)
	at ballerina.compiler_backend_jvm.___init.$lambda$main$(compiler_backend_jvm)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.axiom.om.OMDocument
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
```

**Comment by warunalakshitha** [comment]
This was due to missing some dependencies in libs. Once you add those axiom libs issue got resolved,
