### ISSUE TITLE
JDBC Driver for MySQL not packed when building a Ballerina project

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#20521]
**Description:**
I tried to build a ballerina project which uses MySQL JDBC driver and it gave the bad sad error.
Below is the log that appeared in the ballerina-internal.log file.

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyLibsFromBalo(CopyNativeLibTask.java:227)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedLib(CopyNativeLibTask.java:149)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedLibs(CopyNativeLibTask.java:135)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedLibs(CopyNativeLibTask.java:136)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedJarsForModules(CopyNativeLibTask.java:104)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.execute(CopyNativeLibTask.java:89)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:393)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
```
The issued resolved once I moved the JDBC driver from resources directory to a new directory which I manually created.

**Steps to reproduce:**
1. Use a simple ballerina service which uses JDBC driver
2. Place the MySQL JDBC driver inside the resources directory
3. Configure the JDBC driver path inside the Ballerina.toml file
3. Run `ballerina build`

**Affected Versions:**
v1.0.5

**Suggested Labels (optional):**
Bug

**Comment by warunalakshitha** [comment]
When you move your jar to any other directory issue will not happen. Seems issue is specific to resources directory.
