### ISSUE TITLE
Iterating a data structure with foreach compiles but crashes runtime.

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#20532]
**Description:**
Iterating a data structure with `foreach` compiles but crashes runtime. Please see the code snippet below.

**Steps to reproduce:**

```
$ cat bug-001.bal 
public function main() {
    var fooList = [
        ["A", 1],
        ["B", 2]
    ];
    foreach var foo in fooList {}
}
$ make
time -f 'Build time: %e seconds' ballerina build --offline -o build/bug-001.jar bug-001.bal
Compiling source
        bug-001.bal

Generating executables
        build/bug-001.jar
Build time: 9.22 seconds
$ java -jar build/bug-001.jar 
ballerina: Oh no, something really went wrong.

The `ballerina-internal.log` file located in the current directory
will indicate what the problem is.
We really appreciate it if you can share with us, the code
that broke Ballerina, together with this log file by creating a
bug report in https://github.com/ballerina-platform/ballerina-lang/issues.

$ cat ballerina-internal.log 
[2020-01-06 20:00:35,142] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.ballerinalang.jvm.values.ArrayValueImpl.add(ArrayValueImpl.java:388)
        at bug-001.main(bug-001.bal:3)
        at ___init.$lambda$main$(.)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
        at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:178)
        at ___init.main(.)
 
[2020-01-06 20:00:35,154] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.ballerinalang.jvm.values.ArrayValueImpl.add(ArrayValueImpl.java:388)
        at bug-001.main(bug-001.bal:3)
        at ___init.$lambda$main$(.)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
        at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:178)
        at ___init.main(.)
```

**Affected Versions:**
```
$ ballerina --version
jBallerina 1.1.0
Language specification 2019R3
Ballerina tool 0.8.0
```
**OS, DB, other environment details and versions:**

```
$ which java 
/usr/lib/ballerina/dependencies/jdk8u202-b08-jre/bin/java
$ java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by janihur** [comment]
The workaround (?) is to explicitly define the variable type. The following compiles and runs fine:

```
public function main() {
    [string, int][] fooList = [
        ["A", 1],
        ["B", 2]
    ];
    foreach var foo in fooList {}
}
```

**Comment by MaryamZi** [comment]
Observed the same without the `foreach` too. 

```ballerina
public function main() {
    var fooList = [
        ["A", 1],
        ["B", 2]
    ];
}
```

An incorrect instruction seems to be generated with the inferred type. The error occurs when trying to create the `["A", 1]` array - ["A" is attempted to be added to a `string[]`](https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java#L388) where it should be added to a `string|int[]`.

Also, the inferred type seems to be `((string|int)[]|(string|int)[])[]`, but using that specifically results in a compilation error.
```ballerina
public function main() {
    ((string|int)[]|(string|int)[])[] fooList = [
        ["A", 1], // expected '((string|int)[]|(string|int)[])', found 'any[]'
        ["B", 2]  // expected '((string|int)[]|(string|int)[])', found 'any[]'  
    ];
}
```

But using `((string|int)[])[]` works.

**Comment by grainier** [comment]
There's an issue with the inferring logic. `((string|int)[]|(string|int)[])[]` is wrong, cause it'll lead to ambiguity. So the logic needs to be fixed to return `((string|int)[])[]` instead of the above union array.

PS: This will get fixed on https://github.com/ballerina-platform/ballerina-lang/pull/20564
