### ISSUE TITLE
Placing mysql-connector jar file in module's resource directory causes Bad Sad.

### ISSUE THREAD

**Issue by TomIsoGriv** [ballerina-platform/ballerina-lang#20643]
Since Ballerina was complaining that it could not find the mysql-connector jar file, I tried putting it in the resources directory in my module.  

Here is the build with mysql-connector-java-8.0.18.jar in my module's resource directory:
```
[igv-backend]$ ballerina build  -a 
BALLERINA_HOME = /Library/Ballerina/distributions/jballerina-1.1.0
Compiling source
        igv/database:0.1.1
        igv/backend:0.1.1
        igv/utility:0.1.1

Creating balos
        target/balo/database-2019r3-java8-0.1.1.balo
        target/balo/backend-2019r3-java8-0.1.1.balo
        target/balo/utility-2019r3-java8-0.1.1.balo
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

Here is the build with mysql-connector-java-8.0.18.jar in my project's lib directory:
```
[igv-backend]$ ballerina build  -a 
BALLERINA_HOME = /Library/Ballerina/distributions/jballerina-1.1.0
Compiling source
        igv/database:0.1.1
        igv/backend:0.1.1
        igv/utility:0.1.1

Creating balos
        target/balo/database-2019r3-java8-0.1.1.balo
        target/balo/backend-2019r3-java8-0.1.1.balo
        target/balo/utility-2019r3-java8-0.1.1.balo

Running tests
        igv/backend:0.1.1
        [fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://Igv-database.cluster-ccxwb1zxkec7.us-east-1.rds.amazonaws.com:3306/igv_patents:No suitable driver
        at ballerinax.java_jdbc:createClient(client.bal:136)
           ballerinax.java_jdbc.Client:__init(client.bal:26)
           igv:getIgvDatabase(database.bal:15)
I'm the before suite function!
I'm the after function!
I'm the after suite function!
        0 passing
        0 failing
        1 skipped
        igv/database:0.1.1
        [fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://Igv-database.cluster-ccxwb1zxkec7.us-east-1.rds.amazonaws.com:3306/igv_patents:No suitable driver
        at ballerinax.java_jdbc:createClient(client.bal:136)
           ballerinax.java_jdbc.Client:__init(client.bal:26)
           igv:getIgvDatabase(database.bal:15)
I'm the before suite function!
I'm the after function!
I'm the after suite function!
        0 passing
        0 failing
        1 skipped
        igv/utility:0.1.1
        [fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://Igv-database.cluster-ccxwb1zxkec7.us-east-1.rds.amazonaws.com:3306/igv_patents:No suitable driver
        at ballerinax.java_jdbc:createClient(client.bal:136)
           ballerinax.java_jdbc.Client:__init(client.bal:26)
           igv:getIgvDatabase(database.bal:15)
I'm the before suite function!
I'm the after function!
I'm the after suite function!
        0 passing
        0 failing
        1 skipped
BALLERINA_HOME=/Library/Ballerina/bin/../distributions/jballerina-1.1.0
```

**Affected Versions:**
Ballerina 1.1.0

**OS, DB, other environment details and versions:**
OSX Mojave 10.14.6

**Related Issues (optional):**

**Comment by TomIsoGriv** [comment]
Here is the contents of the ballerina-internal.log file:
```
[2020-01-16 08:32:58,001] SEVERE {b7a.log.crash} - 1 
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyLibsFromBalo(CopyNativeLibTask.java:227)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedLib(CopyNativeLibTask.java:149)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedLibs(CopyNativeLibTask.java:135)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.copyImportedJarsForModules(CopyNativeLibTask.java:104)
	at org.ballerinalang.packerina.task.CopyNativeLibTask.execute(CopyNativeLibTask.java:89)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Comment by TomIsoGriv** [comment]
Seems to be a duplicate of #20521

**Comment by TomIsoGriv** [comment]
I was able to work around this by placing the driver in the /Library/Ballerina/distributions/jballerina-1.1.0/bre directory.
