### ISSUE TITLE
Bad, sad error when specifying a variable reference for the `webSocketUpgrade` field of the `@http:ResourceConfig` annotation

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20742]
**Description:**
$title.

This is because the value has been directly cast to a `BLangRecordLiteral`, whereas in this case it is a `BLangSimpleVarRef` - https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/ResourceSignatureValidator.java#L122.

Same could happen at several places in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java#L451.

**Steps to reproduce:**
BBE modified to use a var ref.

```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/log;

http:WebSocketUpgradeConfig c = {
        upgradePath: "/ws",
        upgradeService: wsService
};

@http:ServiceConfig {
    basePath: "/hello"
}
service httpService on new http:Listener(9090) {
    
    @http:ResourceConfig {
        path: "/world",
        methods: ["POST"]
    }
    resource function httpResource(http:Caller caller, http:Request req) {
        http:Response resp = new;
        var payload = req.getTextPayload();
        if (payload is error) {
            log:printError("Error sending message", err = payload);
            resp.setPayload("Error in payload");
            resp.statusCode = 500;
        } else {
            io:println(payload);
            resp.setPayload(string `HTTP POST received: ${<@untainted> payload}`);
        }        var err = caller->respond(resp);
        if (err is error) {
            log:printError("Error in responding", err = err);
        }
    }

    @http:ResourceConfig {
        webSocketUpgrade: c
    }
    resource function upgrader(http:Caller caller, http:Request req) {    }
}
service wsService = @http:WebSocketServiceConfig {subProtocols: ["xml, json"]
                                         ,idleTimeoutInSeconds: 20} service {    resource function onOpen(http:WebSocketCaller caller) {
        io:println("New WebSocket connection: " + caller.getConnectionId());
    }    resource function onText(http:WebSocketCaller caller, string text) {
        io:println(text);
        var err = caller->pushText(text);
        if (err is error) {
            log:printError("Error sending message", err = err);
        }
    }    resource function onIdleTimeout(http:WebSocketCaller caller) {
        io:println("Idle timeout: " + caller.getConnectionId());
    }
};
```

ballerina-internal.log
```
[2020-01-25 14:56:38,291] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral
	at org.ballerinalang.net.http.compiler.ResourceSignatureValidator.validateWebSocketUpgrade(ResourceSignatureValidator.java:121)
	at org.ballerinalang.net.http.compiler.ResourceSignatureValidator.validateResourceAnnotation(ResourceSignatureValidator.java:83)
	at org.ballerinalang.net.http.compiler.HttpServiceCompilerPlugin.lambda$process$0(HttpServiceCompilerPlugin.java:87)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.net.http.compiler.HttpServiceCompilerPlugin.process(HttpServiceCompilerPlugin.java:85)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$10(CompilerPluginRunner.java:184)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.invokeServiceProcessor(CompilerPluginRunner.java:365)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyServiceTypeProcessors(CompilerPluginRunner.java:334)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:183)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:126)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$2(CompilerPluginRunner.java:138)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:138)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:126)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:280)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:242)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:209)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:284)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.1.0

**Comment by MaryamZi** [comment]
$title, especially for annotations. Seems to be the case across modules.

gRPC - https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceDefinitionValidator.java#L73
