### ISSUE TITLE
BAD SAD error if a JDBC client connector is defined as a global var in a test file

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#20935]
import ballerinax/java.jdbc;

jdbc:Client prgInfoDB = new ({
    url: "jdbc:mysql://localhost:3307/choreo_db?allowPublicKeyRetrieval=true",
    username: "root",
    password: "root",
    dbOptions: {useSSL: false}
});

Having the above code will result in a bad sad error.

[2020-02-07 16:36:57,137] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at choreo.negotiator.___init.choreo_negotiator_0_1_0__stop_(negotiator:37)
	at choreo.negotiator.___init.$lambda$choreo_negotiator_0_1_0__stop_(negotiator)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:178)
	at choreo.negotiator.___init.$moduleStop(negotiator)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.run(TesterinaFunction.java:116)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.directInvoke(TesterinaFunction.java:83)
	at org.ballerinalang.testerina.core.entity.TestSuite.stop(TestSuite.java:341)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:794)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:630)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:90)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)

**Comment by Dilhasha** [comment]
The above mentioned issue was not reproducible while using ballerina 1.1.1
When, trying to reproduce the issue, we came across another issue where defining variables with the same name in a source file and a test file as global variables, throws an error.
Issue https://github.com/ballerina-platform/ballerina-lang/issues/20963 is created to track it.
