### ISSUE TITLE
BAD SAD Error during ballerina test when field name is duplicated in test file and source file

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#20963]
**Description:**
 In a Ballerina module, define variables with same name in a test bal file as well as a source bal file as global variables. 
Use 'ballerina test module_name' to execute tests.

**Steps to reproduce:**

Duplicate the following variable in a source bal file as well as a test bal file.

`string var1 = "value";`

Following is the error log.

```
[2020-02-10 18:17:29,098] SEVERE {b7a.log.crash} - Duplicate field name "var1" with signature "Ljava.lang.String;" in class file dilhasha/testmod/___init 
java.lang.ClassFormatError: Duplicate field name "var1" with signature "Ljava.lang.String;" in class file dilhasha/testmod/___init
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.ballerinalang.testerina.util.TestarinaClassLoader.loadClass(TestarinaClassLoader.java:57)
	at org.ballerinalang.testerina.core.BTestRunner.packageProcessed(BTestRunner.java:352)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$processProgramFile$4(BTestRunner.java:311)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.processProgramFile(BTestRunner.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$buildSuites$2(BTestRunner.java:285)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.ballerinalang.testerina.core.BTestRunner.buildSuites(BTestRunner.java:273)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:156)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:90)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.TestCommand.execute(TestCommand.java:282)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
This needs to be handled during compilation and result in a compilation failure.

**Affected Versions:**
Ballerina 1.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Seems like the same issues as #20694
