### ISSUE TITLE
Cannot create objects with default parameter - Fill-value check

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#20983]
**Description:**
Currently, the runtime has not captured objects' initializer parameter details. Specifically, whether the initializer has defaultable parameters. 
Also maybe a grammar error in the error message "array --> an array".

#### Code
```Ballerina
type Student object {
    public string name;
    public function __init(string name = "John") {
        self.name = name;
    }
};
public function main() {

    Student s = new();
    Student[] arr = [];
    arr[3] = s;
}
```

#### Output
```
error: {ballerina/lang.array}IllegalListInsertion message=array of length 0 cannot be 
expanded into array of length 4 without filler values
```

**Affected Versions:**
jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
#20721 

**Suggested Labels (optional):**
Area/Language
Component/Compiler

**Comment by MaryamZi** [comment]
Need to fix and enable org.ballerinalang.test.statements.arrays.ArrayLValueFillTest#test2DObjectArrays2 when fixing this.

**Comment by MaryamZi** [comment]
```ballerina
class Student {
    public string name;

    public function init(string name = "John") {
        self.name = name;
    }
}

public function main() {
    Student s = new();
    Student[] arr = [];
    arr[3] = s;
}
```

seems to crash at runtime now.

```
[2022-02-24 07:35:32,452] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at $value$Student.call(test.bal)
        at creators.$_objects.createObjectValue0(Unknown Source)
        at creators.$_objects.createObjectValue(Unknown Source)
        at $_init.createObjectValue(.)
        at io.ballerina.runtime.internal.ValueUtils.createObjectValue(ValueUtils.java:147)
        at io.ballerina.runtime.api.creators.ValueCreator.createObjectValue(ValueCreator.java:796)
        at io.ballerina.runtime.internal.types.BObjectType.getZeroValue(BObjectType.java:75)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.extractComplexFillerValues(ArrayValueImpl.java:1054)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.fillValues(ArrayValueImpl.java:1046)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.prepareForAdd(ArrayValueImpl.java:1159)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.addRefValue(ArrayValueImpl.java:546)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.add(ArrayValueImpl.java:439)
        at test.main(test.bal:12)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
