### ISSUE TITLE
Cannot write test methods when importing a module that has imports

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#21035]
**Description:**
Say we have module_1 and module_2. module_2 has the import `samjs/jregex` as `import samjs/jregex as _;`. Now import module_2 to the tests of module_1 as follows:

`import module_2 as _`. Doing so the following error occurs in a ballerina-internal.log
```
[2020-02-13 08:27:19,627] SEVERE {b7a.log.crash} - org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.BTestRunner.formatErrorMessage(BTestRunner.java:811)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:656)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:630)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:90)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:146)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.entity.TestSuite.start(TestSuite.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:652)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.jvm.MapUtils.handleMapStore(MapUtils.java:45)
	at foobar.module_1.module_1.foobar_module_1_0_1_0__testinit_(module_1:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:130)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/4196273/ballerina-internal.log)
[import_test.zip](https://github.com/ballerina-platform/ballerina-lang/files/4196275/import_test.zip)

Execute :
```bash
ballerina pull samjs/jregex
ballerina build module_1
```

**Affected Versions:**
1.1.0 and 1.1.1 versions

**OS, DB, other environment details and versions:**
Mac

**Comment by suganyasuven** [comment]
It seems this issue is fixed with 1.2.0 release
