### ISSUE TITLE
Cannot import a module when the balo is inside a directory where user doesn’t have write access

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#21041]
**Description:**
When importing a module into another module, the path should be specified in the toml file. However, if the user does not have the write access to that path, a Bad-Sad error is thrown.
The internal-log is follows:
> [2020-02-13 12:12:30,185] SEVERE {b7a.log.crash} - null
java.nio.file.ProviderMismatchException
        at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:200)
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:410)
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
        at org.wso2.ballerinalang.compiler.util.ProjectDirs.isTestSource(ProjectDirs.java:114)
        at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:90)
        at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:504)
        at org.wso2.ballerinalang.compiler.PackageLoader.parseAndDefine(PackageLoader.java:475)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:448)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:475)
        at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:204)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:262)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:255)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:242)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:204)
"ballerina-internal.log" 68L, 5233C

**Steps to reproduce:**

1. Create a new ballerina project
Build the module and copy the balo to a non-accessible directory (ex: Library)

2. Add two modules and build 

3. Import one module into the other module

3. Build one module and copy the balo to a non-accessible directory (ex: Library)

4. Specify the balo path in the toml and build again

**Affected Versions:**
v1.1.1

**Comment by IrushiL** [comment]
We cannot refer to a `bala` path in Swan Lake, instead, we have introduced the local repo, therefore, this is fixed now in Swan Lake.
