### ISSUE TITLE
Cannot assign a value other than nil for the optional defaultable field in the object constructor

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21186]
**Description:**
My object constructor expects 'int? test' param, and the default field should be 10. (function __init(public int? testVal=10){ ..... }) When I have like that, I'm getting exception as below. This is resolved when I replace the default field as nil( unction __init(public int? testVal=()){ ..... }))
```
[2020-02-20 19:00:38,897] SEVERE {b7a.log.crash} - 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.objectweb.asm.Frame.merge(Frame.java:1268)
	at org.objectweb.asm.Frame.merge(Frame.java:1244)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.ballerinalang.nativeimpl.jvm.methodvisitor.VisitMaxs.visitMaxs(VisitMaxs.java:49)
	at ballerina.jvm.$value$MethodVisitor.visitMaxs(types.bal:61)
	at ballerina.jvm.$value$MethodVisitor.call(types.bal)
	at ballerina.compiler_backend_jvm.jvm_method_gen.genJMethodForBFunc(jvm_method_gen.bal:343)
	at ballerina.compiler_backend_jvm.jvm_method_gen.generateMethod(jvm_method_gen.bal:54)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.createObjectMethods(jvm_value_gen.bal:113)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.createObjectValueClass(jvm_value_gen.bal:69)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.generateValueClasses(jvm_value_gen.bal:39)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.jvm_package_gen.generatePackage(jvm_package_gen.bal:172)
	at ballerina.compiler_backend_jvm.main.generateJarBinary(main.bal:86)
	at ballerina.compiler_backend_jvm.main.main(main.bal:60)
	at ballerina.compiler_backend_jvm.___init.$lambda$main$(compiler_backend_jvm)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```
**Steps to reproduce:**
Sample ballerina program. The below doesn't work.
```
import ballerina/io;

type Test object {
 int? intVal;

    function __init(public int? testVal=10){
        self.intVal = testVal;
    }
};

public function main() {
    Test test = new();
    io:println("Testing!");
}
```
If corrected the above program as below, it works. 

```
import ballerina/io;

type Test object {
 int? intVal;

    function __init(public int? testVal=()){
        self.intVal = testVal;
    }
};

public function main() {
    Test test = new();
    io:println("Testing!");
}
```
**Affected Versions:**
1.1.3

**OS, DB, other environment details and versions:**
Mac OS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Happens only for the `__init()` method - for any union-typed defaultable parameter.

Works on 1.1.0, but not on 1.1.1 and later versions.
