### ISSUE TITLE
Integration test failures in Travis CI

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#21198]
**Description:**
Please refer to the following test failures. As far as I noted this would be a port conflict.

```sh
jBallerina-Test-Suite > ballerina-data-streaming-tests > org.ballerinalang.test.data.streaming.TableDataStreamingTestCase STANDARD_ERROR
    [2020-02-21 09:12:07,713] WARNING {org.ballerinalang.test.context.BServerInstance} - Running integration test without jacoco test coverage 
    [2020-02-21 09:12:09,429] INFO {org.ballerinalang.test.context.ServerLogReader} - Compiling source 
    [2020-02-21 09:12:09,545] INFO {org.ballerinalang.test.context.ServerLogReader} - 	streaming_test.bal 
    [2020-02-21 09:12:18,954] INFO {org.ballerinalang.test.context.ServerLogReader} -  
    [2020-02-21 09:12:18,954] INFO {org.ballerinalang.test.context.ServerLogReader} - Generating executables 
    [2020-02-21 09:12:19,839] INFO {org.ballerinalang.test.context.ServerLogReader} - 	/home/travis/build/ballerina-platform/ballerina-lang/tests/jballerina-integration-test/build/ballerinatmp1582275161538/jballerina-tools-1.2.0-SNAPSHOT/streaming_test.jar 
    [2020-02-21 09:12:19,927] INFO {org.ballerinalang.test.context.BServerInstance} - Starting Ballerina server.. 
    [2020-02-21 09:12:19,933] INFO {org.ballerinalang.test.context.BServerInstance} - Waiting for port 7020 to open 
    [2020-02-21 09:12:20,026] SEVERE {org.ballerinalang.test.context.ServerLogReader} - ******************************************************* 
    [2020-02-21 09:12:20,026] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Initializing Ballerina server agent with arguments - host=localhost,port=7020,exitStatus=1,timeout=15000,killStatus=5 
    [2020-02-21 09:12:20,026] SEVERE {org.ballerinalang.test.context.ServerLogReader} - ******************************************************* 
    [2020-02-21 09:12:20,026] SEVERE {org.ballerinalang.test.context.ServerLogReader} - timeout - 15000 exitStatus - 1 killStatus - 5 host - localhost port - 7020 
    [2020-02-21 09:12:21,084] SEVERE {org.ballerinalang.test.context.ServerLogReader} - error: {ballerina/http}ListenerStartupError message=failed to start server connector '0.0.0.0:9090': Address already in use 
    [2020-02-21 09:12:21,085] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at ballerina.http:externStart(service_endpoint.bal:160) 
    [2020-02-21 09:12:21,085] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	   ballerina.http.Listener:start(service_endpoint.bal:131) 
    [2020-02-21 09:12:21,085] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	   ballerina.http.Listener:__start(service_endpoint.bal:41) 
    [2020-02-21 09:12:21,085] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	   .<start>(.:30) 
    [2020-02-21 09:12:21,087] INFO {org.ballerinalang.test.context.ServerLogReader} - [ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090 
=====[ 2039 seconds still running ]=====

jBallerina-Test-Suite > ballerina-data-streaming-tests > org.ballerinalang.test.data.streaming.TableDataStreamingTestCase > setup FAILED
    java.lang.RuntimeException: Port '7020' is not open
        at org.ballerinalang.test.context.Utils.lambda$waitForPortsToOpen$0(Utils.java:87)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at org.ballerinalang.test.context.Utils.waitForPortsToOpen(Utils.java:54)
        at org.ballerinalang.test.context.BServerInstance.executeJarFile(BServerInstance.java:519)
        at org.ballerinalang.test.context.BServerInstance.runJar(BServerInstance.java:465)
        at org.ballerinalang.test.context.BServerInstance.startServer(BServerInstance.java:153)
        at org.ballerinalang.test.context.BServerInstance.startServer(BServerInstance.java:123)
        at org.ballerinalang.test.data.streaming.TableDataStreamingTestCase.setup(TableDataStreamingTestCase.java:63)

jBallerina-Test-Suite > ballerina-data-streaming-tests > org.ballerinalang.test.data.streaming.TableDataStreamingTestCase STANDARD_ERROR
    [2020-02-21 09:22:20,250] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mgetJosnViaGetJsonStringMethod: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,257] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mgetJosnViaSetJsonPayloadMethod: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,257] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mtestStreamingLargeJson: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,258] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mtestStreamingLargeJsonAppended: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,258] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mtestStreamingLargeJsonWithSlowClient: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,258] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mtestStreamingLargeXMLWithSlowClient: [33m[1mSKIPPED[0m 
    [2020-02-21 09:22:20,259] INFO {org.ballerinalang.test.data.streaming.TableDataStreamingTestCase} - [1mtestStreamingLargeXml: [33m[1mSKIPPED[0m 

jBallerina-Test-Suite > ballerina-data-streaming-tests STANDARD_ERROR
    [2020-02-21 09:22:20,259] INFO {org.ballerinalang.test.context.BServerInstance} - Stopping server.. 

org.ballerinalang.test.data.streaming.TableDataStreamingTestCase.cleanup FAILED
    org.ballerinalang.test.context.BallerinaTestException: Error shutting down the server, error - Connection refused (Connection refused)
        at org.ballerinalang.test.context.BServerInstance.shutdownServer(BServerInstance.java:231)
        at org.ballerinalang.test.data.streaming.TableDataStreamingTestCase.cleanup(TableDataStreamingTestCase.java:143)

        Caused by:
        java.net.ConnectException: Connection refused (Connection refused)
            at java.net.PlainSocketImpl.socketConnect(Native Method)
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
            at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
            at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
            at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
            at java.net.Socket.connect(Socket.java:607)
            at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
            at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
            at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
            at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
            at sun.net.www.http.HttpClient.New(HttpClient.java:339)
            at sun.net.www.http.HttpClient.New(HttpClient.java:357)
            at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
            at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
            at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
            at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
            at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
            at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
            at org.ballerinalang.test.util.HttpClientRequest.doPost(HttpClientRequest.java:118)
            at org.ballerinalang.test.context.BServerInstance.shutdownServer(BServerInstance.java:223)
            ... 1 more

......

jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.tracing.TracingTestCase > setup FAILED
    java.lang.RuntimeException: Port '7022' is not open
        at org.ballerinalang.test.context.Utils.lambda$waitForPortsToOpen$0(Utils.java:87)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at org.ballerinalang.test.context.Utils.waitForPortsToOpen(Utils.java:54)
        at org.ballerinalang.test.context.BServerInstance.executeJarFile(BServerInstance.java:519)
        at org.ballerinalang.test.context.BServerInstance.runJar(BServerInstance.java:447)
        at org.ballerinalang.test.context.BServerInstance.startServer(BServerInstance.java:207)
        at org.ballerinalang.test.context.BServerInstance.startServer(BServerInstance.java:176)
        at org.ballerinalang.test.context.BServerInstance.startServer(BServerInstance.java:170)
        at org.ballerinalang.test.observability.tracing.TracingTestCase.setup(TracingTestCase.java:94)
```
Please find the attahced error log.

[log-21024.txt](https://github.com/ballerina-platform/ballerina-lang/files/4235695/log-21024.txt)

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/21165

**Comment by BuddhiWathsala** [comment]
This issue(https://github.com/ballerina-platform/ballerina-lang/pull/21024/commits/5d67759bd477a851d5aa31fd2f6e6478c24b968f) was fixed from this commit. The reason for the issue was `BCompileUtil.compile()` function compile the given ballerina code and start it. That leads to a port conflict. Instead using `BCompileUtil.compileOnly()` compile the test ballerina code without starting.
