### ISSUE TITLE
Unable to use function parameter as the object initialiser param with named arguments

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21259]
**Description:**
I have object with named params. I can initialize the object when I assign those named params inline or use a variable defined. But when I initialize the same object within a function by using the parameters from the object, I'm getting the below exception. 

```
[2020-02-26 12:38:24,242] SEVERE {b7a.log.crash} - Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.updateSelfTaintedStatusToTainted(TaintAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeInvocation(TaintAnalyzer.java:2415)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:1101)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:1173)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:63)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1670)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:473)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:558)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1670)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:551)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1670)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:2099)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:2021)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitInvokable(TaintAnalyzer.java:1919)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:407)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.lambda$analyzeNode$6(TaintAnalyzer.java:334)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:331)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyze(TaintAnalyzer.java:298)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyze(TaintAnalyzer.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.taintAnalyze(CompilerDriver.java:276)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:237)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:209)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:284)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
Refer the sample program below to reproduce. Note: the Client object initialized with 'username' paramter from function. 

```
mport ballerina/io;

public type Client object {

    public function __init(public string host="localhost",
        public string? user = (), public string? password= (), public string? database = (),
        public int port=3306) returns error? {
        return ();
    }
};

public function main() {
    callClient("foo");
    io:println("Completed");
}

function callClient(string username) {
     Client|error p1 = new(user=username);
     io:println("Call Completed");
}
```

If I change the above program as below, then it works. Note:  I have assigned the object param 'user' inline with value "foo".
```
import ballerina/io;

public type Client object {

    public function __init(public string host="localhost",
        public string? user = (), public string? password= (), public string? database = (),
        public int port=3306) returns error? {
        return ();
    }
};

public function main() {
    callClient("foo");
    io:println("Completed");
}

function callClient(string username) {
     Client|error p1 = new(user="foo");
     io:println("Call Completed");
}
```

**Affected Versions:**
1.1.3 and 1.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**
MacOS

**Comment by sinthuja** [comment]
This is blocker to write unit tests for such modules.

**Comment by sinthuja** [comment]
@MaryamZi FYI.
