### ISSUE TITLE
Documentation generating failing

### ISSUE THREAD

**Issue by devhammed** [ballerina-platform/ballerina-lang#21265]
**Description:**
The command `ballerina doc -a` fails to generate documentation for my project. below is the log:

```
[2020-02-26 09:47:30,164] SEVERE {b7a.log.crash} - Type def not supported for FUNCTION_TYPE 
java.lang.UnsupportedOperationException: Type def not supported for FUNCTION_TYPE
	at org.ballerinalang.docgen.Generator.createTypeDefModels(Generator.java:162)
	at org.ballerinalang.docgen.Generator.generateModuleConstructs(Generator.java:82)
	at org.ballerinalang.docgen.docs.BallerinaDocGenerator.lambda$writeAPIDocsForModules$1(BallerinaDocGenerator.java:176)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.ballerinalang.docgen.docs.BallerinaDocGenerator.writeAPIDocsForModules(BallerinaDocGenerator.java:182)
	at org.ballerinalang.packerina.task.CreateDocsTask.execute(CreateDocsTask.java:68)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.DocCommand.execute(DocCommand.java:288)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 

```

**Steps to reproduce:**

```sh
git clone https://github.com/devhammed/redux_bal

cd redux_bal

ballerina doc -a
```

**Affected Versions:**
jBallerina 1.1.3
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
Ubuntu 19.10

**Comment by parkavi11** [comment]
This is a bug during generating the doc. We will get this fixed asap.

**Comment by devhammed** [comment]
@parkavi11 Progress on this? `redux_bal` users are already disturbing me for API documentation.

**Comment by hevayo** [comment]
@devhammed we have merge the fixes to the repo and will be available with the next Ballerina release schedules on 18th of March. For the time being you can build the ballerina-1.1.x branch with the fix.

**Comment by devhammed** [comment]
Okay, thank you.

**Comment by devhammed** [comment]
I have updated to 0.8.5 tool and still getting the error.

**Comment by parkavi11** [comment]
I have tried with ballerina version 1.2.0 and updatool version 0.8.5. For me it is working fine.
<img width="796" alt="Screen Shot 2020-05-04 at 15 50 31" src="https://user-images.githubusercontent.com/28732894/80956600-27bc3e80-8e1f-11ea-8e35-032303c5bf6b.png">
Please try with the latest version and update the thread if you still have any problem.

**Comment by devhammed** [comment]
Now working.
