### ISSUE TITLE
Unable to use the attribute defined in the record to assign another attribute

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21388]
**Description:**
I have a record, where I want to set second attribute with the same value of first attribute by default. But this results in an error as below.

```
[2020-03-02 10:55:51,388] SEVERE {b7a.log.crash} - null
java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.merge(Frame.java:1222)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.ballerinalang.nativeimpl.jvm.methodvisitor.VisitMaxs.visitMaxs(VisitMaxs.java:49)
	at ballerina.jvm.$value$MethodVisitor.visitMaxs(types.bal:61)
	at ballerina.jvm.$value$MethodVisitor.call(types.bal)
	at ballerina.compiler_backend_jvm.jvm_method_gen.genJMethodForBFunc(jvm_method_gen.bal:343)
	at ballerina.compiler_backend_jvm.jvm_method_gen.generateMethod(jvm_method_gen.bal:54)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.createRecordMethods(jvm_value_gen.bal:381)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.createRecordValueClass(jvm_value_gen.bal:350)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.generateValueClasses(jvm_value_gen.bal:49)
	at ballerina.compiler_backend_jvm.$value$ObjectGenerator.call(jvm_value_gen.bal)
	at ballerina.compiler_backend_jvm.jvm_package_gen.generatePackage(jvm_package_gen.bal:200)
	at ballerina.compiler_backend_jvm.main.generateJarBinary(main.bal:86)
	at ballerina.compiler_backend_jvm.main.main(main.bal:60)
	at ballerina.compiler_backend_jvm.___init.$lambda$main$(compiler_backend_jvm)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
Please use the sample program provided below to reproduce this. Please note, want to assign attribute `minIdleConnections` with the same value of `maxOpenConnections` when the corresponding configuration is not provided.

```
import ballerina/config;
import ballerina/io;


type ConnectionPool record {|
    int maxOpenConnections = config:getAsInt("b7a.sql.pool.maxOpenConnections", 15);
    decimal maxConnectionLifeTimeInSeconds = <decimal>config:getAsFloat("b7a.sql.pool.maxConnectionLifeTimeInSeconds",
    1800.0);
    int minIdleConnections = config:getAsInt("b7a.sql.pool.minIdleConnections", maxOpenConnections);
|};

public function main() {
    ConnectionPool pool = {};
    io:println(pool);
}

```

**Affected Versions:**
1.1.3 and 1.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
A record field's default value cannot refer another field. Related issue https://github.com/ballerina-platform/ballerina-lang/issues/20825.

With the fix for https://github.com/ballerina-platform/ballerina-lang/issues/20825, this sample produces an "undefined symbol 'maxOpenConnections'" error on 1.2.1 and Swan Lake preview versions.
