### ISSUE TITLE
Stream is not returning custom error type when using next()

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21481]
**Description:**
My iterator returns 'public function next() returns record{| record{} value; |}| sql:Error?', but when I do stream.next(), it's not returning my custom error - 'Error', and it's returning generic 'error' type. And hence I couldn't do, 
```
record{| NumericInvalidColumn value; |}|sql:Error? data =  streamData.next();
```
And I can only do. 
```
record{| NumericInvalidColumn value; |}|error? data =  streamData.next();
```

Compilation error: 
```
    ERROR: .::query-test.bal:71:64:: incompatible types: expected '(record {| NumericInvalidColumn value; |}|ballerina/sql:DatabaseError|ballerina/sql:ApplicationError)?', found '(record {| NumericInvalidColumn value; |}|error)?'
        at org.ballerinalang.test.util.BRunUtil.getInvokedFunction(BRunUtil.java:1143)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1162)
        at org.ballerinalang.jdbc.query.NumericTypesQueryTest.testQueryNumericTypeRecord(NumericTypesQueryTest.java:83)
```

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21524 ...
