### ISSUE TITLE
Cannot use Custom error type in the stream 

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21480]
**Description:**
I have a custom error type as defined below, and I wanted to use that as the stream error type, but I get an error  as below. 
```
 stream<record{}, Error> errorStream = new (resultIterator);
```
Compilation error: 
```
Exception in thread "main" org.ballerinalang.compiler.BLangCompilerException: Compilation failed with 1 error(s) and 0 warning(s)
  ERROR: ballerina/sql::client.bal:92:43:: type '(ballerina/sql:DatabaseError|ballerina/sql:ApplicationError)' not allowed here; expected an 'error' or a subtype of 'error'.
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:123)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:77)
```
Definition of the custom error type: 

```
public type DatabaseError error<DATABASE_ERROR_REASON, DatabaseErrorData>;

# Represents an error originating from application-level causes.
public type ApplicationError error<APPLICATION_ERROR_REASON, ApplicationErrorData>;

# Represents a database or application level error returned from JDBC client remote functions.
public type Error DatabaseError | ApplicationError;
```

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21524 ...
