### ISSUE TITLE
Windows path is not recognised in toml parser

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#21638]
**Description:**
When a dependency path is provided in the Toml, a Bad Sad error is thrown for Windows.

**Steps to reproduce:**
Create two simple Ballerina projects in Windows (say TestProject1 and TestProject2)
Add modules to both projects
Import a function in one module to another project's module by adding the balo path to the Toml
Build the module

```
[2020-03-11 00:29:15,016] SEVERE {b7a.log.crash} - Illegal char < > at index 16: ..\TestProject2\ arget alo\ est1-2019r3-any-0.1.0.balo
java.nio.file.InvalidPathException: Illegal char < > at index 16: ..\TestProject2\ arget alo\ est1-2019r3-any-0.1.0.balo
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
at java.nio.file.Paths.get(Paths.java:84)
at org.ballerinalang.toml.model.DependencyMetadata.getPath(DependencyMetadata.java:56)
at org.wso2.ballerinalang.compiler.PackageLoader.lambda$genRepoHierarchy$1(PackageLoader.java:209)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
at org.wso2.ballerinalang.compiler.PackageLoader.genRepoHierarchy(PackageLoader.java:210)
at org.wso2.ballerinalang.compiler.PackageLoader.<init>(PackageLoader.java:157)
at org.wso2.ballerinalang.compiler.PackageLoader.getInstance(PackageLoader.java:131)
at org.wso2.ballerinalang.compiler.CompilerDriver.<init>(CompilerDriver.java:108)
at org.wso2.ballerinalang.compiler.CompilerDriver.getInstance(CompilerDriver.java:98)
at org.wso2.ballerinalang.compiler.Compiler.<init>(Compiler.java:56)
at org.wso2.ballerinalang.compiler.Compiler.getInstance(Compiler.java:69)
at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:46)
at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:394)
at java.util.Optional.ifPresent(Optional.java:159)
at org.ballerinalang.tool.Main.main(Main.java:57) 

 ```

**Affected Versions:**
1.1.4

**OS, DB, other environment details and versions:**
Windows 

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/20044
https://github.com/ballerina-platform/ballerina-lang/issues/20933

**Suggested Labels (optional):**
Area/BuildTools

**Suggested Assignees (optional):**

**Comment by parkavi11** [comment]
This issue is because of the toml library that is used. Hence the solution would be to use single quotes to specify paths regardless of the OS. 

The following examples of paths are compatible.

1. 
```
[dependencies]
"wso2/twitter" = "2.3.4"
"wso2/github" = { path = './path/to/github.balo', version = "1.2.3"}
```
2.
```
[dependencies]
"wso2/twitter" = "2.3.4"
"wso2/github" = { path = './path/to/github.balo', version = "1.2.3"}
```

Therefore replacing the double quotes with single quotes when specifying paths will work.
