### ISSUE TITLE
Bad, sad error with bitwise or for byte and 'int:UnsignedN

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21767]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/lang.'int;

public function main() {
    byte a = 1;
    'int:Unsigned16 b = 1;

    int x = a | b;
    io:println(x);
}
```

ballerina-internal.log
```
[2020-03-14 14:10:10,855] SEVERE {b7a.log.crash} - 0 
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.objectweb.asm.Frame.merge(Frame.java:1268)
	at org.objectweb.asm.Frame.merge(Frame.java:1233)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:534)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:248)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generatePackage(JvmPackageGen.java:326)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
	at org.wso2.ballerinalang.compiler.bir.BackendDriver.codeGen(BackendDriver.java:77)
	at org.wso2.ballerinalang.compiler.bir.BackendDriver.execute(BackendDriver.java:73)
	at org.ballerinalang.packerina.task.CreateJarTask.execute(CreateJarTask.java:96)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:284)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.2.0-rc1

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21769.
