### ISSUE TITLE
Bad-Sad when serializing progmatically constructed xml value

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21773]
**Description:**
```ballerina
    xmllib:Element  doc = <xmllib:Element> xml`<doc xmlns="http://www.example.com"/>`;
    doc.setChildren(xml `<foo/>`);
    io:println(doc);
```

ballerina-internal.log entry
```
[2020-03-16 08:27:05,516] SEVERE {b7a.log.crash} - failed to get xml as string: {ballerina/lang.xml}XMLOperationError 
org.ballerinalang.jvm.util.exceptions.BallerinaException: failed to get xml as string: {ballerina/lang.xml}XMLOperationError
	at org.ballerinalang.jvm.values.XMLValue.handleXmlException(XMLValue.java:133)
	at org.ballerinalang.jvm.values.XMLItem.stringValue(XMLItem.java:516)
	at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:91)
	at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
	at ballerina.io.print.println(print.bal:28)
	at main.main(main.bal:16)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Fixed in 1.2.0
