### ISSUE TITLE
AssertionError while building the FTP module with 1.2.0-rc1

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#21840]
**Description:**
$title.

**Steps to reproduce:**
Update the ballerina version to 1.2.0-SNAPSHOT in pom.xml and getting below error while build.
```
[2020-03-17 00:53:55,349] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:568)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:949)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:560)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:519)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:325)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:231)
	at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:304)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:216)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:404)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.2.0-RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21841.
