### ISSUE TITLE
[Testerina] Bad, sad error when there's an HTTP service in the tests folder

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21863]
**Description:**
$title.

**Steps to reproduce:**
Following as tests.

```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/test;

service foo on new http:Listener(8080) {
    resource function bar(http:Caller caller, http:Request request) {
        
    }
}

@test:Config {
    
}
function testFunc() {
    io:println("I'm the test!");
}
```

```cmd
$ ballerina build foo
Compiling source
        maryam/foo:0.1.0
error: maryam/foo:0.1.0::tests/main_test.bal:6:5: undefined module 'http'
error: maryam/foo:0.1.0::tests/main_test.bal:6:5: unknown type 'FilterContext'
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

ballerina-internal.log
```
[2020-03-17 12:13:20,879] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.HttpFiltersDesugar.addFilterContextCreation(HttpFiltersDesugar.java:217)
	at org.wso2.ballerinalang.compiler.desugar.HttpFiltersDesugar.addFilterStatements(HttpFiltersDesugar.java:181)
	at org.wso2.ballerinalang.compiler.desugar.HttpFiltersDesugar.addHttpFilterStatementsToResource(HttpFiltersDesugar.java:167)
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.engageCustomResourceDesugar(ServiceDesugar.java:204)
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.lambda$engageCustomServiceDesugar$4(ServiceDesugar.java:200)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.engageCustomServiceDesugar(ServiceDesugar.java:200)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.lambda$visit$5(Desugar.java:626)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:626)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.lambda$visit$7(Desugar.java:657)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:657)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4966)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:350)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:300)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:259)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:216)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:60)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:404)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
1.2.0-rc1

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21961.
