### ISSUE TITLE
Bad, sad error when transitive dependency of a module is not resolved

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#21913]
**Description:**
Getting Bad, sad error, if the dependency of an imported module is not resolved 

**Steps to reproduce:**

<img width="1680" alt="moduleissue" src="https://user-images.githubusercontent.com/30232477/76938527-bf6fd700-691c-11ea-91f1-a6d79f1b99f5.png">

**Affected Versions:**
ballerina-1.2.0-rc2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Shall we add the stacktrace in ballerina-internal-log

**Comment by suganyasuven** [comment]
> Shall we add the stacktrace in ballerina-internal-log

`[2020-03-19 11:21:19,661] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:52)
	at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:99)
	at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:64)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:404)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)`
