### ISSUE TITLE
Graceful shutdown of listeners panicked during init

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#21945]
When there is a panic in __init of a Listener, it will throw unnecessary NPE's when shutting down.

How to reproduce :

run examples/directory-listener/directory_listener.bal with a non-existing directory, and you will see 
```
error: {ballerina/file}FileSystemError message=Folder does not exist: /Users/manux/sc/2020-03-18
	at ballerina.file:initEndpoint(service_endpoint.bal:67)
	   ballerina.file.Listener:__init(service_endpoint.bal:32)
	   ballerina.file.Listener:$__init$(service_endpoint.bal:26)
	   ..<init>(.:10)
```
in output. this is ok.

but you will also see 

```
[2020-03-18 16:06:20,199] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
    at ___init.___stop_(.:10)
    at ___init.$lambda$___stop_(.)
    at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
    at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
    at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
    at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:218)
    at ___init.$moduleStop(.)
    at ___init$SignalListener.run(Unknown Source)
```
in the log. this can be avoided.

**Comment by manuranga** [comment]
duplicate of #20274
