### ISSUE TITLE
Bad Sad Error When Building Ballerina App

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#21992]
**Description:**
I get a bad sad error when I try to build the [Salesforce Opportunity Notifier App](https://github.com/wso2-enterprise/choreo/tree/master/samples/salesforce-opportunity-notifier).

The console log is as follows,

```
miyurud@miyurud:~/git/choreo/samples/salesforce-opportunity-notifier$ ballerina build -a -c --skip-tests=true
Compiling source
        choreo/salesforce-opportunity-notifier:0.1.0
error: module not found for: ballerinax/java:0.0.0_java8
error: module not found for: ballerinax/java:0.0.0_java8
error: module not found for: ballerinax/java.arrays:0.0.0_java8
error: module not found for: ballerinax/java:0.0.0_java8
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

The error log on the ballerina-internal.log file is as follows,

```
[2020-03-19 19:28:43,666] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.LockFileWriter.lambda$getImports$1(LockFileWriter.java:112)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.LockFileWriter.getImports(LockFileWriter.java:116)
	at org.wso2.ballerinalang.compiler.LockFileWriter.addImportsToLockFileModel(LockFileWriter.java:92)
	at org.wso2.ballerinalang.compiler.LockFileWriter.addImportsToLockFileModel(LockFileWriter.java:98)
	at org.wso2.ballerinalang.compiler.LockFileWriter.updateDependencies(LockFileWriter.java:137)
	at org.wso2.ballerinalang.compiler.LockFileWriter.writeLockFile(LockFileWriter.java:149)
	at org.ballerinalang.packerina.task.CreateLockFileTask.execute(CreateLockFileTask.java:36)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:404)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 

```

**Steps to reproduce:**
Clone the  [Salesforce Opportunity Notifier App](https://github.com/wso2-enterprise/choreo/tree/master/samples/salesforce-opportunity-notifier) and build using the command,

ballerina build -a -c --skip-tests=true

**Affected Versions:**
Ballerina 1.2.0-rc2

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
The `LockFileWriter` task is removed in Swan Lake, please reopen if the issue is reproduced.
