### ISSUE TITLE
Invalid `push` on a union-typed array results in a bad, sad error at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22129]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    int[]|string[] arr = [1, 2];
    arr.push("foo");
}
```

ballerina-internal.log
```log
[2020-03-24 12:32:31,321] SEVERE {b7a.log.crash} - java.lang.String cannot be cast to java.lang.Long 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.ballerinalang.jvm.values.utils.ArrayUtils.add(ArrayUtils.java:42)
	at org.ballerinalang.langlib.array.Push.push(Push.java:53)
	at ballerina.lang_array.array.push(array.bal:179)
	at qwe.main(qwe.bal:3)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
1.2.0

**Comment by MaryamZi** [comment]
Same for unshift.
