### ISSUE TITLE
XML with default namespace cannot cast to string

### ISSUE THREAD

**Issue by grahnj** [ballerina-platform/ballerina-lang#22281]
**Description:**
When trying to run an assertEquals on two XML types that contain a default namespace an error is thrown:

```
org.ballerinalang.jvm.util.exceptions.BallerinaException message=failed to get xml as string: {ballerina/lang.xml}XMLOperationError
                at ballerina.io:sprintfExtern(print.bal:57)
                ballerina.io:sprintf(print.bal:54)
                ballerina.test:assertEquals(assert.bal:79)
```

The root cause of this issue is casting an XML type with a default namespace (at any level of nesting) to a string.

**Steps to reproduce:**
```
// this works
io:println(xml`<wrapper xmlns:something="http://anything"><child>1</child></wrapper>`);

// this doesn't
io:println(xml`<wrapper xmlns="http://anything"><child>1</child></wrapper>`);
```

** **UPDATE** **
The issue cannot be reproduced with the example above because the root element must also contain an attribute:

```
// this works
io:println(xml`<wrapper name="artifact1" xmlns:something="http://anything"><child>1</child></wrapper>`);

// this doesn't
io:println(xml`<wrapper name="artifact1" xmlns="http://anything"><child>1</child></wrapper>`);
```

Generated crash report:

[2020-04-02 11:17:44,500] SEVERE {b7a.log.crash} - failed to get xml as string: {ballerina/lang.xml}XMLOperationError
org.ballerinalang.jvm.util.exceptions.BallerinaException: failed to get xml as string: {ballerina/lang.xml}XMLOperationError
at org.ballerinalang.jvm.values.XMLValue.handleXmlException(XMLValue.java:135)
at org.ballerinalang.jvm.values.XMLItem.stringValue(XMLItem.java:499)
at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:91)
at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
at ballerina.io.print.println(print.bal:28)
at 22281.main(22281.bal:31)
at ___init.$lambda$main$(.)
at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
at java.lang.Thread.run(Thread.java:748)

**Affected Versions:**
1.2

**OS, DB, other environment details and versions:**
Tested on Windows

**Comment by rdhananjaya** [comment]
Confirmed to be working on master branch and 1.2.x branch.

**Comment by grahnj** [comment]
I underestimated the extent of the root cause, and in turn removed the part of the xml that was necessary to reproduce the issue. The node needs to contain an attribute as well:

`io:println(xml`<wrapper name="artifact1" xmlns="http://anything"><child>1</child></wrapper>`);`

I then get a crash report:

[2020-04-02 11:17:44,500] SEVERE {b7a.log.crash} - failed to get xml as string: {ballerina/lang.xml}XMLOperationError 
org.ballerinalang.jvm.util.exceptions.BallerinaException: failed to get xml as string: {ballerina/lang.xml}XMLOperationError
	at org.ballerinalang.jvm.values.XMLValue.handleXmlException(XMLValue.java:135)
	at org.ballerinalang.jvm.values.XMLItem.stringValue(XMLItem.java:499)
	at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:91)
	at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
	at ballerina.io.print.println(print.bal:28)
	at 22281.main(22281.bal:31)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/22468
