### ISSUE TITLE
resource signature parameter count should be >= 2 ballerina: Oh no, something really went wrong. Bad. Sad.

### ISSUE THREAD

**Issue by myNameDoesNotMatter** [ballerina-platform/ballerina-lang#22502]
I got this error after moving from ballerina 1.0 to 1.2.1 :

> resource signature parameter count should be >= 2 ballerina: Oh no, something really went wrong. Bad. Sad. 

Here is the ballerina-internal.log file. I have to mention that with older version everything worked fine!
The error came after update! Now i'm trying to download the 1.0 version again and i get the 404 response Page not found. What can i do?

------------------------------------------------------ballerina-internal.log--------------------------------------------------

[2020-04-07` 12:22:07,548] SEVERE {b7a.log.crash} - fromIndex(2) > toIndex(1) 

java.lang.IllegalArgumentException: fromIndex(2) > toIndex(1)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1014)
	at java.util.ArrayList.subList(ArrayList.java:1004)
	at org.ballerinalang.net.http.compiler.ResourceSignatureValidator.verifySignatureParamsWithAnnotatedParams(ResourceSignatureValidator.java:228)
	at org.ballerinalang.net.http.compiler.ResourceSignatureValidator.validateResourceAnnotation(ResourceSignatureValidator.java:120)
	at org.ballerinalang.net.http.compiler.HttpServiceCompilerPlugin.lambda$process$0(HttpServiceCompilerPlugin.java:89)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.net.http.compiler.HttpServiceCompilerPlugin.process(HttpServiceCompilerPlugin.java:87)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$10(CompilerPluginRunner.java:184)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.invokeServiceProcessor(CompilerPluginRunner.java:364)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyServiceTypeProcessors(CompilerPluginRunner.java:333)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:183)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:126)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$2(CompilerPluginRunner.java:138)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:138)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:126)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:294)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:252)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:214)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:284)
	at java.util.Optional.ifPresent(Optional.java:159)
	at `org.ballerinalang.tool.Main.main(Main.java:57)

**Comment by myNameDoesNotMatter** [comment]
@chintana-zz @imesh @upul @bradh

**Comment by bradh** [comment]
@myNameDoesNotMatter: No idea why you tagged me on this...
