### ISSUE TITLE
NPE during API doc gen for typedesc

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#22516]
**Description:**
$subject when creating balo. 

```
> Task :ballerina-http:createBalo
Compiling source
        ballerina/http
Exception in thread "main" java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.toString(BLangSimpleVarRef.java:55)
        at java.lang.String.valueOf(String.java:2994)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.toString(BLangTypeConversionExpr.java:82)
        at java.lang.String.valueOf(String.java:2994)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.toString(BLangTypeConversionExpr.java:82)
        at org.ballerinalang.docgen.Generator.getVariable(Generator.java:246)
        at org.ballerinalang.docgen.Generator.createDocForFunction(Generator.java:210)
        at org.ballerinalang.docgen.Generator.addDocForObjectType(Generator.java:333)
        at org.ballerinalang.docgen.Generator.createTypeDefModels(Generator.java:121)
        at org.ballerinalang.docgen.Generator.generateModuleConstructs(Generator.java:82)
        at org.ballerinalang.docgen.docs.BallerinaDocGenerator.writeAPIDocsForModules(BallerinaDocGenerator.java:185)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genApiDoc(GenerateBalo.java:167)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:157)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:91)

> Task :ballerina-http:createBalo FAILED
```

**Steps to reproduce:**
Add the following type, use it in a function and run creatBalo Gradle task

```ballerina
# The types of data values that are expected by the HTTP `client` to return after the data binding operation
public type TargetType typedesc<Response|string|xml|json|byte[]|CustomRecordType| CustomRecordType[]>;

public remote function post(@untainted string path, RequestMessage message, public TargetType targetType = Response)
            returns @tainted Response|PayloadType|ClientError {
            //
    }
```
The `Response` defaultable param for the targetType in the `post` remote function will result the NPE during the API doc generation.

**Affected Versions:**
v1.2.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Closing since this was fixed with PR #22777
