### ISSUE TITLE
NPE when using mapping constructor expression

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#22546]
**Description:**
Consider the below example.

```ballerina
    var arr = [{ id: 13 , name: "Sanjiva", address: "Weerawarana" },
                                           { id: 23 , name: "James" , address: "Clark" }];
```
But encountered an error as shown below,

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteMappingConstructor(Desugar.java:6441)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3257)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral.accept(BLangRecordLiteral.java:71)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:4960)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:5000)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3182)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr.accept(BLangListConstructorExpr.java:51)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:4960)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1150)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4935)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1211)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4935)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4976)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:4986)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:890)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4935)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:933)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4935)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4993)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:647)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:4935)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:356)
        at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:296)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:255)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:212)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:130)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:490)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:478)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:603)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:586)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:576)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:570)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:685)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:110)
```

**Comment by MaryamZi** [comment]
Fixed in #22549.
