### ISSUE TITLE
Bad sad error with Ballerina 1.2.x

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#22561]
**Description:**
I get the following bad sad error when building module-jira with Ballerina 1.2.0 and 1.2.1.

```
[2020-04-10 09:43:52,128] SEVERE {b7a.log.crash} - null 
java.nio.file.ProviderMismatchException
	at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:200)
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:410)
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
	at org.wso2.ballerinalang.compiler.util.ProjectDirs.isTestSource(ProjectDirs.java:125)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:92)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:494)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:377)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:404)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
Clone the master branch of [module-jira](https://github.com/ballerina-platform/module-jira).
Build the project with `ballerina build -a -c --skip-tests=true` using either Ballerina 1.2.0 or 1.2.1 versions.

**Affected Versions:**
I have found this issue in both Ballerina 1.2.0 as well as 1.2.1 versions

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 1.8.0

**Related Issues (optional):**
[https://github.com/ballerina-platform/module-jira/issues/71](https://github.com/ballerina-platform/module-jira/issues/71)

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This happens when the project name is given as `ballerina`. To overcome this, build the project with the below command which sets the required system variable. 

`JAVA_OPTS="-DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true" ballerina build -a -c --skip-tests=true`

For usage in CI systems, please refer the [module-redis](https://github.com/ballerina-platform/module-redis/blob/master/.github/workflows/ci.yml#L20).

**Comment by miyurud** [comment]
Thanks Asma. By using the modified command I was able to build [module-jira](https://github.com/ballerina-platform/module-jira) without any errors.
