### ISSUE TITLE
Wait action on a future returned by a nested async call crashes the runtime

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22648]
Consider the following:
```ballerina
public function main() {
    testNestedAsyncActions();
}

function bar() returns int => 100;

function baz(future<int>? res) returns int {
    if (res is future<int>) {
        int v = wait res;
        return v + 50;
    } else {
        return 0;
    }
}

function testNestedAsyncActions() {
    future<int> res = start baz(start bar());
    int result = wait res; // this line crashes the runtime
}
```
Following is the crash log:
```
[2020-04-15 20:05:39,882] SEVERE {b7a.log.crash} - test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J 
java.lang.NoSuchMethodError: test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J
	at test.$baz$lambda$5$(test.bal)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-04-15 20:05:39,887] SEVERE {b7a.log.crash} - test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J 
java.lang.NoSuchMethodError: test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J
	at test.$baz$lambda$5$(test.bal)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-04-15 20:05:39,888] SEVERE {b7a.log.crash} - test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J 
java.lang.NoSuchMethodError: test.baz(Lorg/ballerinalang/jvm/scheduling/Strand;Lorg/ballerinalang/jvm/values/FutureValue;Z)J
	at test.$baz$lambda$5$(test.bal)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pubudu91** [comment]
After fixing, need to enable the test case for this in `NestedActionsTest.testNestedAsyncActions`

**Comment by pubudu91** [comment]
Closing since as per the spec, action invocations are not allowed as arguments
