### ISSUE TITLE
Parser crashed for missing close-bracket in member-access-expr

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#22806]
**Description:**

Sample:

```ballerina
function foo() {
    a[b][c = 5;
}
```
Error:
```
Exception in thread "main" java.lang.IllegalStateException
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExpressionRhs(BallerinaParserErrorHandler.java:1295)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:696)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInSubTree(BallerinaParserErrorHandler.java:469)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.fixAndContinue(BallerinaParserErrorHandler.java:1435)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1117)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInSubTree(BallerinaParserErrorHandler.java:469)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.fixAndContinue(BallerinaParserErrorHandler.java:1428)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1117)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInSubTree(BallerinaParserErrorHandler.java:469)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.fixAndContinue(BallerinaParserErrorHandler.java:1428)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1117)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInSubTree(BallerinaParserErrorHandler.java:469)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.fixAndContinue(BallerinaParserErrorHandler.java:1428)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1117)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInSubTree(BallerinaParserErrorHandler.java:469)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:452)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.recover(BallerinaParserErrorHandler.java:319)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.recover(BallerinaParser.java:347)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCloseBracket(BallerinaParser.java:3338)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseMemberAccessExpr(BallerinaParser.java:3324)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:3260)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:3201)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:3291)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:3201)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseActionOrExpressionInLhs(BallerinaParser.java:3180)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatementStartsWithIdentifier(BallerinaParser.java:5640)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatementStartsWithIdentifier(BallerinaParser.java:5611)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:2875)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:2805)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:2742)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:1876)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:1826)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:1812)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionDefinition(BallerinaParser.java:1192)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1069)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:557)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:481)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:381)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:60)
```

**Comment by SupunS** [comment]
Added with #23134
