### ISSUE TITLE
[Table] KeyType tsymbol not getting resolved

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#22822]
As per langlib.table spec, 
```ballerina
# Returns a list of all the keys of table `t`.
#
# + t - the table
# + return - a new list of all keys
public function keys(table<any|error> key<KeyType> t) returns KeyType[] = external;
```
During this case, I observe below NPE since KeyType.tsymbol is null.

```
Compiling source
ballerina/lang.table
Exception in thread "main" java.lang.NullPointerException
        at org.ballerinalang.docgen.generator.model.Type.fromTypeNode(Type.java:143)
        at org.ballerinalang.docgen.Generator.createDocForFunction(Generator.java:231)
        at org.ballerinalang.docgen.Generator.generateModuleConstructs(Generator.java:90)
        at org.ballerinalang.docgen.docs.BallerinaDocGenerator.writeAPIDocsForModules(BallerinaDocGenerator.java:185)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genApiDoc(GenerateBalo.java:167)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:157)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:91)
```

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/22830...
