### ISSUE TITLE
[HTTP] ResponseCacheControlObj returns null strand

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#22871]
**Description:**
The ResponseCacheControlObj returns null for getStrand() method call. 

**Code:**
```
import ballerina/http;
import ballerina/runtime;
import ballerina/io;

int i = 0;

public function main() {
    [int, int]|error res = testForkJoin();
    io:println("result : ", res.toString());
}

function testForkJoin() returns [int, int]|error {
    http:Client c = new ("http://example.com");
    init();

    fork {
        @strand{thread:"any"}
        worker w1 returns int {
            var clientResponse = c -> get("");
            int code = 0;
            if clientResponse is http:Response {
                code = clientResponse.statusCode;
            }
            return code;
        }
        @strand{thread:"any"}
        worker w2 {
            runtime:sleep(3000);
            i = 100;
        }
    }
    map<any> results = wait {w1, w2};
    int st = <int> results["w1"];
    int x = i;
    return [st, x];
}

function init() {
    future<int> accumulator = start sum(2, 4); 
}

function sum(int a, int b) returns int {
    return a + b;
}
```
Found while extracting the current strand for the fix in #21018 

**Thread dump:**
```
java.lang.Thread.State: RUNNABLE
	  at org.ballerinalang.jvm.scheduling.Scheduler.getStrand(Scheduler.java:104)
	  at org.ballerinalang.jvm.BallerinaValues.createObjectValue(BallerinaValues.java:91)
	  at org.ballerinalang.net.http.caching.ResponseCacheControlObj.<init>(ResponseCacheControlObj.java:54)
	  at org.ballerinalang.net.http.HttpUtil.populateInboundResponse(HttpUtil.java:780)
	  at org.ballerinalang.net.http.HttpUtil.createResponseStruct(HttpUtil.java:1169)
	  at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction$HTTPClientConnectorListener.onMessage(AbstractHTTPAction.java:434)
	  at org.wso2.transport.http.netty.contractimpl.DefaultHttpResponseFuture.notifyHttpListener(DefaultHttpResponseFuture.java:110)
	  at org.wso2.transport.http.netty.contractimpl.sender.states.ReceivingHeaders.readInboundResponseHeaders(ReceivingHeaders.java:77)
	  at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.readInboundResponseHeaders(SenderReqRespStateManager.java:54)
	  at org.wso2.transport.http.netty.contractimpl.sender.states.RequestCompleted.readInboundResponseHeaders(RequestCompleted.java:67)
	  at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.readInboundResponseHeaders(SenderReqRespStateManager.java:54)
	  at org.wso2.transport.http.netty.contractimpl.sender.TargetHandler.channelRead(TargetHandler.java:85)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315)
	  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429)
	  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
1.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#21018 

**Suggested Labels (optional):**
Area/StandardLibs

**Comment by manuranga** [comment]
Additional info stdlib team:
This occurs when ever you use `BallerinaValues.createObjectValue` from a non-ballerina thread and object init code has concurrency (ie: `start` keyword). 

We (runtime team) has to provide a new API for the stdlib to provided the correct scheduler to fix this.
