### ISSUE TITLE
Intermittent test failure in Failover Client testcase

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#22990]
**Description:**
The following tests are failing intermittently. need to fix asap.

```
jBallerina-Test-Suite > ballerina-websocket-tests > org.ballerinalang.test.service.websocket.FailoverClientTest > testTextFrameWithSecondServer FAILED    org.ballerinalang.test.context.BallerinaTestException: Unable to start ballerina server on port 15200 : Port already in use        at org.ballerinalang.test.context.Utils.checkPortAvailability(Utils.java:127)        at org.ballerinalang.test.util.websocket.server.WebSocketRemoteServer.run(WebSocketRemoteServer.java:55)        at org.ballerinalang.test.service.websocket.FailoverClientTest.initiateServer(FailoverClientTest.java:142)        at org.ballerinalang.test.service.websocket.FailoverClientTest.testTextFrameWithSecondServer(FailoverClientTest.java:51)
--
```
```
jBallerina-Test-Suite > ballerina-websocket-tests > org.ballerinalang.test.service.websocket.FailoverClientTest > testHandshakeTimeout FAILED    org.ballerinalang.test.context.BallerinaTestException: Unable to start ballerina server on port 15300 : Port already in use        at org.ballerinalang.test.context.Utils.checkPortAvailability(Utils.java:127)        at org.ballerinalang.test.util.websocket.server.WebSocketRemoteServer.run(WebSocketRemoteServer.java:55)        at org.ballerinalang.test.service.websocket.FailoverClientTest.initiateServer(FailoverClientTest.java:142)        at org.ballerinalang.test.service.websocket.FailoverClientTest.testHandshakeTimeout(FailoverClientTest.java:90)
```
```
jBallerina-Test-Suite > ballerina-websocket-tests > org.ballerinalang.test.service.websocket.FailoverClientTest > testFailoverWithBothServerFirstStartSecondServer FAILED    org.ballerinalang.test.context.BallerinaTestException: Unable to start ballerina server on port 15200 : Port already in use        at org.ballerinalang.test.context.Utils.checkPortAvailability(Utils.java:127)        at org.ballerinalang.test.util.websocket.server.WebSocketRemoteServer.run(WebSocketRemoteServer.java:55)        at org.ballerinalang.test.service.websocket.FailoverClientTest.initiateServer(FailoverClientTest.java:142)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kalaiyarasiganeshalingam** [comment]
Close this issue as it fixed in #22992
