### ISSUE TITLE
Table testcases are failing in bstring-unit-test module

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#23132]
**Description:**
As you are aware, we have introduced a new table implementation for the next Ballerina release. In this process, we have removed the old Table implementation and related testcases in the PR [1].

Once, the new implementation is merged with [2], we have started enabling the existing table test cases which are disabled in [1]. Even though, we were able to enable the testcases in unit-test module we have seen some issues when enabling the same testcases in bstring-unit-test module. 

For example, if you consider the testcases in [3]. We are facing the below exception.

```ballerina
ballerina-test-suite > jballerina-test > org.ballerinalang.test.types.anydata.AnydataTest > testAnydataToUnion2 FAILED
    org.ballerinalang.util.exceptions.BLangRuntimeException: Error while invoking function 'testAnydataToUnion2'
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:409)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1390)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:162)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:1439)
        at org.ballerinalang.test.types.anydata.AnydataTest.testAnydataToUnion2(AnydataTest.java:259)

        Caused by:
        java.lang.RuntimeException: Error while invoking function 'testAnydataToUnion2'

            Caused by:
            java.lang.reflect.InvocationTargetException

                Caused by:
                java.lang.ClassCastException: java.lang.String cannot be cast to org.ballerinalang.jvm.values.api.BString
``` 

[1] https://github.com/ballerina-platform/ballerina-lang/pull/22284
[2] https://github.com/ballerina-platform/ballerina-lang/pull/22874
[3] https://github.com/ballerina-platform/ballerina-lang/pull/23115/commits/cebe4a08ce4c8ba0e8d627c45ed4ba8ce564aaa2

**Comment by riyafa** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/23444
