### ISSUE TITLE
Identify and fix issues in `xml<T> & readonly`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23276]
**Description:**
$title. Need more in depth tests to identify any issues.

The following issues are present for `xml:Element & readonly` with attributes.

Case I - the type of the attribute map is not set as readonly
```ballerina
import ballerina/lang.'xml as xmllib;

public function main() {
    xmllib:Element & readonly x = xml `<book status="available" count="5"/>`;

    // The following fails with 
    // `incompatible types: expected 'map<string> & readonly', found 'map<string>'`
    map<string> & readonly attributeMap = x.getAttributes();
}
```

Case II - `setAttribute` fails at runtime since the value is considered immutable - need to have a mechanism to distinguish initalization updates vs subsequent updates

```ballerina
import ballerina/lang.'xml as xmllib;

public function main() {
    xmllib:Element & readonly x = xml `<book status="available" count="5"/>`;

    map<string> attributeMap = x.getAttributes();
}
```

This **crashes** at runtime - ballerina-internal.log

```
[2020-05-15 00:02:43,513] SEVERE {b7a.log.crash} - {ballerina/lang.xml}InvalidUpdate 
org.ballerinalang.jvm.util.exceptions.BLangFreezeException: {ballerina/lang.xml}InvalidUpdate
	at org.ballerinalang.jvm.values.ReadOnlyUtils.handleInvalidUpdate(ReadOnlyUtils.java:61)
	at org.ballerinalang.jvm.values.XMLItem.setAttribute(XMLItem.java:202)
	at org.ballerinalang.jvm.values.XMLValue.setAttribute(XMLValue.java:75)
	at qwe.main(qwe.bal:4)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:267)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:235)
	at java.lang.Thread.run(Thread.java:745)
```

Sub-task of #22515

**Comment by MaryamZi** [comment]
Created https://github.com/ballerina-platform/ballerina-spec/issues/520 regarding Case I.

The following should work regardless.

```ballerina
import ballerina/lang.'xml as xmllib;

public function main() {
    xmllib:Element & readonly x = xml `<book status="available" count="5"/>`;

    map<string> & readonly attrMap = <map<string> & readonly> x.getAttributes();
}
```

Currently panics at runtime.

```cmd
$ ballerina run qwe.bal
Compiling source
        qwe.bal
Running executables

error: {ballerina}TypeCastError message=incompatible types: 'map<string>' cannot be cast to 'map<string> & readonly'
        at qwe:main(qwe.bal:6)
```

**Comment by MaryamZi** [comment]
According to the conclusion on https://github.com/ballerina-platform/ballerina-spec/issues/520, the current behaviour is correct. i.e., can't assign to `map<string> & readonly attrMap`.

**Comment by MaryamZi** [comment]
Case IV - Types of items nested in an `xml:Element & readonly`-typed value are not immutable.

```ballerina
import ballerina/io;
import ballerina/lang.'xml;

public function main() {
    'xml:Element & readonly x = xml `<foo><bar>true</bar><!--I'm a comment--></foo>`;

    io:println(x.isReadOnly()); // true

    foreach var item in x/* {
        io:println(item); 
        io:println(item.isReadOnly()); // false
    }
}
```

```cmd
$ ballerina run xyz.bal 
Compiling source
        xyz.bal
Running executables

true
<bar>true</bar>
false
<!--I'm a comment-->
false
```
