### ISSUE TITLE
Parser crashes with type-cast-expr recovery

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#23287]
**Description:**

Sample: 
```java
function foo(){
    a = <int> > a;
}
```

Error: 
```
Exception in thread "main" java.lang.IllegalStateException: type-cast-expr
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExpressionRhs(BallerinaParserErrorHandler.java:1431)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:659)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:188)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:375)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:316)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1263)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:188)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:368)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:316)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1263)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:188)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:368)
```

Also operator precedence is wrong in `type-cast-expr` parsing.

Sample:
```
function foo(){
    a = <int> a + <int> b;
}
```

**Suggested Labels:**
Component/Parser, Priority/Blocker, Type/Bug

**Suggested Assignees:**
@lochana-chathura

**Comment by SupunS** [comment]
This fixed with https://github.com/ballerina-platform/ballerina-lang/pull/23296
