### ISSUE TITLE
Wait call inside the initialiser for array object creation returns ClassCastException

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#23434]
**Description:**
The array default object initializer with async calls return a ClassCastException when wait is invoked at the initializer.

**Steps to reproduce:**
```ballerina
import ballerina/io;
type Student object {
    public string name;
    public int age;
    public function __init() {
        future<int> accumulator = start add(2, 4);
        self.name = "ABC";
        self.age = wait accumulator;
    }
};
function add(int i, int j) returns int {
    int k = i + j;
    return k;
}

public function main() {
      Student s = new();
      Student[] arr = [];
      arr[0] = s;
      arr[2] = s;
      io:println(arr[1]);
}
```
Output
```
ballerina: Oh no, something really went wrong.
```
ballerina-internal.log
```
[2020-05-22 15:33:49,634] SEVERE {b7a.log.crash} - Student_$__init$Frame cannot be cast to ballerina.io.printlnFrame 
java.lang.ClassCastException: Student_$__init$Frame cannot be cast to ballerina.io.printlnFrame
	at ballerina.io.print.println(print.bal:36)
	at asynObjectCreation.main(asynObjectCreation.bal:21)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:267)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:235)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
master 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#21018 

**Suggested Labels (optional):**
Area/jBallerina
Component/JVMCodeGen
Type/Bug

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
With the latest fix to BallerinaValues, is it still a `ClassCastException` ? or has it changed?

**Comment by HindujaB** [comment]
It is still a `ClassCastException`

**Comment by HindujaB** [comment]
We can reproduce this with the following code in SL-beta3-SNAPSHOT
```ballerina
import ballerina/io;

class Student {
    public string name;
    public int age;
    public function init() {
        future<int> accumulator = start add(2, 4);
        self.name = "ABC";
        self.age = checkpanic wait accumulator;
    }
}

function add(int i, int j) returns int {
    int k = i + j;
    return k;
}

public function main() {
    Student s = new ();
    Student[] arr = [];
    arr[2] = s;
    io:println(arr);
    // Student a = arr[1]; This line works
    // Only when we have the function call from another module, it fails. 
}
```
