### ISSUE TITLE
Getting a "Bad. Sad" with `F f = a => b => a + b;`

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#23621]
I am getting the attached error with the following program. 

```ballerina
type F function (int) returns function (int) returns int;

F f = a => b => a + b;
```

This NPE occurs during the BIROptimization phase.

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/4704736/ballerina-internal.log)

**Comment by HindujaB** [comment]
The issue seems to be not present in the current master. 
I tried with the following bal program and didn't get the expected error.

```ballerina
import ballerina/io;
type F function (int) returns function (int) returns int;

public function main() {
    F f = a => b => a + b;
    var func = f(7);
    var result = func(5);
    io:println(result);
}
```
output :  `12`

**Comment by HindujaB** [comment]
@sameerajayasoma  Can you please mention the version which you have encountered the issue?

**Comment by HindujaB** [comment]
The issue appears at the `v2.0.0-Preview1-M6`. The above code gets a bad sad error. Unlike the NPE mentioned in the issue, a class cast exception is received.

ballerina-internal-log:
```
[2020-06-22 09:07:02,121] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.expressions.BLangArrowFunction cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangArrowFunction cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2032)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.ImplicitAnonymousFunctionExpressionNode.apply(ImplicitAnonymousFunctionExpressionNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3697)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2392)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2363)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3581)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1281)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1162)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1120)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:472)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:430)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:141)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:114)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by SupunS** [comment]
Reopening the issue since, even-though the operator precedence is fixed, class cast exceptions in the node transformer similar to above could occur if the LHS of the arrow function is not a valid node (negative scenario).
