### ISSUE TITLE
Parser crashes for invalid tuple arrays

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#23736]
Consider the following program:
```ballerina
public function main() {
    [int, string, float][] data = [
                    { id: 1, name: "P1", price: 100 },
                    { id: 2, name: "P2", price: 200 },
                    { id: 1, name: "P3", price: 300 }
                ];
}
```
The above program crashes due to a class cast exception. Following is the crash log:
```
[2020-06-04 19:22:34,231] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.ListBindingPatternNode cannot be cast to io.ballerinalang.compiler.syntax.tree.CaptureBindingPatternNode 
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.ListBindingPatternNode cannot be cast to io.ballerinalang.compiler.syntax.tree.CaptureBindingPatternNode
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1713)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:299)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateBLangStatements(BLangNodeTransformer.java:2148)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:947)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:299)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:896)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:299)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:366)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:299)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:324)
	at org.wso2.ballerinalang.compiler.parser.Parser.populateCompilationUnitNew(Parser.java:146)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:127)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:108)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:499)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:291)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by pubudu91** [comment]
Another example of an invalid tuple array:
```ballerina
[int, string, float][] data = [
                    [ id: 1, name: "P1", price: 100 ],
                    [ id: 2, name: "P2", price: 200 ],
                    [ id: 1, name: "P3", price: 300 ]
                ];
```
The above also crashes with the same class cast exception. In addition to that, get the following parser errors as well:
```
Compiling source
	23336.bal
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
xxx.bal:0:0:invalid token ':'
```

**Comment by SupunS** [comment]
In the second case, parser errors are acceptable, since the source is not correct. Therefore parser reports the invalid tokens. These error messages are for testing purpose only. Proper error reporting mechanism is coming soon.

Regarding the 1st issue, the class cast exception is same as #23737 right? Shall we keep only one and close the other?

**Comment by manuranga** [comment]
@m36dot can you please take a look.

**Comment by pubudu91** [comment]
Yeah, opened #23737 due to the false positive parsing error.
