### ISSUE TITLE
Exception during API doc gen for typedesc

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#23832]
**Description:**
When building the grpc module,  getting an UnsupportedOperationException
```
> Task :ballerina-grpc:createBalo
Compiling source
        ballerina/grpc
Exception in thread "main" java.lang.UnsupportedOperationException: Type def not supported for CONSTRAINED_TYPE
        at org.ballerinalang.docgen.Generator.createTypeDefModels(Generator.java:169)
        at org.ballerinalang.docgen.Generator.generateModuleConstructs(Generator.java:84)
        at org.ballerinalang.docgen.docs.BallerinaDocGenerator.getDocsGenModel(BallerinaDocGenerator.java:442)
        at org.ballerinalang.docgen.docs.BallerinaDocGenerator.writeAPIDocsForModules(BallerinaDocGenerator.java:142)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genApiDoc(GenerateBalo.java:162)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:152)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:91)

> Task :ballerina-grpc:createBalo FAILED
```

**Steps to reproduce:**
Add the following type and build the grpc module
```ballerina
# Represents gRPC related errors.
public type Error CancelledError | UnKnownError | InvalidArgumentError | DeadlineExceededError | NotFoundError
| AlreadyExistsError | PermissionDeniedError | UnauthenticatedError | ResourceExhaustedError | FailedPreconditionError
| AbortedError | OutOfRangeError | UnimplementedError | InternalError | UnavailableError | DataLossError
| ResiliencyError;

# Represents gRPC related error types.
public type ErrorType typedesc<Error>;
```

Build command
```
./gradlew :ballerina-grpc:build  -x :composer-library:npmBuild -x :plugin-vscode:test -x :jballerina-tools:generateDocs -x :ballerina-file:createBalo -x :ballerina-file:createBir -x :ballerina-ldap:createBalo -x :ballerina-ldap:createBir -x :ballerina-transactions:createBalo -x :ballerina-transactions:createBir
```

**Affected Versions:**
Current master

**Related Issues**
https://github.com/ballerina-platform/ballerina-lang/issues/22516

**Comment by rdhananjaya** [comment]
This is fixed in #23839 and can be closed when `23283-add-distinct-type` branch is merged to master
