### ISSUE TITLE
Compiler doesn't complain about missing a variable with user-defined types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23847]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo record {|
    int i;
|};

public function main() {
    // int = int; // fails with invalid token '='
    // Foo = 1; // fails with expected 'typedesc<Foo>', found 'int'

    Foo = Foo; // doesn't fail!
}
```

Results in the runtime crashing.

ballerina-internal.log
```
[2020-06-09 16:21:46,526] SEVERE {b7a.log.crash} - org.ballerinalang.jvm.values.TypedescValue cannot be cast to org.ballerinalang.jvm.values.MapValue 
java.lang.ClassCastException: org.ballerinalang.jvm.values.TypedescValue cannot be cast to org.ballerinalang.jvm.values.MapValue
	at xyz.main(xyz.bal:9)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:745)
```

**Affected Versions:**
1.2.4

**Comment by rdhananjaya** [comment]
Fixing this should potentially fix https://github.com/ballerina-platform/ballerina-lang/issues/30311
@lasinicl please test and close https://github.com/ballerina-platform/ballerina-lang/issues/30311 when you fix this
