### ISSUE TITLE
ClassCastException when parsing `public remote` functions

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#23859]
**Description:**
$subject when trying to parse,
```ballerina
public type Client client object {
    public function __init() {
    }

    public remote function query() {
    }
};
```

```log
[2020-06-09 23:52:32,896] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to io.ballerinalang.compiler.syntax.tree.Token 
java.lang.ClassCastException: io.ballerinalang.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to io.ballerinalang.compiler.syntax.tree.Token
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:939)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:921)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:335)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:694)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:335)
	at io.ballerinalang.compiler.syntax.tree.ObjectTypeDescriptorNode.apply(ObjectTypeDescriptorNode.java:62)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:2975)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:534)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:335)
	at io.ballerinalang.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:402)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:335)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:360)
	at org.wso2.ballerinalang.compiler.parser.Parser.populateCompilationUnitNew(Parser.java:146)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:127)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:108)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:499)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:74)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:291)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Comment by niveathika** [comment]
@SupunS This is a blocker for SQL connector. We need the fix ASAP for https://github.com/ballerina-platform/ballerina-lang/issues/23565

I appreciate if this is fixed ASAP.
