### ISSUE TITLE
Test `testServiceLvlVarLockBasic` fails intermittently

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#23879]
**Description:**
This lock test case fails intermittently. I have attached the log file for more details.
```
org.testng.internal.thread.ThreadTimeoutException : Method org.ballerinalang.test.lock.LocksInServicesTest.testServiceLvlVarLockBasic() didn't finish within the time-out 120000

at java.lang.AssertionError.<init>(AssertionError.java:74)	
	at org.testng.Assert.fail(Assert.java:85)	
	at org.ballerinalang.test.lock.LocksInServicesTest.testServiceLvlVarLockBasic(LocksInServicesTest.java:76)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)	
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)	
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)	
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)	
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)
```
[logs_9316.zip](https://github.com/ballerina-platform/ballerina-lang/files/4757535/logs_9316.zip)

**Comment by MaryamZi** [comment]
This test seems to have been removed in [056b5a1](https://github.com/ballerina-platform/ballerina-lang/commit/056b5a108a972bee0996d91f1c722c0aff33e4a5).

Issue to check and add back relevant tests - https://github.com/ballerina-platform/ballerina-lang/issues/35212.
