### ISSUE TITLE
Class cast exception when parsing `return stream<record{}, sql:Error>`

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#23890]
**Description:**
$subject when trying to parse,
```ballerina
public type Client client object {
    public function __init() {
    }

    public remote function query() returns stream<record{}, sql:Error> {
    }
};

```

```log
[2020-06-10 19:05:54,404] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangType 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangType
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2432)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:342)
	at io.ballerinalang.compiler.syntax.tree.StreamTypeDescriptorNode.apply(StreamTypeDescriptorNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:3158)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFuncSignature(BLangNodeTransformer.java:2861)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createObjectMethodNode(BLangNodeTransformer.java:1029)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:996)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:342)
	at io.ballerinalang.compiler.syntax.tree.ObjectMethodDefinitionNode.apply(ObjectMethodDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:713)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:342)
	at io.ballerinalang.compiler.syntax.tree.ObjectTypeDescriptorNode.apply(ObjectTypeDescriptorNode.java:62)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:3158)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:546)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:342)
	at io.ballerinalang.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:409)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:342)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:367)
	at org.wso2.ballerinalang.compiler.parser.Parser.populateCompilationUnitNew(Parser.java:146)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:127)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:108)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:499)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:60)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:429)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by niveathika** [comment]
Fixed in master. (Tested with commit a9c142ce4478b3359b2772cc1936c3200bd9a685)
