### ISSUE TITLE
Unable to have two methods with transaction block within the same .bal file

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#23924]
**Description:**
If two methods are having transaction block within the same .bal file then, it fails. It fails when running with `ballerina run` and also when using with JAVA in the unit tests. 

The error during `ballerina run`
```
[2020-06-10 23:13:07,222] SEVERE {b7a.log.crash} - null 
java.lang.NegativeArraySizeException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:482)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:471)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:144)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:118)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:288)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:284)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:231)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:135)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:291)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.merge(Frame.java:1222)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:1744)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:1451)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:529)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
 
[2020-06-10 23:14:33,730] SEVERE {b7a.log.crash} - null 
java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.merge(Frame.java:1222)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:1744)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:1451)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:529)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:482)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:471)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:144)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:118)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:288)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:284)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:231)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:135)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:291)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

The error in the JAVA class along with unit tests
```
    java.lang.ClassCastException: org.ballerinalang.model.values.BString cannot be cast to org.ballerinalang.model.values.BMap
        at org.ballerinalang.test.util.BRunUtil.getJVMValue(BRunUtil.java:505)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:322)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1155)
        at org.ballerinalang.sql.transaction.LocalTransactionsTest.testLocalTransaction(LocalTransactionsTest.java:55)

```

**Steps to reproduce:**
Use the sample code below to test this. If I comment the second method `testTransactionRollback` then it works.

```
import ballerina/transactions;
import ballerina/io;


function testLocalTransaction(string jdbcURL, string user, string password) returns @tainted [int, int, boolean, boolean]|error? {
    int retryVal = -1;
    boolean committedBlockExecuted = false;
    transactions:Info transInfo;
    retry(1) transaction {
        transInfo = transactions:info();
        var commitResult = commit;
        if(commitResult is ()){
            committedBlockExecuted = true;
        }
    }
    retryVal = transInfo.retryNumber;
    int count = 0;
    return [retryVal, count, committedBlockExecuted];
}

function testTransactionRollback(string jdbcURL, string user, string password) returns @tainted [int, int, boolean]|error?{
    int retryVal = -1;
    boolean stmtAfterFailureExecuted = false;
    transactions:Info transInfo;
    retry(1) transaction {
        transInfo = transactions:info();
        stmtAfterFailureExecuted = true;
        check commit;
    }

    retryVal = transInfo.retryNumber;
    int count = 0;
    return [retryVal, count, stmtAfterFailureExecuted];
}

public function main() {
    var v1 = testLocalTransaction("foo", "bar", "ddd");
    io:println("called");
}
```

**Affected Versions:**
2.0.0 (master)
**OS, DB, other environment details and versions:**
Mac OS.
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sinthuja** [comment]
The same error happens when I have two transactions block in the same method as well as shown below.

```
function testTwoTransactions(string jdbcURL, string user, string password) returns @tainted [int, int, int]|error? {
    mockclient:Client dbClient = check new (url = jdbcURL, user = user, password = password);

    transactions:Info transInfo1;
    transactions:Info transInfo2;
    retry (1) transaction {
        transInfo1 = transactions:info();
        var e1 = check dbClient->execute("Insert into Customers (firstName,lastName,registrationID,creditLimit,country) " +
                            "values ('James', 'Clerk', 400, 5000.75, 'USA')");
        var e2 = check dbClient->execute("Insert into Customers (firstName,lastName,registrationID,creditLimit,country) " +
                            "values ('James', 'Clerk', 400, 5000.75, 'USA')");
        check commit;
    }
    int returnVal1 = transInfo1.retryNumber;

    retry(1) transaction {
        transInfo2 = transactions:info();
        var e1 = dbClient->execute("Insert into Customers (firstName,lastName,registrationID,creditLimit,country) " +
                            "values ('James', 'Clerk', 400, 5000.75, 'USA')");
        var e2 = dbClient->execute("Insert into Customers (firstName,lastName,registrationID,creditLimit,country) " +
                            "values ('James', 'Clerk', 400, 5000.75, 'USA')");
        check commit;
    }
    int returnVal2 = transInfo2.retryNumber;

    //check whether update action is performed
    int count = check getCount(dbClient, "400");
    check dbClient.close();
    return [returnVal1, returnVal2, count];
}
```

**Comment by ThisaruGuruge** [comment]
Facing the same in [Kafka tests](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/messaging/kafka/src/test/resources/test-src/transactions/commit_consumer_offsets.bal).

**Comment by sinthuja** [comment]
With the latest changes on the https://github.com/gimantha/ballerina-lang/tree/new-transaction-impl, I was able to have more transaction blocks in a bal file. 

However, the issue mentioned in the [comment](https://github.com/ballerina-platform/ballerina-lang/issues/23924#issuecomment-642537063) where having two transaction blocks in a method still exists.

**Comment by ThisaruGuruge** [comment]
Thank you @sinthuja. Will try this.
