### ISSUE TITLE
NPE when parsing <@untainted> annotation

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#23964]
**Description:**
$subject when compiling below
```ballerina
var data = <@untainted> "test";
```
```
[2020-06-11 19:03:00,671] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:3250)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1696)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:354)
	at io.ballerinalang.compiler.syntax.tree.TypeCastExpressionNode.apply(TypeCastExpressionNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3020)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.access$400(BLangNodeTransformer.java:354)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer$SimpleVarBuilder.setExpressionByNode(BLangNodeTransformer.java:3792)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVarDef(BLangNodeTransformer.java:2093)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2060)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:354)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateBLangStatements(BLangNodeTransformer.java:2843)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1102)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:354)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1002)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:965)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:354)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:421)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:354)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:379)
	at org.wso2.ballerinalang.compiler.parser.Parser.populateCompilationUnitNew(Parser.java:146)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:127)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:108)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:499)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:60)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:429)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by niveathika** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/23829
