### ISSUE TITLE
Throwing bad sad error while writing bir file 

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#23983]
**Description:**
Throwing bad sad error when it is trying to write bir file for an imported module with compilation errors.

ballerina-internal.log
```
[2020-06-12 10:03:06,385] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:52)
	at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:99)
	at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:64)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:429)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)

```

**Steps to reproduce:**
Build a ballerina module which has an import module with compilation errors.

**Affected Versions:**
ballerina-2.0.0-SNAPSHOT

**Comment by IrushiL** [comment]
Fixed in Beta 1 with https://github.com/ballerina-platform/ballerina-lang/pull/30234
