### ISSUE TITLE
OutOfMemoryError when trying to build SyntaxTree  

### ISSUE THREAD

**Issue by suhothayan** [ballerina-platform/ballerina-lang#24058]
**Description:**
OutOfMemoryError when trying to build SyntaxTree
 
**Steps to reproduce:**
```
  @Test
    public void test(){
        String input = "import ballerina/http;\n" +
                "public function main() {\n" +
                "http:Client clientEndpoint = new (\"http://postman-echo.com\");\n" +
                "http:Response response = check clientEndpoint->get(\"/get?test=123\");\n" +
                "}";
        TextDocument textDocument = TextDocuments.from(input);
        SyntaxTree oldTree = SyntaxTree.from(textDocument);
        TextEdit[] edits = new TextEdit[]{
                TextEdit.from(TextRange.from(23,47-23),
                        "service hello on new http:Listener(9090) {\n" +
                        "    resource function sayHello(http:Caller caller, http:Request req) {"),
                TextEdit.from(TextRange.from(79,1), "    }\n" +
                        "}")
        };
        TextDocumentChange textDocumentChange = TextDocumentChange.from(edits);
        SyntaxTree newTree = SyntaxTree.from(oldTree, textDocumentChange);
        System.out.println(newTree);
    }

```

Getting the below error 

```
    java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:265)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
        at java.util.ArrayList.add(ArrayList.java:462)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2480)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2413)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2398)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.createFuncDefOrMethodDecl(BallerinaParser.java:1457)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1444)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1414)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncDefinition(BallerinaParser.java:1388)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseResource(BallerinaParser.java:6464)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseResource(BallerinaParser.java:6457)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseResource(BallerinaParser.java:6424)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseResources(BallerinaParser.java:6387)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseServiceBody(BallerinaParser.java:6373)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseServiceRhs(BallerinaParser.java:6209)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseServiceDecl(BallerinaParser.java:6189)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1313)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:778)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:708)
        at io.ballerinalang.compiler.internal.parser.incremental.IncrementalParser.parseTopLevelNode(IncrementalParser.java:44)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:609)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:85)
        at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:63)
        at org.ballerinalang.langserver.extensions.document.ASTModifyTest.test(ASTModifyTest.java:436)

1 test completed, 1 failed
```

**Affected Versions:**
2.0.0-SNAPSHOT

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
Sameera, Supun

**Comment by suhothayan** [comment]
Getting the same error even for simple delete functions 

```
    @Test
    public void test() {
        String input = "import ballerina/http;public function main() {http:Client clientEndpoint = new (\"http://postman-echo.com\");http:Response response = check clientEndpoint->get(\"/get?test=123\");var a = 1;}";
        TextDocument textDocument = TextDocuments.from(input);
        SyntaxTree oldTree = SyntaxTree.from(textDocument);
        TextEdit[] edits = new TextEdit[]{
                TextEdit.from(TextRange.from(100, 0), ""),
        };
        TextDocumentChange textDocumentChange = TextDocumentChange.from(edits);
        SyntaxTree newTree = SyntaxTree.from(oldTree, textDocumentChange);
    }
```
Error 

```
    java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:265)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
        at java.util.ArrayList.add(ArrayList.java:462)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2511)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2444)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2429)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.createFuncDefOrMethodDecl(BallerinaParser.java:1475)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1462)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1432)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1417)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1295)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:779)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:708)
        at io.ballerinalang.compiler.internal.parser.incremental.IncrementalParser.parseTopLevelNode(IncrementalParser.java:44)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:608)
        at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:85)
        at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:63)
        at org.ballerinalang.langserver.extensions.document.ASTModifyTest.test(ASTModifyTest.java:476)
```

**Comment by gimantha** [comment]
We will close this issue until we start to work on it later
