### ISSUE TITLE
"Syntax kind is not supported: READONLY_KEYWORD" error for record/object intersection-typed fields where the first member is `readonly`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24089]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
// Record
type Foo record {
    int[] & readonly x = [1, 2];    // OK
    readonly & int[] y = [1, 2];    // ERROR
};

// Object
type Bar object {
    int[] & readonly x = [1, 2];    // OK
    readonly & int[] y = [1, 2];    // ERROR
};
```

ballerina-internal.log for the record (the object one is similar).
```log
[2020-06-14 11:23:12,678] SEVERE {b7a.log.crash} - Syntax kind is not supported: READONLY_KEYWORD 
java.lang.RuntimeException: Syntax kind is not supported: READONLY_KEYWORD
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1842)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.Token.apply(Token.java:89)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:3027)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.IntersectionTypeDescriptorNode.apply(IntersectionTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:3720)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVar(BLangNodeTransformer.java:3490)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVar(BLangNodeTransformer.java:3478)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1014)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.RecordFieldWithDefaultValueNode.apply(RecordFieldWithDefaultValueNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:955)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.RecordTypeDescriptorNode.apply(RecordTypeDescriptorNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:3720)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:592)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:455)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:388)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:413)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:131)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:106)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:499)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 ```

**Affected Versions:**
Current master

**Comment by MaryamZi** [comment]
The following test which were disabled with https://github.com/ballerina-platform/ballerina-lang/pull/23795/commits/c9b99bcb74708bd1f7bf7a4763627dcc2c8330a9 for the new parser can be enabled when fixing this.

- ReadonlyObjectFieldTest.java - https://github.com/ballerina-platform/ballerina-lang/commit/c9b99bcb74708bd1f7bf7a4763627dcc2c8330a9#diff-04c03ee79ed553d73d2b9bea8eabc0f5R42
- ReadonlyRecordFieldTest.java - https://github.com/ballerina-platform/ballerina-lang/commit/c9b99bcb74708bd1f7bf7a4763627dcc2c8330a9#diff-9ece5e124027d38986e429111b4c4516R42
