### ISSUE TITLE
Incremental Parser tries to find java introp functions for functions in abstract class

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#24155]
**Description:**
$subject
```ballerina
public type Client abstract client object {
 public remote function query(@untainted string|ParameterizedString sqlQuery, typedesc<record {}>? rowType = ())
    returns @tainted stream <record {}, Error>;
}
```

```
Exception in thread "main" org.ballerinalang.compiler.BLangCompilerException: cannot find full qualified class name for extern function : ballerina/sql/0_5_0/execute
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.createExternalFunctionWrapper(ExternalMethodGen.java:247)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateClassNameMapping(JvmPackageGen.java:664)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:449)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:144)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:118)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:300)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:296)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:243)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:136)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:127)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:87)

```

**Comment by niveathika** [comment]
Fixed in enable-lib-with-new-parser branch (7ee6851fa0bcfef0f12e2789d90bd4236637d28b)
