### ISSUE TITLE
VisibleEndpointVisitor.visit(packageNode) fails to visit some code at build time

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#24194]
**Description:**
Some code fails to compile due to VisibleEndpointVisitor.visit(packageNode) failing to visit the code being compiled.

**Code from DefaultObservabilitySymbolCollector** (Added with PR #23518 as part of packaging AST in the Jar)
```
VisibleEndpointVisitor visibleEndpointVisitor = new VisibleEndpointVisitor(compilerContext);
visibleEndpointVisitor.visit(packageNode);
visibleEPsByNode = visibleEndpointVisitor.getVisibleEPsByNode();
```
**Sample code that cannot be compiled:** https://raw.githubusercontent.com/ballerina-platform/ballerina-lang/413895d3bf2135cadbd075823d19f3f74446475e/tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/03_bidirectional_streaming_service.bal

Doing either one of the following makes the code compilable.
1. By moving `grpc:Caller conn;` in Line 81 to Line 89 makes.
2. Commenting out `var v = connectionsMap.remove(caller.getId().toString());` in line 84
Option 2 does not make the code executable proper code. But `VisibleEndpointVisitor.visit(packageNode)` does not fail. 

Option 2 doesn't make it a proper running program though. I mentioned it since it might help to debug the issue.

**CLI  Build Command Output**
```
Compiling source
	03_bidirectional_streaming_service.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

**Ballerina Internal Log**
```
[2020-06-16 14:01:42,354] SEVERE {b7a.log.crash} - null 
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$resolveEndpointsFromStatements$9(VisibleEndpointVisitor.java:225)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.resolveEndpointsFromStatements(VisibleEndpointVisitor.java:204)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:133)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$resolveEndpointsFromStatements$9(VisibleEndpointVisitor.java:231)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.resolveEndpointsFromStatements(VisibleEndpointVisitor.java:204)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:128)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:108)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$visit$3(VisibleEndpointVisitor.java:116)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:116)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:126)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$visit$1(VisibleEndpointVisitor.java:95)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:95)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getVisibleEndpoints(DefaultObservabilitySymbolCollector.java:159)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getModuleASTHolder(DefaultObservabilitySymbolCollector.java:146)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:85)
	at org.wso2.ballerinalang.compiler.CompilerDriver.generateObservabilityData(CompilerDriver.java:314)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:291)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:442)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by nadeeshaan** [comment]
This implementation has been removed and migrated to the latest semantic API based implementation and this is no longer valid. Hence closing the issue.
