### ISSUE TITLE
Index out of bounds in Windows when using incremental parser

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#24227]
**Description:**
$subject, when parsing
[simple-params-query-test.bal](https://github.com/niveathika/ballerina-lang/blob/master/stdlib/database/jdbc/src/test/resources/test-src/query/simple-params-query-test.bal)
```
2020-06-16T18:24:07.6293091Z ballerina-jdbc-test-suite > ballerina-jdbc-test > org.ballerinalang.jdbc.query.ParamsQueryTest > setup FAILED
2020-06-16T18:24:07.6666321Z     java.lang.IndexOutOfBoundsException: Index: '28746', Size: '28736'
2020-06-16T18:24:07.6667222Z         at io.ballerinalang.compiler.text.LineMap.positionRangeCheck(LineMap.java:59)
2020-06-16T18:24:07.6667615Z         at io.ballerinalang.compiler.text.LineMap.linePositionFrom(LineMap.java:40)
2020-06-16T18:24:07.6668019Z         at io.ballerinalang.compiler.text.TextDocument.linePositionFrom(TextDocument.java:41)
2020-06-16T18:24:07.6668374Z         at io.ballerinalang.compiler.syntax.tree.Node.lineRange(Node.java:110)
2020-06-16T18:24:07.6668808Z         at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getPosition(BLangNodeTransformer.java:448)
2020-06-16T18:24:07.6669506Z         at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:460)
2020-06-16T18:24:07.6669912Z         at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:404)
2020-06-16T18:24:07.6670280Z         at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
2020-06-16T18:24:07.6670668Z         at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:429)
2020-06-16T18:24:07.6671046Z         at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:131)
2020-06-16T18:24:07.6671500Z         at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:106)
2020-06-16T18:24:07.6671856Z         at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
2020-06-16T18:24:07.6672232Z         at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
2020-06-16T18:24:07.6672596Z         at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
2020-06-16T18:24:07.6672947Z         at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
2020-06-16T18:24:07.6673283Z         at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
2020-06-16T18:24:07.6673614Z         at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:516)
2020-06-16T18:24:07.6673962Z         at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:503)
2020-06-16T18:24:07.6674324Z         at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:731)
2020-06-16T18:24:07.6674695Z         at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:619)
2020-06-16T18:24:07.6675270Z         at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:701)
2020-06-16T18:24:07.6817407Z         at org.ballerinalang.test.util.BCompileUtil.compileOffline(BCompileUtil.java:125)
2020-06-16T18:24:07.6817833Z         at org.ballerinalang.jdbc.query.ParamsQueryTest.setup(ParamsQueryTest.java:57)

```
Full log of the [build](https://github.com/ballerina-platform/ballerina-lang/pull/24091/checks?check_run_id=777557068)
https://pipelines.actions.githubusercontent.com/pUXJn1fEhzukAfTMnMIuOxVrDE4lxWxdQvm21voQ2KAqQbuObE/_apis/pipelines/1/runs/11109/signedlogcontent/3?urlExpires=2020-06-16T18%3A41%3A18.4386556Z&urlSigningMethod=HMACV1&urlSignature=WANKgi%2F3iTBGuQv0JGvdoTYQq0m3oa5kIxJ3nXfhH6U%3D

**Steps to reproduce:**
Build https://github.com/ballerina-platform/ballerina-lang/pull/24091

**OS, DB, other environment details and versions:**
Windows

**Comment by niveathika** [comment]
Since this is not the issue with the feature. I am disabling these specific testcases in windows build and proceeding with the PR

**Comment by SupunS** [comment]
Related issues https://github.com/ballerina-platform/ballerina-lang/issues/24270
