### ISSUE TITLE
Test `testOOTBTracingWithWorkers` fails

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#24237]
**Description:**
Following is the excerpt of the log.

```
2020-06-17T03:29:38.4921806Z jBallerina-Test-Suite > ballerina-observability-tests > org.ballerinalang.test.observability.tracing.TracingTestCase > testOOTBTracingWithWorkers FAILED
2020-06-17T03:29:38.4922263Z     java.lang.AssertionError: Mismatch in number of spans reported. expected [38] but found [37]
2020-06-17T03:29:38.4922597Z         at org.testng.Assert.fail(Assert.java:96)
2020-06-17T03:29:38.4922910Z         at org.testng.Assert.failNotEquals(Assert.java:776)
2020-06-17T03:29:38.4923226Z         at org.testng.Assert.assertEqualsImpl(Assert.java:137)
2020-06-17T03:29:38.4923531Z         at org.testng.Assert.assertEquals(Assert.java:118)
2020-06-17T03:29:38.4923860Z         at org.testng.Assert.assertEquals(Assert.java:652)
2020-06-17T03:29:38.4924236Z         at org.ballerinalang.test.observability.tracing.TracingTestCase.testOOTBTracingWithWorkers(TracingTestCase.java:401)
```

**Comment by nadundesilva** [comment]
This seems to be intermittent.... Disabled the test for now... I will update and send a fix later..
