### ISSUE TITLE
Crash : optional field access in assignment crashes in new parser

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24272]
**Description:**
note $subject. Below code crashes in new parser. Old parser 

### Code
```Ballerina
type Quux record {|
    int id;
    string code?;
|};

function testInvalidOptionalFieldUpdate() {
    Quux q = {id: 100};
    q?.code = "asdsa"; // bad syntax
}

public function main() {
    testInvalidOptionalFieldUpdate();
}
```

### Crash log
```Logtalk
[2020-06-17 20:34:27,803] SEVERE {b7a.log.crash} - null
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:461)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.accept(BLangSimpleVarRef.java:61)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:972)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:591)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:550)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:358)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:358)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:243)
	at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:354)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:301)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	...
```

### Old parser
```Logtalk
error: .::m1.bal:9:5: optional field access cannot be used in the target expression of an assignment
```

**Steps to reproduce:**
Run above code in new parser.

**Affected Versions:**
jBallerina 2.0.0-SNAPSHOT
Language specification 2020R1

**OS, DB, other environment details and versions:**
macOS Catalina

**Suggested Labels (optional):**
Component/Compiler,Type/Bug,Area/Language

**Comment by sameerajayasoma** [comment]
I fixed this issue in the master with this PR: https://github.com/ballerina-platform/ballerina-lang/pull/24236. You get the following syntax error now. 

```
error: .::temp.bal:8:13: invalid expr in assignment lhs
```

We need to improve error messages and locations, though. I created a separate issue to track: https://github.com/ballerina-platform/ballerina-lang/issues/24286
