### ISSUE TITLE
Ballerina socket stdlib goto definition fails

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#24309]
**Description:**
The `ballerina/socket` module goto definition fails by giving the following error output log in VSCode. Note that, this `ballerina/socket` is a kind of different stdlib since it is migrated to a separate isolated repository[1] from ballerina-lang.

```sh
org.ballerinalang.langserver.exception.LSStdlibCacheException: Invalid module source root provided for module: [ballerina_socket_0.6.3]'}
com.google.common.util.concurrent.UncheckedExecutionException: org.ballerinalang.langserver.exception.LSStdlibCacheException: Invalid module source root provided for module: [ballerina_socket_0.6.3]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5148)
	at org.ballerinalang.langserver.util.definition.LSStandardLibCache.getTopLevelNodesForModule(LSStandardLibCache.java:164)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getStdLibDefinitionLocations(DefinitionUtil.java:118)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:87)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$6(BallerinaTextDocumentService.java:309)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.ballerinalang.langserver.exception.LSStdlibCacheException: Invalid module source root provided for module: [ballerina_socket_0.6.3]
	at org.ballerinalang.langserver.util.definition.LSStdLibCacheUtil.extract(LSStdLibCacheUtil.java:101)
	at org.ballerinalang.langserver.util.definition.LSStdLibCacheUtil.extractSourceForModule(LSStdLibCacheUtil.java:85)
	at org.ballerinalang.langserver.util.definition.LSStandardLibCache$1.load(LSStandardLibCache.java:94)
	at org.ballerinalang.langserver.util.definition.LSStandardLibCache$1.load(LSStandardLibCache.java:84)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	... 10 more
```

[1] https://github.com/ballerina-platform/module-ballerina-socket
**Steps to reproduce:**
Try socket BBE in VSCode.

**Comment by BuddhiWathsala** [comment]
Source code:

**Service**

```ballerina
import ballerina/io;
import ballerina/log;
import ballerina/socket;

service echoServer on new socket:Listener(61598) {

    resource function onConnect(socket:Caller caller) {
        log:printInfo("Client connected: " + caller.id.toString());
    }

    resource function onReadReady(socket:Caller caller) {
        var result = caller->read();
        if (result is [byte[], int]) {
            var [content, length] = result;
            if (length > 0) {

                var byteChannel =
                io:createReadableChannel(content);
                if (byteChannel is io:ReadableByteChannel) {
                    io:ReadableCharacterChannel characterChannel =
                    new io:ReadableCharacterChannel(byteChannel, "UTF-8");
                    var str = characterChannel.read(20);
                    if (str is string) {
                        string reply = <@untainted>str + " back";
                        byte[] payloadByte = reply.toBytes();

                        int i = 0;
                        int arrayLength = payloadByte.length();
                        while (i < arrayLength) {
                            var writeResult = caller->write(payloadByte);
                            if (writeResult is int) {
                                log:printInfo("Number of bytes written: "
                                    + writeResult.toString());
                                i = i + writeResult;
                                payloadByte = payloadByte.slice(writeResult, arrayLength);
                            } else {
                                log:printError("Unable to write the content",
                                    writeResult);
                            }
                        }
                    } else {
                        log:printError("Error while writing content to the caller",
                            str);
                    }
                }
            } else {
                log:printInfo("Client left: " + caller.id.toString());
            }
        } else {
            io:println(result);
        }
    }

    resource function onError(socket:Caller caller, error er) {
        log:printError("An error occurred", err = er);
    }
}

```

**Comment by nadeeshaan** [comment]
Closing the issue hence the definition implementation has been differed
