### ISSUE TITLE
Language server does not clean fixed errors

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24303]
**Description:**
Fixed errors are not going away.

### First Create a syntax error
<img width="584" alt="Screenshot 2020-06-18 at 13 48 41" src="https://user-images.githubusercontent.com/2173530/84996175-8b4dc180-b16a-11ea-8809-6f025bef7125.png">

### Then fix it
<img width="584" alt="Screenshot 2020-06-18 at 13 50 25" src="https://user-images.githubusercontent.com/2173530/84996300-b20bf800-b16a-11ea-9293-27d5d18e01f2.png">

### Logs
```Logtalk
[Info  - 2:20:56 PM] Operation 'text/didChange' {fileUri: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects/abstract_objects.bal'} updated}
[Info  - 2:20:56 PM] Operation 'text/codeAction' {projectRoot: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects'} added cache entry with {key: sourceRoot /Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects, errorStrategy: LSCustomErrorStrategy, compilerPhase: compilerPlugin, preserveWS: true, testEnabled: true, skipTests: false, sourceDirectory: LangServerFSProgramDirectory}
[Info  - 2:20:56 PM] Operation 'text/codeAction' {projectRoot: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects'}, compilation took 2ms
[Info  - 2:20:57 PM] Operation 'debouncer/diagnostics' {projectRoot: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects'}, compilation took 1ms
[Info  - 2:20:57 PM] Operation 'debouncer/diagnostics' {projectRoot: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects'} cleared 1 cached entries for the project
[Info  - 2:20:57 PM] Operation 'text/didChange' {fileUri: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects/abstract_objects.bal'} updated}
[Error - 2:20:58 PM] Computing 'diagnostics' failed! {uri: '/Users/rukshanp/Projects/ballerina-distribution/examples/abstract-objects/abstract_objects.bal', error: 'Oh no, something really went wrong. Bad. Sad.'}
org.ballerinalang.langserver.compiler.exception.CompilationFailedException: Oh no, something really went wrong. Bad. Sad.
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:246)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackages(LSModuleCompiler.java:177)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:76)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$didChange$16(BallerinaTextDocumentService.java:724)
	at org.ballerinalang.langserver.util.Debouncer.lambda$call$0(Debouncer.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.ballerinax.docker.DockerPlugin.process(DockerPlugin.java:100)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$2(CompilerPluginRunner.java:135)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:135)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:126)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:346)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:286)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:79)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:232)
	... 11 more

```

**Steps to reproduce:**
try abstract-objects BBE

**Affected Versions:**
vscode plugin v2.0.0-Preview1-M6

**Suggested Labels (optional):**
Area/Tooling,Component/LanguageServer,Type/Bug

**Comment by KRVPerera** [comment]
> 1. cd to ballerina-swan-lake-preview1-build2
> 2. execute 
> rm -f distributions/jballerina-2.0.0-Preview1-M6/bre/lib/docker-extension-2.0.0-Preview1-M6.jar distributions/jballerina-2.0.0-Preview1-M6/bre/lib/kubernetes-extension-2.0.0-Preview1-M6.jar
> 
> This will remove the both extensions
> 

Above solution fixed this
