### ISSUE TITLE
Bad. Sad. NewParser invalid syntax handling

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24300]
**Description:**
note $subject. Below codes are not handled properly in new parser.

#### Case 1
```Ballerina
public function main() {
    type sdsa record {
        var x {
            s : asd
        }
    }
}
```

#### Case 2
```Ballerina
const asd  = "asda";
    type sdsa record {
        var x = {
            s : asd
        };
    };
```

#### Output 1
```Logtalk
error: .::crash3.bal:4:15: missing semicolon token
error: .::crash3.bal:4:15: missing object keyword
error: .::crash3.bal:6:1: missing identifier
error: .::crash3.bal:6:1: missing semicolon token
error: .::crash3.bal:7:1: missing identifier
error: .::crash3.bal:7:1: missing semicolon token
error: .::crash3.bal:8:1: missing semicolon token
ballerina: Oh no, something really went wrong. Bad. Sad.
...
```

##### Crash Log 1

```Logtalk
java.lang.RuntimeException: Node not supported: LocalTypeDefinitionStatementNode
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:3275)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:120)
	at io.ballerinalang.compiler.syntax.tree.LocalTypeDefinitionStatementNode.apply(LocalTypeDefinitionStatementNode.java:62)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3581)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1281)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1162)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1120)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:472)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:430)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:141)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:114)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

#### Output 2
```Logtalk
error: jVM generation is not supported for type other
```

**Steps to reproduce:**
Run above codes in new parser.

**Affected Versions:**
jBallerina 2.0.0-SNAPSHOT
Language specification 2020R1

**OS, DB, other environment details and versions:**
macOS Catalina

**Suggested Labels (optional):**
Component/Parser,Type/Bug

**Comment by KRVPerera** [comment]
### Code
```Ballerina
const asd  = "asda";
    type sdsa record {
        var x = {
            s : asd
        };
    };
```
### Output
```Logtalk
error: jVM generation is not supported for type other
```

**Comment by SupunS** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/24301

**Comment by SupunS** [comment]
Fixed in slp5
