### ISSUE TITLE
IndexOutOfBOund in positionRangeCheck

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#24304]
**Description:**
Source code :-

```
public function main() {
    string s = string ```;
}
```
error :- 
```
java.lang.IndexOutOfBoundsException: Index: '66', Size: '55'
	at io.ballerinalang.compiler.text.LineMap.positionRangeCheck(LineMap.java:59)
	at io.ballerinalang.compiler.text.LineMap.linePositionFrom(LineMap.java:40)
	at io.ballerinalang.compiler.text.TextDocument.linePositionFrom(TextDocument.java:41)
	at io.ballerinalang.compiler.syntax.tree.Node.lineRange(Node.java:109)
	at io.ballerinalang.compiler.syntax.tree.NodeLocation.lineRange(NodeLocation.java:38)
	at org.wso2.ballerinalang.compiler.parser.Parser.getPosition(Parser.java:278)
	at org.wso2.ballerinalang.compiler.parser.Parser.reportSyntaxDiagnostics(Parser.java:265)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:128)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:114)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)

```

**Comment by sameerajayasoma** [comment]
There was a bug in calculating the text ranges of invalid nodes generated by the parser. I will send a PR soon
