### ISSUE TITLE
[Observability] NPE when compiling Raw Templates

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#24306]
**Description:**
$subject. Note NPE is only thrown when building as a module. If only a sinle bal file is run warning is printed
```
warning: niveathika/jdbc_test:0.1.0::main.bal:1:1: Error while generating json AST for main.bal. Error occurred while generating JSON
```

Sample: https://github.com/niveathika/ballerina-distribution/blob/master/examples/jdbc-parameterized-query/jdbc_parameterized_query.bal

```log
[2020-06-18 15:24:31,678] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.generateCanonicalJsonString(DefaultObservabilitySymbolCollector.java:212)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.writeCollectedSymbols(DefaultObservabilitySymbolCollector.java:107)
	at org.ballerinalang.packerina.task.CopyObservabilitySymbolsTask.execute(CopyObservabilitySymbolsTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by niveathika** [comment]
It may be because tooling support for raw templates is not added yet, https://github.com/ballerina-platform/ballerina-lang/issues/23785

**Comment by a5anka** [comment]
Is this fixed?

**Comment by niveathika** [comment]
This should have been fixed in https://github.com/ballerina-platform/ballerina-lang/pull/24298 but need to validate in master

**Comment by niveathika** [comment]
Verified the fix at the master.
