### ISSUE TITLE
Goto definitions of the concurrency related keywords not working

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#24312]
**Description:**
$subject happens to the ballerina keywords such as 
- `worker`
- `future`
- `thread`
- `fork`

Error log

```sh
[Error - 4:27:16 PM] Operation 'text/definition' failed! {uri: '/Users/buddhi/Documents/MyWork/Ballerina/bbe/concurrency/src/worker-interaction/worker_interaction.bal', line: 8, col: 8, error: 'Couldn't find a valid identifier token at cursor!'}
java.lang.IllegalStateException: Couldn't find a valid identifier token at cursor!
	at org.ballerinalang.langserver.util.references.ReferencesUtil.findCursorTokenAndCompileModules(ReferencesUtil.java:175)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:70)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$6(BallerinaTextDocumentService.java:309)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
**Steps to reproduce:**

Try this BBE

```ballerina
import ballerina/io;

// The in-scope variables can be accessed by the workers inside the `fork` block.
public function main() {
    // These variables can be accessed by the forked workers.
    int i = 100;
    string s = "WSO2";
    map<string> m = {"name": "Bert", "city": "New York", "postcode": "10001"};

    string name = <string>m["name"];
    string city = <string>m["city"];
    string postcode = <string>m["postcode"];

    io:println("[value type variables] before fork: " +
                   "value of integer variable is [", i, "] ",
                   "value of string variable is [", s, "]");

    io:println("[reference type variables] before fork: value " +
      "of name is [", name , "] value of city is [", city, "] value of " +
      "postcode is [", postcode, "]");

    // Declares the `fork` block.
    fork {
        worker W1 {
            // Changes the value of the integer variable `i` within the worker `W1`.
            i = 23;
            // Changes the value of the `map` variable `m` within the worker `W1`.
            m["name"] = "Moose";

            fork {
                worker W3 {
                    // Changes the value of the `map` variable `m` within 
                    // the worker `W3`.
                    string street = "Wall Street";
                    m["street"] = street;

                    // Changes the value of the integer variable `i` within
                    // the worker `W3`.
                    i = i + 100;
                }
            }

            // Waits for the worker `W3` to finish.
            wait W3;
        }

        worker W2 {
            // Changes the value of the `string` variable `s` within the worker `W2`.
            s = "Ballerina";
            // Changes the value of the `map` variable `m` within the worker `W2`.
            m["city"] = "Manhattan";
        }
    }

    // Waits for both workers `W1` and `W2` to finish.
    _ = wait {W1, W2};

    // Prints the values after the `fork` block to check if the values of the
    // variables have changed.

    // The value-type variables have changed since the original variables are passed in.
    io:println("[value type variables] after fork: " +
               "value of integer variable is [", i, "] ",
               "value of string variable is [", s, "]");

    // The internal content of the reference-type variables have got updated 
    // since they are passed in as a reference to the workers.
    name = <string>m["name"];
    city = <string>m["city"];
    // Gets the value of the new field added to the `map` variable `m` inside the worker `W3`.
    string street = <string>m["street"];
    io:println("[reference type variables] after fork: " +
               "value of name is [", name,
               "] value of city is [", city, "] value of street is [", street,
               "] value of postcode is [", postcode, "]");
}

```

**Comment by nadeeshaan** [comment]
For the keywords, it is not possible to provide the go-to definition support. This is the expected behaviour and the exception here is gracefully handled. This particular exception is logged only when we enable debug logs and trace logs for development purposes. Hence closing this issue.
