### ISSUE TITLE
Bad Sad Error Thrown When Building Connector Code

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#24327]
**Description:**
I got the following bad sad error when I built the Ballerina Slack connector from the code located in the this [Github repository branch](https://github.com/miyurud/module-slack/tree/june18).

```
[2020-06-18 19:46:54,695] SEVERE {b7a.log.crash} - Index: '0', Size: '0' 
java.lang.IndexOutOfBoundsException: Index: '0', Size: '0'
	at io.ballerinalang.compiler.internal.syntax.NodeListUtils.rangeCheck(NodeListUtils.java:38)
	at io.ballerinalang.compiler.syntax.tree.SeparatedNodeList.get(SeparatedNodeList.java:45)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1882)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.IndexedExpressionNode.apply(IndexedExpressionNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3697)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2572)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.PositionalArgumentNode.apply(PositionalArgumentNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3697)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.lambda$createBLangInvocation$6(BLangNodeTransformer.java:4093)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangInvocation(BLangNodeTransformer.java:4093)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1787)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.MethodCallExpressionNode.apply(MethodCallExpressionNode.java:66)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3697)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2392)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2363)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3581)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1281)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1162)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1120)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:472)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:430)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:141)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:114)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:443)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
Clone this repository [branch](https://github.com/miyurud/module-slack/tree/june18) and build using ballerina-swan-lake-preview1-build2

**Affected Versions:**
ballerina-swan-lake-preview1-build2

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 1.8

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by manuranga** [comment]
1) There is a known error in parser(#24294), so you need to warp ternary operator with parentheses as a workaround.

2) Types are not allowed as expressions under new ballerina spec, define them as type aliases.

```diff
diff --git a/src/slack/utils.bal b/src/slack/utils.bal
index 9516d6f..14e9860 100644
--- a/src/slack/utils.bal
+++ b/src/slack/utils.bal
@@ -19,6 +19,8 @@ import ballerina/http;
 import ballerina/mime;
 import ballerina/stringutils;

+type FileInfoArray FileInfo[];
+
 function getChannelId(http:Client slackClient, string channelName) returns @tainted string|Error {
     http:Response|error response = slackClient->get(LIST_CONVERSATIONS_PATH);
     if (response is error) {
@@ -409,7 +411,7 @@ function listFiles(http:Client slackClient, string? channelId, int? count, strin
     }
     json[] fileJson = <json[]> files;
     convertJsonArrayToCamelCase(fileJson);
-    var fileRec = fileJson.cloneWithType(FileInfo[]);
+    var fileRec = fileJson.cloneWithType(FileInfoArray);
     if (fileRec is error) {
         return Error("Response cannot be converted to FileInfo array", fileRec);
     } else {
@@ -424,16 +426,13 @@ function uploadFile(string filePath, http:Client slackClient, string? channelId,
         url = url + CHANNELS_PARAM + channelId;
     }
     if (title is string) {
-        url = (stringutils:contains(url, QUESTION_MARK)) ? url + TITLE_AS_SECOND_PARAM + title :
-                url + TITLE_AS_FIRST_PARAM + title;
+        url = (stringutils:contains(url, QUESTION_MARK)) ? (url + TITLE_AS_SECOND_PARAM + title) : (url + TITLE_AS_FIRST_PARAM + title);
     }
     if (initialComment is string) {
-        url = (stringutils:contains(url, QUESTION_MARK)) ? url + INITIAL_COMMENT_AS_SECOND_PARAM + initialComment :
-                url + INITIAL_COMMENT_AS_FIRST_PARAM + initialComment;
+        url = (stringutils:contains(url, QUESTION_MARK)) ? (url + INITIAL_COMMENT_AS_SECOND_PARAM + initialComment) : (url + INITIAL_COMMENT_AS_FIRST_PARAM + initialComment);
     }
     if (threadTs is string) {
-        url = (stringutils:contains(url, QUESTION_MARK)) ? url + THREAD_TS_AS_SECOND_PARAM + threadTs :
-                url + THREAD_TS_AS_FIRST_PARAM + threadTs;
+        url = (stringutils:contains(url, QUESTION_MARK)) ? (url + THREAD_TS_AS_SECOND_PARAM + threadTs) : (url + THREAD_TS_AS_FIRST_PARAM + threadTs);
     }
     http:Request request = new;
     mime:Entity filePart = new;

```

**Comment by manuranga** [comment]
we need to fix `var fileRec = fileJson.cloneWithType(FileInfo[]);` to give a better error message than bad-sad.

**Comment by miyurud** [comment]
I had already warpped ternary operator's true case with parentheses in the code which I got bad sad error. But after defining the type `FileInfoArray` and using that as a parameter for `cloneWithType()` eliminated the bad sad error.

**Comment by SupunS** [comment]
@miyurud Do you still get this error?
Is there a minimal working sample I can use to reproduce this?

**Comment by miyurud** [comment]
> @miyurud Do you still get this error?
> Is there a minimal working sample I can use to reproduce this?

@SupunS You can clone [june18 branch of miyurud/module-slack](https://github.com/miyurud/module-slack/tree/june18) and move the code on that branch to this [commit](https://github.com/miyurud/module-slack/commit/591572a21e72d7de281dbb28e3e75974196c29e2) using the command `git branch -f june18-debug 591572a21e72d7de281dbb28e3e75974196c29e2`. Then try to build it using the following command.

`ballerina build -a -c --skip-tests=true`

I checked it with Ballerina Swan Lake Preview 2 pack and still the issue exists. However, as I have commented on 18/6/2020, I was able to solve the bad sad error defining the type `FileInfoArray` and using that as a parameter for `cloneWithType()`. Those fixes were done in this [commit](https://github.com/miyurud/module-slack/commit/5c73ef87a0ea8d1f27d0adeeea5a92bb70f372fc).

**Comment by miyurud** [comment]
@SupunS Based on the discussion we had today I created a minimal working sample to reproduce this issue as follows,

```
function listFiles() {
    var fileRec = fileJson.cloneWithType(FileInfo[]);
}

type FileInfo record {
};
```

You can keep the above code segment in a file called `utils.bal` and then try building it using the following command,

`ballerina build utils.bal`

You should get the same bad sad error.

But if you change the code as follows, then you will not get bad sad error, but some other compilation error will be thrown (which is as expected).

```
type FileInfoArray FileInfo[];

function listFiles() {
    var fileRec = fileJson.cloneWithType(FileInfoArray);
}

type FileInfo record {
};
```
