### ISSUE TITLE
Warnings are getting printed for some Query BBEs

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#24341]
**Description:**
Below warning is getting printed for query expression related below BBEs.

- Query Expression
- Stream From Query Expression
- String From Query Expression
- XML From Query Expression
- Join Iterables

```ballerina
warning: .::query_expression_to_stream.bal:1:1: Error while generating json AST for query_expression_to_stream.bal. Error occurred while generating JSON
```

Observed, ```ballerina: Oh no, something really went wrong. Bad. Sad.``` for below query expression BBE.

- Table From Query Expression

**Comment by mohanvive** [comment]
@grainier Please followup.

**Comment by sameerajayasoma** [comment]
Do you have the full stack trace? Please attach the ballerina-internal.log file as well.

**Comment by mohanvive** [comment]
There is no much stack trace for cases which generated the warning (or no any logs in ballerina-internal.log). Just the below one.

```
Compiling source
	query_expression.bal
warning: .::query_expression.bal:1:1: Error while generating json AST for query_expression.bal. Error occurred while generating JSON
Running executables

name=Alex degree=Bachelor of Medicine expectedGradYear=2025
name=John degree=Bachelor of Medicine expectedGradYear=2027
```

For `ballerina: Oh no, something really went wrong. Bad. Sad.` error case, it generated below logs in ballerina-internal.log. 

```
[2020-06-19 02:02:08,154] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to io.ballerinalang.compiler.syntax.tree.Token 
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to io.ballerinalang.compiler.syntax.tree.Token
	at io.ballerinalang.compiler.syntax.tree.RecordFieldNode.fieldName(RecordFieldNode.java:49)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1063)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.RecordFieldNode.apply(RecordFieldNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1011)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.RecordTypeDescriptorNode.apply(RecordTypeDescriptorNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:4021)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:610)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:472)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:430)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:141)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:114)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 ```

**Comment by grainier** [comment]
Seems, https://github.com/ballerina-platform/ballerina-lang/pull/24298 got rid of the `Error while generating json AST for query_expression_to_stream.bal. Error occurred while generating JSON` warning. However, now it gives a NPE at;

```
[2020-06-18 19:40:47,759] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.generateCanonicalJsonString(DefaultObservabilitySymbolCollector.java:212)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.writeCollectedSymbols(DefaultObservabilitySymbolCollector.java:107)
	at org.ballerinalang.packerina.task.CopyObservabilitySymbolsTask.execute(CopyObservabilitySymbolsTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
``` 
@nadundesilva any idea?
