### ISSUE TITLE
NPE when parsing function call with keywords

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#24357]
**Description:**
$subject However using escape character sorted out the issue.
```ballerina
public remote function find(map<json>? filter = (), map<json>? sort = (), int limit = -1)  {
       return find(self.collection, (), (), limit);
}

```

```
[2020-06-19 12:29:09,338] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgList(BallerinaParser.java:4933)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgsList(BallerinaParser.java:4893)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncCall(BallerinaParser.java:4852)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4416)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4338)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3990)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3984)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3978)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseActionOrExpression(BallerinaParser.java:3920)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseReturnStatementRhs(BallerinaParser.java:5848)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseReturnStatement(BallerinaParser.java:5780)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3670)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3524)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3519)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseBlockNode(BallerinaParser.java:5582)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseIfElseBlock(BallerinaParser.java:5533)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3660)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3524)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3519)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseBlockNode(BallerinaParser.java:5582)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseIfElseBlock(BallerinaParser.java:5533)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3660)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2499)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2440)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2425)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.createFuncDefOrMethodDecl(BallerinaParser.java:1475)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1462)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1432)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1417)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethod(BallerinaParser.java:5518)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethodOrField(BallerinaParser.java:5345)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethodOrField(BallerinaParser.java:5324)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMember(BallerinaParser.java:5291)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMember(BallerinaParser.java:5272)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMembers(BallerinaParser.java:5217)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectTypeDescriptor(BallerinaParser.java:5080)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2282)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2199)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2188)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2183)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseModuleTypeDefinition(BallerinaParser.java:2982)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1297)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:779)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:708)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:608)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:85)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:50)
	at org.wso2.ballerinalang.compiler.packaging.converters.FileSystemSourceInput.getTree(FileSystemSourceInput.java:77)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:129)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:116)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:443)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
[2020-06-19 12:36:09,152] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgList(BallerinaParser.java:4933)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgsList(BallerinaParser.java:4893)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncCall(BallerinaParser.java:4852)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4416)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4338)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3990)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3984)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:3978)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseActionOrExpression(BallerinaParser.java:3920)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseReturnStatementRhs(BallerinaParser.java:5848)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseReturnStatement(BallerinaParser.java:5780)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3670)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3524)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3519)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseBlockNode(BallerinaParser.java:5582)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseIfElseBlock(BallerinaParser.java:5533)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3660)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3524)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatements(BallerinaParser.java:3519)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseBlockNode(BallerinaParser.java:5582)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseIfElseBlock(BallerinaParser.java:5533)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3660)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3625)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3545)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2499)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2440)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2425)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.createFuncDefOrMethodDecl(BallerinaParser.java:1475)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1462)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1432)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1417)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethod(BallerinaParser.java:5518)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethodOrField(BallerinaParser.java:5345)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMethodOrField(BallerinaParser.java:5324)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMember(BallerinaParser.java:5291)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMember(BallerinaParser.java:5272)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectMembers(BallerinaParser.java:5217)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseObjectTypeDescriptor(BallerinaParser.java:5080)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2282)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2199)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2188)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2183)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseModuleTypeDefinition(BallerinaParser.java:2982)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1297)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:779)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:708)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:608)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:85)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:50)
	at org.wso2.ballerinalang.compiler.packaging.converters.FileSystemSourceInput.getTree(FileSystemSourceInput.java:77)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:129)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:116)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:443)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 

```

**Comment by m36dot** [comment]
This is now fixed in master, the above code parses and the output is as follows,

```
m36@slick:~/WSO2/test/jballerina-tools-2.0.0-Preview3-SNAPSHOT/bin$ ./ballerina run ./test.bal 
Compiling source
	test.bal
error: .::test.bal:1:15: invalid token 'remote'
error: .::test.bal:1:79: missing identifier
error: .::test.bal:1:85: invalid token 'limit'
error: .::test.bal:2:45: missing identifier
error: .::test.bal:2:50: invalid token 'limit'
error: .::test.bal:2:20: undefined symbol 'self'
error: .::test.bal:2:41: incompatible types: expected 'int', found '()'
error: .::test.bal:2:15: too many arguments in call to 'find()'
```
