### ISSUE TITLE
Issues with VSCode when there's an enum declaration

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24380]
**Description:**
$title, could be because tooling support for enums is not available yet (https://github.com/ballerina-platform/ballerina-lang/issues/24378).

**Steps to reproduce:**
Suggestions stop working for
```ballerina
import ballerina/io;

enum FooBar {
    Foo,
    Bar
}

public function main() {
    io: // no suggestions
}
```

The output log has
```log
[Error - 2:40:51 AM] Operation 'text/codeAction' failed! {uri: '<PATH_TO_FILE>', line: 9, col: 8- line: 9, col: 8, error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at org.ballerinalang.langserver.common.utils.CommonUtil.toZeroBasedPosition(CommonUtil.java:181)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.topLevelNodeInLine(CodeActionUtil.java:114)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$11(BallerinaTextDocumentService.java:429)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

@pubudu91 pointed out that it works to a certain extent when the enum comes after the function.

**Affected Versions:**
Swan Lake Preview 1 RC1

**Comment by nadeeshaan** [comment]
This is because the position being null. We have to fix this from the node transformer.

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing the issue.
