### ISSUE TITLE
Build Native image for single Bal file

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#24662]
Need to test simple Hello world sample

```
import ballerina/io;
public function main() {
    io:println("Hello, World!");
}


```

**Comment by warunalakshitha** [comment]
Following error observed during native image generation for simple ballerina bal file.
```
Call path from entry point to ballerina.lang_stream/0_4_0.$value$_anonType_1.next(Strand):
at ballerina.lang_stream.0_4_0.$value$_anonType_1.next(stream.bal)
at ballerina.lang_stream.0_4_0.$value$_anonType_1.call(stream.bal)
at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:78)
at org.ballerinalang.jvm.values.MapValueImpl.stringValue(MapValueImpl.java:416)
at org.ballerinalang.jvm.values.MapValueImpl.toString(MapValueImpl.java:376)
at org.ballerinalang.jvm.values.ErrorValue.getPrintableError(ErrorValue.java:227)
at org.ballerinalang.jvm.values.ErrorValue.getPrintableStackTrace(ErrorValue.java:179)
at org.ballerinalang.jvm.values.ErrorValue.printStackTrace(ErrorValue.java:149)
at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:761)
at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Original exception that caused the problem: org.graalvm.compiler.core.common.PermanentBailoutException: Non-reducible loop requires too much duplication
```

**Comment by warunalakshitha** [comment]
We we were able to solve it with using the   -H:MaxDuplicationFactor=20.0.
