### ISSUE TITLE
GraalVm image generation failed for concat string which was return from extern function

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#24733]
**Description:**
```ballerina
import ballerina/io;

public function main() {
    string s = "test1" + io:sprintf("%s", "sss");
}
```

**Error**
```
Call path from entry point to org.ballerinalang.jvm.values.BmpStringValue.concat(BString): 
	at org.ballerinalang.jvm.values.BmpStringValue.concat(BmpStringValue.java:53)
	at main.main(main.bal:6)
	at ___init.$lambda$main$(.)
	at ___init$$Lambda$3/448672246.apply(Unknown Source)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:267)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:235)
	at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:222)
	at ___init.main(.)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: Field mainFrame._9 has declared type org.ballerinalang.jvm.values.api.BString which is incompatible with types in state: MTypeMObject<3817:[0x0000000100000002:!S:Object, 0x0000000E0000000F:!S:String, 0x0000001100000012:!S:byte[],
```

Here io:sprintf is a extern function. If you use normal ballerina function return string, no errors.

ex. 

```
public function main() {
    string s = "test1" + foo();
}

function foo() returns string {
    return "sss";
}

```

**Comment by warunalakshitha** [comment]
I am closing this since graalvm work is on hold. Will reopen once we start on graalvm support.
