### ISSUE TITLE
When we create a anonymous functions inside loop, graal vm image generation failed with an error

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#24741]
**Description:**
Sample code
```
public function main() {
    string[] warningHeaders = ["h1", "h2"];
    foreach var warningHeader in warningHeaders {
        function ()  anonFunction = function ()  {

        };  
    } 
}
```

Error

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing main.main(org.ballerinalang.jvm.scheduling.Strand) 
Parsing context:
	parsing ___init.$lambda$main$(.)
	parsing ___init$$Lambda$3/651974446.apply(Unknown Source)
	parsing org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	parsing org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:267)
	parsing org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:235)
	parsing org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:222)
	parsing ___init.main(.)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:437)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: Detected previously intrinsified element
	at parsing main.main(main.bal:8)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2590)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:94)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3428)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
	... 10 more
Caused by: com.oracle.svm.core.util.VMError$HostedError: Detected previously intrinsified element
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
	at com.oracle.svm.hosted.snippets.IntrinsificationPluginRegistry.add(IntrinsificationPluginRegistry.java:88)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.processInvokeWithMethodHandle(IntrinsifyMethodHandlesInvocationPlugin.java:511)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.handleInvoke(IntrinsifyMethodHandlesInvocationPlugin.java:220)
	at org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2216)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1904)
	at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1793)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1718)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1714)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5342)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	... 21 more
Error: Image build request failed with exit status 1


```

**Comment by warunalakshitha** [comment]
I am closing this since graalvm work is on hold. Will reopen once we start on graalvm support.
