### ISSUE TITLE
NPE from Parser for incomplete function invocation

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#24820]
**Description:**
Consider following ballerina code snippet;

```ballerina
# Description
#
# + a - a Parameter Description 
# + b - b Parameter Description 
# + c - c Parameter Description 
# + d - d Parameter Description
function foo(int a, float b, boolean c, string d) {
    
}

public function main() {
    foo(1,,);
}
```

Compiling above code throws following error;
```
[2020-07-17 20:41:51,535] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgList(BallerinaParser.java:4981)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseArgsList(BallerinaParser.java:4945)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncCall(BallerinaParser.java:4904)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4468)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4390)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:4384)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypedBPOrExprRhs(BallerinaParser.java:13101)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypeOrExpr(BallerinaParser.java:13090)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3766)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3666)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3586)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2529)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2470)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2455)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.createFuncDefOrMethodDecl(BallerinaParser.java:1498)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1485)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1455)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1440)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1318)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:801)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:730)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:630)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:93)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:50)
	at org.wso2.ballerinalang.compiler.packaging.converters.FileSystemSourceInput.getTree(FileSystemSourceInput.java:77)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:129)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:116)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)

```
**Affected Versions:**
2.0.0-P1

**Comment by rasika** [comment]
This is not reproducible in latest master. Hence closing.
