### ISSUE TITLE
Exception thrown when using --code-coverage flag with ballerina test when there are no source files

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#24856]
**Description:**
An exception is thrown when using --code-coverage flag with ballerina test when there are no source files in the module. 
We need to handle the exception and display a meaningful message.

**Steps to reproduce:**
1. Create a new project & add a module
2. Delete the source file "main.bal" from the module
3. Execute tests with the "--code-coverage" flag
4. Following exception is thrown

```
$ ballerina test --code-coverage --all

Compiling source
	dilhashanazeer/diltest:0.1.0

Creating balos
	target/balo/diltest-2020r1-any-0.1.0.balo

Running Tests with Coverage
	dilhashanazeer/diltest:0.1.0
I'm the before suite function!
I'm the before function!
I'm in test function!
I'm the after function!
I'm the after suite function!

	[pass] testFunction

	1 passing
	0 failing
	0 skipped

Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/dilhashanazeer/Documents/CodeCovTest/target/coverage/dilhashanazeer-diltest-0.1.0-testable.jar/dilhashanazeer/diltest
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:74)
	at org.ballerinalang.test.runtime.entity.CoverageReport.generateReport(CoverageReport.java:76)
	at org.ballerinalang.test.runtime.CoverageMain.main(CoverageMain.java:46)
Caused by: java.nio.file.NoSuchFileException: /Users/dilhashanazeer/Documents/CodeCovTest/target/coverage/dilhashanazeer-diltest-0.1.0-testable.jar/dilhashanazeer/diltest
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.copyClassFilesToBinPath(CodeCoverageUtils.java:94)
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:71)
	... 2 more
error: error while generating test report

```
**Affected Versions:**
jBallerina 1.2.6

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Closing this issue since its being tracked here : #25399
