### ISSUE TITLE
Unable to build WSO2 product-microgateway distribution in Windows

### ISSUE THREAD

**Issue by ShalkiWenushika** [ballerina-platform/ballerina-lang#24861]
**Description:**
When building the product-microgateway-3.1.0 in Windows with an Administrator-Local account which is having a username ending with "$" symbol, a build failure occurs.

Following is the microgw.log:

```
[2020-07-21 11:43:04,732] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Internal error occurred while executing command. 
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:819)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at org.ballerinalang.packerina.cmd.CommandUtil.initProject(CommandUtil.java:118)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.initTarget(BuildCmd.java:337)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.init(BuildCmd.java:279)
	at org.wso2.apimgt.gateway.cli.cmd.BuildCmd.execute(BuildCmd.java:140)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)
```

 

**Steps to reproduce:**
1. Create an  Administrator-Local account with an account name ending with the "$" symbol (ex: INTRW00023$).
2. Build the product-microgateway-3.1.0 distribution with the command `mvn clean install -Dcheckstyle.skip`

**Affected Versions:**
jBallerina 1.1.4

**OS, DB, other environment details and versions:**
OS: Windows 10 Pro

**Related Issues (optional):**

**Suggested Labels (optional):**
Type/Bug, dev-tools

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Hi @ShalkiWenushika

Probably this issue has to be reported to the microgateway repo. It is difficult to see how this is related to ballerina. Please reopen if you can specifically find a issue with Ballerina related to this.

**Comment by praminda** [comment]
Hi @hevayo 
This happens when we try to init a new ballerina project within the microgateway. B7a throws this error around [CommandUtil.java#L118] when resolving `ORG_NAME`

[CommandUtil.java#L118]:https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.6/cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/CommandUtil.java#L118

**Comment by IrushiL** [comment]
`$` is not allowed inside org names in Swan Lake.
Need to check if the `$` is replaced with an allowed character similar to how package names are derived in Swan Lake.
