### ISSUE TITLE
TypeParamAnalyzer throws null pointer exception

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#24864]
**Description:**
This was found when doing java 11 migration.

Steps to reproduce on current master:
Change `internal.bal` of `lang.table` module as follows:
```ballerina
# Represent the iterator type returned when `iterator` method is invoked.
type TableIterator object {

    private table<Type> t;
    private KeyType[] keys;
    private int size;

    public function init(table<Type> t) {
       self.t = t;
        self.size = length(t);
       if (t is table<Type> key<KeyType>) {
           self.keys = keys(t);
       } else {
           self.keys = [];
       }
    }

    # Return the next member in table iterator, nil if end of iterator is reached.
    # + return - iterator result
    public function next() returns record {|
        Type value;
    |}? {
        next(self);
    }
};

function next(TableIterator this) returns record { Type value; |}? = external;

```

Console out:
```
> Task :ballerina-lang:table:createBalo
Compiling source
Exception in thread "main" java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.lambda$updateTypeParamAndBoundType$0(TypeParamAnalyzer.java:395)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.updateTypeParamAndBoundType(TypeParamAnalyzer.java:395)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:283)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:271)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:300)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:271)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParamInObject(TypeParamAnalyzer.java:531)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:365)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.findTypeParam(TypeParamAnalyzer.java:271)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeParamAnalyzer.checkForTypeParamsInArg(TypeParamAnalyzer.java:129)
```

This sees to be caused because the type symbol of `KeyType` is null.
[`lang.table/table.bal`]
```ballerina
@typeParam
type KeyType anydata;
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
This is fixed in the latest preview version SLP5. Hence closing the issue.
