### ISSUE TITLE
Code Analyzer fails for incomplete listener declaration

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24893]
**Description:**
Consider the following source snippet,

_Source1_

```
import ballerina/http;
import ballerina/lang.'object as lang;

public listener http:Listener lst = new h
```

_Source2_
```
import ballerina/http;
import ballerina/lang.'object as lang;

public listener http:Listener ll = new http:L
```

This fails with the following exception,

```
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2261)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:62)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:2862)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1500)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:334)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$analyzeTopLevelNodes$1(CodeAnalyzer.java:323)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:323)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:318)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:307)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeAnalyze(CompilerDriver.java:330)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:261)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more
```

**Comment by pubudu91** [comment]
Tried these in the latest master and it's not crashing for me though.

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/25210. 

NPE occurs at https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-alpha2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3073 due to `type.tsymbol` becoming null.

**Comment by nadeeshaan** [comment]
> Related issue: #25210.
> 
> NPE occurs at https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-alpha2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3073 due to `type.tsymbol` becoming null.

@MaryamZi yes, we have to handle these cases with null checks at least. Since the parser is resilient and recovers the incomplete sources, at the semantic layer however we have to handle this.

**Comment by mohanvive** [comment]
Above issue is fixed in the master now. Hence, closing the issue.
