### ISSUE TITLE
Exception when untainting XML entity

### ISSUE THREAD

**Issue by georgecookeIW** [ballerina-platform/ballerina-lang#24946]
**Description:**

It appears that untainting a XML entity throws a **null pointer exception**.

Code:
```
//broken
//string entityType = check self.mapEntityType(<@untainted>x/<Interaction>/<OrganisationDetails>/<Status>.OptionValue);
//works
string entityType = check self.mapEntityType(x/<Interaction>/<OrganisationDetails>/<Status>.OptionValue);
```

Error log:
```
[2020-07-24 12:05:08,766] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.isMutableVariable(TaintAnalyzer.java:678)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.isMutableVariable(TaintAnalyzer.java:676)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitAssignment(TaintAnalyzer.java:614)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.updateArgTaintedStatus(TaintAnalyzer.java:2649)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.updateArgTaintedStatus(TaintAnalyzer.java:2611)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeInvocation(TaintAnalyzer.java:2383)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:1056)
   at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:1398)
   at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:58)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1612)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:499)
   at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:584)
   at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1612)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:408)
   at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeNode(TaintAnalyzer.java:1612)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:2042)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyzeReturnTaintedStatus(TaintAnalyzer.java:1963)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitInvokable(TaintAnalyzer.java:1861)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:396)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visitAttachedInvokable(TaintAnalyzer.java:1885)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:378)
   at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.resolveBlockedInvokable(TaintAnalyzer.java:2713)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyze(TaintAnalyzer.java:290)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.visit(TaintAnalyzer.java:271)
   at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
   at org.wso2.ballerinalang.compiler.semantics.analyzer.TaintAnalyzer.analyze(TaintAnalyzer.java:253)
   at org.wso2.ballerinalang.compiler.CompilerDriver.taintAnalyze(CompilerDriver.java:286)
   at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:242)
   at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:214)
   at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
   at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
   at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
   at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
   at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
   at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:61)
   at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
   at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:293)
   at java.util.Optional.ifPresent(Optional.java:159)
   at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
1. Take any XML with multiple entities (possibly the bug exists with only a single entity, have not tried that)
2. To break: add `<@untainted>` to the start of the XML entity string
3. To fix: remove `<@untainted>` from the start of the XML entity string

**Affected Versions:**
Ballerina 1.2.6

**OS, DB, other environment details and versions:**
Appears to be both MacOS and Windows; have not tried any Linux distro.

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
**Dhananjaya** - replied to me in Slack with an idea about what the bug might be.

**Comment by hasithaa** [comment]
We are removing the current taint analysis implementation with #30981, Hence closing this issue.
