### ISSUE TITLE
Node transformer throws runtime exception

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24942]
**Description:**
Consider the following code snippet,

```
function testFunction() {
    int|string|boolean sss = true;
    boolean tre =sss is <cursor>
}

# This is a test function
#
# + return - Return Value Description
function functionWithReturn() returns Record1 {
    return {};
}

type Record1 record {
    int testIntField = 12;
    Record2 testOptional?;
};

type Record2 record {
    float testField = 3.4;
};

```

The above snippet throws the following exception,

```
Caused by: java.lang.RuntimeException: Node not supported: LocalTypeDefinitionStatementNode
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:3363)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:120)
	at io.ballerinalang.compiler.syntax.tree.LocalTypeDefinitionStatementNode.apply(LocalTypeDefinitionStatementNode.java:62)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3682)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1325)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1206)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1163)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:505)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:443)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more
```

**Affected Versions:**
Swan Lake Preview3-Snapshot at least

**Comment by SupunS** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/24300

**Comment by MaryamZi** [comment]
Fixed in slp5 according to https://github.com/ballerina-platform/ballerina-lang/issues/24300#issuecomment-721538359.

Also verified on the current master.
