### ISSUE TITLE
[Spec Deviation] Need support for Quoted Identifier with Unicode code points

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#24951]
**Description:**
As per the specs, we need to support quoted identifiers with unicode code points in the following format
```ballerina
string '\u{0234} = "abc";
```
specs : https://ballerina.io/ballerina-spec/spec.html#StringNumericEscape

**Steps to reproduce:**
The above line gives a bad sad error
```
[2020-07-27 12:33:49,155] SEVERE {b7a.log.crash} - Unable to parse unicode value: {023 
java.lang.IllegalArgumentException: Unable to parse unicode value: {023
	at org.apache.commons.lang3.text.translate.UnicodeUnescaper.translate(UnicodeUnescaper.java:59)
	at org.apache.commons.lang3.text.translate.AggregateTranslator.translate(AggregateTranslator.java:55)
	at org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(CharSequenceTranslator.java:90)
	at org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(CharSequenceTranslator.java:64)
	at org.apache.commons.lang3.StringEscapeUtils.unescapeJava(StringEscapeUtils.java:526)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.escapeQuotedIdentifier(BLangNodeTransformer.java:4629)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createIdentifier(BLangNodeTransformer.java:3933)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createIdentifier(BLangNodeTransformer.java:3923)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVariable(BLangNodeTransformer.java:3593)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getBLangVariableNode(BLangNodeTransformer.java:3645)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2433)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2409)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3669)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1325)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1206)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1163)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:505)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:443)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.NumberFormatException: For input string: "{023"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at org.apache.commons.lang3.text.translate.UnicodeUnescaper.translate(UnicodeUnescaper.java:56)
	... 38 more
 ```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#18720 

**Suggested Labels (optional):**
Area/jBallerina, Type/SpecDeviation

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
Fixed with the PR
