### ISSUE TITLE
Bad Sad Error Thrown When using Anonymous Functions

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#24956]
**Description:**
I got a bad sad error when I built [module-ballerinax-microsoft.sheets](https://github.com/miyurud/module-ballerinax-microsoft.sheets.git). This happens because of I started to use an anonymous function as an argument for a `log:printDebug()`statement. The log is shown below

``
[2020-07-27 13:12:47,207] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:155)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:387)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$5(BIROptimizer.java:117)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:117)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:346)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:94)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:94)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:74)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:249)
	at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:354)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:301)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:68)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
``

**Steps to reproduce:**
Clone the repo [module-ballerinax-microsoft.sheets](https://github.com/miyurud/module-ballerinax-microsoft.sheets.git) and build it using the command `ballerina build -a -c --skip-tests=true`. Should use the code from this [commit](https://github.com/miyurud/module-ballerinax-microsoft.sheets/commit/e0eb57f5c00890e81f65495812b54bd28eb32730) which caused this bad sad error.

**Affected Versions:**
Ballerina Swan Lake Preview 2

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 1.8

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by Kishanthan** [comment]
A simplified example to reproduce this

```ballerina
public function main() {
    string|int s = "World";
    if (s is string) {
        function() returns string a = () => "Hello " + s;
    }
}
```

**Comment by Kishanthan** [comment]
The issue here is with the arrow function where the type test narrowing is being included in its scope, which fails to properly identify the closure var symbol.
