### ISSUE TITLE
Incremental SyntaxTree build fails for text addition throws errors

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#24966]
**Description:**
Consider applying text addition as below;

**main.bal Before:**
```ballerina
123456
```

**main.bal After:**
```ballerina
1234567
```

Java API Call for the text is as below:
```java
function void getUpdatedTree(TextDocumentContentChangeEvent change) {
 Position start = change.getRange().getStart(); // returns 0, 6 in LSP4J
 Position end = change.getRange().getEnd(); // returns 0, 6 in LSP4J
 String text = change.getText(); // returns "7" in LSP4J

 int startOffset = textDocument.textPositionFrom(LinePosition.from(start.getLine(), start.getCharacter()));
 int endOffset = textDocument.textPositionFrom(LinePosition.from(end.getLine(), end.getCharacter()));

 TextEdit[] edits = new TextEdit[1]; // simplified array creation logic for the readability
 edits[0] = TextEdit.from(TextRange.from(startOffset, endOffset - startOffset), text);
 return SyntaxTree.from(oldTree, TextDocumentChange.from(edits));
}
```

```ballerina
[Error - 12:57:44 AM] Operation 'text/didChange' failed! {uri: '/Users/rasika/Documents/WSO2/Ballerina/samples/parser-samples/hello-world/main.bal', error: 'java.lang.IllegalArgumentException'}
java.lang.IllegalArgumentException
	at io.ballerinalang.compiler.syntax.tree.NonTerminalNode.findToken(NonTerminalNode.java:88)
	at io.ballerinalang.compiler.internal.parser.incremental.HybridNodeStorage.markAffectedRange(HybridNodeStorage.java:168)
	at io.ballerinalang.compiler.internal.parser.incremental.HybridNodeStorage.markAffectedRanges(HybridNodeStorage.java:160)
	at io.ballerinalang.compiler.internal.parser.incremental.HybridNodeStorage.createInitialNode(HybridNodeStorage.java:149)
	at io.ballerinalang.compiler.internal.parser.incremental.HybridNodeStorage.<init>(HybridNodeStorage.java:55)
	at io.ballerinalang.compiler.internal.parser.ParserFactory.getParser(ParserFactory.java:77)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:62)
	at org.ballerinalang.langserver.compiler.workspace.WorkspaceDocumentManagerImpl.lambda$updateFile$1(WorkspaceDocumentManagerImpl.java:115)
```
**Steps to reproduce:**

**Affected Versions:**
2.0.0-P3-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sameerajayasoma** [comment]
It looks like this issue has been fixed with the following PR. Can you please check?
https://github.com/ballerina-platform/ballerina-lang/pull/24965

**Comment by rasika** [comment]
Resolved with PR  https://github.com/ballerina-platform/ballerina-lang/pull/24965
