### ISSUE TITLE
Bad Sad error is thrown when using the new parser

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#24999]
**Description:**
When built the websub module, got a following Bad Sad error. This is happened by the deprecated [method-level comment](https://github.com/ballerina-platform/module-ballerina-websub/blob/master/websub-ballerina/src/websub/commons.bal#L574)

`SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.FunctionCallExpressionNode cannot be cast to io.ballerinalang.compiler.syntax.tree.SimpleNameReferenceNode
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.FunctionCallExpressionNode cannot be cast to io.ballerinalang.compiler.syntax.tree.SimpleNameReferenceNode
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformDocumentationIdentifier(BLangNodeTransformer.java:4433)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.lambda$addReferencesAndReturnDocumentationText$7(BLangNodeTransformer.java:4382)
  at java.util.Optional.ifPresent(Optional.java:159)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.addReferencesAndReturnDocumentationText(BLangNodeTransformer.java:4379)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createMarkdownDocumentationAttachment(BLangNodeTransformer.java:4267)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1224)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
  at io.ballerinalang.compiler.syntax.tree.ObjectMethodDefinitionNode.apply(ObjectMethodDefinitionNode.java:75)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:852)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
  at io.ballerinalang.compiler.syntax.tree.ObjectTypeDescriptorNode.apply(ObjectTypeDescriptorNode.java:62)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:4131)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:642)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
  at io.ballerinalang.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:505)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
  at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
  at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:443)
  at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
  at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
  at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
  at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
  at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
  at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
  at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
  at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
  at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:64)
  at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
  at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
  at java.util.Optional.ifPresent(Optional.java:159)
  at org.ballerinalang.tool.Main.main(Main.java:57)`

**Steps to reproduce:**
Clone the repo [module-ballerina-websub](https://github.com/ballerina-platform/module-ballerina-websub/tree/buddhi-dev) and build it using this command `./gradlew clean build`.

**Affected Versions:**
Ballerina Swan Lake Preview 3

**Comment by SupunS** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/25000

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/25001
