### ISSUE TITLE
CSVReader returning null instead of empty string for a field that has no value

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25014]
**Description:**
In the current implementation, we set null values when the field value is empty in the CSV records. This leads to NPE when reading the CSV file from `ReadableCSVChannel`.

We should consider it an empty string instead of null.

```
[2020-07-29 14:57:27,053] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
        at org.ballerinalang.jvm.values.ArrayValueImpl.stringValue(ArrayValueImpl.java:579)
        at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:69)
        at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
        at ballerina.io.0_5_0.print.println(print.bal:30)
        at daneshk.csv_sample.0_1_0.main.process(main.bal:14)
        at daneshk.csv_sample.0_1_0.main.main(main.bal:31)
        at daneshk.csv_sample.0_1_0.___init.$lambda$main$(csv_sample)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
        at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
Run the sample https://ballerina.io/swan-lake/learn/by-example/csv-io.html with following CSV record,

```
1,James,10000
2,Nathan,150000
3,Ronald,120000
4,Roy,6000
5,,1100000
```

**Affected Versions:**
1.2.6, slp2

**Comment by daneshk** [comment]
We also need to fix the error in `code snippet` in API Doc[1]
1.  https://ballerina.io/swan-lake/learn/api-docs/ballerina/io/objects/ReadableCSVChannel.html#getNext
