### ISSUE TITLE
Bad Sad Error Thrown When Building a Single BAL file

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#25020]
**Description:**
I got a bad sad error when I try to compile the attached `opportunities.bal` file [opportunities.zip](https://github.com/ballerina-platform/ballerina-lang/files/4994680/opportunities.zip). The log is shown below.

```
[2020-07-29 11:45:43,294] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:501)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:490)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:144)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:118)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:310)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:306)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:669)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:631)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:614)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:402)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:252)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateBasicBlocks(JvmMethodGen.java:2095)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:1808)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:1658)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:550)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Steps to reproduce:**
Unzip [opportunities.zip](https://github.com/ballerina-platform/ballerina-lang/files/4994680/opportunities.zip) and build the BAL file using the following command.

`ballerina build opportunities.bal`

**Affected Versions:**
Ballerina Swan Lake Preview 2

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 1.8

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by Kishanthan** [comment]
I tried compiling this file with SLP2 and I do not see any compilation issues.

```
➜  $ ballerina version                
Ballerina Swan Lake Preview 2
Language specification v2020-06-18
Update Tool 0.8.8
➜  $ ballerina build opportunities.bal
Compiling source
	opportunities.bal

Generating executables
	opportunities.jar
```

**Comment by Kishanthan** [comment]
Tested with slp3 as well. Not reproducible.

```
➜ ballerina version                
Ballerina Swan Lake Preview 3
Language specification v2020-06-18
Update Tool 0.8.8
➜ ballerina build opportunities.bal
Compiling source
	opportunities.bal

Generating executables
	opportunities.jar
```

**Comment by Kishanthan** [comment]
@miyurud, do you have any additional input on this?

**Comment by miyurud** [comment]
Unfortunately I am unable to reproduce this issue now. Based on the offline discussion we had I will close this issue now.
