### ISSUE TITLE
Langlib tests fails in JDK 11

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#25041]
**Description:**
When executing the langlib tests in the `jdk_11_migration` branch using the `./gradlew :ballerina-langlib:test:test -x :composer-library:npmBuild -x :composer-library:npmInstall` command, the following error occurs.

```
> Task :ballerina-langlib:test:test
ballerina-langlib-test-suite > lang-lib-test > org.ballerinalang.langlib.test.TypeParamTest > testBoundTypeAsCET STANDARD_OUT
        type_param_bound_type_as_cet.bal
ballerina-langlib-test-suite > lang-lib-test > org.ballerinalang.langlib.test.TypeParamTest > testBoundTypeAsCET FAILED
    org.ballerinalang.core.util.exceptions.BLangRuntimeException: Error while invoking function 'testBoundRestParamAsCET'
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:417)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1166)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:172)
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:1209)
        at org.ballerinalang.langlib.test.TypeParamTest.testBoundTypeAsCET(TypeParamTest.java:93)
        Caused by:
        java.lang.RuntimeException: Error while invoking function 'testBoundRestParamAsCET'
            Caused by:
            java.lang.reflect.InvocationTargetException
                Caused by:
                java.lang.IncompatibleClassChangeError: Method 'void ballerina.lang_array.1_1_0.$value$ArrayIterator.setOnInitialization(org.ballerinalang.jvm.values.api.BString, java.lang.Object)' must be Methodref constant
ballerina-langlib-test-suite > lang-lib-test > org.ballerinalang.langlib.test.TypeParamTest > testLangLibImports STANDARD_OUT
        imported_type_param.bal
<============-> 99% EXECUTING [3m 38s]
```

**Steps to reproduce:**
Execute any of the following commands in the `jdk_11_migration` branch. 
- `./gradlew :ballerina-langlib:test:test -x :composer-library:npmBuild -x :composer-library:npmInstall`
- `./gradlew :ballerina-langlib:test:test -x :composer-library:npmBuild -x :composer-library:npmInstall --tests TypeParamTest`

**Affected Versions:**
Executed on the `jdk_11_migration` branch

**OS, DB, other environment details and versions:**
Executed on Ubuntu 20.04

**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Language, Area/jBallerina

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Fixed with #25389
