### ISSUE TITLE
Parser ServiceDeclarationTest test failure

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25061]
**Description:**
$subject happens by giving the following error.

```sh
ballerina-parser-test-suite > ballerina-parser-test > io.ballerinalang.compiler.parser.test.syntax.declarations.ServiceDeclarationTest > testResourceWithoutName FAILED
    java.lang.AssertionError: error at node [start]. expected [START_KEYWORD] but found [INVALID_TOKEN_MINUTIAE_NODE]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNodeKind(ParserTestUtils.java:221)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:163)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertMinutiaeNode(ParserTestUtils.java:288)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertMinutiaeNodes(ParserTestUtils.java:263)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.validateMinutiae(ParserTestUtils.java:243)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertTerminalNode(ParserTestUtils.java:239)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:167)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNonTerminalNode(ParserTestUtils.java:319)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.assertNode(ParserTestUtils.java:169)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.test(ParserTestUtils.java:109)
        at io.ballerinalang.compiler.parser.test.ParserTestUtils.test(ParserTestUtils.java:88)
        at io.ballerinalang.compiler.parser.test.syntax.declarations.AbstractDeclarationTest.testFile(AbstractDeclarationTest.java:36)
        at io.ballerinalang.compiler.parser.test.syntax.declarations.ServiceDeclarationTest.testResourceWithoutName(ServiceDeclarationTest.java:100)
```

**Full Log**
- https://github.com/ballerina-platform/ballerina-lang/runs/926795652
- https://github.com/ballerina-platform/ballerina-lang/pull/25030/checks?check_run_id=927319646

**Comment by BuddhiWathsala** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/25070
