### ISSUE TITLE
Bad, sad error with missing `function` keyword and invalid qualifiers

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25261]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
remote foo() {
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:1:1: missing at token
error: .::qwe.bal:1:1: missing function keyword
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
...
```

ballerina-internal.log
```log
[2020-08-13 16:20:20,981] SEVERE {b7a.log.crash} - Can't find resource for bundle java.util.PropertyResourceBundle, key error.qualifier.not.allowed 
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key error.qualifier.not.allowed
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at io.ballerinalang.compiler.internal.diagnostics.DiagnosticMessageHelper.getDiagnosticMessage(DiagnosticMessageHelper.java:38)
	at io.ballerinalang.compiler.internal.diagnostics.SyntaxDiagnostic.message(SyntaxDiagnostic.java:68)
	at org.wso2.ballerinalang.compiler.parser.Parser.reportSyntaxDiagnostics(Parser.java:280)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:131)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
Current master.

**Comment by m36dot** [comment]
this is fixed in the master. Now this compiles with following output
```
Compiling source
	test.bal
error: .::test.bal:1:1: missing at token
error: .::test.bal:1:1: missing function keyword
error: .::test.bal:1:8: invalid token 'remote'
error: .::test.bal:1:1: undefined annotation '$missingNode$0'
```

**Comment by SupunS** [comment]
Closing since this is fixed. Please do reopen if the issue still exist.
