### ISSUE TITLE
CLASS_NOT_FOUND error with Swan Lake Preview 3

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#25309]
**Description:**
We are currently in the process of migrating standard library modules to separate reopos. But in some modules (Math, Task, Runtime-API, reflect etc.) after restructuring, the module fails to build with SLP3 with a `CLASS_NOT_FOUND` error. But modules get successfully built with SLP2. 

```sh
error: ballerina/math:1.0.0::natives.bal:36:1: {ballerina/java}CLASS_NOT_FOUND 'org.ballerinalang.jvm.values.api.BError'
error: ballerina/math:1.0.0::natives.bal:53:1: {ballerina/java}CLASS_NOT_FOUND 'org.ballerinalang.jvm.values.api.BError'
error: ballerina/math:1.0.0::natives.bal:64:1: {ballerina/java}CLASS_NOT_FOUND 'org.ballerinalang.jvm.values.api.BError'
error: ballerina/math:1.0.0::natives.bal:77:1: {ballerina/java}CLASS_NOT_FOUND 'org.ballerinalang.jvm.values.api.BError'
error: ballerina/math:1.0.0::natives.bal:89:1: {ballerina/java}CLASS_NOT_FOUND 'org.ballerinalang.jvm.values.api.BError'
```

**Steps to reproduce:**
1. Follow this [doc](https://docs.google.com/document/d/1Um4jUaSazZq0uX3_HJk58VDgY6KHo06VuaLebjmKDU0/edit#heading=h.yim7izpu106l) and re-structure the code.
2. Build with SLP3.

**Affected Versions:**
SLP3

**Comment by BuddhiWathsala** [comment]
Also, received a similar bad sad issue when we build other migrating modules with SLP3 and SLP3 SNAPSHOT versions.

```sh
[2020-08-18 13:49:06,566] SEVERE {b7a.log.crash} - org/ballerinalang/jvm/values/ObjectValue 
java.lang.NoClassDefFoundError: org/ballerinalang/jvm/values/ObjectValue
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.getExecutables(JMethodResolver.java:639)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolveByMethodName(JMethodResolver.java:118)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolve(JMethodResolver.java:87)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateAndGetJMethod(InteropValidator.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJMethodWrapper(InteropMethodGen.java:755)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJInteropFunctionWrapper(InteropMethodGen.java:743)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.createExternalFunctionWrapper(ExternalMethodGen.java:254)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.getBirFunctionWrapper(JvmPackageGen.java:786)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.linkModuleFunctions(JvmPackageGen.java:771)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateClassNameLinking(JvmPackageGen.java:610)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:463)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:140)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:114)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:310)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:306)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:64)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.ClassNotFoundException: org.ballerinalang.jvm.values.ObjectValue
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

```

**Comment by chamil321** [comment]
Seems a runtime value issue. Dropping another stack trace here to dig more

```
[2020-08-18 22:35:58,955] SEVERE {b7a.log.crash} - org/ballerinalang/jvm/values/api/BString 
java.lang.NoClassDefFoundError: org/ballerinalang/jvm/values/api/BString
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.getExecutables(JMethodResolver.java:639)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolveByMethodName(JMethodResolver.java:118)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolve(JMethodResolver.java:87)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateAndGetJMethod(InteropValidator.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJMethodWrapper(InteropMethodGen.java:755)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJInteropFunctionWrapper(InteropMethodGen.java:743)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.createExternalFunctionWrapper(ExternalMethodGen.java:254)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.getBirFunctionWrapper(JvmPackageGen.java:786)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.linkModuleFunctions(JvmPackageGen.java:771)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateClassNameLinking(JvmPackageGen.java:610)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:463)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:140)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:114)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:310)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:306)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:64)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.ClassNotFoundException: org.ballerinalang.jvm.values.api.BString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by Kishanthan** [comment]
@MadhukaHarith92, can you share the restructured repo that we can build with slp3 to reproduce this?

**Comment by BuddhiWathsala** [comment]
@Kishanthan please use this migrated module to reproduce the issue. https://github.com/ballerina-platform/module-ballerina-reflect/tree/migration

Command to execute:
```sh
./gradlew clean build
```

**Comment by Kishanthan** [comment]
@hevayo, @suganyasuven,  looks like the rt jar is not getting added to the list of nativeDependencies when this module is being compiled. Maybe there is an issue with the logic here - https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview3/cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/JarResolverImpl.java#L133 ?

The root cause is the rt jar not available with interop validation classpath which is populated by invoking the JarResolver API to get the list of module dependencies.

**Comment by suganyasuven** [comment]
> @hevayo, @suganyasuven, looks like the rt jar is not getting added to the list of nativeDependencies when this module is being compiled. Maybe there is an issue with the logic here - https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview3/cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/JarResolverImpl.java#L133 ?
> 
> The root cause is the rt jar not available with interop validation classpath which is populated by invoking the JarResolver API to get the list of module dependencies.

Yes, there is an issue with that logic. I have sent the PR(https://github.com/ballerina-platform/ballerina-lang/pull/25325).
