### ISSUE TITLE
Bad Sad Error when trying to generate code coverage in SLP3 libs

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#25342]
**Description:**
$subject
```
[2020-08-20 00:23:21,382] SEVERE {b7a.log.crash} - in is null 
java.lang.NullPointerException: in is null
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipReportResources(CodeCoverageUtils.java:139)
	at org.ballerinalang.packerina.task.RunTestsTask.generateHtmlReport(RunTestsTask.java:302)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:204)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.TestCommand.execute(TestCommand.java:411)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
Swan lake preview 3

**Comment by azinneera** [comment]
Are you trying this with the SLP3 release pack or is it a locally built pack? This is expected if you build a pack locally by skipping the npm builds.

**Comment by niveathika** [comment]
@azinneera My bad, it seems I have run in a snapshot dependency
