### ISSUE TITLE
DocumentationAnalyzer fails for incomplete table type descriptor

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#25512]
**Description:**
Consider the following code snippet,

`type TestType table<>`

This source snippet fails with the following exception thrown from DocumentationAnalyzer

```
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DocumentationAnalyzer.visit(DocumentationAnalyzer.java:218)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:110)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DocumentationAnalyzer.analyzeNode(DocumentationAnalyzer.java:113)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DocumentationAnalyzer.lambda$analyze$0(DocumentationAnalyzer.java:106)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DocumentationAnalyzer.analyze(DocumentationAnalyzer.java:106)
	at org.wso2.ballerinalang.compiler.CompilerDriver.documentationAnalyze(CompilerDriver.java:326)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:271)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more
```

**Affected Versions:**
SLP3 at least

**Comment by mohanvive** [comment]
Verified above issue (with and without TOOLING_COMPILATION flag) and it is fixed in the latest master. Hence, closing the issue.
