### ISSUE TITLE
Compiling old syntax gives Bad Sad error in SLP3

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-lang#25549]
**Description:**
Compiling the following piece of code gives Ballerina Bad Sad error while compilation errors are expected. 

```
resource function getProjectSecret(grpc:Caller caller, GetProjectSecretRequest req) {
    if (req.appId == "") {
        sendGrpcError(caller, "Required appId field missing");
        return;
    }
    table<record {}>|error selectRet =
        progDb->select("SELECT project_secret FROM program WHERE app_id=?", ProjectSecret, req.appId);
    if (selectRet is error) {
        sendGrpcError(caller, "Select data from program table failed: " + <string>selectRet.detail()?.message);
        return;
    } else {            // if (selectRet is table<record {}>)
        table<ProjectSecret> rows = <table<ProjectSecret>>selectRet;
        ProjectSecret secret = rows.getNext();
        GetProjectSecretResponse res = {projectSecret: secret.projSecret};
        sendGrpcResponse(caller, res);
    }
}
```

**Error Message**

```
[2020-08-18 21:08:12,859] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.statements.BLangWorkerSend cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangExpression 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.statements.BLangWorkerSend cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangExpression
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3733)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2415)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2384)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3644)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1286)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1199)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1170)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1033)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.ServiceBodyNode.apply(ServiceBodyNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:4089)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createService(BLangNodeTransformer.java:983)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:919)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.ServiceDeclarationNode.apply(ServiceDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:512)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:442)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by mohanvive** [comment]
I am not pretty sure about our take handling these kinds of issues with legacy code. It is nearly impossible to provide context-sensitive error messages. Even though code matches the grammar, the chances for failures at a later stage are possible. Also, handling each of these cases individually is a tedious process. 

I think, we have to make a policy decision on this.

**Comment by KavinduZoysa** [comment]
This gives compile time errors as expected in `Ballerina 2201.4.0 `
