### ISSUE TITLE
Cannot break/continue using a lambda invocation 

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#25558]
**Description:**
I'm trying to break a loop calling a lambda function which contains a break statement.
This fails with an NPE causing below stacktrace.

`   java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:116)
        at org.wso2.ballerinalang.compiler.bir.model.BIRTerminator$GOTO.accept(BIRTerminator.java:70)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:98)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:387)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:71)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:71)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:280)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$5(BIRBinaryWriter.java:185)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:185)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:89)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:250)
        at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:354)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:301)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:516)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:503)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:729)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:624)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:612)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:605)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:690)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:110)
        at org.ballerinalang.langlib.test.DummyTest.setup(DummyTest.java:42)`

It seems while generating the BIR, we are maintaining the loop ending basic block and once we visit the break we add a terminator instruction to the block to goto the ending block.
Since functions are visited separately, the loop ending basic block becomes null.

**Steps to reproduce:**
Try running the below function.

```ballerina
function testmatch() {
       int[5] intArray = [0, 1, 2, 3, 4];

          foreach var counter in intArray {
              var endLoop = function () {
                       io:println("Ending loop");
                       break;
               };
              match counter {
                 0 => {
                      io:println("value is: 0");
                      endLoop();
                  }
                  1 => {
                      io:println("value is: 1");
                  }
                  2 => {
                      io:println("value is: 2");
                  }
                  3 => {
                      io:println("value is: 3");
                  }
                  4 => {
                      io:println("value is: 4");
                  }
                  5 => {
                      io:println("value is: 5");
                  }
              }
          }
  }
```

**Affected Versions:**
v1.2.8

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Restricted usage of break/continue in such cases with https://github.com/ballerina-platform/ballerina-lang/pull/28054
