### ISSUE TITLE
Bad, sad error when using a string literal as array size

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25579]
**Description:**
Prints a `invalid token 'x'` error and then crashes.

**Steps to reproduce:**
```ballerina
public function main() {
    int["foo"] x = [1, 2];
}
```

ballerina-internal.log
```log
[2020-09-03 11:34:29,282] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.IndexedExpressionNode cannot be cast to io.ballerinalang.compiler.syntax.tree.TypedBindingPatternNode 
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.IndexedExpressionNode cannot be cast to io.ballerinalang.compiler.syntax.tree.TypedBindingPatternNode
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.typedBindingPattern(VariableDeclarationNode.java:45)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2384)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3644)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1286)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1199)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1170)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:512)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:417)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:442)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp3, current master

**Comment by lochana-chathura** [comment]
Output with slp6-snapshot.
```
Compiling source
	test.bal
ERROR [test.bal:(2:8,2:9)] invalid array length
error: compilation contains errors
```

**Comment by lochana-chathura** [comment]
A unit-test has been added  with  77e15d778a3d4d8f02a5d9a9b917ddc057776d4a in PR #26313
