### ISSUE TITLE
Unrecognized ballerina/encoding dependecy version 1.0.1 in ballerina/jwt  module in SLP3

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-lang#25656]
**Description:**
>Ballerina services secured using JWT authentication fails to get invoked in SLP-03 due to  unrecognized dependency `ballerina/encoding` version 1.0.1 in `ballerina/jwt` module.

> Produces the below logs during service invocation 
```
[2020-09-07 06:09:29,796] SEVERE {b7a.log.crash} - ballerina/encoding/1_0_1/src/encoding/encoding 
java.lang.NoClassDefFoundError: ballerina/encoding/1_0_1/src/encoding/encoding
        at ballerina.jwt.1_0_1.jwt_validator.getJwtHeader(jwt_validator.bal:141)
        at ballerina.jwt.1_0_1.jwt_validator.decodeJwt(jwt_validator.bal:127)
        at ballerina.jwt.1_0_1.jwt_validator.validateJwt(jwt_validator.bal:80)
        at ballerina.jwt.1_0_1.$value$InboundJwtAuthProvider.authenticate(inbound_jwt_auth_provider.bal:74)
        at ballerina.jwt.1_0_1.$value$InboundJwtAuthProvider.call(inbound_jwt_auth_provider.bal)
        at ballerina.http.1_0_0.$value$BearerAuthHandler.process(auth/bearer_auth_handler.bal:56)
        at ballerina.http.1_0_0.$value$BearerAuthHandler.call(auth/bearer_auth_handler.bal)
        at ballerina.http.1_0_0.auth.authn_filter.checkForAuthHandlers(auth/authn_filter.bal:80)
        at ballerina.http.1_0_0.auth.authn_filter.handleAuthRequest(auth/authn_filter.bal:59)
        at ballerina.http.1_0_0.$value$AuthnFilter.filterRequest(auth/authn_filter.bal:46)
        at ballerina.http.1_0_0.$value$AuthnFilter.call(auth/authn_filter.bal)
        at choreo.linker.0_1_2.$value$LinkerSecured__service_3.getProjectSecret(svc_linker_secured.bal:243)
        at choreo.linker.0_1_2.$value$LinkerSecured__service_3.call(svc_linker_secured.bal)
        at org.ballerinalang.jvm.values.connector.Executor.lambda$submit$0(Executor.java:86)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ballerina.encoding.1_0_1.src.encoding.encoding
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more
```

**Comment by ldclakmal** [comment]
This issue is fixed in Ballerina SLP4. Please reopen the ticket if the issue occurred.
