### ISSUE TITLE
Parser crashes when reocvering with error-binding-pattern

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#25724]
**Description:**
Consider the following code snippet

```bal
public function test() {
    int i = 0;
    {
        i = i + 1;
        error err = error("Custom error thrown explicitly.");
        fail err;
    } on fail error e {
        io:println("Exception thrown...");
    }
}
```

Parser crashes with stackoverflow.

</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```java
Exception in thread "main" java.lang.StackOverflowError
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.getNextRuleInternal(BallerinaParserErrorHandler.java:2712)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.getNextRule(BallerinaParserErrorHandler.java:2434)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:386)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ba</details>llerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:181)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:102)
	at io.ballerinalang.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:106)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13214)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
```

</details>

**Suggested Labels**
Team/CompilerFE, Area/Parser, Type/Bug, Priority/Blocker

**Comment by lochana-chathura** [comment]
Simpler version:
Parser crashes when there's error keyword alone in the error binding pattern. 
```bal
function testErrorBindingPatternRecovery() {
    var error = e;
}
```

**Comment by lochana-chathura** [comment]
Original issue root cause is fixed. But, Still the first example crashes. Created issue #27214 to track the new issue.
