### ISSUE TITLE
MissingResourceException thrown for incomplete source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#25766]
**Description:**
Consider the following source snippet which is incomplete. For this, parser throws exception

`public distinct `

Following exception is thrown,

```
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key error.missing.class.keyword
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at io.ballerinalang.compiler.internal.diagnostics.DiagnosticMessageHelper.getDiagnosticMessage(DiagnosticMessageHelper.java:38)
	at io.ballerinalang.compiler.internal.diagnostics.SyntaxDiagnostic.message(SyntaxDiagnostic.java:68)
	at org.wso2.ballerinalang.compiler.parser.Parser.reportSyntaxDiagnostics(Parser.java:280)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:131)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more
```

**Comment by SupunS** [comment]
Fixed with #25768
