### ISSUE TITLE
NPE when trying to sort an any[]

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#25848]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
    any[] x = [1, 3, 2];
    any[] sortResult = x.sort(array:ASCENDING, (i) => i);
```

**Affected Versions:**
n/a

**OS, DB, other environment details and versions:**
n/a

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/25781
https://github.com/ballerina-platform/ballerina-lang/issues/25682 blocked on this.

**Comment by grainier** [comment]
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:117)
        at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:87)
        at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLogHelper.error(BLangDiagnosticLogHelper.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkArrayLibSortFuncArgs(TypeChecker.java:5428)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationArgs(TypeChecker.java:5376)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParam(TypeChecker.java:5195)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParamAndReturnType(TypeChecker.java:5143)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getLangLibMethod(TypeChecker.java:5136)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInLangLib(TypeChecker.java:2757)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2694)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:361)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:340)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:663)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2759)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2751)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1678)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2759)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2755)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:374)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:346)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2759)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2751)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:269)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:243)
        at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:330)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:259)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:251)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:512)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:499)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:716)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:609)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:690)
        at org.ballerinalang.test.util.BCompileUtil.compileOffline(BCompileUtil.java:123)
        at org.ballerinalang.test.types.tuples.SandboxTest.setup(SandboxTest.java:34)

```
