### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#25861]
**Description:**
I am getting the following error when compiling the attached source
[awslambda-extension-balo.zip](https://github.com/ballerina-platform/ballerina-lang/files/5236292/awslambda-extension-balo.zip) from the latest ballerina-swan-lake-preview4-SNAPSHOT pack.

Compiling source
	ballerinax/awslambda:0.0.0
Exception in thread "main" java.lang.NullPointerException
	at org.ballerinalang.tool.Main.main(Main.java:62)

Following is the stack-trace.
```
org.ballerinalang.compiler.BLangCompilerException
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:170)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadCompiledPackageAndDefine(PackageLoader.java:501)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:436)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:790)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:80)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:301)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:295)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:156)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:236)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:467)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:378)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:68)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:436)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: org.ballerinalang.compiler.BLangCompilerException
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:170)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadCompiledPackageAndDefine(PackageLoader.java:501)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:436)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineImportPackage(BIRPackageSymbolEnter.java:342)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:332)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:236)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:219)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:193)
	... 22 more
```

**Steps to reproduce:**
Compile attached code with jballerina-tools-2.0.0-Preview4-SNAPSHOT built on 17th September.

**Affected Versions:**
jballerina-tools-2.0.0-Preview4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Are you using the snapshots of the dependencies? If so, can you try each of the dependencies with the same jballerina tools pack?

**Comment by anuruddhal** [comment]
Used the pack built from distribution repo.

**Comment by rdhananjaya** [comment]
Building distribution fails for me with the following log
```
> Task :ballerina:testStdlibs
Created new Ballerina project at StdlibTestProject

Next:
    Move into the project directory and use `ballerina add <module-name>` to
    add a new Ballerina module.
Compiling source
        dhananjaya/grpc-bidirectional-streaming:0.1.0
Exception in thread "main" java.lang.NullPointerException
        at org.ballerinalang.tool.Main.main(Main.java:62)
```

**Comment by daneshk** [comment]
@rdhananjaya This is because stdlib modules are not yet migrated to the latest language changes

**Comment by rdhananjaya** [comment]
Ack will remove the Blocker label

**Comment by rdhananjaya** [comment]
Closing as this is no longer the case as stdlibs are migrated
