### ISSUE TITLE
Runtime Crash in Creating XML from Query Expression

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#25948]
Code:

Version: Ballerina slp3

```ballerina
import ballerina/io;
import ballerina/lang.'string as stringlib;

public function main() returns @tainted error? {
    xml payload = xml `<Root>
                            <data>
                                <record>
                                    <field name="Country or Area" key="ABW">Aruba</field>
                                    <field name="Item" key="EN.ATM.CO2E.KT">CO2 emissions (kt)</field>
                                    <field name="Year">1960</field>
                                    <field name="Value">11092.675</field>
                                </record>
                            </data>
                       </Root>`;

    xml ax = from var x in payload/<data>/<*> 
             let var year = <xml> x/<'field>[2]
             let var value = <xml> x/<'field>[3].name
             select xml `<entry>${<string> value}</entry>`;
    io:println("A:", ax);
}
```

The above program crashes in the runtime, with a log similar to the following:

```
    same_frame(@5891)
    same_frame(@5901)
    full_frame(@5909,{Object[#13],Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Long,Null,Long,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Null,Integer,Null,Integer,Null,Null,Integer},{})
    full_frame(@6527,{Object[#13],Object[#97],Object[#4],Object[#4],Object[#4],Object[#702],Object[#702],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Object[#97],Long,Object[#704],Long,Object[#97],Object[#256],Object[#688],Object[#256],Object[#256],Object[#258],Object[#256],Object[#258],Object[#4],Object[#256],Object[#258],Object[#4],Object[#256],Object[#258],Object[#4],Object[#353],Object[#353],Object[#4],Object[#4],Object[#704],Object[#4],Object[#4],Object[#4],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Object[#176],Integer,Object[#176],Integer,Object[#176],Object[#4],Integer},{})

        at ___init.___init_(.:65535)
        at ___init.$moduleInit(.)
        at ___init.$lambda$$moduleInit$(.)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by daneshk** [comment]
@rdhananjaya Can you share your input on this

**Comment by rdhananjaya** [comment]
@mohanvive Please have a look
