### ISSUE TITLE
Error in handling compilation error.

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#25961]
**Description:**
We have a mock listener declared as following:
```ballerina
import ballerina/http;
import ballerina/'lang\.object as lang;

public class ABC {
    *lang:Listener;

    public function __init() {
    }

    public function __attach(service s, string? name = ()) returns error? {
    }

    public function __detach(service s) returns error? {
    }

    public function __start() returns error? {
    }

    public function __gracefulStop() returns error? {
        return ();
    }

    public function __immediateStop() returns error? {
        return ();
    }
}
```
Compiling the above code fails with the following error on ballerina-internal.log
```
{b7a.log.crash} - Illegal character in path at index 4: lang\.object/
    java.lang.IllegalArgumentException: Illegal character in path at index 4: lang\.object/
        at java.net.URI.create(URI.java:852)
        at java.net.URI.resolve(URI.java:1036)
        at org.wso2.ballerinalang.compiler.packaging.converters.URIConverter.combine(URIConverter.java:90)
        at org.wso2.ballerinalang.compiler.packaging.converters.URIConverter.combine(URIConverter.java:47)
        at org.wso2.ballerinalang.compiler.packaging.Patten.callReduceForEach(Patten.java:93)
        at org.wso2.ballerinalang.compiler.packaging.Patten.lambda$convert$1(Patten.java:73)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wso2.ballerinalang.compiler.packaging.RepoHierarchy.resolve(RepoHierarchy.java:61)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageEntity(PackageLoader.java:263)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:418)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:790)
        at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:80)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:301)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:295)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:236)
        at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:436)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
    Caused by: java.net.URISyntaxException: Illegal character in path at index 4: lang\.object/
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3063)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 36 more
```
The error can be fixed by changing the import to `import ballerina/lang.'object as lang;`. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
In Swan Lake-alpha, the error message is a bit different, but it could be improved.

```
error: compilation failed: error: could not connect to remote repository to find versions for: ballerina/lang\.
```

**Comment by rdhananjaya** [comment]
This is fixed now, current error message is ` cannot resolve module 'ballerina/lang\.object as lang'`
