### ISSUE TITLE
Top level lambda function causes to crash the compilation

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#26100]
Following programs fails with Bad sad error. 

```
var f = function () returns [int, int] {
    return [3, 3];
};
```
Error 
```
[2020-09-25 14:46:39,482] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:1146)
	at org.wso2.ballerinalang.compiler.tree.types.BLangTupleTypeNode.accept(BLangTupleTypeNode.java:52)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:452)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:443)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.createInvokableType(SymbolResolver.java:1417)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveAndSetFunctionTypeFromRHSLambda(SymbolEnter.java:2887)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:353)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:236)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 ```

**Comment by mohanvive** [comment]
The above issue in the master with the latest changes done to master. Hence, closing the issue.
