### ISSUE TITLE
Ballerina run/build commands are failing when source files contain quoted identifiers

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#26109]
**Description:**

Balo creation phase is failing with the following error, when the source files contain local/global variables with quoted identifiers.

![Screenshot from 2020-09-25 17-38-13](https://user-images.githubusercontent.com/29032600/94265944-02a7a400-ff57-11ea-8e1f-67ddd227e78e.png)

**Steps to reproduce:**

Try `ballerina run` / `ballerina build` for the following code snippet, which contains a local variable with a quoted identifier.
![Screenshot from 2020-09-25 17-47-50](https://user-images.githubusercontent.com/29032600/94266105-44d0e580-ff57-11ea-8954-db073983cab0.png)

**Affected Versions:**
Ballerina Swan Lake Preview 4 SNAPSHOT [RC]

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
Looks like this is specific to creating balos task in this case.

Actual failure is due to a file copy issue

```
java.nio.file.NoSuchFileException:  /:/@/[/`/{/
	at com.sun.nio.zipfs.ZipFileSystem.checkParents(ZipFileSystem.java:863)
	at com.sun.nio.zipfs.ZipFileSystem.newOutputStream(ZipFileSystem.java:528)
	at com.sun.nio.zipfs.ZipPath.newOutputStream(ZipPath.java:792)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newOutputStream(ZipFileSystemProvider.java:285)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126)
	at java.nio.file.Files.copy(Files.java:1277)
	at org.ballerinalang.packerina.writer.BaloFileWriter$Copy.visitFile(BaloFileWriter.java:441)
	at org.ballerinalang.packerina.writer.BaloFileWriter$Copy.visitFile(BaloFileWriter.java:407)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.ballerinalang.packerina.writer.BaloFileWriter.addResources(BaloFileWriter.java:335)
	at org.ballerinalang.packerina.writer.BaloFileWriter.populateBaloArchive(BaloFileWriter.java:170)
	at org.ballerinalang.packerina.writer.BaloFileWriter.write(BaloFileWriter.java:116)
	at org.ballerinalang.packerina.task.CreateBaloTask.execute(CreateBaloTask.java:42)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:436)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)

```
If we have a type like this, we are trying to create a json file within the balo archive with the same name

```
public client class '\ \/\:\@\[\\{\~\u{2324}_ƮέŞŢ_Connector {
    .....
}
```

This is what failing

**Comment by Kishanthan** [comment]
![Uploading Screen Shot 2020-09-26 at 12.46.40 AM.png…]()

**Comment by Kishanthan** [comment]
<img width="841" alt="debug-view" src="https://user-images.githubusercontent.com/690559/94307238-0b699b80-ff92-11ea-970e-fdbb689520bc.png">

**Comment by HindujaB** [comment]
It seems the error happens when we have a client class like the following, 
```ballerina
public client class '\ \/\:\@\[\`\{\~_Connector {
    boolean action2Invoked = false;

    public function init(string param1, string param2, int param3) {

    }

    public remote function '\ \/\:\@\[\`\{\~_Action() returns string {
        string 'sample_String_2 = "this ";
        return 'sample_String_2 ;
    }
}

```
A json file is created with the connector function information at data mapper plugin. And, we use the name of the client class as the file name. 
(In this case, ```\ \/\:\@\[\`\{\~_Connector``` )
As some of the special characters are not supported in the file system (`/`), the file is not created properly. 
This causes the failure while copying the file at `createBalo` task 

![cropped](https://user-images.githubusercontent.com/28644893/95163071-b8c78500-07c4-11eb-9145-200a69f36fc0.png)

**Comment by miyurud** [comment]
This issue was fixed via the [PR](https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/25).
