### ISSUE TITLE
Bad, sad error when using `fromJsonWithType()`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26117]
**Description:**
$title. `cloneWithType()` works though.

**Steps to reproduce:**
```ballerina
type Person record {|
    boolean employed;
    string first_name;
    string last_name?;
    Address? address;
|};

type Address record {
    string city;
    string country;
};

type PersonArray Person[];

public function main() {
    Person[] personArr = <Person[]> arr.fromJsonWithType(PersonArray);
}

json[] arr = [
    {
        "first_name": "Radha",
        "address": {
            "apartment_no": 123,
            "street": "Perera Mawatha",
            "city": "Colombo",
            "country": "Sri Lanka"
        },
        "employed": false
    },
    {
        "first_name": "Nilu",
        "last_name": "Peiris",
        "address": null,
        "employed": true
    }
];
```

ballerina-internal.log
```log
[2020-09-27 11:37:24,092] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.jvm.commons.TypeValuePair.equals(TypeValuePair.java:42)
	at java.util.ArrayList.indexOf(ArrayList.java:317)
	at java.util.ArrayList.contains(ArrayList.java:300)
	at org.ballerinalang.langlib.value.FromJsonWithType.convert(FromJsonWithType.java:96)
	at org.ballerinalang.langlib.value.FromJsonWithType.putToMap(FromJsonWithType.java:242)
	at org.ballerinalang.langlib.value.FromJsonWithType.convertMap(FromJsonWithType.java:186)
	at org.ballerinalang.langlib.value.FromJsonWithType.convert(FromJsonWithType.java:124)
	at org.ballerinalang.langlib.value.FromJsonWithType.convertArray(FromJsonWithType.java:205)
	at org.ballerinalang.langlib.value.FromJsonWithType.convert(FromJsonWithType.java:128)
	at org.ballerinalang.langlib.value.FromJsonWithType.fromJsonWithType(FromJsonWithType.java:81)
	at ballerina.lang_value.1_0_0.value.fromJsonWithType(value.bal:175)
	at qwe.main(qwe.bal:16)
	at $_init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:745)
```

**Affected Versions:**
slp4

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/28338.
