### ISSUE TITLE
IndexOutOfBoundsException for invalid syntax

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26127]
**Description:**

#### Code
```Ballerina
public function main() {
    xml x = xml``;
}
```

#### Swan Lake
```LogTalk
[2020-09-28 12:27:48,830] SEVERE {b7a.log.crash} - Index: '0', Size: '0' 
java.lang.IndexOutOfBoundsException: Index: '0', Size: '0'
        at io.ballerinalang.compiler.internal.syntax.NodeListUtils.rangeCheck(NodeListUtils.java:38)
        at io.ballerinalang.compiler.syntax.tree.NodeList.get(NodeList.java:61)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1949)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
        at io.ballerinalang.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:58)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3700)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2395)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2366)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
        at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3584)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1284)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
        at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1165)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1123)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
        at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:472)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:405)
        at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:430)
        at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:143)
        at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:116)
        at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
Run above code in Swan Lake channel.

**Affected Versions:**
All the Swan Lake versions are affected

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Parser

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/25955

**Comment by KRVPerera** [comment]
Closing as a duplicate of #25955
