### ISSUE TITLE
Compiler crashes when a module-level anonymous function has an array type as the return type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26138]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
var fn = function (int[] y) returns int[] {
    return y;
};
```

ballerina-internal.log
```log
[2020-09-28 16:38:37,919] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:909)
	at org.wso2.ballerinalang.compiler.tree.types.BLangArrayType.accept(BLangArrayType.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:452)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:443)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.createInvokableType(SymbolResolver.java:1417)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveAndSetFunctionTypeFromRHSLambda(SymbolEnter.java:2887)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:353)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:236)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp4

**Comment by dulvinw** [comment]
@MaryamZi Cannot reproduce with SLP8.

**Comment by MaryamZi** [comment]
Yes, this seems to have been fixed. Verified on sl-alpha-SNAPSHOT too.
