### ISSUE TITLE
Bad-Sad for invalid method def

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26158]
**Description:**
```ballerina
class F {
    function add(string k) => { self.g.add(k); }
}
```

internal-log
```
 
[2020-09-30 11:39:58,041] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2461)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:361)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:340)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2649)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:361)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:340)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:381)
	at org.wso2.ballerinalang.compiler.tree.BLangExprFunctionBody.accept(BLangExprFunctionBody.java:36)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:346)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2791)
```

**Steps to reproduce:**

**Affected Versions:**
SLP4
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Fixed in current master/alph2.
Output:
```
Compiling source
	test.bal
ERROR [test.bal:(2:31,2:39)] invalid operation: type 'record {| F self; |}' does not support field access for non-required field 'g'
ERROR [test.bal:(2:37,2:37)] missing close brace token
ERROR [test.bal:(5:1,5:1)] invalid token '}'
error: compilation contains errors
````
