### ISSUE TITLE
Exception when fail statement called within on-fail clause

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26202]
**Description:**
Please refer the below code segment

```ballerina
function testQuery() returns error?{
    int i = 0;
    while (i < 2) {
        do {
            io:println("This is inside do");
            i = i + 1;
            fail getError();
        } on fail error e {
            io:println("This is inner on-fail");
            fail getError();
        }
    } on fail error e {
        io:println("This is outer on-fail");
    }

    io:println("While is completed.");
}

function getError() returns error {
    error err = error("Custom Error");
    return err;
}
```

Above result in the error which is given below,

```
    java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:160)
        at org.wso2.ballerinalang.compiler.bir.model.BIRTerminator$GOTO.accept(BIRTerminator.java:70)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:142)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:402)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:87)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:281)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$5(BIRBinaryWriter.java:184)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:184)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:84)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:258)
        at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:365)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:308)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:250)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:142)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:470)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:658)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:563)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:553)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:547)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:624)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:106)
        at org.ballerinalang.test.query.TempQueryExpressionTest.setup(TempQueryExpressionTest.java:38)
```

**Comment by grainier** [comment]
Closed with https://github.com/ballerina-platform/ballerina-lang/pull/26353
