### ISSUE TITLE
Defining a distinct object type crashed the compiler

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26212]
The following example crashes on slp4:
```ballerina
public function main() {
    
}

type PersonType distinct object {
    string name;

    function getName() returns string;
};
```
The crash log:
```
[2020-10-05 21:15:21,207] SEVERE {b7a.log.crash} - org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType cannot be cast to org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.populateDistinctTypeIdsFromIncludedTypeReferences(SymbolEnter.java:419)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineDistinctClassAndObjectDefinitions(SymbolEnter.java:405)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:375)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:243)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:236)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by rdhananjaya** [comment]
This change should fix this issue https://github.com/ballerina-platform/ballerina-lang/issues/26212

**Comment by pubudu91** [comment]
This is now fixed in the `service-typing` branch.

**Comment by rdhananjaya** [comment]
Fixed in `master` hence closing.
