### ISSUE TITLE
Observing metrics using Prometheus is broken on SLP4

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#26217]
**Description:**
$title. And gives the following error when the service is starting;

```
ballerina: failed to start Prometheus HTTP listener 0.0.0.0:9797 java.lang.NoClassDefFoundError cannot be cast to java.lang.RuntimeException
```

**Complete trace:**

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ballerinalang.jvm.services.JVMEmbeddedExecutor.lambda$runInitOnSchedule$2(JVMEmbeddedExecutor.java:215)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: ballerina/time/1_0_0/$_init
        at ballerina.prometheus.0_0_0.$_init.$moduleInit(prometheus)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: ballerina.time.1_0_0.$_init
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 10 more
```

**Steps to reproduce:**
- start a service with metrics enabled.

**Affected Versions:**
- slp4

**Related Notes (optional):**
- probably std-lib migration.

**Comment by nadundesilva** [comment]
We have decided to move all the Ballerina extensions to `ballerina-observability` repository and make sure all the extensions are part of a ballerina module. Importing the module will automatically package the extension (similar to how docker extension work). In the future, we will introduce a Compiler Extension to handle adding the import automatically.

As a first step to make sure Prometheus extension is working properly, we will be moving the extension to the `ballerina-observability` repository.
- [ ] Remove Prometheus extension from the ballerina-lang build
- [ ] Add Prometheus extension to `ballerina-observability` repository and publish to GitHub packages in the same repository
- [ ] Add compiler level modification to automatically inject the import statement (to make sure the current behavior is not broken)
- [ ] Package Prometheus extension in the `ballerina-distribution` repository build.
- [ ] Completely remove Prometheus extension from the ballerina-lang repository

**Comment by nadundesilva** [comment]
We have taken a decision to remove the extension from SLP5 release as this is not working properly. We will add it back as soon as a proper extension model had been introduced and the extensions are working again properly.
