### ISSUE TITLE
Building and running the JAR doesn't seem to work after the Java 11 migration

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26235]
**Description:**
$title. Using `ballerina build xyz.bal` and `ballerina run xyz.jar`.

ballerina-internal.log
```log
[2020-10-07 10:29:05,055] SEVERE {b7a.log.crash} - ballerina/java/0_9_0/$_init 
java.lang.NoClassDefFoundError: ballerina/java/0_9_0/$_init
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: ballerina.java.0_9_0.$_init
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
```

**Affected Versions:**
Current master

**Comment by riyafa** [comment]
This is because the migration of ballerina/java as a langlib module from PR https://github.com/ballerina-platform/ballerina-lang/pull/23504 has some issues. The ballerina-java module is not recognized under ballerina-lang in gradle and is not included in the rt jar.
