### ISSUE TITLE
HTTP module fails with the error 'http:HttpResourceConfig & readonly' cannot be cast to 'anydata'

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#26478]
**Description:**
HTTP and WebSub modules are failing with the error, 
```
error: error("{ballerina}TypeCastError",message="incompatible types: 'websub:SubscriberServiceConfiguration & readonly' cannot be cast to 'anydata'")
ballerina: Oh no, something really went wrong.
```
Internal Log

```
[2020-10-21 16:50:16,962] SEVERE {b7a.log.crash} - error("{ballerina}TypeCastError",message="incompatible types: 'websub:SubscriberServiceConfiguration & readonly' cannot be cast to 'anydata'") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("{ballerina}TypeCastError",message="incompatible types: 'websub:SubscriberServiceConfiguration & readonly' cannot be cast to 'anydata'")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:567)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("{ballerina}TypeCastError",message="incompatible types: 'websub:SubscriberServiceConfiguration & readonly' cannot be cast to 'anydata'")
	at io.ballerina.runtime.api.ErrorCreator.createError(ErrorCreator.java:60)
	at io.ballerina.runtime.internal.ErrorUtils.createTypeCastError(ErrorUtils.java:88)
	at io.ballerina.runtime.TypeChecker.checkCast(TypeChecker.java:146)
	at ballerina.lang_value.1_0_0.value.cloneReadOnly(value.bal:44)
	at ballerina.websub_advanced_integration_tests.1_0_3.tests.subscriber.test_subscribers_at_basic_auth_secured_hub.$annot_func$_726(tests/subscriber/test_subscribers_at_basic_auth_secured_hub.bal:32)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$annot_func$_726$lambda7$(websub_advanced_integration_tests)
	at io.ballerina.runtime.values.FPValue.call(FPValue.java:62)
	at io.ballerina.runtime.AnnotationUtils.processServiceAnnotations(AnnotationUtils.java:75)
	at io.ballerina.runtime.types.BServiceType.setAttachedFuncsAndProcessAnnots(BServiceType.java:45)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_17(websub_advanced_integration_tests:48)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_16(websub_advanced_integration_tests:52)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_15(websub_advanced_integration_tests:35)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_14(websub_advanced_integration_tests:26)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_13(websub_advanced_integration_tests:119)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_12(websub_advanced_integration_tests:114)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_11(websub_advanced_integration_tests:90)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_10(websub_advanced_integration_tests:85)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_9(websub_advanced_integration_tests:61)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_8(websub_advanced_integration_tests:56)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_7(websub_advanced_integration_tests:30)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_6(websub_advanced_integration_tests:25)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_5(websub_advanced_integration_tests:24)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_4(websub_advanced_integration_tests:64)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_3(websub_advanced_integration_tests:47)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_2(websub_advanced_integration_tests:30)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_1(websub_advanced_integration_tests:28)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__init_0(websub_advanced_integration_tests:24)
	at ballerina.websub_advanced_integration_tests.1_0_3.websub_advanced_integration_tests.$ballerina_websub_advanced_integration_tests_1_0_3__testinit_(websub_advanced_integration_tests:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
```

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26476.
