### ISSUE TITLE
Failed to publish events to analytics gRPC server

### ISSUE THREAD

**Issue by ruwiniwj** [ballerina-platform/ballerina-lang#26488]
**Description:**
gRPC server implemented using the following message and rpc call fails to receive data.

```
service AnalyticsService {
  rpc PublishEvent(stream EventList) returns (google.protobuf.Empty) {}
}

message EventList {
  repeated Event events = 1;
}

message Event {
    string nodeId = 1;
    string applicationConsumerKey = 2;
    string applicationName = 3;
    string applicationId = 4;
    string applicationOwner = 5;
    string apiContext = 6;
    string apiName = 7;
    string apiVersion = 8;
    string apiResourcePath = 9;
    string apiResourceTemplate = 10;
    string apiMethod = 11;
    string apiCreator = 12;
    string apiCreatorTenantDomain = 13;
    string apiTier = 14;
    string apiHostname = 15;
    string username = 16;
    string userTenantDomain = 17;
    string userIp = 18;
    string userAgent = 19;
    string requestTimestamp  = 20;
    bool throttledOut = 21;
    int64 responseTime = 22;
    int64 serviceTime  = 23;
    int64 backendTime = 24;
    bool responseCacheHit = 25;
    int64 responseSize = 26;
    string protocol = 27;
    int32 responseCode = 28;
    string destination = 29;
    int64 securityLatency = 30;
    int64 throttlingLatency = 31;
    int64 requestMedLat = 32;
    int64 responseMedLat = 33;
    int64 backendLatency = 34;
    int64 otherLatency = 35;
    string gatewayType = 36;
    string label = 37;
    string subscriber = 38;
    string throttledOutReason = 39;
    string throttledOutTimestamp = 40;
    string errorCode = 41;
    string errorMessage = 42;
    string regionId = 43;
    string apiUUID = 44;
    string customerID = 45;
}

```

The following error was observed in the gRPC client. (The client was implemented using Java)

```
io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 499
invalid content-type: text/plain
headers: Metadata(:status=499,content-type=text/plain,grpc-status=CANCELLED,grpc-message=Failed to dispatch inbound message. null,server=ballerina,date=Thu, 22 Oct 2020 10:55:13 +0530)
DATA-----------------------------
failed to dispatch inbound message. null
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Affected Versions:**
Ballerina slp3

**Related Issues (optional):**
A similar issue seem to have been reported and fixed in https://github.com/ballerina-platform/ballerina-lang/issues/20888

**Suggested Assignees (optional):**
@daneshk

**Comment by ruwiniwj** [comment]
This seems to be an intermittent issue. I was able to successfully publish events to the same server today.
