### ISSUE TITLE
VSCODE object, class, object-ctor errors are issuing exceptions. (Diagnostics are not shown)

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26505]
**Description:**

```Ballerina
class Person {
    public int age;
    public string firstName;
    public string lastName;

    // The object initializer.
    function init(int age, string firstName, string lastName) {
        self.age = age;
        self.first Name = firstName;
        self.lastName = la;
    }

    // A method returning the full name value of the `Person` object.
    function getFullName() returns string {
        return self.firstName + " " + self.lastName;
    }
}
```

## Log
```LogTalk

[Error - 3:28:05 PM] Operation 'text/codeAction' failed! {uri: '/Users/rukshanp/Projects/ballerina-distribution/examples/object-methods/t3.bal', line: 9, col: 18- line: 9, col: 18, error: 'Oh no, something really went wrong. Bad. Sad.'}
org.ballerinalang.langserver.compiler.exception.CompilationFailedException: Oh no, something really went wrong. Bad. Sad.
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:237)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackages(LSModuleCompiler.java:166)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackage(LSModuleCompiler.java:69)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.topLevelNodeInLine(CodeActionUtil.java:76)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$9(BallerinaTextDocumentService.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.checkAssignment(DataflowAnalyzer.java:1843)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:520)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1729)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:449)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:105)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1729)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:300)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1729)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:281)
	at org.wso2.ballerinalang.compiler.CompilerDriver.dataflowAnalyze(CompilerDriver.java:351)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:278)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:89)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:220)
	... 11 more

```

## Errors

Some errors are retained and not getting updated.

<img width="667" alt="3" src="https://user-images.githubusercontent.com/2173530/96850602-a0b65d80-1474-11eb-8c0a-abada8d96109.png">
<img width="667" alt="8" src="https://user-images.githubusercontent.com/2173530/96850624-a9a72f00-1474-11eb-9dad-233bcde3bf5b.png">

Gif is created by saving the file after each step.
![animated](https://user-images.githubusercontent.com/2173530/96850536-8c726080-1474-11eb-86ce-e80698e2b908.gif)

https://ballerina.io/swan-lake/learn/by-example/object-constructor-expression.html
https://ballerina.io/swan-lake/learn/by-example/object-initializer.html

**Steps to reproduce:**

**Affected Versions:**
slp5b1

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Final Fields BBE fails for largely similar log and `Documentation` functionalities also do not work probably due to this.
https://ballerina.io/swan-lake/learn/by-example/object-final-fields.html

```LogTalk
Info  - 3:57:28 PM] Operation 'text/hover' {projectRoot: '/Users/rukshanp/Projects/ballerina-distribution/examples/object-final-fields'}, served through cache within 0ms
[Error - 3:57:29 PM] Operation 'text/codeAction' failed! {uri: '/Users/rukshanp/Projects/ballerina-distribution/examples/object-final-fields/object_final_fields.bal', line: 9, col: 12- line: 9, col: 12, error: 'Oh no, something really went wrong. Bad. Sad.'}
org.ballerinalang.langserver.compiler.exception.CompilationFailedException: Oh no, something really went wrong. Bad. Sad.
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:237)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackages(LSModuleCompiler.java:166)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.getBLangPackage(LSModuleCompiler.java:69)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.topLevelNodeInLine(CodeActionUtil.java:76)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$9(BallerinaTextDocumentService.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2574)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:62)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3188)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1745)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:363)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1857)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:363)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:517)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:363)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visitFunction(CodeAnalyzer.java:487)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:454)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:363)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$analyzeTopLevelNodes$1(CodeAnalyzer.java:352)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:352)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:347)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:336)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeAnalyze(CompilerDriver.java:347)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:273)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:89)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compileSafe(LSModuleCompiler.java:220)
	... 11 more
```

**Comment by nadeeshaan** [comment]
Tested this in the latest master sl-alpha6-snapshot in lang. This issue seems not to be existing. Hence closing the issue and please reopen if the issue still exists.
