### ISSUE TITLE
NullPointerException for mapping constructor key with built in type names

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26537]
**Description:**
note $subject

#### Ballerina code
```Ballerina
public function main() {
    var x = {
        never: 65,
    };
} 
```

#### Output
```LogTalk

[2020-10-22 21:03:15,478] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1690)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangRecordVariableDef.accept(BLangRecordVariableDef.java:48)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2766)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2762)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:381)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:353)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2766)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2758)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:269)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:243)
        at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:339)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:268)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```
**Steps to reproduce:**
Compile above code

**Affected Versions:**
Swan Lake

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Here `never` is a mapping constructor key, right? Happens for other built-in types too;

e.g.,
```
public function main() {
    var x = {
        int: 65,
    };
} 
```

**Comment by KRVPerera** [comment]
My bad title should be changed. I tried to create a test case like that and then after the crash reduced it to a different one.

Below also crash in node transformer.
```
public function main() {
    map<int> x = {
        test: typedesc<>,
    };
}
```
