### ISSUE TITLE
Bad sad error gets thrown when compiling googleapis gmail module

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#26592]
**Description:**
I get the following bad sad error when building `module-ballerinax-googleapis.gmail` with Ballerina slp5.

```
[2020-10-26 11:23:18,445] SEVERE {b7a.log.crash} - Illegal character in path at index 4: lang\.int/ 
java.lang.IllegalArgumentException: Illegal character in path at index 4: lang\.int/
	at java.base/java.net.URI.create(URI.java:883)
	at java.base/java.net.URI.resolve(URI.java:1066)
	at org.wso2.ballerinalang.compiler.packaging.converters.URIConverter.combine(URIConverter.java:90)
	at org.wso2.ballerinalang.compiler.packaging.converters.URIConverter.combine(URIConverter.java:47)
	at org.wso2.ballerinalang.compiler.packaging.Patten.callReduceForEach(Patten.java:93)
	at org.wso2.ballerinalang.compiler.packaging.Patten.lambda$convert$1(Patten.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.wso2.ballerinalang.compiler.packaging.RepoHierarchy.resolve(RepoHierarchy.java:61)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageEntity(PackageLoader.java:263)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageSymbol(PackageLoader.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:800)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:244)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:300)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:294)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:244)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:237)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:147)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:66)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:435)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.net.URISyntaxException: Illegal character in path at index 4: lang\.int/
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 34 more
 
```

**Steps to reproduce:**
Clone [module-ballerinax-googleapis.gmail](https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail) and build with Ballerina slp5 using the command `ballerina build -a -c`

**Affected Versions:**
Ballerina slp5

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by rdhananjaya** [comment]
This issue seems to have two parts.
1. Compiler front-end doesn't escape the `\.` part in the module name.
2. Package resolving doesn't seems to support charactors that are not URI compatible ( in this case `\`)

Issue to track and fix part of this issue in compiler front-end side: https://github.com/ballerina-platform/ballerina-lang/issues/26597

**Comment by azinneera** [comment]
Closing since this issue is not applicable now.
