### ISSUE TITLE
Compiler crashes when there is a hyphen(-) with module name of import declaration

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26603]
**Description:**
$Title

**Steps to reproduce:**
```
import ballerina/lang.ballerina-val-test as test;
```
Running the above crashed the compiler with the following in the crash log:
```
[2020-10-26 16:57:24,691] SEVERE {b7a.log.crash} - class 
io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app')
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getAnnotations(BLangNodeTransformer.java:480)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:549)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:436)
	at io.ballerina.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:530)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:436)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:460)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:121)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:94)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:487)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:374)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Comment by KRVPerera** [comment]
Not just hyphen. Below code also give a Bad Sad error.

```Ballerina
ximport ballerina/log;
```

```LogTalk
[2020-10-27 09:06:37,239] SEVERE {b7a.log.crash} - class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app')
	at java.base/java.util.Optional.map(Unknown Source)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getAnnotations(BLangNodeTransformer.java:480)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:549)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:436)
```

**Comment by KRVPerera** [comment]
This also looks similar to issue `Bad sad error gets thrown when compiling AWS S3 module` #26591

**Comment by chamil321** [comment]
Mistakenly I have the following lines(not within a particular scope) in a bal file. I got the same error. 

```
path : "/{foo}/bar"

foo 1



(@Payload{})
string[]
type
```
