### ISSUE TITLE
Crashes the compiler when it uses invalid number as an index of array

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26635]
**Description:**
```ballerina
public function main() {
    int[] a = [];
    a[2wed2] = 10;
}
```
```ballerina
public function main() {
    int[] a = [];
    a[2147483647-9] = 10;
}
```
Running the above programs crashed the compiler with the following in the crash log:
```
[2020-10-27 22:05:07,455] SEVERE {b7a.log.crash} - class 
io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.BindingPatternNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.BindingPatternNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.BindingPatternNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.BindingPatternNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getBLangVariableNode(BLangNodeTransformer.java:4019)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2642)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2618)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4111)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1437)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1344)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1315)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:529)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:459)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:121)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:94)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:487)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:374)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:435)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Comment by chiranSachintha** [comment]
When considering the following program, It compiles properly and gives an error as `undefined symbol 'xxx'`
```ballerina
public function main() {
    int[] a = [];
    a[xxx] = 10;
}
```
