### ISSUE TITLE
Compiler crashes for distinct object-type-descriptor

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26648]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo distinct object {
    int i;
    string s;
};
```

```cmd
[2020-10-28 12:18:32,725] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType cannot be cast to class org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode (org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType and org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType cannot be cast to class org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode (org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType and org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.populateDistinctTypeIdsFromIncludedTypeReferences(SymbolEnter.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineDistinctClassAndObjectDefinitions(SymbolEnter.java:404)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:374)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:282)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:244)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:237)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:464)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:375)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp5

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26212
