### ISSUE TITLE
Bad Sad error for ballerina project when Address already in use

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26640]
**Description:**
When the address is already in use `ballerina build -a -c" command gives a Bad Sad error.

```
error: error("failed to start server connector '0.0.0.0:9090': Address already in use")
ballerina: Oh no, something really went wrong.

The `ballerina-internal.log` file located in the current directory
...

error: there are test failures
```

```LogTalk
[2020-10-28 09:42:58,043] SEVERE {b7a.log.crash} - error("failed to start server connector '0.0.0.0:9090': Address already in use")
io.ballerina.runtime.util.exceptions.BallerinaException: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:572)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:564)
	at org.ballerinalang.net.http.serviceendpoint.Start.startServerConnector(Start.java:63)
	at org.ballerinalang.net.http.serviceendpoint.Start.start(Start.java:41)
	at ballerina.http.1_0_1.service_endpoint.externStart(service_endpoint.bal:148)
	at ballerina.http.1_0_1.$value$Listener.startEndpoint(service_endpoint.bal:119)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at ballerina.http.1_0_1.$value$Listener.__start(service_endpoint.bal:40)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at rukshanp.np.0_1_0.$_init.$rukshanp_np_0_1_0__start_(np:2)
	at rukshanp.np.0_1_0.$_init.$moduleStart(np)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Steps to reproduce:**
Create a simple project and a module. Copy the hello world BBE to main.bal. Run `ballerina build -a -c`. Run the module via ballerina run. 
On a different terminal try to run `ballerina build -a -c` again.

> ballerina new testCrash
> cd testCrash
> ballerina add np

Copy Hello World service BBE to main.bal in np module.
https://ballerina.io/swan-lake/learn/by-example/hello-world-service.html

> ballerina build -a -c
> ballerina run np
> ballerina build -a -c (on a different terminal)

**Affected Versions:**
Swan Lake

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Tracked in https://github.com/ballerina-platform/ballerina-lang/issues/25340
