### ISSUE TITLE
Bad Sad error when compiling

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26667]
**Description:**
I have a project which crashes when trying to compile. I have added a tag `0` for this version. 
https://github.com/KRVPerera/Links/releases/tag/0

```LogTalk
[2020-10-29 08:34:27,753] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:457)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:445)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:158)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:128)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:327)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:323)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:147)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:66)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:435)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:727)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:689)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:672)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:432)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:280)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateBasicBlocks(JvmMethodGen.java:1283)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:288)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:2220)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:505)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Steps to reproduce:**
Get the code in https://github.com/KRVPerera/Links/releases/tag/0
Use slp5 and try to compile.

**Affected Versions:**
slp5

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
I have simplified the code in a branch named `crash` with tag https://github.com/KRVPerera/Links/releases/tag/0.1

**Comment by HindujaB** [comment]
I am getting the following compilation error when building module:db in the given project. This causes the NPE at code generation as the main module is depending on module:db. 
```
error: rukshanp/db:0.1.0::main.bal:36:60: undefined method 'executeQuery' in object 'ballerina/java.jdbc:0.5.1:Client'
```

**Comment by KRVPerera** [comment]
This happened while the code is unstable. Let me explain. You can test this with https://github.com/KRVPerera/Links/releases/tag/0. Most of the code are straight copied from BBEs. In the `src/db/main.bal` file change `getAllRecord` methods query to `jdbcClient->execute`. Then the project will build successfully. But I am using the execute method for a search query. Since the project gets build successfully you can run the API module (`ballerina run api`). 
Then run this command in the terminal `curl http://localhost:9090/links/all -d '{"name" : "all"}' -H "Content-Type:application/json"`

You will get the below error.

```LogTalk
Compiling source
	rukshanp/api:0.1.0

Creating balos
	target/balo/api-2020r2-any-0.1.0.balo
	target/bin/api.jar

Running executables

[ballerina/http] started HTTP/WS listener 0.0.0.0:9090
2020-11-09 22:41:41,879 ERROR [rukshanp/db] - Error occurred:  : error("Error while executing SQL query: select * from Links. Method is not allowed for a query. Use execute or executeQuery instead of executeUpdate; SQL statement:
select * from Links [90001-199].",errorCode=90001,sqlState="90001")
```

So without further investigating and trying to understand I changed the `execute` to `executeQuery`. After that, I get an NPE and reported it here.
But I understand it is much easier if we can reproduce this in a very simple example.  Also, even a slight change to the code will remove the NPE. I kind of feel the root cause is only in `src/db/main.bal`.

**Comment by HindujaB** [comment]
This happens due to a bug in `CompilerDriver` (slp5) which causes different order of module compilation depending on the module name. This is fixed in the master with the new Project API changes. 

https://github.com/ballerina-platform/ballerina-lang/blob/109942413cba1a3671a0cfbd1c6d4d2ae4571cac/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java#L176

**Comment by KRVPerera** [comment]
Closing as fixed in later releases.
