### ISSUE TITLE
Calling stackTrace() crashes the runtime

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26678]
Consider the following:
```ballerina
import ballerina/io;

public function main() {
    error v = <error>trap foo();
    io:println(v.stackTrace());
}

function foo() {
  bar();
}

function bar() {
  baz();
}

function baz() {
  panic error("Op Failed");
}
```
The above program crashes with the following log:
```
[2020-10-29 16:07:24,659] SEVERE {b7a.log.crash} - class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.values.AbstractObjectValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.values.AbstractObjectValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.values.AbstractObjectValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.values.AbstractObjectValue are in unnamed module of loader 'app')
	at io.ballerina.runtime.api.StringUtils.getStringValue(StringUtils.java:201)
	at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
	at ballerina.io.0_5_1.print.println(print.bal:36)
	at test.main(test.bal:7)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
[2020-10-29 16:07:24,684] SEVERE {b7a.log.crash} - class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.values.AbstractObjectValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.values.AbstractObjectValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.values.AbstractObjectValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.values.AbstractObjectValue are in unnamed module of loader 'app')
	at io.ballerina.runtime.api.StringUtils.getStringValue(StringUtils.java:201)
	at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
	at ballerina.io.0_5_1.print.println(print.bal:36)
	at test.main(test.bal:7)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by riyafa** [comment]
The following code does not crash:
```
public function main() {
    error v = <error>trap foo();
    var trace = v.stackTrace().callStack;
}

function foo() {
  bar();
}

function bar() {
  baz();
}

function baz() {
  panic error("Op Failed");
}
```
Can this be an stdlib issue?

**Comment by pubudu91** [comment]
More like an issue in the `StringUtils` class I guess? Don't think it's an std lib issue
