### ISSUE TITLE
CCE for MappingBindingPatternNode to CaptureBindingPatternNode

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26694]
**Description:**
Below code givea a CCE.

```Ballerina
import ballerina/http;

@http:ServiceConfig {
    basePath : "/hello" // missing comma
    cors: {
        allowOrigins: ["http://www.m3.com", "http://www.hello.com"]
    }
}
service hello on new http:Listener(9090) {}
```

```LogTalk
[2020-11-01 21:25:53,619] SEVERE {b7a.log.crash} - class io.ballerina.compiler.syntax.tree.MappingBindingPatternNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.MappingBindingPatternNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.MappingBindingPatternNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.MappingBindingPatternNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:545)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:436)

	at io.ballerina.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)

	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:530)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:436)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:460)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:121)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:94)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:487)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:374)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**

**Affected Versions:**
slp5

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/24833
https://github.com/ballerina-platform/ballerina-lang/issues/24878
https://github.com/ballerina-platform/ballerina-lang/issues/24473
https://github.com/ballerina-platform/ballerina-lang/issues/25486
https://github.com/ballerina-platform/ballerina-lang/issues/25910

**Comment by rdulmina** [comment]
Fixed in #26949
