### ISSUE TITLE
NPE when org name is not present in the import statement

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#26719]
**Description:**
Getting the below NPE when imports does not contain orgname part.

```
    java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at java.base/java.util.Optional.<init>(Optional.java:107)
        at java.base/java.util.Optional.of(Optional.java:120)
        at io.ballerina.projects.environment.ModuleLoadRequest.orgName(ModuleLoadRequest.java:54)
        at io.ballerina.projects.environment.PackageLoadRequest.from(PackageLoadRequest.java:49)
        at io.ballerina.projects.env.DefaultPackageResolver.loadFromDistributionCache(DefaultPackageResolver.java:91)
        at io.ballerina.projects.env.DefaultPackageResolver.loadPackages(DefaultPackageResolver.java:70)
        at io.ballerina.projects.ModuleContext.resolveDependenciesInternal(ModuleContext.java:292)
        at io.ballerina.projects.ModuleCompilationState$1.resolveDependencies(ModuleCompilationState.java:38)
        at io.ballerina.projects.ModuleContext.resolveDependencies(ModuleContext.java:263)
        at io.ballerina.projects.PackageContext.populateModuleDependencies(PackageContext.java:212)
        at io.ballerina.projects.PackageContext.resolveDependencies(PackageContext.java:196)
        at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:143)
        at io.ballerina.projects.Package.getCompilation(Package.java:113)
```

Need to fails with proper error message here.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
After changes to the initial Project API code, this is the latest BadSad reproducible:
```
[2021-04-19 11:52:54,963] SEVERE {b7a.log.crash} - The orgName cannot be an empty string. It should be either null or a non-empty string value 
java.lang.IllegalArgumentException: The orgName cannot be an empty string. It should be either null or a non-empty string value
	at io.ballerina.projects.environment.ModuleLoadRequest.<init>(ModuleLoadRequest.java:50)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequest(DocumentContext.java:185)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:129)
	at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:121)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:172)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:160)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:236)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:146)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:70)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:77)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:213)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:68)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:263)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)

```
