### ISSUE TITLE
Jar emit fails if the project is already compiled and thin jar is found in cache

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#26720]
**Description:**
Getting a NPE as below for $subject.

```
    java.lang.NullPointerException
        at io.ballerina.projects.JarWriter.write(JarWriter.java:50)
        at io.ballerina.projects.JBallerinaBackend.emitJar(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:112)
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
This issue is not reproducible anymore. If you compile and codegen without cleaning target, it still works as expected.
