### ISSUE TITLE
Bad, sad error for bound method access on union

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26726]
**Description:**
$title.

https://github.com/ballerina-platform/ballerina-lang/issues/26667 has an almost similar stacktrace.

**Steps to reproduce:**
```ballerina
class Foo {
    function func(int i) returns int => i;
}

class Bar {
    function func(int i) returns int => i + 1;
}

public function main() {
    Foo|Bar ob = new Foo();
    function (int) returns int func = ob.func;
}
```

```log
[2020-11-03 22:47:19,062] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:726)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:689)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:672)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:432)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:280)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateBasicBlocks(JvmMethodGen.java:1283)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:288)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:2220)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:505)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:457)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:445)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:158)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:128)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:327)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:323)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp5

**Comment by Nadeeshan96** [comment]
Here I see an issue in the generated BIR. There it doesn't denote to which object the method `func` belongs. See the following code.
```ballerina
class Foo {
    function func(int i) returns int => i;
}

class Bar {
    function func(int i) returns int => i + 1;
}

public function main() {
    Foo obj = new Foo();
    function (int) returns int funcworking = obj.func;

    Foo|Bar unionobj = new Foo();
    function (int) returns int funcnotworking = unionobj.func;
}
```
In the generated BIR, can see the following.
```llvm
public main function() -> () {
    %0(RETURN) ();
    %1(SYNTHETIC) map<...>;
    %2(TEMP) typeDesc<...>;
    %4(SYNTHETIC) Foo;
    %7(TEMP) ();
    %10(TEMP) string;
    %11(LOCAL) function(int) -> int;
    %13(TEMP) Foo|Bar;
    %14(SYNTHETIC) Foo;
    %17(TEMP) ();
    %21(LOCAL) function(int) -> int;

    bb0 {
        %2 = newType map<...>;
        %1 = NewMap %2;
        %4 = new Foo;
        %7 = $init$(%4) -> bb1;
    }
    bb1 {
        %10 = ConstLoad obj;
        %1[%10] = %4;
        %11 = fp $anon/.:0.0.0::$annon$method$delegate$0(%1);
        %14 = new Foo;
        %17 = $init$(%14) -> bb2;
    }
    bb2 {
        %13 = <Foo|Bar> %14;
        %10 = ConstLoad unionobj;
        %1[%10] = %13;
        %21 = fp $anon/.:0.0.0::$annon$method$delegate$1(%1);
        %0 = ConstLoad 0;
        GOTO bb4;
    }
    bb3 {
        GOTO bb4;
    }
    bb4 {
        return;
    }


}

$annon$method$delegate$0 function(map<...>, int) -> int {
    %0(RETURN) int;
    %1(ARG) ...;
    %2(ARG) int;
    %4(TEMP) string;
    %5(TEMP) Foo;

    bb0 {
        %4 = ConstLoad obj;
        %5 = %1[%4];
        %0 = func(%5, %2) -> bb1;
    }
    bb1 {
        GOTO bb3;
    }
    bb2 {
        GOTO bb3;
    }
    bb3 {
        return;
    }


}

$annon$method$delegate$1 function(..., int) -> int {
    %0(RETURN) int;
    %1(ARG) ...;
    %2(ARG) int;

    bb0 {
        %0 = func(%2) -> bb1;
    }
    bb1 {
        GOTO bb3;
    }
    bb2 {
        GOTO bb3;
    }
    bb3 {
        return;
    }


}
``` 
Although in the main function `%1 map` gets passed to the `$annon$method$delegate$1` function it does not get used there. Hence, when there is an union type it does not know which object method `func` belongs to and produce the mentioned error. When there is no union it works correctly, see `$annon$method$delegate$0` function.

**Comment by warunalakshitha** [comment]
This seems to isseu with rewriteObjectMemberAccessAsField in Desuger.
