### ISSUE TITLE
StackOverflowError for incorrect syntax with `isolated`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26742]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
isolated boolean foo(any[] arr) returns boolean => true;
```

```log
[2020-11-04 13:35:19,036] SEVERE {b7a.log.crash} - null 
java.lang.StackOverflowError
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:380)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1142)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExpressionRhs(BallerinaParserErrorHandler.java:2274)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2037)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1142)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1142)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2044)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1142)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1908)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1142)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1908)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1668)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1131)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:181)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:102)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:106)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:14187)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:14188)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:14188)
        ..............................................................
```

**Affected Versions:**
Current master with isolated variable change.

**Comment by lochana-chathura** [comment]
Duplicate of #25724. This is fixed in the current master.

**Comment by MaryamZi** [comment]
Closing since this is fixed and will emit errors in slp6, as expected.
