### ISSUE TITLE
Bad, sad error when defining an anonymous record array where a field default value is a reference

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26784]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    final int x = 1;

    record {
        int b = x;
    }[] arr;
}
```

```log
[2020-11-05 20:39:31,879] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$BSameTypeVisitor.visit(Types.java:2075)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$BSameTypeVisitor.visit(Types.java:2054)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BType.accept(BType.java:86)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:239)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:226)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:6423)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2060)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5829)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createStructFieldUpdate(Desugar.java:6785)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createStructFieldUpdate(Desugar.java:6766)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:906)
	at org.wso2.ballerinalang.compiler.tree.types.BLangRecordTypeNode.accept(BLangRecordTypeNode.java:42)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:942)
	at org.wso2.ballerinalang.compiler.tree.types.BLangArrayType.accept(BLangArrayType.java:60)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1109)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1238)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5829)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:5839)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1032)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1072)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5846)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:744)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:409)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:371)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:313)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp2, slp5

**Comment by rdhananjaya** [comment]
Cannot reproduce in Swan Lake beta-1.
