### ISSUE TITLE
Crash during compilation of listener init in a different module

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#26837]
**Description:**
The compiler crashes when an import is missing in one module(basic) and the listener in that module(basic) is initialized in another module(current).

**Steps to reproduce:**
Consider this [project](https://github.com/ballerina-platform/ballerina-lang/files/5516144/ModuleInitInvocationProject.zip)
try building it as `ballerina build current` it crashes with the following `ballerina-internal.log`
```
[2020-11-10 14:43:24,116] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:4337)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4323)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:62)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:5813)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2059)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5829)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:5839)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1032)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1072)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.splitInitFunction(Desugar.java:7553)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:752)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5788)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:409)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:371)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:313)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:62)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:435)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```
The issue in the project is the missing import for `ballerina/test` in the `basic/main.bal`. Instead of a compilation error the build crashes. Further noticed that this crash happens for any compilation error in `basic/main.bal`, not only for import issues.

**Affected Versions:**
slp5

**OS, DB, other environment details and versions:**
Ubuntu 20.04

**Comment by ThisaruGuruge** [comment]
I've faced the same issue when there is a test failure in a submodule, and a class from that submodule is used in the top-level module. Instead of showing the test failure, or error, it crashes without a clue.

**Comment by azinneera** [comment]
Looks like this is related to https://github.com/ballerina-platform/ballerina-lang/issues/27471. @rdhananjaya

**Comment by rdhananjaya** [comment]
Yes this look similar to that, checked with Swan Lake beta1, this is fixed now
