### ISSUE TITLE
Compiler crashes when there's native code with outdated code

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26915]
I was compiling a module with interop code and the native component of it had outdated code, with classes which are no longer there/exposed. During codegen, this caused the compiler to crash with the following log. Ideally, for these scenarios, the compiler should give an appropriate error message:
```
[2020-11-13 14:37:06,245] SEVERE {b7a.log.crash} - org/ballerinalang/jvm/values/api/BString 
java.lang.NoClassDefFoundError: org/ballerinalang/jvm/values/api/BString
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
	at java.base/java.lang.Class.getMethods(Class.java:1904)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.getExecutables(JMethodResolver.java:723)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolveByMethodName(JMethodResolver.java:136)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolve(JMethodResolver.java:106)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateAndGetJMethod(InteropValidator.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJMethodWrapper(InteropMethodGen.java:776)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJInteropFunctionWrapper(InteropMethodGen.java:764)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.createExternalFunctionWrapper(ExternalMethodGen.java:273)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.getBirFunctionWrapper(JvmPackageGen.java:747)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.linkTypeDefinitions(JvmPackageGen.java:633)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateClassNameLinking(JvmPackageGen.java:583)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:428)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:159)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:128)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:327)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:323)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:62)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.ClassNotFoundException: org.ballerinalang.jvm.values.api.BString
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 30 more
```

**Comment by warunalakshitha** [comment]
@pubudu91 Can you provide us an example? I have tested this with the following code and it gives approprite error.

```
import ballerina/jballerina.java;
public function foo() returns handle = @java:FieldGet {
    name: "foo",
    'class: "myClass"
} external;
```

Getting following compilation issue

ERROR [main.bal:(2:1,5:12)] {ballerina/jballerina.java}CLASS_NOT_FOUND 'myClass'

**Comment by pubudu91** [comment]
Ah no, I didn't mean the native implementation class. I meant the use of old runtime API classes. In this case, the old `BString` class.

**Comment by warunalakshitha** [comment]
IMO we need to handle that scenario as well.
