### ISSUE TITLE
Having multiple BIR test classes in the module test suite causes build failure in Windows build in Github Actions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26987]
In the `ballerina-compiler-api-test` module, there's a BIR test class (`SymbolBIRTest`) which sets up a module using the `BaloCreator`. Recently, I tried to add another BIR test class which used the same module. But when I opened a PR, the Windows build for it failed due to failing the `SymbolBIRTest`. It was apparently a permission issue when trying to set up the BIR. The following was the exception stack trace:

```
Gradle suite > Gradle test > io.ballerina.semantic.api.test.SymbolBIRTest > setup FAILED
    org.ballerinalang.core.util.exceptions.BLangRuntimeException: error occured while copying from 'src\test\resources\test-src\test-project\.ballerina' to 'build\ballerina-home\test\lib'
        at org.ballerinalang.test.util.BFileUtil.copy(BFileUtil.java:79)
        at org.ballerinalang.test.balo.BaloCreator.create(BaloCreator.java:79)
        at org.ballerinalang.test.balo.BaloCreator.createAndSetupBalo(BaloCreator.java:114)
        at io.ballerina.semantic.api.test.SymbolBIRTest.setup(SymbolBIRTest.java:62)

        Caused by:
        java.nio.file.AccessDeniedException: src\test\resources\test-src\test-project\.ballerina\repo\testorg\foo\1.0.0\foo.zip -> build\ballerina-home\test\lib\repo\testorg\foo\1.0.0\foo.zip
            at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
            at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
            at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:202)
            at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:283)
            at java.base/java.nio.file.Files.copy(Files.java:1294)
            at org.ballerinalang.test.util.BFileUtil$1.visitFile(BFileUtil.java:73)
            at org.ballerinalang.test.util.BFileUtil$1.visitFile(BFileUtil.java:52)
            at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
            at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
            at org.ballerinalang.test.util.BFileUtil.copy(BFileUtil.java:52)
            ... 3 more
```

Build scan: https://scans.gradle.com/s/ng5if23ugzqjq

When I removed the newly added test, the build passed. So it looks like there's an issue in the `BaloCreator`. It's also passing when I use a different Ballerina module than the one used by `SymbolBIRTest`. 

There wasn't any failures locally either.

**Comment by manuranga** [comment]
Wired issue, since it only happens on windows and is a permission issue, must be some edge case related filesystem, maybe pervious copy of the file is still being read.

**Comment by warunalakshitha** [comment]
This issue needs to be fixed in Project APIs side. BTW the given code seems to be no longer exist in the code, with new project api impl. We need to recheck this issue with new project api impl.

**Comment by warunalakshitha** [comment]
Closing this since we no longer observe the issue with new project API.
