### ISSUE TITLE
ballerina init fails with a BAD SAD error on Windows

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#27097]
Steps to reproduce 

1. Create a empty directory 
1. CD to that directory
1. run ballerina init

It fails with following error. 

```
[2020-11-23 20:25:52,800] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at io.ballerina.projects.util.FileUtils.readFileAsString(FileUtils.java:100)
	at io.ballerina.cli.cmd.CommandUtil.initProject(CommandUtil.java:261)
	at io.ballerina.cli.cmd.InitCommand.execute(InitCommand.java:140)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Comment by hasithaa** [comment]
This is happening for `ballerina new` command as well. 

```
[2020-11-23 23:11:40,206] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at io.ballerina.projects.util.FileUtils.readFileAsString(FileUtils.java:100)
	at io.ballerina.cli.cmd.CommandUtil.initProject(CommandUtil.java:228)
	at io.ballerina.cli.cmd.CommandUtil.initProjectByTemplate(CommandUtil.java:138)
	at io.ballerina.cli.cmd.NewCommand.execute(NewCommand.java:144)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 ```
