### ISSUE TITLE
Jar files not created if no entry-point is there in the code.

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#27119]
**Description:**
In slp5 a jar file got created even there was no entry-point. As per new project API changes, the following bad sad error is thrown if a single .bal file is compiled without an entry point.

```
[2020-11-24 15:02:28,597] SEVERE {b7a.log.crash} - no entrypoint found in package: .
java.lang.RuntimeException: no entrypoint found in package: .
	at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:476)
	at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:138)
	at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:101)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:242)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:5
```

**Steps to reproduce:**
Compile a single bal file without an entry-point.

**Affected Versions:**
SLP6 SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sameerajayasoma** [comment]
We are removing the entry point validation with this PR. 

https://github.com/ballerina-platform/ballerina-lang/pull/27164
