### ISSUE TITLE
Parser crashes for negative source: block-statement with an on-fail-clause

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#27214]
**Description:**
Consider the following code snippet

```bal
public function test() {
    int i = 0;
    {
        i = i + 1;
        error err = error("Custom error thrown explicitly.");
        fail err;
    } on fail error e {
        io:println("Exception thrown...");
    }
}
```

Parser crashes with IllegalStateException.

</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```java
java.lang.IllegalStateException: found close-brace in: fail-stmt
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.getNextRuleForCloseBrace(BallerinaParserErrorHandler.java:3904)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.getNextRule(BallerinaParserErrorHandler.java:2344)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:386)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1152)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekInStatements(BallerinaParserErrorHandler.java:2086)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1699)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1683)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1141)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekInStatements(BallerinaParserErrorHandler.java:2086)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1699)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1683)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1141)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1152)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1152)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:2062)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1919)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1683)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1141)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1152)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1923)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1683)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1141)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:181)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:102)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:106)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:14284)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPatterns(BallerinaParser.java:14153)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPatterns(BallerinaParser.java:14183)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPatterns(BallerinaParser.java:14149)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorBindingPattern(BallerinaParser.java:14109)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorBindingPattern(BallerinaParser.java:14104)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseErrorBindingPattern(BallerinaParser.java:14087)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:3994)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:3933)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:3927)
```

</details>

**Suggested Labels**
Team/CompilerFE, Area/Parser, Type/Bug

**Comment by lochana-chathura** [comment]
Issue is not from BallerinaParserErrorHandler. Reason is we have allowed error-binding-pattern in parseTerminalExpression.
