### ISSUE TITLE
Compiler crashes for invalid global level statements

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#27253]
**Description:**
Mistakenly I had added the following statements(not within a particular scope) in a bal file. These are invalid statements. 
I got the bad sad error rather than a compilation error. 

```ballerina
path : "/{foo}/bar"

foo 1



(@Payload{})
string[]
type
```

Error : 
```
[2020-11-30 13:12:59,432] SEVERE {b7a.log.crash} - class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app')
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getAnnotations(BLangNodeTransformer.java:493)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:608)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:441)
	at io.ballerina.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:550)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:441)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:471)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:110)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:328)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:123)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:113)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:94)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:123)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:93)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:244)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```
This issue occurred in https://github.com/ballerina-platform/ballerina-lang/tree/service-typing

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/26603

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Root error cause is fixed in PR #27328.

But, still the above code segment gives CCE at BLangNodeTransformer since we still do not support list-binding-pattern in module-var-decl. Should be fixed in PR #26599

New log as follows.
</details>
<details>
  <summary><b>ballerina-internal.log</b>  (<i>click to expand</i>)</summary>

```
[2020-12-03 18:44:04,956] SEVERE {b7a.log.crash} - class io.ballerina.compiler.syntax.tree.ListBindingPatternNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.ListBindingPatternNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.ListBindingPatternNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.ListBindingPatternNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:586)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:442)
	at io.ballerina.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:549)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:442)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:472)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:110)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:328)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

</details>
