### ISSUE TITLE
Bad sad error gets thrown when compiling a foreach statement

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#27375]
**Description:**
When I try to compile a Ballerina source with the following `main()` I get bad sad error. Note that the `foreach` syntax is incorrect in the context of Ballerina language. However, the bad sad error should not be thrown. Rather the compiler should gracefully handle this error and throw an appropriate error message.

```
public function main() {
        foreach (1 ... 5) {

        }
}
```

**Steps to reproduce:**
Create a new project using Ballerina SLP7 and add a `foreach` loop as shown above to the `main.bal` file. Then build the project using `ballerina build <project_name>`.

**Affected Versions:**
Ballerina SLP7

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by miyurud** [comment]
The bad sad error log on the `ballerina-internal.log` file is as follows.

```
[2020-12-08 08:38:07,925] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:44)
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:38)
	at java.base/java.util.TreeMap.put(TreeMap.java:550)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.addDiagnostic(BLangPackage.java:277)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.storeDiagnosticInModule(BLangDiagnosticLog.java:208)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:202)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:80)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.handleForeachDefinitionVariables(SemanticAnalyzer.java:3117)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2718)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2985)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2981)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:399)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:371)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2985)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2977)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:287)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:252)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:205)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:345)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:243)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
