### ISSUE TITLE
Bad Sad error with unexpected initial charactors in the code

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#27420]
**Description:**
The following code gives a bad sad error.

```ballerina
A
B
import ballerina/io;

public function main() {
    io:println("english");
}

```

log file.

```
java.lang.ClassCastException: class io.ballerina.compiler.internal.syntax.ExternalTreeNodeList cannot be cast to class io.ballerina.compiler.syntax.tree.MetadataNode (io.ballerina.compiler.internal.syntax.ExternalTreeNodeList and io.ballerina.compiler.syntax.tree.MetadataNode are in unnamed module of loader 'app')
        at java.base/java.util.Optional.map(Unknown Source)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getAnnotations(BLangNodeTransformer.java:492)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:607)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:442)
        at io.ballerina.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:549)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:442)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:472)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:110)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:328)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
        at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**

```
$ ballerina -v
Ballerina Swan Lake Preview 7
Language specification v2020-09-22
Update Tool 0.8.10
```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Related issues: #26603
