### ISSUE TITLE
[Testerina] Function mocking throws Bad-Sad when mock annotation is used on a function

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#27480]
**Description:**
Using the mock annotation `@test:Mock { }` on a function instead of the mock object causes the compiler plugin to crash : 

```

Compiling source
        mohamedaquibzulfikar/FunctionMocking:0.1.0
WARNING [tests/main_test.bal:(7:1,8:2)] compiler plugin crashed
```

And the following bad-sad log to be printed. 

```
[2020-12-14 14:33:41,434] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.testerina.core.TestAnnotationProcessor.process(TestAnnotationProcessor.java:349)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$3(CompilerPluginRunner.java:200)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:331)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:200)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:188)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$1(CompilerPluginRunner.java:156)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:154)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:134)
	at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:233)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:148)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:345)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:200)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
[2020-12-14 14:33:41,777] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.projects.TestAnnotationProcessor.processFunction(TestAnnotationProcessor.java:342)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.ballerina.projects.JBallerinaBackend.generateTestSuite(JBallerinaBackend.java:348)
	at io.ballerina.projects.JBallerinaBackend.testSuite(JBallerinaBackend.java:284)
	at io.ballerina.cli.task.RunTestsTask.execute(RunTestsTask.java:171)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:200)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@Ibaqu We will be removing the old implementation. So, we won't face this issue. Anyway, let's test once the PR https://github.com/ballerina-platform/ballerina-lang/pull/27504 is merged.

**Comment by Dilhasha** [comment]
The null pointer is not present with after removing the deprecated mocking approach. I have updated the annotation processing to throw a compilation error if user tries to use the deprecated approach.
