### ISSUE TITLE
Compiler crashes when `var` is used with a nested complex binding pattern in a variable declaration 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27496]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    var [a, [b, c]] = [1, ["", true]];
}
```

ballerina-internal.log
```log
[2020-12-15 13:59:38,665] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.BLangTupleVariable cannot be cast to class org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable (org.wso2.ballerinalang.compiler.tree.BLangTupleVariable and org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.BLangTupleVariable cannot be cast to class org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable (org.wso2.ballerinalang.compiler.tree.BLangTupleVariable and org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.handleDeclaredWithVar(SemanticAnalyzer.java:966)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:821)
	at org.wso2.ballerinalang.compiler.tree.BLangTupleVariable.accept(BLangTupleVariable.java:56)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2985)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2977)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1770)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangTupleVariableDef.accept(BLangTupleVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2985)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2981)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:399)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:371)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3017)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2985)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2977)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:287)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:252)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:205)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:345)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp7

**Comment by lochana-chathura** [comment]
Fixed in the current master
