### ISSUE TITLE
Ballerina parser crashes due to missing error message, in error message resource bundle

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27502]
**Description:**
Execute following:
```ballerina
listener Listener|error lsn = new ();
```

Compiler crashes with following log:
```
[2020-12-15 17:11:37,134] SEVERE {b7a.log.crash} - Can't find resource for bundle java.util.PropertyResourceBundle, key error.missing.positional.arg.in.error.constructor 
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key error.missing.positional.arg.in.error.constructor
	at java.base/java.util.ResourceBundle.getObject(Unknown Source)
	at java.base/java.util.ResourceBundle.getString(Unknown Source)
	at io.ballerina.compiler.internal.diagnostics.DiagnosticMessageHelper.getDiagnosticMessage(DiagnosticMessageHelper.java:40)
	at io.ballerina.compiler.internal.diagnostics.SyntaxDiagnostic.message(SyntaxDiagnostic.java:69)
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:71)
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:38)
	at java.base/java.util.TreeMap.put(Unknown Source)
	at java.base/java.util.TreeSet.add(Unknown Source)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.addDiagnostic(BLangPackage.java:277)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.storeDiagnosticInModule(BLangDiagnosticLog.java:208)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.logDiagnostic(BLangDiagnosticLog.java:169)
	at io.ballerina.projects.DocumentContext.reportSyntaxDiagnostics(DocumentContext.java:194)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:108)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:328)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 

```
**Steps to reproduce:**

**Affected Versions:**
SLP7.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in #27516, merged via #27652.
