### ISSUE TITLE
[Testerina] Function mocking doesnt work if the test functoin has the name `test`

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#27519]
**Description:**
Function mocking throws a bad-sad when a test function has the name `test`. 

eg 

```
@test:Config {}
public function test() {
   test:when(mockIntAdd).call("mock_IntAdd");
   test:assertEquals(intAdd(4,1), 3);
}
```

However, removing the function mocking implementation does not cause any bad-sad errors. Changing the function name to `test1` does not cause any issues. 

The following is the bad-sad

```
[2020-12-16 12:18:03,199] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.ASTBuilderUtil.createInvocationExprMethod(ASTBuilderUtil.java:483)
	at org.wso2.ballerinalang.compiler.desugar.ASTBuilderUtil.createInvocationExprForMethod(ASTBuilderUtil.java:475)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateBLangInvocation(MockDesugar.java:384)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateTypeConversionExpression(MockDesugar.java:365)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateStatements(MockDesugar.java:323)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateBody(MockDesugar.java:294)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunction(MockDesugar.java:155)
	at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunctions(MockDesugar.java:114)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:709)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6607)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:422)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:237)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:156)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:362)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:301)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:200)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
 ```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/27619
