### ISSUE TITLE
[Testerina] Mismatch in Jacoco line coverage and the Test coverage report generated

### ISSUE THREAD

**Issue by sachiniSam** [ballerina-platform/ballerina-lang#27524]
**Description:**
For the observability feature improvement i carried out `BIR` level instrumentation, while testing the feature it was observed that there is a mismatch in the line coverage data produced with Jacoco coverage report and the Testerina coverage report generated.

Build fail error
```
testerina-intg-test-suite > testerina-intg-tests > org.ballerinalang.testerina.test.TestReportTest > testWithCoverage FAILED
    java.lang.AssertionError: expected [[]] but found [[22,23,24,26,29,30,36,37]]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:442)
        at org.ballerinalang.testerina.test.TestReportTest.validateCoverage(TestReportTest.java:212)
        at org.ballerinalang.testerina.test.TestReportTest.testWithCoverage(TestReportTest.java:69)
```
Jacoco coverage report

![image](https://user-images.githubusercontent.com/30947080/102325633-5ef3f000-3fa9-11eb-94f3-5ced79d8ba49.png)

**Steps to reproduce:**

**Affected Versions:**
slp7

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
I have temporally disabled the `testWithCoverage` test in the #27356 PR

**Suggested Labels (optional):**
Component/Testerina, Team/TestFramework

**Suggested Assignees (optional):**
@azinneera

**Comment by sachiniSam** [comment]
PR (#27779) with disabled `testWithCoverage` test was merged to master
