### ISSUE TITLE
DebugClient.stop() results in error

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27726]
**Description:**
DebugClient.stop(), with vscode-debugadapter-testsupport DebugClient, results in the following error, and kills the debug adapter.

```
Listening for transport dt_socket at address: 5005
Debug server started on 4711
Jan 07, 2021 5:49:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.debugadapter.JBallerinaDebugServer.disconnect(JBallerinaDebugServer.java:507)
	... 16 more
```

**Steps to reproduce:**
1. Change terminateRequest in teardown() (https://github.com/ballerina-platform/plugin-vscode/blob/master/test/debugger/debugger.test.ts#L83) to dc.stop().
2. Run debug tests againt an already started debug adapter instead of the one starts in test setup().

**Affected Versions:**
SLP8

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
@prabushi As per the discussion we had offline, the above issue is not reproducible with the latest master. 

This issue should have been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30530. Therefore we are closing this issue. Feel free to reopen the above issue if you have any querries.
