### ISSUE TITLE
Class cast exception when function keyword is missing in init method

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#27756]
**Description:**
When I try to build the following code,  I got class cast exception `java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference`

```
public class HelloCaller {
    private Caller caller;
    public init(Caller caller) {
        self.caller = caller;
    }
    public function send(string response) returns error? {
        return self.caller.send(response);
    }
}
public class Caller {
    function send(anydata res) returns error? {
    }
}
```

Full stackstrace,

```
[2021-01-08 22:59:58,410] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral and org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral and org.wso2.ballerinalang.compiler.tree.expressions.BLangVariableReference are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2466)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:368)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:347)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:755)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3088)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3056)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3048)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeClassDefinition(SemanticAnalyzer.java:493)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:482)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3088)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3056)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3048)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:286)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:251)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:205)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:348)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:297)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:132)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:91)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:119)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:238)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp8

**Comment by mohanvive** [comment]
I could see proper error message for the above Ballerina code in master branch. Hence, closing the issue.

```
ERROR [temp-query.bal:(3:15,3:16)] invalid token 'init'
```
