### ISSUE TITLE
FileSystemAlreadyExistsException gets thrown for Project API

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#27763]
**Description:**
When the project API gets called via concurrent invocations the following exception gets thrown.

```
2021-01-08 15:08:51.170 ERROR 1 --- [io-9000-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed  nested exception is java.lang.NullPointerException] with root cause 
 
 at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na] 
 at java.base/java.lang.Thread.run(Thread.java:834) 
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) 
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) 
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) 
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) 
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) 
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) 
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) 
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) 
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) 
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) 
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
 at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) 
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
 at io.ballerina.projects.Bootstrap.loadLangLibFromBalr(Bootstrap.java:157) 
 at io.ballerina.projects.internal.repositories.FileSystemRepository.getPackage(FileSystemRepository.java:104) 
 at io.ballerina.projects.balo.BaloProject.loadProject(BaloProject.java:43) 
 at io.ballerina.projects.internal.PackageConfigCreator.createBalrProjectConfig(PackageConfigCreator.java:78) 
 at io.ballerina.projects.internal.BaloFiles.createPackageManifest(BaloFiles.java:145) 
 at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286) 
 at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337) 
 at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102) 
java.nio.file.FileSystemAlreadyExistsException
2021-01-08 15:08:51 ERROR ActionInvocationParser:50 - Error in compiling module 
 at io.ballerina.projects.internal.environment.BallerinaDistribution.loadLangLibPackages(BallerinaDistribution.java:69) 
 at io.ballerina.projects.Bootstrap.loadLangLibSymbols(Bootstrap.java:129) 
 at io.ballerina.projects.Bootstrap.loadLangLibFromBalr(Bootstrap.java:163) 
 at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:97) 
 at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:79) 
 at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:115) 
 at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveLangLibPackage(DefaultPackageResolver.java:166) 
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) 
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

```

**Steps to reproduce:**
This may be reporduced by creating two concurrent requests to build a Ballerina project.

**Affected Versions:**
Ballerina SLP8

**OS, DB, other environment details and versions:**
This was tested in a docker container which was built using alpine:3.12 and openjdk11

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by miyurud** [comment]
Reopening this issue since it still exists with [Ballerina Swan Lake Preview 8.1](http://dist-dev.ballerina.io/downloads/swan-lake-preview8.1/ballerina-swan-lake-preview8.1.zip). The exception stack trace observed is as follows.

```
java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at io.ballerina.projects.internal.BaloFiles.createManifest(BaloFiles.java:154)
	at io.ballerina.projects.internal.BaloFiles.createPackageManifest(BaloFiles.java:146)
	at io.ballerina.projects.internal.PackageConfigCreator.createBalrProjectConfig(PackageConfigCreator.java:78)
	at io.ballerina.projects.balo.BaloProject.loadProject(BaloProject.java:43)
	at io.ballerina.projects.internal.repositories.FileSystemRepository.getPackage(FileSystemRepository.java:104)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveLangLibPackage(DefaultPackageResolver.java:166)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:115)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:79)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:97)
	at io.ballerina.projects.Bootstrap.loadLangLibFromBalr(Bootstrap.java:163)
	at io.ballerina.projects.Bootstrap.loadLangLibFromBalr(Bootstrap.java:157)
	at io.ballerina.projects.Bootstrap.loadLangLibSymbols(Bootstrap.java:134)
	at io.ballerina.projects.internal.environment.BallerinaDistribution.loadLangLibPackages(BallerinaDistribution.java:69)
	at io.ballerina.projects.environment.EnvironmentBuilder.build(EnvironmentBuilder.java:96)
	at io.ballerina.projects.environment.EnvironmentBuilder.buildDefault(EnvironmentBuilder.java:50)
	at io.ballerina.projects.ProjectEnvironmentBuilder.getDefaultBuilder(ProjectEnvironmentBuilder.java:49)
	at io.ballerina.projects.directory.BuildProject.load(BuildProject.java:75)
	at io.ballerina.projects.directory.BuildProject.load(BuildProject.java:68)
	at controller.ballerina.parser.ActionInvocationParser.getServiceNameList(ActionInvocationParser.java:48)
	at controller.ProgramAnalyzerController.analyzePerf(ProgramAnalyzerController.java:102)
	at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
