### ISSUE TITLE
Enable testIncompleteListenerDecl

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#27778]
**Description:**
Disabled the above test temporarily to fix it

**Comment by lochana-chathura** [comment]
stacktrace for the `testIncompleteListenerDecl` with alpha 1.
</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
java.lang.IllegalStateException: defaultable-parameter
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.getNextRuleForSemicolon(BallerinaParserErrorHandler.java:4396)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.getNextRule(BallerinaParserErrorHandler.java:2552)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:386)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1246)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1246)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1246)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:380)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1246)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:380)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1246)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1872)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1235)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1872)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1235)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:181)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:102)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:106)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseParameter(BallerinaParser.java:2017)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseParamList(BallerinaParser.java:1864)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncSignature(BallerinaParser.java:1489)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionTypeDesc(BallerinaParser.java:10218)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2372)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2237)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2230)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2224)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2210)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseListenerDeclaration(BallerinaParser.java:7404)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:783)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:760)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:316)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:249)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:153)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:98)
	at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerina.projects.DocumentContext.parse(DocumentContext.java:86)
	at io.ballerina.projects.DocumentContext.syntaxTree(DocumentContext.java:90)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:127)
	at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:121)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:171)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:160)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:229)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:146)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:70)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:77)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:201)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:194)
	at io.ballerina.projects.Package.getCompilation(Package.java:124)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```
</details>
