### ISSUE TITLE
Method too large exception when module contains large no of string constants

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#27822]
**Description:**
Following exception can be observed

    org.objectweb.asm.MethodTooLargeException: Method too large: $_string_constants.$string_init0 ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:447)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmBStringConstantsGen.generateConstantInit(JvmBStringConstantsGen.java:112)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:441)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:89)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:67)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:240)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:372)
        at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:301)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:131)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:117)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:93)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:126)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:92)
        at org.ballerinalang.test.BCompileUtil.jBallerinaBackend(BCompileUtil.java:114)
        at org.ballerinalang.test.BCompileUtil.compile(BCompileUtil.java:63)
        at org.ballerinalang.test.jvm.CodegenErrorsTest.testTooLargeStringConstants(CodegenErrorsTest.java:60)

**Comment by warunalakshitha** [comment]
This occurs when a given module has strings more than 5000 due to method size limit in Java.
