### ISSUE TITLE
Bad Sad error when the BALLERINA_STAGE_CENTRAL flag is enabled

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#27837]
**Description:**
The following bad sad error is seen when building a ballerina project after enabling the `BALLERINA_STAGE_CENTRAL` environment variable.

```
[2021-01-13 12:26:12,055] SEVERE {b7a.log.crash} - java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at org.ballerinalang.central.client.CentralAPIClient.getPackageVersions(CentralAPIClient.java:196)
	at io.ballerina.projects.internal.repositories.RemotePackageRepository.getPackageVersions(RemotePackageRepository.java:115)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:134)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:79)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:237)
	at io.ballerina.projects.PackageResolution.getDependencyGraphWithPackageDescriptors(PackageResolution.java:197)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:132)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:59)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:66)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:174)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:80)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:167)
	at io.ballerina.projects.Package.getCompilation(Package.java:117)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:238)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 20 more
```
**Steps to reproduce:**
```sh
$ ballerina new testProj
```
```sh
$ export BALLERINA_STAGE_CENTRAL=true
```
```sh
$ cd testProj
$ ballerina build
```

**Affected Versions:**
SLP8

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
@IrushiL This should get fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28638

**Comment by hemikak** [comment]
Closing this as its fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28638. This issue was related to the client. Hence this fix will be available in Swan Lake alpha2 release and onwards.

Please reopen if issue exists.
