### ISSUE TITLE
Compiler crashes for inclusion in `readonly` class

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#27845]
**Description:**
$title

FTM produce a bad sad.

**Comment by MaryamZi** [comment]
The currently commented out `testComplexIntersectionsInUnions` test in `test_intersection_type.bal`, fails due to this after changes from `readonly` to `final` for object fields.

```ballerina
type IntermediateInboundHandler object {
    int allow;
};

readonly class InboundHandlerImpl {
    *IntermediateInboundHandler;

    public function init(int allow) {
        self.allow = allow;
    }
}
```

```log
[2021-01-18 19:47:19,840] SEVERE {b7a.log.crash} - null 
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.markFieldsAsImmutable(ImmutableTypeCloner.java:126)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.setReadOnlynessOfClassDef(SymbolEnter.java:2365)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.validateFieldsAndSetReadOnlyType(SymbolEnter.java:2267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineUndefinedReadOnlyTypes(SymbolEnter.java:2226)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:395)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:297)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:259)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:252)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:342)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:301)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:133)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:123)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
