### ISSUE TITLE
SyntaxTreeMapGenerator returns empty object due to nullpointerexception thrown by valuetype being null

### ISSUE THREAD

**Issue by SumayyaZiyad** [ballerina-platform/ballerina-lang#27883]
**Description:**
The $subject happens when you try to retrieve the syntax tree object of the following completion test of the langserver.

```ballerina
import ballerina/module1;

public type TEST_TYPE 

function testFunction1() 

function testFunction() {
}
```

Exception is thrown when the testFunction1 node is being processed.

**Stacktrace:**

```
Operation 'ballerinaDocument/syntaxTree' failed! {uri: '/ballerina-lang/language-server/modules/langserver-core/src/test/resources/completion/new/type_def/source/source1.bal', error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.types.BLangValueType.accept(BLangValueType.java:57)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:935)
	at org.wso2.ballerinalang.compiler.tree.types.BLangValueType.accept(BLangValueType.java:57)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:226)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:989)
	at org.wso2.ballerinalang.compiler.tree.types.BLangFunctionTypeNode.accept(BLangFunctionTypeNode.java:69)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:226)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:299)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:110)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookup(SymbolFinder.java:203)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:129)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:127)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:336)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.apply(SimpleNameReferenceNode.java:46)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:341)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:77)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:192)
	at io.ballerina.compiler.syntax.tree.RequiredParameterNode.apply(RequiredParameterNode.java:55)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:341)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:73)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:476)
	at io.ballerina.compiler.syntax.tree.FunctionSignatureNode.apply(FunctionSignatureNode.java:59)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:341)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:77)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:472)
	at io.ballerina.compiler.syntax.tree.FunctionTypeDescriptorNode.apply(FunctionTypeDescriptorNode.java:54)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:341)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:77)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:60)
	at io.ballerina.compiler.syntax.tree.TypeDefinitionNode.apply(TypeDefinitionNode.java:67)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:341)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:73)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:54)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:44)
	at org.ballerinalang.diagramutil.DiagramUtil.getSyntaxTreeJSON(DiagramUtil.java:51)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentServiceImpl.syntaxTree(BallerinaDocumentServiceImpl.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
Call the syntaxTree method of the langserver extension for the above test.

**Comment by SumayyaZiyad** [comment]
Resolved from slapha2 onwards.
