### ISSUE TITLE
NPE in `JvmObservabilityGen` with bound method access with remote method

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27917]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
service class Foo {
    remote function bar() {
        
    }
}

public function main() {
    Foo foo = new;
    any x = foo.bar;
}
```

```log
[2021-01-18 15:33:38,383] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.generatePositionId(JvmObservabilityGen.java:980)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.injectStartCallableObservationCall(JvmObservabilityGen.java:715)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.rewriteObservableFunctionInvocations(JvmObservabilityGen.java:577)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.instrumentPackage(JvmObservabilityGen.java:143)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:78)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:67)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:245)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:372)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:301)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:135)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:121)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:127)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:154)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slp9-SNAPSHOT

**Comment by MaryamZi** [comment]
This should have resulted in a compilation error (https://github.com/ballerina-platform/ballerina-lang/issues/37362).
