### ISSUE TITLE
Crash with Unicode identifiers

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28269]
I got this:

```
C:\Users\jjc>bal build demo2.bal

Compiling source
        demo2.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

[demo2.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/5891267/demo2.bal.txt)

**Comment by jclark** [comment]
Unicode identifiers don't seem to work at all. I get a parse error from this (this is an identifier consisting of character 0xE01):

```

import ballerina/io;

int ก = 1;

function main() {
  io:println(ก);
}
```

**Comment by jclark** [comment]
Seems to be a problem only when the first character of the identifier is Unicode.

Also happens with Unicode escapes e.g. `\u{E01}`.

**Comment by lochana-chathura** [comment]
</details>
<details>
  <summary><b>internal-log</b>  (<i>click to expand</i>)</summary>

```
[2021-02-18 11:20:40,750] SEVERE {b7a.log.crash} - class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypeDescriptorNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.TypeDescriptorNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypeDescriptorNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.TypeDescriptorNode are in unnamed module of loader 'app')
	at io.ballerina.compiler.syntax.tree.ParenthesisedTypeDescriptorNode.typedesc(ParenthesisedTypeDescriptorNode.java:40)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:939)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.ParenthesisedTypeDescriptorNode.apply(ParenthesisedTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5052)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2743)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2700)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4572)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1483)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1391)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1371)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1349)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:569)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:492)
```
</details>

**Comment by lochana-chathura** [comment]
> Seems to be a problem only when the first character of the identifier is Unicode.
> 
> Also happens with Unicode escapes e.g. `\u{E01}`.

This is fixed with the linked PR. 
Still, the compiler should not crash when an invalid identifier is used. Created a separate issue for that.  #28755
