### ISSUE TITLE
XML literals do not handle CDATA sections

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28309]
If I do this in the shell:

```
xml`<![CDATA[<hello>]]>`
```

I get an error

```
Tree parsing failed: null
```

**Comment by kdsuneraavinash** [comment]
I think this behavior is because it causes a bad sad error is parser as will.
The compiler bad sad error message seems to null, which is reported by the shell.

```
public function main() {
    xml x = xml`<![CDATA[<hello>]]>`;
}
```

This produces a bad sad error,
```
[2021-01-31 12:45:24,512] SEVERE {b7a.log.crash} - null 
java.lang.IllegalStateException
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLCharacterSet(XMLParser.java:631)
	at io.ballerina.compiler.internal.parser.XMLParser.parseAttributeValue(XMLParser.java:403)
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLAttribute(XMLParser.java:365)
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLElementStartOrEmptyTag(XMLParser.java:178)
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLElement(XMLParser.java:146)
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLContentItem(XMLParser.java:108)
	at io.ballerina.compiler.internal.parser.XMLParser.parseXMLContent(XMLParser.java:63)
	at io.ballerina.compiler.internal.parser.XMLParser.parse(XMLParser.java:47)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTemplateContentAsXML(BallerinaParser.java:10036)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseXMLTemplateExpression(BallerinaParser.java:9987)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4539)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4466)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4460)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4441)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4436)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4431)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseActionOrExpression(BallerinaParser.java:4372)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseVarDeclRhs(BallerinaParser.java:4154)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypedBPOrExprRhs(BallerinaParser.java:13945)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypeOrExpr(BallerinaParser.java:13938)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4046)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3923)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:3904)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2602)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2565)
	at io.ballerina.compiler.internal.parser.BallerinaParser.createFunctionDefinition(BallerinaParser.java:1230)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrMethodDeclEnd(BallerinaParser.java:1141)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1112)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1099)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:775)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:760)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:316)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:249)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:153)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:98)
	at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerina.projects.DocumentContext.parse(DocumentContext.java:86)
	at io.ballerina.projects.DocumentContext.syntaxTree(DocumentContext.java:90)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:127)
	at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:121)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:171)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:160)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:229)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:146)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:70)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:77)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:201)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:194)
	at io.ballerina.projects.Package.getCompilation(Package.java:124)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```
