### ISSUE TITLE
Test case cannot depend on a function with a data provider config

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#28358]
**Description:**

Test case cannot depend on a function with a data provider config as in below sample code.
We need to wait for any function implementation (#27742) to fix this bug if we are to support function pointers for depends on config.

**Steps to reproduce:**

See below implementation.

```
import ballerina/io;
import ballerina/test;

function stringDataProvider() returns (string[][]) {
    return [["1", "2", "3"], ["10", "20", "30"], ["5", "6", "11"]];
}

@test:Config {dataProvider: stringDataProvider}
function testAddingValues(string fValue, string sValue, string result) {
    int|error val1 = 'int:fromString(fValue);
    int value1 = val1 is int ? val1 : 0;
    int|error val2 = 'int:fromString(sValue);
    int value2 = val2 is int ? val2 : 0;
    int|error res1 = 'int:fromString(result);
    int result1 = res1 is int ? res1 : 0;
    io:println("Input : [" + fValue + "," + sValue + "," + result + "]");
    test:assertEquals(value1 + value2, result1, msg = "Incorrect Sum");
}

@test:Config {dependsOn: [testAddingValues]}
function testAddingValuesDependant() {
    io:println("I'm in test function 1!");
    test:assertTrue(true, msg = "Failed!");
}
```

This throws the below compilation error.

`incompatible types: expected 'function () returns ((any|error))', found 'function (string,string,string) returns ()'
`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
This issue arises because of the change to the `TestConfig` for function pointers.

```
public type TestConfig record {
    (function() returns (any|error))[] dependsOn?;
};
```

Depends on expects `'function () returns ((any|error))'`

**Comment by Dilhasha** [comment]
> This issue arises because of the change to the `TestConfig` for function pointers.
> 
> ```
> public type TestConfig record {
>     (function() returns (any|error))[] dependsOn?;
> };
> ```
> 
> Depends on expects `'function () returns ((any|error))'`

Yes, that's why we need to wait for https://github.com/ballerina-platform/ballerina-lang/issues/27742 to fix this.

**Comment by Ibaqu** [comment]
Changing the dependsOn type to `function` causes the following bad-sad to occur. 

```
[2021-04-01 20:22:42,589] SEVERE {b7a.log.crash} - error("java.lang.NullPointerException") 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: error("java.lang.NullPointerException")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:553)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:264)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:114)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:116)
	at org.ballerinalang.test.runtime.Main.main(Main.java:97)
Caused by: error("java.lang.NullPointerException")
	at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:127)
	at io.ballerina.runtime.internal.ErrorUtils.createInteropError(ErrorUtils.java:78)
	at ballerina.lang$0046value.1_0_0.value.cloneReadOnly(value.bal:53)
	at mohamedaquibzulfikar.Logging.0_1_0.tests.main_test.$annot_func$_2(tests/main_test.bal:14)
	at mohamedaquibzulfikar.Logging.0_1_0.Logging.$gen$$0046$0060testinit$0062(Logging:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Fails at the BTestRunner.startSuite() function when the testInit function is invoked.

**Comment by Ibaqu** [comment]
`function[] dependsOn = []` can be used in the annotation when the Function type array is sorted out #29795. 

As mentioned, the issue resides in the hashCode function of BFunctionType. 

the following is a temporary workaround to affirm that the `dependsOn` feature works with the change in the annotation

runtime.internal.types.BFunctionType.java 
```java
 @Override
    public int hashCode() {
        int result = super.hashCode();
        if (SymbolFlags.isFlagOn(this.flags, SymbolFlags.ANY_FUNCTION)) {
            return result;
        }
        result = 31 * result + Arrays.hashCode(paramTypes);
        result = 31 * result + retType.hashCode();

        return result;
    }
    
```

**Comment by azinneera** [comment]
Blocked on #27742
