### ISSUE TITLE
[Testerina] Function mocking throws NullPointer when used to initialize global values

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#28410]
**Description:**

NPE is thrown when function mocking is used to initialize global values

A temporary workaround would be to move the initialization inside another function

```
[2021-02-03 10:54:50,394] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: java.lang.NullPointerException
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:543)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:264)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:115)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:75)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:70)
	at org.ballerinalang.test.runtime.Main.main(Main.java:54)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@Ibaqu / @sachiniSam 
Can you please point me to a sample code block where this issue is reproduced?

**Comment by Ibaqu** [comment]
@Dilhasha The scenario is similar to the following code block. 

Main.bal

```
string configValue = initConfig();

function initConfig() returns (string) {
    return "Hello World";
}
```

main_test.bal

```
@test:Mock {
    functionName: "initConfig"
}
test:MockFunction mock_init = new();

@test:Config {}
function test1() {
    test:when(mock_init).thenReturn("mocked_value"); //This doesnt execute for the global var initialization
    
    test:assertEquals(configValue, "mocked_value");
}
```

The issue arises due to a limitation in the way we mock functions. A mock function object needs to be initialized with a value using `thenReturn` or `call`. The global variable in this case cannot be mocked as the test function `test1` does not run before `configValue` is initialized. 

Its due to this limitation that I have a PR for the old implementation as well, as this restriction doesnt apply in the old function mocking implementation
