### ISSUE TITLE
Suggestions are not showing for some modules

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#28431]
**Description:**
$subject for some standard library modules. When tried to import `ballerina/time` and click cmd + space bar, no suggestions are shown. But suggestions are shown for `ballerina/io` module. Refer below for more details.

![Screen-Recording-2021-01-30-at-1](https://user-images.githubusercontent.com/16300038/106313800-ca123100-628e-11eb-9972-e654cfd6ac5e.gif)

Error in Logs:

```[Error - 11:45:45 PM] Operation 'text/completion' failed! {uri: '/Volumes/work/Ballerina/TestBallerina/temp/test.bal', [3:10], error: 'class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:154)
	at io.ballerina.compiler.api.impl.symbols.BallerinaModule.allSymbols(BallerinaModule.java:191)
	at org.ballerinalang.langserver.common.utils.completion.QNameReferenceUtil.lambda$getModuleContent$2(QNameReferenceUtil.java:86)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.ballerinalang.langserver.common.utils.completion.QNameReferenceUtil.getModuleContent(QNameReferenceUtil.java:86)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getCompletions(BlockNodeContextProvider.java:81)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:45)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:36)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.providers.context.TypedBindingPatternNodeContext.getCompletions(TypedBindingPatternNodeContext.java:47)
	at org.ballerinalang.langserver.completions.providers.context.TypedBindingPatternNodeContext.getCompletions(TypedBindingPatternNodeContext.java:33)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:134)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)```


**Affected Product Version:**

Swan Lake Alpha1

**Comment by nadeeshaan** [comment]
This issue has been resolved in latest master. Hence closing the issue
