### ISSUE TITLE
Bad-Sad error when function is accessed using field access within the init method of same class

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28457]
**Description:**
```ballerina
class A {
    function foo(int i) returns int {
        return i+1;
    }

    function (int i) returns int bar;

    function init() {
        self.bar = self.foo;
    }

    // This works
    function baz() returns function (int) returns int {
        self.bar = self.foo;
        return self.bar;
    }
}

public function main() {
    A a = new A();
    var x = a.baz();
    panic error(x(1).toString());
}
```

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5931625/ballerina-internal.log)
**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
<details>
  <summary><b>ballerina-internal.log</b>  (<i>click to expand</i>)</summary>

```
[2021-04-06 20:01:44,732] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    $value$A.init(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @243: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$A'
  Current Frame:
    bci: @243
    flags: { }
    locals: { '$value$A', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$A', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 4d01 4e01
    0000010: 3a04 013a 0501 3a06 013a 0701 3a08 013a
    0000020: 0903 360a 2bb4 001d 9d00 e915 0aab 0000
    0000030: 0000 012d 0000 0004 0000 0000 0000 002b
    0000040: 0000 0001 0000 00cc 0000 0002 0000 00d4
    0000050: 0000 0003 0000 00dc 1100 0036 0abb 0040
    0000060: 59bb 0042 59b2 0048 03b7 004b 1000 bd00
    0000070: 4db7 0050 4e2d 2b14 0051 88bd 0054 b900
    0000080: 5a03 003a 0419 04c0 004d 4d2a 3a05 b200
    0000090: 603a 062c 1906 1905 b800 66bb 0068 592c
    00000a0: ba00 e100 00bb 007e 5914 001e 88bd 0080
    00000b0: 5914 0051 88b2 0084 5301 b200 8414 0085
    00000c0: b700 8901 03b7 008c 59b2 0092 12e3 b800
    00000d0: 9a3a 07b2 0060 3a06 2cc0 004d 1906 b900
    00000e0: 9d02 00c0 0007 3a08 b200 a03a 0619 0819
    00000f0: 0619 07b7 00e6 013a 0911 0001 360a a700
    0000100: 0b11 0002 360a a700 0311 0003 360a 1909
    0000110: b02b b400 232b 59b4 001d 0464 5ab5 001d
    0000120: 32c0 00e8 59b4 00e9 3a09 59b4 00ea 4d59
    0000130: b400 eb4e 59b4 00ec 3a04 59b4 00ed 3a05
    0000140: 59b4 00ee 3a06 59b4 00ef 3a07 59b4 00f0
    0000150: 3a08 b400 f136 0aa7 fed4 bb00 e859 b700
    0000160: f259 1909 b500 e959 2cb5 00ea 592d c000
    0000170: 56b5 00eb 5919 04b5 00ec 5919 05b5 00ed
    0000180: 5919 06b5 00ee 5919 07b5 00ef 5919 08b5
    0000190: 00f0 5915 0ab5 00f1 3a0c 2bb4 0023 2b59
    00001a0: b400 1d5a 0460 b500 1d19 0c53 1909 b0  
  Stackmap Table:
    same_frame(@11)
    full_frame(@43,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    same_frame(@88)
    full_frame(@249,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@257,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@265,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@273,{Object[#3],Object[#15],Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@346,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    $value$A.init(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @243: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$A'
  Current Frame:
    bci: @243
    flags: { }
    locals: { '$value$A', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$A', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 4d01 4e01
    0000010: 3a04 013a 0501 3a06 013a 0701 3a08 013a
    0000020: 0903 360a 2bb4 001d 9d00 e915 0aab 0000
    0000030: 0000 012d 0000 0004 0000 0000 0000 002b
    0000040: 0000 0001 0000 00cc 0000 0002 0000 00d4
    0000050: 0000 0003 0000 00dc 1100 0036 0abb 0040
    0000060: 59bb 0042 59b2 0048 03b7 004b 1000 bd00
    0000070: 4db7 0050 4e2d 2b14 0051 88bd 0054 b900
    0000080: 5a03 003a 0419 04c0 004d 4d2a 3a05 b200
    0000090: 603a 062c 1906 1905 b800 66bb 0068 592c
    00000a0: ba00 e100 00bb 007e 5914 001e 88bd 0080
    00000b0: 5914 0051 88b2 0084 5301 b200 8414 0085
    00000c0: b700 8901 03b7 008c 59b2 0092 12e3 b800
    00000d0: 9a3a 07b2 0060 3a06 2cc0 004d 1906 b900
    00000e0: 9d02 00c0 0007 3a08 b200 a03a 0619 0819
    00000f0: 0619 07b7 00e6 013a 0911 0001 360a a700
    0000100: 0b11 0002 360a a700 0311 0003 360a 1909
    0000110: b02b b400 232b 59b4 001d 0464 5ab5 001d
    0000120: 32c0 00e8 59b4 00e9 3a09 59b4 00ea 4d59
    0000130: b400 eb4e 59b4 00ec 3a04 59b4 00ed 3a05
    0000140: 59b4 00ee 3a06 59b4 00ef 3a07 59b4 00f0
    0000150: 3a08 b400 f136 0aa7 fed4 bb00 e859 b700
    0000160: f259 1909 b500 e959 2cb5 00ea 592d c000
    0000170: 56b5 00eb 5919 04b5 00ec 5919 05b5 00ed
    0000180: 5919 06b5 00ee 5919 07b5 00ef 5919 08b5
    0000190: 00f0 5915 0ab5 00f1 3a0c 2bb4 0023 2b59
    00001a0: b400 1d5a 0460 b500 1d19 0c53 1909 b0  
  Stackmap Table:
    same_frame(@11)
    full_frame(@43,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    same_frame(@88)
    full_frame(@249,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@257,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@265,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@273,{Object[#3],Object[#15],Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@346,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})

	at test.main(test.bal:20)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2021-04-06 20:01:44,749] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    $value$A.init(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @243: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$A'
  Current Frame:
    bci: @243
    flags: { }
    locals: { '$value$A', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$A', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 4d01 4e01
    0000010: 3a04 013a 0501 3a06 013a 0701 3a08 013a
    0000020: 0903 360a 2bb4 001d 9d00 e915 0aab 0000
    0000030: 0000 012d 0000 0004 0000 0000 0000 002b
    0000040: 0000 0001 0000 00cc 0000 0002 0000 00d4
    0000050: 0000 0003 0000 00dc 1100 0036 0abb 0040
    0000060: 59bb 0042 59b2 0048 03b7 004b 1000 bd00
    0000070: 4db7 0050 4e2d 2b14 0051 88bd 0054 b900
    0000080: 5a03 003a 0419 04c0 004d 4d2a 3a05 b200
    0000090: 603a 062c 1906 1905 b800 66bb 0068 592c
    00000a0: ba00 e100 00bb 007e 5914 001e 88bd 0080
    00000b0: 5914 0051 88b2 0084 5301 b200 8414 0085
    00000c0: b700 8901 03b7 008c 59b2 0092 12e3 b800
    00000d0: 9a3a 07b2 0060 3a06 2cc0 004d 1906 b900
    00000e0: 9d02 00c0 0007 3a08 b200 a03a 0619 0819
    00000f0: 0619 07b7 00e6 013a 0911 0001 360a a700
    0000100: 0b11 0002 360a a700 0311 0003 360a 1909
    0000110: b02b b400 232b 59b4 001d 0464 5ab5 001d
    0000120: 32c0 00e8 59b4 00e9 3a09 59b4 00ea 4d59
    0000130: b400 eb4e 59b4 00ec 3a04 59b4 00ed 3a05
    0000140: 59b4 00ee 3a06 59b4 00ef 3a07 59b4 00f0
    0000150: 3a08 b400 f136 0aa7 fed4 bb00 e859 b700
    0000160: f259 1909 b500 e959 2cb5 00ea 592d c000
    0000170: 56b5 00eb 5919 04b5 00ec 5919 05b5 00ed
    0000180: 5919 06b5 00ee 5919 07b5 00ef 5919 08b5
    0000190: 00f0 5915 0ab5 00f1 3a0c 2bb4 0023 2b59
    00001a0: b400 1d5a 0460 b500 1d19 0c53 1909 b0  
  Stackmap Table:
    same_frame(@11)
    full_frame(@43,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    same_frame(@88)
    full_frame(@249,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@257,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@265,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@273,{Object[#3],Object[#15],Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@346,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    $value$A.init(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @243: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$A'
  Current Frame:
    bci: @243
    flags: { }
    locals: { '$value$A', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$A', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/FPValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 4d01 4e01
    0000010: 3a04 013a 0501 3a06 013a 0701 3a08 013a
    0000020: 0903 360a 2bb4 001d 9d00 e915 0aab 0000
    0000030: 0000 012d 0000 0004 0000 0000 0000 002b
    0000040: 0000 0001 0000 00cc 0000 0002 0000 00d4
    0000050: 0000 0003 0000 00dc 1100 0036 0abb 0040
    0000060: 59bb 0042 59b2 0048 03b7 004b 1000 bd00
    0000070: 4db7 0050 4e2d 2b14 0051 88bd 0054 b900
    0000080: 5a03 003a 0419 04c0 004d 4d2a 3a05 b200
    0000090: 603a 062c 1906 1905 b800 66bb 0068 592c
    00000a0: ba00 e100 00bb 007e 5914 001e 88bd 0080
    00000b0: 5914 0051 88b2 0084 5301 b200 8414 0085
    00000c0: b700 8901 03b7 008c 59b2 0092 12e3 b800
    00000d0: 9a3a 07b2 0060 3a06 2cc0 004d 1906 b900
    00000e0: 9d02 00c0 0007 3a08 b200 a03a 0619 0819
    00000f0: 0619 07b7 00e6 013a 0911 0001 360a a700
    0000100: 0b11 0002 360a a700 0311 0003 360a 1909
    0000110: b02b b400 232b 59b4 001d 0464 5ab5 001d
    0000120: 32c0 00e8 59b4 00e9 3a09 59b4 00ea 4d59
    0000130: b400 eb4e 59b4 00ec 3a04 59b4 00ed 3a05
    0000140: 59b4 00ee 3a06 59b4 00ef 3a07 59b4 00f0
    0000150: 3a08 b400 f136 0aa7 fed4 bb00 e859 b700
    0000160: f259 1909 b500 e959 2cb5 00ea 592d c000
    0000170: 56b5 00eb 5919 04b5 00ec 5919 05b5 00ed
    0000180: 5919 06b5 00ee 5919 07b5 00ef 5919 08b5
    0000190: 00f0 5915 0ab5 00f1 3a0c 2bb4 0023 2b59
    00001a0: b400 1d5a 0460 b500 1d19 0c53 1909 b0  
  Stackmap Table:
    same_frame(@11)
    full_frame(@43,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    same_frame(@88)
    full_frame(@249,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@257,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@265,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#200],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})
    full_frame(@273,{Object[#3],Object[#15],Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@346,{Object[#3],Object[#15],Object[#77],Object[#86],Object[#77],Object[#200],Object[#202],Object[#104],Object[#7],Object[#200],Integer},{})

	at test.main(test.bal:20)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

**Comment by rdulmina** [comment]
Simplified code
```bal
class A {
    function foo() {
    }

    function () bar;

    function init() {
        self.bar = self.foo;
    }

    function baz() {
        self.bar = self.foo;
    }
}

public function main() {
    A a = new A();
    // a.baz();
}
```
