### ISSUE TITLE
Compiler crashes for function type variable initialization in module level

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#28499]
**Description:**
$title

**Steps to reproduce:**
```ballerina
(function() returns string)? a;

public function main() {
    
}
```
```
[2021-02-08 18:31:10,641] SEVERE {b7a.log.crash} - class io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.createFunctionSymbol(SymbolFactory.java:208)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:121)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.convertDiagArgsToProps(BLangDiagnosticLog.java:235)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:216)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:99)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.checkForUninitializedGlobalVars(DataflowAnalyzer.java:352)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:308)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1763)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:286)
	at io.ballerina.projects.internal.CompilerPhaseRunner.dataflowAnalyze(CompilerPhaseRunner.java:229)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:125)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:373)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:326)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:135)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:248)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slalpha1

**Comment by lasinicl** [comment]
Results in the expected errors on Swan Lake 2201.0.0.
```ballerina
(function() returns string)? a; // uninitialized variable 'a'
```
Added tests in 35320.

**Comment by MaryamZi** [comment]
Tests added in https://github.com/ballerina-platform/ballerina-lang/pull/35320.
