### ISSUE TITLE
Suggestions on array variables are not shown

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28583]
**Description:**
Check the image below. No suggestion given.

<img width="463" alt="Screen Shot 2021-02-11 at 3 10 17 PM" src="https://user-images.githubusercontent.com/690559/107621601-85b66600-6c7c-11eb-8115-f7a4fbe02153.png">

Error at VSCode output

```
[Error - 3:10:15 PM] Operation 'text/completion' failed! {uri: '/Users/kishanthan/WSO2/work/dist/ballerina/projects/myproj1/main.bal', [11:10], error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.containsTwoElements(BallerinaUnionTypeSymbol.java:161)
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.getSignatureForUnion(BallerinaUnionTypeSymbol.java:124)
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.signature(BallerinaUnionTypeSymbol.java:95)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.getFuncArguments(FunctionCompletionItemBuilder.java:271)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.setMeta(FunctionCompletionItemBuilder.java:140)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.build(FunctionCompletionItemBuilder.java:89)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.populateBallerinaFunctionCompletionItem(AbstractCompletionProvider.java:365)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:155)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:150)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getCompletionsForTypeDesc(FieldAccessContext.java:264)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getEntries(FieldAccessContext.java:78)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:42)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:32)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:134)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjana** [comment]
@Kishanthan could you please share a full code snippet that was used for testing?

**Comment by MaryamZi** [comment]
Observed similar behaviour with
```ballerina
int[] arr = [];

isolated function push(int i) {
    arr.<cursor>
}
```

```log
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.containsTwoElements(BallerinaUnionTypeSymbol.java:162)
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.getSignatureForUnion(BallerinaUnionTypeSymbol.java:125)
	at io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol.signature(BallerinaUnionTypeSymbol.java:96)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getModifiedTypeName(CommonUtil.java:923)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.getFuncArguments(FunctionCompletionItemBuilder.java:272)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.setMeta(FunctionCompletionItemBuilder.java:141)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.build(FunctionCompletionItemBuilder.java:90)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.populateBallerinaFunctionCompletionItem(AbstractCompletionProvider.java:328)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:148)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:143)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getCompletionsForTypeDesc(FieldAccessContext.java:272)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getEntries(FieldAccessContext.java:82)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:42)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:32)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nadeeshaan** [comment]
Similar case 
```
function sum(float[] arr) returns float {
    float r = 0.0;
    foreach float x in arr {
        r += x;
    }
    foreach int i in 0 ..< arr.<cursor> {
        
    }
    return r;
}
```
