### ISSUE TITLE
Suggestions are not working when having imports with quoted values

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28604]
**Description:**
Suggestions are not working when I have an import like `import ballerina/lang.'array;`. Check the below image.
<img width="376" alt="Screen Shot 2021-02-12 at 1 56 10 AM" src="https://user-images.githubusercontent.com/690559/107694945-f50c7400-6cd5-11eb-8c5f-13e91afca3e4.png">

Error at VSCode ballerina output console.

```
[Error - 1:56:05 AM] Operation 'text/completion' failed! {uri: '/Users/kishanthan/WSO2/work/dist/ballerina/projects/myproj1/main.bal', [3:4], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getModuleCompletionItems$2(AbstractCompletionProvider.java:256)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getModuleCompletionItems(AbstractCompletionProvider.java:267)
	at org.ballerinalang.langserver.completions.providers.context.ModulePartNodeContext.getCompletions(ModulePartNodeContext.java:70)
	at org.ballerinalang.langserver.completions.providers.context.ModulePartNodeContext.getCompletions(ModulePartNodeContext.java:36)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:134)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed with #28405. Hence closing the issue
