### ISSUE TITLE
Bad, sad error when trying to use 'handle' type for static 'FieldSet'

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#28605]
**Description:**
Getting Bad, sad error when attempting to set value to a Java Integer Field by using Ballerina 'handle' type.

**Steps to reproduce:**
```java
package javalibs.app;
public class IntegerApp {
    public static Integer setInt;
}
```
```Ballerina
public function main() {
    handle h = fromInteger(5);
    setInt(h);
}
function setInt(handle arg) = @java:FieldSet {
    name: "setInt",
    'class: "javalibs.app.IntApp"
} external;
function fromInteger(int val) returns handle = @java:Constructor {
    'class:"java.lang.Integer",
    paramTypes:["int"]
} external;
```
Bad, sad error:
```
[2021-02-12 12:19:54,828] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    gabilan/testFields/0_1_0/main.setInt(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/HandleValue;Z)Ljava/lang/Object; @4: putstatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/HandleValue', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2bb6 00b5 b300 b901 4e2d b0            
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    gabilan/testFields/0_1_0/main.setInt(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/HandleValue;Z)Ljava/lang/Object; @4: putstatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/HandleValue', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2bb6 00b5 b300 b901 4e2d b0            

	at gabilan.testFields.0_1_0.$_init.$lambda$main$(testFields)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
slp5, slp7, alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Type/Bug, Team/jBallerina

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
This issue has been solved. No such problem comes with Ballerina Swan Lake Beta 3 snapshot.

**Comment by warunalakshitha** [comment]
Closing the issue as per the above comment.
