### ISSUE TITLE
Error variable with additional named arg gives runtime error

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#28655]
**Description:**
Consider the bellow code
```bal
type VarTestErrorDetail record {
    [int] fieldA?;
};

type VarTestError error<VarTestErrorDetail>;

public function main() {
VarTestError error(m, fieldD = {a: varB}) = error VarTestError("message");
}
```
gives null pointer at runtime

```
[2021-02-16 10:47:05,177] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at test.main(test.bal:12)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KavinduZoysa** [comment]
In bal version `Ballerina 2201.0.0 (Swan Lake)` we are getting following error for above example.

`cannot bind undefined error detail field 'fieldD'`

**Comment by KavinduZoysa** [comment]
The current behavior is correct, therefore closing the issue.
