### ISSUE TITLE
Bad sad error when compiling following async call

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#28672]
**Description:**
Occurs after the change mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/28671

```
future<http:Response|http:ClientError> asyncInvo = start clientEP2->get("/httpClientActionBE/greeting");
```

Error:
```
[2021-02-16 19:00:48,967] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.rewriteAsyncInvocations(JvmObservabilityGen.java:286)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.instrumentPackage(JvmObservabilityGen.java:165)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:78)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generateTestModule(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:270)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:326)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:135)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:199)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)


```

**Comment by MaryamZi** [comment]
Dependently-typed functions don't seem to be working with async calls.

Both the calls in the following example fail with `error: jVM generation is not supported for async return type (int|string|error)` at the backend.
```ballerina
import ballerina/jballerina.java;

function get(int|string x, typedesc<int|string> y) returns y|error =
    @java:Method {
        'class: "org.maryam.Test",
        name: "get"
    } external;

client class Client {
    function get(int|string x, typedesc<int|string> y) returns y|error = @java:Method {
        'class: "org.maryam.Test",
        name: "clientGet"
    } external;
}

public function main() {
    future<int|error> a = start get("", int); // error: jVM generation is not supported for async return type (int|string|error)

    Client cl = new;
    future<int|error> b = start cl->get("", int); // error: jVM generation is not supported for async return type (int|string|error)
}
```

**Comment by MaryamZi** [comment]
I was able to reproduce the CCE with the following code.

```ballerina
type IntOrString int|string;

public function main() {
    Client cl = new;

    // Should result in compilation errors.
    future<int|string> d = start cl.get("", IntOrString);
    future<int|string> e = start cl->remoteGet("", IntOrString);
    future<int|string> f = start get("", IntOrString);
}

function get(int|string x, typedesc<int|string> y) returns y|error = external;

client class Client {
    function get(int|string x, typedesc<int|string> y = int) returns y|error = external;

    remote function remoteGet(int|string x, typedesc<int|string> y) returns y|error = external;
}
```

This should have resulted in compilation errors - https://github.com/ballerina-platform/ballerina-lang/issues/28749.
