### ISSUE TITLE
Bad, sad error when iterating over a table constructed for a configurable variable at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28676]
**Description:**
$title. 

Happens in the `io.ballerina.runtime.internal.TypeChecker#checkIsTableType` check at https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L1020 because `io.ballerina.runtime.internal.TypeChecker#getTableConstraintField` returns null when the constraint type is an intersection type.

May be an issue with non-configurable table values too (if it is possible that we get here and the constraint type is an intersection type). 

**Steps to reproduce:**
```ballerina
type AuthInfo record {
    readonly string username;
    string password;
    string[] scopes?;
};

configurable table<AuthInfo> key(username) & readonly users = ?;

public function main() {
    foreach var item in users {
    }
}
```

**Affected Versions:**
slalpha2

**Comment by MaryamZi** [comment]
ballerina-internal.log
```log
[2021-02-16 22:05:11,411] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at io.ballerina.runtime.internal.TypeChecker.lambda$checkIsTableType$19(TypeChecker.java:1020)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at io.ballerina.runtime.internal.TypeChecker.checkIsTableType(TypeChecker.java:1019)
	at io.ballerina.runtime.internal.TypeChecker.checkIsRecursiveType(TypeChecker.java:778)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:707)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:605)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:732)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:273)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:261)
	at ballerina.lang$0046table.0_4_0.$value$TableIterator.init(internal.bal:29)
	at ballerina.lang$0046table.0_4_0.$value$TableIterator.call(internal.bal)
	at ballerina.lang$0046table.0_4_0.$value$TableIterator.$init$(internal.bal:20)
	at ballerina.lang$0046table.0_4_0.$value$TableIterator.call(internal.bal)
	at ballerina.lang$0046table.0_4_0.table.iterator(table.bal:58)
	at test.main(test.bal:10)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HindujaB** [comment]
The table iterator works without error when we use lang.table `forEach` method. 
We can use this as a workaround until we get the proper fix. 
```ballerina
users.forEach(function(AuthInfo item) {
                      //do the required task
                      });
```
