### ISSUE TITLE
Exceptions thrown when manually typing in an import

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28677]
**Description:**
```ballerina
import ballerina/lang<cursor>
```
throws
```log
java.lang.IndexOutOfBoundsException: Index: '1', Size: '1'
	at io.ballerina.compiler.internal.syntax.NodeListUtils.rangeCheck(NodeListUtils.java:38)
	at io.ballerina.compiler.syntax.tree.SeparatedNodeList.get(SeparatedNodeList.java:45)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequest(DocumentContext.java:167)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:129)
	at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:121)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:172)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:160)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:229)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:146)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:70)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:77)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:201)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:194)
	at io.ballerina.projects.Package.getCompilation(Package.java:124)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:208)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:187)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:61)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:329)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```ballerina
import ballerina/lang.i<cursor>
```
throws
```log
java.lang.IllegalStateException: Ballerina langlib package cannot be found in Ballerina distribution: org=ballerina, name=lang.i
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.lambda$resolveLangLibPackage$0(DefaultPackageResolver.java:181)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveLangLibPackage(DefaultPackageResolver.java:179)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:115)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:79)
	at io.ballerina.projects.PackageResolution$ModuleResolver.resolvePackage(PackageResolution.java:453)
	at io.ballerina.projects.PackageResolution$ModuleResolver.resolve(PackageResolution.java:423)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:247)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:146)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:70)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:77)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:201)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:194)
	at io.ballerina.projects.Package.getCompilation(Package.java:124)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:208)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:187)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:61)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:329)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
slalpha2

**Comment by hasithaa** [comment]
@hevayo I think, project API should not panic in this situation. This is affecting the LS side.

**Comment by lochana-chathura** [comment]
`IndexOutOfBoundsException` is due to accessing the second element of the list without checking the size.
https://github.com/ballerina-platform/ballerina-lang/blob/c7980126ba082481c0e67bef763b3cfc9978141d/compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java#L168

Here we need to handle the negative scenarios.
