### ISSUE TITLE
[Testerina] Code coverage fails with nio.AccessDeniedException when having extra tests

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#28694]
**Description:**
When adding extra tests to the code coverage, the windows build fails with the following error

```
testerina-intg-test-suite > testerina-intg-tests > org.ballerinalang.testerina.test.TestReportTest > testWithCoverage STANDARD_ERROR
    Feb 17, 2021 5:37:31 AM org.ballerinalang.test.context.ServerLogReader feedAndPrint
    SEVERE: error: unable to clean the target directory: Unable to delete directory C:\Users\RUNNER~1\AppData\Local\Temp\bal-test-integration-testerina-project-17320448599123816210\project-based-tests\test-report-tests\target\report.

testerina-intg-test-suite > testerina-intg-tests > org.ballerinalang.testerina.test.TestReportTest > testWithCoverage FAILED
    java.nio.file.AccessDeniedException: C:\Users\RUNNER~1\AppData\Local\Temp\bal-test-integration-testerina-project-17320448599123816210\project-based-tests\test-report-tests\target\report\test_results.json
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
        at org.ballerinalang.testerina.test.TestReportTest.runCommand(TestReportTest.java:129)
        at org.ballerinalang.testerina.test.TestReportTest.testWithCoverage(TestReportTest.java:77)
        
```

**Steps to reproduce:**
Add the following changes removed by the commit : https://github.com/ballerina-platform/ballerina-lang/pull/28236/commits/756304ba029297ebffd19009934fa12e5d91b4ca

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@Ibaqu Shall we add what we are trying to test with these extra tests for clarity?
Also let's see whether the issue still persists because we've done some changes to the code coverage implementation now.

**Comment by Ibaqu** [comment]
The tests I attempted to add were to validate the code coverage when using the `--tests` flag for module wise execution. 
This was to make sure that multiple flags could be used in tandem with the correct results. 

Changes removed in the commit : https://github.com/ballerina-platform/ballerina-lang/commit/756304ba029297ebffd19009934fa12e5d91b4ca tests the code coverage as well as refactors the entire test case.
