### ISSUE TITLE
StringIndexOutOfBoundsException with incomplete quotes

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28739]
**Description:**
Results in the following error.

```
[Error - 10:52:15 AM] Operation 'text/didChange' failed! {uri: '/Users/prabushi/Desktop/workspace/single-file/empty.bal', error: 'begin 1, end 0, length 1'}
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleLiteral(BLangNodeTransformer.java:4952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleLiteral(BLangNodeTransformer.java:4891)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleLiteral(BLangNodeTransformer.java:4879)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:4668)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4663)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1929)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.BinaryExpressionNode.apply(BinaryExpressionNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:4692)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4663)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVar(BLangNodeTransformer.java:4803)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createSimpleVar(BLangNodeTransformer.java:4761)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1212)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.ObjectFieldNode.apply(ObjectFieldNode.java:75)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:3872)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.ClassDefinitionNode.apply(ClassDefinitionNode.java:75)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:569)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:462)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:492)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:355)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:322)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:145)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:104)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.getLatestDiagnostics(DiagnosticsHelper.java:116)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:80)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:487)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**

```
import ballerina/io;

public function main() {
    Person4 p = new;
    io:print(p.getName());
}

class Person4 {
    string name = "Alice  " Bob "
    function getName() returns string {
        return self.name;
    }
}

type ObjectName object {
    string a;
    function getName() returns string;
};

```

**Affected Versions:**
SL Alpha2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
This is a bug in NodeTransformer due to incomplete string `string name = "Alice  " Bob "`.
