### ISSUE TITLE
[LS] NPE at startup

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28744]
Get the following error in VSCode, 

```
'bal' command is picked up from the plugin.
Plugin version: 2.0.0
Ballerina version: Swan Lake Alpha 2
Using Ballerina CLI command 'bal.bat' for Language server.
[Error - 11:30:22 AM] Operation 'text/didOpen' failed! {uri: '/d%3A/test-pack/tmp.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didOpen(BallerinaWorkspaceManager.java:224)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:506)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[Error - 11:30:22 AM] Operation 'text/codeAction' failed! {uri: '/d%3A/test-pack/tmp.bal', [1:1]- [1:1], error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectPair(BallerinaWorkspaceManager.java:433)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:156)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.syntaxTree(BallerinaWorkspaceManager.java:168)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:58)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:329)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 11:30:22 AM] Operation 'text/foldingRange' failed! {uri: '/d%3A/test-pack/tmp.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectPair(BallerinaWorkspaceManager.java:433)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:156)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getSyntaxTree(FoldingRangeProvider.java:66)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getFoldingRange(FoldingRangeProvider.java:45)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$foldingRange$16(BallerinaTextDocumentService.java:573)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 11:30:22 AM] Operation 'text/codeLens' failed! {uri: '/d%3A/test-pack/tmp.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectPair(BallerinaWorkspaceManager.java:433)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:156)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:367)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 11:30:22 AM] Operation 'text/codeLens' failed! {uri: '/d%3A/test-pack/tmp.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectPair(BallerinaWorkspaceManager.java:433)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:156)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:367)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 11:30:22 AM] Operation 'text/codeLens' failed! {uri: '/d%3A/test-pack/tmp.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.ballerina.projects.util.ProjectPaths.isNonDefaultModuleTestFile(ProjectPaths.java:177)
	at io.ballerina.projects.util.ProjectPaths.isStandaloneBalFile(ProjectPaths.java:146)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:425)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:421)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:115)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectPair(BallerinaWorkspaceManager.java:433)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:156)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:367)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by hasithaa** [comment]
I have used the following code (single file, not a project), 

```
import ballerina/file;

public function main() {
   
}
```

**Comment by hasithaa** [comment]
@hevayo Please note, this seems to be an issue with the project API.

**Comment by rasika** [comment]
This is a path issue in project api. Assuming file is in path `/d:/test-pack/tmp.bal` the check below causes `absFilePath.getParent().getParent().getParent()` a NPE since the `.getParent()` is called on top a null path.https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectPaths.java#L177

**Comment by nadeeshaan** [comment]
As per the log, this seems to be an issue with the path. For the file uri from the IDE, we convert to a path object using `Paths.get(new URL(uri).toURI())`. Does this means that the generated path is having an issue or cannot be identified by the usage?

**Comment by rasika** [comment]
@nadeeshaan i think NPE is due to `.getParent()`. This is reproducible in mac os by opening a file in `/private/test.bal`

**Comment by nadeeshaan** [comment]
> @nadeeshaan i think NPE is due to `.getParent()`. This is reproducible in mac os by opening a file in `/private/test.bal`

Yeah, Somehow the generated path processing has been failed
