### ISSUE TITLE
BLangNodeTransformer gives CCE for invalid code snippet

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#28755]
**Description:**
```bal
// Note: "- U+EFFA" is a unicode private use character and it is not allowed within an identifier.
function foo(string bar) {
   io:println(bar);
}

public function main() {
  foo("Lochana");
}
```
</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypeDescriptorNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.TypeDescriptorNode are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypeDescriptorNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.TypeDescriptorNode are in unnamed module of loader 'app')
	at io.ballerina.compiler.syntax.tree.ParenthesisedTypeDescriptorNode.typedesc(ParenthesisedTypeDescriptorNode.java:40)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:957)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:470)
	at io.ballerina.compiler.syntax.tree.ParenthesisedTypeDescriptorNode.apply(ParenthesisedTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5307)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2762)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2719)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:470)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4827)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1501)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:470)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1409)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1389)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1367)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:470)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
```
</details>

**Comment by lochana-chathura** [comment]
This is fixed. Hence closing the issue.
