### ISSUE TITLE
[LS] text/completion' failed with a NoSuchElementException

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28788]
Sample program to reproduce 

```ballerina
import ballerina/http;

const BALLERINA_ORG = "ballerina-platform";
const BALLERINA_LANG_REPO = "ballerina-lang";

public function main() returns error? {
    check getLables(BALLERINA_ORG, BALLERINA_LANG_REPO);
}

function getLables(string org, string repo) returns error? {

    http:Client cli = check new http:Client("https://api.github.com");
    string path = string `/repos/${org}/${repo}/labels`;
    var process = function(json result) returns error|boolean {
                      return false;
                  };
    check invokeAPI(cli, path, process);
}

function invokeAPI(http:Client cli, string path, function (json) returns boolean|error logic) returns error? {
    json result = <json>check cli->get(path, targetType = json);
}
```

![test-pack-1613805262889](https://user-images.githubusercontent.com/1356214/108587498-d8c5a280-7379-11eb-9bc4-82bc0ecdd68b.gif)

Error 

```
[Error - 12:44:24 PM] Operation 'text/completion' failed! {uri: '/d%3A/test/temp.bal', [21:44], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.getDocumentation(FunctionCompletionItemBuilder.java:188)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.setMeta(FunctionCompletionItemBuilder.java:148)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.build(FunctionCompletionItemBuilder.java:90)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.populateBallerinaFunctionCompletionItem(AbstractCompletionProvider.java:328)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:148)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:143)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.expressionCompletions(AbstractCompletionProvider.java:380)
	at org.ballerinalang.langserver.completions.providers.context.CheckExpressionNodeContext.getCompletions(CheckExpressionNodeContext.java:57)
	at org.ballerinalang.langserver.completions.providers.context.CheckExpressionNodeContext.getCompletions(CheckExpressionNodeContext.java:37)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by hasithaa** [comment]
I suspect this is something related to having a function type in the function signature.
