### ISSUE TITLE
`bal run` command in vscode plugin throws NPE for configurable decryption

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28783]
**Description:**
If we have a bal source that contains configurable variables in encrypted string and uses `config:decryptString()` for decryption, 
It asks a predefined secret from user in the console. 
Due to this, we receive an NPE when executing the `bal run` command from the vscode command.

**Steps to reproduce:**
Ballerina source
```ballerina
import ballerina/io;
import ballerina/lang.config;
 
configurable string name = ?;
 
public function main() {
    io:println(name);
    io:println(config:decryptString(name));  
}
```
- Get the encrypted string for a prefered string (Eg. "test") using `bal encrypt` command in terminal. 
- Provide a preferred secret. 
- Copy the encrypted string provided in the terminal and replace it in the value of `name` in Config.toml
```toml
name="@encrypted:{<encrypted-string>}"
```
- execute the `bal run` command from vscode command palette.

Console output

![Screenshot from 2021-02-19 19-49-08](https://user-images.githubusercontent.com/28644893/108516119-d9aff300-72eb-11eb-942f-09dd0b47275e.png)

Error log: 
```
java.lang.NullPointerException
	at io.ballerina.runtime.internal.configurable.ConfigSecurityUtils.handleEncryptedValues(ConfigSecurityUtils.java:80)
	at io.ballerina.runtime.internal.configurable.ConfigTomlParser.getBalValue(ConfigTomlParser.java:299)
	at io.ballerina.runtime.internal.configurable.ConfigTomlParser.retrievePrimitiveValue(ConfigTomlParser.java:172)
	at io.ballerina.runtime.internal.configurable.ConfigTomlParser.validateNodeAndExtractValue(ConfigTomlParser.java:131)
	at io.ballerina.runtime.internal.configurable.ConfigTomlParser.populateConfigMap(ConfigTomlParser.java:106)
	at io.ballerina.runtime.internal.launch.LaunchUtils.initConfigurableVariables(LaunchUtils.java:134)
	at $ConfigurationMapper.$configureInit(Unknown Source)
	at $_init.main(.)
 
```
Even if the vscode command does not support user input while execution, it should provide a proper error message. 
An NPE is not preferred. 

**Affected Versions:**
alpha2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
`bal run` CLI command results in the mentioned NPE error.

**Comment by warunalakshitha** [comment]
We have removed the encrypting config values and config lang lib (https://github.com/ballerina-platform/ballerina-lang/pull/29634)  hence above issue is no longer valid.
