### ISSUE TITLE
BIR optimizer fails to handle closure variables

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28789]
Sample Code to reproduce 

```ballerina
function testFunc(string org, string repo) returns error? {
    string path = "hello"; // Problem case
    var process = function() returns error? {
                      if path == "hello" {
                          return;
                      } else {
                          return error("Hello not found", path1 = path);    // Problem case
                      }

                  };
}
```

Error
```
[2021-02-20 12:58:41,550] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:419)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:121)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:121)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:378)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:98)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:98)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:81)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:77)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:265)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
```

**Comment by riyafa** [comment]
This is not an issue with the BIROptimizer, but the details are missing in the AST used in the BirGen

**Comment by manuranga** [comment]
@riyafa can you please add more info on what exactly is missing ?

**Comment by riyafa** [comment]
The path in the first instance in `if path == "hello" {` is desugared to read from the map passed to the lamda as `if $paramMap$_2[path] == hello` but the second instance with the error constructor it is not desugared to read from the map, hence at BirGen when the `path` field is not found an exception is thrown

**Comment by riyafa** [comment]
On further debugging I have noticed that the `namedArgs` on the `BLangErrorConstructorExpr` is not desugared properly, but is used in the AST passed for birGen
