### ISSUE TITLE
NPE when calling a function with an anon function as an argument at a module level

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#28797]
**Description:**
Calling a function with an anon function as an argument at a module level will result in an NPE. Refer to the below code snippet.

**Steps to reproduce:**
```ballerina
var getIntArray = function () returns int[] {
     return [1, 2, 3, 4];
};

function getSalaries(function () returns int[] arrayFunc) returns int[] {
    return arrayFunc();
}

int[] salaries = getSalaries(getIntArray);

public function main() {
    int[] sal = salaries; // this gives an NPE.
}
```

**Affected Versions:**
SLA1

**OS, DB, other environment details and versions:**
n/a

**Related Issues (optional):**

**Comment by chiranSachintha** [comment]
`ballerina-internal.log` for the above program

```
[2021-04-15 17:00:53,863] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at test3.getSalaries(test3.bal:6)
	at $_init.$gen$$0046$0060init$0062(.:9)
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
