### ISSUE TITLE
NPE with invalid string concat inside object

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28803]
**Description:**
Result in the following error when editing the source via VSCode.
```
[4:19]- [4:26], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:232)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:304)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:218)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:911)
	at org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode.accept(BLangObjectTypeNode.java:71)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:236)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:292)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:111)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:202)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:207)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.computePositionDetails(CodeActionUtil.java:329)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$3(CodeActionRouter.java:88)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:86)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$6(BallerinaTextDocumentService.java:314)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```

**Steps to reproduce:**
```
type ObjectName object {

    string name = "Alice" + " Bob";
    function getName() returns string;
};

```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Could not reproduce with SL GA. @prabushi can you please confirm whether it's been resolved?
