### ISSUE TITLE
AIDatamapperCodeAction fails with Exception

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28899]
**Description:**
Consider the following example, 

```
class TestC {
      *TestO;
}

function testMain() {
    TestC cc = new(<cursor>)
}

type TestO object {
    int oField1;
    int oField2;
};
```

Following exception is thrown when the cursor is at the mentioned position

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.ballerinalang.datamapper.AIDataMapperCodeActionUtil.getAIDataMapperCodeActionEdits(AIDataMapperCodeActionUtil.java:132)
	at org.ballerinalang.datamapper.AIDataMapperCodeAction.getAIDataMapperCommand(AIDataMapperCodeAction.java:100)
	at org.ballerinalang.datamapper.AIDataMapperCodeAction.getDiagBasedCodeActions(AIDataMapperCodeAction.java:61)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$2(CodeActionRouter.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$3(CodeActionRouter.java:93)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
```
**Affected Versions:**
sl-alpha2 at least

**Comment by isuruRuhu** [comment]
This issue is fixed now.

**Comment by nadeeshaan** [comment]
Closing the issue as per the above comment
