### ISSUE TITLE
User doesn't get LS suggestions in For-each template

### ISSUE THREAD

**Issue by sajeerAhamed15** [ballerina-platform/ballerina-lang#28927]
**Description:**
![image](https://user-images.githubusercontent.com/26720235/109485955-44112200-7aa8-11eb-8020-be919d6cb9c6.png)
The user doesn't get LS completions in the above code snippet

```
foreach var item in <here> {
            
}
```

**Comment by nadeeshaan** [comment]
This is because the semantic analyzer fails for the particular issue with the following 

```
ballerinalang.compiler.semantics.analyzer.Types.inferRecordFieldType(Types.java:1954)'}
java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.inferRecordFieldType(Types.java:1954)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.setForeachTypedBindingPatternType(Types.java:1596)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2855)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3186)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3182)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:443)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:415)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3186)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3178)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:310)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
```

**Comment by lochana-chathura** [comment]
> This is because the semantic analyzer fails for the particular issue with the following

Issue https://github.com/ballerina-platform/ballerina-lang/issues/28709

**Comment by sajeerAhamed15** [comment]
Duplicate Issue [#28709](https://github.com/ballerina-platform/ballerina-lang/issues/28709)
