### ISSUE TITLE
Error building ballerina/io which was pushed to central

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#29142]
**Description:**
The DEV central currently has 0.6.0 version of ballerina/io pushed using https://drive.google.com/file/d/1U4r9Q1aQ1vlRmC9C2pzhPutBXDuSebn-/view?usp=sharing.

When trying to run a hello world main, a ballerina-internal.log is created with an error.

![Screenshot 2021-03-11 at 7 53 58 PM](https://user-images.githubusercontent.com/4398820/110801737-8bb35d00-82a3-11eb-89bb-3d64bb6ff8f8.png)

```
[2021-03-11 19:30:55,647] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:592)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$1(BIRGen.java:390)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:390)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:265)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:141)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:127)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:103)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:102)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:247)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
- Use the above pack to create a hello world main
- Set env var for DEV central. i.e `export BALLERINA_DEV_CENTRAL=true`
- Using the above pack, build the hello world main by invoking `bal build`

**Affected Versions:**
Post Alpha2 pack

**OS, DB, other environment details and versions:**
MAC

**Comment by azinneera** [comment]
This happens while it tries to inject the observability to dependencies. This is a bug and we need not inject the observability imports into dependencies.
