### ISSUE TITLE
Suppress missing node names from the error messages

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#29168]
**Description:**
$subject.

**Describe your problem(s)**
e.g.
```bal
function func4(any v) {
    match v {
        {a} => {}
    }
}
```
The above code sample will have the following diagnostic.

`ERROR [test_parser.bal:(2:10,2:10)] variable '$missingNode$_0' should be declared as constant`

`$missingNode$_0` should not be exposed to the user.

**Describe your solution(s)**
Two possible ways to handle this.
1.  Inside the `dlog.error()` API check for the args if they are missing node names and replace  them with something like "missingIdentifier"
2.  Can suppress the whole diagnostic. Since we already log an error for the missing identifier, we may drop any error causing on top of that.  i.e. Inside the `dlog.error()` check the args and simply return.

**Comment by KRVPerera** [comment]
Maybe we can force position data to be available for `anon` and `missing` nodes when creating them. Instead of string, we may have to keep a string and also position data to track multiple errors for the same position.

**Comment by lochana-chathura** [comment]
Currently, there are places we already do the suppression.
https://github.com/ballerina-platform/ballerina-lang/blob/4266d2bf32840a69525605dd900e120fd13fab35/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L8408-L8412

Since we currently only relying upon the string, for the following case typechecker error get skipped. Therefore, causes problems at later phases. 
```bal
public function main() {
    \u{24}missingNode\u{24} = 10;
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2021-11-19 14:26:45,695] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5931)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.accept(BLangSimpleVarRef.java:61)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2431)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:80)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1288)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1333)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8195)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:809)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:234)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:421)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:189)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```        
</details>

**Comment by rdulmina** [comment]
I'm +1 for not giving the error since we have already logged the missing identifier error. We may have to bring the missing node info to BLangNode as well since as per the above comment we cannot rely upon string comparison
