### ISSUE TITLE
Using quoted identifier as function argument crashes the program

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#29196]
Using quoted identifier as function argument crashes the program

The following code crashes:
```
public function foo(string '--val)  {

}
```
Following log can be found in the ballerina-internal.log:
```
[2021-03-15 10:26:08,953] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineInvokableSymbolParams(SymbolEnter.java:2743)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineInvokableSymbol(SymbolEnter.java:2716)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1721)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$6(SymbolEnter.java:407)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:407)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:300)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:255)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:368)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:257)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 

```

**Comment by HindujaB** [comment]
This error should be handled at parser level.
Because, as per spec, the param-name `'--val` is unsupported. We can only use special characters in identifiers with a preceding `\`.
So the supported identifier would be `'\-\-val`.

**Comment by lochana-chathura** [comment]
The above sample is parsed as,
```bal
public function foo(string ' MISSING[=]--val)  {

}
```
while giving `ERROR_INCOMPLETE_QUOTED_IDENTIFIER` for the quote. `--val` is parsed as a `unary-expr`.
Parser behavior seems to be correct. We need to fix the NPE at the semantics analyzer.

**Comment by lochana-chathura** [comment]
In this case, the quote will be removed at the blangNodeTranformer and the resultant identifier is an empty string (but not null). This might be the reason.

**Comment by lochana-chathura** [comment]
Related to #29163
