### ISSUE TITLE
Redeclared symbol didn't provide a proper error message for rest parameter inside a ballerina function

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#29205]
**Description:**
$Subject

**Steps to reproduce:**
```
public function main() {
    testFunc(1, 2, 3);
}

function testFunc(int i, int... i) {
}
```
Error log:
```
[2021-03-15 13:28:22,970] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationArgs(TypeChecker.java:5691)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParam(TypeChecker.java:5479)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParamAndReturnType(TypeChecker.java:5362)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkFunctionInvocationExpr(TypeChecker.java:5069)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2679)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:370)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:349)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1903)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3231)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3199)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3195)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:443)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3231)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:415)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3231)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3199)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3191)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:310)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:275)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:217)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:374)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:160)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:130)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:251)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
This issue happens because,
1. When we look up the second `i` and since we found the symbol we identified it as a redeclared symbol and we set the type to `symTable.semanticError`(already it is in array type)
2. When it tries to cast to tuple it gets CCE
Simply we can fix this by checking the type before the cast.

But by looking at the overall picture is it okay to set the `type of redeclared symbol` to `symTable.semanticError`?
After identifying a particular symbol is redeclared, we do not exit but we continue the compilation. 
@hasithaa, @gimantha, @MaryamZi WDYT?

**Comment by gimantha** [comment]
> This issue happens because,
> 
> 1. When we look up the second `i` and since we found the symbol we identified it as a redeclared symbol and we set the type to `symTable.semanticError`(already it is in array type)
> 2. When it tries to cast to tuple it gets CCE
>    Simply we can fix this by checking the type before the cast.
> 
> But by looking at the overall picture is it okay to set the `type of redeclared symbol` to `symTable.semanticError`? After identifying a particular symbol is redeclared, we do not exit but we continue the compilation. @hasithaa, @gimantha, @MaryamZi WDYT?

Should we not print the `redeclared symbol` error message?

**Comment by KavinduZoysa** [comment]
> Should we not print the `redeclared symbol` error message?

No, what I mean was after the compiler identified second `i` is redeclared, we set the type of `i` to `symTable.semanticError`. Do we need to do that?

**Comment by MaryamZi** [comment]
Setting the type of redeclared symbols to `symTable.semanticError` ensures there's only one valid symbol with that name.

If we don't do that, there may be additional irrelevant errors in scenarios like

```ballerina
public function main() {
    string[] x = [];
    int[] x = [1, 2]; // `redeclared symbol 'x'``

    string[] _ = x; // will result in `incompatible types: expected 'string[]', found 'int[]'`
}
```

Validity of the second error will obviously depend on what the user will change, but I think we can assume the first one is the valid one.

**Comment by KavinduZoysa** [comment]
I understood. It seems this is a design-level change. My point was changing the actual type of any symbol will affect other phases. 
Let's go with this. Thank you for the clarification.

**Comment by KavinduZoysa** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/35268
