### ISSUE TITLE
NPE when using the `function` type descriptor

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29277]
**Description:**
$title, the `function` type descriptor was introduced for slalpha3.

**Steps to reproduce:**
```ballerina
function foo() {

}

function x = f // when `f` is typed in
```

```log
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.symbols.BallerinaFunctionTypeSymbol.parameters(BallerinaFunctionTypeSymbol.java:65)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.getFuncArguments(FunctionCompletionItemBuilder.java:293)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.setMeta(FunctionCompletionItemBuilder.java:133)
	at org.ballerinalang.langserver.completions.builder.FunctionCompletionItemBuilder.build(FunctionCompletionItemBuilder.java:95)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.populateBallerinaFunctionCompletionItem(AbstractCompletionProvider.java:376)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:159)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:154)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.expressionCompletions(AbstractCompletionProvider.java:426)
	at org.ballerinalang.langserver.completions.providers.context.VariableDeclarationProvider.initializerContextCompletions(VariableDeclarationProvider.java:121)
	at org.ballerinalang.langserver.completions.providers.context.ModuleVariableDeclarationNodeContext.getCompletions(ModuleVariableDeclarationNodeContext.java:59)
	at org.ballerinalang.langserver.completions.providers.context.ModuleVariableDeclarationNodeContext.getCompletions(ModuleVariableDeclarationNodeContext.java:47)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
slalpha3-SNAPSHOT

**Comment by pubudu91** [comment]
Fixed with #29291. Hence closing this.
