### ISSUE TITLE
Bad, sad error when attempting to push a package built without using `-c`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29286]
**Description:**
$title.

**Steps to reproduce:**
- create a simple package
- build without using `-c` (i.e., `bal build`)
- attempt pushing it - I tried to push it to the local repo (`bal push --repository=local`)

This results in a bad, sad error with the following in the ballerina-internal.log
```log
[2021-03-17 16:06:42,552] SEVERE {b7a.log.crash} - cannot find bala file for the package: proj. Run 'bal build' to compile and generate the bala. 
io.ballerina.projects.ProjectException: cannot find bala file for the package: proj. Run 'bal build' to compile and generate the bala.
	at io.ballerina.cli.cmd.PushCommand.validateBalaFile(PushCommand.java:221)
	at io.ballerina.cli.cmd.PushCommand.pushPackage(PushCommand.java:177)
	at io.ballerina.cli.cmd.PushCommand.execute(PushCommand.java:135)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

Even this error is not useful since I did use `bal build`.

**Affected Versions:**
slalpah3-SNAPSHOT

**Comment by MaryamZi** [comment]
@azinneera, with the fix for this, there is no bad, sad error but the error I get is still
```cmd
ballerina: cannot find bala file for the package: proj. Run 'bal build' to compile and generate the bala.
``` 

Instead, can't/shouldn't we say
```cmd
ballerina: cannot find bala file for the package: proj. Run 'bal build -c' to compile and generate the bala.
```

**Comment by MaryamZi** [comment]
> @azinneera, with the fix for this, there is no bad, sad error but the error I get is still
> 
> ```batchfile
> ballerina: cannot find bala file for the package: proj. Run 'bal build' to compile and generate the bala.
> ```
> 
> Instead, can't/shouldn't we say
> 
> ```batchfile
> ballerina: cannot find bala file for the package: proj. Run 'bal build -c' to compile and generate the bala.
> ```

Just noticed that this has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/29349.
