### ISSUE TITLE
CCE Thrown in semantic API when observability is enabled

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#29290]
**Description:**
Ballerina run fails with bad sad with following error log when executing the sample below.

```
[2021-03-17 17:16:00,640] SEVERE {b7a.log.crash} - class io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.createFunctionSymbol(SymbolFactory.java:231)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:132)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:274)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:139)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:146)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:588)
	at io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode.apply(CaptureBindingPatternNode.java:46)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:87)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:584)
	at io.ballerina.compiler.syntax.tree.TypedBindingPatternNode.apply(TypedBindingPatternNode.java:50)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:87)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:76)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:83)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:320)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:87)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:48)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:83)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:64)
	at io.ballerina.compiler.syntax.tree.ServiceDeclarationNode.apply(ServiceDeclarationNode.java:83)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:351)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:83)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:66)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:44)
	at org.ballerinalang.diagramutil.DiagramUtil.getSyntaxTreeJSON(DiagramUtil.java:48)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:97)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:105)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:168)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
Make sure observability is enabled in the project. 
```toml
[build-options]
observabilityIncluded = true
```
Sample Code
```ballerina
import ballerina/http;

# INTERNAL stucture - the request handler parameter data.
# 
# + request - The HTTP request
# + response - The HTTP response
# + pure - The flag to mention if it's a pure HTTP request
# + result - The result JSON
public type HandlerParams record {
    http:Request request;
    http:Response response;
    boolean pure = false;
    json result = { Outputs: {}, Logs: [] };
};

# Function handler type.
type FunctionHandler (function (HandlerParams) returns error?);

@untainted public listener http:Listener hl = new(9099);
map<FunctionHandler> dispatchMap = {};

service http:Service / on hl {

    resource function 'default [string functionName](http:Caller caller, http:Request request) returns @tainted error? {
        FunctionHandler? handler = dispatchMap[functionName];
        http:Response response = new;
        if handler is FunctionHandler {
            response.setTextPayload("is a function handler");
            response.statusCode = 200;
            check caller->respond(response);
        } else {
            response.setTextPayload("function handler not found: " + <@untainted> functionName);
            response.statusCode = 404;
            check caller->respond(response);
        }
    }
}
```
Execute Ballerina run

**Affected Versions:**
SLAlpha3 test pack

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Fixed with #29298. Hence closing this.
