### ISSUE TITLE
Internal error with cast of readonly array to byte[]

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#29316]
With slalpha2, the following program:

```
import ballerina/io;

public function main() {
  (readonly & any) a = [1, 2, 3];
  any aa = a;
  byte[] b = <byte[]>aa;
  io:println("Should be true: ", aa === b);
  io:println("Should be 1: ", b[0]);
}
```

outputs

```
Should be true: true
ballerina: Oh no, something really went wrong.
```

Note that the `aa` variable should not be necessary, but I get compile errors without it.

**Comment by hasithaa** [comment]
This seems to be an issue with the optimization we have done for the byte[]. Here is the error. 

```
[2021-03-18 15:34:59,374] SEVERE {b7a.log.crash} - class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap') 
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.ballerina.runtime.internal.values.ArrayValueImpl.getByte(ArrayValueImpl.java:350)
	at temp.main(temp.bal:8)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
