### ISSUE TITLE
PositionUtil.withinRange() throws an NPE

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29328]
**Description:**
Noticed that the `PositionUtil.withinRange()` method throws an NPE with the `nodePosition` being null. 

```java
[Error - 4:09:32 PM] Operation 'text/codeAction' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test.bal', [12:20]- [12:20], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:214)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:270)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:236)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:259)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:202)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Steps to reproduce:**
Paste below code in a new bal file:
```
function anotherFunc() {
    string:lastIn<cursor>dexOf();
}
```
and put your cursor somewhere on the function body.

**Affected Versions:**
On master branch as of 18th March

**Comment by pubudu91** [comment]
The above appears to be the same as https://github.com/ballerina-platform/ballerina-lang/issues/29105. Apparently the parser seems to be modeling the above as an error binding pattern 🤔  @lochana-chathura is this the correct behaviour for the above code snippet?

**Comment by IMS94** [comment]
Can reproduce for `int[<cursor>]` as well.

**Comment by nadeeshaan** [comment]
@lochana-chathura @IMS94 this issue still can be observed in the master branch even after merging #29340 . Can you guys please confirm?

**Comment by IMS94** [comment]
@nadeeshaan Just checked this in master. Seems like the above cases cannot be reproduced anymore.

**Comment by nadeeshaan** [comment]
As per the above comment, I'm closing this issue. If the issue still exists please reopen
