### ISSUE TITLE
Bad sad error hides the exact compilation error

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#29389]
**Description:**
Following sample results in a bad sad error hiding the exact compilation error
```ballerina
import ballerina/log;

public class Proto3SerDes {


    private final typedesc<anydata> & readonly dataType;

    # Generates a schema for a given data type.
    #
    # + ballerinaDataType - The data type of the value that needs to be serialized
    # + return - `serdes:Error` if the data type is not supported else nil
    public isolated function init(typedesc<anydata> ballerinaDataType) returns error? {
        self.dataType = ballerinaDataType;
        log:printInfo("new");
    }

    # Deserializes a given array of bytes.
    #
    # + encodedMessage - The encoded byte array of the value that is serialized
    # + return - The value represented by the encoded byte array
    public isolated function deserialize(byte[] encodedMessage, typedesc<anydata> T = dataType) returns anydata|error {
        log:printInfo("deserialize");
        return "deserialize(self, encodedMessage, self.dataType)";
    }
}

public function main() returns error? {

    Proto3SerDes|error p = new(json);
}
```

**Affected Versions:**
alpha3

Error
```
[2021-03-23 09:33:15,144] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:421)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$3(BIROptimizer.java:119)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:119)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:380)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$2(BIROptimizer.java:103)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRTypeDefinition.accept(BIRNode.java:489)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$0(BIROptimizer.java:97)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:97)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:77)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:145)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:131)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:105)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:168)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
```

**Comment by MaryamZi** [comment]
The default value of the `T` param in `deserialize` should have resulted in a compilation error for undefined symbol.

Also happens with object type descriptors.

```ballerina
public type Proto3SerDes object {

    typedesc<anydata> & readonly dataType;

    public function deserialize(byte[] encodedMessage, typedesc<anydata> T = dataType) returns anydata|error;
};
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/35326.
