### ISSUE TITLE
Unsupported file update thrown for Config.toml updates

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29398]
**Description:**
Create a multi-module project with a `Config.toml` in root level. Then try to add changes to the Config.toml.

**Error**
```
[Error - 11:50:45 AM] Operation 'text/didChange' failed! {uri: '/Users/rasika/Documents/WSO2/projects/bal-order-processing/Config.toml', error: 'Unsupported file update'}
org.ballerinalang.langserver.commons.workspace.WorkspaceDocumentException: Unsupported file update
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didChange(BallerinaWorkspaceManager.java:282)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:533)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
2.0.0-SLA3

**Comment by nadeeshaan** [comment]
Duplicate #29512. Hence closing the issue
