### ISSUE TITLE
Missing semicolon error shown in incorrect lines

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#29418]
**Description:**
![error1](https://user-images.githubusercontent.com/30715489/112098076-2f1b4080-8bc7-11eb-8e3e-4e3741dd4589.png)

```
'bal' command is picked up from the plugin.
Plugin version: 2.0.0
Ballerina version: Swan Lake Alpha 3
Using Ballerina CLI command 'bal' for Language server.
[Error - 10:55:46 AM] Operation 'text/codeAction' failed! {uri: '/home/suleka/stock_data_monitoring/client.bal', [1:1]- [1:1], error: 'Index 1 out of bounds for length 0'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/java.util.ArrayList.add(ArrayList.java:487)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at org.ballerinalang.langserver.codeaction.CodeActionProvidersHolder.loadServices(CodeActionProvidersHolder.java:76)
	at org.ballerinalang.langserver.codeaction.CodeActionProvidersHolder.<init>(CodeActionProvidersHolder.java:59)
	at org.ballerinalang.langserver.codeaction.CodeActionProvidersHolder.getInstance(CodeActionProvidersHolder.java:51)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:59)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
**Suggested Labels:**
Ballerina Swan Lake - Alpha3

**Comment by nadeeshaan** [comment]
The provided error trace is different from the diagnostic issue.

**Comment by lochana-chathura** [comment]
In the parser, we have zero-based numbering for the location. In diagnostic API we convert it to one-based numbering. Could be some issue due to that. Will check.

**Comment by suleka96** [comment]
oh sorry my bad, I just copied the existing error trace at the time. Seems like this does not give any errors in the ballerina output.

**Comment by lochana-chathura** [comment]
Currently, the missing semicolon is reported at the immediate next line which is the expected behavior atm. Let's keep this issue to see if we can improve the location.

**Comment by nadeeshaan** [comment]
> Currently, the missing semicolon is reported at the immediate next line which is the expected behavior atm. Let's keep this issue to see if we can improve the location.

@lochana-chathura shall we lower the priority then?

**Comment by lochana-chathura** [comment]
Our syntax tree-related implementations are quite similar to C#. 
This issue seems to exist with C# as well.
 
![Screenshot from 2021-07-01 00-00-11](https://user-images.githubusercontent.com/39232462/124013167-9edb6b80-d9ff-11eb-8629-4e436f152393.png)
