### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find a line with the character offset '8'

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29414]
**Description:**
For a new module which is yet to be imported, when the cursor is at the position like below, observing the following stack trace in debug output.

<img width="325" alt="Screenshot 2021-03-23 at 12 45 07" src="https://user-images.githubusercontent.com/690559/112108510-4b72a980-8bd6-11eb-868b-2efc36104689.png">

```
[Error - 12:30:30 PM] Operation 'text/codeAction' failed! {uri: '/Users/kishanthan/WSO2/work/projects/ballerina-projects/test_hackathon/msmp_with_nats/main.bal', [5:8]- [5:8], error: 'Cannot find a line with the character offset '8''}
java.lang.IllegalArgumentException: Cannot find a line with the character offset '8'
	at io.ballerina.tools.text.LineMap.textPositionFrom(LineMap.java:50)
	at io.ballerina.tools.text.TextDocument.textPositionFrom(TextDocument.java:50)
	at org.ballerinalang.langserver.common.utils.CommonUtil.findNode(CommonUtil.java:862)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.computePositionDetails(CodeActionUtil.java:327)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$3(CodeActionRouter.java:93)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:92)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
This is fixed. Tested with beta-1.
