### ISSUE TITLE
NPE at BLangBlockFunctionBody 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29438]
**Description:**
'java.lang.NullPointerException
org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
<img width="383" alt="Screenshot 2021-03-23 at 14 24 12" src="https://user-images.githubusercontent.com/690559/112119551-7d3e3d00-8be3-11eb-8017-af56a6f30773.png">

Observed the below trace in debug output when trying out the above code.
```
[Error - 1:53:39 PM] Operation 'text/codeAction' failed! {uri: '/Users/kishanthan/WSO2/work/projects/ballerina-projects/test_hackathon/msmp_with_nats/main.bal', [4:27]- [4:27], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:215)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:271)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:237)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:260)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:203)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@pubudu91 I think we have to add the null check for the withinRange method's arguments, before processing them.

**Comment by pubudu91** [comment]
> @pubudu91 I think we have to add the null check for the withinRange method's arguments, before processing them.

If we do a null check there, the underlying issues in positions will go unnoticed though.

**Comment by nadeeshaan** [comment]
> > @pubudu91 I think we have to add the null check for the withinRange method's arguments, before processing them.
> 
> If we do a null check there, the underlying issues in positions will go unnoticed though.

Given the number of usages, I'm not sure whether we can address all the possible cases related to the positions being null.

**Comment by dulajdilshan** [comment]
Already fixed in `master`, so closing this.
