### ISSUE TITLE
[Semantic API] CCE when `Ctrl + click` on a resource method name

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29441]
Consider the following:
```ballerina
import ballerina/http;

listener http:Listener ep0 = new (9090, config = {host: localhost});

service /v1 on ep0 {
    resource function get pets(int? 'limit) returns Pets|Error {
    }
    resource function post pets() returns http:Created|Error {
    }
    resource function get pets/[string petId]() returns Pet|Error {
    }
}
```
When I `Ctrl + click` on the name of a resource method, a CCE is thrown.
```
[Error - 2:34:15 PM] Operation 'text/references' failed! {uri: '/c%3A/Users/Pubudu/Projects/openapi/foo-service.bal', [10:25], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaResourceMethodSymbol cannot be cast to class io.ballerina.compiler.api.impl.symbols.BallerinaSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaResourceMethodSymbol and io.ballerina.compiler.api.impl.symbols.BallerinaSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaResourceMethodSymbol cannot be cast to class io.ballerina.compiler.api.impl.symbols.BallerinaSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaResourceMethodSymbol and io.ballerina.compiler.api.impl.symbols.BallerinaSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.getInternalSymbol(BallerinaSemanticModel.java:337)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:176)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:85)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:84)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$references$6(BallerinaTextDocumentService.java:280)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by pubudu91** [comment]
This is working in slalpha5. Was fixed with #29788. Hence closing.
