### ISSUE TITLE
Goto defintion does not work for nats module and its types

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29442]
**Description:**
Trying to get the definition of below nats related types. 

```ballerina
import ballerinax/nats;

public function main() {
    nats:Client|nats:Error natsClient = new();
}

```

Getting below error

```
[Error - 2:33:38 PM] Operation 'text/definition' failed! {uri: '/Users/kishanthan/WSO2/work/projects/ballerina-projects/test_hackathon/msmp_with_nats/main.bal', [4:12], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:382)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getLocation(DefinitionUtil.java:82)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:61)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$3(BallerinaTextDocumentService.java:257)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed with #29744. Hence closing the issue
