### ISSUE TITLE
Bad Sad error on building

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#29468]
**Description:**
`bal doc` and `bal build` crashed for two scenarios. 

```LogTalk
 [2021-03-23 16:00:54,393] SEVERE {b7a.log.crash} - null 
java.lang.StackOverflowError
	at java.base/java.util.Arrays.hashCode(Arrays.java:4685)
	at java.base/java.util.Objects.hash(Objects.java:146)
	at io.ballerina.projects.ModuleId.hashCode(ModuleId.java:79)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.get(HashMap.java:552)
	at java.base/java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
	at io.ballerina.projects.DependencyGraph.getDirectDependencies(DependencyGraph.java:86)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:75)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:85)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:85)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:85)
	...
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
 
[2021-03-23 16:10:18,289] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getPackageAlias(ImmutableTypeCloner.java:590)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.populateImmutableStructureFields(ImmutableTypeCloner.java:580)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.populateImmutableStructureFields(ImmutableTypeCloner.java:538)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.defineImmutableRecordType(ImmutableTypeCloner.java:657)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.setImmutableType(ImmutableTypeCloner.java:308)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:194)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableType(ImmutableTypeCloner.java:171)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.setImmutableType(ImmutableTypeCloner.java:320)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:194)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:114)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.computeIntersectionType(SymbolResolver.java:1909)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:1112)
	at org.wso2.ballerinalang.compiler.tree.types.BLangIntersectionTypeNode.accept(BLangIntersectionTypeNode.java:48)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:466)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:457)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1871)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$8(SymbolEnter.java:417)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:417)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:305)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:260)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:369)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:160)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:130)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.DocCommand.execute(DocCommand.java:197)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
macOS 

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Having trouble reproducing both crashes.

**Comment by KRVPerera** [comment]
Closing as cannot reprduce
