### ISSUE TITLE
Cannot rename methods in a class

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#29467]
**Description:**
Consider the following source snippet and try renaming the `poll` method

```
class FinnHubTradesSubsriber {
    private ws:Client wsClient;
    private decimal pollInterval;
    private boolean proceed = false;

    function init(ws:Client wsClient, decimal pollInterval) {
        self.wsClient = wsClient;
        self.pollInterval = pollInterval;
    }

    public function poll(string symbolName) {
        
    }

    public function stop() {
        io:println("interrupted!");
        self.proceed = false;
    }
}
```

**Comment by pubudu91** [comment]
#29578 may be related to this.

**Comment by nadeeshaan** [comment]
In master, we get the following for starters

```
'class io.ballerina.compiler.api.impl.symbols.BallerinaMethodSymbol cannot be cast to class io.ballerina.compiler.api.impl.symbols.BallerinaSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaMethodSymbol and io.ballerina.compiler.api.impl.symbols.BallerinaSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaMethodSymbol cannot be cast to class io.ballerina.compiler.api.impl.symbols.BallerinaSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaMethodSymbol and io.ballerina.compiler.api.impl.symbols.BallerinaSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.getInternalSymbol(BallerinaSemanticModel.java:337)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:176)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:85)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:84)
	at org.ballerinalang.langserver.util.rename.RenameUtil.rename(RenameUtil.java:54)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$rename$12(BallerinaTextDocumentService.java:488)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by pubudu91** [comment]
This is possibly the same as #28388. @dulajdilshan Can you verify #28388 as well once you fix this?
