### ISSUE TITLE
Unexpected runtime error occurrs when using ballerina-modules pulled from ballerina-central.

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#29492]
**Description:**
* I am trying implement a weather-reporter service backed by Apache Kafka. 
* For this I am using `ballerinax-kafka-2.1.0-alpha5` which is pulled from ballerina central.
* When running the code following runtime error could be found in `ballerina-internal.log`.
```[2021-03-23 18:12:41,573] SEVERE {b7a.log.crash} - ballerinax/kafka/2_1_0-alpha5/$ConfigurationMapper 
java.lang.NoClassDefFoundError: ballerinax/kafka/2_1_0-alpha5/$ConfigurationMapper
        at ayeshalm.kafka_weather_reporter.0_1_0.$ConfigurationMapper.$configureInit(Unknown Source)
        at ayeshalm.kafka_weather_reporter.0_1_0.$_init.main(kafka_weather_reporter)
Caused by: java.lang.ClassNotFoundException: ballerinax.kafka.2_1_0-alpha5.$ConfigurationMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
```

**Steps to reproduce:**
* Write a simple project using `ballerinax-kafka` latest version (2.1.0-alpha5). We could use sample codes in kafka-BBEs.
* Try to run the program.

**Affected Versions:**
* ballerinax-kafka 2.1.0-alpha5 / ballerina-lang swanlake-alpha3

**OS, DB, other environment details and versions:**
* Ubuntu 20.04

**Related Issues (optional):**

**Suggested Labels (optional):**
https://github.com/ballerina-platform/ballerina-lang/labels/Version%2FSLAlpha3

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
I tested this locally with `Swan Lake Beta 2` using a simple producer [sending a message to a topic](https://ballerina.io/learn/by-example/kafka-producer) 

The project seems to pull all the relevant dependencies from central automatically. Note that Kafka has since been updated to `kafka:2.1.0-beta.1`. 

```
~/Desktop/Kafka/KafkaProject ❯ bal run                                                                
Compiling source
        mohamedaquibzulfikar/KafkaProject:0.1.0
ballerinax/kafka:2.1.0-beta.1 [central.ballerina.io -> home repo]  100% [====================================================================================================] 8933/8933 KB (0:00:09 / 0:00:00) 
        ballerinax/kafka:2.1.0-beta.1 pulled from central successfully
ballerina/crypto:1.1.0-beta.1 [central.ballerina.io -> home repo]  100% [====================================================================================================] 5107/5107 KB (0:00:08 / 0:00:00) 
        ballerina/crypto:1.1.0-beta.1 pulled from central successfully
ballerina/regex:0.7.0-beta.1 [central.ballerina.io -> home repo]  100% [===========================================================================================================] 4/4 KB (0:00:00 / 0:00:00) 
        ballerina/regex:0.7.0-beta.1 pulled from central successfully
ballerina/time:2.0.0-beta.1 [central.ballerina.io -> home repo]  100% [==========================================================================================================] 23/23 KB (0:00:00 / 0:00:00) 
        ballerina/time:2.0.0-beta.1 pulled from central successfully
ballerina/uuid:0.10.0-beta.1 [central.ballerina.io -> home repo]  100% [=========================================================================================================] 10/10 KB (0:00:00 / 0:00:00) 
        ballerina/uuid:0.10.0-beta.1 pulled from central successfully

Running executable

^C
```

**Comment by Ibaqu** [comment]
Closing since has since been resolved. Implementation works as expected.
