### ISSUE TITLE
NPE from Compiler API

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29503]
**Description:**
```ballerina
public function main() returns error? {
    mysql:Client 'client = check new("localhost", user = "root", password = "rootroot", port = 3306);
    'client

    io:println("hi");
}
```

![Screenshot 2021-03-23 at 19 27 46](https://user-images.githubusercontent.com/1496990/112158170-edfa4f00-8c0d-11eb-83f0-61bceecfe6a1.png)

VSCode output:
```
[Error - 7:27:27 PM] Operation 'text/codeAction' failed! {uri: '/Users/dhananjaya/Work/Samples/simple-etl/simpletl/main.bal', [4:12]- [4:12], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:215)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:271)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:237)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:260)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:203)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
I didn't get the NPE. @rdhananjaya Can you verify this with the current `master`?

**Comment by dulajdilshan** [comment]
@rdhananjaya Can you please check with the latest `master` and confirm whether if this issue still prevails?
