### ISSUE TITLE
NPE in 'create variable' code action for `string:from...` functions 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#29507]
**Description:**
This happens when there's a string lang lib function that does not have the string as first argument
Eg: `fromBytes()`, `fromCodePointInt()`, `fromCodePointInts()`

**Steps to reproduce:**

![Screenshot from 2021-03-23 20-05-07](https://user-images.githubusercontent.com/28644893/112164790-30268f00-8c14-11eb-9267-f5e5cf40cd1b.png)

Log output:
```
[Error - 8:07:34 PM] Operation 'text/codeAction' failed! {uri: '/home/hinduja/TEST/Hackathon/CCTransactionApp/modules/httpPortal/httpPortal.bal', [62:6]- [62:6], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:215)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:271)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:237)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:260)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:203)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Affected Versions:**
alpha3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjana** [comment]
@HindujaB does this issue persist in the latest release?

**Comment by HindujaB** [comment]
@sanjana This issue seems to be fixed in swan lake beta2.

**Comment by sanjana** [comment]
Closing since this issue has been fixed.
