### ISSUE TITLE
`Unsupported file update` exception when editing the Config.toml

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29512]
I added a `Config.toml` to my project mid way through working on it and when editing that file, keep seeing the following exception:
```
[Info  - 10:06:44 PM] Operation 'text/didOpen' {fileUri: 'file:///c%3A/Users/Pubudu/Projects/openapi/bookstore/Config.toml'} opened
[Error - 10:06:58 PM] Operation 'text/didChange' failed! {uri: '/c%3A/Users/Pubudu/Projects/openapi/bookstore/Config.toml', error: 'Unsupported file update'}
org.ballerinalang.langserver.commons.workspace.WorkspaceDocumentException: Unsupported file update
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didChange(BallerinaWorkspaceManager.java:282)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:533)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by nadeeshaan** [comment]
Currently the project API does not have an API to edit the `Config.toml` at compile time. Hence we throw the exception. @azinneera how can we handle this? Do we need to ignore this silently from LS? If we resolve info from the config.toml at compile time, we need an API to be exposed

**Comment by azinneera** [comment]
The `Config.toml` is a runtime-specific file and we only store files related to build time in Project API. IMO, we should not throw an exception here since there can be more files getting added to a package, and supporting them all in the Project API is not viable. @hevayo @nadeeshaan WDYT?

**Comment by hevayo** [comment]
Since Config.toml is not part of ProjectAPI +1 to ignore the file from LS side.

**Comment by nadeeshaan** [comment]
@hevayo @azinneera We can ignore the editing from the LS without any issue and +1 for doing so for now. We will have to find a proper approach when it comes to the language features such as auto completion for these kind of config files.
