### ISSUE TITLE
Bad sad error when testing mock function

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#29513]
**Description:**
Sample code

```ballerina
import ballerina/test;
import ballerina/http;
import ballerina/file;
import ballerina/io;

http:Client clientEndpoint = check new ("http://0.0.0.0:8080");

@test:Mock {
    moduleName: "ballerina/log",
    functionName: "printInfo"
}
test:MockFunction printlnMockFn = new();

string[] logs = []; 
public function mockLogPrintInfo(string value) {
    logs.push(value);
}

@test:Config {
    after: afterFunc
}
function testFileService() {
    test:when(printlnMockFn).call("mockLogPrintInfo");
    var response = checkpanic clientEndpoint->post("/files?fileName=myfile", "");
    test:assertEquals(response.getTextPayload(), "File is created successfully");

    response = checkpanic clientEndpoint->put("/files?fileName=myfile", "File content");
    test:assertEquals(response.getTextPayload(), "File is modified successfully");

    response = checkpanic clientEndpoint->delete("/files?fileName=myfile");
    test:assertEquals(response.getTextPayload(), "File is deleted successfully");

    foreach var log in logs {
        io:println(log);
    }
}

function afterFunc() {
    checkpanic file:remove("tests/testDirectory");
}

```

Error

```
[2021-03-23 22:14:01,687] SEVERE {b7a.log.crash} - Mock Function and Function to Mock cannot be null
java.lang.IllegalStateException: Mock Function and Function to Mock cannot be null
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunction(MockDesugar.java:162)
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunctions(MockDesugar.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:743)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7686)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:452)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:389)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:145)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:131)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:106)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:105)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:251)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Comment by Ibaqu** [comment]
This issue happens when a mocking a function whose module is not imported into the project. 

The compilation checks pass but it fails at the desugar level. 

This will be handled in the following issue : https://github.com/ballerina-platform/ballerina-lang/issues/29833
