### ISSUE TITLE
NPE in PositionUtil for an expr bodied function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29523]
The following code results in an NPE in `PositionUtil`.
```ballerina
function mapToBook(record {int book_id; string title; string first_name; string last_name;} book) returns Book => {
    id: book.book_id;
    name: ""  
};
```
NPE is thrown as soon as the quotes are added.
```
[Error - 11:48:26 PM] Operation 'text/codeAction' failed! {uri: '/c%3A/Users/Pubudu/Projects/openapi/bookstore/data_mappers.bal', [3:12]- [3:12], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:233)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:305)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:203)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by dulajdilshan** [comment]
Already fixed. Tested with current `master`
