### ISSUE TITLE
NPE at PositionUtil 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29533]
**Description:**
When cursor was at as seen in the image, an NPE was observed from debug output. 
<img width="549" alt="Screenshot 2021-03-24 at 00 25 41" src="https://user-images.githubusercontent.com/690559/112202539-81944580-8c37-11eb-862a-48008bf9ba24.png">

Error
```
[Error - 12:15:40 AM] Operation 'text/codeAction' failed! {uri: '/Users/kishanthan/WSO2/work/projects/ballerina-projects/test_hackathon/msmp_with_nats/subscriber.bal', [7:26]- [7:26], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:52)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:215)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:271)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:237)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:260)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNodes(NodeFinder.java:219)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:899)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupNode(NodeFinder.java:237)
	at io.ballerina.compiler.api.impl.NodeFinder.visit(NodeFinder.java:287)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:141)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:203)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:184)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.type(BallerinaSemanticModel.java:205)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:69)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:335)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
This is preventing from proceeding further as no code actions are being shown due to the NPE.

**Comment by IMS94** [comment]
This is same as #29328

**Comment by pubudu91** [comment]
Tested this in the latest master. The above mentioned NPE seems to have been fixed. Hence closing this.
