### ISSUE TITLE
`start` keywrod dosn't work with println

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#29557]
**Description:**
```ballerina
function print(int i) {
    io:println(i);
}

public function main() {
    int i = 0;

    while (i < 1000) {
        var s = start print(i);
        i = i + 1;
    }
    runtime:sleep(100000);
}
```
This prints numbers from 0 to 1000. 

```ballerina
public function main() {
    int i = 0;

    while (i < 1000) {
        var s = start io:println(i);
        i = i + 1;
    }
    runtime:sleep(100000);
}
```
This doesn't produce any output.
It should also have the same behavior as above.

**Comment by gimantha** [comment]
@manuranga 

This is what it prints repeatedly in the ballerina-internal.log

```
[2021-06-16 19:53:48,969] SEVERE {b7a.log.crash} - 'java.lang.Object ballerina.io.0_6_0-beta_1.print.println(io.ballerina.runtime.internal.scheduling.Strand)' 
java.lang.NoSuchMethodError: 'java.lang.Object ballerina.io.0_6_0-beta_1.print.println(io.ballerina.runtime.internal.scheduling.Strand)'
	at gimantha.myProj.0_1_0.tests.$println$lambda$_0$(tests.bal:7)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
```
