### ISSUE TITLE
Debugger hangs for conditional breakpoints with relational operators

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#29619]
**Description:**
$subject and need to improve conditional breakpoint support for the following relational operators

- [ ] > (greater than)
- [ ] < (less than)
- [ ] >= (greater than or equal to)
- [ ] <= (less than or equal to)
- [ ] x is int (type test expression)

**Comment by praveennadarajah** [comment]
Ballerina’s JPDA-based debugger hangs when we evaluate the expression for conditional breakpoints. We observed that the target method to be invoked using ClassType.invokeMethod() throws an uncaught exception, and JDI will hang waiting for response from the target VM.

Ballerina debugger is prepared to deal with asynchronous events coming from the debug process.
https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java#L81

Also it is resuming the target process after the invokeMethod().
https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java#L139

Here is a snippet of the relevant thread dump when the hang occurs:
```
"ForkJoinPool.commonPool-worker-7" #18 daemon prio=5 os_prio=31 cpu=274.40ms elapsed=38.27s tid=0x00007ff297b0b800 nid=0x7303 in Object.wait()  [0x0000700010e90000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11.0.4/Object.java:328)
	at com.sun.tools.jdi.TargetVM.waitForReply(jdk.jdi@11.0.4/TargetVM.java:306)
	- waiting to re-lock in wait() <0x00000007ccb967a8> (a com.sun.tools.jdi.Packet)
	at com.sun.tools.jdi.VirtualMachineImpl.waitForTargetReply(jdk.jdi@11.0.4/VirtualMachineImpl.java:1145)
	at com.sun.tools.jdi.PacketStream.waitForReply(jdk.jdi@11.0.4/PacketStream.java:87)
	at com.sun.tools.jdi.JDWP$ClassType$InvokeMethod.waitForReply(jdk.jdi@11.0.4/JDWP.java:3479)
	at com.sun.tools.jdi.ClassTypeImpl.waitForReply(jdk.jdi@11.0.4/ClassTypeImpl.java:299)
	at com.sun.tools.jdi.InvokableTypeImpl.invokeMethod(jdk.jdi@11.0.4/InvokableTypeImpl.java:113)
	at org.ballerinalang.debugadapter.evaluation.utils.EvaluationUtils.loadClass(EvaluationUtils.java:208)
	at org.ballerinalang.debugadapter.evaluation.utils.EvaluationUtils.getGeneratedMethod(EvaluationUtils.java:165)
	at org.ballerinalang.debugadapter.evaluation.engine.BinaryExpressionEvaluator.compare(BinaryExpressionEvaluator.java:213)
	at org.ballerinalang.debugadapter.evaluation.engine.BinaryExpressionEvaluator.performOperation(BinaryExpressionEvaluator.java:122)
	at org.ballerinalang.debugadapter.evaluation.engine.BinaryExpressionEvaluator.evaluate(BinaryExpressionEvaluator.java:88)
	at org.ballerinalang.debugadapter.evaluation.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:52)
	at org.ballerinalang.debugadapter.JDIEventProcessor.evaluateBreakpointCondition(JDIEventProcessor.java:307)
	at org.ballerinalang.debugadapter.JDIEventProcessor.processEvent(JDIEventProcessor.java:120)
	at org.ballerinalang.debugadapter.JDIEventProcessor.lambda$startListening$0(JDIEventProcessor.java:88)
	at org.ballerinalang.debugadapter.JDIEventProcessor$$Lambda$154/0x00000008002d7c40.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@11.0.4/CompletableFuture.java:1736)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(java.base@11.0.4/CompletableFuture.java:1728)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.4/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.4/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.4/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.4/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.4/ForkJoinWorkerThread.java:177)

   Locked ownable synchronizers:
	- None
```

The complete thread dump when the hang occurs:
[thread_dump_2021-04-01-08:50:37.txt](https://github.com/ballerina-platform/ballerina-lang/files/6256075/thread_dump_2021-04-01-08.50.37.txt)

I have reported this issue in https://bugreport.java.com/bugreport/ and the internal review ID for the above mentioned issue is `9069743`
