### ISSUE TITLE
[Testerina] Refactor exception handling in Test Framework

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29632]
**Description:**
Exception handling in the Test Framework needs to be handled taking various scenarios into account

- [ ] Throw an exception when module init of a imported module
- [x] Throw an exception from interop code
- [ ] Class not found in module init of a imported module
- [x] Class not found in test running
- [x] Class def not found for imported dependencies
- [ ] Class cast when running test function
- [x] Class cast when running module init of a imported module
- [ ] BadSad from user code

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/28151

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Tests with a custom interop throwing exceptions : https://github.com/Ibaqu/TesterinaInteropExceptions

# Testerina Exceptions

## Division by Zero
Divide by Zero locally
Execution of tests continue

```
Compiling source
        mohamedaquibzulfikar/Interop:0.1.0

Running Tests

        Interop

                [fail] test3:

                    {ballerina}DivisionByZero {"message":" / by zero"}

                        at mohamedaquibzulfikar.Interop.0_1_0.tests.main_test:intDiv(tests/main_test.bal:21)
                        mohamedaquibzulfikar.Interop.0_1_0.tests.main_test:test3(tests/main_test.bal:17)


                0 passing
                1 failing
                0 skipped

error: there are test failures
```

## Division by Zero interop
Throws exception and stops test execution

```
Compiling source
        mohamedaquibzulfikar/Interop:0.1.0

Running Tests

        Interop
~ [Ibaqu] Divide Int called
~ [Ibaqu] Divide called. Dividing by Zero
error: java.lang.ArithmeticException: / by zero
error: there are test failures
```

## Throw a NullPointerException directly from the interop
Throws exception and stops the test execution

```
Compiling source
        mohamedaquibzulfikar/Interop:0.1.0

Running Tests

        Interop
~ [Ibaqu] call called. Throwning exception
error: java.lang.NullPointerException
error: there are test failures
```

## Classes not packed in the JAR 

If function is to return a value : 
- Returns the NoClassDefFound error

```
Compiling source
        mohamedaquibzulfikar/Interop:0.1.0

Running Tests

        Interop
~ [Ibaqu] Return Add Int called

                [fail] test2:

                    The test failed normally

                        at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
                        ballerina.test.0_0_0:assertFail(assert.bal:125)
                        mohamedaquibzulfikar.Interop.0_1_0.tests.main_test:test2(tests/main_test.bal:12)

                [fail] test7:

                    java.lang.NoClassDefFoundError {"message":"Aquib","cause":error("java.lang.ClassNotFoundException",message="Aquib")}

                        at mohamedaquibzulfikar.Interop.0_1_0:returnAddInt(main.bal:22)
                        mohamedaquibzulfikar.Interop.0_1_0.tests.main_test:test7(tests/main_test.bal:44)


                0 passing
                2 failing
                0 skipped

error: there are test failures
```

else 
- Doesnt print any sort of error. Just blank

```
Compiling source
        mohamedaquibzulfikar/Interop:0.1.0

Running Tests

        Interop
~ [Ibaqu] Add Int called

                [fail] test2:

                    The test failed normally

                        at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
                        ballerina.test.0_0_0:assertFail(assert.bal:125)
                        mohamedaquibzulfikar.Interop.0_1_0.tests.main_test:test2(tests/main_test.bal:12)

                [pass] test6

                1 passing
                1 failing
                0 skipped

error: there are test failures
```

Execution continues normally

**Comment by Ibaqu** [comment]
Exceptions caused due to an internal Ballerina language error : 

https://github.com/ballerina-platform/ballerina-lang/issues/29795


```
Compiling source
        mohamedaquibzulfikar/Logging:0.1.0

Running Tests

        Logging
error: error("java.lang.NullPointerException")
error: there are test failures
```

` RuntimeUtils.silentlyLogBadSad(e);` prints full stack trace

```
[2021-04-02 14:04:51,698] SEVERE {b7a.log.crash} - error("java.lang.NullPointerException") 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: error("java.lang.NullPointerException")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:554)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:264)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:114)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:116)
	at org.ballerinalang.test.runtime.Main.main(Main.java:97)
Caused by: error("java.lang.NullPointerException")
	at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:127)
	at io.ballerina.runtime.internal.ErrorUtils.createInteropError(ErrorUtils.java:78)
	at ballerina.lang$0046value.1_0_0.value.cloneReadOnly(value.bal:53)
	at mohamedaquibzulfikar.Logging.0_1_0.tests.main_test.$annot_func$_0(tests/main_test.bal:3)
	at mohamedaquibzulfikar.Logging.0_1_0.Logging.$gen$$0046$0060testinit$0062(Logging)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

`RuntimeUtils.silentlyLogBadSad(e.getCause());`
```
[2021-04-05 10:57:11,986] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
error: java.lang.NullPointerException
	at ballerina.lang.value.1_0_0:cloneReadOnly(value.bal:53)
	   mohamedaquibzulfikar.Logging.0_1_0.tests.main_test:$annot_func$_0(tests/main_test.bal:3) 
```

**Comment by Ibaqu** [comment]
Exception when providing invalid class paths when executing Test runner

```
Compiling source
        invalid-data-provider-test.bal

Running Tests

        invalid-data-provider-test.bal
error: java.lang.NoSuchMethodException: invalid-data-provider-test.testInvalidDataProvider(io.ballerina.runtime.internal.scheduling.Strand, long, boolean)
error: there are test failures
```

Stack
```
[2021-04-05 11:38:58,900] SEVERE {b7a.log.crash} - invalid-data-provider-test.testInvalidDataProvider(io.ballerina.runtime.internal.scheduling.Strand, long, boolean) 
java.lang.NoSuchMethodException: invalid-data-provider-test.testInvalidDataProvider(io.ballerina.runtime.internal.scheduling.Strand, long, boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:105)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:58)
	at org.ballerinalang.test.runtime.BTestRunner.invokeTestFunction(BTestRunner.java:616)
	at org.ballerinalang.test.runtime.BTestRunner.executeFunction(BTestRunner.java:416)
	at org.ballerinalang.test.runtime.BTestRunner.lambda$executeTests$1(BTestRunner.java:309)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.test.runtime.BTestRunner.executeTests(BTestRunner.java:297)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:268)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:114)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:116)
	at org.ballerinalang.test.runtime.Main.main(Main.java:97)
```

**Comment by Ibaqu** [comment]
Exception in Kafka module

```
Compiling source
        mohamedaquibzulfikar/Logging:0.1.0

Running Tests

        Logging
error: error("java.lang.NullPointerException")
error: there are test failures
```

Stack 
```
[2021-03-11 15:45:52,287] SEVERE {b7a.log.crash} - error("java.lang.NullPointerException") 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: error("java.lang.NullPointerException")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:553)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:265)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:115)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:115)
	at org.ballerinalang.test.runtime.Main.main(Main.java:96)
Caused by: error("java.lang.NullPointerException")
	at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:127)
	at io.ballerina.runtime.internal.ErrorUtils.createInteropError(ErrorUtils.java:78)
	at ballerinax.kafka.2_1_0-alpha5.producer_utils.producerInit(producer_utils.bal:259)
	at ballerinax.kafka.2_1_0-alpha5.$value$Producer.init(producer.bal:38)
	at ballerinax.kafka.2_1_0-alpha5.$value$Producer.call(producer.bal)
	at ballerinax.kafka.2_1_0-alpha5.$value$Producer.$init$(producer.bal:23)
	at ballerinax.kafka.2_1_0-alpha5.$value$Producer.call(producer.bal)
	at ballerinax.kafka.2_1_0-alpha5.kafka.$gen$ballerinax$0047kafka$00582$00461$00460-alpha5$0046$0060init$00620(kafka:42)
	at ballerinax.kafka.2_1_0-alpha5.kafka.$gen$$0046$0060testinit$0062(kafka:244)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Ibaqu** [comment]
Class cast in log module

Stack 
```
[2021-03-10 09:28:44,406] SEVERE {b7a.log.crash} - Dependant module initialization for test suite failed due to java.lang.ExceptionInInitializerError 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: Dependant module initialization for test suite failed due to java.lang.ExceptionInInitializerError
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:547)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:265)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:115)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:115)
	at org.ballerinalang.test.runtime.Main.main(Main.java:96)
Caused by: java.lang.ExceptionInInitializerError
	at ballerina.log.1_1_0-alpha5.natives.setGlobalLogLevelExtern(natives.bal:174)
	at ballerina.log.1_1_0-alpha5.natives.initializeLogLevels(natives.bal:168)
	at ballerina.log.1_1_0-alpha5.init.init(init.bal:21)
	at ballerina.log.1_1_0-alpha5.$_init.$gen$$0046$0060init$0062(log:1)
	at ballerina.log.1_1_0-alpha5.$_init.$moduleInit(log)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class java.util.logging.LogManager cannot be cast to class org.ballerinalang.logging.BLogManager (java.util.logging.LogManager is in module java.logging of loader 'bootstrap'; org.ballerinalang.logging.BLogManager is in unnamed module of loader 'app')
	at org.ballerinalang.stdlib.log.AbstractLogFunction.<clinit>(AbstractLogFunction.java:38)
	... 14 more
 ```
