### ISSUE TITLE
Intermittent test failure in master for :ballerina-cli:test

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#29633]
**Description:**
Noticed intermittent `:ballerina-cli:test` failure in master for the last couple of days. 

Experienced today as well for PR #29351 for 46ff43575043cc2331e4334bbd51d6a233516b69. (https://github.com/ballerina-platform/ballerina-lang/runs/2199038738)
But, syncing again with master and letting re-run the jobs get the build passed.

**Comment by lochana-chathura** [comment]
Failed again for #29248.

</details>
<details>
  <summary><b>log for the failing part</b>  (<i>click to expand</i>)</summary>

```java
commands-test-suite > command-tests > io.ballerina.cli.cmd.AddCommandTest > testAddCommandWithoutProject STANDARD_OUT
    ballerina: not a ballerina project (or any parent up to mount point)
    You should run this command inside a ballerina project


Running Tests

	winery

		[fail] testRunMain:

		    Failed!

		    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_0_0:assertTrue(assert.bal:53)
		    	foo.winery.0_1_0.tests.main_tests:testRunMain(tests/main_tests.bal:5)


		0 passing
		1 failing
		0 skipped


Running Tests

	winery

		No tests found


	winery.storage

		No tests found


Running Tests

	winery

		[pass] testRunMain

		1 passing
		0 failing
		0 skipped


Running Tests

	winery

		[pass] testRunMain

		1 passing
		0 failing
		0 skipped


Running Tests

	winery
Error: Exception in thread "main" java.io.FileNotFoundException: C:\Users\RUNNER~1\AppData\Local\Temp\b7a-cmd-test-4787296999007856051342127036168\build-test-resources\validProjectWithBuildOptions\target\cache\tests_cache\winery\module_status.json (Access is denied)

		[pass] testRunMain
	at java.base/java.io.FileOutputStream.open0(Native Method)

	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
		1 passing
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
		0 failing
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
		0 skipped
	at org.ballerinalang.test.runtime.Main.writeStatusToJsonFile(Main.java:133)

	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:121)
	at org.ballerinalang.test.runtime.Main.main(Main.java:97)

commands-test-suite > command-tests > io.ballerina.cli.cmd.BuildCommandTest > testSingleFileWithBuildOptions FAILED
    java.lang.AssertionError: error: error occurred while running testsjava.nio.file.AccessDeniedException: C:\Users\RUNNER~1\AppData\Local\Temp\b7a-cmd-test-4787296999007856051342127036168\build-test-resources\validProjectWithBuildOptions\target\cache\tests_cache\winery\module_status.json
        at org.testng.Assert.fail(Assert.java:96)
        at io.ballerina.cli.cmd.BuildCommandTest.testSingleFileWithBuildOptions(BuildCommandTest.java:429)

Running Tests

	winery.storage

		[pass] beforeFunc

		1 passing
		0 failing
		0 skipped


	winery

		[pass] beforeFunc

		1 passing
		0 failing
		0 skipped


Running Tests

	winery

		[pass] testRunMain

		1 passing
		0 failing
		0 skipped
```		
</details>
