### ISSUE TITLE
Immutable cyclic union results in a bad, sad error at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29654]
**Description:**
$title.

Note: currently the name of the immutable type seems to be the same as the original type for unions. https://github.com/ballerina-platform/ballerina-lang/pull/29362 fixes the name, but it still fails.

**Steps to reproduce:**
```ballerina
import ballerina/lang.value;

public function main() {
    value:Cloneable & readonly x = 1;
}
```

```log
[2021-03-27 00:31:42,874] SEVERE {b7a.log.crash} - $type$Cloneable 
java.lang.NoSuchFieldError: $type$Cloneable
	at foo.main(foo.bal:4)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Error with change in #29362.
```log
[2021-03-27 00:33:10,004] SEVERE {b7a.log.crash} - $type$(Cloneable & readonly) 
java.lang.NoSuchFieldError: $type$(Cloneable & readonly)
	at ballerina.lang$0046value.1_0_0.$_init.$populate$type$Cloneable(lang.value)
	at ballerina.lang$0046value.1_0_0.$_init.$createTypes(lang.value)
	at ballerina.lang$0046value.1_0_0.$_init.$currentModuleInit(lang.value)
	at ballerina.lang$0046value.1_0_0.$ConfigurationMapper.$initAndPopulateConfigData(Unknown Source)
	at $ConfigurationMapper.$configureInit(Unknown Source)
	at $_init.main(.)
```

**Affected Versions:**
Current master

**Comment by MaryamZi** [comment]
Does not happen for all cyclic unions though. The following doesn't result in a bad, sad error.

```ballerina
type MyCyclicUnion int|MyCyclicUnion[];

public function main() {
    MyCyclicUnion & readonly x = [1, 2];
}
```
