### ISSUE TITLE
Error initialising Counter

### ISSUE THREAD

**Issue by bondowe** [ballerina-platform/ballerina-lang#29754]
**Description:**
Failing to initialize `observe:Counter`.

**Steps to reproduce:**
Run the following

```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/observe;
import ballerinax/prometheus as _;

observe:Counter globalCounter = new ("total_orders", desc = "Total quantity required");

service /onlineStoreService on new http:Listener(9090) {
    
    resource function get makeOrder(http:Caller caller, http:Request req) {
        globalCounter.increment();

        http:Response res = new;

        res.setPayload("Order Processed!");

        var result = caller->respond(res);
        if (result is error) {
            log:printError("Error sending response", err = result.toString());
        }
    }
}
```

[2021-03-31 18:13:33,671] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.observability.metrics.Counter$Builder.build(Counter.java:84)
	at org.ballerinalang.observe.nativeimpl.CounterInitialize.initialize(CounterInitialize.java:35)
	at ballerina.observe.0_9_0.natives.externCounterInit(natives.bal:163)
	at ballerina.observe.0_9_0.$value$Counter.init(natives.bal:123)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at ballerina.observe.0_9_0.$value$Counter.$init$(natives.bal:98)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at elondombonze.hierar.0_1_0.hierar.$gen$elondombonze$0047hierar$00580$00461$00460$0046$0060init$00620(hierar:6)
	at elondombonze.hierar.0_1_0.$_init.$gen$$0046$0060init$0062(hierar:0)
	at elondombonze.hierar.0_1_0.$_init.$moduleInit(hierar)
	at elondombonze.hierar.0_1_0.$_init.$lambda$$moduleInit$(hierar)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)

**Affected Versions:**
slalpha3

**OS, DB, other environment details and versions:**
Windows 10 Pro for Workstations

**Comment by madushajg** [comment]
Hi @bondowe 
This can happen when the observability is not packed to the executable JAR file(s). There is a build time flag to enable/disable this (enabled by default).

If you are running this as a ballerina project, can you please share your `Ballerina.toml` file? It should contain the following entry to package observability to the executable JAR(s).
```
[build-options]
observabilityIncluded = true
```

Or if you are running this as a standalone ballerina file, can you try building this like the following?
```
bal build --observability-included hierar.bal  
```

**Comment by bondowe** [comment]
Hi @madushajg,

thanks for your reply.
Building works, it's just that you can't run it with `bal run`. 

![image](https://user-images.githubusercontent.com/1747482/121534403-1a498e80-c9f9-11eb-921d-2e96ab8e72c8.png)

Error:

[2021-06-10 14:37:32,760] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.observability.metrics.Counter$Builder.build(Counter.java:84)
	at org.ballerinalang.observe.nativeimpl.CounterInitialize.initialize(CounterInitialize.java:35)
	at ballerina.observe.0_9_0.natives.externCounterInit(natives.bal:163)
	at ballerina.observe.0_9_0.$value$Counter.init(natives.bal:123)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at ballerina.observe.0_9_0.$value$Counter.$init$(natives.bal:98)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at $$$.$gen$$0046$0046$0060init$00620(.:6)
	at $_init.$gen$$0046$0060init$0062(.:0)
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2021-06-10 14:37:32,780] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.observability.metrics.Counter$Builder.build(Counter.java:84)
	at org.ballerinalang.observe.nativeimpl.CounterInitialize.initialize(CounterInitialize.java:35)
	at ballerina.observe.0_9_0.natives.externCounterInit(natives.bal:163)
	at ballerina.observe.0_9_0.$value$Counter.init(natives.bal:123)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at ballerina.observe.0_9_0.$value$Counter.$init$(natives.bal:98)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at $$$.$gen$$0046$0046$0060init$00620(.:6)
	at $_init.$gen$$0046$0060init$0062(.:0)
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by madushajg** [comment]
Hi @bondowe 

Can you check whether you have placed the `Config.toml` file with the required configurations as per the [documentation](https://ballerina.io/learn/user-guide/observability/observing-ballerina-code/#monitoring-metrics)?

e.g:
```
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"

[ballerinax.prometheus]
port=9797
host="0.0.0.0"
```
