### ISSUE TITLE
Getting NPEs when testing the same ballerina program with multiple ballerina version

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#29784]
**Description:**
I had a simple HTTP client sample that was working fine with alpha2. but when I try to test with alpha 4 I got the below error.
```
[2021-03-31 10:54:31,674] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.defineErrorDetailRecord(SymbolResolver.java:1897)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.defineIntersectionType(SymbolResolver.java:1888)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.computeIntersectionType(SymbolResolver.java:1836)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:1103)
	at org.wso2.ballerinalang.compiler.tree.types.BLangIntersectionTypeNode.accept(BLangIntersectionTypeNode.java:48)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:459)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:450)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1322)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:111)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineIntersectionTypes(SymbolEnter.java:422)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:386)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:300)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:255)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:368)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileIfRequired(PackageCompilation.java:148)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:102)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:118)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:257)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 ```

**Comment by warunalakshitha** [comment]
I had delete Dependency.toml file to build the program.

**Comment by pramodya1994** [comment]
This is not reproducible with beta1 and cannot be reproduced using alpha2 pack due to syntax changes.
