### ISSUE TITLE
[Testerina] Test Suite initialization for modules fails when there are more than one non default modules with only test sources

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29898]
**Description:**
$subject

Fails at the test initialization phase. This can affect the default module as well since having a singular test folder without any source files causes the issue
**Steps to reproduce:**
Create modules with only test folders and test files and execute the test command

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadundesilva** [comment]
Even with a test sources, it fails when I add a simple service.

**File to which I added the service**
```ballerina
$ cat modules/mod1/tests/test_1.bal 
import ballerina/test;
import ballerina/http;
service /test on new http:Listener(9091) {
    resource function get sum(http:Caller caller, http:Request req) {
        http:Response resp = new;
        resp.setTextPayload(<@untainted> "Hello");
        checkpanic caller->respond(resp);
    }
}
@test:Config { }
public function test1() {
    test:assertTrue(true);
}
```

**Console output**
```bash
$ bal test
Compiling source
	nadun/temp:0.1.0
Running Tests
	temp
		[pass] test1
		1 passing
		0 failing
		0 skipped
	temp.mod2
		[pass] test2
		1 passing
		0 failing
		0 skipped
	temp.mod1
error: Test module initialization for test suite failed due to java.lang.NoSuchFieldError: $type$$anonType$_0
error: there are test failures
```

**ballerinal-internal.log**
```
[2021-04-07 16:59:05,634] SEVERE {b7a.log.crash} - Test module initialization for test suite failed due to java.lang.NoSuchFieldError: $type$$anonType$_0 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: Test module initialization for test suite failed due to java.lang.NoSuchFieldError: $type$$anonType$_0
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:556)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:264)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:114)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:76)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:116)
	at org.ballerinalang.test.runtime.Main.main(Main.java:97)
Caused by: java.lang.NoSuchFieldError: $type$$anonType$_0
	at nadun.temp$0046mod1.0_1_0.temp$$$mod1.$gen$$0046$0060testinit$0062(temp.mod1:4)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Dilhasha** [comment]
@Ibaqu We can reproduce the issue even with source file in default module and only tests in non default modules. Let's prioritise and address this issue as discussed.

**Comment by Dilhasha** [comment]
These are the findings so far for the NPE.

1. This happens when there are more than one non default modules with only test sources. When there are multiple non default modules, the behaviour is not consistent.

2. The NPE is thrown from Scheduler when trying execute the strands related to module initialisation.

3. This is reproducible since SL Alpha3 and we suspect it's coming from a class loading issue due to the changes done to use a single JVM for running tests in all the modules instead of separate JVMs.
