### ISSUE TITLE
Bad sad error when casting to inline record type

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#29965]
**Description:**
$title

**Steps to reproduce:**
Refer the following code where the return type is cast to the inline record type. The resource definitions and schemas were generated from an open API spec using the open-api tool. 
Note that Error is a record (as generated from the tool) and hence the approach with casting. Please suggest if there is a different way to achieve this. 

```
import  ballerina/http;

listener  http:Listener  ep0  = new (8085);

service  /v1  on  ep0  {

    resource function post developers(@http:Payload Developer payload) 
            returns record {| *http:Created; Developer  body; |}|Error {
        Developer dev1 = {id: "123", name: "Jane Doe"};
        return <record {| *http:Created; Developer  body; |}>{body: dev1};
    }
    
}
```

```
type  Error record  { 
    string  errorType?;
    string  message?;
};

type  Developer record  { 
    string  id?;
    string  name?;
    string  team?;
    string[]  skils?;
    string  createdAt?;
    string  updatedAt?;
};
```

```
[2021-04-10 19:31:15,921] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsPureTypeUniqueVisitor.visit(IsPureTypeUniqueVisitor.java:252)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:281)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:293)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAnydata(Types.java:327)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:706)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:647)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$resolveReferencedFields$32(SymbolEnter.java:4044)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveReferencedFields(SymbolEnter.java:4052)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveFields(SymbolEnter.java:3242)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFieldsOfObjectOrRecordTypeDef(SymbolEnter.java:3174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFields(SymbolEnter.java:3140)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:388)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:305)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:260)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:369)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:160)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:130)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:168)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 

```
**Affected Versions:** Swan Lake Alpha 3

**OS, DB, other environment details and versions:** OSX

**Related Issues (optional):**
This was an alternative approach suggested to resolve issue reported in https://github.com/ballerina-platform/ballerina-lang/issues/29753
Also see : https://ballerina-platform.slack.com/archives/C47EAELR1/p1617191396102900

**Comment by MaryamZi** [comment]
When the records are defined before the service, the compiler crashes at BIRTypeWriter.

```log
 
[2021-04-11 00:07:07,849] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.writer.BIRTypeWriter.visitType(BIRTypeWriter.java:99)
	at org.wso2.ballerinalang.compiler.bir.writer.ConstantPool.writeToStream(ConstantPool.java:127)
	at org.wso2.ballerinalang.compiler.bir.writer.ConstantPool.serialize(ConstantPool.java:68)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:94)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:269)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:389)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:147)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:133)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:107)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:106)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

Also reproducible with
```ballerina
type Foo record {|
    int x = 1;
|};

type Bar record {|
    string y;
|};

public function main() {
    var rec = <record {| *Foo; Bar body; |}>{body: {y: "123"}};
}
```
