### ISSUE TITLE
Compiler crash after building the project for the second time after installing ballerina as root in ubuntu

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#30064]
After installing the ballerina following Linux instructions as the root (Ubuntu 20.04.2 LTS), compiler crashes when building a project without root access for the second time.

Ballerina version : Ballerina Swan Lake Alpha 4

ballerina-internal.log output is shown below
`[2021-04-19 11:51:25,167] SEVERE {b7a.log.crash} - Failed to write library: /home/damitha/Documents/balHello/helloworld/target/cache/damitha/helloworld/0.1.0/java11/helloworld.connection.jar 
java.lang.RuntimeException: Failed to write library: /home/damitha/Documents/balHello/helloworld/target/cache/damitha/helloworld/0.1.0/java11/helloworld.connection.jar
	at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:114)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:271)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:399)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:145)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:131)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:105)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:251)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.io.IOException: File '/home/damitha/Documents/balHello/helloworld/target/cache/damitha/helloworld/0.1.0/java11/helloworld.connection.jar' cannot be written to
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:355)
	at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2222)
	at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2186)
	at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2171)
	at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:111)`

**Comment by azinneera** [comment]
**Steps to reproduce**
1. Create a new ballerina package with the normal user 
`bal new proj1`
2. Navigate into the package root and execute with root user
`sudo bal build`
3. Rebuild using normal user
`bal build`

This exception is thrown the user does not have permission to the target directory since its first run with root user. We need to give a proper error for this. ATM we check the permission of the package root. Checking the permissions for target also should resolve the issue
