### ISSUE TITLE
[Testerina] Jacoco code coverage throws a MethodTooLarge exception for certain services

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#30091]
**Description:**

This is thrown from the ballerina project after the tests are executed at the code coverage generation phase.

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting cookie/logging/0_1_0/$value$Service$$service$_2.
        at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:94)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_6(logging:61)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_5(logging:12)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_4(logging:31)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_3(logging:29)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_2(logging:22)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_1(logging:15)
        at cookie.logging.0_1_0.logging.$cookie_logging_0_1_0__init_0(logging:38)
        at cookie.logging.0_1_0.$_init.$cookie_logging_0_1_0__init_(logging:18)
        at cookie.logging.0_1_0.$_init.$moduleInit(logging)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
        at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
        at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
        at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Error while instrumenting cookie/logging/0_1_0/$value$Service$$service$_2.
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:110)
        at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:92)
        ... 30 more


Caused by: org.jacoco.agent.rt.internal_f3994fa.asm.MethodTooLargeException: Method too large: cookie/logging/0_1_0/$value$Service$$service$_2.getZippedLogs (Lio/ballerina/runtime/scheduling/Strand;Lio/ballerina/runtime/api/values/BObject;ZLio/ballerina/runtime/api/values/BObject;ZLio/ballerina/runtime/api/values/BString;Z)Ljava/lang/Object;
         at org.jacoco.agent.rt.internal_f3994fa.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
         at org.jacoco.agent.rt.internal_f3994fa.asm.ClassWriter.toByteArray(ClassWriter.java:496)
         at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:91)
         at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:108)
         ... 31 more
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
https://stackoverflow.com/questions/37666076/jacoco-method-code-too-large-when-using-ver-0-7-6-and-0-7-5

**Comment by Ibaqu** [comment]
This issue happens when the class processed by Jacoco exceeds the size limit of a class that can be processed. 

As quoted in a similar issue : 
> There is no way to increase this limit, because it comes from Java Virtual Machine Specification, which states that
`The value of the code_length item must be less than 65536`
> During instrumentation JaCoCo adds instructions to bytecode to record coverage, so that after instrumentation method can become too big violating the statement above.

**Comment by LakshanKarunathilake** [comment]
We tried with the ballerina alpha 4, issue is still there 

```

	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Error while instrumenting choreo/loggingapi/0_1_0/$value$$anonType$_36.
	at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
	at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:110)
	at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:92)
	... 28 more
Caused by: org.jacoco.agent.rt.internal_f3994fa.asm.MethodTooLargeException: Method too large: choreo/loggingapi/0_1_0/$value$$anonType$_36.$get$apps$*$logs$zip (Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;ZLio/ballerina/runtime/api/values/BObject;ZLio/ballerina/runtime/api/values/BObject;Z)Ljava/lang/Object;
	at org.jacoco.agent.rt.internal_f3994fa.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
	at org.jacoco.agent.rt.internal_f3994fa.asm.ClassWriter.toByteArray(ClassWriter.java:496)
	at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:91)
	at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:108)
	... 29 more


```

**Comment by LakshanKarunathilake** [comment]
I tried this with a hello world service, containing 125 log lines. And now it is complaining that the resource is too large

```
Compiling source
        lakshan/test_testarina:0.1.0
ERROR [service.bal:(13:5,128:6)] method is too large: '$get$sayHello'
error: compilation contains errors
```

**Comment by Ibaqu** [comment]
Related Issue : https://github.com/ballerina-platform/ballerina-lang/issues/29137

**Comment by Ibaqu** [comment]
https://stackoverflow.com/questions/49296416/how-to-prevent-jacoco-instrumenting-production-code

> JaCoCo provides two ways of performing instrumentation:
> 
> so-called "on-the-fly" using Java Agent - http://www.jacoco.org/jacoco/trunk/doc/agent.html
> and so-called "offline" - http://www.jacoco.org/jacoco/trunk/doc/offline.html
> The difference is that in first case instrumentation happens in memory during execution and so no class or jar files will be changed on disk - quoting the second link:
> 
> One of the main benefits of JaCoCo is the Java agent, which instruments classes on-the-fly. This simplifies code coverage analysis a lot as no pre-instrumentation and classpath tweaking is required.

**Comment by Dilhasha** [comment]
This issue still exists. Please refer to the issue https://github.com/ballerina-platform/ballerina-lang/issues/29137#issuecomment-832630725 for more information.

You can overcome the issue by splitting the method.

**Comment by pubudu91** [comment]
This issue is still there in `2201.1.0`. Is there anything we can do for this? I don't think we can keep asking people to split the method since this occurs for fairly small methods as well. For example, I get this when I have the following in a test source.
```ballerina
import ballerina/http;
import ballerina/test;
import choreo/mediation;

service on new http:Listener(9090) {

    resource function get hello(http:Request req, http:Caller caller, string url) returns error? {
        mediation:Context mediationCtx = {httpMethod: "get", resourcePath: string `/greet`};
        http:Response? backendResponse;

        do {
            {
                var x = check addHeader_In(req, mediationCtx, "foo", "Foo");

                if x is false {
                    check caller->respond(http:INTERNAL_SERVER_ERROR);
                    return;
                } else if x is http:Response {
                    check caller->respond(x);
                    return;
                }
            }

            http:Client ep = checkpanic new (url);
            backendResponse = check ep->execute(mediationCtx.httpMethod, mediationCtx.resourcePath, req, targetType = http:Response);

            {
                var x = check addHeader_Out(<http:Response>backendResponse, req, mediationCtx, "bar", "Bar");

                if x is false {
                    check caller->respond(http:INTERNAL_SERVER_ERROR);
                    return;
                } else if x is http:Response {
                    check caller->respond(x);
                    return;
                }
            }

            check caller->respond(backendResponse);
        } on fail var e {
            http:Response errFlowResponse = new;
            errFlowResponse.statusCode = http:STATUS_INTERNAL_SERVER_ERROR;

            {
                var v = addHeader_Fault(errFlowResponse, e, backendResponse, req, mediationCtx, "baz", "Baz");

                if v is false|error {
                    check caller->respond(errFlowResponse);
                    return;
                } else if v is http:Response {
                    check caller->respond(v);
                    return;
                }
            }

            check caller->respond(errFlowResponse);
        }
    }
}

service on new http:Listener(8080) {
    resource function get greet(http:Request req) returns json {
        string[]|http:HeaderNotFoundError headers = req.getHeaders("foo");

        if headers is http:HeaderNotFoundError {
            test:assertFail("Header 'foo' not found");
        }

        test:assertEquals(headers, ["Foo"]);
        return {"greeting": "Hello World!"};
    }
}
```
From my observations, it looks like using `check` seems to add a quite a bit of code. Will open a separate issue on that.

**Comment by Dilhasha** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/29137 introduced code generation improvements for the mentioned issue. Hence, closing.
