### ISSUE TITLE
Bad, sad with distinct error type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30117]
`bal run` on this gets a Bad, Sad

```
type JsonParseDetail record {
    string s;
};

type JsonParseError error<JsonParseDetail> & distinct error;
```

ballerina-internal.log is

```
[2021-04-21 11:19:24,918] SEVERE {b7a.log.crash} - $type$ 
java.lang.NoSuchFieldError: $type$

	at $_init.$gen$$0046$0060init$0062(.:1)
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
[2021-04-21 11:19:24,933] SEVERE {b7a.log.crash} - $type$ 
java.lang.NoSuchFieldError: $type$
	at $_init.$gen$$0046$0060init$0062(.:1)
	at $_init.$moduleInit(.)
	at $_init.$lambda$$moduleInit$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
 ```

**Comment by jclark** [comment]
Not sure if this is related to #30116.
