### ISSUE TITLE
Can't create an array of record with a closure type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#30145]
**Description:**
```ballerina
import ballerina/io;

public function main() {
    int j = 9;
    record {| int i = j; |}[] a = [];
    io:println(a);
}
```
Get below exception when building.
```
[2021-04-21 22:53:42,231] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$BSameTypeVisitor.visit(Types.java:2365)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$BSameTypeVisitor.visit(Types.java:2344)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BType.accept(BType.java:86)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:332)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:304)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:8423)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2289)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:80)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7741)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createStructFieldUpdate(Desugar.java:8785)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createStructFieldUpdate(Desugar.java:8766)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1114)
	at org.wso2.ballerinalang.compiler.tree.types.BLangRecordTypeNode.accept(BLangRecordTypeNode.java:42)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1150)
	at org.wso2.ballerinalang.compiler.tree.types.BLangArrayType.accept(BLangArrayType.java:60)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1340)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1473)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7741)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7751)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1240)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1285)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7758)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:797)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7700)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:453)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:389)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:147)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:133)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:107)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:106)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:251)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Could be related to https://github.com/ballerina-platform/ballerina-lang/issues/27583.
