### ISSUE TITLE
Implement validations for Dependencies.toml

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#30221]
**Description:**
The current set of validations for Dependencies.toml is not adequate. This results in BadSad and skipping of dependency entries when building a package. We need to add validations such as required fields and regex for field values. 

**Steps to reproduce:**
1. When a required key is not present:
    ```toml
    [[dependency]]
    name = "foo1"
    version = "0.1.0"
    ```
    _Current behavior:_ Build failure with a BadSad
    ballerina-internal.log
    ```
    [2021-04-27 23:08:51,099] SEVERE {b7a.log.crash} - null 
    java.lang.NullPointerException
            at io.ballerina.projects.internal.ManifestBuilder.getStringFromTomlTableNode(ManifestBuilder.java:485)
            at io.ballerina.projects.internal.ManifestBuilder.getStringValueFromDependencyNode(ManifestBuilder.java:473)
            at io.ballerina.projects.internal.ManifestBuilder.getDependencies(ManifestBuilder.java:290)
            at io.ballerina.projects.internal.ManifestBuilder.parseAsPackageManifest(ManifestBuilder.java:185)
            at io.ballerina.projects.internal.ManifestBuilder.<init>(ManifestBuilder.java:101)
            at io.ballerina.projects.internal.ManifestBuilder.from(ManifestBuilder.java:107)
            at io.ballerina.projects.internal.PackageConfigCreator.createBuildProjectConfig(PackageConfigCreator.java:70)
            at io.ballerina.projects.directory.BuildProject.load(BuildProject.java:89)
            at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:219)
            at java.base/java.util.Optional.ifPresent(Optional.java:183)
            at io.ballerina.cli.launcher.Main.main(Main.java:58)
    ```
    _Expected behavior:_
    `ERROR [Dependencies.toml:(3:1,3:1)] 'org' under [[dependency]] is missing`

2.  When a value is not present
      ```toml
      [[dependency]]
      org =
      name = "foo1"
      version = "0.1.0"
      ```
      _Output:_ Build failure with a BadSad
      ballerina-internal.log (same output as above)

3. When a value doesn't match the expected regex
    ```toml
    [[dependency]]
    org = "foo-1"
    name = "proj"
    version = "0.1.0"
    ```
    _Current behavior:_ Ignores the entry and continues execution
    _Expected behavior:_
        `ERROR [Dependencies.toml:(3:1,3:1)] invalid 'org' under [[dependency]]: 'org' can only contain alphanumerics, underscores and the maximum length is 256 characters`

**Affected Versions:**
At least slalpha5

**Comment by azinneera** [comment]
Blocked by #30304
