### ISSUE TITLE
CCE with nested error binding pattern in destructuring assignment statement

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30275]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main(){
    [int, error] t = [12, error("error!", message = "error message")];

    int i;
    string m;
    any|error n;

    error(m, message = n) = t[1]; // Works.

    [i, error(m, message = n)] = t; // Crashes.
}
```

```log
[2021-05-01 21:11:52,936] SEVERE {b7a.log.crash} - class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.IdentifierToken (io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode and io.ballerina.compiler.syntax.tree.IdentifierToken are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.IdentifierToken (io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode and io.ballerina.compiler.syntax.tree.IdentifierToken are in unnamed module of loader 'app')
	at io.ballerina.compiler.syntax.tree.NamedArgBindingPatternNode.argName(NamedArgBindingPatternNode.java:36)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2434)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.NamedArgBindingPatternNode.apply(NamedArgBindingPatternNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2420)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.ErrorBindingPatternNode.apply(ErrorBindingPatternNode.java:63)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:4981)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2365)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.ListBindingPatternNode.apply(ListBindingPatternNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:4981)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTupleDestructureStatement(BLangNodeTransformer.java:2525)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2503)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.AssignmentStatementNode.apply(AssignmentStatementNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4853)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1458)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1365)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1345)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1323)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:592)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:505)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:365)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slalpha5

**Comment by MaryamZi** [comment]
Need to enable relevant tests in org.ballerinalang.test.expressions.varref.ErrorVariableReferenceTest when fixing this.

**Comment by rpjayasekara** [comment]
> @rpjayasekara, the issue is moved to `PR Sent` category in the project board, but PR is not tagged. Can you tagged the PR to issue?

Now this CCE is not raised as now this binding pattern is now allowed by the compiler. I have added few negative test cases for this https://github.com/ballerina-platform/ballerina-lang/pull/35227

**Comment by rpjayasekara** [comment]
This is fixed now. Added tests in https://github.com/ballerina-platform/ballerina-lang/pull/35227
