### ISSUE TITLE
Intersection of two records cause an NPE

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30401]
**Description:**
Consider the following code snippet:
```
type Foo record {|
    int i;
|};

type Bar record {
    int i;
};

type FooBar Foo & Bar;
```

It cause an NPE with the following logs:
```
[Error - 5:03:23 PM] Operation 'ballerinaDocument/executorPositions' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/projects/lstest/intersection_types.bal', error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getAllTypes(Types.java:4778)'}
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getAllTypes(Types.java:4778)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4069)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.createRecordIntersection(Types.java:4341)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersection(Types.java:4106)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4072)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.getPotentialIntersection(SymbolResolver.java:2094)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.computeIntersectionType(SymbolResolver.java:1914)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:1109)
	at org.wso2.ballerinalang.compiler.tree.types.BLangIntersectionTypeNode.accept(BLangIntersectionTypeNode.java:48)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:479)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:470)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1369)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:111)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:272)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:1108)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:381)
```

_**This cause a bad sad error when compiled**_

**Steps to reproduce:**
See description above

**Affected Versions:**
Beta1 SNAPSHOT

**Related Issues (optional):**
#30118

**Suggested Labels (optional):**
Semantic API

**Comment by MaryamZi** [comment]
I don't think we've allowed record intersections yet (other than via error intersections). Until we fully support this, this should result in a compilation error to say it is not supported yet.

Adding generic intersection type support is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/24078
