### ISSUE TITLE
NPE at PositionUtil.withinRange() 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#30441]
**Description:**
Getting an NPE at PositionUtil.withinRange()  when getting the reference of a function name with the following code snippet. See the steps
```ballerina
function name() {
    var p = { a: "foo"};
}
```
**Steps to reproduce:**
![Peek 2021-05-07 19-12](https://user-images.githubusercontent.com/25485997/117458804-4f7d3f80-af68-11eb-99ff-fa0c830f30fd.gif)

**Ballerina output log**
```
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:63)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:223)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:205)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupEnclosingContainer(NodeFinder.java:214)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:186)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:166)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:86)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:84)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$references$6(BallerinaTextDocumentService.java:281)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
beta-1

**Note**
To see the above stack trace, The `null` checking must be reverted back to the previous code in the `PositionUtil.withinRange()`

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
This is partially fixed with #30434. But the root cause is not fixed yet.
