### ISSUE TITLE
Bad, sad error when a wildcard binding pattern is used in the rest pattern in an error binding pattern

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30480]
**Description:**
$title.

This should probably result in a compilation error since `rest-binding-pattern` is `... variable-name` and `variable-name` is `identifier`.

This runs without an issue for error match pattern, but that should probably fail too.

**Steps to reproduce:**
```ballerina
function func(any|error f) {
    match f {
        var error (message, ..._) => {
            
        }
    }
}
```

```log
[2021-05-10 23:22:53,062] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1541)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1253)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1229)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:80)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1559)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1253)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1541)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1559)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1253)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1541)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1253)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1541)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:746)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:697)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:400)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:400)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:150)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:108)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:107)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:169)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Related Issues:**
May be related to https://github.com/ballerina-platform/ballerina-lang/issues/30470

**Affected Versions:**
slbeta1

**Comment by MaryamZi** [comment]
Need to enable/remove relevant tests in org.ballerinalang.test.statements.matchstmt.MatchStructuredErrorPatternsTest.

**Comment by lochana-chathura** [comment]
Depends on #30470.
