### ISSUE TITLE
Issues with intersection logic with intersection types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30680]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public type Bar record {|
    record {|
        string s;
    |} baz?;
|};

public function main() {
    // Works if this.
    // Bar? bar = ();

    Bar? & readonly bar = ();

    if bar is Bar {
        // No error for this!
        // var t = bar?.t;

        // No error for this!
        // boolean x = bar?.baz;

        // Crashes at BIR Gen.
        record {| string s; |}? y = bar?.baz;
    }
}
```

```log
[2021-05-19 19:34:02,273] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:630)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1693)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1203)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1559)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:746)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:697)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:400)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:400)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:156)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:66)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slbeta1-rc1

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/30682.
