### ISSUE TITLE
[LS] CCE when hovering return type descriptor of a function

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30697]
**Description:**
Consider the following code snippet. 
```

# Given the last used ID, this will return the next ID to be used
# for required purposes
#
# + lastId - Last used ID
# + return - Next ID to be used
public function generateId(int lastId) returns int {
    return lastId + 1;
}

public function func() returns string {
    return "";
}
```
When we hover over the return type descriptor of any of the functions, it prints a CCE. For the 1st function, the error is this:
```
[Error - 6:12:53 PM] Operation 'text/hover' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/single/documentation.bal', [7:48], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.hover.HoverUtil.getHoverForSymbol(HoverUtil.java:96)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:74)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:161)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 1 snapshot

**Suggested Labels (optional):**
Language Server

**Comment by malinthar** [comment]
This seems to occur with all the  ypes that are not type references(type definitions). For instance int, string.
