### ISSUE TITLE
ballerina: Oh no, something really went wrong. Bad. Sad.

### ISSUE THREAD

**Issue by PowellDean** [ballerina-platform/ballerina-lang#30707]
I'm working through the examples for creating modules (https://ballerina.io/learn/user-guide/structuring-ballerina-code/working-with-ballerina-modules/). The main.bal file I entered by hand looked like so:

```
import ballerina/io;
import powelldean/winery.storage;
import winery.model;

public function main() {
    model.Wine[] wines = storage.getWineList();
    foreach var wine in wines {
      io:println(wine);
    }
}
```

Of course, I entered two typos on line 6. The periods (.) should be colons(:)
- model.Wine[] should actually be model:Wine[]
- storage.getWineList() should actually be storage:getWineList()

As soon as I fixed the typos, the sample program worked fine. The compiler should flag the syntax error, not crash.

The Ballerina-internal.log is below:

```
[2021-05-21 00:08:30,549] SEVERE {b7a.log.crash} - Index: '0', Size: '0' 
java.lang.IndexOutOfBoundsException: Index: '0', Size: '0'
	at io.ballerina.compiler.internal.syntax.NodeListUtils.rangeCheck(NodeListUtils.java:38)
	at io.ballerina.compiler.syntax.tree.SeparatedNodeList.get(SeparatedNodeList.java:45)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2109)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.IndexedExpressionNode.apply(IndexedExpressionNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:4981)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2821)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.ExpressionStatementNode.apply(ExpressionStatementNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4853)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1458)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1365)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1345)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1323)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:592)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:475)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:505)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:365)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

Many thanks.

Dean Powell
Edmonton, Canada

**Comment by gimantha** [comment]
please check @SandaruJayawardana
