### ISSUE TITLE
Type guard results in bad sad error

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#30733]
**Description:**
Ideally compiler should have given a meaning full error in this case.

Sample code which results in error,

```ballerina
# A list of all `Lift` objects
    # + return - the lifts
    resource function get allLifts(ds:Status? status) returns Lift[] {
        ds:LiftRecord[] lifts;
        if status is () {
            lifts = from var lift in ds:liftTable select lift;
        } else {
            lifts = from var lift in ds:liftTable where lift.status == status select lift;
        }
        lifts = from var lift in ds:liftTable where lift.status == status select lift;
        return lifts.map(function (ds:LiftRecord liftRecord) returns Lift => new Lift(liftRecord));  
    }
```

But not,

```ballerina
# A list of all `Lift` objects
    # + return - the lifts
    resource function get allLifts(ds:Status? status) returns Lift[] {
        ds:LiftRecord[] lifts;
        if status is () {
            lifts = from var lift in ds:liftTable select lift;
        } else {
            lifts = from var lift in ds:liftTable where lift.status == status select lift;
        }
        // lifts = from var lift in ds:liftTable where lift.status == status select lift;
        return lifts.map(function (ds:LiftRecord liftRecord) returns Lift => new Lift(liftRecord));  
    }
```

**Comment by MaryamZi** [comment]
Reproducible with

```ballerina
type Status boolean;

type LiftRecord record {
    anydata status;
};

class Lift {
    function init(LiftRecord lr) {

    }
}

table<LiftRecord> liftTable = table [];

service / on new Listener() {
    resource function get allLifts(Status? status) returns Lift[] {
        LiftRecord[] lifts;
        if status is () {
            lifts = from var lift in liftTable select lift;
        } else {
            lifts = from var lift in liftTable where lift.status == status select lift;
        }
        
        lifts = from var lift in liftTable where lift.status == status select lift;
        return lifts.map(function (LiftRecord liftRecord) returns Lift => new Lift(liftRecord));  
    }
}

class Listener {
    public function attach(service object {} s, string|string[]? name = ()) returns error? {
    }

    public function detach(service object {} s) returns error? {
    }

    public function 'start() returns error? {
    }

    public function gracefulStop() returns error? {
    }

    public function immediateStop() returns error? {
    }
}
```

```log
[2021-05-23 12:57:28,714] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1921)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeTestExpr.accept(BLangTypeTestExpr.java:65)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1541)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:746)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:697)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:600)
	at org.wso2.ballerinalang.compiler.tree.BLangResourceFunction.accept(BLangResourceFunction.java:40)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:400)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:400)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:156)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:65)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

Works when 

```
lifts = from var lift in liftTable where lift.status == status select lift;
```

is replaced with
```
var st = status;
lifts = from var lift in liftTable where lift.status == st select lift; 
```

**Comment by grainier** [comment]
@MaryamZi It seems this is not a query-specific issue. Changing service to following also breaks the same way. So, I think this is a closure issue.

```ballerina
service / on new Listener() {
    resource function get allLifts(Status? status) returns Lift[] {
        LiftRecord[] lifts = [];
        if !(status is ()) {
            function () returns boolean f = function () returns boolean {
                Status s = true;
                return s == status;
            };
            boolean a = f();
        }
        return [];
    }
}
```
