### ISSUE TITLE
Bad, sad with "on fail"

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30738]
With slalpha5, the following program:

```
type Position record {};

type ParseError distinct error<record { Position pos; }>;

const DECIMAL_NUMBER = 2;

type Token "="|"-"|[DECIMAL_NUMBER,string];

class Tokenizer {
  function current() returns Token? {}
  function expect(string arg) returns ParseError? {}
  function advance() returns ParseError? {}
  function currentPos() returns Position => {};
}

type TypeDesc "any"|SingletonTypeDesc;

type SingletonTypeDesc record { (int|string|boolean) value; };

function parseConstExpr(Tokenizer tok) returns TypeDesc|ParseError {
    check tok.expect("=");
    string sign = "";
    if tok.current() == "-" {
        check tok.advance();
        sign = "-";
    }
    match tok.current() {
        [DECIMAL_NUMBER, var digits] => {
            int n;
            do {
                n = check int:fromString(sign + digits);
            } on fail var cause {
                return error ParseError("invalid number", cause, pos=tok.currentPos());
            }
            check tok.advance();
            return <SingletonTypeDesc>{ value: n };         
        }
    }
    return parseError(tok);
}

function parseError(Tokenizer t) returns ParseError {
  return error("parse error", pos=t.currentPos());
}
```

gets an internal error

```
[2021-05-23 13:31:23,348] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:421)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:121)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:121)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:380)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:98)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:98)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:77)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:269)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:147)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:133)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:107)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:106)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Comment by MaryamZi** [comment]
Does not crash on Swan Lake Beta1 RCs. Need to verify and add tests.

**Comment by pcnfernando** [comment]
Even though the specific sample mentioned above does not crash, using the variable `digits` defined in the match pattern within an on-fail clause or a lambda function causes it to crash.
