### ISSUE TITLE
Stackoverflow error in `ModuleCompilation` when having cyclic dependencies

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30756]
**Description:**
When a ballerina project has cyclic dependencies among its default module and other modules, `ModuleCompilation` gives a stackoverflow error as below.
```
[Info  - 3:53:28 PM] Operation 'text/didOpen' {fileUri: 'file:///home/imesha/Documents/WSO2/Ballerina/Tests/cyclic_test/main.bal'} opened
[Error - 3:53:28 PM] Operation 'text/didOpen' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Tests/cyclic_test/main.bal', error: 'java.lang.StackOverflowError'}
java.lang.StackOverflowError
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at java.base/java.util.HashSet.<init>(HashSet.java:120)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:75)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io.ballerina.projects.ModuleCompilation.addModuleDependencies(ModuleCompilation.java:90)
	at io
```

This same error is logged by VSCode and `bal run` gives a **bad sad error**. The project I used is attached below:
[cyclic_test.zip](https://github.com/ballerina-platform/ballerina-lang/files/6531618/cyclic_test.zip)

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 1 RC4

**Related Issues (optional):**
#30750

**Comment by IMS94** [comment]
Relates to #29695

**Comment by azinneera** [comment]
This is fixed with the datamapper plugin migration to the new compiler design https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/135. 

Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/30633

**Comment by azinneera** [comment]
Reopened since the issue stil exists

**Comment by azinneera** [comment]
Fixed by https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/138

**Comment by IMS94** [comment]
Verified on RC6 and this issue is fixed.
