### ISSUE TITLE
Compiler crashes when trying to define type desc with enums 

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#30761]
**Description:**
```ballerina

enum Colors {
    RED,
    GREEN
}

type ColorType Colors;

```

error
```
[2021-05-24 18:55:47,468] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BEnumSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:194)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.moduleSymbols(BallerinaSemanticModel.java:152)
	at org.ballerinax.datamapper.DataMapperPlugin.checkForClient(DataMapperPlugin.java:627)
	at org.ballerinax.datamapper.DataMapperPlugin.codeAnalyze(DataMapperPlugin.java:111)
	at io.ballerina.projects.PackageCompilation.runPluginCodeAnalysis(PackageCompilation.java:191)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:181)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:132)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:65)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 

```

**Comment by warunalakshitha** [comment]
```
enum Colors {
    RED,
    GREEN
}

type ColorType RED|GREEN;
```
This works fine but we need to fix the crash issue.

**Comment by pubudu91** [comment]
I tried the following in the latest master. And it's working as expected.
```ballerina
enum Colors {
    RED,
    GREEN
}

type ColorType Colors;

public function main() {
    ColorType t = RED;
    panic error(t);
}
```
This gives
```
❯ bal run test.bal
Compiling source
        test.bal

Running executable

error: RED
        at test:main(test.bal:10)
```
