### ISSUE TITLE
Non public 'start' listener life cycle method gives a bad sad error

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#30799]
**Description:**
Mistakenly changed `start` listener life cycle method to a non-public one in WebSocket module. It gives a bad sad error when running a bal file outside the module. 

**Steps to reproduce:**
Make the listener `start` a non-public.
```
isolated function 'start() returns error? = @java:Method {
        'class: "org.ballerinalang.net.websocket.serviceendpoint.Start",
         name: "start"
    } external;
```

Try to run a service importing the module
```
import ballerina/websocket;
service /basic/ws on new websocket:Listener(9090) {
   resource isolated function get .() returns websocket:Service|websocket:UpgradeError {
       return new WsService();
   }
}

service class WsService {
    *websocket:Service;
    remote isolated function onTextMessage(websocket:Caller caller, string text) {
    }
}
```

This gives the following error in the internal log
```[2021-05-26 15:14:45,826] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.rewriteListenerLifeCycleFunction(ServiceDesugar.java:137)
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.rewriteListener(ServiceDesugar.java:119)
	at org.wso2.ballerinalang.compiler.desugar.ServiceDesugar.rewriteListeners(ServiceDesugar.java:112)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:792)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7840)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:455)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:238)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:153)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:156)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:66)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)```

**Comment by MaryamZi** [comment]
The following seems to work on 2201.0.1-rc3. 

```ballerina
service on new Listener() {

}

class Listener {

    public function attach(service object {} s, string|string[]? name = ()) returns error? {
    }

    public function detach(service object {} s) returns error? {
    }

    function 'start() returns error? {
    }

    public function gracefulStop() returns error? {
    }

    public function immediateStop() returns error? {
    }
}
```

Need to verify if it is correct to have a non-public start (or other) method though. Also need to add tests.
