### ISSUE TITLE
RC5 non-functional with multiple package project

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30811]
I am trying to use Beta1 RC5 with a multi-package project.

https://github.com/ballerina-platform/nballerina/tree/james-bir

After compiling the types package with `bal build -c` and then pushing to local repo, I open the bir folder with VSCode. The output window shows errors like this and no editing functionality is available.

```
Ballerina version: Swan Lake Beta 1
Using Ballerina CLI command 'bal.bat' for Language server.
[Info  - 15:40:50] Operation 'text/didOpen' {project: 'file:///c:/Users/jjc/Documents/GitHub/nballerina/bir/' kind: 'build_project'} created
[Error - 15:40:50] Operation 'text/didOpen' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.updateBalDocument(BallerinaWorkspaceManager.java:764)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didOpen(BallerinaWorkspaceManager.java:250)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:507)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[Error - 15:40:50] Operation 'text/foldingRange' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getSyntaxTree(FoldingRangeProvider.java:66)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getFoldingRange(FoldingRangeProvider.java:45)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$foldingRange$13(BallerinaTextDocumentService.java:576)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 15:40:50] Operation 'text/codeLens' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentDocument(AbstractDocumentServiceContext.java:142)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:374)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 15:40:50] Operation 'text/codeLens' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentDocument(AbstractDocumentServiceContext.java:142)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:374)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nadeeshaan** [comment]
This is an issue with module id calculation when there is a dot in the org name of a package. Added a draft fix with https://github.com/ballerina-platform/ballerina-lang/pull/30812 and @azinneera please check whether the fix is okay.

**Comment by jclark** [comment]
You mean dot in *module* name, right?

**Comment by nadeeshaan** [comment]
> You mean dot in _module_ name, right?

@jclark Sorry, my bad. Yes, Since in the `Ballerina.toml` we have the package name set as `nballerina.bir` where in the sense the default module is having the same name.

**Comment by azinneera** [comment]
@jclark There was a bug in the API used for getting the DocumentId for hierarchical package names. https://github.com/ballerina-platform/ballerina-lang/blob/170aa78e4ccd995f1b51b15a6021a4ed03878529/compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java#L134 

@nadeeshaan's PR will fix this
