### ISSUE TITLE
Intermittent nballerina NPE

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31009]
With the code at https://github.com/ballerina-platform/nballerina/releases/tag/jballerina-bug-31008, building uising

```
bal build --skip-tests
```

or

```
bal build
```

I frequently but not always get the NPE

```
[2021-06-05 15:07:48,264] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.fixStreamTypeCastsInInvocationParams(Desugar.java:6192)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6102)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6045)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:7859)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:7899)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6101)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6045)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:7859)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3148)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangReturn.accept(BLangReturn.java:44)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7875)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7885)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1472)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7875)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3253)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7875)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7885)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1472)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7875)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3253)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7875)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7885)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1245)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1290)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7892)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:802)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7834)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:455)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:238)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:153)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:156)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:66)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:291)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

It comes and goes unpredictably: `bal build --skip-tests` seems to get the NPE more frequently than `bal build`

**Comment by jclark** [comment]
I get it always (not intermittently) on this branch: https://github.com/ballerina-platform/nballerina/tree/remove-query-expr

This is on Windows.

**Comment by jclark** [comment]
Verified same behavior on Linux.
