### ISSUE TITLE
Goto definition does not work for defined error types

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31005]
**Description:**
```ballerina
function test1() returns error? {
    error er = error error:Retriable("");
}
```

**Steps to reproduce:**

**Affected Versions:**
SL Beta 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
When trying to go to def of `Retirable`, following error is printed:
```
[Error - 4:17:21 PM] Operation 'text/definition' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test.bal', [2:33], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getFilePathForLanglib(DefinitionUtil.java:153)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getLocation(DefinitionUtil.java:100)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:84)
```
The cause is, `BallerinaErrorTypeSymbol` returns empty for it's locations. Investigating further.
