### ISSUE TITLE
Compiler crash when trying call toString() from array element with object

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#31010]
**Description:**
bal code
```
import ballerina/lang.runtime;

public function main() {
    runtime:StackFrame[] callStack = runtime:getStackTrace();
    string moduleInfo = callStack[0].toString();
}
```
Exception
```
[2021-06-05 18:35:30,760] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.createMethodSymbol(SymbolFactory.java:280)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:136)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:281)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:137)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:158)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:340)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.apply(SimpleNameReferenceNode.java:46)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:430)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:92)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:160)
	at io.ballerina.compiler.syntax.tree.MethodCallExpressionNode.apply(MethodCallExpressionNode.java:66)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:430)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:92)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:76)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:430)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:88)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:324)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:430)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:92)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:48)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.apply(SyntaxTreeMapGenerator.java:430)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:88)
	at org.ballerinalang.diagramutil.SyntaxTreeMapGenerator.transformSyntaxNode(SyntaxTreeMapGenerator.java:69)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:44)
	at org.ballerinalang.diagramutil.DiagramUtil.getSyntaxTreeJSON(DiagramUtil.java:50)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:97)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:66)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 

```
**Affected Versions:**
slbeta1

**Comment by pubudu91** [comment]
Tried the following in latest master and it's working as expected.
```ballerina
import ballerina/lang.runtime;

public function main() {
    runtime:StackFrame[] callStack = runtime:getStackTrace();
    string moduleInfo = callStack[0].toString();
    panic error(moduleInfo);
}
```
This gives,
```
❯ bal run test.bal
Compiling source
        test.bal

Running executable

error: callableName: externGetStackTrace moduleName: ballerina.lang$0046runtime.0_0_1.runtime fileName: runtime.bal lineNumber: 95
        at test:main(test.bal:6)
```
