### ISSUE TITLE
Bad sad error with select clause when accessing non-existing key while querying a json[]

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31041]
**Description:**
Consider the following code:
```
import ballerina/lang.value;
import ballerina/io;

public function main() returns error? {
    json data = check value:fromJsonString("[{\"id\": 1}]");

    if (data is json[]) {
        io:println(data.length());

        json first = data[0];
        io:println(first);

        json[] res = from json item in data
            select {
                id: check item.id,
                name: check item.name
            };
    }
}
```
In the select clause I'm trying to create a new json by assigning some values from the original json array. When I try to access a non-existing key (`item.name`) as above, following bad sad error is printed:
```
[2021-06-08 17:33:01,551] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
	at test.main(test.bal:14)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
 ```

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 1

**Comment by jclark** [comment]
@hasithaa Can we get this fixed for beta2? I keep running into this.
