### ISSUE TITLE
Route BAD SAD errors to stderr and stop writing it to a file

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#31079]
**Description:**
In jBallerina we need to log the current BAD SAD errors to stderror. This will make it easier to retrieve errors from containers. 

We need to fix this for slalpha5 and in master.

Before login the java stack trace we should indicate the user what has happen so that he can report the issue to the dev team and find a possible workaround. 

ie 
```
ballerina: Oh no, something really went wrong. Bad. Sad.

If you are able to share with us the code that broke Ballerina then
We would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with following log and the sample code.

[2018-10-30 13:28:58,000] ERROR {org.ballerinalang.launcher.Main} - configuration file not found: abc.conf 
java.lang.RuntimeException: configuration file not found: abc.conf
	at org.ballerinalang.config.ConfigProcessor.getConfigFile(ConfigProcessor.java:141)
	at org.ballerinalang.config.ConfigProcessor.processConfiguration(ConfigProcessor.java:61)
	at org.ballerinalang.config.ConfigRegistry.initRegistry(ConfigRegistry.java:70)
	at org.ballerinalang.testerina.core.TestCmd.execute(TestCmd.java:135)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

**Comment by pubudu91** [comment]
Shouldn't this be a configurable option? I mean, leave the default behaviour as the current behaviour and make it possible to configure the log to be logged to stderr? A similar argument came up regarding logs of all levels being logged to stderr. There also what we finally agreed was to make it configurable. https://github.com/ballerina-platform/ballerina-standard-library/issues/135

**Comment by azinneera** [comment]
While fixing this we encountered a duplication of the error log in the console for BadSad errors caused in the runtime. In the runtime, the error is logged twice: first at https://github.com/ballerina-platform/ballerina-lang/blob/815cb9701f0832cbed3282791bc137e03b02d76b/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java#L307 and then at https://github.com/ballerina-platform/ballerina-lang/blob/815cb9701f0832cbed3282791bc137e03b02d76b/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java#L130

**Steps to reproduce**

Sample code:
```bal
public function main() returns error? {
    check testArray([1]);
}

function testArray(int[] input) returns error? {
    int[] arr = from var val in input
        select check add(val);
}

function add(int a) returns int|error {
    return error("Invalid value");
}
```
Console output for `bal run` after the change to print the BadSad to console instead of the `ballerina-internal.log`:

```

Compiling source
	asmaj/badSadTest:0.1.0

Running executable

[2021-06-10 12:13:49,757] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
	at asmaj.badSadTest.0_1_0.foo.testArray(foo.bal:6)
	at asmaj.badSadTest.0_1_0.foo.main(foo.bal:2)
	at asmaj.badSadTest.0_1_0.$_init.$lambda$main$(badSadTest)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
ballerina: Oh no, something really went wrong.

The `ballerina-internal.log` file located in the current directory
will indicate what the problem is.
We really appreciate it if you can share with us, the code
that broke Ballerina, together with this log file by creating a
bug report in https://github.com/ballerina-platform/ballerina-lang/issues.

[2021-06-10 12:14:54,557] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
	at asmaj.badSadTest.0_1_0.foo.testArray(foo.bal:6)
	at asmaj.badSadTest.0_1_0.foo.main(foo.bal:2)
	at asmaj.badSadTest.0_1_0.$_init.$lambda$main$(badSadTest)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
@warunalakshitha

**Comment by hevayo** [comment]
@pubudu91, I think by default we should write it to stderror. If the user require they can redirect the stderror to a file. We can consider adding a option later.

**Comment by warunalakshitha** [comment]
@azinneera This is the current behavior. As an example, if we have a service defined, there is a possibility of multiple errors in the crash log for each request that can be the same or different.  We log unexpected errors from the scheduler and other runtime components. The last one is the actual crash log.

**Comment by pubudu91** [comment]
> @pubudu91, I think by default we should write it to stderror. If the user require they can redirect the stderror to a file. We can consider adding a option later.

Why make it the default though? The decision to log it to a file was because a crash is not recoverable by a user and hence not their concern. Wouldn't this introduce this issue back of mixing user errors with crashes if we log it to stderr by default? Logging it to stderr for container use case makes senses, but I don't feel that it's the general/regular case, hence should not be the default behaviour.
