### ISSUE TITLE
NPE at Runtime type checking with error:Retriable

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31118]
**Description:**

Error type's detail type constraint becomes null

[2021-06-11 12:17:35,553] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.internal.types.BMapType.equals(BMapType.java:137)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:555)
	at io.ballerina.runtime.internal.TypeChecker.checkIsErrorType(TypeChecker.java:2553)
	at io.ballerina.runtime.internal.TypeChecker.checkIsRecursiveType(TypeChecker.java:739)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:648)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:549)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:673)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:272)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:260)
	at ballerinai.transaction.1_0_14.tests.retry_transaction_stmt.customRetryTrxManager(tests/retry_transaction_stmt.bal:239)
	at ballerinai.transaction.1_0_14.tests.retry_transaction_stmt.testCustomRetryTrxManager(tests/retry_transaction_stmt.bal:226)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    var bV = error error:Retriable("TransactionError");
    if (bV is transaction:Error) {
        io:println("transaction error");
    }
}
```

**Affected Versions:**
ballerinaLangVersion=2.0.0-beta.2-20210610-094800-31640cd2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Disabled default retry manager tests in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/215

**Comment by niveathika** [comment]
BBE Output Verification disabled in https://github.com/ballerina-platform/ballerina-distribution/pull/1948/commits/caf05fc7072961505e9684de60756f5c853608f2

**Comment by pcnfernando** [comment]
The above observed NPE occurred while creating the BErrorType with a new BMap as detail type constrained with Clonable type. The clonable type used as the constraint is loaded through the `lang.value` and is used at the `lang.error`.  ie, the `lang.value` is a dependency for `lang.error`. At the JvmPackageGen.java, we add the built-in imports in an order to be loaded after; at `addBuiltinImports()`. Here we should load the dependent imports before
