### ISSUE TITLE
Update `Bad Sad Error` message 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#31257]
**Description:**
With the fix of #31079, we no longer write the ballerina crash log in a separate file. But the error message from cli still says we are updating it to the file. 
https://github.com/ballerina-platform/ballerina-lang/blob/00074dbd78eedc178b0046281f11da959159dc14/cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java#L187

**Steps to reproduce:**
```ballerina
public function main() {
     testFunc(10);
}

function testFunc(byte b, byte c = 10) {
     byte a = <byte> (b + c);
}
```
Error:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

[2021-06-17 17:41:09,609] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.objectweb.asm.Frame.merge(Frame.java:1268)
        at org.objectweb.asm.Frame.merge(Frame.java:1233)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
....
```
**Affected Versions:**
beta1- SNAPSHOT

**OS, DB, other environment details and versions:**

**Comment by azinneera** [comment]
Fixed with #31137
