### ISSUE TITLE
When goto definition invoked for http construct and jump to the http source, compiler throws exception

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31280]
**Description:**
Consider the following source snippet. 

```
import ballerina/module1;
import ballerina/http;
import ballerina/time;

public function main() {
    
}

public type Table table<http:LoadBalanceClientConfiguration>;
```

When go to definition invoked for `http:LoadBalanceClientConfiguration`, the source jumps to the relevant http source, then the server throws the following exception.

```
[Error - 10:51:49 AM] Operation 'text/didOpen' failed! {uri: '/Library/Ballerina/distributions/ballerina-slbeta1/repo/bala/ballerina/http/1.1.0-beta.1/java11/modules/http/resiliency_load_balance_client.bal', error: 'java.lang.AssertionError, org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:602)'}
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:602)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangConstRef.accept(BLangConstRef.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3787)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExprs(CodeAnalyzer.java:3846)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3021)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3787)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3596)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckPanickedExpr.accept(BLangCheckPanickedExpr.java:44)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3787)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3338)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3787)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2331)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:388)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2426)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:388)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:568)
```

**Affected Versions:**
Swanlake beta-1 at least

**Comment by hasithaa** [comment]
@nadeeshaan Can you verify this in beta2?

**Comment by nadeeshaan** [comment]
This issue has been fixed in SwanLake-beta2, hence closing the issue.
