### ISSUE TITLE
Compiler crash with StackOverflowError when we have configurable record type variable with self reference

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#31295]
**Description:**
```ballerina
type Person record {|
    string name;
    Person child?;
|};

configurable Person p = ?; 
```

```
[2021-06-19 14:26:19,088] SEVERE {b7a.log.crash} - null 
java.lang.StackOverflowError
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:335)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:306)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:636)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:631)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:939)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:929)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:929)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isS

```
**Affected Versions:**
slbeta2

**Comment by HindujaB** [comment]
This is fixed in `beta2` release branch. Hence, closing this.
