### ISSUE TITLE
a panic with a test:config results in Bad, Sad error; CodeGen fails

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#31338]
Consider the following code

```ballerina
import ballerina/test;

@test:Config {

}
function testCompileVP(string path) {

}

function errorLine(string path) {
     panic unreached();
}

public function unreached(string? detail = ()) returns never {
    panic error("error!!!");
}
```

Compiling fails with a Bad, Sad error with the following error

```
[2021-06-21 20:40:24,457] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    gimantha/PROJ/0_1_0/main.errorLine(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;Z)Ljava/lang/Object; @121: athrow
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @121
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/api/values/BString', integer, 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 4e01 3a04
    0000010: 0336 052a b400 1b9d 007e 1505 ab00 0000
    0000020: 0000 00a9 0000 0006 0000 0000 0000 003c
    0000030: 0000 0001 0000 0041 0000 0002 0000 0057
    0000040: 0000 0003 0000 0061 0000 0004 0000 0069
    0000050: 0000 0005 0000 0071 1100 0036 0511 0001
    0000060: 3605 2a01 03b8 003b 4e2a b600 3f9a 0058
    0000070: a700 0311 0002 3605 2dbf 0000 bf11 0003
    0000080: 3605 a700 0b11 0004 3605 a700 0311 0005
    0000090: 3605 1904 b02a b400 1f2a 59b4 001b 0464
    00000a0: 5ab5 001b 32c0 0041 59b4 0042 3a04 59b4
    00000b0: 0043 4c59 b400 443d 59b4 0047 4eb4 0048
    00000c0: 3605 a7ff 58bb 0041 59b7 0049 5919 04b5
    00000d0: 0042 592b b500 4359 1cb5 0044 592d b500
    00000e0: 4759 1505 b500 483a 062a b400 1f2a 59b4
    00000f0: 001b 5a04 60b5 001b 1906 5319 04b0     
  Stackmap Table:
    same_frame(@11)
    append_frame(@26,Object[#4],Object[#4],Integer)
    same_frame(@88)
    same_frame(@93)
    same_frame(@115)
    full_frame(@122,{},{Object[#75]})
    full_frame(@125,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
    same_frame(@133)
    same_frame(@141)
    full_frame(@149,{Object[#13],Object[#54],Integer,Null,Null,Integer},{})
    full_frame(@197,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    gimantha/PROJ/0_1_0/main.errorLine(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;Z)Ljava/lang/Object; @121: athrow
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @121
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/api/values/BString', integer, 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 4e01 3a04
    0000010: 0336 052a b400 1b9d 007e 1505 ab00 0000
    0000020: 0000 00a9 0000 0006 0000 0000 0000 003c
    0000030: 0000 0001 0000 0041 0000 0002 0000 0057
    0000040: 0000 0003 0000 0061 0000 0004 0000 0069
    0000050: 0000 0005 0000 0071 1100 0036 0511 0001
    0000060: 3605 2a01 03b8 003b 4e2a b600 3f9a 0058
    0000070: a700 0311 0002 3605 2dbf 0000 bf11 0003
    0000080: 3605 a700 0b11 0004 3605 a700 0311 0005
    0000090: 3605 1904 b02a b400 1f2a 59b4 001b 0464
    00000a0: 5ab5 001b 32c0 0041 59b4 0042 3a04 59b4
    00000b0: 0043 4c59 b400 443d 59b4 0047 4eb4 0048
    00000c0: 3605 a7ff 58bb 0041 59b7 0049 5919 04b5
    00000d0: 0042 592b b500 4359 1cb5 0044 592d b500
    00000e0: 4759 1505 b500 483a 062a b400 1f2a 59b4
    00000f0: 001b 5a04 60b5 001b 1906 5319 04b0     
  Stackmap Table:
    same_frame(@11)
    append_frame(@26,Object[#4],Object[#4],Integer)
    same_frame(@88)
    same_frame(@93)
    same_frame(@115)
    full_frame(@122,{},{Object[#75]})
    full_frame(@125,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
    same_frame(@133)
    same_frame(@141)
    full_frame(@149,{Object[#13],Object[#54],Integer,Null,Null,Integer},{})
    full_frame(@197,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})

	at gimantha.PROJ.0_1_0.$_init.$gen$$0046$0060init$0062(PROJ:1)
	at gimantha.PROJ.0_1_0.$_init.$moduleInit(PROJ)
	at gimantha.PROJ.0_1_0.$_init.$lambda$$moduleInit$(PROJ)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
[2021-06-21 20:40:24,483] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    gimantha/PROJ/0_1_0/main.errorLine(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;Z)Ljava/lang/Object; @121: athrow
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @121
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/api/values/BString', integer, 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 4e01 3a04
    0000010: 0336 052a b400 1b9d 007e 1505 ab00 0000
    0000020: 0000 00a9 0000 0006 0000 0000 0000 003c
    0000030: 0000 0001 0000 0041 0000 0002 0000 0057
    0000040: 0000 0003 0000 0061 0000 0004 0000 0069
    0000050: 0000 0005 0000 0071 1100 0036 0511 0001
    0000060: 3605 2a01 03b8 003b 4e2a b600 3f9a 0058
    0000070: a700 0311 0002 3605 2dbf 0000 bf11 0003
    0000080: 3605 a700 0b11 0004 3605 a700 0311 0005
    0000090: 3605 1904 b02a b400 1f2a 59b4 001b 0464
    00000a0: 5ab5 001b 32c0 0041 59b4 0042 3a04 59b4
    00000b0: 0043 4c59 b400 443d 59b4 0047 4eb4 0048
    00000c0: 3605 a7ff 58bb 0041 59b7 0049 5919 04b5
    00000d0: 0042 592b b500 4359 1cb5 0044 592d b500
    00000e0: 4759 1505 b500 483a 062a b400 1f2a 59b4
    00000f0: 001b 5a04 60b5 001b 1906 5319 04b0     
  Stackmap Table:
    same_frame(@11)
    append_frame(@26,Object[#4],Object[#4],Integer)
    same_frame(@88)
    same_frame(@93)
    same_frame(@115)
    full_frame(@122,{},{Object[#75]})
    full_frame(@125,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
    same_frame(@133)
    same_frame(@141)
    full_frame(@149,{Object[#13],Object[#54],Integer,Null,Null,Integer},{})
    full_frame(@197,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    gimantha/PROJ/0_1_0/main.errorLine(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;Z)Ljava/lang/Object; @121: athrow
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @121
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/api/values/BString', integer, 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 4e01 3a04
    0000010: 0336 052a b400 1b9d 007e 1505 ab00 0000
    0000020: 0000 00a9 0000 0006 0000 0000 0000 003c
    0000030: 0000 0001 0000 0041 0000 0002 0000 0057
    0000040: 0000 0003 0000 0061 0000 0004 0000 0069
    0000050: 0000 0005 0000 0071 1100 0036 0511 0001
    0000060: 3605 2a01 03b8 003b 4e2a b600 3f9a 0058
    0000070: a700 0311 0002 3605 2dbf 0000 bf11 0003
    0000080: 3605 a700 0b11 0004 3605 a700 0311 0005
    0000090: 3605 1904 b02a b400 1f2a 59b4 001b 0464
    00000a0: 5ab5 001b 32c0 0041 59b4 0042 3a04 59b4
    00000b0: 0043 4c59 b400 443d 59b4 0047 4eb4 0048
    00000c0: 3605 a7ff 58bb 0041 59b7 0049 5919 04b5
    00000d0: 0042 592b b500 4359 1cb5 0044 592d b500
    00000e0: 4759 1505 b500 483a 062a b400 1f2a 59b4
    00000f0: 001b 5a04 60b5 001b 1906 5319 04b0     
  Stackmap Table:
    same_frame(@11)
    append_frame(@26,Object[#4],Object[#4],Integer)
    same_frame(@88)
    same_frame(@93)
    same_frame(@115)
    full_frame(@122,{},{Object[#75]})
    full_frame(@125,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})
    same_frame(@133)
    same_frame(@141)
    full_frame(@149,{Object[#13],Object[#54],Integer,Null,Null,Integer},{})
    full_frame(@197,{Object[#13],Object[#54],Integer,Object[#4],Object[#4],Integer},{})

	at gimantha.PROJ.0_1_0.$_init.$gen$$0046$0060init$0062(PROJ:1)
	at gimantha.PROJ.0_1_0.$_init.$moduleInit(PROJ)
	at gimantha.PROJ.0_1_0.$_init.$lambda$$moduleInit$(PROJ)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
 

```

**Comment by manuranga** [comment]
Issue can be simplified more
```ballerina
public function main() {
    panic unreached();
}

public function unreached() returns never {
    panic error("error!!!");
}
```

**Comment by lasinicl** [comment]
> Consider the following code
> 
> ```ballerina
> import ballerina/test;
> 
> @test:Config {
> 
> }
> function testCompileVP(string path) {
> 
> }
> 
> function errorLine(string path) {
>      panic unreached();
> }
> 
> public function unreached(string? detail = ()) returns never {
>     panic error("error!!!");
> }
> ```

This should result in a compilation error since 
```
Context where expression of type never is permitted:

call-stmt
start-action
trap-expr
```
https://github.com/ballerina-platform/ballerina-spec/issues/510#issuecomment-796368278

**Comment by warunalakshitha** [comment]
Removed jballerina label since need to fix from compiler FE.
