### ISSUE TITLE
NPE when creating a recuserive tuple type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31346]
**Description:**
```
type Rule string|[Rule...];

public function main() {
    Rule r = [""];
}

```
When running above source it gives following error.
```
[2021-06-21 23:35:48,266] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:656)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:272)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:260)
	at io.ballerina.runtime.internal.values.TupleValueImpl.prepareForAdd(TupleValueImpl.java:681)
	at io.ballerina.runtime.internal.values.TupleValueImpl.addRefValue(TupleValueImpl.java:285)
	at io.ballerina.runtime.internal.values.TupleValueImpl.<init>(TupleValueImpl.java:152)
	at manu.produce.0_1_0.main.main(main.bal:17)
	at manu.produce.0_1_0.$_init.$lambda$main$(produce)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
```

**Affected Versions:**
sl-beta1

**Comment by warunalakshitha** [comment]
I tested the above code with beta 2 rc1 and works for me.

**Comment by warunalakshitha** [comment]
Tested with beta 2 snapshot and works fine for me. Anyway I was able to observe the same issue with beta 1.

**Comment by riyafa** [comment]
Closed based on the above comment
