### ISSUE TITLE
[Semantic API] CCE in SymbolFactory

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31347]
**Description:**
Consider the following source where I intentionally have redeclared the same symbol `a` at the cursor position.
```ballerina
function func1(string a, int b, function(int,int) returns string a<curosr>) returns function (int, function (int,int) r)  {

}
```
When `a` is hovered over , the following st is observed.
![issue](https://user-images.githubusercontent.com/35211477/123032653-ed877500-d403-11eb-99ea-a77bedf6be22.png)

Stack trace:
```
[Error - 9:17:09 am] Operation 'text/hover' failed! {uri: '/home/malintha/Documents/wso2/experimental/testing/doc_test/main.bal', [29:66], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.createFunctionSymbol(SymbolFactory.java:252)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:138)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:321)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:139)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:77)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:158)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
Try above code segment.

**Comment by malinthar** [comment]
This is no longer reproducible.
![issue](https://user-images.githubusercontent.com/35211477/123031934-c67c7380-d402-11eb-814a-9dfea171c73b.png)
