### ISSUE TITLE
CCE for function pointer variable assignment

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31351]
**Description:**
$subject for the following source code.
```ballerina
var lambda = function(i)
```
The exception is captured below. LS stopped working after this. 
<img src="https://user-images.githubusercontent.com/35211477/122867539-4e9d4300-d347-11eb-8127-aacc512161f3.gif" width=700/>

Stack trace
```
[Error - 10:57:12 am] Operation 'text/codeAction' failed! {uri: '/home/malintha/Documents/wso2/experimental/testing/single/test.bal', [3:1]- [3:1], error: 'class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveAndSetFunctionTypeFromRHSLambda(SymbolEnter.java:4643)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:387)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:317)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:274)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:267)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:377)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:134)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:218)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:197)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:66)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:289)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
**Steps to reproduce:**

**Affected Versions:**
slbeta3

**Comment by MaryamZi** [comment]
Same as Case I of https://github.com/ballerina-platform/ballerina-lang/issues/33616. Fixed in https://github.com/ballerina-platform/ballerina-lang/commit/387661e5b1fbd602d68e9a8738906da724169bcb (https://github.com/ballerina-platform/ballerina-lang/pull/33675).
