### ISSUE TITLE
wild card binding pattern in let clause in a query expression causes Bad, Sad error

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#31360]
Consider the following code

```ballerina
type Person record {|
   string firstName;
   string lastName;
   string deptAccess;
|};

public function main() {
    Person[] personList = [];
    Person[] outputPersonList = from var person in personList
            let var [_, name] = foo()
            where person.deptAccess == "XYZ" && person.firstName == name
            select {
                   firstName: "Alexander",
                   lastName: person.lastName,
                   deptAccess: "WSO2"
            };
}

function foo() returns [string, string?] {
  return ["", ""];
}
```
Compiling the above code, gives the below exception.

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.shadowSymbolScope(QueryDesugar.java:986)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.addLetFunction(QueryDesugar.java:560)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.buildStream(QueryDesugar.java:365)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.desugar(QueryDesugar.java:257)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7805)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangQueryExpr.accept(BLangQueryExpr.java:99)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8112)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1373)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1502)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8128)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8138)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1268)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1313)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8145)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:806)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:232)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:150)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:157)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:114)
        at org.ballerinalang.test.BCompileUtil.jBallerinaBackend(BCompileUtil.java:189)
        at org.ballerinalang.test.BCompileUtil.compile(BCompileUtil.java:80)
        at org.ballerinalang.test.expressions.access.Test.setup(Test.java:37)
```

**Comment by manuranga** [comment]
Is this in beta2? I am still getting it in beta2.

**Comment by pcnfernando** [comment]
No, this has only been merged to master. I believe we targeted this for beta3. @gimantha please confirm
