### ISSUE TITLE
Runtime crash when Error is intersected with readonly

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31379]
**Description:**
No 1:

```ballerina
function foo() returns (error & readonly)? {
    return error("msg");
}

public function main() returns error? {
    return foo();
}
```

Output:
```shell
[2021-06-23 09:30:45,582] SEVERE {b7a.log.crash} - $type$$anonIntersectionErrorType$_0 
java.lang.NoSuchFieldError: $type$$anonIntersectionErrorType$_0
        at main.foo(main.bal:31)
        at main.main(main.bal:35)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

No 2:

```ballerina
type E error & readonly;

function foo() returns E? {
    return error("msg");
}

public function main() returns error? {
    return foo();
}
```

Output:
```shell
[2021-06-23 09:43:38,526] SEVERE {b7a.log.crash} - $type$E 
java.lang.NoSuchFieldError: $type$E
        at $_init.$gen$$0046$0060init$0062(.:1)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**

**Affected Versions:**
SL beta-2
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
IIRC, for the intersection `T & readonly`, if `T` is immutable we don't create a new type. So this should have worked in the same path as saying `error` instead of `error & readonly`.

Related to https://github.com/ballerina-platform/ballerina-lang/issues/30717.

**Comment by warunalakshitha** [comment]
Removing jballerina label since this seems to be fixed by FE.
