### ISSUE TITLE
Bad, sad in code gen from nBallerina 

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31386]
codeGen bad, sad https://github.com/ballerina-platform/nballerina/commit/50b3fc792e612b563008d693bc135fe88aad0277#diff-1e22b6b83586d5b9c1292abfd2061834c5ba5ba95a821fede25da9a5f68a897eR83

```
[2021-06-23 12:41:11,699] SEVERE {b7a.log.crash} - null
java.lang.ArrayIndexOutOfBoundsException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:410)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:804)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:92)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:69)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:298)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:407)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:156)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:114)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:113)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:66)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:291)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.objectweb.asm.Frame.getConcreteOutputType(Frame.java:1139)
        at org.objectweb.asm.Frame.merge(Frame.java:1184)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:259)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:154)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:461)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by manuranga** [comment]
Simplified version of the source:
```
public function main() {
    int i = num();
}

public function num() returns int {
    return unreached();
}

public function unreached() returns never {
    panic error("error!!!");
}
```
Very likely be related to #31338

**Comment by manuranga** [comment]
Additional info at ballerina-platform/ballerina-spec#510

**Comment by lasinicl** [comment]
> Simplified version of the source:
> 
> ```ballerina
> public function main() {
>     int i = num();
> }
> 
> public function num() returns int {
>     return unreached();
> }
> 
> public function unreached() returns never {
>     panic error("error!!!");
> }
> ```
This should result in a compilation error since
```
Context where expression of type never is permitted:

call-stmt
start-action
trap-expr
```
https://github.com/ballerina-platform/ballerina-spec/issues/510#issuecomment-796368278

**Comment by jclark** [comment]
@lacinicl Thanks for pointing this out: the spec should be fixed allow this.

**Comment by Nadeeshan96** [comment]
These examples should also be failed with a compilation error but at the moment failed during codegen. So those needs to be fixed in compiler FE.

```ballerina
public function main() {
   panic num();
}
 
public function num() returns error {
   return unreached();
}
 
public function unreached() returns never {
   panic error("error!!!");
}
```

```ballerina
public function main() {
   test(unreached());
}
 
public function unreached() returns never {
 panic error("error");
}
 
public function test(int a) { }
```

```ballerina
public function main() {
  error i = num();
}

public function num() returns error {
  return unreached();
}

public function unreached() returns never {
  panic error("error!!!");
}
```

**Comment by Nadeeshan96** [comment]
This sample failed as compilation error but should not be a compilation error.

```ballerina
public function main() {
    int i = num();
}

public function num() returns int {
    unreached();
}

public function unreached() returns never {
    panic error("error!!!");
}
```

**Comment by warunalakshitha** [comment]
Removed jballerina label since we need to fix from compiler FE.
