### ISSUE TITLE
PositionUtil throws NPE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31422]
**Description:**
Try invoking the References API over the nBallerina repo, then the following exception is thrown. Due to this reason non of the references related operations are working. Such as `rename` and `find all references`.

```
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:63)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:230)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:212)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupEnclosingContainer(NodeFinder.java:221)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:199)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:178)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:84)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:82)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$references$6(BallerinaTextDocumentService.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
sl-beta2-RC3

**Comment by dulajdilshan** [comment]
There are some scenarios where `PositionUtil.withinRange()` throws NPE. Therefore, particular parser improvements need to be done.

**Comment by dulajdilshan** [comment]
TODO: convert direct `pos` usages to its getter and setter.

**Comment by pubudu91** [comment]
Is this issue fixed now? Tried find references and renaming in slbeta2 on the nballerina repo and it seems to be working fine.

**Comment by dulajdilshan** [comment]
@pubudu91 Yes this particular issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31440, but we kept this because the `null` check we added to the `PositionUtil.withinRange()` needs to be removed in the master after it synced with the `staging-beta2` branch

**Comment by pubudu91** [comment]
The master is now includes all the changes that went into slbeta2.

**Comment by pubudu91** [comment]
Closing this since the issue mentioned here is fixed. @dulajdilshan Can you create a separate issue to track the requirement you mentioned?

**Comment by dulajdilshan** [comment]
We will be tracking the task with this issue https://github.com/ballerina-platform/ballerina-lang/issues/31764
