### ISSUE TITLE
Completions within record literal expression throws a CCE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31423]
**Description:**
Consider the following source snippet 

```
public type Position readonly & record {|
    // 1-based
    int lineNumber;
    // 0-based index (in code points) in the line
    int indexInLine;
|};

public function main() {

    Position pos = {<cursor>}

}
```

Invoke the completions at the given cursor position, which throws the following CCE.

```
at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:320)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:588)
	at org.ballerinalang.langserver.common.utils.CommonUtil.lambda$getRecordFieldCompletionItems$7(CommonUtil.java:383)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionItems(CommonUtil.java:380)
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.getCompletions(MappingConstructorExpressionNodeContext.java:102)
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.getCompletions(MappingConstructorExpressionNodeContext.java:62)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:112)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:69)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:138)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
sl-beta2-rc3 at least

**Comment by IMS94** [comment]
Fix has been merged to staging beta 2. Will be merged to master after beta 2 release.
