### ISSUE TITLE
The Below Program Results in BAD SAD

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#31452]
```Ballerina
import ballerina/http;
import ballerina/graphql;

service /graphql on new graphql:Listener(9000) {

    final http:Client covid_19 = check new("https://disease.sh/v3/covid-19");

    resource function get foo() returns WorldStatus|error? {
        return check new WorldStatus(self.covid_19);               
    }
}

service class WorldStatus {

    final WorldStatusData worldStatusData;

    public function init(http:Client covid_19) returns error? {
        self.worldStatusData = check covid_19->get("/all");
    }

    resource function get cases () returns int|error {
        return self.worldStatusData.cases;
    }

    resource function get deaths () returns int|error {
        return self.worldStatusData.deaths;
    }

    resource function get recovered () returns int|error {
        return self.worldStatusData.recovered;
    }
}

type WorldStatusData record {
    int cases;
    int deaths;
    int recovered;
    int active;
};
```
Error
```
[2021-06-28 11:16:51,987] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3781)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3983)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2521)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:422)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:382)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:374)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:363)
	at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:212)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:117)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:383)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Comment by MaryamZi** [comment]
This is because the field-initializer uses `check`. We currently allow `check` only when the expression is enclosed in a function that returns an `error` or when it is at module level. Created a spec issue to clarify what the behaviour should be - https://github.com/ballerina-platform/ballerina-spec/issues/886.

This shouldn't have crashed anyway.
