### ISSUE TITLE
[Testerina] Code coverage throws a NPE when normalizing file names for `createXMLReport()`

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#31532]
**Description:**
Fails for `ballerina build --code-coverage`

Following is the stack trace that applies to Swan-lake `Alpha 5`

```
[2021-06-30 06:49:04,500] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
 	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.normalizeFileName(CodeCoverageUtils.java:365)
 	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.modifyClasses(CodeCoverageUtils.java:310)
 	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.getPartialCoverageModifiedBundle(CodeCoverageUtils.java:431)
 	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.createXMLReport(CodeCoverageUtils.java:461)
 	at io.ballerina.cli.task.RunTestsTask.generateCoverage(RunTestsTask.java:286)
 	at io.ballerina.cli.task.RunTestsTask.execute(RunTestsTask.java:234)
 	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
 	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:189)
 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
 	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

The build passes locally but fails in the Azure pipeline. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@Ibaqu shall we verify whether the issue is still reproducible and close if not applicable?

**Comment by Thevakumar-Luheerathan** [comment]
We could not reproduce this issue with `bal test --code-coverage` with latest swan-lake update 4.
