### ISSUE TITLE
Compiler throws CCE for semantically invalid source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31636]
**Description:**
Consider the following source snippet

```
public isolated service class testClass {
    private int testField = 12;
    resource function name [module1:RequestMessage a]() {

    }
}
```

For the above, the compiler throws the following CCE

```
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to class org.wso2.ballerinalang.compiler.tree.types.BLangType (org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef and org.wso2.ballerinalang.compiler.tree.types.BLangType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:677)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.ResourcePathParameterNode.apply(ResourcePathParameterNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createResourceFunctionNode(BLangNodeTransformer.java:711)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1368)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:3902)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.ClassDefinitionNode.apply(ClassDefinitionNode.java:75)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:590)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:503)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:365)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:219)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:198)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:66)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:289)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
SwanLake beta2 at least

**Comment by nadeeshaan** [comment]
Related to this issue, we have added a couple of Language server test cases and disabled them until this is fixed. With this issue's fix make sure to enable those test cases as well.

Test cases are, https://github.com/ballerina-platform/ballerina-lang/pull/31619/files?file-filters%5B%5D=.java#diff-86bf485708da8ea9d6e14dc554aebe9d527b6604fec81d227c452ec82f64ebd4
