### ISSUE TITLE
Reordering doesn't seem to happen with object constructor field initializers

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#31655]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
final string|error notString = error("error!");

var x = object {
    string|error b = notString;

    function init() returns error? {
    }
};

public function main() {
    var y = checkpanic x;

    string|error yb = y.b;
    if yb is string {
        // panic error("should be error!");
        panic error(string `y.b is string '${yb}'`);
    }
}
```

The `b` field should hold an error value.

**Affected Versions:**
slbeta2, current master

**Comment by KRVPerera** [comment]
- [ ] Test case also has a crash now
Probably due to the same issue
```LogTalk
[2021-09-27 13:12:22,289] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.internal.values.BmpStringValue.concat(BmpStringValue.java:47)
        at s1.main(s1.bal:16)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:608)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:333)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:301)
        at java.base/java.lang.Thread.run(Thread.java:834)
 
 ```
