### ISSUE TITLE
NodeTransformer throws CCE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31785]
**Description:**
Consider the following source snippet,
```
function name() returns error? {
    error ee = error("");
    function x = function () returns int {
        return 12;
    };

    string stringResult = x.toString();
    int[] test = [(let int)];
}
```

The NodeTransformer throws the following CCE for this.
```
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.ParameterizedTypeDescriptorNode cannot be cast to class io.ballerina.compiler.syntax.tree.BindingPatternNode (io.ballerina.compiler.syntax.tree.ParameterizedTypeDescriptorNode and io.ballerina.compiler.syntax.tree.BindingPatternNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getBLangVariableNode(BLangNodeTransformer.java:4795)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2746)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createLetVariable(BLangNodeTransformer.java:2370)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2361)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.LetExpressionNode.apply(LetExpressionNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:5021)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4992)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2030)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.BracedExpressionNode.apply(BracedExpressionNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:5012)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4992)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1921)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.ListConstructorExpressionNode.apply(ListConstructorExpressionNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:5021)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4992)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2760)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2737)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4893)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1511)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1418)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1398)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1376)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:590)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:503)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:113)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:380)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:343)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:179)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:219)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:198)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:182)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:63)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$3(BallerinaTextDocumentService.java:212)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
SwanLake Beta2 at least

**Comment by rdulmina** [comment]
This issue is no longer in master. Please feel free to reopen if any concerns.

**Comment by rdulmina** [comment]
This issue is no longer in master. Please feel free to reopen if any concerns.
