### ISSUE TITLE
DataFlowAnalyzer throws NPE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31823]
**Description:**
Consider the following source snippet
```
function helloWOrld() {
    TestClass tc = new;
    var helloVar = object t {
        
    };
}

type ObjectName object {};

class TestClass {
    public typedesc<ObjectName> get;
}

type Rec record {
    int field1;
    string field2;
};
```

**Steps to reproduce:**
1. Open the file in VSCode (You cannot see the NPE at this stage)
2. Add a new line at the end of the file (Now you can see the NPE.)

During both step 1 and step 2, the source is semantically equivalent. This could be due to a caching issue in when we do subsequent compilations of the same project instance.

Following exception is thrown

```
NullPointerException, org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1613)'}
java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addFirst(ArrayDeque.java:287)
	at java.base/java.util.ArrayDeque.push(ArrayDeque.java:580)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1613)
	at org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType.accept(BLangUserDefinedType.java:71)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1890)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.lambda$visit$15(DataflowAnalyzer.java:495)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:495)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1890)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:315)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:1890)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:294)
	at io.ballerina.projects.internal.CompilerPhaseRunner.dataflowAnalyze(CompilerPhaseRunner.java:216)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:122)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:398)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:343)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:179)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:219)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.getLatestDiagnostics(DiagnosticsHelper.java:115)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:80)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:508)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Fixing
- [x] Fix NPE : https://github.com/ballerina-platform/ballerina-lang/pull/31982
- [ ] https://github.com/ballerina-platform/ballerina-lang/pull/32518

**Affected Versions:**
SwanLake beta2 at least

**Comment by KRVPerera** [comment]
The solution has two steps

- [x] Fix NPE : https://github.com/ballerina-platform/ballerina-lang/pull/31982
- [ ] Investigate the caching problem
