### ISSUE TITLE
CCE when triggering completions within a method in an object constructor

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#31839]
Consider the following:
```ballerina
function helloWorld() {
    var helloVar = object {
        int xx = 12;       
        public function testFunction() {
            <cursor>
        }
    };
}
```
When I trigger completions at the above cursor position, it gives the following CCE:
```
[Error - 6:40:38 PM] Operation 'text/completion' failed! {uri: '/Users/pubuduf/issues/test.bal', [25:13], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaClassSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaClassSymbol and io.ballerina.compiler.api.symbols.FunctionSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaClassSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaClassSymbol and io.ballerina.compiler.api.symbols.FunctionSymbol are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.lambda$transform$0(ReturnTypeFinder.java:56)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.transform(ReturnTypeFinder.java:56)
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.transform(ReturnTypeFinder.java:41)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.transformSyntaxNode(ReturnTypeFinder.java:84)
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.transformSyntaxNode(ReturnTypeFinder.java:41)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:324)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.ballerinalang.langserver.completions.util.ReturnTypeFinder.getTypeSymbol(ReturnTypeFinder.java:50)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.lambda$getStatementCompletionItems$1(BlockNodeContextProvider.java:149)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getStatementCompletionItems(BlockNodeContextProvider.java:147)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getCompletions(BlockNodeContextProvider.java:90)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:45)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:36)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:115)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:72)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:138)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
After this the completions are broken.

**Comment by nadeeshaan** [comment]
This has the same root-cause as per #31833. Hence marking as duplicate

**Comment by pubudu91** [comment]
As per above comment and since this is working in master, closing this.
