### ISSUE TITLE
Checking byte_value is int:Unsigned8 gives wrong result

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#31857]
**Description:**

$subject

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    byte a = 0x4;    
    io:println(a is int:Unsigned8); //gives false, correct answer is true
}
```

**Affected Versions:**
Ballerina Swan Lake Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/jBallerina

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Another bug is if I build the above code snippet using `bal build --dump-bir filename.bal`, it gives the following error.
```logtalk
Compiling source
	temp.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

[2021-07-26 11:59:40,660] SEVERE {b7a.log.crash} - Invalid type 
java.lang.IllegalStateException: Invalid type
	at org.wso2.ballerinalang.compiler.bir.emit.TypeEmitter.emitType(TypeEmitter.java:129)
	at org.wso2.ballerinalang.compiler.bir.emit.TypeEmitter.emitTypeRef(TypeEmitter.java:431)
	at org.wso2.ballerinalang.compiler.bir.emit.InstructionEmitter.emitInsTypeTest(InstructionEmitter.java:319)
	at org.wso2.ballerinalang.compiler.bir.emit.InstructionEmitter.emitInstruction(InstructionEmitter.java:97)
	at org.wso2.ballerinalang.compiler.bir.emit.InstructionEmitter.emitInstructions(InstructionEmitter.java:53)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emitBasicBlock(BIREmitter.java:292)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emitBasicBlocks(BIREmitter.java:278)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emitFunction(BIREmitter.java:231)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emitFunctions(BIREmitter.java:207)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emitModule(BIREmitter.java:110)
	at org.wso2.ballerinalang.compiler.bir.emit.BIREmitter.emit(BIREmitter.java:80)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birEmit(CompilerPhaseRunner.java:240)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:160)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:412)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:347)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:163)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:114)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:77)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:331)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:53)
```
The above comes also when `byte` in `byte a = 0x4;` or `int:Unsigned8` in `a is int:Unsigned8` are replaced with every other subtype of int.
