### ISSUE TITLE
NullPointerException related to Transaction Statement

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#32072]
**Description:**
following error occurred when using transaction statement

```
[2021-08-09 15:17:31,632] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:669)
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.invokeRollbackFunc(TransactionDesugar.java:490)
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.createRollbackIfFailed(TransactionDesugar.java:450)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createTrxInternalOnFail(Desugar.java:5392)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5487)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangTransaction.accept(BLangTransaction.java:66)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8128)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8138)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1268)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1313)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8145)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:806)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8087)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:232)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:150)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:157)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:114)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:65)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:59)
```

**Steps to reproduce:**

consider following code segment (from https://ballerina.io/learn/by-example/transaction-statement.html?is_ref_by_example=true)

```ballerina
import ballerina/io;

public function main() returns error? {

    transaction {
        doStage1();
        doStage2();

        check commit;

    }
}

function doStage1() {
    io:println("Stage1 completed");
}

function doStage2() {
    io:println("Stage2 completed");
}
```

**Affected Versions:**
slbeta3

**Comment by pcnfernando** [comment]
Are you trying this on distribution snapshot built from https://github.com/ballerina-platform/ballerina-distribution/blob/master?

**Comment by DamithaSenevirathne** [comment]
> Are you trying this on distribution snapshot built from https://github.com/ballerina-platform/ballerina-distribution/blob/master?

yes

**Comment by DamithaSenevirathne** [comment]
I tried the Snapshot built from ballerina-lang (https://github.com/ballerina-platform/ballerina-lang) which is in jballerina-tools folder.

**Comment by pcnfernando** [comment]
I tried the same on the master branch and couldn't reproduce it. 

This issue is observed when there is a mismatch between the version in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BLangCompilerConstants.java#L58 and the transaction-internal version used in https://github.com/ballerina-platform/ballerina-distribution/blob/master/gradle.properties#L47.

Try syncing the https://github.com/ballerina-platform/ballerina-distribution from the upstream and using `--no-build-cache
` argument when building the distribution.

**Comment by DamithaSenevirathne** [comment]
Code segment executed without any issues after following mentioned steps.
