### ISSUE TITLE
Bad Sad with `bal push`

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32091]
**Description:**

Bad. Sad.  in `bal push`. 

```
[2021-08-10 10:21:54,728] SEVERE {b7a.log.crash} - Duplicate key io.ballerina.projects.ModuleDescriptor@600dfead (attempted merging values [io.ballerina.projects.ModuleDescriptor@a36787ac] and [io.ballerina.projects.ModuleDescriptor@a36787ac]) 
java.lang.IllegalStateException: Duplicate key io.ballerina.projects.ModuleDescriptor@600dfead (attempted merging values [io.ballerina.projects.ModuleDescriptor@a36787ac] and [io.ballerina.projects.ModuleDescriptor@a36787ac])
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.ballerina.projects.internal.BalaFiles.createModuleDescDependencies(BalaFiles.java:417)
	at io.ballerina.projects.internal.BalaFiles.createPackageDependencyGraph(BalaFiles.java:230)
	at io.ballerina.projects.internal.BalaFiles.createPackageDependencyGraph(BalaFiles.java:212)
	at io.ballerina.projects.internal.PackageConfigCreator.createBalaProjectConfig(PackageConfigCreator.java:93)
	at io.ballerina.projects.bala.BalaProject.loadProject(BalaProject.java:54)
	at io.ballerina.cli.cmd.PushCommand.pushBalaToCustomRepo(PushCommand.java:296)
	at io.ballerina.cli.cmd.PushCommand.pushPackage(PushCommand.java:204)
	at io.ballerina.cli.cmd.PushCommand.execute(PushCommand.java:147)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
```
# Clone the sample repository
$ git clone \
    --single-branch \
    --branch module-descriptor-conflict \
     https://bitbucket.org/gubaer/module-gubaer-opencsv.git

# Change working directory
$ cd module-gubaer-opencsv/ballerina

# build and publish to the local repository
$ bal build -c
$ bal push --repository local

# ==> Bad. Sad. 
```

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by azinneera** [comment]
@Gubaer thanks for reporting this issue. We have fixed this issue in Swan Lake Beta3. I cloned your project and I was able to successfully build and push the package to local repository with the Swan Lake beta release (SL Beta.5). Please download this from https://ballerina.io/downloads/ and try again.

Please not that we have introduced the `bal pack` command to build the ballerina archive. Please use this command instead of `bal build -c`
