### ISSUE TITLE
Bad. Sad. in 1.2.x when executing `run` command with `--sourceroot`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#32110]
**Description:**

**Steps to reproduce:**
1. Create a new Ballerina Project with `bal new myproj`
     This is the file structure created
```
myproj
├── Ballerina.toml
└── src
```
2. Add `main.bal` inside `src` directory 
```
myproj
├── Ballerina.toml
├── src
│   └── main.bal
└── target
    └── bin
```
3. Code for `main.bal`
```ballerina
public function main() {
    var wer = 2; 
}
```
4. Run this command
```
bal run --sourceroot myproj .
```
$ballerina-internal.log
```
[2021-08-11 12:03:44,696] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.packerina.buildcontext.BuildContext.getExecutablePathFromTarget(BuildContext.java:525)
	at org.ballerinalang.packerina.task.CleanTargetDirTask.execute(CleanTargetDirTask.java:48)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:293)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
```

**Affected Versions:**
1.2.15, 1.2.16 and 1.2.17 (at least)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is not fixed in Swan Lake.
