### ISSUE TITLE
NoClassDefFoundError: `bal run` crashes because of missing java class

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32153]
**Description:**
A sample package (see below) where `bal run` results in a `NoClassDefFoundError`.

```
[2021-08-12 17:56:32,848] SEVERE {b7a.log.crash} - gubaer/csvplus$0046java$0046util/0_0_1/$ConfigurationMapper 
java.lang.NoClassDefFoundError: gubaer/csvplus$0046java$0046util/0_0_1/$ConfigurationMapper
	at gubaer.csvplus$0046samples.0_0_1.$ConfigurationMapper.$configureInit(Unknown Source)
	at gubaer.csvplus$0046samples.0_0_1.$_init.main(csvplus.samples)
Caused by: java.lang.ClassNotFoundException: gubaer.csvplus$0046java$0046util.0_0_1.$ConfigurationMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```
**Steps to reproduce:**

```bash
# clone the sample repository
$ git clone \
    --single-branch \
    --branch missing-java-class \
     https://bitbucket.org/gubaer/module-gubaer-opencsv.git

# Change working directory, then build and publish the custom module
$ cd module-gubaer-opencsv/ballerina
$ bal build -c
$ bal push --repository local

# Change to the samples directory and run the sample script
$ cd module-gubaer-opencsv/samples
$ bal run
[2021-08-12 18:01:41,959] SEVERE {b7a.log.crash} - gubaer/csvplus$0046java$0046util/0_0_1/$ConfigurationMapper 
java.lang.NoClassDefFoundError: gubaer/csvplus$0046java$0046util/0_0_1/$ConfigurationMapper
	at gubaer.csvplus$0046samples.0_0_1.$ConfigurationMapper.$configureInit(Unknown Source)
	at gubaer.csvplus$0046samples.0_0_1.$_init.main(csvplus.samples)
Caused by: java.lang.ClassNotFoundException: gubaer.csvplus$0046java$0046util.0_0_1.$ConfigurationMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by warunalakshitha** [comment]
I have followed same steps and able to run the program without an issue. This is my output.

```
module-gubaer-opencsv$ cd ballerina/
module-gubaer-opencsv/ballerina$ bal build -c
Resolving Maven dependencies
	Downloading dependencies into /home/waruna/Dev/git/git1/module-gubaer-opencsv/ballerina/target/platform-libs
opencsv-5.5.1.jar 100% [=================================================================================================================================================] 229/229 KB (0:00:01 / 0:00:00) 

Compiling source
	gubaer/csvplus:0.0.1

Creating bala
	target/bala/gubaer-csvplus-java11-0.0.1.bala
module-gubaer-opencsv/ballerina$ bal push --repository local
Successfully pushed target/bala/gubaer-csvplus-java11-0.0.1.bala to 'local' repository.
module-gubaer-opencsv/ballerina$ ls
Ballerina.toml  main.bal  Makefile  modules  Package.md  parser.bal  target
module-gubaer-opencsv/ballerina$ cd ../
module-gubaer-opencsv$ cd samples/
module-gubaer-opencsv/samples$ ls
Ballerina.toml  Dependencies.toml  main.bal  sample-01.bal  sample-02.bal
module-gubaer-opencsv/samples$ bal run
Compiling source
	gubaer/csvplus.samples:0.0.1

Running executable

fatal: missing sample number
usage: bal run -- help | <number> 
where <number> is a sample number. Supported numbers:
     1  # just a hello world sample
     2  # sample for CSVParser which parses a single line

error: command line error {}
module-gubaer-opencsv/samples$ bal run 1
ballerina: The directory does not exist: 1

USAGE:
    bal run [--experimental] [--offline]
                  [<executable-jar | ballerina-file | package-path>] [-- program-args...]
module-gubaer-opencsv/samples$ bal run -- 1
Compiling source
	gubaer/csvplus.samples:0.0.1

Running executable

Hello World!

```

I think this is due to cache issue. Similar issue can be found from [1]. As per the stackoverflow response workaround is to clear the cache.

```
This is due to a caching issue in ballerina and will be fixed in a future release. For now, users can remove:

/home/${username}/.ballerina/repositories/central.ballerina.io directory on ubuntu
C:\Users\${username}\.ballerina\repositories\central.ballerina.io directory on windows
and rebuild.
```

[1] https://stackoverflow.com/questions/68363514/error-when-trying-to-open-a-jdbc-connection-using-ballerina-slbeta2

**Comment by Gubaer** [comment]
yes, this seems to be a caching issue. After having reset (deleted) the local ballerina repo, it works as expected. The issue can be closed.
