### ISSUE TITLE
Parser throws NoSuchElementException for an intermediate code snippet

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32188]
**Description:**
Consider the following code snippet:
```
import ballerina/http;
import ballerinax/mysql;

type Product record {|
    int id;
    string productName;
    float price;
    string currency;
|};

service /products on new http:Listener(8080) {

    private mysql:Client? cl = ();

    resource function get .() returns Product[] {
        stream<Product, error?> prodStream = self.cl->query("select id, product_name as productName, price, currency from products", Product);
        Product[] products = [];
        error? e = prodStream.forEach(function(Product p) {
            products[products.length()] = p;
        });

        if e is error {
        // return e;
        }

        return products;
    }

    function getClient() returns mysql:Client|error {
        mysql:Client? mysqlClient = self.cl;
        if mysqlClient is () {
            self.cl = check new ("localhost", user = "root", password = "root", database = "bal_productdb");
            mysqlClient = self.cl;
        }

        if mysqlClient is mysql:Client {
            mysql:Client clResult = self.cl;
            return self.cl;            
        } else {
            return error("Client not created");
        }
    }
}
```
This throws the following exception:
```
[Error - 10:59:59 PM] Operation 'ballerinaDocument/syntaxTreeNode' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/microservices_reactjs/product_service/main.bal', error: 'java.util.NoSuchElementException'}
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.endContext(AbstractParserErrorHandler.java:235)
	at io.ballerina.compiler.internal.parser.AbstractParser.endContext(AbstractParser.java:127)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:180)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:99)
	at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerina.projects.DocumentContext.parse(DocumentContext.java:88)
	at io.ballerina.projects.DocumentContext.syntaxTree(DocumentContext.java:92)
	at io.ballerina.projects.Document.syntaxTree(Document.java:55)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.syntaxTree(BallerinaWorkspaceManager.java:182)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentServiceImpl.lambda$syntaxTreeNode$13(BallerinaDocumentServiceImpl.java:343)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
and 
```
[Error - 10:59:59 PM] Operation 'text/didChange' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/microservices_reactjs/product_service/main.bal', error: 'java.util.NoSuchElementException'}
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.endContext(AbstractParserErrorHandler.java:235)
	at io.ballerina.compiler.internal.parser.AbstractParser.endContext(AbstractParser.java:127)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:180)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:99)
	at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerina.projects.DocumentContext.parse(DocumentContext.java:88)
	at io.ballerina.projects.DocumentContext.syntaxTree(DocumentContext.java:92)
	at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:129)
	at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:123)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:178)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:161)
	at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:238)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:147)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:71)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:78)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:213)
	at io.ballerina.projects.Package.getResolution(Package.java:139)
	at io.ballerina.projects.Module$Modifier.getAllDependants(Module.java:289)
	at io.ballerina.projects.Module$Modifier.createNewModule(Module.java:268)
	at io.ballerina.projects.Module$Modifier.apply(Module.java:240)
	at io.ballerina.projects.Document$Modifier.apply(Document.java:106)
```

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 2

**Comment by IMS94** [comment]
Couldn't reproduce this again on SL beta 2. May be this was caused by the writing pattern. Will reopen if I get this again.
