### ISSUE TITLE
ModuleContext throws concurrent modification exception

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32214]
**Description:**
Following exception is thrown while doing consecutive text edits/ compilations by opening a project in VSCode. (The project I'm using is the nBallerina project)

```
[Error - 4:03:39 PM] Operation 'text/didChange' failed! {uri: '/Users/nadeeshaan/Development/repo/nballerina/compiler/modules/types/error.bal', error: 'java.util.ConcurrentModificationException'}
java.util.ConcurrentModificationException
    at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
    at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
    at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:180)
    at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:171)
    at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:228)
    at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:163)
    at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:83)
    at io.ballerina.projects.PackageResolution.from(PackageResolution.java:90)
    at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:235)
    at io.ballerina.projects.Package.getResolution(Package.java:148)
    at io.ballerina.projects.Package$Modifier.createNewPackage(Package.java:433)
    at io.ballerina.projects.Package$Modifier.apply(Package.java:415)
    at io.ballerina.projects.Module$Modifier.createNewModule(Module.java:279)
    at io.ballerina.projects.Module$Modifier.apply(Module.java:240)
    at io.ballerina.projects.Document$Modifier.apply(Document.java:106)
    at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.updateBalDocument(BallerinaWorkspaceManager.java:801)
    at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didChange(BallerinaWorkspaceManager.java:282)
    at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:506)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
SwanLake beta3-snapshot at least

**Comment by azinneera** [comment]
With PR #32715, the original issue is resolved but still the ConcurrentModificationException is thrown from anther place:
```
[Error - 5:47:29 PM] Operation 'ballerinaPackage/components' failed! {, error: 'java.util.ConcurrentModificationException'}
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:180)
	at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:205)
	at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:248)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:197)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:89)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:96)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:235)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:99)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$getPackageComponents$13(BallerinaPackageServiceImpl.java:131)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.getPackageComponents(BallerinaPackageServiceImpl.java:124)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$1(BallerinaPackageServiceImpl.java:99)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$2(BallerinaPackageServiceImpl.java:99)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$3(BallerinaPackageServiceImpl.java:97)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$4(BallerinaPackageServiceImpl.java:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by sameerajayasoma** [comment]
I think we need to make sure that only one compilation can be active for a given package for a given instance.

**Comment by nadeeshaan** [comment]
> I think we need to make sure that only one compilation can be active for a given package for a given instance.

@sameerajayasoma we have the locking implementation in language server where all the compilations are going through the lock in the `WorkspaceManager`.

This seems to a usage issue in the `BallerinaPackageService` extension service implementation. @prabushi shall we check whether we are doing any compilations in between?
