### ISSUE TITLE
Bad sad errors in invalid interop FieldSet and FieldGet

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#32226]
**Description:**

$title

**Steps to reproduce:**

```java
package javalibs.app;

public class AppInstance {
	public boolean testBoolField;
}
```
Gives the following bad sad errors for the above java code with each of the ballerina codes
Ballerina code 1
```ballerina
import ballerina/jballerina.java;

public function main() {
    boolean ans = testBoolField();
}

function testBoolField() returns boolean = @java:FieldGet {
    name:"testBoolField",
    'class:"javalibs.app.AppInstance"
} external;
```
```logtalk
Compiling source
ballerina: Oh no, something really went wrong. Bad. Sad.

[2021-08-20 10:21:22,971] SEVERE {b7a.log.crash} - null 
java.lang.IndexOutOfBoundsException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:418)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:820)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:92)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:69)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:426)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:345)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:161)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.genJFieldForInteropField(InteropMethodGen.java:205)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.genJMethodForBExternalFunc(ExternalMethodGen.java:74)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:152)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:467)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
Ballerina code 2
```bal
import ballerina/jballerina.java;

public function main() {
    boolean ans = testBoolField(2);
}

function testBoolField(int arg) returns boolean = @java:FieldGet {
    name:"testBoolField",
    'class:"javalibs.app.AppInstance"
} external;
```
```logtalk
Compiling source
        nadeeshan/FieldSetInstanceProject:0.1.0

Running executable

[2021-08-20 10:26:18,686] SEVERE {b7a.log.crash} - Bad local variable type
Exception Details:
  Location:
    nadeeshan/FieldSetInstanceProject/0/main.testBoolField(Lio/ballerina/runtime/internal/scheduling/Strand;JZ)Z @0: aload_1
  Reason:
    Type long (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', long, long_2nd, integer }
    stack: { }
  Bytecode:
    0000000: 2bb6 0097 c000 9959 c700 11b2 009f b200
    0000010: a503 bd00 04b8 00ab bfb4 00ad 3604 1504
    0000020: ac                                     
  Stackmap Table:
    same_locals_1_stack_item_frame(@25,Object[#153])
 
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    nadeeshan/FieldSetInstanceProject/0/main.testBoolField(Lio/ballerina/runtime/internal/scheduling/Strand;JZ)Z @0: aload_1
  Reason:
    Type long (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', long, long_2nd, integer }
    stack: { }
  Bytecode:
    0000000: 2bb6 0097 c000 9959 c700 11b2 009f b200
    0000010: a503 bd00 04b8 00ab bfb4 00ad 3604 1504
    0000020: ac                                     
  Stackmap Table:
    same_locals_1_stack_item_frame(@25,Object[#153])

        at nadeeshan.FieldSetInstanceProject.0.$_init.$lambda$main$(FieldSetInstanceProject)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:608)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:333)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:301)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Ballerina code 3
```bal
import ballerina/jballerina.java;

public function main() {
    testBoolField(2, true);
}

function testBoolField(int receiver, boolean arg) = @java:FieldSet {
    name:"testBoolField",
    'class:"javalibs.app.AppInstance"
} external;
```
```logtalk
Compiling source
        nadeeshan/FieldSetInstanceProject:0.1.0

Running executable

[2021-08-20 10:35:49,326] SEVERE {b7a.log.crash} - Bad local variable type
Exception Details:
  Location:
    nadeeshan/FieldSetInstanceProject/0/main.testBoolField(Lio/ballerina/runtime/internal/scheduling/Strand;JZZZ)Ljava/lang/Object; @0: aload_1
  Reason:
    Type long (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', long, long_2nd, integer, integer, integer }
    stack: { }
  Bytecode:
    0000000: 2bb6 009a c000 9c59 c700 11b2 00a2 b200
    0000010: a803 bd00 04b8 00ae bf15 04b5 00b0 013a
    0000020: 0619 06b0                              
  Stackmap Table:
    same_locals_1_stack_item_frame(@25,Object[#156])
 
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    nadeeshan/FieldSetInstanceProject/0/main.testBoolField(Lio/ballerina/runtime/internal/scheduling/Strand;JZZZ)Ljava/lang/Object; @0: aload_1
  Reason:
    Type long (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', long, long_2nd, integer, integer, integer }
    stack: { }
  Bytecode:
    0000000: 2bb6 009a c000 9c59 c700 11b2 00a2 b200
    0000010: a803 bd00 04b8 00ae bf15 04b5 00b0 013a
    0000020: 0619 06b0                              
  Stackmap Table:
    same_locals_1_stack_item_frame(@25,Object[#156])

        at nadeeshan.FieldSetInstanceProject.0.$_init.$lambda$main$(FieldSetInstanceProject)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:608)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:333)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:301)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

And for the following java code
```java
package javalibs.app;

public class AppInstance {
	public static boolean testBoolField;
}
```
with the following ballerina code
```bal
import ballerina/jballerina.java;;

public function main() {
    testBoolField();
}


function testBoolField() = @java:FieldSet {
    name: "testBoolField",
    'class: "javalibs.app.AppInstance"
} external;
```
gives
```logtalk
Compiling source
        nadeeshan/StaticFieldGetSetProject:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

[2021-08-20 11:24:05,741] SEVERE {b7a.log.crash} - null 
java.lang.NegativeArraySizeException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:418)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:820)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:92)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:69)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:426)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:345)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:161)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
Caused by: java.lang.NegativeArraySizeException: -1
        at org.objectweb.asm.Frame.merge(Frame.java:1222)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.genJFieldForInteropField(InteropMethodGen.java:282)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.genJMethodForBExternalFunc(ExternalMethodGen.java:74)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:152)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:467)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
**Affected Versions:**
slbeta3-snapshot

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/jBallerina

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/32452
