### ISSUE TITLE
Bad Sad Error when Ballerina.toml is not complete 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#32235]
**Description:**

Consider the following Ballerin.toml file
```
[package]
org = "malinthar"
name = "bootstrap_node"
version = "0.1.0"
export = ["bootstrap_node","bootstrap_node.node","bootstrap_node.constants"]

[build-options]
observabilityIncluded = true
observabilityIncluded = true
experimental = true
offline = true
skipTests = true
testReport = true
codeCoverage = true

[[platform.java11.dependecy]]

```
When we haven't specified the properties of [[platform.java11.dependency]] in the Ballerina.toml build the project using the CLI command following stack trace is observed.

```
 bal build -c
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in 
https://github.com/ballerina-platform/ballerina-lang/issues with the 
log you get below and your sample code.

We thank you for helping make us better.

[2021-08-19 13:59:31,729] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.projects.internal.ManifestBuilder.getPlatforms(ManifestBuilder.java:339)
        at io.ballerina.projects.internal.ManifestBuilder.parseAsPackageManifest(ManifestBuilder.java:189)
        at io.ballerina.projects.internal.ManifestBuilder.<init>(ManifestBuilder.java:101)
        at io.ballerina.projects.internal.ManifestBuilder.from(ManifestBuilder.java:107)
        at io.ballerina.projects.internal.PackageConfigCreator.createBuildProjectConfig(PackageConfigCreator.java:70)
        at io.ballerina.projects.directory.BuildProject.load(BuildProject.java:88)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:225)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)

```
**Steps to reproduce:**
Mentioned above

**Affected Versions:**
sl-beta2

**Comment by malinthar** [comment]
Closing as this is fixed in slbeta3
