### ISSUE TITLE
Cannot have an enum field named `'error`

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#32239]
**Description:**
$Subject

**Steps to reproduce:**
Run the following code.
```
public enum WebsocketMessage {
    unknown,
    control,
    data,
    'error
}
```

It crashes with the following error message.
```
[2021-08-19 14:59:10,269] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BErrorTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BConstantSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BErrorTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BConstantSymbol are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BErrorTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BConstantSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BErrorTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BConstantSymbol are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.createEnumSymbol(SymbolEnter.java:1734)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1492)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:111)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:1123)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:384)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:318)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:268)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:190)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:177)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:102)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:91)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

**Affected Versions:**
SL Beta2

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/30268

**Comment by dilanSachi** [comment]
`'json`  and `'anydata` also results in the same issue

**Comment by MaryamZi** [comment]
Once the initial issue is fixed may be related to https://github.com/ballerina-platform/ballerina-lang/issues/34950.
