### ISSUE TITLE
Using `var` as a module variable name causes `CCE` in `SymbolFactory`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32520]
**Description:**
Consider the bellow sample where `var` is used as a module variable name 
```bal
type ab int; 
ab var = 5;
```

Causes CCE in `SymbolFactory` when hover `ab`. Local variable declaration gives errors as expected.
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.SymbolFactory.createFunctionSymbol(SymbolFactory.java:253)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:139)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.moduleSymbols(BallerinaSemanticModel.java:166)
	at org.ballerinalang.langserver.extensions.ballerina.document.ExecutorPositionsUtil.getExecutorPositions(ExecutorPositionsUtil.java:77)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentServiceImpl.lambda$executorPositions$14(BallerinaDocumentServiceImpl.java:380)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

**Affected Versions:**
Current master

**Comment by pubudu91** [comment]
Closing since this seems to be fixed in master.
