### ISSUE TITLE
Compiler crashes when `byte-array-literal` is written over multiple lines

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#32545]
**Description:**
As per the spec, [byte-array-literal](https://ballerina.io/ballerina-spec/spec.html#byte-array-literal) can include newlines. But the compiler crashes at such instances. 

For example following sample gives `StringIndexOutOfBoundsException`.
```bal
byte[] glbByteArray1 = base16 `afcd34abcdef123abc234bc
d1a4bdfaaabadabcd892312df`;
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2021-09-02 12:40:44,833] SEVERE {b7a.log.crash} - String index out of range: 49 
java.lang.StringIndexOutOfBoundsException: String index out of range: 49
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.hexStringToByteArray(Desugar.java:5675)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteBlobLiteral(Desugar.java:5651)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5639)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2364)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:80)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8055)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1266)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1311)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:801)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:232)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:150)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
```
</details>

**Comment by lochana-chathura** [comment]
Also crash when they are tabs instead of spaces.
```bal
public function main() {
    byte[] byteArray1 = base64 `aGVsbG8gYmFsbGVyaW5hICEhIQ==`;
   // In following two cases, we have tabs. not spaces.
    byte[] byteArray2 = base64 `aGVs	bG8g	YmFs	bGVy	aW5h	ICEh	IQ==`; spaces
    byte[] byteArray3 = base64 `	aG	Vs	b	G	8g	Y	mFs	bGVy	aW5h	ICEh	IQ=		=	`;
    
    io:println(byteArray1 == byteArray2); // @output true
    io:println(byteArray1 == byteArray3); // @output true    
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
java.lang.IllegalArgumentException: Illegal base64 character 9
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:743)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:535)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteBlobLiteral(Desugar.java:5649)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5639)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1371)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1500)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8055)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1266)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1311)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8072)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:804)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:232)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:150)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:157)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
```
</details>
