### ISSUE TITLE
NPE with unary complement expression in constant declaration

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#32628]
**Description:**
```ballerina
const int CONST2 = ~~false;
```

**Steps to reproduce:**
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.calculateBitWiseComplement(ConstantValueResolver.java:407)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.evaluateUnaryOperator(ConstantValueResolver.java:249)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:196)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangUnaryExpr.accept(BLangUnaryExpr.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visitExpr(ConstantValueResolver.java:436)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:91)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangConstant.accept(BLangConstant.java:107)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.lambda$resolve$1(ConstantValueResolver.java:82)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.resolve(ConstantValueResolver.java:82)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:314)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:299)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:206)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:394)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
        at io.ballerina.projects.Package.getCompilation(Package.java:140)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```
**Affected Versions:**
SL Beta 3 RC2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdulmina** [comment]
Fixed with #33502
