### ISSUE TITLE
Compiler crashes when using a spread field inside a table constructor

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#32707]
Consider the following:
```ballerina
type Foo record {
    readonly int x;
    int y;
};

public function main() {
    var m = {x: 1002, y: 30};

    var tb = table key(x) [
        {x: 1001, y: 20},
        {...m} // spread field 
    ];
}
```
The above fails with the following log
```[2021-09-13 15:52:40,057] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getRecordKeyValueField(TypeChecker.java:1193)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.validateTableKeyValue(TypeChecker.java:1150)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkKeySpecifier(TypeChecker.java:1006)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:885)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTableConstructorExpr.accept(BLangTableConstructorExpr.java:67)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:374)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:353)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.handleDeclaredWithVar(SemanticAnalyzer.java:1447)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:878)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3840)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3808)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3800)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1755)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3840)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3808)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3804)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:480)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3840)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:450)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3840)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3808)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3800)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:336)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:302)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:206)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:394)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
        at io.ballerina.projects.Package.getCompilation(Package.java:140)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
 
ERROR [.:(1:1,1:1)] Compilation failed due to: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField are in unnamed module of loader 'app')
error: compilation contains errors
```

**Comment by pubudu91** [comment]
Also, what's the following log about? 🤔 Is that a part of the crash log or the compiler error message. If it's the latter, does it belong in a compile error message? 🤔 
```
ERROR [.:(1:1,1:1)] Compilation failed due to: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordKeyValueField are in unnamed module of loader 'app')
error: compilation contains errors
```

**Comment by pubudu91** [comment]
In which version will the fix for this be available? Shall we tag the milestone please?
