### ISSUE TITLE
NPE with annotation for module variable declaration 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#32709]
**Description:**
Getting a  `NullPointerException` when running the following code snippet
```ballerina
public annotation modVar;

@modVar
var p = 2;
```

Output:
```
❯ bal run var_decl_symbol_test.bal
Compiling source
        var_decl_symbol_test.bal
[2021-09-13 16:46:07,548] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:328)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:240)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:154)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:137)
        at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:230)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:144)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:394)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
        at io.ballerina.projects.Package.getCompilation(Package.java:140)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:176)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

**Affected Versions:**
Beta 2, Beta 3

**Comment by dulajdilshan** [comment]
This doesn't show the usual "Bad. Sad" message

**Comment by MaryamZi** [comment]
Can't seem to reproduce this on 2201.0.1-rc3. @dulajdilshan, can you please check?

**Comment by dulajdilshan** [comment]
Tested with `2201.0.1-rc3` pack and `2201.0.x` branch. The issue seems to be fixed indirectly
