### ISSUE TITLE
Bad sad error is thrown for string template

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#32723]
**Description:**
I get a bad sad error for the following application,

```
import ballerina/http;
import ballerina/io;
import ballerinax/aws.s3;

const string ACCESS_KEY_ID = "non-confidential-access-key";
const string SECRET_ACCESS_KEY = "non-confidential-secret-access-key";
const string US_EAST_1_REGION = "us-east-1";
const int NUMBER_OF_COLUMNS_IN_CSV = 12;

final s3:Client amazonS3Client = check new ({
    accessKeyId: ACCESS_KEY_ID,
    secretAccessKey: SECRET_ACCESS_KEY,
    region: US_EAST_1_REGION
});

service / on new http:Listener(8090) {
    resource function get tv_shows(string country) returns json|error {
        s3:S3Object movieCatalogResponse = check amazonS3Client->getObject("library-catalog", "movies-tv-shows.csv");
        byte[]? byteArray = movieCatalogResponse?.content;
        if byteArray is byte[] {
            io:ReadableCharacterChannel readableCharacterChannel = new (check io:createReadableChannel(byteArray), 
                                                                        "UTF-8");
            io:ReadableCSVChannel csvChannel = new (readableCharacterChannel, io:COMMA, NUMBER_OF_COLUMNS_IN_CSV);

            stream<string[], io:Error?> csvStream = check csvChannel.csvStream();
            int tvShowCount = 0;
            check from string[] cells in csvStream
                  where cells[1].equalsIgnoreCaseAscii("TV Show") && cells[5].equalsIgnoreCaseAscii(country)
                  do {
                      tvShowCount += 1;
                  };

            return { title: string `TV shows from ${country}`, count: tvShowCount};
        } else {
            return error("Error: unexpected content");
        }
    }
}

```

The error log is as follows,

```
Compiling source
	sample.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

[2021-09-14 12:58:08,998] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:2001)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1690)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.generateMappingConstructorEntries(BIRGen.java:2875)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1679)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangMapLiteral.accept(BLangRecordLiteral.java:264)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1482)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangReturn.accept(BLangReturn.java:44)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1119)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1556)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:743)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:694)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:600)
	at org.wso2.ballerinalang.compiler.tree.BLangResourceFunction.accept(BLangResourceFunction.java:40)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:400)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:400)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:147)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:133)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:107)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:106)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

However, when I change the following line,

```
 return { title: string `TV shows from ${country}`, count: tvShowCount};
```

as follows,

```
 return { title: "", count: tvShowCount};
```
the application gets compiled and starts running as expected.

**Steps to reproduce:**
See the above description.

**Affected Versions:**
I observed this with Ballerina SL Alpha 5.11

**OS, DB, other environment details and versions:**
Ubuntu 20.04, JDK 11.0.8

**Comment by MaryamZi** [comment]
This seems to be the same as https://github.com/ballerina-platform/ballerina-lang/issues/30864, due to the query action.

This was fixed for Swan Lake beta1, also verified with Swan Lake beta3-rc3.

This works on alpha5, when `country` is assigned to a local variable and the local variable is used within the query.

```ballerina
            string localCountry = country; // `localCountry` as a workaround
            check from string[] cells in csvStream
                  where cells[1].equalsIgnoreCaseAscii("TV Show") && cells[5].equalsIgnoreCaseAscii(localCountry)
                  do {
                      tvShowCount += 1;
                  };
```

**Comment by MaryamZi** [comment]
Closing since this is a duplicate and was already fixed in slbeta1.
