### ISSUE TITLE
Ballerina project build fails throwing `StackOverflowError` exception

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-lang#32725]
**Description:**
Following error was thrown while building Ballerina Jira connector which was generated using Ballerina Open API tool.

```
java.lang.StackOverflowError
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
```

Please find the connector code [here](https://github.com/aneeshafedo/jira). 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Reproducible with

```ballerina
public function fn(Foo[] f) {
}

public type Foo record {
    Foo[] x;
}[];
```

We need to track visited types here.
