### ISSUE TITLE
FileSystem Exception when specifying a local dependency declaration without repository value

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#32787]
**Description:**
Following FileSystem Exception is thrown when specifying a local dependency declaration without repository value.

```
java.nio.file.FileSystemNotFoundException: /Users/dilhashanazeer/.ballerina/repositories/local/bala/winery/package_h/0.1.0/java11
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:118)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at io.ballerina.projects.internal.BalaFiles.createPackageDependencyGraph(BalaFiles.java:212)
	at io.ballerina.projects.internal.repositories.FileSystemRepository.getModules(FileSystemRepository.java:239)
	at io.ballerina.projects.internal.BlendedManifest.moduleNames(BlendedManifest.java:114)
	at io.ballerina.projects.internal.BlendedManifest.from(BlendedManifest.java:75)
	at io.ballerina.projects.PackageResolution.createBlendedManifest(PackageResolution.java:403)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:86)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:96)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:235)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:99)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:337)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:53)
	
```

Expected behavior is to get a diagnostic as follows.

`repository under [[dependency]] is missing`

**Steps to reproduce:**

create a Ballerina project and add a local dependency declaration in `Ballerina.toml` without the repository value as follows.

```
[[dependency]]
org="winery"
name="package_h"
version="0.1.0"
```

**Affected Versions:**
Beta.3-rc3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The reason is that we assume that the package is always present in the local repository. As the fix, we should make it similar to other repos where a package can be non-existent in the repository.

Can be reproduced with the following minimum steps:

1. Create a new ballerina package
2. Add `import myorg/package_a as _;` in main.bal
3. Add a matching local repo entry in Ballerina.toml
```
[[dependency]]
org="myorg"
name="a"
version="0.1.0"
repository="local"
```
4. Build the project
