### ISSUE TITLE
Semantic Analyzer throws NPE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32830]
**Description:**
Consider the following screen capture

https://user-images.githubusercontent.com/1329674/134150583-c4ffa1e5-4fec-40fe-9ced-4158f7a24354.mp4

Following stack trace is thrown

```
2021-09-21 15:21:34,302] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.initPredeclaredModules(SymbolEnter.java:1044)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:323)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:280)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:273)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:274)
	at org.ballerinalang.langserver.util.LSClientUtil.chekAndRegisterCommands(LSClientUtil.java:77)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:512)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36520.
