### ISSUE TITLE
Bad Sad for certain invalid decimal floating point numbers

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#32839]
**Description:**
All of the invalid decimal floating point numbers in the code snippet below result in a compiler crash.    

**Steps to reproduce:**
```
public function main() {
    float|decimal a = 25.E;1742;
    a = 25.E=1742;
    a = 25.E:1742;
    a = 25.E,1742;
// NOTE: In above samples there might be other symbols that can cause these to fail

    a = .99E-;
    a = .99E+;
    a = .99E;
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-03-09 15:31:51,138] SEVERE {b7a.log.crash} - For input string: "25.E" 
java.lang.NumberFormatException: For input string: "25.E"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.validateFloatLiteral(Types.java:3589)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getTypeOfDecimalFloatingPointLiteral(TypeChecker.java:651)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setLiteralValueAndGetType(TypeChecker.java:704)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:425)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:55)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:354)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1052)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1907)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
```
</details>

**Comment by lochana-chathura** [comment]
We can enable these with this fix.
https://github.com/ballerina-platform/ballerina-lang/blob/cd0e3896697e6a1fe2a3d3f57f6f8a00bc696675/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java#L54-L57
