### ISSUE TITLE
Bad Sad for certain invalid hex floating point literals

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#32840]
**Description:**
All of the invalid hex floating point literals in the code snippet below result in a compiler crash.  

**Steps to reproduce:**

```
public function main() {
    float|decimal a = 0x 3eA3p34;
    a = 0Xp34;
    a = 0x3eA3p-;
    a = 0x3eA3p+;
    a = 0x3eA3p;
    a = 0x 3eA3 .4Eb2 p45;
    a = 0x 3eA3.4Eb2p+45;
    
    a = 0X3eAp;
    a = 0x3eA3p=34;
    a = 0x3eA3p:34;
    a = 0x3eA3p,34;
    a = 0x=4Eb2P-45;
    a = 0x:4Eb2P-45;
    a = 0x,4Eb2P-45;
// NOTE: In above samples there might be other symbols that can cause these to fail
}
```

**Related Issues (optional):**
#32750

**Comment by lochana-chathura** [comment]
The current CCE will be fixed with PR #35470. 
Now this is failing with a NumberFormatException. This is due to the same issue as of #32839
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
java.lang.NumberFormatException: For input string: "0Xp34"
	at java.base/jdk.internal.math.FloatingDecimal.parseHexString(FloatingDecimal.java:2082)
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1870)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.validateFloatLiteral(Types.java:3589)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getTypeOfHexFloatingPointLiteral(TypeChecker.java:670)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setLiteralValueAndGetType(TypeChecker.java:709)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:425)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:55)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:354)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2026)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
```
</details>
