### ISSUE TITLE
NPE in `BallerinaMapTypeSymbol`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32955]
**Description:**
Consider the bellow sample
```bal
public function main() {
    map<string> a = {a: "dul", b: "grg"}.<cursor>
    map<string> b = {d: "dul", e: "fg"};
}
```
Causes NPE at `BallerinaMapTypeSymbol`
```
[Error - 10:47:48 AM] CodeAction 'ChangeVariableTypeCodeAction' failed! {, error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.symbols.BallerinaMapTypeSymbol.signature(BallerinaMapTypeSymbol.java:64)
	at org.ballerinalang.langserver.common.utils.FunctionGenerator.generateTypeDefinition(FunctionGenerator.java:53)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:314)
	at org.ballerinalang.langserver.codeaction.providers.changetype.ChangeVariableTypeCodeAction.getDiagBasedCodeActions(ChangeVariableTypeCodeAction.java:91)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:107)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:101)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:99)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:157)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:315)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sanjana** [comment]
This is being parsed as `{a: dul,b: grg}.map(<> b, $missingNode$_0= {d: dul,e: fg})`, and within the `TypeChecker` `checkInvocationParamAndReturnType(BLangInvocation iExpr)` method is logging this diagnostic. 

It would be unknown at the `TypeChecker`, whether this was a parser-generated node or not.
