### ISSUE TITLE
Diagram not loaded in VSCode due to `BallerinaPackageService.components()` throwing an exception

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32954]
**Description:**
VSCode plugin uses above mentioned method to determine components in the project.

```java
[Error - 10:36:02 AM] Operation 'ballerinaPackage/components' failed! {, error: 'provided path is not a regular file: /home/imesha/Documents/WSO2/Ballerina/Projects/csv_querying'}
io.ballerina.projects.ProjectException: provided path is not a regular file: /home/imesha/Documents/WSO2/Ballerina/Projects/csv_querying
	at io.ballerina.projects.util.ProjectPaths.packageRoot(ProjectPaths.java:53)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:847)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:839)
	at com.google.common.cache.LocalCache.lambda$computeIfAbsent$0(LocalCache.java:4204)
	at com.google.common.cache.LocalCache$LoadingValueReference.compute(LocalCache.java:3567)
	at com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2243)
	at com.google.common.cache.LocalCache.compute(LocalCache.java:4197)
	at com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4204)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:211)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$getPackageComponents$13(BallerinaPackageServiceImpl.java:132)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.getPackageComponents(BallerinaPackageServiceImpl.java:125)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$1(BallerinaPackageServiceImpl.java:100)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$2(BallerinaPackageServiceImpl.java:100)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$3(BallerinaPackageServiceImpl.java:98)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$4(BallerinaPackageServiceImpl.java:97)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
Open a ballerina project and on left hand side, under `Diagram` panel, click the `reload` icon. Above error will be logged in the plugin output.

**Affected Versions:**
SL Beta 3 RC4

**Comment by IMS94** [comment]
When investigated, above method uses `workspaceManager.waitAndGetPackageCompilation(project.sourceRoot())`. Inside workspace manager, we use `ProjectPaths.packageRoot(path)` to determine the project root. That method doesn't support the path to be the package root itself.
