### ISSUE TITLE
Invoking goto definition for standard libraries throws a NPE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33047]
**Description:**
$title

Please refer the following stacktrace, and this leads to goto definition not working within the standard library sources

```
[Error - 12:35:48 PM] Operation 'text/didOpen' failed! {uri: '/Library/Ballerina/distributions/ballerina-slbeta3/repo/bala/ballerina/io/1.0.0/java11/modules/io/print.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.projects.Module$Modifier.getAllDependants(Module.java:298)
	at io.ballerina.projects.Module$Modifier.getAllDependants(Module.java:290)
	at io.ballerina.projects.Module$Modifier.createNewModule(Module.java:268)
	at io.ballerina.projects.Module$Modifier.apply(Module.java:240)
	at io.ballerina.projects.Document$Modifier.apply(Document.java:106)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.updateBalDocument(BallerinaWorkspaceManager.java:801)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didOpen(BallerinaWorkspaceManager.java:251)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:486)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**

**Affected Versions:**
SwanLakeBeta3-RC5

**Comment by azinneera** [comment]
Checked this locally and found that when the `print.bal` is opened, a file update call is being triggered for this file. @nadeeshaan why do we need to do an edit operation for `didOpen`? Project API edit operations are not designed to edit a file in a bala project. In the Project API, we can improve to introduce read-only type project or at least to throw and `UnsupportedOperationException` for bala file edits. But still the LS needs to handle this exception to handle it

**Comment by nadeeshaan** [comment]
We treat what ever the project kind (bala/ source) in a similar manner within the language server since we need to jump in to the references within the bala projects as well. 
The file update upon the open is for handling a special case, where the user creates a new file from the editor for an already opened editor. 
Earlier this was working without any issue (beta2) and that is the major concern.

**Comment by nadeeshaan** [comment]
For the moment we will be sending a fix from the LS to avoid the inmemory update which will not proceed to the NPE. As per the discussion with @azinneera, let's throw an unsupported operation exception for attempting the edits on bala sources from the Project API

**Comment by azinneera** [comment]
Closing the issue based on the last comment.
