### ISSUE TITLE
Using checkpanic inside xml-template-expr crashes the compiler

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33079]
Consider the following code

```
import ballerina/io;

public function main() {
    xml z = xml `<A>${xml `<B>${checkpanic foo()}</B>`}</A>`;
    io:println(z); // @output <A><B>23</B></A>
}

function foo() returns error|int {
    return 23;
}
```

Compiling above code gives the below exception

```
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:790)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckPanickedExpr.accept(BLangCheckPanickedExpr.java:44)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:969)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLTextLiteral.accept(BLangXMLTextLiteral.java:52)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExprs(ClosureDesugar.java:1582)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:962)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExprs(ClosureDesugar.java:1582)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:962)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:898)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:554)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:417)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteStmt(ClosureDesugar.java:1574)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:292)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:284)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.lambda$visit$1(ClosureDesugar.java:218)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:217)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:811)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:455)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:234)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:412)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:345)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

**Comment by MaryamZi** [comment]
This was an issue with interpolated `xml` template expressions. Same as [#33077](https://github.com/ballerina-platform/ballerina-lang/issues/33077), fixed for slbeta6 in [#33821](https://github.com/ballerina-platform/ballerina-lang/pull/33821).
