### ISSUE TITLE
xml attribute values without double quotes in xml template expression crashes the compiler

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33074]
Consider the following code

```ballerina
public function main() {
    xmlValue = xml `<Book price=65></Book>`; 
}
```

Compiling the above code using Ballerina SL Beta3 crashes with the following exception

```
java.lang.IllegalStateException
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLCharacterSet(XMLParser.java:630)
        at io.ballerina.compiler.internal.parser.XMLParser.parseAttributeValue(XMLParser.java:402)
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLAttribute(XMLParser.java:364)
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLElementStartOrEmptyTag(XMLParser.java:178)
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLElement(XMLParser.java:146)
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLContentItem(XMLParser.java:108)
        at io.ballerina.compiler.internal.parser.XMLParser.parseXMLContent(XMLParser.java:63)
        at io.ballerina.compiler.internal.parser.XMLParser.parse(XMLParser.java:47)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTemplateContentAsXML(BallerinaParser.java:10508)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseXMLTemplateExpression(BallerinaParser.java:10459)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4928)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4856)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:4850)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4828)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4823)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4818)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseActionOrExpression(BallerinaParser.java:4758)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseAssignmentStmtRhs(BallerinaParser.java:4715)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatementStartWithExprRhs(BallerinaParser.java:8415)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypedBPOrExprRhs(BallerinaParser.java:14589)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStmtStartsWithTypeOrExpr(BallerinaParser.java:14577)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4173)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4166)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4128)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2832)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2795)
        at io.ballerina.compiler.internal.parser.BallerinaParser.createFunctionDefinition(BallerinaParser.java:1366)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrMethodDeclEnd(BallerinaParser.java:1277)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionDefinition(BallerinaParser.java:1169)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDescRhs(BallerinaParser.java:1195)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1228)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1159)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:812)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:800)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:320)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:252)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:156)
        at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:100)
        at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:56)
        at io.ballerina.projects.DocumentContext.parse(DocumentContext.java:86)
        at io.ballerina.projects.DocumentContext.syntaxTree(DocumentContext.java:90)
        at io.ballerina.projects.DocumentContext.getModuleLoadRequests(DocumentContext.java:127)
        at io.ballerina.projects.DocumentContext.moduleLoadRequests(DocumentContext.java:121)
        at io.ballerina.projects.ModuleContext.populateModuleLoadRequests(ModuleContext.java:176)
        at io.ballerina.projects.PackageResolution.getModuleLoadRequestsOfDirectDependencies(PackageResolution.java:205)
        at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:248)
        at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:197)
        at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:89)
        at io.ballerina.projects.PackageResolution.from(PackageResolution.java:96)
        at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:235)
        at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:99)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
        at io.ballerina.projects.Package.getCompilation(Package.java:140)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:75)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

**Comment by rdulmina** [comment]
Fixed with #33074
