### ISSUE TITLE
Subsequent compilation fails after pull module codeaction making LS unresponsive

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33073]
**Description:**
We added `pull module` codeaction to LS in beta 3 (#31725) to pull locally unavailable modules when imported in the source code.  Now, when `pull module` codeaction is executed, required modules are downloaded. But the subsequent compilation fails with the following error:
```
[Error - 7:30:51 PM] Operation 'ballerinaDocument/executorPositions' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/projects/analytics/processor.bal', error: 'Semantic model cannot be retrieved when the module is in compilation state 'PLATFORM_LIBRARY_GENERATED'. This is an internal error which will be fixed in a later release.'}
java.lang.IllegalStateException: Semantic model cannot be retrieved when the module is in compilation state 'PLATFORM_LIBRARY_GENERATED'. This is an internal error which will be fixed in a later release.
	at io.ballerina.projects.PackageCompilation.getSemanticModel(PackageCompilation.java:147)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:441)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:431)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:423)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:115)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:68)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:121)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at org.ballerinalang.langserver.extensions.ballerina.document.ExecutorPositionsUtil.getExecutorPositions(ExecutorPositionsUtil.java:75)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentServiceImpl.lambda$executorPositions$14(BallerinaDocumentServiceImpl.java:380)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
After this failure, LS functionalities (completions, codeactions) stop working.

When implementing, used the recommended approach (https://github.com/ballerina-platform/ballerina-lang/issues/30757#issuecomment-876233632).

Similar issue has recently been discovered in https://github.com/ballerina-platform/ballerina-lang/issues/32525#issuecomment-915852975

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 3 RC5

**Comment by IMS94** [comment]
This happens only in multi module projects. To force a recompilation, inside `worspace manager`, we update a document inside the project. It's not enough to force recompilation on all modules in the project. Therefore, need to change the logic to update a document in each module of the project as a workaround.

**Comment by hevayo** [comment]
@mohanvive This got dragged due to the unforeseen issues but I would not consider this as workarounds it just the solution is getting a bit complicated due the LS use-cases. And yes we can give an API but it will use the above approach.

**Comment by sameerajayasoma** [comment]
At first, we thought that the pull action required the following three things:
- Create the dependency graph with precise versions.
- Pull missing packages from central 
- Compile missing packages to create compilation caches. 

The first two things are handled by the `PackageResolution pkgResolution = Package.getResolution()` method. 

@azinneera, Shall we try this approach first? We need to figure out whether we need the third step.
