### ISSUE TITLE
Compiler crashes for `io:println(transactional);` with NPE when there's no `transaction-stmt`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#33087]
**Description:**
Following code crashes when the `transaction-stmt` is commented out.
```bal
public function main() returns error? {
    io:println(transactional);

    // transaction {
    //     io:println("Stage1 completed");
    //     io:println("Stage2 completed");
    //     io:println(transactional);
    //     check commit;
    // }
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:669)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7303)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTransactionalExpr.accept(BLangTransactionalExpr.java:38)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6958)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6958)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8079)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5712)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr$BLangArrayLiteral.accept(BLangListConstructorExpr.java:89)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8079)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6285)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6225)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8039)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3324)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8055)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1266)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1311)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8072)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:804)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8014)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:232)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:150)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:157)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:114)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:65)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:302)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```        
</details>

**Comment by gimantha** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35627
