### ISSUE TITLE
Lax access with check crashes when access is on a module-level json variable

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33102]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
json j = { 
   x: { 
      y: { 
         z: "value" 
      }
   }
};

public function main() returns error? {
   string s = check j.x.y.z;
}
```

```log
[2021-10-06 17:18:21,507] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.clone(NodeCloner.java:313)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.cloneBLangAccessExpression(NodeCloner.java:358)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.visit(NodeCloner.java:1126)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.clone(NodeCloner.java:311)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.cloneBLangAccessExpression(NodeCloner.java:358)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.visit(NodeCloner.java:1126)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.cloneNode(NodeCloner.java:274)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.getSuccessPattern(Desugar.java:9573)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.handleSafeNavigation(Desugar.java:9430)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteSafeNavigationExpr(Desugar.java:9325)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5964)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1393)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:100)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3429)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3430)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:100)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7849)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5964)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8202)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6391)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6335)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1393)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:100)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1519)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7849)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:7789)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7729)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8162)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1393)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8178)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8188)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1288)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1333)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8195)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:809)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8137)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:234)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:421)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:189)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

But the following works

```ballerina
public function main() returns error? {
    json j = {
        x: {
            y: {
                z: "value"
            }
        }
    };

    string s = check j.x.y.z;
}
```

**Affected Versions:**
slbeta3-rc5

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33635, merged to master in https://github.com/ballerina-platform/ballerina-lang/pull/33977.
