### ISSUE TITLE
No error shown when accessing optional record field of function type

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33107]
**Description:**
Consider following code:
```
type Club record {|
    string name;
    string country;
|};

type Player record {|
    string name;
    string nationality;
    Club club?;

    int age;

    int appearances?;
    int internationalCaps?;
    int goals?;
    (function () returns string) action?;
|};

public function main() {
    Player p = {
        nationality: "England",
        name: "Wayne Rooney",
        age: 29,
        club: {
            name: "Man Utd",
            country: "England"
        },
        appearances: 100,
        action: () => ""
    };
    
    int val = 100;
    float ab = 120.2;
    string str = "";
    string s = p.action();
}
```
In the last line, I invoke `p.action()` where `action` is an optional field of `function type`. No error is shown when this source is compiled.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 4 Snapshot

**Comment by MaryamZi** [comment]
```ballerina
type Player record {|
    (function () returns string) action?;
|};

public function main() {
    Player p = {};
    string _ = p.action();
}
```

crashes at runtime.

```cmd
[2022-03-02 20:59:55,349] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at test.main(test.bal:7)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KavinduZoysa** [comment]
This is a compile-time error in `Ballerina 2201.3.0`
