### ISSUE TITLE
'Cannot find the generated jar library for module' error when `bal build`

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#33476]
**Description:**
`testBuildAndRunPackageD` test in distribution CentralTest failing due to `Cannot find the generated jar library for module:` error.
I tested this locally with the latest master pack by setting up some packages.

```
pkgD ---> pkgC ---> pkgB, pkgA
```
`pkgA`,  `pkgB` and `pkgC` is in central.

If I run `bal build`, I get the following exception:
```
SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: pkgC
java.lang.IllegalStateException: Cannot find the generated jar library for module: pkgC
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$3(JBallerinaBackend.java:501)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:500)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:273)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:122)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:81)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:79)
	at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:507)
	at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:197)
	at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:97)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:413)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

But if I run `bal pack` or `bal build -c` it works w/o any issue.
Note: Tested with dev central instance.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Closing this since it is not reproducible now.

**Comment by spencerwi** [comment]
For what it's worth, I've seen a similar problem when trying out Swan Lake Beta4 -- the first time I've ever tried to use a third-party dependency from Ballerina Central (`samjs/jregex`), I saw this exact error both with `bal build` and `bal run`. Interestingly, `bal pack` worked fine, so I'm not sure what the deal is there.
