### ISSUE TITLE
Dataflow analysis doesn't run for the typedesc expression of an annotation access expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33495]
**Description:**
$title. 

**Steps to reproduce:**

```ballerina
annotation v1 on type;

public function main()  {
    typedesc<any> t;
    _ = t.@v1;
}
```

Crashes at runtime instead.

```
[2021-10-28 19:35:19,180] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.internal.TypeChecker.getAnnotValue(TypeChecker.java:578)
        at test.main(test.bal:5)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Affected Versions:**
slbeta3

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33527.
