### ISSUE TITLE
BIRGen crashes for complex binding pattern

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33530]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    [int, record { boolean e; string f; }, error<record { int h; string i?; }>, boolean...] [d, {e, ...f}, error(g, h = h, ...i), ...j] = 
        [1, {e: true, f: "str"}, error("error!", h = 1, i = "str"), true, false];
}
```

```
[2021-10-30 10:44:39,093] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:484)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1087)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:59)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:742)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:698)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:397)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:397)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:267)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:238)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:421)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:189)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

Most probably a desugaring issue. `foreach` is desugared to while, so we shouldn't have a `BLangForeach` at BIRGen.

**Affected Versions:**
slbeta3

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34502
