### ISSUE TITLE
Incomplete code sample causes `Node not supported` in `BLangNodeTransformer`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#33572]
**Description:**
The bellow code sample causes `Node not supported` in `BLangNodeTransformer`
```bal
public function main() {
    myType|[myType[]];
}
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
Error - 12:47:29 PM] Operation 'text/codeAction' failed! {uri: '/home/dulmina/Documents/test.bal', [4:1]- [7:2], error: 'Node not supported: TypedBindingPatternNode'}
java.lang.RuntimeException: Node not supported: TypedBindingPatternNode
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:3851)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transformSyntaxNode(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:576)
	at io.ballerina.compiler.syntax.tree.TypedBindingPatternNode.apply(TypedBindingPatternNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:998)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.TupleTypeDescriptorNode.apply(TupleTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:911)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.UnionTypeDescriptorNode.apply(UnionTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2806)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2773)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4961)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1544)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1451)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1431)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1409)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:608)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:507)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:387)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:349)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:201)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:274)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:285)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:253)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:238)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getMatchedTypeSymbol(CodeActionRouter.java:138)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:72)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:157)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:328)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

**Comment by rdulmina** [comment]
Related Issue #33260

**Comment by lochana-chathura** [comment]
Fixed in current master. I will add a test case.
```
Error Count: 3
Warning Count: 0
===================================
ERROR [test_parser.bal:(2:5,2:11)] unknown type 'myType'
ERROR [test_parser.bal:(2:13,2:19)] unknown type 'myType'
ERROR [test_parser.bal:(2:22,2:22)] missing identifier
===================================
```

**Comment by lochana-chathura** [comment]
Closing as attached PR was merged to staging branch.
