### ISSUE TITLE
Null as the TypeKind is captured

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33666]
**Description:**
Consider the following source snippet

```
function getIntVal() {
    worker w1 {
        int x = 12;
        x -> w2;
    }

    worker w2 {
        <-
    }
}
```

**Steps to reproduce:**
Within the worker `w2` we have an incomplete worker receive action where the diagnostic properties contains the type symbols. If we get the type kind of the type symbol we get a null. Instead we should have `NONE` or `CompilationError` type kind. This is resulting of NPEs when using the API.

In order to observe the behaviour, get the cursor to the particular erroneous location and you can see the following stack trace thrown from the code actions.

```
Error - 4:40:35 PM] CodeAction 'CreateVariableCodeAction' failed! {, error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at org.ballerinalang.langserver.common.utils.CommonUtil.generateVariableName(CommonUtil.java:780)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCreateVariableTextEdits(CreateVariableCodeAction.java:112)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getDiagBasedCodeActions(CreateVariableCodeAction.java:77)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:103)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:101)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:157)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:328)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
SwanLake-beta3 at least

**Comment by sanjana** [comment]
@nadeeshaan by applying the fix for the above NPE in the Semantic API side, would the following code segment that's being generated be considered appropriate? 
![create-var-codeaction](https://user-images.githubusercontent.com/9464997/143395835-30e20a01-6a2a-4e64-bd25-8e96ca39fcb1.gif)

**Comment by nadeeshaan** [comment]
> @nadeeshaan by applying the fix for the above NPE in the Semantic API side, would the following code segment that's being generated be considered appropriate? ![create-var-codeaction](https://user-images.githubusercontent.com/9464997/143395835-30e20a01-6a2a-4e64-bd25-8e96ca39fcb1.gif)

Basically, the `variable assignment required` diagnostic should not be suggested at the location first place. This is because we assume when the diagnostic available, the types are resolved. Otherwise we will have to include specific check for the types at the LS.

**Comment by sanjana** [comment]
Adding a diagnostic-based test case is Blocked by #34031
