### ISSUE TITLE
CCE when getting completions within mapping constructor

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33699]
**Description:**
Consider the following code:
```ballerina
type Data record {
    string id;
    int code;
};

function myFunc(int another) {
    int val = 1002 + another;
    Data d = {<cursor>};
}
```
At `<cursor>`. we don't get completions and a CCE is thrown.
```java
[Error - 12:21:06 PM] Operation 'text/completion' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/projects/pull_mod_test/main.bal', [8:15], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaParameterSymbol cannot be cast to class io.ballerina.compiler.api.symbols.VariableSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaParameterSymbol and io.ballerina.compiler.api.symbols.VariableSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaParameterSymbol cannot be cast to class io.ballerina.compiler.api.symbols.VariableSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaParameterSymbol and io.ballerina.compiler.api.symbols.VariableSymbol are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.lambda$getVariableCompletionsForFields$2(MappingConstructorExpressionNodeContext.java:195)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.getVariableCompletionsForFields(MappingConstructorExpressionNodeContext.java:194)
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.getCompletions(MappingConstructorExpressionNodeContext.java:109)
	at org.ballerinalang.langserver.completions.providers.context.MappingConstructorExpressionNodeContext.getCompletions(MappingConstructorExpressionNodeContext.java:63)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:124)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:80)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:63)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:38)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:116)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

Cause is `MappingConstructorExpressionNodeContext#getVariableCompletionsForFields()` not checking if the symbol is a `VariableSymbol`.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 4 RC1

**Comment by IMS94** [comment]
Closing this since #33710 was merged.
