### ISSUE TITLE
java.lang.NullPointerException on compilation

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#33768]
**Description:**
Following exception is thrown when building project [1].
```
[2021-11-11 16:24:48,536] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.addDependency(BIROptimizer.java:215)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.addDependency(BIROptimizer.java:208)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:120)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:401)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:268)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:416)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:293)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

ERROR [ballerina.update.tool:(1:1,1:1)] Compilation failed due to an unhandled exception
```

[1] https://github.com/anuruddhal/ballerina-registry/tree/migration/projects
**Steps to reproduce:**
1. Build and push the following project in the mentioned order and push to the local central
error_logger, email_api, semver, azure_appinsights, 

2. After building and pushing the above projects build the ballerina_update_tool_api which results the above error.

**Affected Versions:** 
Swan Lake Beta3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Merged the fix to the beta4 stage branch.  Need to patch beta3 with the fix

**Comment by pcnfernando** [comment]
Verified with @anuruddhal. They'll be moving to beta 4 instead. Hence, closing.
