### ISSUE TITLE
Code actions tests are failing intermittently

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#33784]
**Description:**
This occurs with c2c tests. https://github.com/ballerina-platform/module-ballerina-c2c
These tests are working fine when we execute them one by one but when we execute them subsequently, we get NPEs from SymbolEnter class from semantic analyzer. Also, we get different stack traces each time we execute the test.Probably due to caching issue.

Sample stacktrace:
```
    java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:943)
        at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:280)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$1(SymbolEnter.java:344)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:338)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:323)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:280)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:273)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:397)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:349)
        at io.ballerina.projects.ModuleCompilation.compile(ModuleCompilation.java:101)
        at io.ballerina.projects.ModuleCompilation.<init>(ModuleCompilation.java:63)
        at io.ballerina.projects.PackageContext.lambda$getModuleCompilation$5(PackageContext.java:209)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageContext.getModuleCompilation(PackageContext.java:208)
        at io.ballerina.projects.Module.getCompilation(Module.java:94)
        at io.ballerina.c2c.diagnostics.ProjectServiceInfo.<init>(ProjectServiceInfo.java:60)
        at io.ballerina.c2c.diagnostics.ProjectServiceInfo.<init>(ProjectServiceInfo.java:48)

```
Should be related to : ballerina-platform/ballerina-lang#33741

**Steps to reproduce:**
Comment out everything except these two in testing.xml and run the tests
```
            <class name="io.ballerina.c2c.test.codeactions.diagnostic.InvalidServicePath"/>
            <class name="io.ballerina.c2c.test.codeactions.diagnostic.InvalidResourcePath"/>
```
**Affected Versions:**
nightly
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment]
This is due to a caches not being updated with c2c scripts. Sorry for the false alarm.
