### ISSUE TITLE
decimal operations give incorrect results

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33805]
**Description:**
$subject

**Steps to reproduce:**
```
import ballerina/io;
public function main() {
    io:println(1e-6143 + 1e-6143); // 2e-6143
    io:println(-1e-6143 + 1e-6143); // 0
    io:println(9.999999999999999999999999999999998e6144 + 0.000000000000000000000000000000001e6144); //  9.999999999999999999999999999999999E+6144
    io:println(-9.999999999999999999999999999999998E6144 + -0.000000000000000000000000000000001E6144); //  -9.999999999999999999999999999999999E+6144
    io:println(-9.999999999999999999999999999999999E6144 + 0.000000000000000000000000000000001E6144); //  -9.999999999999999999999999999999998E+6144
    io:println(2E-6143 + 1E-6143); //  3E-6143
    io:println(9E-6143 + 1E-6143); //  1.0E-6142
}
```

The expected output is commented in the code, actual values are
```
0.0
0.0
Infinity
-Infinity
NaN
0.0
0.0
```

**Affected Versions:**
swan-lake beta4 rc1

**Comment by chiranSachintha** [comment]
@KavinduZoysa  This is fixed in the ` swan-lake beta4 rc2`. For the out of range float values, give a compile-time error. (https://github.com/ballerina-platform/ballerina-lang/issues/33318)
Output in ` swan-lake beta4 rc2`
```
ERROR [test3.bal:(3:16,3:23)] float '1e-6143' too small
ERROR [test3.bal:(3:26,3:33)] float '1e-6143' too small
ERROR [test3.bal:(4:16,4:24)] float '-1e-6143' too small
ERROR [test3.bal:(4:27,4:34)] float '1e-6143' too small
ERROR [test3.bal:(5:16,5:56)] float '9.999999999999999999999999999999998e6144' too large
ERROR [test3.bal:(5:58,5:98)] float '0.000000000000000000000000000000001e6144' too large
ERROR [test3.bal:(6:16,6:57)] float '-9.999999999999999999999999999999998E6144' too large
ERROR [test3.bal:(6:59,6:100)] float '-0.000000000000000000000000000000001E6144' too large
ERROR [test3.bal:(7:16,7:57)] float '-9.999999999999999999999999999999999E6144' too large
ERROR [test3.bal:(7:59,7:99)] float '0.000000000000000000000000000000001E6144' too large
ERROR [test3.bal:(8:16,8:23)] float '2E-6143' too small
ERROR [test3.bal:(8:25,8:32)] float '1E-6143' too small
ERROR [test3.bal:(9:16,9:23)] float '9E-6143' too small
ERROR [test3.bal:(9:25,9:32)] float '1E-6143' too small
```

**Comment by KavinduZoysa** [comment]
@chiranSachintha, We need to consider these literals as decimal not as floats

**Comment by KavinduZoysa** [comment]
@chiranSachintha, please consider this case too.
```
import ballerina/io;

public function main() {
    io:println(9.999999999999999999999999999999999E-6001d * 1E-143d); //output 0
}
```

**Comment by KavinduZoysa** [comment]
Please consider this case.
```
import ballerina/io;

public function main() {
    io:println(<int>-9223372036854775808d); // @output -9223372036854775807L - 1
}
```
But we are getting this error message,
```
error: {ballerina}NumberConversionError {"message":"'decimal' value '-9223372036854775808' cannot be converted to 'int'"}
	at test:main(test.bal:4)
```

**Comment by KavinduZoysa** [comment]
Please consider this example,

```
import ballerina/io;

public function main() {
    float f = 0.0000000000000009e+308;
    decimal d = <decimal>f;
    io:println(d); // @output 9E+292
}
```
actual output is : 8.999999999999999676143817781127689E+292
I think this is not a bug, we just want to check whether the result does not violate round-trip(i.e. the result float to dec conversion should equal to initial float).

**Comment by KavinduZoysa** [comment]
Please check these examples, they are giving wrong answers.

```
import ballerina/io;
public function main() {
    io:println(decimal:fromString("1e-6144")); // less than minimum magnitude, should be zero 
    io:println(decimal:fromString("9.999999999999999999999999999999999E6145")); // greater than max, shoulbe be an overflow error
    io:println(decimal:fromString("10E6145")); // greater than max, shoulbe be an overflow error
}
```

**Comment by KavinduZoysa** [comment]
```
import ballerina/io;

public function main() {
    io:println(1e6133d*1e30d); // this should be an error
}
```

**Comment by KavinduZoysa** [comment]
```
import ballerina/io;
public function main() {
    decimal d = 10e6144d; 
    io:println(d);
}
```

**Comment by KavinduZoysa** [comment]
```
import ballerina/io;

public function main() {
    io:println(<int>-9223372036854775808d);
}
```
Eor the above example, we are getting a runtime error. It is not correct.

**Comment by KavinduZoysa** [comment]
`decimal _ = <decimal>float:Infinity;` 
Above statement crashes the compiler with,

```
[2021-12-23 15:53:48,417] SEVERE {b7a.log.crash} - Infinite or NaN 
java.lang.NumberFormatException: Infinite or NaN
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:923)
	at io.ballerina.runtime.internal.values.DecimalValue.valueOf(DecimalValue.java:590)
	at test.main(test.bal:16)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KavinduZoysa** [comment]
```
import ballerina/io;
public function main() {
    io:println(<decimal>(1.0/0.0)); // should be panic arithmetic overflow
                                    // but getting `Infinity`
}
```

**Comment by KavinduZoysa** [comment]
```
import ballerina/io;
public function main() {
    io:println(<decimal>(0.0/0.0)); // should be panic invalid decimal
                                    // but getting `NaN`
}```

**Comment by gabilang** [comment]
The following cases has been already fixed 

- Decimal operations result in unsupported values (`NaN`, `+INFINITY`, `-INFINITY`). Now these cases panic with unsupported value error.
- Inconsistent behaviours in decimal to float conversion

The PR #38057 addresses the number overflow cases of decimal values which results by decimal operations and some issues with decimal to int conversion as mentioned here https://github.com/ballerina-platform/ballerina-lang/issues/33805#issuecomment-983258108
The decimal operations result in subnormals should be treated as zero.
