### ISSUE TITLE
Runtime crashes when `is-expr` is used with decimal numbers

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#33897]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

const decimal CD = 104;

public function main() {
    io:println(CD is 14.0d);
}
```
Error:
```
[2021-11-18 16:23:08,272] SEVERE {b7a.log.crash} - Character d is neither a decimal digit number, decimal point, nor "e" notation exponential mark. 
java.lang.NumberFormatException: Character d is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:852)
        at io.ballerina.runtime.internal.values.DecimalValue.<init>(DecimalValue.java:71)
        at test2.main(test2.bal:6)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HindujaB** [comment]
This issue is fixed in slbeta4 through #33472
