### ISSUE TITLE
`bal build` on the Simple Query BBE for the second time results in compilation failure

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#34081]
**Description:**
$subject with the following output:
```
Compiling source
	test.bal
error: failed to load the module 'ballerina/sql:1.1.0' from its BIR
```

**Steps to reproduce:**
1. Copy the [Simple Query BBE](https://ballerina.io/learn/by-example/jdbc-query-operation.html?is_ref_by_example=true) to a bal file and execute `bal build` command - builds successfully and generates the executable
2. Rerun `bal build` command - compilation failure

**Affected Versions:**
SL Beta.6-SNAPSHOT (51934f8fa305af61241470f7dd4a9de1fafeb60b)

**Comment by azinneera** [comment]
When debugged the following NPE was seen as the cause of the BIR load failure
```
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType.isNullable(BTypeReferenceType.java:64)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType.add(BUnionType.java:272)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1274)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1461)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1215)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.ignoreAttachedFunc(BIRPackageSymbolEnter.java:1567)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1487)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1159)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1274)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1461)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1274)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1221)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1014)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.ignoreAttachedFunc(BIRPackageSymbolEnter.java:1567)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1487)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:599)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineTypeDef(BIRPackageSymbolEnter.java:470)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:363)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:239)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:214)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:187)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:168)
	at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:516)
	at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:385)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:141)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:85)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:254)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

```

**Comment by MaryamZi** [comment]
Reproducible with the following source in the imported module.

```ballerina
public type Foo object {
    Bar b;    
};

public type Bar object {
    Baz b;
};

type Baz record {
    Foo|Bar c;
};
```
