### ISSUE TITLE
Compiler throws AssertionError when compiling valid code 

### ISSUE THREAD

**Issue by spencerwi** [ballerina-platform/ballerina-lang#34225]
**Description:**

When compiling [this valid code](https://github.com/spencerwi/AdventOfCode2021/blob/250e1b2c9c46ee45da01dbdbdf74c500a1d0bbda/day8/main.bal), the compiler crashes with the following error message:

```
Compiling source
        vscode/day8:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-12-08 15:28:16,578] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:630)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:65)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1675)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1179)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:741)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:697)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:396)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:396)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:266)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:416)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:191)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [day8:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

**Steps to reproduce:**

1. Launch a new Codespace from [this repo at this commit](https://github.com/spencerwi/AdventOfCode2021/tree/250e1b2c9c46ee45da01dbdbdf74c500a1d0bbda/) (there's already devcontainer configuration in the repo)
2. In that codespace, run `cd day8 && bal run`
3. Observe the error message presented above.

**Affected Versions:**
Swan Lake Beta 4 (possibly also Swan Lake Beta 5; there's no Beta 5 devcontainer image available yet though)

**OS, DB, other environment details and versions:**
Using the Swan Lake Beta 4 devcontainer docker image.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
@prakanth97 can you backport the fix to the relavant branches
