### ISSUE TITLE
LS getting stopped when incompatible version is provided in Dependencies.toml

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34221]
**Description:**
$title

**Steps to reproduce:**
1. Use nBallerina project
2. Change the following information in `Dependencies.toml` file.
```toml
[[package]]
org = "ballerina"
name = "os"
version = "0.9.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]
```
3. See the ballerina output in VScode

<details>
  <summary>Ballerina VSCode Output</summary>

```
[Error - 5:29:29 PM] Operation 'text/didChange' failed! {uri: '/home/dulaj/Work/nballerina/compiler/Dependencies.toml', error: 'Incompatible versions: ballerina/os. Version specified in Dependencies.toml: 0.0.0 and the version resolved from other dependencies: 1.0.0'}
io.ballerina.projects.ProjectException: Incompatible versions: ballerina/os. Version specified in Dependencies.toml: 0.0.0 and the version resolved from other dependencies: 1.0.0
	at io.ballerina.projects.internal.ResolutionEngine.getRequestForUnresolvedNode(ResolutionEngine.java:302)
	at io.ballerina.projects.internal.ResolutionEngine.updateDependencyVersions(ResolutionEngine.java:250)
	at io.ballerina.projects.internal.ResolutionEngine.resolveDependencies(ResolutionEngine.java:86)
	at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:270)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:212)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:92)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:99)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:242)
	at io.ballerina.projects.Package.getResolution(Package.java:149)
	at io.ballerina.projects.Package$Modifier.<init>(Package.java:310)
	at io.ballerina.projects.Package.modify(Package.java:265)
	at io.ballerina.projects.DependenciesToml$Modifier.apply(DependenciesToml.java:101)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.updateDependenciesToml(BallerinaWorkspaceManager.java:859)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didChange(BallerinaWorkspaceManager.java:335)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManagerProxyImpl.didChange(BallerinaWorkspaceManagerProxyImpl.java:85)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65
```
</details>

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment]
This exception is thrown when there are two different  versions of the same package in use. (Say by the current package and a std library). The subsequent requests results in this error as long as the incompatible dependency version is there. A TODO to has been added to add a diagnostic instead of throwing an exception. 


https://github.com/ballerina-platform/ballerina-lang/blob/45f8dafdf72deaf92641b362bb7adc4b660fdd15/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java#L295-L302

**Comment by malinthar** [comment]
Ideally, user should not be able to edit the Dependencies.toml file which causes this issue with a minor/major version not which is not allowed by the dependency resolution mechanism. There are couple of solutions to tackle this.

1. Make the Dependencies.toml readonly
2. Gracefully skip/ignore the didChange event of Dependencies.toml file
