### ISSUE TITLE
no such field error for $type$StringDefn when running `bal run` and `bal test`

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#34241]
**Description:**
Getting the following errors for nballerina compiler with `stage-slbeta6` branch (e574b22960e4e356892649b9d62dd6cdd818a874).

`bal test`
```   
	nballerina.nback
error: $type$StringDefn
```

`bal run`
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-12-09 14:36:32,128] SEVERE {b7a.log.crash} - $type$StringDefn 
java.lang.NoSuchFieldError: $type$StringDefn
	at wso2.nballerina$0046print$0046llvm.0.constants.$_tuple_type_constants.$populate$tupleType8(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_tuple_type_constants.$tuple_type_init1(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_tuple_type_constants.<clinit>(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_bunion_type_constants.createMembers$$unionType40(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_bunion_type_constants.$populate$unionType4(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_bunion_type_constants.$union_type_init1(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.constants.$_bunion_type_constants.<clinit>(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.types.$_types.createMembers$original$type$BinaryOp0(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.types.$_union_types.$populate$type$BinaryOp(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.types.$_types.$createTypes(Unknown Source)
	at wso2.nballerina$0046print$0046llvm.0.$_init.$currentModuleInit(nballerina.print.llvm)
	at wso2.nballerina$0046print$0046llvm.0.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
	at wso2.nballerina.0.$configurationMapper.$configureInit(Unknown Source)
	at wso2.nballerina.0.$_init.main(nballerina)
```

**Comment by MaryamZi** [comment]
Reproducible with

em/foo

```ballerina
public readonly class ConstPointerValue {
}
```

Used in

```ballerina
import em/foo;

type StringDefn foo:ConstPointerValue;

type Module record {|
    map<StringDefn> stringDefns = {};
|};
```

```log
[2021-12-09 16:16:15,385] SEVERE {b7a.log.crash} - $type$StringDefn 
java.lang.NoSuchFieldError: $type$StringDefn
        at em.foo.0.types.$_object_types.$populate$type$ConstPointerValue(Unknown Source)
        at em.foo.0.types.$_types.$createTypes(Unknown Source)
        at em.foo.0.$_init.$currentModuleInit(foo)
        at em.foo.0.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at em.bar.0.$configurationMapper.$configureInit(Unknown Source)
        at em.bar.0.$_init.main(bar)
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34246.
