### ISSUE TITLE
Compiler FE crashes when a `let var f =  from/select` clause is used inside a `from/select` expression

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#34332]
**Steps to reproduce:**
The issue can be reproduce by running the following code sample
```ballerina
type Label record {
    string name;
};

type PR record {
    string url;
    string title;
    string state;
    string created_at;
    string updated_at;
    string? merged_at;
    Label[] labels;
};

public function main() returns error? {
    PR[] prs = [
        {
            "url": "https://api.github.com/repos/ballerina-platform/ballerina-lang/pulls/34133",
            "title": "Add missing completions inside ternary conditional expression",
            "state": "closed",
            "created_at": "2021-12-06T04:21:47Z",
            "updated_at": "2021-12-13T11:02:18Z",
            "merged_at": "2021-12-13T11:02:17Z",
            "closed_at": "2021-12-13T11:02:18Z",
            "labels": [
                {
                    "name": "Team/LanguageServer",
                    "default": false,
                    "color": "ead279",
                    "description": "Language Server Implementation related issues. #Compiler",
                    "id": 828273958,
                    "url": "https://api.github.com/repos/ballerina-platform/ballerina-lang/labels/Team/LanguageServer",
                    "node_id": "MDU6TGFiZWw4MjgyNzM5NTg="
                }
            ]
        },
        {
            "url": "https://api.github.com/repos/ballerina-platform/ballerina-lang/pulls/34123",
            "title": "Fix issue in tracking field references in index-based access exprs",
            "state": "closed",
            "created_at": "2021-12-03T16:46:53Z",
            "updated_at": "2021-12-13T06:14:33Z",
            "merged_at": "2021-12-13T05:40:57Z",
            "closed_at": "2021-12-13T05:40:57Z",
            "labels": [
                {
                    "name": "Team/CompilerFETools",
                    "default": false,
                    "color": "ead279",
                    "description": "Semantic API, Formatter, Shell",
                    "id": 1341668468,
                    "url": "https://api.github.com/repos/ballerina-platform/ballerina-lang/labels/Team/CompilerFETools",
                    "node_id": "MDU6TGFiZWwxMzQxNjY4NDY4"
                },
                {
                    "name": "Area/SemanticAPI",
                    "default": false,
                    "color": "186872",
                    "description": "Semantic API Related Issues #Compiler",
                    "id": 2286594184,
                    "url": "https://api.github.com/repos/ballerina-platform/ballerina-lang/labels/Area/SemanticAPI",
                    "node_id": "MDU6TGFiZWwyMjg2NTk0MTg0"
                }
            ]
        }
    ];

    PR[] projectedPRs = from var {url, title, state, created_at, updated_at, merged_at, labels} in prs
        let var projectedLabels = from var {name} in labels
            select {name} // JBUG
        select {url, title, state, created_at, updated_at, merged_at, labels: projectedLabels};

    io:println(projectedPRs);
}
```

**Affected Versions:**
Swan Lake Beta6

**Comment by sameerajayasoma** [comment]
I have a workaround for now
```ballerina
function projectLabels(Label[] labels) returns Label[] {
    return from var {name} in labels
        select {name};
}

```

```ballerina

    PR[] projectedPRs = from var {url, title, state, created_at, updated_at, merged_at, labels} in prs
        let var projectedLabels = projectLabels(labels)
        select {url, title, state, created_at, updated_at, merged_at, labels: projectedLabels};
```

**Comment by lochana-chathura** [comment]
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2021-12-15 11:27:42,748] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.createFunctionInfoArray(MainMethodGen.java:336)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.loadCLIArgsForMain(MainMethodGen.java:296)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateUserMainFunctionCall(MainMethodGen.java:271)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateMainMethod(MainMethodGen.java:165)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:426)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1039)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:395)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:802)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:89)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:68)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:430)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:191)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>
