### ISSUE TITLE
NPE when hovering resource path

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34367]
**Description:**
Consider the bellow sample

```bal
service on listenerName {
    resource function get person/name() {
    }
}
```
give NPE when hovering `name`.

```
java.lang.NullPointerException
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:95)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by nadeeshaan** [comment]
This issue has been fixed with https://github.com/ballerina-platform/ballerina-lang/commit/0cdfc72420b72002f405f828c13b442cb58d2cd2.

Hence closing the issue
