### ISSUE TITLE
Having a client action invocation inside query do clause causes a runtime error

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34384]
Consider the following code.

```ballerina
import ballerina/io;
import ballerina/http;

http:Client handlerClient = check new("google.com");
public client class ClientWithHandlers {
    int port;
    public function init(int port) {
        self.port = port;
    }

    remote function get(string str) returns @tainted byte[]|error {
        return [12];
    }
}

public function xxx() returns byte[]|error? {
   // ClientWithHandlers handlerClient = new (9091);
    byte[] result = [];
    check from var _ in [1, 2]
        do {
            byte[]|error bytes = [];
            bytes = handlerClient->get("/");
            if bytes is error {
                io:println("error");
              return;
            }
            result = bytes;
        };
    return result;
}

public function main() returns error? {
    io:println(check xxx());
}
```

Running the above code gives this error.

```
SEVERE {b7a.log.crash} - class ballerina.lang$0046query.0.$annon$method$delegate$0Frame cannot be cast to class ballerina.io.1.printlnFrame (ballerina.lang$0046query.0.$annon$method$delegate$0Frame and ballerina.io.1.printlnFrame are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.lang$0046query.0.$annon$method$delegate$0Frame cannot be cast to class ballerina.io.1.printlnFrame (ballerina.lang$0046query.0.$annon$method$delegate$0Frame and ballerina.io.1.printlnFrame are in unnamed module of loader 'app')
        at ballerina.io.1.print.println(print.bal:66)
        at gimantha.myProj.0.ddd.main(ddd.bal:33)
        at gimantha.myProj.0.$_init.$lambda$main$(myProj)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

If I comment the http client and use the custom client, then the error goes away.

**Comment by gimantha** [comment]
Can be related to https://github.com/ballerina-platform/ballerina-lang/issues/34353
