### ISSUE TITLE
Bug in array.unshift

### ISSUE THREAD

**Issue by rpkamp** [ballerina-platform/ballerina-lang#34394]
**Description:**

**Steps to reproduce:**

1. Create this script
```
public function main() {
    int[] list = [];
    foreach int i in 0 ..< 200 {
        list.unshift(i);
    }
}
```

2. Run it
3. Scripts crashes with
```
[2021-12-17 14:09:45,293] SEVERE {b7a.log.crash} - arraycopy: last destination index 101 out of bounds for long[100]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 101 out of bounds for long[100]
        at java.base/java.lang.System.arraycopy(Native Method)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshiftArray(ArrayValueImpl.java:1218)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshift(ArrayValueImpl.java:1131)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshift(ArrayValueImpl.java:619)
        at org.ballerinalang.langlib.array.Unshift.unshift(Unshift.java:34)
        at ballerina.lang$0046array.0.array.unshift(array.bal:272)
        at app.main(app.bal:5)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at io.ballerina.runtime.internal.scheduling.Scheduler.start(Scheduler.java:278)
        at $_init.main(.)
```

Sound like array has a fixed size and isn't doubled as soon as it hits the limit.

**Affected Versions:**
At least Swan Lake beta 6

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by hasithaa** [comment]
@rpkamp Thank you for reporting this. @warunalakshitha, shall we prioritize this?

**Comment by warunalakshitha** [comment]
We will check this.
