### ISSUE TITLE
NPE from desugar

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#34404]
Following results NPE. 

```
public function main() {
   map<int>? m = {};
   m["x"] += 1;
}
```

```
 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6351)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangErrorConstructorExpr.accept(BLangErrorConstructorExpr.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8330)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3319)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangPanic.accept(BLangPanic.java:49)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8349)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1511)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3420)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8349)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1511)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2421)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8349)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1511)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3408)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangCompoundAssignment.accept(BLangCompoundAssignment.java:86)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8349)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1286)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1328)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:75)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8356)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:805)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8305)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:450)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:452)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by hasithaa** [comment]
Observed this, while checking this, https://github.com/ballerina-platform/ballerina-spec/issues/191#issuecomment-997159247
