### ISSUE TITLE
Compiling http_listener_method_service_test.bal in HTTP module give BIR error

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34418]
Refer to this file : https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina-tests/tests/http_listener_method_service_test.bal

As you can see, The outer service object creates new service objects here. Outer and inner service objects all have `http:Caller `called `caller` in their resource methods. Somehow, Compiler thinks that there is one `caller` variable and consider the other variable references as closures in other places.  Renaming the below `caller` references to something else will solve this issue, but the issue needs to be fixed properly.
![image](https://user-images.githubusercontent.com/9362271/146786962-5a8293f4-ede4-4edc-9346-546691bee3fa.png)

Below is the error without the workaround.
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$2(BIROptimizer.java:108)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:108)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRTypeDefinition.accept(BIRNode.java:516)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$0(BIROptimizer.java:102)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:102)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$genBIR$0(BIRGen.java:286)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:277)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by hasithaa** [comment]
This should be a compile-time error, because, the `caller` is shadowing a in-scope variable.

**Comment by hasithaa** [comment]
According to the https://ballerina.io/spec/lang/master/#section_5.9.3, it is an error. See the last paragraph.

**Comment by KRVPerera** [comment]
@chiranSachintha  pointed out a related discussion which happened here.
https://github.com/ballerina-platform/ballerina-spec/issues/873

Also I would like to quote this fragment from the spec which explains default values can refer previous parameters.

> A defaultable-param is a parameter for which a default value is specified. An expression can be used to specify the default value; this expression may refer to previous parameters. Each such expression is turned into a closure that computes the default value for the parameter using the values of previous parameters, and this closure is part of the type descriptor for the function.

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34445
