### ISSUE TITLE
java.util.ConcurrentModificationException during building a program

### ISSUE THREAD

**Issue by juriad** [ballerina-platform/ballerina-lang#34415]
**Description:**

I am using a different language every day to solve Advent of Code. I don't have time to figure out all detail of every language, but it is enough for a feel of it. Today I used Ballerina.
During simplification of my code, I encountered the ConcurrentModificationException; full output is:
```
Compiling source
	Prg.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-12-20 13:02:37,704] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:750)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:558)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.constants.JvmArrayTypeConstantsGen.add(JvmArrayTypeConstantsGen.java:108)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmConstantsGen.getTypeConstantsVar(JvmConstantsGen.java:108)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:414)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateArrayNewIns(JvmInstructionGen.java:1472)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2055)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:549)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:475)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:235)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:161)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.createObjectMethods(JvmValueGen.java:618)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.createObjectValueClass(JvmValueGen.java:578)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.lambda$generateValueClasses$0(JvmValueGen.java:219)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.generateValueClasses(JvmValueGen.java:213)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:804)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:95)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:466)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1219)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

I could not find any issue with `JvmArrayTypeConstantsGen`, so here you go.
Since I have no idea what is going on, I could not come up with a better name for the issue.

**Steps to reproduce:**

The source code is available on Github: https://github.com/juriad/advent2021/tree/master/day-20
To trigger the bug just uncomment the following lines: https://github.com/juriad/advent2021/blob/master/day-20/Prg.bal#L46
If you need any more info, I will do my best to provide it.

**Affected Versions:**

A fresh download from the website (zip):
```
ballerina-swan-lake-beta6/bin/bal -v
Ballerina Swan Lake Beta 6
Language specification 2021R1
Update Tool 1.3.6
```
```
uname -a
Linux *** 5.15.2-arch1-1 #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux
```
```
java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

**Comment by Nadeeshan96** [comment]
This issue does not occur with `Ballerina 2201.0.1 (Swan Lake)` version. It had been solved, hence closing the issue.
