### ISSUE TITLE
No completion support for xml-atribute-access expression

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34433]
**Description:**
Consider the following capture

![xml](https://user-images.githubusercontent.com/35211477/146899452-22ebdd51-4eaf-4d78-b4d8-5cbc328ee44b.png)

Following st can be observed in the log stream
```
[Error - 2:15:18 pm] Operation 'text/completion' failed! {uri: '/home/malintha/Documents/wso2/experimental/projects/ballerina/test-hackathon/project1/main.bal', [91:37], error: 'class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType (org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType and org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType (org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType and org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.LangLibrary.getTypeParamBoundType(LangLibrary.java:216)
	at io.ballerina.compiler.api.impl.LangLibrary.getMethods(LangLibrary.java:111)
	at io.ballerina.compiler.api.impl.LangLibrary.getMethods(LangLibrary.java:104)
	at io.ballerina.compiler.api.impl.symbols.AbstractTypeSymbol.langLibMethods(AbstractTypeSymbol.java:93)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.langLibMethods(BallerinaTypeReferenceTypeSymbol.java:82)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getVisibleEntries(FieldAccessCompletionResolver.java:321)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.lambda$getVisibleEntries$6(FieldAccessCompletionResolver.java:256)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getVisibleEntries(FieldAccessCompletionResolver.java:256)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getEntries(FieldAccessContext.java:78)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:44)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:33)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:136)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:82)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```
**Steps to reproduce:**
```ballerina
public function test() {

    xml:Element expr = xml `<hello>Hello</hello>`;
    string|error unionResult = expr.<cursor>;

}
```
**Affected Versions:**
slbeta6

**Comment by malinthar** [comment]
This is no longer reproducible
