### ISSUE TITLE
"ballerina: Oh no, something really went wrong. Bad. Sad." error when using connectors / modules

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#34439]
**Description:**

Ballerina Swan Lake Beta 6
Language specification 2021R1
Update Tool 1.3.6

1. Create a program having a connector (e.g github), but have a compilation error in the code (may be wrong return type)
2. when compiling, the connector will be downloaded (if you already had from previous use, please remove from local repo). However, the compilation will fail
3. Now fix the compilation error in the program
4. build now
5. You will get bellow error
6. Only way to fix is to remove the connector from local repo (.ballerina/repository/...) and build again

```
Generating executable
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-12-22 10:28:39,380] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: github.webhook 
java.lang.IllegalStateException: Cannot find the generated jar library for module: github.webhook
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$3(JBallerinaBackend.java:502)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:501)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:274)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:122)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:81)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:79)
	at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:508)
	at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:198)
	at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:97)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Closing since this is fixed with #34849
