### ISSUE TITLE
CCE in BXMLType 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34482]
**Description:**
Consider the following source
```ballerina
function testFiedAccess() {
    xml:Element expr = xml `<hello>Hello</hello>`;
    string|error unionResult = expr.<cursor>;
}
```

The following CCE is produced when I tried to get field access completions at the depicted cursor position.

```
[Error - 11:27:20 pm] Operation 'text/completion' failed! {uri: '/home/malintha/Documents/wso2/experimental/projects/ballerina/test-hackathon/project1/main.bal', [94:37], error: 'class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType (org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType and org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType (org.wso2.ballerinalang.compiler.semantics.model.types.BXMLSubType and org.wso2.ballerinalang.compiler.semantics.model.types.BXMLType are in unnamed module of loader 'app')
	at io.ballerina.compiler.api.impl.LangLibrary.getTypeParamBoundType(LangLibrary.java:216)
	at io.ballerina.compiler.api.impl.LangLibrary.getMethods(LangLibrary.java:111)
	at io.ballerina.compiler.api.impl.LangLibrary.getMethods(LangLibrary.java:104)
	at io.ballerina.compiler.api.impl.symbols.AbstractTypeSymbol.langLibMethods(AbstractTypeSymbol.java:93)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.langLibMethods(BallerinaTypeReferenceTypeSymbol.java:83)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getVisibleEntries(FieldAccessCompletionResolver.java:321)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.lambda$getVisibleEntries$6(FieldAccessCompletionResolver.java:256)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getVisibleEntries(FieldAccessCompletionResolver.java:256)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getEntries(FieldAccessContext.java:78)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:44)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:33)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:136)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:82)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
mentioned above

**Affected Versions:**
sl-2201.0.0-snapshot

**Comment by pubudu91** [comment]
Closing since this is fixed in #34645
