### ISSUE TITLE
Using a Reference type for map<int>? fails with CCE

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34552]
Consider the following code

```ballerina
type FOO map<int>?;
public function main() {
    FOO x = {"w": 33};
    var s = x["w"];
}
```

Compiling the above code throws the following CCE.

```java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.handleSafeNavigation(Desugar.java:9593)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteSafeNavigationExpr(Desugar.java:9533)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6287)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangIndexBasedAccess.accept(BLangIndexBasedAccess.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8368)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8381)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8387)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8394)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:795)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
```

**Comment by pcnfernando** [comment]
Fixed with #34429
