### ISSUE TITLE
Passthrough server hangs intermittently when IO exception occurs while writing outbound request.

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#34685]
**Description:**
$subject has been observed in microgateway 3.2.0 which is basically a passthrough service in ballerina context. In there, there is an additional http client running, to publish metrics to the analytics server. 

In the thread dump, we could observe that the httpcarbon message's lock has been acquired by this client. And it remains in this state without releasing. 

```
"jbal-strand-exec-97" #461 prio=5 os_prio=0 tid=0x00007f411434f000 nid=0x1f8 waiting on condition [0x00007f403b5f3000]
   java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000007491c38a0> (a java.util.concurrent.Semaphore$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
at org.wso2.transport.http.netty.message.DefaultBackPressureListener.onUnWritable(DefaultBackPressureListener.java:48)
at org.wso2.transport.http.netty.message.DefaultBackPressureObservable.notifyUnWritable(DefaultBackPressureObservable.java:44)
at org.wso2.transport.http.netty.contractimpl.common.Util.checkUnWritabilityAndNotify(Util.java:962)
at org.wso2.transport.http.netty.contractimpl.sender.channel.TargetChannel.lambda$writeContent$1(TargetChannel.java:99)
at org.wso2.transport.http.netty.contractimpl.sender.channel.TargetChannel$$Lambda$106/1391198339.onMessage(Unknown Source)
at org.wso2.transport.http.netty.message.MessageFuture.notifyMessageListener(MessageFuture.java:61)
at org.wso2.transport.http.netty.message.HttpCarbonMessage.addHttpContent(HttpCarbonMessage.java:114)
- locked <0x0000000749395400> (a org.wso2.transport.http.netty.message.HttpCarbonMessage)
at org.wso2.transport.http.netty.message.HttpMessageDataStreamer$ByteBufferOutputStream.close(HttpMessageDataStreamer.java:165)
at org.ballerinalang.net.http.HttpUtil.closeMessageOutputStream(HttpUtil.java:326)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.serializeMultipartDataSource(AbstractHTTPAction.java:407)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.serializeMultiparts(AbstractHTTPAction.java:390)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.send(AbstractHTTPAction.java:348)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.sendOutboundRequest(AbstractHTTPAction.java:289)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.executeNonBlockingAction(AbstractHTTPAction.java:246)
at org.ballerinalang.net.http.actions.httpclient.HttpClientAction.executeClientAction(HttpClientAction.java:55)
at ballerina.http.http_client.externExecuteClientAction(http_client.bal:235)
at ballerina.http.$value$HttpClient.post(http_client.bal:48)
at ballerina.http.$value$HttpClient.call(http_client.bal)
at ballerina.http.$value$Client.post(client_endpoint.bal:72)
at ballerina.http.$value$Client.call(client_endpoint.bal)
at wso2.gateway.src.gateway.analytics.usagedata_uploader.multipartSender(/src/gateway/analytics/usagedata_uploader.bal:36)
at wso2.gateway.src.gateway.analytics.upload_files_timer.searchFilesToUpload(/src/gateway/analytics/upload_files_timer.bal:47)
at wso2.gateway.$value$_anonService_2__service_3.onTrigger(/src/gateway/analytics/upload_files_timer.bal:111)
at wso2.gateway.$value$_anonService_2__service_3.call(/src/gateway/analytics/upload_files_timer.bal)
at org.ballerinalang.jvm.BRuntime.lambda$invokeMethodAsync$0(BRuntime.java:65)
at org.ballerinalang.jvm.BRuntime$$Lambda$140/858645824.apply(Unknown Source)
at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
at org.ballerinalang.jvm.scheduling.Scheduler$$Lambda$7/1146848448.run(Unknown Source)
at java.lang.Thread.run(Thread.java:748)
```

And the netty thread is trying to set the IO exception, but as the lock is already acquired by the previous thread, it cannot proceed. 

```
"nioEventLoopGroup-3-3" #470 prio=10 os_prio=0 tid=0x00007f4014005800 nid=0x209 waiting for monitor entry [0x00007f3ff51b7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
at org.wso2.transport.http.netty.message.HttpCarbonMessage.setIoException(HttpCarbonMessage.java:463)
- waiting to lock <0x0000000749395400> (a org.wso2.transport.http.netty.message.HttpCarbonMessage)
at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction$HTTPClientConnectorListener.onError(AbstractHTTPAction.java:451)
at org.wso2.transport.http.netty.contractimpl.DefaultHttpResponseFuture.notifyHttpListener(DefaultHttpResponseFuture.java:129)
at org.wso2.transport.http.netty.contractimpl.common.states.StateUtil.lambda$notifyIfHeaderWriteFailure$0(StateUtil.java:82)
at org.wso2.transport.http.netty.contractimpl.common.states.StateUtil$$Lambda$114/789260318.operationComplete(Unknown Source)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57)
at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:835)
at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797)
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:778)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812)
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036)
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293)
at org.wso2.transport.http.netty.contractimpl.sender.states.SendingEntityBody.writeOutboundRequestEntity(SendingEntityBody.java:82)
at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.writeOutboundRequestEntity(SenderReqRespStateManager.java:50)
at org.wso2.transport.http.netty.contractimpl.sender.states.SendingHeaders.writeRequestBody(SendingHeaders.java:163)
at org.wso2.transport.http.netty.contractimpl.sender.states.SendingHeaders.writeOutboundRequestEntity(SendingHeaders.java:122)
at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.writeOutboundRequestEntity(SenderReqRespStateManager.java:50)
at org.wso2.transport.http.netty.contractimpl.sender.channel.TargetChannel.lambda$null$0(TargetChannel.java:102)
at org.wso2.transport.http.netty.contractimpl.sender.channel.TargetChannel$$Lambda$108/2037796737.run(Unknown Source)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

Hard to reproduce. 

**Affected Versions:**

ballerina 1.2.22

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
Fixed via https://github.com/wso2/transport-http/pull/434, https://github.com/wso2/transport-http/pull/435 and https://github.com/ballerina-platform/ballerina-lang/pull/34727. Hence closing the issue
