### ISSUE TITLE
Crashing throwing an ArrayIndexOutOfBoundsException when using `foreach` on `table`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34693]
**Description:**
Runtime crashes throwing an `ArrayIndexOutOfBoundsException`  when using `foreach` on `table`. Also this doesn't show a `Bad. Sad. error message`

**Steps to reproduce:**
Run this source Code with `bal run` command
```ballerina
import ballerina/io;

type AA record {
    string a;
};

public function main() {
    table<AA> tbl = table [{a: "a1"}, {a: "a2"}];
    tbl.forEach(function (AA a) {
        io:println(a);
    });
}
```

Stack trace:
```
Compiling source
	types.bal

Running executable

[2022-01-18 11:48:46,833] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.ballerinalang.langlib.table.Foreach.lambda$forEach$0(Foreach.java:57)
	at io.ballerina.runtime.internal.scheduling.AsyncUtils.scheduleNextFunction(AsyncUtils.java:157)
	at io.ballerina.runtime.internal.scheduling.AsyncUtils.invokeFunctionPointerAsyncIteratively(AsyncUtils.java:131)
	at org.ballerinalang.langlib.table.Foreach.forEach(Foreach.java:55)
	at ballerina.lang$0046table.0.table.forEach(table.bal:128)
	at types.main(types.bal:9)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:829)
 
[2022-01-18 11:48:46,855] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.ballerinalang.langlib.table.Foreach.lambda$forEach$0(Foreach.java:57)
	at io.ballerina.runtime.internal.scheduling.AsyncUtils.scheduleNextFunction(AsyncUtils.java:157)
	at io.ballerina.runtime.internal.scheduling.AsyncUtils.invokeFunctionPointerAsyncIteratively(AsyncUtils.java:131)
	at org.ballerinalang.langlib.table.Foreach.forEach(Foreach.java:55)
	at ballerina.lang$0046table.0.table.forEach(table.bal:128)
	at types.main(types.bal:9)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) Snapshot build 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Bad. Sad. message is not given https://github.com/ballerina-platform/ballerina-lang/issues/32708

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
Tested with Swan Lake GA RC1. It's working
