### ISSUE TITLE
IllegalArgumentException when hover is expr inside if condition context

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34708]
**Description:**
Below sample causes `IllegalArgumentException` when I hover result var ref in RHS of the logical expression.

```bal
function testUnreachabilityWithIfStmtWithUnaryNot() {
    1|2 result = 2;

    if result is 1 || result is 2 {
    }
}
```

<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[Error - 2:54:14 PM] Operation 'text/hover' failed! {uri: '/home/dulmina/Documents/test2.bal', [4:23], error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:129)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:104)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:122)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:157)
	at org.ballerinalang.langserver.hover.HoverUtil.getVariableHoverMarkupContent(HoverUtil.java:422)
	at org.ballerinalang.langserver.hover.HoverUtil.getHoverForSymbol(HoverUtil.java:127)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:103)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

**Comment by nadeeshaan** [comment]
If we consider this particular scenario, we have tried to hover over the second `result` reference within the `is` expression. When we look at the second occurrence the symbol extracted from the particular scope entry is `null`. This is not only limited for this scenario, but also, this has reflected for any type check added after the first condition.

**Comment by gimantha** [comment]
> If we consider this particular scenario, we have tried to hover over the second `result` reference within the `is` expression. When we look at the second occurrence the symbol extracted from the particular scope entry is `null`. This is not only limited for this scenario, but also, this has reflected for any type check added after the first condition.
> 
> @pubudu91 @gimantha please share your thoughts as well

These two result vars are in the same scope and should have the same symbol. Is this in stage-swan-lake branch?

**Comment by rdulmina** [comment]
> > If we consider this particular scenario, we have tried to hover over the second `result` reference within the `is` expression. When we look at the second occurrence the symbol extracted from the particular scope entry is `null`. This is not only limited for this scenario, but also, this has reflected for any type check added after the first condition.
> > @pubudu91 @gimantha please share your thoughts as well
> 
> These two result vars are in the same scope and should have the same symbol. Is this in stage-swan-lake branch?

Yes

**Comment by lasinicl** [comment]
This might be related to how the types are being narrowed for finite types. Observed the following behavior with `Ballerina 2201.0.0 (Swan Lake) RC1`

https://user-images.githubusercontent.com/19838787/150280450-86b0c892-e8cb-42dd-9695-24eb4e472a72.mp4

**Comment by lochana-chathura** [comment]
Got the same exception **without hovering**. Just for else block completion.

```bal
function test26(1|+2|-3 n) {
    if n is 2 {
        return;
    } e<cursor>
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[Error - 10:46:43 AM] Operation 'text/completion' failed! {uri: '/home/lochanaj/BLearn/test.bal', [4:15], error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:129)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:104)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:122)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:157)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getModifiedTypeName(CommonUtil.java:1357)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:210)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:174)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getSymbolCompletions(BlockNodeContextProvider.java:206)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getCompletions(BlockNodeContextProvider.java:92)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:45)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:36)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:136)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:82)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/39232462/151107835-a2d27d13-c09c-4bc8-ad97-82dfba21ed67.gif)

**Comment by rdulmina** [comment]
Another sample reproduce the same error

```bal
function test() returns string {
    1|2 result = 2;

    if result == 1 {
        return "foo";
    } else {
        r<cursor>
        return "bar";
    }
}
```

@nadeeshaan @pubudu91 @gimantha will this be a blocker for GA?

**Comment by nadeeshaan** [comment]
> Another sample reproduce the same error
> 
> ```ballerina
> function test() returns string {
>     1|2 result = 2;
> 
>     if result == 1 {
>         return "foo";
>     } else {
>         r<cursor>
>     }
> }
> ```
> 
> @nadeeshaan @pubudu91 @gimantha will this be a blocker for GA?

@rdulmina this is sort of breaking the auto-completions for language server within the given context. IMO it would be better if we can have a fix for this. Let's get some other input as well, before deciding this is a blocker

**Comment by gimantha** [comment]
> > Another sample reproduce the same error
> > ```ballerina
> > function test() returns string {
> >     1|2 result = 2;
> > 
> >     if result == 1 {
> >         return "foo";
> >     } else {
> >         r<cursor>
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @nadeeshaan @pubudu91 @gimantha will this be a blocker for GA?
> 
> @rdulmina this is sort of breaking the auto-completions for language server within the given context. IMO it would be better if we can have a fix for this. Let's get some other input as well, before deciding this is a blocker

Lets target this one for the update

**Comment by pubudu91** [comment]
Sorry, missed this. Had a quick look. It's incorrectly identifying the singleton type `2` as a type ref.
