### ISSUE TITLE
Using the table type descriptor snippet completion item throws NPE

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34732]
**Description:**
When I select the following completion item `type TypeName table<>`, it throws the NPE below.

<img width="812" alt="Screenshot 2022-01-19 at 13 05 44" src="https://user-images.githubusercontent.com/27485094/150085066-8450cc5e-630b-4922-bf90-82e8a40fd68d.png">

<details>
  <summary>Stack trace. </summary>

```
Error - 1:06:23 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.types.BLangTableTypeNode.accept(BLangTableTypeNode.java:82)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:1180)
	at org.wso2.ballerinalang.compiler.tree.types.BLangTableTypeNode.accept(BLangTableTypeNode.java:82)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:253)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:335)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:116)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookup(SymbolFinder.java:230)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:379)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:165)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.processSymbols(SemanticTokensVisitor.java:441)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:181)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.accept(SimpleNameReferenceNode.java:41)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:846)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:455)
	at io.ballerina.compiler.syntax.tree.TypeParameterNode.accept(TypeParameterNode.java:49)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:846)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:451)
	at io.ballerina.compiler.syntax.tree.TableTypeDescriptorNode.accept(TableTypeDescriptorNode.java:50)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:846)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:307)
	at io.ballerina.compiler.syntax.tree.TypeDefinitionNode.accept(TypeDefinitionNode.java:62)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:846)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:106)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$15(BallerinaTextDocumentService.java:624)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

Once `type TypeName table<>;` is inserted, hovering over `table<>` throws the NPE below.
<img width="812" alt="Screenshot 2022-01-19 at 13 20 50" src="https://user-images.githubusercontent.com/27485094/150087155-e5b2821f-4eaa-440f-a858-1af74579ac44.png">

<details>
  <summary>Stack trace. </summary>

```
[Error - 1:09:33 PM] Operation 'text/hover' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', [139:21], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.types.BLangTableTypeNode.accept(BLangTableTypeNode.java:82)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:1180)
	at org.wso2.ballerinalang.compiler.tree.types.BLangTableTypeNode.accept(BLangTableTypeNode.java:82)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:253)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:335)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:116)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookup(SymbolFinder.java:230)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:379)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:153)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:86)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
</details>

For as long as the completion item remains to be in the file, NPEs continue to be thrown for every text edit.
<details>
  <summary>Stack trace. </summary>

```
[Error - 12:40:02 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:40:09 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:40:10 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:40:10 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:40:14 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:41:51 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:41:51 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException

[Error - 12:41:51 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test-beta6/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
```
</details>

**Steps to reproduce:**
Mentioned in the description.

**Affected Versions:**
stage-swan-lake

**Comment by pubudu91** [comment]
Closing since fixed with #35007
