### ISSUE TITLE
`UnsupportedOperationException` when there is a dot after module name in import declaration

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34749]
**Description:**
![Peek 2022-01-20 15-25](https://user-images.githubusercontent.com/26381349/150315912-fa8e4178-0382-4e9d-a291-ab9c7e7465f6.gif)
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
java.lang.UnsupportedOperationException: remove
	at java.base/java.util.Iterator.remove(Iterator.java:102)
	at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:299)
	at org.ballerinalang.langserver.completions.providers.context.ImportDeclarationNodeContext.lambda$getCurrentProjectModules$3(ImportDeclarationNodeContext.java:277)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.langserver.completions.providers.context.ImportDeclarationNodeContext.lambda$getCurrentProjectModules$4(ImportDeclarationNodeContext.java:277)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.langserver.completions.providers.context.ImportDeclarationNodeContext.getCurrentProjectModules(ImportDeclarationNodeContext.java:267)
	at org.ballerinalang.langserver.completions.providers.context.ImportDeclarationNodeContext.getCompletions(ImportDeclarationNodeContext.java:94)
	at org.ballerinalang.langserver.completions.providers.context.ImportDeclarationNodeContext.getCompletions(ImportDeclarationNodeContext.java:58)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:136)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:82)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

**Affected Versions:**

Ballerina 2201.0.0 (Swan Lake) RC1

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
