### ISSUE TITLE
Cannot set readonly bit for xml subtypes

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#34760]
**Description:**
$subject

**Steps to reproduce:**
```ballerina
type E readonly & xml:Element;
// type P readonly & xml:ProcessingInstruction;
// type C readonly & xml:Comment;

public function main() {

}
```
Compiler crashes for above intersections.

```
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1654)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:116)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:299)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:1218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:411)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:342)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:299)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:276)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:434)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
	at io.ballerina.projects.Package.getCompilation(Package.java:145)
	at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by pcnfernando** [comment]
We'll have to handle the tsymbol being null. This should be reproducible with other built-in subtypes as well.

**Comment by pcnfernando** [comment]
As a workaround, we can use the inline definition.
```ballerina
public function main() {
    xml:Element & readonly _ = xml `<foo/>`; 
}
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34764.
