### ISSUE TITLE
Bad sad for constant boolean maps with logical negation

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#34774]
**Description:**
Consider the following example,
```ballerina
const map<boolean> X = {b : !false};
```
Output
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-01-21 12:38:57,073] SEVERE {b7a.log.crash} - finite type value is not supported for type: map<boolean> 
java.lang.UnsupportedOperationException: finite type value is not supported for type: map<boolean>
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstValue(BIRBinaryWriter.java:439)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstant(BIRBinaryWriter.java:387)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeConstants$7(BIRBinaryWriter.java:370)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstants(BIRBinaryWriter.java:370)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:79)
        at io.ballerina.projects.ModuleContext.cacheBIR(ModuleContext.java:491)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:461)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
**Affected Versions:**
2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
May also be related to https://github.com/ballerina-platform/ballerina-lang/issues/34765.

**Comment by KavinduZoysa** [comment]
No crash in `Ballerina 2201.4.0`. Therefore we can close this issue.
