### ISSUE TITLE
`(true|false?) b = true;` crashes local level due to missing SingletonTypeDescriptor wrapper for `false`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34810]
**Description:**
```bal
function fn() {
    true|false? b = true; // works
    (true|false?) b = true; // crashes
    (true|false) b = true; // works
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
2022-01-24 17:26:19,267] SEVERE {b7a.log.crash} - Node not supported: BasicLiteralNode 
java.lang.RuntimeException: Node not supported: BasicLiteralNode
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transformSyntaxNode(BLangNodeBuilder.java:3872)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transformSyntaxNode(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.NodeTransformer.transform(NodeTransformer.java:336)
	at io.ballerina.compiler.syntax.tree.BasicLiteralNode.apply(BasicLiteralNode.java:46)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createTypeNode(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3116)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.OptionalTypeDescriptorNode.apply(OptionalTypeDescriptorNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createTypeNode(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:911)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.UnionTypeDescriptorNode.apply(UnionTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createTypeNode(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:978)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.ParenthesisedTypeDescriptorNode.apply(ParenthesisedTypeDescriptorNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createTypeNode(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2833)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2798)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
```
</details>

**Affected Versions:**
2201.0.0 RC1

**Comment by rdulmina** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/34810
