### ISSUE TITLE
Compiler crashes when closures are used in object constructor expression 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#34823]
**Description:**
$title

**Steps to reproduce:**
```ballerina
int b5 = 60;
function testFunc(int b1) returns (function (int) returns (function (int) returns (int))) {
    int a1 = 10;
    return function(int b2) returns (function (int) returns (int)) {
        int a2 = 20;
        return function(int b3) returns (int) {
            int a3 = 30;
            var obj1 = object {
                int a4 = 40;
                function foo(int b4) returns int {
                    int sum = a1 + a2 + a3 + self.a4 + b1 + b2 + b3 + b4 + b5;
                    return sum;
                }
            };
            return obj1.foo(50);
        };
    };
}
```

```
{b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.addFunctionMapMapToClassDefinition(ClosureDesugar.java:399)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:1433)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef$BLangLocalVarRef.accept(BLangSimpleVarRef.java:99)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:2071)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:1227)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:67)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:2071)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:1225)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:67)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:2071)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:1225)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:67)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:2071)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:909)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:2051)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:714)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:2051)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteStmts(ClosureDesugar.java:2079)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:578)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:2051)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:570)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:2051)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:236)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:798)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```
**Affected Versions:**
SwanLake-GA-RC2

**Comment by lasinicl** [comment]
Following example also fails with a similar error log.
```ballerina
function testFunc(int b1) returns int|error? {
    int a1 = 10;
    var obj1 = object {
        int a2 = 20;
        function foo(int b2 = 10) returns int|error? {
            var obj2 = object {
                int a3 = 30;

                function bar(string b3) returns int|error? {
                    return a1 + self.a3 + b2 + check int:fromString(b3); 
                }

                function bam(int|error? b4) returns int {
                    if b4 is int {
                        return b4;
                    }
                    return 0;
                }
            };
            return obj2.bam(obj2.bar("123")) + self.a2;
        }
    };
    return obj1.foo(50);
}
```
