### ISSUE TITLE
Compiler crashes for `r is record {|int i;|}` where static type of r is `readonly & record {|int i;|}?`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34833]
**Description:**
```bal
type R readonly & record {|int i;|}?;

function test(R r) {
    if r is record {|int i;|} {
    
    }
    else {
   
    }
}

```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-01-25 21:43:25,555] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.TypeDefBuilderHelper.populateStructureFields(TypeDefBuilderHelper.java:361)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.populateImmutableStructureFields(ImmutableTypeCloner.java:535)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.defineImmutableRecordType(ImmutableTypeCloner.java:597)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.setImmutableType(ImmutableTypeCloner.java:285)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:195)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getEffectiveImmutableType(ImmutableTypeCloner.java:95)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersection(Types.java:4694)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4633)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4624)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.setNarrowedTypeInfo(TypeNarrower.java:458)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.visit(TypeNarrower.java:274)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeTestExpr.accept(BLangTypeTestExpr.java:75)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.analyzeExpr(TypeNarrower.java:302)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.getNarrowedTypes(TypeNarrower.java:280)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.evaluateTruth(TypeNarrower.java:105)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeNarrower.evaluateTruth(TypeNarrower.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2500)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
	at io.ballerina.projects.Package.getCompilation(Package.java:145)
	at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```
</details>

**Affected Versions:**
2201.0.0 RC2

**Comment by lochana-chathura** [comment]
with parenthesis; `(readonly & record { ... })?` works.
