### ISSUE TITLE
NPE for multi level record literal used as an argument

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#34876]
**Description:**

### Code

```Ballerina
import ballerina/http;

final http:Client securedEP = check new("abc",
    {cache: {enabled: true, isShared: true}},
    auth = {
        username: "abc",
        password: "abc"
    }
);
```

### Output
```LogTalk
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createAndAddRecordFieldForIncRecordLiteral(Desugar.java:8818)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.setFieldsForIncRecordLiterals(Desugar.java:8807)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderNamedArgs(Desugar.java:8785)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderArguments(Desugar.java:8525)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6400)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6346)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6525)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3541)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:105)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:7997)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7931)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:62)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2449)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.splitInitFunction(Desugar.java:10109)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:791)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
```

**Affected Versions:**
All

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Is the title accurate? Isn't this the same as https://github.com/ballerina-platform/ballerina-lang/issues/34566?

Works when

```ballerina
import ballerina/http;

final http:Client securedEP = check new ("abc",
    cache = {
        enabled: true,
        isShared: true
    },
    auth = {
        username: "abc",
        password: "abc"
    }
);
```

**Comment by KRVPerera** [comment]
Yes these are duplicates.
