### ISSUE TITLE
Docker run command gives a NPE due to `Config.toml` and `ballerina:ballrina` name

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#34906]
**Description:**
Simple project with `Config.toml` with atleast one variable without org name in `Ballerina.toml` crashes inside docker due to organisation name being ballerina. This may be happening because `whoami` returns `ballerina`.
Workaround is to add a org name to `Ballerina.toml` file. 

```toml
[package]
org = "customName"
name = "abcd"
version = "0.1.0"
```
We can also use this to forcefully recreate this locally.

### Config.toml
```toml
API_KEY=""
```
### Ballerina.toml
```toml
[package]
org = "ballerina"
name = "ballerina"
```

### How to run
```
bal run
```
or 

```
docker run -v `pwd`:/home/ballerina -it ballerina/ballerina:2201.0.0 bal run
```

```LogTalk
[2022-01-31 10:58:53,867] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at io.ballerina.runtime.internal.configurable.providers.toml.TomlProvider.getBasicTomlValue(TomlProvider.java:376)
	at io.ballerina.runtime.internal.configurable.providers.toml.TomlProvider.getPrimitiveTomlValue(TomlProvider.java:367)
	at io.ballerina.runtime.internal.configurable.providers.toml.TomlProvider.getAsStringAndMark(TomlProvider.java:203)
	at io.ballerina.runtime.internal.configurable.ConfigResolver.lambda$getConfigValue$6(ConfigResolver.java:112)
	at io.ballerina.runtime.internal.configurable.ConfigResolver.getConfigValue(ConfigResolver.java:162)
	at io.ballerina.runtime.internal.configurable.ConfigResolver.getConfigValue(ConfigResolver.java:111)
	at io.ballerina.runtime.internal.configurable.ConfigResolver.resolveConfigs(ConfigResolver.java:82)
	at io.ballerina.runtime.internal.launch.LaunchUtils.initConfigurableVariables(LaunchUtils.java:85)
	at ballerina.ballerina.0.$configurationMapper.$configureInit(Unknown Source)
	at ballerina.ballerina.0.$_init.main(ballerina)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
This is due to a bug in the module name ambiguity checking for configurable variables. 
Happens if we have the same org name and another module name. 
https://ballerina-platform.slack.com/archives/C47EAELR1/p1643609729186499
