### ISSUE TITLE
`NPE` in `BIROptimizer` when using query action

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34910]
**Description:**

Consider the below sample containing query action with where clause. It causes NPE when we return `item` inside do block.

```bal
function testReachabilityWithQueryAction() returns string {
    string[] stringArray = ["Hello", " ", "World"];

    error? unionResult = from var item in stringArray
        where item is string
        do {
            if item == "Hello" {
                return item;
            }
        };

    if unionResult is error {
    }
    return "c#";
}
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[2022-02-01 09:47:02,178] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:271)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>

**Affected Versions:**
2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
Same with 

```ballerina
function fn(stream<byte[] & readonly, error?> str) returns string[][]|error {
    string[][] arr = [];
    check from byte[] _ in str
    do {
        string|error s = "";

        if s is string {
            string[] r = [];
            foreach string _ in r {
                string[] r2 = [];
                arr.push(r2.map(currentRecord => currentRecord.trim()));
            }
        }
    };
    return arr;
}
```

Simplified from a connector example.

**Comment by KavinduZoysa** [comment]
Regarding these two examples, even if the stack trace is the same, the causes are different.
In first example the two variable references `item` in if-stmt inside do-clause have two different symbols in BIrGen.
But in the 2nd example, symbol of `arr` inside foreach is not available.

So my plan is to solve these two cases seperately.

**Comment by KavinduZoysa** [comment]
Simplified example for 2nd case,

```ballerina
function fn() returns error? {
    int i = 2;
    check from int _ in []
    do {
        foreach string _ in [] {
            int _ = i;
        }
    };
}
```
