### ISSUE TITLE
Choreo failed to write library error

### ISSUE THREAD

**Issue by BechtelCanDoIt** [ballerina-platform/ballerina-lang#34926]
**Description:**

scott@choreo-editor-a233b1b6-702a-4c0b-b1ce-fc9ccedf9852:~/workspace$ bal run /config/workspace 
Compiling source
        scottbechtel/checkcert:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-02-01 22:17:07,935] SEVERE {b7a.log.crash} - Failed to write library: /config/workspace/target/cache/scottbechtel/checkcert/0.1.0/java11/scottbechtel-checkcert-0.1.0.jar 
java.lang.RuntimeException: Failed to write library: /config/workspace/target/cache/scottbechtel/checkcert/0.1.0/java11/scottbechtel-checkcert-0.1.0.jar
        at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:117)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:308)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:466)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
Caused by: java.io.FileNotFoundException: /config/workspace/target/cache/scottbechtel/checkcert/0.1.0/java11/scottbechtel-checkcert-0.1.0.jar (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2187)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2881)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2843)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:2826)
        at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:114)
        ... 15 more
 
scott@choreo-editor-a233b1b6-702a-4c0b-b1ce-fc9ccedf9852:~/workspace$ 
**Steps to reproduce:**
Create api that does a get on httpclient
leave default say hello call
run 
See error in console

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by BechtelCanDoIt** [comment]
Associated with scott@wso2.com account.

**Comment by gimantha** [comment]
I followed the steps you have mentioned. The pack I used was 2201.0.2. But I was not able to reproduce this issue. Which version did you use @BechtelCanDoIt ?

**Comment by v-scottbechtel** [comment]
It was whatever version Choreo was using at the time. No idea. Feel free to close this since so much time has gone by. I'm sure it's been fixed since then.
