### ISSUE TITLE
Runtime crashes when `float:NaN` or `float:Infinity` is cast to `decimal`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#34997]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    float f = float:NaN; // or `float:Infinity`
    decimal _ = <decimal> f;
}
```

```log

[2022-02-10 11:18:50,766] SEVERE {b7a.log.crash} - Infinite or NaN 
java.lang.NumberFormatException: Infinite or NaN
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:923)
        at io.ballerina.runtime.internal.values.DecimalValue.valueOf(DecimalValue.java:590)
        at x.main(x.bal:3)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
2201.0.0

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34302. Hence closing this.
