### ISSUE TITLE
Compiler crashes for let-expr combined with anonymous function

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#35015]
**Description:**
$subject

**Steps to reproduce:**
```ballerina
public function main() {
    var _ = let null n = null in function() returns boolean {
        return n == ();
    };
}
```

<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[2022-02-10 17:13:18,183] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.createFunctionInfoArray(MainMethodGen.java:341)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.loadCLIArgsForMain(MainMethodGen.java:298)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateUserMainFunctionCall(MainMethodGen.java:273)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateMainMethod(MainMethodGen.java:167)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:428)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1039)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:397)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:808)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:95)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35796
