### ISSUE TITLE
Compiler crashes when accessing xml attribute available in wrong place

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#35102]
**Description:**
$subject

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    xml x = xml `<root></root attr="attr">`;
    io:println(x.attr);
}
```

error:
[2022-02-18 09:51:44,779] SEVERE {b7a.log.crash} - Syntax kind is not supported: EQUAL_TOKEN 
java.lang.RuntimeException: Syntax kind is not supported: EQUAL_TOKEN
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2280)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.Token.apply(Token.java:114)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5141)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5114)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3384)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.XMLTextNode.apply(XMLTextNode.java:46)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5141)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5114)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXMLTextLiteral(BLangNodeBuilder.java:3398)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXmlSequence(BLangNodeBuilder.java:4196)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXmlTemplateLiteral(BLangNodeBuilder.java:4243)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2294)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5141)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5114)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2823)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2798)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5015)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1555)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1458)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1438)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1416)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:607)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:473)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:506)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:424)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
	at io.ballerina.projects.Package.getCompilation(Package.java:145)
	at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

**Affected Versions:**

Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
Reproducible with just

```ballerina
public function main() {
    xml x = xml `<root></root attr="attr">`;
}
```
