### ISSUE TITLE
NPE for optional field access in lax type with type references

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#35107]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type T6 map<json>;

function init() {
    T6 t14 = {"a": 149, "b": {"a": null}, "c": null};
    json a = (t14?.b?.a);
}
```
Error:
```

[2022-02-18 12:53:19,290] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(Types.java:1311)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.handleSafeNavigation(Desugar.java:9561)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteSafeNavigationExpr(Desugar.java:9532)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteFieldBasedAccess(Desugar.java:5968)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6056)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:71)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5859)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangGroupExpr.accept(BLangGroupExpr.java:43)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8393)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:795)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
SL 2201.0.0

**Comment by pcnfernando** [comment]
Fixing this should also fix https://github.com/ballerina-platform/ballerina-lang/issues/34621
