### ISSUE TITLE
Runtime exception when assigning a mapping constructor for user-defined type of `json` 

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#35105]
**Description:**
$title. This works fine for other basic types which are supported by `json`. 
E.g. 
```ballerina
type T7 json;
// Following scenarios are working
T7 t15 = 21; // int
T7 t16 = 1.2; // float
T7 t17 = "JSON"; // string
T7 t18 = null; // nil
T7 t19 = true; // boolean

T7 t20 = {"a": 1}; // mapping constructor, runtime exception!
```
**Steps to reproduce:**
```ballerina
type T7 json;
T7 t20 = {"a": 1};
```
Output:
```
[2022-02-18 12:13:10,125] SEVERE {b7a.log.crash} - Given type can't be instantiated at runtime : json 
io.ballerina.runtime.internal.util.exceptions.BallerinaException: Given type can't be instantiated at runtime : json
        at io.ballerina.runtime.internal.values.TypedescValueImpl.instantiate(TypedescValueImpl.java:90)
        at test2.init(test2.bal:57)
        at $_init.$gen$$0046$0060init$0062(.:1)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Affected Versions:**
SL 2201.0.0

**Comment by HindujaB** [comment]
When creating a map value from the user-defined type which refers to the Ballerina in-built unions (anydata, json, any), it fails at runtime as the union type is not a proper map type. This needs to be fixed from compiler `TypeChecker` to check and provide the map type similar to a non-type-referenced type map constructor. 

```ballerina
type Any any;

public function main() {
    Any a = {"age": 22};  // passed as any
    io:println(a);

    any b = {"age": 22}; // passed as map<any> 
    io:println(b); 
}
```
The fix needs to be done from compiler FE.  Hence, removing the `jballerina` tag.
