### ISSUE TITLE
NPE in `JvmObservabilityGen` when `init` function is mistakenly specified as `remote` in client class

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#35143]
**Description:**
When the init function is specified as a remote function in a client class it results in an NPE as follows. Instead, we should display an error saying that the `init` function cannot be marked as `remote`.

```
[2022-02-21 12:48:44,307] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.generatePositionArgs(JvmObservabilityGen.java:1018)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.injectStartCallableObservationCall(JvmObservabilityGen.java:736)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.rewriteObservableFunctionInvocations(JvmObservabilityGen.java:572)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.instrumentPackage(JvmObservabilityGen.java:200)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:85)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:247)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Steps to reproduce:**

1. Create a simple library package using `bal new -t lib`
2. Add a dummy client class as follows.

```
public isolated client class Client {

    remote isolated function init() returns error? {
    }

}
```

3. Execute `bal pack` command.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This should probably result in a compilation error.
