### ISSUE TITLE
`java.lang.NullPointerException` when using `bal build`

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#35153]
**Description:**
When try to build following code-segment using `bal build`, the build crashes with a `java.lang.NullPointerException`.
```ballerina
import ballerina/http;
import ballerina/io;

var simpleHttpService = service object {
    // here param `name` is a query param
    // http://localhost:8080/hello?name=ayesh
    resource function get hello (string name) returns string {
        return string`Hello ${name}!`;
    }

    // here param `name` is a path variable
    // http://localhost:8080/greeting/ayesh
    resource function get greeting/[string name] () returns string {
        return string`Hello ${name}!`; 
    }

    // http://localhost:8080/
    resource function get . (http:Caller caller, http:Request request) {
        var response = caller->respond("Hello World..!");
        if (response is error) {
            io:println("Error occurred while responding to the request ", response.message());
        }
    }
};
```

Error Log:
```sh
[2022-02-21 23:37:47,057] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.createErrorType(Types.java:5203)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.createErrorType(Types.java:5194)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersectionForErrorTypes(Types.java:4960)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersection(Types.java:4700)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4633)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.lambda$getTypeForUnionTypeMembersAssignableToType$19(Types.java:3777)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeForUnionTypeMembersAssignableToType(Types.java:3776)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersection(Types.java:4740)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4633)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4624)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.addVarIfInferredTypeIncludesError(DataflowAnalyzer.java:2305)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:655)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:628)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:448)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visitFunctionBodyWithDynamicEnv(DataflowAnalyzer.java:428)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:405)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:389)
	at org.wso2.ballerinalang.compiler.tree.BLangResourceFunction.accept(BLangResourceFunction.java:41)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:579)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:607)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangObjectConstructorExpression.accept(BLangObjectConstructorExpression.java:56)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:665)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:322)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2065)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:292)
	at io.ballerina.projects.internal.CompilerPhaseRunner.dataflowAnalyze(CompilerPhaseRunner.java:200)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:124)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
	at io.ballerina.projects.Package.getCompilation(Package.java:145)
	at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

But when I changed my code as follows the build started working.
```ballerina
import ballerina/http;
import ballerina/io;

http:Service simpleHttpService = service object {
    // here param `name` is a query param
    // http://localhost:8080/hello?name=ayesh
    resource function get hello (string name) returns string {
        return string`Hello ${name}!`;
    }

    // here param `name` is a path variable
    // http://localhost:8080/greeting/ayesh
    resource function get greeting/[string name] () returns string {
        return string`Hello ${name}!`; 
    }

    // http://localhost:8080/
    resource function get . (http:Caller caller, http:Request request) {
        var response = caller->respond("Hello World..!");
        if (response is error) {
            io:println("Error occurred while responding to the request ", response.message());
        }
    }
};
```

**Comment by MaryamZi** [comment]
Seems to happen when `var` is used in both the service declaration and the local variable declaration.
