### ISSUE TITLE
Index out of bounds exception when triggering completions for a union

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35299]
Consider the following:
```ballerina
type Foo int|<cursor>
```

When you trigger completions at the illustrated cursor position, you get the following exception. Could potentially be an issue in the compiler side as well. 

```
[Error - 3:38:11 PM] Operation 'ballerinaDocument/executorPositions' failed! {uri: '/Users/pubuduf/issues/test.bal', error: 'Index: '56', Size: '55''}
java.lang.IndexOutOfBoundsException: Index: '56', Size: '55'
	at io.ballerina.tools.text.LineMap.positionRangeCheck(LineMap.java:59)
	at io.ballerina.tools.text.LineMap.linePositionFrom(LineMap.java:40)
	at io.ballerina.tools.text.TextDocument.linePositionFrom(TextDocument.java:46)
	at io.ballerina.compiler.syntax.tree.Node.lineRange(Node.java:142)
	at io.ballerina.compiler.syntax.tree.NodeLocation.lineRange(NodeLocation.java:41)
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:44)
	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:38)
	at java.base/java.util.TreeMap.compare(TreeMap.java:1292)
	at java.base/java.util.TreeMap.put(TreeMap.java:536)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.addDiagnostic(BLangPackage.java:291)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.storeDiagnosticInModule(BLangDiagnosticLog.java:290)
	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.logDiagnostic(BLangDiagnosticLog.java:212)
	at io.ballerina.projects.DocumentContext.reportSyntaxDiagnostics(DocumentContext.java:178)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:104)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:424)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:141)
	at org.ballerinalang.langserver.extensions.ballerina.document.ExecutorPositionsUtil.getExecutorPositions(ExecutorPositionsUtil.java:75)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentService.lambda$executorPositions$15(BallerinaDocumentService.java:392)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by IMS94** [comment]
This issue is no longer reproducible.
