### ISSUE TITLE
Compiling a table with an empty key field throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#35310]
**Description:**

Consider the scenario below.

<img width="688" alt="Screenshot 2022-03-02 at 22 13 24" src="https://user-images.githubusercontent.com/27485094/156407480-448b5c27-9c54-47dd-ae59-f0939c71bab9.png">

It shows no error diagnostics, but throws the following ArrayIndexOutOfBoundsException once compiled.

```
[2022-03-02 22:04:52,418] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.ballerina.runtime.internal.values.TableValueImpl$KeyHashValueHolder$DefaultKeyWrapper.wrapKey(TableValueImpl.java:699)
        at io.ballerina.runtime.internal.values.TableValueImpl$KeyHashValueHolder.addData(TableValueImpl.java:553)
        at io.ballerina.runtime.internal.values.TableValueImpl.addData(TableValueImpl.java:137)
        at io.ballerina.runtime.internal.values.TableValueImpl.<init>(TableValueImpl.java:127)
        at $_init.$gen$$0046$0060init$0062(.:370)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Steps to reproduce:**

Compile the following.
```
type Employee record {|
   readonly string name;
|};
 

public function main() {
    table <Employee> key() t = table [{name: ""}];
}
```
**Affected Versions:**
2201.0.1 (Swan Lake)

**Comment by pcnfernando** [comment]
Not compile-time; but runtime.
