### ISSUE TITLE
Compilation failure with NPE when a transitive dependency is not found

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#35385]
**Description:**
When a transitive dependency is missing, the compilation fails with different errors for different packages.

**Steps to reproduce:**

1. Create new ballerina lib package pkg_a, pack and push to local repo (`bal pack && bal push --repository local`)
5.Create new ballerina lib package pkg_b and use the `pkg_a:hello("hello")` function as shown below.
pkg_b.bal
```bal
import user/pkg_a;

public function hello_b(string name) returns string {
    return pkg_a:hello(name);
}
```
Add the local repo dependency in Ballerina.toml of pkg_b
```toml
[[dependency]]
org = "<org>"
name = "pkg_a"
version = "0.1.0"
repository="local"
```
Pack and push pkg_b to local repo

6. Create pkg_foo and use pkg_b as shown below.
```bal
import user/pkg_b;
import ballerina/io;

public function main() {
    io:println(pkg_b:hello("Hello, Foo!"));
}
```
Add the local repo dependency in Ballerina.toml of pkg_foo
```toml
[[dependency]]
org = "<org>"
name = "pkg_b"
version = "0.1.0"
repository="local"

[[dependency]]
org = "<org>"
name = "pkg_a"
version = "0.1.0"
repository="local"
```
Now build pkg_foo package. The package should build successfully.
7. Remove the local dependency for pkg_a from Ballerina.toml and rebuild the package.

Ballerina.toml after edit
```toml
[[dependency]]
org = "<org>"
name = "pkg_b"
version = "0.1.0"
repository="local"
```
Output:
```
Compiling source
        user/pkg_foo:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-03-08 23:37:20,905] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.populateConfigurableVars(SymbolResolver.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.getConfigVarSymbolsIncludingImportedModules(SymbolResolver.java:2477)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeModuleConfigurableAmbiguity(SemanticAnalyzer.java:1064)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:351)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [pkg_c:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```
Note: To recover from this situation, the bir and jar caches of the pkg_b has to be deleted.

**Affected Versions:**
Tested on 2201.0.x (commit: 6b2684fb0100a9e06c45b22358cb288b69363baf)

**Comment by azinneera** [comment]
Debugged and got this NPE as the cause for the failure:
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbol(SymbolResolver.java:636)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbolInMainSpace(SymbolResolver.java:665)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1167)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1347)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1190)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1121)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1190)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1246)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineFunction(BIRPackageSymbolEnter.java:392)
        at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:364)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:248)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:215)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:188)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:169)
        at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:533)
        at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by azinneera** [comment]
When the same conditions are met for `ballerina/task` package example, a different stacktrace was seen. Created https://github.com/ballerina-platform/ballerina-lang/issues/35390 since the cause looks different.

**Comment by MaryamZi** [comment]
We need to check if and where we can log an error for unresolved dependencies, when they are from the BIR.

The different exceptions are just probably depending on where we first try to work with that module.
