### ISSUE TITLE
NPE with optional field access in lax type

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#35384]
**Description:**
```ballerina
function init() returns error? {
    map<json> t14 = {"a": 149, "b": [{"a": {"b": {"c": 123}}}], "c": null};
    json|error b = (<json[]>(t14?.b))[0]?.a?.b;
}
```

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.clone(NodeCloner.java:313)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.visit(NodeCloner.java:1362)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.clone(NodeCloner.java:311)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.visit(NodeCloner.java:1292)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangGroupExpr.accept(BLangGroupExpr.java:43)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.clone(NodeCloner.java:311)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.cloneBLangAccessExpression(NodeCloner.java:357)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.visit(NodeCloner.java:1166)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:71)
        at org.wso2.ballerinalang.compiler.parser.NodeCloner.cloneNode(NodeCloner.java:275)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.getSuccessPattern(Desugar.java:9786)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.handleSafeNavigation(Desugar.java:9639)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteSafeNavigationExpr(Desugar.java:9532)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteFieldBasedAccess(Desugar.java:5968)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6056)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:71)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3541)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:105)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3445)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3446)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3541)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:105)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8065)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteFieldBasedAccess(Desugar.java:5968)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6056)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:71)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7301)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8400)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5821)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr$BLangArrayLiteral.accept(BLangListConstructorExpr.java:104)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8400)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6406)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6346)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3438)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8393)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:795)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
**Steps to reproduce:**

**Affected Versions:**
SL GA

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Doesn't crash on update 3 and later versions.
