### ISSUE TITLE
Compilation failure when a transitive dependency is not found

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#35390]
**Description:**
Compilation fails when the following conditions are met:
1. Transitive dependency is not found 
2. Corresponding direct dependency caches are generated already

**Steps to reproduce:**
1 . Create a new ballerina package and add the following code to the `main.bal`
```bal
import ballerina/task;

public function main() {
    task:JobId result;
}
```
2. Build with `jballerina-tools-2201.0.1-SNAPSHOT`. The task and time packages should be pulled and the compilation should be successful. `ballerina/time:2.2.1` should be locked in the Dependencies.toml.
3. Now, delete the bala and the cache of `ballerina/time:2.2.1` and rebuild the package with `bal build --offline`. Compilation should fail with the following output.
```
Compiling source
        user/pkg_c:0.1.0
error: failed to load the module 'ballerina/task:2.2.1' from its BIR
```

**Affected Versions:**
Tested on 2201.0.x (commit: https://github.com/ballerina-platform/ballerina-lang/commit/6b2684fb0100a9e06c45b22358cb288b69363baf)

**Comment by azinneera** [comment]
Debugged and got this NPE as the cause for the failure:
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbol(SymbolResolver.java:636)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbolInMainSpace(SymbolResolver.java:665)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1167)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1347)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1190)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1121)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1190)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1040)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1246)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:602)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineFunction(BIRPackageSymbolEnter.java:392)
        at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:364)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:248)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:215)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:188)
        at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:169)
        at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:533)
        at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by azinneera** [comment]
When the same conditions are met for basic lib packages, a different stacktrace was seen. Created https://github.com/ballerina-platform/ballerina-lang/issues/35385 since the cause looks different.

**Comment by MaryamZi** [comment]
See https://github.com/ballerina-platform/ballerina-lang/issues/35385#issuecomment-1062743433.

**Comment by azinneera** [comment]
LS is crashing and suggestions stop working due to the exception.

```
[Error - 1:08:52 am] Operation 'ballerinaDocument/executorPositions' failed! {uri: '/home/user/ipaas/nballerina/compiler/output.bal', error: 'failed to load the module 'ballerina/file:1.3.0' from its BIR due to: cannot resolve module ballerina/os:1.2.1'}
org.ballerinalang.compiler.BLangCompilerException: failed to load the module 'ballerina/file:1.3.0' from its BIR due to: cannot resolve module ballerina/os:1.2.1
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:198)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:174)
	at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:529)
	at io.ballerina.projects.ModuleCompilationState$8.compile(ModuleCompilationState.java:232)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:200)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:143)
	at org.ballerinalang.langserver.extensions.ballerina.document.ExecutorPositionsUtil.getExecutorPositions(ExecutorPositionsUtil.java:75)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentService.lambda$executorPositions$15(BallerinaDocumentService.java:392)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.ballerinalang.compiler.BLangCompilerException: cannot resolve module ballerina/os:1.2.1
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineImportPackage(BIRPackageSymbolEnter.java:384)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:369)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:238)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:220)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:193)
	... 19 more

```
