### ISSUE TITLE
Method is too large in `teststart` method

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#35396]
**Description:**

I am getting the following error when I try to add some ballerina tests to the HTTP module repo : 
```
Compiling source
        ballerina/http_tests:2.2.2
ERROR [http_tests:(2:2,2:2)] method is too large: '.<teststart>'
```

When I removed some of the tests, the test source is getting compiled. This is even happens if I remove some of the code segments.

Also this message is getting printed when the ballerina tests are running (not a recent one, this has been getting printed for quite some time), not sure whether this is related or not :
```
Running Tests with Coverage
        http_tests
java.lang.instrument.IllegalClassFormatException: Error while instrumenting ballerina/http_tests/2/http_tests.
        at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:94)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:272)
        at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:135)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:90)
        at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:119)
        at org.ballerinalang.test.runtime.Main.main(Main.java:100)
Caused by: java.io.IOException: Error while instrumenting ballerina/http_tests/2/http_tests.
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:110)
        at org.jacoco.agent.rt.internal_f3994fa.CoverageTransformer.transform(CoverageTransformer.java:92)
        ... 18 more
Caused by: org.jacoco.agent.rt.internal_f3994fa.asm.MethodTooLargeException: Method too large: ballerina/http_tests/2/http_tests.$gen$$0046$0060teststart$0062 (Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object;
        at org.jacoco.agent.rt.internal_f3994fa.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.jacoco.agent.rt.internal_f3994fa.asm.ClassWriter.toByteArray(ClassWriter.java:496)
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:91)
        at org.jacoco.agent.rt.internal_f3994fa.core.instr.Instrumenter.instrument(Instrumenter.java:108)
        ... 19 more
Sample products are added.
```

**Steps to reproduce :**
1. Clone the following repo : https://github.com/TharmiganK/module-ballerina-http
2. Checkout to `method-too-large` branch
3. Uncomment the code segments in `module-ballerina-http-response-interceptors/ballerina-tests/tests/interceptor_special_test.bal`
4. Run the build command : `./gradlew clean test -x :http-native:test -x :http-ballerina-tests:startLdapServer -x :http-ballerina-tests:stopLdapServer -x :http-compiler-plugin-tests:test` (Skipping java tests and docker container startup) 
5. You could see the error : `ERROR [http_tests:(2:2,2:2)] method is too large: '.<teststart>'`
6. If you uncomment only one or two tests the tests are getting compiled (there may be some test failures but it will get compiled)

**Comment by TharmiganK** [comment]
As a workaround, we have tried to reuse the same listener for a set of tests as much as possible. Since we have used many listeners for interceptor tests, we have tried to reduce it first. At first, this seems to be working but after a while when we add more code segments, only the windows build workflow failed due to idle timeout. Furthermore, we could not recreate this locally.
