### ISSUE TITLE
Compiler crashes when `is-expr` is used with distinct object type 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35500]
**Description:**
$titlle

**Steps to reproduce:**
```ballerina
import ballerina/io;
type Obj1 distinct object {
    int a;
    function f1();
};

function init() {
    Obj1 c = object {
        int a = 10;
        function f1() {

        }
    };
    io:println(c is distinct object {
        int a;
        function f1();
    }); 
}
```
Error Log:
```
SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:486)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1771)
        at org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode.accept(BLangObjectTypeNode.java:72)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1670)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeTestExpr.accept(BLangTypeTestExpr.java:75)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeArgIsolatedness(IsolationAnalyzer.java:2269)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeInvocation(IsolationAnalyzer.java:1985)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1403)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:640)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:439)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:359)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyze(IsolationAnalyzer.java:325)
        at io.ballerina.projects.internal.CompilerPhaseRunner.isolationAnalyze(CompilerPhaseRunner.java:204)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:129)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
Swan Lake GA

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/36714, https://github.com/ballerina-platform/ballerina-lang/issues/36714#issuecomment-1165514787. Fixed for Update 3 in https://github.com/ballerina-platform/ballerina-lang/pull/37003.
