### ISSUE TITLE
Runtime crash when default or rest parameters of called function types are not provided

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#35526]
**Description:**

$title

**Steps to reproduce:**
1.
```bal
public function main() {
    function (boolean|float,string="") returns string? func = (p,q) => "someString";
    string? funcval = func(2.0);
}
```
will give
```
Running executable

[2022-03-22 12:40:56,226] SEVERE {b7a.log.crash} - Bad local variable type
Exception Details:
  Location:
    issue.main(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @513: aload
  Reason:
    Type top (current frame, locals[35]) is not assignable to reference type
  Current Frame:
    bci: @513
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/FPValue', 'java/lang/Object', 'java/lang/Object', double, double_2nd, 'io/ballerina/runtime/api/values/BString', long, long_2nd, long, long_2nd, 'io/ballerina/runtime/api/values/BString', long, long_2nd, long, long_2nd, 'io/ballerina/runtime/api/values/BString', long, long_2nd, long, long_2nd, 'io/ballerina/runtime/api/values/BString', long, long_2nd, long, long_2nd, 'java/lang/Object', 'io/ballerina/runtime/internal/values/ErrorValue', 'java/lang/Object', integer }
    stack: { 'java/util/function/Function', '[Ljava/lang/Object;', '[Ljava/lang/Object;', integer }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 4c01 4d01
    0000010: 4e0e 3904 013a 0609 3707 0937 0901 3a0b
    0000020: 0937 0c09 370e 013a 1009 3711 0937 1301
    0000030: 3a15 0937 1609 3718 013a 1a01 3a1b 013a
.
.
.
    same_frame(@885)
    full_frame(@896,{Object[#13],Null,Null,Null,Double,Null,Long,Long,Null,Long,Long,Null,Long,Long,Null,Long,Long,Null,Null,Null,Integer},{})
    full_frame(@1029,{Object[#13],Object[#92],Object[#4],Object[#4],Double,Object[#281],Long,Long,Object[#281],Long,Long,Object[#281],Long,Long,Object[#281],Long,Long,Object[#4],Object[#187],Object[#4],Integer},{})

        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
2. 
```bal
public function main() {
    function (boolean|float,string...) returns string? func = (p) => "someString";
    string? funcval = func(2.0);
    // string? funcval = func(2.0,"jj"); // This will also give the same error
}
```
will give
```
Running executable

[2022-03-22 12:46:04,192] SEVERE {b7a.log.crash} - 'java.lang.Object issue.$lambda$_0(io.ballerina.runtime.internal.scheduling.Strand, java.lang.Object, boolean)' 
java.lang.NoSuchMethodError: 'java.lang.Object issue.$lambda$_0(io.ballerina.runtime.internal.scheduling.Strand, java.lang.Object, boolean)'
        at issue.$lambda$_0$lambda0$(issue.bal:2)
        at issue.main(issue.bal:3)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Here also needs to check whether this should be a compilation error unless two args should be there (i.e. `func = (p,q) => "someString";`) because when we write functions with rest args we write like this
```
function func(int p, string... q) returns string? {
    return "someString";
}
```

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Most probably fixed in https://github.com/ballerina-platform/ballerina-lang/pull/31589, merged to master an hour ago. cc @chiranSachintha

**Comment by chiranSachintha** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31589
@Nadeeshan96 Can you recheck on master

**Comment by Nadeeshan96** [comment]
I checked with the master branch. The first one is solved, but the second one (one with rest parameters) is not solved.

**Comment by Nadeeshan96** [comment]
As the following
```bal
public function main() {
    function (boolean|float,string...) returns string? func2 = function (boolean|float p, string... q) returns string? { return "someString";};
    string? funcval1 = func2(2.0);
    string? funcval2 = func2(2.0,"jj");
}
```
works fine, it seems the correct way to write the expression-bodied function is this.
```bal
function (boolean|float,string...) returns string? func = (p, q) => "someString";
```
But currently it gives a compilation error when written like that and no compilation error when written like this.
```bal
function (boolean|float,string...) returns string? func = (p) => "someString";
```
So, other way around should be the correct way and the compilation error should be corrected.
