### ISSUE TITLE
CCE in IsolationAnalyzer for Tuples

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#35733]
**Description:**
```LogTalk
[2022-04-07 15:36:06,655] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeArgIsolatedness(IsolationAnalyzer.java:2173)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeInvocation(IsolationAnalyzer.java:1985)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1419)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation$BLangActionInvocation.accept(BLangInvocation.java:263)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1641)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:62)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:640)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:543)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:646)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:439)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:316)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:359)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyze(IsolationAnalyzer.java:325)
        at io.ballerina.projects.internal.CompilerPhaseRunner.isolationAnalyze(CompilerPhaseRunner.java:204)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:129)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
WARNING [shuttle_service.bal:(8:5,8:5)] concurrent calls will not be made to this method since the method is not an 'isolated' method
WARNING [shuttle_service.bal:(27:5,27:5)] concurrent calls will not be made to this method since the service and the method are not 'isolated'
WARNING [shuttle_service.bal:(31:5,31:5)] concurrent calls will not be made to this method since the service and the method are not 'isolated'
WARNING [shuttle_service.bal:(42:5,42:5)] concurrent calls will not be made to this method since the service and the method are not 'isolated'
WARNING [main.bal:(85:5,85:55)] unused variable 'prevKeys'
WARNING [main.bal:(89:5,89:54)] unused variable 'newKeys'
WARNING [main.bal:(90:36,90:49)] unused variable 'currentCaller'
WARNING [main.bal:(90:51,90:73)] unused variable 'desiredPickUpLocations'
ERROR [problem_6_1:(1:1,1:1)] Compilation failed due to: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app')
error: compilation contains errors
```

**Affected Versions:**
Ballerina 2201.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Reproducible with

```ballerina
type Foo [int, string...];

public function main() {
    Foo f = [1];
    fn(...f);
}

function fn(int a, string... b) {
}
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36505.
