### ISSUE TITLE
Runtime crash during inter worker message passing

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#35858]
**Description:**

$title
The BBE https://ballerina.io/1.2/learn/by-example/worker-interaction.html?is_ref_by_example=true is modified to support swan lake. Runtime crashes when that code is run giving this error.
```
Running executable

[2022-04-20 10:11:46,585] SEVERE {b7a.log.crash} - Expecting a stackmap frame at branch target 939
Exception Details:
  Location:
    flush_other.$lambda$_1(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @165: lookupswitch
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2a10 02bd 000d 5910 00bb 000d 5912 0f03
    0000010: 03b7 0012 5359 1001 bb00 0d59 1214 0304
    0000020: b700 1253 b600 1c2a b400 2099 0007 b800
    0000030: 26bf 0940 0e4a 013a 0509 3706 0937 080e
    0000040: 390a 013a 0c01 3a0d 013a 0e01 3a0f 013a
    0000050: 1001 3a11 013a 1201 3a13 013a 1401 3a15
.
.
.
    same_frame(@1398)
    full_frame(@1409,{Object[#24],Long,Double,Null,Long,Long,Double,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Long,Null,Null,Null,Null,Long,Long,Null,Null,Null,Integer},{})
    full_frame(@1591,{Object[#24],Long,Double,Object[#187],Long,Long,Double,Object[#187],Object[#4],Object[#187],Object[#4],Object[#4],Object[#394],Object[#4],Object[#4],Object[#4],Object[#4],Object[#4],Object[#209],Object[#4],Object[#394],Object[#394],Object[#4],Object[#4],Object[#4],Object[#4],Long,Object[#438],Object[#4],Object[#4],Object[#394],Long,Long,Object[#4],Object[#272],Object[#4],Integer},{})

        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
**Steps to reproduce:**
```bal
import ballerina/io;
import ballerina/lang.runtime;

public function main() {
    worker w1 {
        int i = 100;
        float k = 2.34;

        // Sends messages asynchronously to the worker `w2`. This message contains a
        // tuple value with the member types `int` and `float`.
        [int, float] t1 = [i, k];
        t1 -> w2;
        io:println("[w1 -> w2] i: ", i, " k: ", k);

        // Receives a message from the worker `w2`. This message contains `
        // a `json`-typed value.
        json j = {};
        j = <- w2;
        string jStr = j.toString();
        io:println("[w1 <- w2] j: ", jStr);
        io:println("[w1 ->> w2] i: ", i);

        // Sends messages synchronously to the worker `w2`. The worker `w1` will wait
        // until the worker `w2` receives the message.
        () send = i ->> w2;

        // The synchronous sending returns `nil` if the message was successfully sent or
        // returns an error or panics based on the receiving worker's state.
        io:println("[w1 ->> w2] successful!!");

        // Sends messages asynchronously to the worker `w3`.
        io:println("[w1 -> w3] k: ", k);
        k -> w3;
        k -> w3;
        k -> w3;

        io:println("Waiting for worker w3 to fetch messages..");

        // Flushes all messages sent asynchronously to the worker `w3`. The worker
        // will halt at this point until all messages are sent or until the worker `w3`
        // fails.
        error? flushResult = flush w3;
        io:println("[w1 -> w3] Flushed!!");
    }

    worker w2 {
        // Receives a message from the worker `w1`.
        int iw;
        float kw;
        [int, float] vW1 = [0, 1.0];
        vW1 = <- w1;
        [iw, kw] = vW1;
        io:println("[w2 <- w1] iw: ", iw, " kw: ", kw);

        // Sends a message asynchronously to the worker `w1`.
        json jw = {"name": "Ballerina"};
        io:println("[w2 -> w1] jw: ", jw);
        jw -> w1;

        // Receives the message sent synchronously from the worker `w1`
        int lw;
        runtime:sleep(0.005);
        lw = <- w1;
        io:println("[w2 <- w1] lw: ", lw);
    }

    worker w3 {
        float mw;

        // Receives messages from the worker `w1` after a certain time.
        runtime:sleep(0.05);
        mw = <- w1;
        mw = <- w1;
        mw = <- w1;
        io:println("[w3 <- w1] mw: ", mw);
    }

    // Waits for the worker `w1`to finish.
    wait w1;
}
```
**Note:**
The error doesn't come and the program runs as expected if the jar file is run using `java -jar -noverify balprogram.jar`

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Can be reproduced by the following snippet.
```bal
public function main() {
    worker w1 {
        int[1] t1 = [1];
        t1 -> w2;
        int c = 3;
    }

    worker w2 {
        int[1] vW1 = <- w1;
    }
}
```
