### ISSUE TITLE
NPE at runtime when an immutable type is created in tests referring a type in main module

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#35865]
**Description:**
NPE is thrown when a type defined in the main module is being used to create an immutable type in the tests.

Stacktrace
```
java.lang.NullPointerException
        at io.ballerina.runtime.internal.types.BIntersectionType.<init>(BIntersectionType.java:66)
        at ballerina.websub.2.types.$_record_types.$populate$type$UnsubscriptionVerification(Unknown Source)
        at ballerina.websub.2.types.$_types.$createTypes(Unknown Source)
        at ballerina.websub.2.$_init.$currentModuleInit(websub)
        at ballerina.websub.2.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at ballerina.websub$test.2.$configurationMapper.$configureInit(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.run(TesterinaFunction.java:90)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.directInvoke(TesterinaFunction.java:67)
        at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:288)
        at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:268)
        at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:132)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:92)
        at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:139)
        at org.ballerinalang.test.runtime.Main.main(Main.java:120)
```

**Steps to reproduce:**
[intersection-type-test.zip](https://github.com/ballerina-platform/ballerina-lang/files/8524191/intersection-type-test.zip)

**Affected Versions:**
[v2201.1.0-rc1](https://github.com/ballerina-platform/ballerina-lang/releases/tag/v2201.1.0-rc1)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/35866.
