### ISSUE TITLE
Type checking issue for user defined type constants

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#35919]
**Description:**
$title.

```ballerina
const X AAA = "ab" + "c"; // incompatible types: expected '"abc"', found 'string'
type X "abc";
```
**Affected Versions:**
2201.0.2 (Swan Lake)

**Comment by SandaruJayawardana** [comment]
Bad sad for following code
```ballerina
type X int;
const X bm3 = 1 + bm1;
const int bm1 = 1;
```
Stack trace
```
java.lang.IllegalStateException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8096)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangConstant.accept(BLangConstant.java:112)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8394)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:781)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8343)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
