### ISSUE TITLE
NullPointerException in SymbolResolver

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#35958]
nBallerina nightly failing with  following error

```
java.lang.NullPointerException
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.populateConfigurableVars(SymbolResolver.java:2550)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.getConfigVarSymbolsIncludingImportedModules(SymbolResolver.java:2542)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeModuleConfigurableAmbiguity(SemanticAnalyzer.java:1082)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:330)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
    at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
    at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:201)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:282)
    at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
    at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
    at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:438)
    at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
    at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:387)
    at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
    at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
    at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
    at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
    at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
    at io.ballerina.projects.Package.getCompilation(Package.java:147)
    at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
    at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:95)
    at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
    at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:248)
    at java.base/java.util.Optional.ifPresent(Optional.java:183)
    at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

https://github.com/ballerina-platform/nballerina/runs/6203970625?check_suite_focus=true

**Comment by pcnfernando** [comment]
Relates to https://github.com/ballerina-platform/ballerina-lang/issues/35385

**Comment by pcnfernando** [comment]
Closing this as the NPE is handled and diagnostics are added for unresolved dependencies. The original issue of distribution not having related dependencies in-house will be handled through https://github.com/ballerina-platform/ballerina-lang/issues/36047
