### ISSUE TITLE
Compiler crashes with field access on remote method of client object 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#36034]
**Description:**
$title

**Steps to reproduce:**
```ballerina
function init() {
    var obj = client object {
        remote function f1() {
        }
    };
    io:println(obj.f1); 
}
```
```
SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.generatePositionArgs(JvmObservabilityGen.java:1037)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.injectStartCallableObservationCall(JvmObservabilityGen.java:736)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.rewriteObservableFunctionInvocations(JvmObservabilityGen.java:590)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.instrumentPackage(JvmObservabilityGen.java:152)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:85)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:310)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:166)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:123)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
**Affected Versions:**
2201.0.3

**Comment by MaryamZi** [comment]
This should have resulted in a compilation error (https://github.com/ballerina-platform/ballerina-lang/issues/37362). May also be related to https://github.com/ballerina-platform/ballerina-lang/issues/27917.

cc @ushirask
