### ISSUE TITLE
`ReferenceFinder` crashing with the list constructor spread operator

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#36073]
**Description:**
$subject.

```bal
public function main() {
    int[] x = [1, 2 , 3];
    int[] y = [...x];
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[Error - 11:10:02 AM] Operation 'text/codeAction' failed! {uri: '/home/lochanaj/Downloads/new/test.bal', [5:22]- [5:22], error: 'java.lang.AssertionError, org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:661)'}
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:661)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr$BLangListConstructorSpreadOpExpr.accept(BLangListConstructorExpr.java:180)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:224)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:229)
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:895)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr.accept(BLangListConstructorExpr.java:57)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:224)
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:340)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:224)
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:391)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:224)
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:298)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:224)
	at io.ballerina.compiler.api.impl.ReferenceFinder.findReferences(ReferenceFinder.java:215)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.getReferences(BallerinaSemanticModel.java:283)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:229)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:202)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:98)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:929)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:96)
	at org.ballerinalang.langserver.codeaction.providers.IgnoreUnusedVariableCodeAction.lambda$getDiagBasedCodeActions$2(IgnoreUnusedVariableCodeAction.java:111)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.ballerinalang.langserver.codeaction.providers.IgnoreUnusedVariableCodeAction.lambda$getDiagBasedCodeActions$3(IgnoreUnusedVariableCodeAction.java:111)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.ballerinalang.langserver.codeaction.providers.IgnoreUnusedVariableCodeAction.getDiagBasedCodeActions(IgnoreUnusedVariableCodeAction.java:110)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:122)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
```
</details>

**Comment by lochana-chathura** [comment]
Fixed in #36076
