### ISSUE TITLE
NPEs in `ImmutableTypeCloner` and `SymbolFinder`

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#36088]
**Description:**
Editing the latest code in the nballerina repo throws the following NullPointerExceptions.
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-05-11 11:45:50,799] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.requiredTypeDefsExist(ImmutableTypeCloner.java:921)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.requiredTypeDefsExist(ImmutableTypeCloner.java:899)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.isDefinedInCurrentModuleInCurrentCompilation(ImmutableTypeCloner.java:837)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:192)
	at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableIntersectionType(ImmutableTypeCloner.java:114)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.computeIntersectionType(SymbolResolver.java:2369)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.transform(SymbolResolver.java:1266)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.transform(SymbolResolver.java:144)
	at org.wso2.ballerinalang.compiler.tree.types.BLangIntersectionTypeNode.apply(BLangIntersectionTypeNode.java:61)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:520)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:2342)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:301)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineConstructs$8(SymbolEnter.java:461)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:461)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:344)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:301)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:277)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:426)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:200)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:143)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:271)
	at org.ballerinalang.langserver.util.LSClientUtil.chekAndRegisterCommands(LSClientUtil.java:78)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:556)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
 ```
[Error - 11:45:51 AM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/tharushijayasekara/Documents/Ballerina/nballerina/compiler/modules/front/expr.bal', error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.types.BLangConstrainedType.accept(BLangConstrainedType.java:55)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:1168)
	at org.wso2.ballerinalang.compiler.tree.types.BLangConstrainedType.accept(BLangConstrainedType.java:55)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:253)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:356)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:253)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:414)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNodes(SymbolFinder.java:242)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:301)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookupNode(SymbolFinder.java:253)
	at io.ballerina.compiler.api.impl.SymbolFinder.visit(SymbolFinder.java:291)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at io.ballerina.compiler.api.impl.SymbolFinder.lookup(SymbolFinder.java:230)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:388)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:175)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.processSymbols(SemanticTokensVisitor.java:441)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:181)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.accept(SimpleNameReferenceNode.java:41)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:455)
	at io.ballerina.compiler.syntax.tree.TypeParameterNode.accept(TypeParameterNode.java:49)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:299)
	at io.ballerina.compiler.syntax.tree.MapTypeDescriptorNode.accept(MapTypeDescriptorNode.java:45)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:575)
	at io.ballerina.compiler.syntax.tree.TypedBindingPatternNode.accept(TypedBindingPatternNode.java:45)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:75)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.accept(VariableDeclarationNode.java:62)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:323)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.accept(FunctionBodyBlockNode.java:54)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:850)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:106)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$15(BallerinaTextDocumentService.java:624)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
Comment out line [#929](https://github.com/ballerina-platform/nballerina/blob/33f8e5ae797769eeaf6d9540eeecf9a810f9bd5c/compiler/modules/front/expr.bal#L929) in `nballerina/compiler/modules/front/expr.bal`.

**Affected Versions:**
2201.1.0 (Swan Lake)

**Comment by KavinduZoysa** [comment]
Tested with PR #36093. It is working.

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36093.
