### ISSUE TITLE
Runtime crashes when a hardcoded string contains large surrogates

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#36087]
**Description:**
$subject
Happens when the string contains > 1000 Unicode characters (emoji).

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() returns error? {
    string test1 = "<Add_large_string>";
    io:println(test1 + " ");
}
```
Large string - 
[TestNonBMP1000.txt](https://github.com/ballerina-platform/ballerina-lang/files/8667132/TestNonBMP1000.txt)

Error : 
```
[2022-05-11 11:20:55,861] SEVERE {b7a.log.crash} - null 
java.lang.ExceptionInInitializerError
        at hinduja.foo.0.$_init.$gen$$0046$0060init$0062(foo:0)
        at hinduja.foo.0.$_init.$moduleInit(foo)
        at hinduja.foo.0.$_init.$lambda$$moduleInit$(foo)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NegativeArraySizeException: -40
        at hinduja.foo.0.constants.$_string_constants.$string_init0(Unknown Source)
        at hinduja.foo.0.constants.$_string_constants.<clinit>(Unknown Source)
        ... 7 more
```
**Affected Versions:**
2201.0.3 and previous versions

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#36015

**Comment by HindujaB** [comment]
Fix merged with PR https://github.com/ballerina-platform/ballerina-lang/pull/36089
