### ISSUE TITLE
NPE when trying to build a xml payload.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [ballerina-platform/ballerina-lang#36091]
Below is the code snippet that I was trying.

EmployeeFillUpSummary[] perEmployeeRecordArray = [];

xml processedPayload = xml `<s:employeeFuelRecords xmlns:s="http://www.so2w.org">
    ${from var {employeeId, gasFillUpCount, totalFuelCost, totalGallons, totalMilesAccrued} in perEmployeeRecordArray
           select xml`<s:employeeFuelRecord employeeId="${employeeId}">
           <s:gasFillUpCount>${gasFillUpCount}</s:gasFillUpCount>
           <s:totalFuelCost>${totalFuelCost}</s:totalFuelCost>
           <s:totalGallons>${totalGallons}</s:totalGallons>
           <s:totalMilesAccrued>${totalMilesAccrued}</s:totalMilesAccrued>
           </s:employeeFuelRecord>
           `}
    </s:employeeFuelRecords>`;

type EmployeeFillUpSummary record {
    int employeeId;
    int gasFillUpCount;
    float totalFuelCost;
    float totalGallons;
    int totalMilesAccrued;
};

Stack trace:

[2022-05-11 12:59:14,529] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:273)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:166)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:123)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [problem_1_4:(1:1,1:1)] Compilation failed due to an unhandled exception

**Comment by Dumindu-Kanchana** [comment]
It looks like NS seems to be the problem.

**Comment by gimantha** [comment]
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/36012 @pcnfernando shall we check?

**Comment by pcnfernando** [comment]
> This should be fixed with #36012 @pcnfernando shall we check?

Yes this will be fixed with #36012
