### ISSUE TITLE
Compiler crashes with NPE for the valid code

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#36172]
**Description:**
$subject.

```bal
type ReadableTextRecordChannel any;

public const COLON = ":";

public const TAB = "\t";

public const COMMA = ",";

public type Separator COMMA|TAB|COLON|string;

public class ReadableCSVChannel {
    private ReadableTextRecordChannel? dc;

    isolated function init(Separator fs = ",") {
    }
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
2022-05-17 13:58:19,352] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:405)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:363)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1070)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4155)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4131)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4112)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:467)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4155)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4131)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addClassMemberFunctionsToTopLevel(Desugar.java:506)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addAttachedFunctionsToPackageLevel(Desugar.java:489)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:752)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8434)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
```
</details>

**Affected Versions:**
current master

**Comment by lochana-chathura** [comment]
Root cause is at, 
https://github.com/ballerina-platform/ballerina-lang/blob/c609456a73fae659a1263615a409b83841131c56/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java#L351

`isFiniteContext` is updated to `true` only after type checking. Therefore, it should not be cloned as it could compromise any new type checking on top of the cloned node. 

In the sample above, at desugar, we clone the BLangLiteral  `","` in  `Separator fs = ","` and do type checking on the cloned node.
