### ISSUE TITLE
Windows 10: Cannot add Module to Project

### ISSUE THREAD

**Issue by IAmPapaMike** [ballerina-platform/ballerina-lang#36288]
**Description:**
I created a project, then added a module to it, and when I try to execute the project I get the following error:

[2022-05-23 16:57:53,899] SEVERE {b7a.log.crash} - ballerina/io/1/$configurationMapper 
java.lang.NoClassDefFoundError: ballerina/io/1/$configurationMapper
        at papamike.ptest.0.$configurationMapper.$configureInit(Unknown Source)
        at papamike.ptest.0.$_init.main(ptest)
Caused by: java.lang.ClassNotFoundException: ballerina.io.1.$configurationMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more

**Steps to reproduce:**
1. Create a new project: "bal new ptest"
2. CD into the project folder and add a module "bal add ppkg"
3. Attempt to execute the project

**Affected Versions:**
Ballerina 2201.0.3 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9

**OS, DB, other environment details and versions:**
Windows 10, using Visual Studio Code, Using Ballerina WS02 extension

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@azinneera Any update on this issue?

**Comment by azinneera** [comment]
Doubt this issue is Windows specific since we have not come across this with Ubuntu or Mac. We will check this and update.

**Comment by gayaldassanayake** [comment]
This issue has been already addressed for 2201.0.4 milestone when fixing https://github.com/ballerina-platform/ballerina-lang/issues/34949. 

Expected behaviour seen in update 1, update 2 as well.

**Comment by azinneera** [comment]
@IAmPapaMike You can download our latest release from https://ballerina.io/downloads/ to get the fix. If you want to stick to `Ballerina 2201.0.x`, the archived versions are available at https://ballerina.io/downloads/archived/#swan-lake-archived-versions
