### ISSUE TITLE
Query with select clause having xml template with interpolated query crashes

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#36286]
**Description:**
$subject. Refer to the following code sample. 

```bal
public function main() {
    int[] a = [1, 2];

   xml x = from int i in a
        select xml `<row>${from int j in a
            select xml `<num>${i}${j}</num>`}</row>`;
            
    io:println(x);
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-05-24 00:52:51,520] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.createFunctionInfoArray(MainMethodGen.java:341)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.loadCLIArgsForMain(MainMethodGen.java:298)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateUserMainFunctionCall(MainMethodGen.java:273)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateMainMethod(MainMethodGen.java:167)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:428)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1040)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:397)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:808)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:95)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:309)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>

**Affected Versions:**
2201.1.0 rc2

**Comment by Nadeeshan96** [comment]
Consider the following program which crashes.
```bal
public function main() {
    foo();
}

function foo() {
    int[] a = [1, 2];

    xml x = from int i in a
        select xml `<row>${from int j in a
            select xml `<num>${i}${j}</num>`}</row>`;
}
```
There in the BIR we see it is due to the `foo` function requiring arguments when it is called, which is wrong.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/33286289/178924659-d2f9fa38-b9e2-4501-a86b-11747fd5648d.png">
This is due to adding an element to the `foo`'s `bLangFunction.paramClosureMap` in `ClosureDesugar.updatePrecedingFunc` method.
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/33286289/178925842-fed45de5-140c-42ff-b7c1-05a0b1bfc932.png">
But if we see the below working code somewhat similar to the above, it doesn't go in such path.
```bal
public function main() {
    foo();
}

function foo() {
    int[] a = [1, 2];

    xml x = from int i in a
        select xml `<row>${from int j in a
            select xml `<num>${j}</num>`}</row>`;
}
```
Therefore this needs to be fixed in the frontend most probably in `QueryDesugar`. Hence removing the `jBallerina` tag.
