### ISSUE TITLE
Runtime stack type mismatch

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#36300]
**Description:**

```Ballerina
public function main() {
    map<int> bmap = {};
    bmap["i"] = 10;

    var foo = new Foo(bmap);
}

class Foo {
    map<int> oceMap;

    function init(map<int> mm) {
        self.oceMap = mm;
    }
}
```

```LogTalk

[2022-05-24 14:08:00,602] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    $value$Foo.init(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/MapValue;Z)Ljava/lang/Object; @183: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$Foo'
  Current Frame:
    bci: @183
    flags: { }
    locals: { '$value$Foo', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', integer, 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$Foo', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/MapValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 3a04 013a
    0000010: 0501 3a06 013a 0701 3a08 013a 0901 3a0a
    0000020: 0336 0b2b b400 1d9d 00a6 150b ab00 0000
    0000030: 0000 00d9 0000 0003 0000 0000 0000 0024
    0000040: 0000 0001 0000 0091 0000 0002 0000 0099
    0000050: 1100 0036 0bbb 005f 59bb 0061 59b2 0067
    0000060: 03b7 006a 1000 bd00 5db7 006d 3a05 1905
    0000070: 2b14 0024 88bd 006f b900 7503 003a 0619
    0000080: 06c0 005d 3a04 2a3a 07b2 007b 3a08 1904
    0000090: 1908 1907 b800 81b2 007b 3a08 1904 c000
    00000a0: 5d19 08b9 0084 0200 c000 073a 09b2 0087
    00000b0: 3a08 1909 1908 2cb7 008b 013a 0a11 0001
    00000c0: 360b a700 0311 0002 360b 190a b02b 59b4
    00000d0: 001d 0464 b500 1d2b b400 39b6 003f c000
    00000e0: 8d59 b400 8e3a 0a59 b400 8f4d 59b4 0090
    00000f0: 3e59 b400 933a 0459 b400 963a 08b4 0097
    0000100: 360b a7ff 28bb 008d 59b7 0098 5919 0ab5
    0000110: 008e 592c b500 8f59 1db5 0090 5919 04b5
    0000120: 0093 5919 08b5 0096 5915 0bb5 0097 3a0d
    0000130: 2bb4 0039 190d b600 5657 2b59 b400 1d04
    0000140: 60b5 001d 190a b0                      
  Stackmap Table:
    same_frame(@11)
    full_frame(@42,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Null,Null,Null,Object[#154],Null,Object[#35],Integer},{})
    same_frame(@80)
    full_frame(@189,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Object[#95],Object[#35],Object[#3],Object[#154],Object[#7],Object[#35],Integer},{})
    same_frame(@197)
    full_frame(@205,{Object[#3],Object[#15],Object[#93],Integer,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@261,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Null,Null,Null,Object[#154],Null,Object[#35],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    $value$Foo.init(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/MapValue;Z)Ljava/lang/Object; @183: invokespecial
  Reason:
    Type 'io/ballerina/runtime/api/values/BObject' (current frame, stack[0]) is not assignable to '$value$Foo'
  Current Frame:
    bci: @183
    flags: { }
    locals: { '$value$Foo', 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', integer, 'io/ballerina/runtime/internal/values/MapValue', 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', '$value$Foo', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/api/values/BObject', 'java/lang/Object', integer }
    stack: { 'io/ballerina/runtime/api/values/BObject', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/MapValue' }
  Bytecode:
    0000000: 2bb4 0013 9900 07b8 0019 bf01 3a04 013a
    0000010: 0501 3a06 013a 0701 3a08 013a 0901 3a0a
    0000020: 0336 0b2b b400 1d9d 00a6 150b ab00 0000
    0000030: 0000 00d9 0000 0003 0000 0000 0000 0024
    0000040: 0000 0001 0000 0091 0000 0002 0000 0099
    0000050: 1100 0036 0bbb 005f 59bb 0061 59b2 0067
    0000060: 03b7 006a 1000 bd00 5db7 006d 3a05 1905
    0000070: 2b14 0024 88bd 006f b900 7503 003a 0619
    0000080: 06c0 005d 3a04 2a3a 07b2 007b 3a08 1904
    0000090: 1908 1907 b800 81b2 007b 3a08 1904 c000
    00000a0: 5d19 08b9 0084 0200 c000 073a 09b2 0087
    00000b0: 3a08 1909 1908 2cb7 008b 013a 0a11 0001
    00000c0: 360b a700 0311 0002 360b 190a b02b 59b4
    00000d0: 001d 0464 b500 1d2b b400 39b6 003f c000
    00000e0: 8d59 b400 8e3a 0a59 b400 8f4d 59b4 0090
    00000f0: 3e59 b400 933a 0459 b400 963a 08b4 0097
    0000100: 360b a7ff 28bb 008d 59b7 0098 5919 0ab5
    0000110: 008e 592c b500 8f59 1db5 0090 5919 04b5
    0000120: 0093 5919 08b5 0096 5915 0bb5 0097 3a0d
    0000130: 2bb4 0039 190d b600 5657 2b59 b400 1d04
    0000140: 60b5 001d 190a b0                      
  Stackmap Table:
    same_frame(@11)
    full_frame(@42,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Null,Null,Null,Object[#154],Null,Object[#35],Integer},{})
    same_frame(@80)
    full_frame(@189,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Object[#95],Object[#35],Object[#3],Object[#154],Object[#7],Object[#35],Integer},{})
    same_frame(@197)
    full_frame(@205,{Object[#3],Object[#15],Object[#93],Integer,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@261,{Object[#3],Object[#15],Object[#93],Integer,Object[#93],Null,Null,Null,Object[#154],Null,Object[#35],Integer},{})

	at t3.main(t3.bal:5)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:829)
 
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Related to the PR only
