### ISSUE TITLE
Runtime crash for expression function inside object actor

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#36301]
**Description:**

```Ballerina
public function main() {
    int i = 10;     // Unused variable
    Foo foo = object {
        function foo() returns int {
            function () returns int xx = () => i;   // Runtime crash.
            return xx();
        }
    };
    panic error(foo.foo().toString());
}

type Foo object {
    function foo() returns int;
};
```

```LogTalk
[2022-05-24 14:23:27,385] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at $value$$anonType$_0.call(t1.bal)
	at t1.main(t1.bal:9)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Internal APIs created and desugared code may look like below 
```Ballerina
var foo = object {
        int j = i;

        function getI() returns int {
            int p = 300; // will be added to $paramMap
            map<any> getMapValue = <map<any>>__internal:getClosureMap(self);
            return <int>getMapValue["i"] + <int>getMapValue["k"] + p; // p will be accessed via closure map in function body
        }
    };
__internal:loadClosureMap(foo, mm); // setClosureMap
__internal:printClosureMap(foo);
```

**Comment by KRVPerera** [comment]
There is an existing bug for object ctor trying to incorporate it to normal flow. Fixing this along with this PR
```Ballerina
import ballerina/io;

function TestFuncA(int k) returns int {
    final int p1 = 100;
    var foo =
        function(int k2) returns int { // lambda_0
            var foo = object {
                int _p1 = p1;
                int _k = k;
            };
            io:println("#### values inside object ctor START ####");
            io:println(foo._p1);
            io:println(foo._k);
            io:println(k);
            io:println(k2);
            io:println("#### values inside object ctor END ####");
            return foo._p1 + foo._k + k + k2; // 100 + 100 + 100 + 100 ==> 400
        };



    var objectResult = foo(100);
    int res = objectResult;
    io:println("------ final results ------");
    io:println(objectResult);
    return res;
}

public function main() {
    int k = 100;
    int x = TestFuncA(k);
    io:println(x);
}
```

```
#### values inside object ctor START ####
0
0
100
100
#### values inside object ctor END ####
------ final results ------
200
200
```

**Comment by KRVPerera** [comment]
Will be merging few changes to ClosureDesugar taken from the branch [closures-for-default-values](https://github.com/ballerina-platform/ballerina-lang/tree/closures-for-default-values)


https://github.com/ballerina-platform/ballerina-lang/compare/master...closures-for-default-values#diff-7c71f66d9ff2b8ca170333cd7ee5f3456d84e3d4341a112f97aa323d3037315c

**Comment by KRVPerera** [comment]
### Information

On Going Pr: https://github.com/ballerina-platform/ballerina-lang/pull/36667

### Internal APIs (from Same PR)
https://github.com/KRVPerera/OfficeWork/tree/main/Closures/new_approach/objects/internalAPIS
