### ISSUE TITLE
`BallerinaErrorHandler` reaching fail-safe for incomplete code sample

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#36385]
**Description:**

Below sample is reaching fail-safe  in `BallerinaErrorHandler`
```bal
var x = from var a in m = {
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
Exception in thread "main" java.lang.AssertionError: fail safe reached
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:115)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:111)
	at io.ballerina.compiler.internal.parser.BallerinaParser.recover(BallerinaParser.java:19067)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseIntermediateClause(BallerinaParser.java:11932)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseQueryExprRhs(BallerinaParser.java:11809)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTableConstructorOrQueryInternal(BallerinaParser.java:11726)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTableConstructorOrQuery(BallerinaParser.java:11716)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5134)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5065)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5059)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5037)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5032)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5027)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4958)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseVarDeclRhs(BallerinaParser.java:4628)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseVariableDecl(BallerinaParser.java:4567)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseModuleVarDecl(BallerinaParser.java:1084)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1038)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:984)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:499)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:431)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:335)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:100)
	at io.ballerinalang.compiler.parser.test.TestParser.testParser(TestParser.java:46)
	at io.ballerinalang.compiler.parser.test.TestParser.main(TestParser.java:40)
```
</details>

**Comment by SandaruJayawardana** [comment]
We can enable commented test in https://github.com/ballerina-platform/ballerina-lang/pull/36304#pullrequestreview-999914414 after fixing this issue.

**Comment by lochana-chathura** [comment]
Added to `2201.1.x` with #36489
