### ISSUE TITLE
CCE in desugar with rest argument of a type reference type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#36504]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo [int, string...];

public function main() {
    Foo f = [1];
    fn(...f);
}

function fn(int a, string... b) {
}
```

```
[2022-06-10 16:03:01,220] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderNamedArgs(Desugar.java:8869)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderArguments(Desugar.java:8617)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6474)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6420)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8459)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3472)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8434)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8472)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8478)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1350)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8434)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1392)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8434)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8485)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:801)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8434)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:456)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:447)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
2201.1.0

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35733

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36505.
