### ISSUE TITLE
NPE when attempting to return finite type with multiple values in value space  from a function marked as `public`

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#36685]
**Description:**
$title 

**Steps to reproduce:**
```
type testType 3|-4;
public function main() {
    testType val = foo();
}

public function foo() returns 3|-4 {
    testType val = 3;
    return val;
}
```

> java.lang.NullPointerException
> 	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:44)
> 	at org.wso2.ballerinalang.compiler.diagnostic.DiagnosticComparator.compare(DiagnosticComparator.java:38)
> 	at java.base/java.util.TreeMap.compare(TreeMap.java:1292)
> 	at java.base/java.util.TreeMap.put(TreeMap.java:536)
> 	at java.base/java.util.TreeSet.add(TreeSet.java:255)
> 	at org.wso2.ballerinalang.compiler.tree.BLangPackage.addDiagnostic(BLangPackage.java:291)
> 	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.storeDiagnosticInModule(BLangDiagnosticLog.java:290)
> 	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:257)
> 	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:230)
> 	at org.wso2.ballerinalang.compiler.diagnostic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:102)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:1683)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExportableTypeRef(CodeAnalyzer.java:1606)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:439)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:275)
> 	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
> 	at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:198)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:344)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:333)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:321)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:275)
> 	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
> 	at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:198)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:309)
> 	at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:196)
> 	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:119)
> 	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:427)
> 	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
> 	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:376)
> 	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:198)
> 	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:183)
> 	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
> 	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
> 	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:232)
> 	at io.ballerina.projects.Package.getCompilation(Package.java:147)
> 	at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
> 	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:95)
> 	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
> 	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:202)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at io.ballerina.cli.launcher.Main.main(Main.java:51)
>

**Comment by MaryamZi** [comment]
Doesn't crash on Swan Lake Update 2 and Update 3 RCs. Keeping the issue open to add tests.
