### ISSUE TITLE
Do-on fail causes program to crash with `ClassFormatError`

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#36817]
**Description:**

Use the below code to reproduce the issue.

```ballerina
import ballerina/http;

service /test on new http:Listener(9090) {
    resource function get packages() returns string {
        do {
            string[] packages = [];
            return "packages";
        } on fail var e {
            return e.toString();
        }
    }
}

```

Output:

```
bal run service.bal
Compiling source
        service.bal
WARNING [service.bal:(6:13,6:36)] unused variable 'packages'

Running executable

[2022-07-01 15:16:41,052] SEVERE {b7a.log.crash} - Invalid length 65528 in LocalVariableTable in class file $value$$anonType$_0 
java.lang.ClassFormatError: Invalid length 65528 in LocalVariableTable in class file $value$$anonType$_0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at $$$.$gen$$0046$0046$0060init$00620(.:3)
        at $_init.$gen$$0046$0060init$0062(.:0)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
The issue happens due to an unnecessary basic block created, when there are no `fail` statements provided inside the `do` block. 

At desugaring phase, we remove the `on-fail` clause if there are no `fail` statements provided inside the `do` block. 
So, the function is expected to behave similarly to a function that does not have a `do-fail` block.
The following functions are expected to execute similarly.
```ballerina
function testFuncWithDoFail() returns string? {
    do {
        int a = 8;
    } on fail var e {
        panic error(e.toString());
    }
}

function testFunc() returns string? {
       int a = 8;
}
```

But the BIR representations of these functions are slightly different.
```
testFuncWithDoFail function() -> string|() {
    %0(RETURN) string|();
    %1(LOCAL) int;

    bb0 {
        %1 = ConstLoad 8;
        GOTO bb1;
    }
    bb1 {
        %0 = ConstLoad 0;
        GOTO bb2;
    }
    bb2 {
        return;
    }
}

testFunc function() -> string|() {
    %0(RETURN) string|();
    %1(LOCAL) int;

    bb0 {
        %1 = ConstLoad 8;
        %0 = ConstLoad 0;
        GOTO bb1;
    }
    bb1 {
        return;
    }
}
```
The function with `do-fail` contains an additional basic block.
This happens due to the `do` block still passes the `breakable` state to the BIR generation, even though the `fail` block is omitted.
https://github.com/ballerina-platform/ballerina-lang/blob/31e1d2c7b78e23ab880f16650ac74a11dcc0c89b/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java#L922

**Comment by HindujaB** [comment]
Since the fix needs to be done from `compilerFE`, removing `jBallerina` tag. 
Please re-add if there is any fix needed from the runtime code base.
