### ISSUE TITLE
`ModuleExecutionFlowTests.testMultipleDynamicListenersWithAsyncCall` test failing intermittently giving `ConcurrentModificationException`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#36820]
**Description:**

`ModuleExecutionFlowTests.testMultipleDynamicListenersWithAsyncCall` test failing intermittently giving
```
2022-07-01T09:52:06.3368769Z jBallerina-Test-Suite > ballerina-packerina-tests > org.ballerinalang.test.packaging.ModuleExecutionFlowTests > testMultipleDynamicListenersWithAsyncCall STANDARD_ERROR
2022-07-01T09:52:06.3369613Z     [2022-07-01 09:51:58,906] INFO {ModuleExecutionFlowTests} - [1mtestMultipleDynamicListenersWithAsyncCall: [34m[1mRUNNING[0m 
2022-07-01T09:52:06.3393419Z     [2022-07-01 09:52:01,743] INFO {org.ballerinalang.test.context.ServerLogReader} - Compiling source 
2022-07-01T09:52:06.3394129Z     [2022-07-01 09:52:01,761] INFO {org.ballerinalang.test.context.ServerLogReader} - 	testorg/dynamic_listener_async_call_test_project:0.1.0 
2022-07-01T09:52:06.3394750Z     [2022-07-01 09:52:04,353] INFO {org.ballerinalang.test.context.ServerLogReader} -  
2022-07-01T09:52:06.3395359Z     [2022-07-01 09:52:04,354] INFO {org.ballerinalang.test.context.ServerLogReader} - Generating executable 
2022-07-01T09:52:06.3396403Z     [2022-07-01 09:52:05,366] INFO {org.ballerinalang.test.context.ServerLogReader} - 	/home/runner/work/ballerina-lang/ballerina-lang/tests/jballerina-integration-test/src/test/resources/packaging/dynamic_listener_async_call_test_project/target/bin/dynamic_listener_async_call_test_project.jar 
2022-07-01T09:52:06.3397292Z     [2022-07-01 09:52:05,446] INFO {org.ballerinalang.test.context.BServerInstance} - Starting Ballerina server.. 
2022-07-01T09:52:06.3397938Z     [2022-07-01 09:52:05,451] INFO {org.ballerinalang.test.context.BServerInstance} - Waiting for port 7008 to open 
2022-07-01T09:52:06.3398602Z     [2022-07-01 09:52:06,048] SEVERE {org.ballerinalang.test.context.ServerLogReader} - ******************************************************* 
2022-07-01T09:52:06.3399423Z     [2022-07-01 09:52:06,078] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Initializing Ballerina server agent with arguments - host=localhost,port=7008,exitStatus=1,timeout=15000,killStatus=5 
2022-07-01T09:52:06.3400279Z     [2022-07-01 09:52:06,079] SEVERE {org.ballerinalang.test.context.ServerLogReader} - ******************************************************* 
2022-07-01T09:52:06.3401002Z     [2022-07-01 09:52:06,148] SEVERE {org.ballerinalang.test.context.ServerLogReader} - timeout - 15000 exitStatus - 1 killStatus - 5 host - localhost port - 7008 
2022-07-01T09:52:07.9237457Z     [2022-07-01 09:52:07,833] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Starting Ballerina agent on host - localhost, port - 7008 
2022-07-01T09:52:07.9239142Z     [2022-07-01 09:52:07,833] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Ballerina agent started on host - localhost, port - 7008 
2022-07-01T09:52:09.5237214Z     [2022-07-01 09:52:09,455] INFO {org.ballerinalang.test.context.BServerInstance} - Server Started Successfully. 
2022-07-01T09:52:09.5238803Z     [2022-07-01 09:52:09,456] INFO {org.ballerinalang.test.context.BServerInstance} - Stopping server.. 
2022-07-01T09:52:09.8237844Z     [2022-07-01 09:52:09,762] INFO {org.ballerinalang.test.context.BServerInstance} - Server Stopped Successfully 
2022-07-01T09:52:09.8239425Z     [2022-07-01 09:52:09,765] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Shutting down Ballerina server with agent port - 7008 
2022-07-01T09:52:09.8327226Z     [2022-07-01 09:52:09,770] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Starting Ballerina agent on host - localhost, port - 7008 
2022-07-01T09:52:09.8328038Z     [2022-07-01 09:52:09,784] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Ballerina agent started on host - localhost, port - 7008 
2022-07-01T09:52:11.9238126Z     [2022-07-01 09:52:11,826] SEVERE {org.ballerinalang.test.context.ServerLogReader} - Error initializing agent server, error - Address already in use 
2022-07-01T09:52:12.0239385Z     [2022-07-01 09:52:11,926] SEVERE {org.ballerinalang.test.context.ServerLogReader} - [2022-07-01 09:52:11,852] SEVERE {b7a.log.crash} - null  
2022-07-01T09:52:12.0240973Z     [2022-07-01 09:52:11,926] SEVERE {org.ballerinalang.test.context.ServerLogReader} - java.util.ConcurrentModificationException 
2022-07-01T09:52:12.0242081Z     [2022-07-01 09:52:11,926] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511) 
2022-07-01T09:52:12.0289867Z     [2022-07-01 09:52:11,926] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534) 
2022-07-01T09:52:12.0292461Z     [2022-07-01 09:52:11,926] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.RuntimeRegistry.invokeListenerGracefulStop(RuntimeRegistry.java:78) 
2022-07-01T09:52:12.0294256Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.RuntimeRegistry$ListenerCallback.notifySuccess(RuntimeRegistry.java:115) 
2022-07-01T09:52:12.0295567Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.Scheduler.postProcess(Scheduler.java:388) 
2022-07-01T09:52:12.0296648Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:337) 
2022-07-01T09:52:12.0297683Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:288) 
2022-07-01T09:52:12.0298759Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at io.ballerina.runtime.internal.scheduling.Scheduler.start(Scheduler.java:275) 
2022-07-01T09:52:12.0299817Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at testorg.dynamic_listener_async_call_test_project.0.$_init.$moduleStop(dynamic_listener_async_call_test_project) 
2022-07-01T09:52:12.0300863Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 	at testorg.dynamic_listener_async_call_test_project.0.$_init$SignalListener.run(Unknown Source) 
2022-07-01T09:52:12.0302817Z     [2022-07-01 09:52:11,927] SEVERE {org.ballerinalang.test.context.ServerLogReader} -   
2022-07-01T09:52:19.9236293Z 
2022-07-01T09:52:19.9237687Z jBallerina-Test-Suite > ballerina-packerina-tests > org.ballerinalang.test.packaging.ModuleExecutionFlowTests > testMultipleDynamicListenersWithAsyncCall FAILED
2022-07-01T09:52:19.9238913Z     org.ballerinalang.test.context.BallerinaTestException: Timeout expired waiting for matching log: Stopped module A
2022-07-01T09:52:19.9239557Z         at org.ballerinalang.test.context.LogLeecher.waitForText(LogLeecher.java:103)
2022-07-01T09:52:19.9240463Z         at org.ballerinalang.test.packaging.ModuleExecutionFlowTests.runAssertDynamicListener(ModuleExecutionFlowTests.java:130)
2022-07-01T09:52:19.9241647Z         at org.ballerinalang.test.packaging.ModuleExecutionFlowTests.testMultipleDynamicListenersWithAsyncCall(ModuleExecutionFlowTests.java:120)
2022-07-01T09:52:19.9242254Z 
2022-07-01T09:52:19.9243035Z jBallerina-Test-Suite > ballerina-packerina-tests > org.ballerinalang.test.packaging.ModuleExecutionFlowTests STANDARD_ERROR
2022-07-01T09:52:19.9244851Z     [2022-07-01 09:52:19,780] SEVERE {org.ballerinalang.test.packaging.ModuleExecutionFlowTests} - [1mtestMultipleDynamicListenersWithAsyncCall: [31m[1mFAILED -> Timeout expired waiting for matching log: Stopped module A[0m 
```
**Steps to reproduce:**
https://github.com/ballerina-platform/ballerina-lang/runs/7147524496?check_suite_focus=true

**Affected Versions:**
`2201.2.x` branch

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gabilang** [comment]
PR has been merged. Hence closing this.
