### ISSUE TITLE
Compile time error when matching on a recursive type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36852]
```ballerina
public type Type ["list", Type[]]|"int";

function g() {
    Type x =  ["list", ["int"]];
    match x {
        "int" => {
            io:println(x);
        }
        ["list", var y] => {
            io:println(y);
        }
    }
}
```

Give compile time error:
```
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:613)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangIndexBasedAccess.accept(BLangIndexBasedAccess.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1707)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1211)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1582)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1270)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1563)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1270)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1563)
 ```

**Comment by SasinduDilshara** [comment]
This works fine.

```
import ballerina/io;

public type Type [Type]|string;

public function main() {
    Type x = ["list"];
    match x {
        ["list"] => {
            io:println(1); // 1
        }
    }
}
```

**Comment by lochana-chathura** [comment]
Related issue: #37136
