### ISSUE TITLE
[Intermittent] Requests failed when sending continuous request for a long period

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3689]
Observed the following NullPointer exception while sending HTTP requests for around an hour. This happens rarely. When this happens the request fails. 

```
WARN  {io.netty.util.concurrent.AbstractEventExecutor} - A task raised an exception. Task: org.wso2.carbon.transport.http.netty.contractimpl.HttpResponseListener$$Lambda$201/2139631335@48be83e2 
java.lang.NullPointerException: msg
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:710)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpResponseListener.lambda$onMessage$21(HttpResponseListener.java:84)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
 
[2017-10-19 11:49:44,281] ERROR {org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel} - Failed to send the request 
java.lang.NullPointerException: msg
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:710)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1026)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel.writeContent(TargetChannel.java:171)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpClientConnectorImpl$1.operationComplete(HttpClientConnectorImpl.java:91)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpClientConnectorImpl$1.operationComplete(HttpClientConnectorImpl.java:80)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
 
[2017-10-19 11:49:44,282] ERROR {org.ballerinalang.net.http.actions.AbstractHTTPAction} - non-blocking action invocation validation failed.  
org.ballerinalang.connector.api.BallerinaConnectorException: org.wso2.carbon.messaging.exceptions.MessagingException: Failed to send the request
	at org.ballerinalang.net.http.actions.AbstractHTTPAction$HTTPClientConnectorLister.onMessage(AbstractHTTPAction.java:182)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpResponseFutureImpl.notifyHttpListener(HttpResponseFutureImpl.java:58)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel.writeContent(TargetChannel.java:186)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpClientConnectorImpl$1.operationComplete(HttpClientConnectorImpl.java:91)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpClientConnectorImpl$1.operationComplete(HttpClientConnectorImpl.java:80)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.messaging.exceptions.MessagingException: Failed to send the request
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel.writeContent(TargetChannel.java:184)
	... 12 more
Caused by: java.lang.NullPointerException: msg
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:710)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1026)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel.writeContent(TargetChannel.java:171)
	... 12 more
```

**Comment by irunika** [comment]
This test is not valid with latest changes. This is already captured with https://github.com/ballerina-platform/ballerina-lang/issues/6896
