### ISSUE TITLE
Server hangs while sending messages continuosly

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3690]
I ran the following test for few hours and ballerina server became unresponsive and stopped responding.

  | Payload Size | TPS
-- | -- | --
HTTP Payloads | 1K | 15
  | 5K | 10
  | 10K | 7
  | 100K | 5
  | 500K | 2
  |   |  
  | Response Time |  
Slow Backends | 10s | 3
  | 7s | 4
  | 4s | 6

Observed the following in the thread dump which was taken at the time of issue.

```
"nioEventLoopGroup-3-6" #34 prio=10 os_prio=0 tid=0x00007f92fc005800 nid=0x203 waiting on condition [0x00007f92e8ffb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c74759e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at org.wso2.carbon.transport.http.netty.message.BlockingEntityCollector.getFullMessageLength(BlockingEntityCollector.java:189)
	at org.wso2.carbon.transport.http.netty.message.HTTPCarbonMessage.getFullMessageLength(HTTPCarbonMessage.java:94)
	at org.wso2.carbon.transport.http.netty.common.Util.setupTransferEncodingForResponse(Util.java:188)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpResponseListener.lambda$onMessage$21(HttpResponseListener.java:54)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpResponseListener$$Lambda$201/2139631335.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```

**Comment by riyafa** [comment]
There was a performance test done on Ballerina server and this issue has not been encountered in the process. Hence closing the issue. Please reopen if it reappears.
