### ISSUE TITLE
Compile time error when indexing into a tuple with rest

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36911]
```ballerina
import ballerina/io;
public type IntArr [int...];
public function main() {
    IntArr x = [1, 2];
    foreach var i in 0 ..< x.length() {
        io:println(x[i]);
    }
}
```

```
org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BTupleType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkTupleIndexBasedAccess(TypeChecker.java:8130)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkListIndexBasedAccess(TypeChecker.java:8097)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkIndexAccessExpr(TypeChecker.java:7891)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2901)
```

**Comment by SasinduDilshara** [comment]
I will work on this.

**Comment by SasinduDilshara** [comment]
This happen when accessing a member on a type reference type for a tuple type using a variable expression.

```
public type IntArr [int...];
public function main() {
    int i = 0;
    IntArr x = [1, 2];
    io:println(x[0]); //No error, Expected Behaviour
    io:println(x[i]); // Compile time error
}
```
