### ISSUE TITLE
got a bad/sad error with a program with an http service and a graphql service

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-lang#37086]
```
import ballerina/graphql;
import ballerina/http;

type OpenLibBooks record {
    int numFound;
    record {
        string[] author_name;
        string[] isbn;
    }[] docs;
};

type GoogleBookInfo record {
    int totalItems;
    string kind;
    record {
        record {
            string country;
            boolean isEbook;
            string saleability;
        } saleInfo;
        string kind;
        record {
            record {
                string identifier;
                string 'type;
            }[] industryIdentifiers;
            int pageCount;
            string printType;
            record {
                boolean image;
                boolean text;
            } readingModes;
            string previewLink;
            string canonicalVolumeLink;
            string language;
            string title;
            string subtitle;
            string publishedDate;
            string maturityRating;
            boolean allowAnonLogging;
            string contentVersion;
            string[] authors;
            string infoLink;
        } volumeInfo;
        string etag;
        string id;
        record {
            string accessViewStatus;
            string country;
            string viewability;
            record {
                boolean isAvailable;
            } pdf;
            string webReaderLink;
            record {
                boolean isAvailable;
            } epub;
            boolean publicDomain;
            boolean quoteSharingAllowed;
            boolean embeddable;
            string textToSpeechPermission;
        } accessInfo;
        string selfLink;
    }[] items;
};

type BookInfo record {|
    string[] authors;
    string isbn;
    string kind;
|};

map<GoogleBookInfo> books = {};

listener http:Listener hl = check new(9090);
# A service representing a network-accessible API
# bound to port `9090`.
service / on hl {
    resource function get search(string author) returns BookInfo|error {
        http:Client openLib = check new ("https://openlibrary.org");
        OpenLibBooks oinfo = check openLib->get(string `/search.json?q=${author}`);

        // get the first book returned and get its first ISBN numer
        if oinfo.numFound > 0 {
            string isbn = oinfo.docs[0].isbn[0];

            http:Client googleBooks = check new ("https://www.googleapis.com/books/v1");
            GoogleBookInfo ginfo = check googleBooks->get(string `/volumes?q=isbn:${isbn}`);
            books[isbn] = ginfo;

            BookInfo bi = {
                authors: oinfo.docs[0].author_name,
                isbn: isbn,
                kind: ginfo.items[0].kind
            };
            return bi;
        }

        return error("no books found");
    }
}

listener graphql:Listener gl = check new(hl);

service /graphQL on gl {
    resource function get book(string isbn) returns GoogleBookInfo? {
        return books[isbn];
    }
}
```

Error:
```
[2022-07-20 14:11:42,359] SEVERE {b7a.log.crash} - Failed to write library: /config/workspace/target/cache/sanjiva/simplebookinfo/0.1.0/java11/sanjiva-simplebookinfo-0.1.0.jar 
java.lang.RuntimeException: Failed to write library: /config/workspace/target/cache/sanjiva/simplebookinfo/0.1.0/java11/sanjiva-simplebookinfo-0.1.0.jar
        at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:117)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:316)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:252)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
Caused by: java.io.FileNotFoundException: /config/workspace/target/cache/sanjiva/simplebookinfo/0.1.0/java11/sanjiva-simplebookinfo-0.1.0.jar (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2451)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3325)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3289)
        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3272)
        at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:114)
        ... 15 more
```

**Comment by sanjiva** [comment]
More info:
```
sanjiva@choreo-editor-636f51b9-6dbf-451d-a58f-bc2f0bcf3d78:~/workspace$ bal clean
Successfully deleted '/config/workspace/target'.
sanjiva@choreo-editor-636f51b9-6dbf-451d-a58f-bc2f0bcf3d78:~/workspace$ ls
Ballerina.toml  Cloud.toml  Dependencies.toml  README.md  service.bal  target
sanjiva@choreo-editor-636f51b9-6dbf-451d-a58f-bc2f0bcf3d78:~/workspace$ ls target
cache
sanjiva@choreo-editor-636f51b9-6dbf-451d-a58f-bc2f0bcf3d78:~/workspace$ ls target/cache/sanjiva/simplebookinfo/0.1.0/java11/sanjiva-simplebookinfo-0.1.0.jar 
target/cache/sanjiva/simplebookinfo/0.1.0/java11/sanjiva-simplebookinfo-0.1.0.jar
sanjiva@choreo-editor-636f51b9-6dbf-451d-a58f-bc2f0bcf3d78:~/workspace$ 
```

Its not deleting the target directory.
