### ISSUE TITLE
Getting a Bad sad error when building the WebSocket module after updating the dependencies

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#37107]
**Description:**
Compiling ballerina module after updating the lang version and the dependent versions compatible with the latest lang gives a Bad sad error.

**Steps to reproduce:**
Fails for this dependency update PR,
https://github.com/ballerina-platform/module-ballerina-websocket/pull/697/files

Delete the `Dependancies.toml` files and run the gradle build with tests.

The following logs were printed :
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-07-22 16:37:40,640] SEVERE {b7a.log.crash} - No value present 
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:382)
        at io.ballerina.projects.JarResolver.addPlatformLibraryPaths(JarResolver.java:150)
        at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:87)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:83)
        at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForTestExecution(JarResolver.java:174)
        at org.ballerinalang.testerina.core.TestProcessor.generateTestSuite(TestProcessor.java:162)
        at org.ballerinalang.testerina.core.TestProcessor.testSuite(TestProcessor.java:118)
        at io.ballerina.cli.task.RunTestsTask.execute(RunTestsTask.java:207)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:281)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by Ibaqu** [comment]
This issue occurs due to a bug in the JarResolver.addPlatformLibrary paths which considers an incomplete jarLibrary and a complete one as [equal](https://github.com/ballerina-platform/ballerina-lang/blob/2201.2.0-stage/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java#L147). ie. A jarLibrary with `groupId`, `artifactId` and `version` as null is considered equal to the same complete jarLibrary as the `path` value to the jar is the same. 

As this check passes, attempting to [get](https://github.com/ballerina-platform/ballerina-lang/blob/2201.2.0-stage/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java#L150) the `version` value from this incomplete jarLibrary causes the `NoSuchElementException` at ` new ComparableVersion(existingEntry.version().orElseThrow());`

**Comment by azinneera** [comment]
@Ibaqu can you mention the entry that results in the error?

**Comment by Ibaqu** [comment]
The entry that causes the issue is mime-native in this case. 

```
 "platformDependencies": [
    {
      "path": "platform/java11/mime-native-2.4.0-20220720-115500-9fe8dcf.jar"
    },
    {
```

Only the path is given under package.json. This will have to be updated to include the relevant version.

**Comment by azinneera** [comment]
@Bhashinee we did an improvement to handle platform library conflicts and we agreed to add the groupId, artifactId and the version to the platform libraries that are reused (See https://github.com/ballerina-platform/ballerina-lang/issues/32666#issuecomment-1162799632). The related issue in stdlib can be found at https://github.com/ballerina-platform/ballerina-standard-library/issues/3117. So we need to update all the standard libraries to properly resolve the issue.

**Comment by Bhashinee** [comment]
@azinneera we have already updated the dependencies as in the comment in this PR. 
https://github.com/ballerina-platform/module-ballerina-websocket/pull/697/files

Have I missed anything?

**Comment by azinneera** [comment]
This 

> @azinneera we have already updated the dependencies as in the comment in this PR. https://github.com/ballerina-platform/module-ballerina-websocket/pull/697/files
> 
> Have I missed anything?

All packages having the mime-native jar as a platform library should be updated. We should start with `ballerina/mime`.

**Comment by azinneera** [comment]
@niveathika lLoks like we have missed some libraries. I can see the same for `io` and `os` packages for `io-native` library.

ballerina/io: https://github.com/ballerina-platform/module-ballerina-io/blob/1c280aa34553fbcfafd64cc9880f51efab39d9b4/ballerina/Ballerina.toml#L12-L14
```toml
[[platform.java11.dependency]]
path = "../native/build/libs/os-native-1.4.0-SNAPSHOT.jar"
```

ballerina/os: https://github.com/ballerina-platform/module-ballerina-os/blob/b07e48b2bcd52e207c6fed77d0fc5bc1dc5449d1/ballerina/Ballerina.toml#L15-L19
```toml
[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
version = "1.3.0"
path = "./lib/io-native-1.3.0-20220720-110800-3bbc805.jar"
```
