### ISSUE TITLE
CCE in implement method code action

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37100]
**Description:**
Consider the following screen capture.
![Peek 2022-07-22 11-09](https://user-images.githubusercontent.com/35211477/180370751-7d823e52-bbc5-4877-9e7a-5e85e51b002d.gif)

stack trace
```
Error - 11:09:18 am] CodeAction 'ImplementMethodCodeAction' failed! {, error: 'class java.lang.String cannot be cast to class io.ballerina.compiler.api.symbols.TypeSymbol (java.lang.String is in module java.base of loader 'bootstrap'; io.ballerina.compiler.api.symbols.TypeSymbol is in unnamed module of loader 'app')'}
java.lang.ClassCastException: class java.lang.String cannot be cast to class io.ballerina.compiler.api.symbols.TypeSymbol (java.lang.String is in module java.base of loader 'bootstrap'; io.ballerina.compiler.api.symbols.TypeSymbol is in unnamed module of loader 'app')
	at org.ballerinalang.langserver.codeaction.providers.AbstractImplementMethodCodeAction.getDiagBasedTextEdits(AbstractImplementMethodCodeAction.java:93)
	at org.ballerinalang.langserver.codeaction.providers.ImplementMethodCodeAction.getCodeActions(ImplementMethodCodeAction.java:58)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:123)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:110)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:167)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:332)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```

**Steps to reproduce:**
```Ballerina
public client class Client {
    public string url;

    public function init(string url) {
        self.url = url;
    }

    resource function post path2/[string id]/path4(string str, int a) returns string {
        return "";
    }

}


public function test() {
    Client cl = new ("");
    string a  = cl-> /path2/[""]/path4.post()
}

```
**Affected Versions:**
2201.2.x
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment]
Closing this issue as this was fixed with #37105
