### ISSUE TITLE
Crash on basic service template

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [ballerina-platform/ballerina-lang#37236]
Because #37180 has not received any response, I decided to re-install the OS and Ballerina.
1. Clean installed and updated Rocky Linux
2. Installed OpenJDK 17 with `sudo dnf install java-17-openjdk`, set JAVA_HOME environment variable
3. Installed Ballerina from ZIP
    1. Downloaded and unzipped
    2. Put extracted director in /usr/lib64/
    3. Created symlink to /usr/bin/ with `ln -s /usr/lib64/ballerina/bin/bal /usr/bin`
4. Tested the installation
```
bal --version
Ballerina 2201.1.1 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.9
```

Afterwards, following the page [Write a RESTful API with Ballerina](https://ballerina.io/learn/write-a-restful-api-with-ballerina/) I have created the default service template

```
bal new testService -t service
```

Then tested is the default template would run

```
bal run
Compiling source
	myuser/testService:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 09:56:39,859] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:750)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:604)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.constants.JvmUnionTypeConstantsGen.add(JvmUnionTypeConstantsGen.java:94)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmConstantsGen.getTypeConstantsVar(JvmConstantsGen.java:111)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:438)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadIntersectionType(JvmTypeGen.java:791)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:442)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.createField(JvmCreateTypeGen.java:645)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.splitAddFields(JvmCreateTypeGen.java:607)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.types.JvmRecordTypeGen.addRecordFields(JvmRecordTypeGen.java:121)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.types.JvmRecordTypeGen.populateRecord(JvmRecordTypeGen.java:102)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.populateTypes(JvmCreateTypeGen.java:283)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.generateCreateTypesMethod(JvmCreateTypeGen.java:173)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.generateTypeClass(JvmCreateTypeGen.java:159)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmMethodsSplitter.generateMethods(JvmMethodsSplitter.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:808)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:309)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

If using the RPM package instead of zip, the error I get is the same as #37180

```
bal run
Compiling source
	myuser/testService:0.1.0

Running executable

ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 10:17:08,596] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: auth 
java.lang.IllegalStateException: Cannot find the generated jar library for module: auth
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$4(JBallerinaBackend.java:515)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:514)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:282)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:124)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:83)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:81)
	at io.ballerina.cli.task.RunExecutableTask.getAllClassPaths(RunExecutableTask.java:117)
	at io.ballerina.cli.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:96)
	at io.ballerina.cli.task.RunExecutableTask.execute(RunExecutableTask.java:76)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

Creating a new service, weirdly gives a similar error, but instead of being unable to find auth, it is now unable to find jwt.

```
bal run
Compiling source
	myuser/testService2:0.1.0

Running executable

ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 10:53:49,996] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: jwt 
java.lang.IllegalStateException: Cannot find the generated jar library for module: jwt
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$4(JBallerinaBackend.java:515)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:514)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:282)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:124)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:83)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:81)
	at io.ballerina.cli.task.RunExecutableTask.getAllClassPaths(RunExecutableTask.java:117)
	at io.ballerina.cli.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:96)
	at io.ballerina.cli.task.RunExecutableTask.execute(RunExecutableTask.java:76)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

```

Running TestService2 a second time, the error becomes exactly as the previous with auth

**Comment by Jeffrey-de-Bruijn** [comment]
I gave up on Ballerina.

**Comment by Jeffrey-de-Bruijn** [comment]
This problem does not seem to happen on Debian. Still don't know why, but it is a problem.

**Comment by IMS94** [comment]
Ballerina is not yet supported on Java 17. Can you try this on Java 11?

**Comment by Jeffrey-de-Bruijn** [comment]
Same problem on Java 11

I have tried on EuroLinux 9 instead of Rocky 9, with Java 17 and I am not getting the error. So it must be another dependency that isn't documented

**Comment by IMS94** [comment]
I see. @azinneera can you check this issue?

**Comment by azinneera** [comment]
The underlying issue seems to be from the Code generation. In the first try, the jar creation fails but the BIR has been created. Project API assumes that if the BIR and jar creation is an atomic operation and so during the second run, the jar is expected to be there. Failing to find the jar has caused the issue. Cleaning the `~/.ballerina/repositories/central.ballerina.io/cache-2201.1.1` should reproduce the first strackstace. Looping in @warunalakshitha for more analysis on the code generation side.

**Comment by warunalakshitha** [comment]
We will check the code generation error.
