### ISSUE TITLE
Class cast exception for nested query action

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#37300]
**Description:**
```ballerina
public type Point record {|anydata...;|};

public type Feature record {|Point location;|};

Feature[] FEATURES = [];

client class Service {
    remote function RecordRoute(stream<Point, error?> pointStream) returns error? {
        check from var point in pointStream
            do {
                check from Feature feature in FEATURES
                    do {
                        Point streamPoint = point;
                    };
            };
    }
}
```

stacktrace
```
Running executable

[2022-08-08 14:15:39,579] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.StreamValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.StreamValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.StreamValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.StreamValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app')
        at $value$Service.call(test.bal)
        at test.main(test.bal:58)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Steps to reproduce:**

**Affected Versions:**
2201.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharushiJay** [comment]
Closing since this cannot be reproduced in master.
