### ISSUE TITLE
Compiler crashes when an XML filter expression uses an import prefix instead of an XMLNS prefix in the XML atomic name pattern

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#37359]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/lang.'int as foo;

public function main() {
    xml x = xml`foo`;
    xml _ = x.<foo:doc>; // no compilation error

    foo:Signed8 _ = 1;
}
```

Crashes with

```cmd
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BXMLNSSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BPackageSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BXMLNSSymbol are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.expandFilters(Desugar.java:7879)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7856)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementAccess.accept(BLangXMLElementAccess.java:48)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8485)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1456)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1590)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8498)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8504)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1353)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1399)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8511)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:804)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:459)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:447)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
2201.2.0-RC

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/37357. Changes will be merged to master when merging the client declaration PR.
