### ISSUE TITLE
NPE during package compilation with cyclic imports 

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#37395]
**Description:**
`ModuleContext.moduleCompState` becomes null with the following resolution diagnostics

<img width="1164" alt="Screenshot 2022-08-15 at 21 22 24" src="https://user-images.githubusercontent.com/15815199/184671912-25638105-0c2d-4ca7-a54b-efcd5c4ccb90.png">

```
[Error - 9:24:45 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/chiran/Desktop/WSO2/nballerina/compiler/modules/front.syntax/ascii.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.projects.PackageCompilation.getSemanticModel(PackageCompilation.java:144)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:75)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:59)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:51)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:108)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:61)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:241)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:236)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:205)
	at io.ballerina.compiler.syntax.tree.ConstantDeclarationNode.accept(ConstantDeclarationNode.java:70)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:862)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$15(BallerinaTextDocumentService.java:624)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
 Adding below import statement  to `compiler/modules/front.syntax/ascii.bal` file in `nballerina`
`import nballerina.front;`

![nballerina_npe](https://user-images.githubusercontent.com/15815199/184671687-bac6b9b9-c099-4514-9bd2-90e165a78c8f.gif)

**Affected Versions:**
2201.2.0-rc2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/37419 fixes the NPE. Overall cyclic import handling improvement will be handled through https://github.com/ballerina-platform/ballerina-lang/issues/37242
