### ISSUE TITLE
NPE when cyclic import is added

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37432]
**Description:**
![image](https://user-images.githubusercontent.com/35211477/185228485-66777df5-32bb-42f6-bcb4-1ce46102a137.png)

When the  `import exchange_rates;` is added, the subsequent compilations fails with the following st

```
	[Error - 1:13:10 am] Operation 'text/codeAction' failed! {uri: '/home/malintha/Documents/wso2/experimental/projects/ballerina/other/articles/exchange_rates/modules/mod1/mod1.bal', [1:1]- [1:23], error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.projects.PackageCompilation.getSemanticModel(PackageCompilation.java:144)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:75)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:59)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:51)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:108)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:61)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:283)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:251)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:238)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getMatchedTypeSymbol(CodeActionRouter.java:139)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:73)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:167)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:332)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
Import the default module in another module.

**Affected Versions:**
2201.2.0-rc1

**Comment by malinthar** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/37395. Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/37419
