### ISSUE TITLE
Fix qualified identifiers with `client:` on the `client-declaration` branch

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#37461]
**Description:**
Branch - https://github.com/ballerina-platform/ballerina-lang/tree/client-declaration

```ballerina
client:T a = 2;
```

crashes with

```cmd
[2022-08-20 10:32:13,199] SEVERE {b7a.log.crash} - Index: '999', Size: '993' 
java.lang.IndexOutOfBoundsException: Index: '999', Size: '993'
        at io.ballerina.tools.text.LineMap.positionRangeCheck(LineMap.java:72)
        at io.ballerina.tools.text.LineMap.linePositionFrom(LineMap.java:44)
        at io.ballerina.tools.text.TextDocument.linePositionFrom(TextDocument.java:48)
        at io.ballerina.compiler.syntax.tree.Node.lineRange(Node.java:143)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.getPosition(BLangNodeBuilder.java:544)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:608)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:480)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:517)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:415)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:183)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:232)
        at io.ballerina.projects.Package.getCompilation(Package.java:148)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:255)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:114)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/37779.
