### ISSUE TITLE
NPE at `BmpStringValue.concat`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#37507]
**Description:**

$title

**Steps to reproduce:**
```bal
string[] globalArr = ["B"];

function func() {
    string a = "A";

    worker B {  
        var obj1 = object {
            function f1() returns string {
                return globalArr[0] + a;
            }
        };
        string f1 = obj1.f1();
    }
}

public function main() {
    func();
}
```
gives
```
Running executable

[2022-08-24 18:07:31,495] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.internal.values.BmpStringValue.concat(BmpStringValue.java:47)
        at $value$$anonType$_0.f1(async_issue.bal:9)
        at $value$$anonType$_0.call(async_issue.bal)
        at async_issue.$lambda$_0(async_issue.bal:12)
        at async_issue.$lambda$_0$lambda0$(async_issue.bal:6)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Affected Versions:**
Ballerina 2201.1.0 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
This one also doesn't work.
```bal
import ballerina/io;

function func() {
    string[] globalArr = ["B"];
    string a = "A";

    worker B returns string {  
        var obj1 = object {
            function f1() returns string {
                return globalArr[0] + a;
            }
        };
        string f1 = obj1.f1();
        io:println(f1);
        return f1;
    }

    string stringResult = wait B;
    io:println(stringResult);
}

public function main() {
    func();
}
```
gives
```
Running executable

error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string[]'"}
```
at `return globalArr[0] + a;`

**Comment by Nadeeshan96** [comment]
It seems both of the above errors are due to an error in the BIR. If we see the BIR of the generated function for the `worker B`
```ll
$lambda$_0 function() -> () {
    %0(RETURN) ();
    %1(SYNTHETIC) map<any|error>;
    %2(TEMP) typeDesc<any|error>;
    %4(LOCAL) $anonType$_0;
    %5(SYNTHETIC) $anonType$_0;
    %9(TEMP) ();
    %11(LOCAL) string;

    bb0 {
        %2 = newType map<any|error>;
        %1 = NewMap %2;
        %5 = new $anonType$_0;
        %9 = $init$(%5, %1) -> bb1;
    }
    bb1 {
        %4 = %5;
        %11 = f1(%4) -> bb2;
    }
    bb2 {
        %0 = ConstLoad 0;
        GOTO bb3;
    }
    bb3 {
        return;
    }


}
```
Although a new map `%1` is created and passed to the `$init$` function it is not populated with the local variables (e.g. `a`). It seems that local variables (e.g. `a`) which are used inside the object are not getting passed to the worker function also through the closure map.
