### ISSUE TITLE
Lang server throws `IllegalArgumentException`s

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#37511]
**Description:**
$title.

**Steps to reproduce:**

```ballerina
public const DEFAULT_URL = "http://www.example.com";

public type ClientConfiguration record {
    string url?;
    int 'limit;
};

public isolated client class 'client {
    public final string url;
    private int 'limit;

    public function init(*ClientConfiguration config) {
        self.url = config.url ?: DEFAULT_URL;
        <cursor>
        self.'limit = config.'limit;
    }

    remote function getLimit() returns int {
        lock {
            return self.'limit;
        }
    }

    remote function setLimit(int 'limit) {
        lock {
            self.'limit = 'limit;
        }
    }
}
```

Case 1 - Add a new line at the cursor position. 

Throws

```cmd
java.lang.IllegalArgumentException: Cannot find a line with the character offset '8'
	at io.ballerina.tools.text.LineMap.textPositionFrom(LineMap.java:54)
	at io.ballerina.tools.text.TextDocument.textPositionFrom(TextDocument.java:52)
	at org.ballerinalang.langserver.common.utils.CommonUtil.findNode(CommonUtil.java:243)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentService.lambda$syntaxTreeNode$14(BallerinaDocumentService.java:357)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Case II - Type in a character

```cmd
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:138)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:106)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:124)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:159)
	at org.ballerinalang.langserver.common.utils.NameUtil.getModifiedTypeName(NameUtil.java:213)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:204)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:181)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getSymbolCompletions(BlockNodeContextProvider.java:227)
	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getCompletions(BlockNodeContextProvider.java:95)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:48)
	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:39)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:125)
	at org.ballerinalang.langserver.completions.providers.context.VariableDeclarationNodeContext.getCompletions(VariableDeclarationNodeContext.java:67)
	at org.ballerinalang.langserver.completions.providers.context.VariableDeclarationNodeContext.getCompletions(VariableDeclarationNodeContext.java:39)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:125)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:81)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
2201.2.0-rc2

**Comment by malinthar** [comment]
I couldn't reproduce case 1. @MaryamZi could you try again
![error_reporoduce](https://user-images.githubusercontent.com/35211477/187353880-ab476178-f4a0-428f-aaa7-4cc709c9358b.gif)

**Comment by dulajdilshan** [comment]
In case 2, we are searching for `'client`, but we don't have an entry calling `'client`, But we do have an entry as `client`.

**Comment by MaryamZi** [comment]
> I couldn't reproduce case 1. @MaryamZi could you try again 

Yeah, can't seem to reproduce now. I recall it happening repeatedly though, not sure what changed.
