### ISSUE TITLE
[Bug]: NPE when tuple matched with rest pattern

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#37550]
### Description

```ballerina
import ballerina/io;
public type Data string|Data[];

public type Insn CallInsn|BranchInsn;
public type CallInsn ["call", string, Data...];
public type BranchInsn ["branch", string];

public function main() {
    f(["branch", "b.target"]);
    f(["call", "add", "1", "2"]);
}

function f (Insn d) {
    match d {
        ["call", "add", ...var operands] => {
            io:println("call add");
        }
        _ => {
            io:println("branch/call other");
        }
    }
}
```

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(Types.java:1311)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.createVarSymbol(SymbolEnter.java:4519)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.createVarSymbol(SymbolEnter.java:4513)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineVarSymbol(SymbolEnter.java:4487)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineVarSymbol(SymbolEnter.java:4480)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.resolveMatchClauseVariableTypes(SemanticAnalyzer.java:2642)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2608)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangMatchClause.accept(BLangMatchClause.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2579)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:77)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
```

### Labels

CompilerFE

**Comment by manuranga** [comment]
Also note `["call", "add", var a, var b] => ` gives a different exception, please open another issue if needed.

**Comment by SasinduDilshara** [comment]
This bug already solved in https://github.com/ballerina-platform/ballerina-lang/pull/37235.
Added tests for this scenario in https://github.com/ballerina-platform/ballerina-lang/pull/37833.

**Comment by SasinduDilshara** [comment]
> Also note `["call", "add", var a, var b] => ` gives a different exception, please open another issue if needed.

This bug is also already solved in https://github.com/ballerina-platform/ballerina-lang/pull/37235
