### ISSUE TITLE
[Bug]: `IllegalArgumentException` in `SymbolResolver` when using empty list in query expression

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#37587]
### Description

```bal
public function main() {
    int[] & readonly result = from var user in []
                                select user.cloneReadOnly();
}
```

Above code sample gives 

```
[2022-08-31 10:58:20,000] SEVERE {b7a.log.crash} - Union type '' does not have member types 
java.lang.IllegalArgumentException: Union type '' does not have member types
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupLangLibMethod(SymbolResolver.java:757)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getLangLibMethod(TypeChecker.java:6969)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInLangLib(TypeChecker.java:3738)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visitInvocation(TypeChecker.java:3309)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:3283)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:228)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:133)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:406)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:339)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.solveSelectTypeAndResolveType(TypeChecker.java:5806)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.resolveQueryType(TypeChecker.java:5758)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:5706)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:228)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangQueryExpr.accept(BLangQueryExpr.java:111)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:406)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:370)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1107)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4073)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4048)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4016)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2018)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:55)
```

### Affected Version(s)

2201.2.0-rc2

### Labels

CompilerFE

**Comment by lasinicl** [comment]
The same issue is there with `foreach` as well.
```
    foreach var item in [] {
        _ = item.cloneReadOnly();
    }
```
