### ISSUE TITLE
[Bug]: Breakpoints inside bala sources are not getting hit when configured as direct breakpoints

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#37646]
### Description

Please note $subject. Debug hits are working as expected if the user steps into the bala sources (i.e. lang libraries + standard libraries)

### Steps to Reproduce

Use the below sample program and configure a breakpoint on any source line within the `int` lang-library module.
```ballerina
public function main() {
    int absInt = int:abs(-45);
}
```

### Labels

DevTools

**Comment by azinneera** [comment]
Getting the following exception when a breakpoint is added to a bala source. The function cannot be stepped into since it is being called inside a code that is generated by a code generator plugin.

```
Sep 25, 2022 12:34:55 AM org.ballerinalang.debugadapter.DebugExecutionManager attach
INFO: Debugger is attaching to: 127.0.0.1:5005
Sep 25, 2022 12:34:58 AM org.ballerinalang.debugadapter.JBallerinaDebugServer stackTrace
SEVERE: defaultObj
java.lang.NullPointerException: defaultObj
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Objects.requireNonNullElse(Objects.java:301)
	at org.ballerinalang.debugadapter.BallerinaStackFrame.getAsDAPStackFrame(BallerinaStackFrame.java:84)
	at org.ballerinalang.debugadapter.JBallerinaDebugServer.toDapStackFrame(JBallerinaDebugServer.java:756)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.ballerinalang.debugadapter.JBallerinaDebugServer.stackTrace(JBallerinaDebugServer.java:344)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
