### ISSUE TITLE
[Bug]: GraalVM native image generation failed with retry transaction block

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#37694]
### Description

Sample code

```ballerina
public function main() returns error? {
    retry transaction {
        check commit;
    }
}
```

### Labels

jBallerina

**Comment by TharmiganK** [comment]
Tried disabling the watchdog by using the following flags :
```
-H:DeadlockWatchdogInterval=0 -H:-DeadlockWatchdogExitOnTimeout
```

After that I am getting a OOM error :
```
Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: Java heap space
        at method: Object user.Retry_transaction_statement/0.main.main(Strand)  [Direct call from Object $_init.$lambda$main$(Object[])]
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1435)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1370)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:337)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

Tried to increase the maximum heap size to 16gb (`-J-Xmx16g`) but still getting this error

Seems like there is an issue with GraalVM native-image tool. HindujaB has already created an issue on graal repository. Linking the issue here : https://github.com/oracle/graal/issues/5109

**Comment by TharmiganK** [comment]
This sample has an internal dependency `ballerinai/transaction` which has HTTP dependency. Since we have added the necessary configs needed to build native-image upto HTTP, I tried to generate the jar file with the updated std lib modules. I got the dead lock error for that jar also .

Then I tried to remove the watch dog using the configs mentioned in the previous comments. When the watch dog is disabled I did not get any OOM as before but the build process hangs for a very long time (possibly a dead lock scenario). Attaching the thread dumps here for further analysis : https://drive.google.com/drive/folders/1p9sBhugfVPLhvyMEt90imNV9EGsw8DeO?usp=sharing

**Comment by HindujaB** [comment]
This seems to be working with `2201.2.1` with the following configurations
```
native-image -H:MaxDuplicationFactor=40.0 \
       -jar <jar-path> --no-fallback \
       -H:IncludeResources=logging.properties \
       -H:ReflectionConfigurationFiles=reflection-config.json \
       -H:ResourceConfigurationFiles=/home/hinduja/graalVM/ballerina-graalvm-native-image/config/resource-config.json \
       -H:+ReportExceptionStackTraces \
       -H:DeadlockWatchdogInterval=2 \
       -H:+DeadlockWatchdogExitOnTimeout \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j.impl.JDK14LoggerAdapter,org.slf4j.LoggerFactory,org.slf4j.impl.StaticLoggerBinder \
       --initialize-at-run-time=io.netty.handler.ssl.OpenSsl,io.netty.handler.codec.http2.Http2ServerUpgradeCodec,io.netty.handler.codec.http.HttpMethods,io.netty.handler.codec.compression.ZstdOptions \
       --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils,io.netty.handler.codec.http2.HttpConversionUtil,io.netty.handler.codec.http2.HttpConversionUtil$Http2ToHttpHeaderTranslator \
       --initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier,io.netty.internal.tcnative.CertificateCompressionAlgo,io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod,io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod \
       --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine,io.netty.handler.ssl.OpenSslPrivateKeyMethod \
       --initialize-at-run-time=io.netty.internal.tcnative.SSL,io.netty.internal.tcnative.SSLPrivateKeyMethod   
```

The bal code, 
```ballerina
import ballerina/io;

public function main() returns error? {
    check test1();
}

function test1() returns error? {
    retry transaction {
        io:println("trx started...");
        check commit;
        io:println("trx ended...");
    }
    return;
}
```
![Screenshot from 2022-10-14 10-52-55](https://user-images.githubusercontent.com/28644893/195769155-430d7465-7738-4980-8c5b-fd6838b269e1.png)

The code mentioned in the comment https://github.com/ballerina-platform/ballerina-lang/issues/37694#issuecomment-1269723448 is also working.

![Screenshot from 2022-10-14 11-04-48](https://user-images.githubusercontent.com/28644893/195770136-a0e88ccf-e208-4da0-a47a-df331f10fac3.png)

**Comment by HindujaB** [comment]
The native build seems to fail only if we have the `retry transaction` clause inside the `main` method.
