### ISSUE TITLE
[Bug]: A crash error is generated when running from extracted distributions

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#37706]
### Description

Running a simple Ballerina program using the jballerina-tools in extracted distributions causes a sad error as below.
```
[2022-09-10 20:03:31,801] SEVERE {b7a.log.crash} - 'void io.ballerina.runtime.internal.types.BFunctionType.<init>(io.ballerina.runtime.api.types.Parameter[], io.ballerina.runtime.api.types.Type, io.ballerina.runtime.api.types.Type, long)' 
java.lang.NoSuchMethodError: 'void io.ballerina.runtime.internal.types.BFunctionType.<init>(io.ballerina.runtime.api.types.Parameter[], io.ballerina.runtime.api.types.Type, io.ballerina.runtime.api.types.Type, long)'
        at ballerina.io.1.types.$_object_types.$populate$type$ReadableTextRecordChannel(Unknown Source)
        at ballerina.io.1.types.$_types.$createTypes(Unknown Source)
        at ballerina.io.1.$_init.$currentModuleInit(io)
        at ballerina.io.1.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at xenon.playground2.0.$configurationMapper.$configureInit(Unknown Source)
        at xenon.playground2.0.$_init.main(playground2)
```

### Steps to Reproduce

1. Clone the ballerina-lang repository and build the gradle project under the `master` branch
2. Create a new Ballerina project and write a simple hello world program.
```
import ballerina/io;

public function main() {
   io:println("Hello World");
}
```
3. Run it using the jballerina-tools in the extracted distributions, `<ballerina-lang-repo-path>/distribution/zip/jballerina-tools/build/extracted-distributions/jballerina-tools-2201.2.0-rc1-SNAPSHOT/bin/bal run <ballerina-program-path>`

### Affected Version(s)

2201.3.0-SNAPSHOT

### OS, DB, other environment details and versions

OS - Ubuntu 22.04.1 LTS

### Related area

Run Time

**Comment by warunalakshitha** [comment]
ballerina/io module will not be compatible with ballerina-lang jballerina-tools distribution due to internal api changes. We need to test with pack taken from ballerina-distribution after building all stdlibs.

**Comment by azinneera** [comment]
We are seeing a similar stacktrace in the testerina implementation. We have not used `ballerina/io` in that

**Comment by warunalakshitha** [comment]
I am closing this since this was due to api change in runtime which is not compatible with already pushed io versions. Once we build the distribution with latest lang this should be resolved. Please reopen if you have any queries on this.
