### ISSUE TITLE
[Bug]: Getting NoSuchElementException

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#37717]
### Description

```ballerina
client "http://example.com/apis/one.yaml" as cl1;
```

```
[2022-09-13 08:36:43,985] SEVERE {b7a.log.crash} - No value present 
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:382)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:739)
        at org.wso2.ballerinalang.compiler.tree.BLangClientDeclaration.accept(BLangClientDeclaration.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2247)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:322)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:174)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2247)
       ...
 
ERROR [main.bal:(1:1,1:50)] no matching plugin found for client declaration
ERROR [clientdecl:(1:1,1:1)] Compilation failed due to: No value present
error: compilation contains errors
```

### Steps to Reproduce

Create a new project and add the above ballerina source code to `main.bal`. Now, try to run the code using `bal run` inside the project

### Affected Version(s)

[ballerina-platform:client-declaration](https://github.com/ballerina-platform/ballerina-lang/tree/client-declaration) branch

### Related area

Compilation

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/37725.
