### ISSUE TITLE
[Bug]: Windows build failing for `BuildCommandTest`

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/ballerina-lang#37724]
### Description

The Windows build in Github of the pull request #37553 is failing for the `BuildCommandTest` test case.
```
commands-test-suite > command-tests > io.ballerina.cli.cmd.BuildCommandTest > testBalProjectWithSyntaxError FAILED
    java.lang.IllegalArgumentException: 'other' has different root
        at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:404)
        at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
        at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:118)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:256)
        at io.ballerina.cli.cmd.BuildCommandTest.testBalProjectWithSyntaxError(BuildCommandTest.java:239)
```

**Comment by Thevakumar-Luheerathan** [comment]
I am unable to reproduce this issue with the latest master. Please reopen if the issue is still there.
