### ISSUE TITLE
[Bug]: Type definition with a type reference causes NPE at runtime

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#37892]
### Description

 regexp.bal
```ballerina
@builtinSubtype
public type RegExp any;
```

 string.bal
```ballerina
import ballerina/lang.regexp;

type RegExp regexp:RegExp;
```

```
 io.ballerina.runtime.internal.util.exceptions.BLangRuntimeException: Failed to invoke the function '$configureInit' due to null
        at org.ballerinalang.test.BRunUtil.directRun(BRunUtil.java:390)
        at org.ballerinalang.test.BRunUtil.runInit(BRunUtil.java:367)
        at org.ballerinalang.test.BCompileUtil.invokeModuleInit(BCompileUtil.java:257)
        at org.ballerinalang.test.BCompileUtil.compile(BCompileUtil.java:98)
        at org.ballerinalang.langlib.test.LangLibBooleanTest.setup(LangLibBooleanTest.java:51)

        Caused by:
        java.lang.reflect.InvocationTargetException
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.ballerinalang.test.BRunUtil.directRun(BRunUtil.java:384)
            ... 4 more

            Caused by:
            java.lang.ExceptionInInitializerError
                at ballerina.lang$0046string.0.constants.$_typeref_type_constants.$populate$typeRefType$RegExp(Unknown Source)
                at ballerina.lang$0046string.0.constants.$_typeref_type_constants.$typeref_type_init1(Unknown Source)
                at ballerina.lang$0046string.0.constants.$_typeref_type_constants.<clinit>(Unknown Source)
                at ballerina.lang$0046string.0.types.$_record_types.$populate$type$$anonType$return$next$_0$addField$(Unknown Source)
                at ballerina.lang$0046string.0.types.$_record_types.$populate$type$$anonType$return$next$_0(Unknown Source)
                at ballerina.lang$0046string.0.types.$_types.$createTypes(Unknown Source)
                at ballerina.lang$0046string.0.$_init.$currentModuleInit(lang.string)
                at ballerina.lang$0046string.0.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
                at $configurationMapper.$configureInit(Unknown Source)
                ... 9 more

                Caused by:
                java.lang.NullPointerException
                    at io.ballerina.runtime.internal.types.BIntersectionType.<init>(BIntersectionType.java:66)
                    at ballerina.lang$0046regexp.0.constants.$_typeref_type_constants.$populate$typeRefType$Span(Unknown Source)
                    at ballerina.lang$0046regexp.0.constants.$_typeref_type_constants.$typeref_type_init1(Unknown Source)
                    at ballerina.lang$0046regexp.0.constants.$_typeref_type_constants.<clinit>(Unknown Source)
                    ... 18 more
```

### Related area

-> Runtime

**Comment by pcnfernando** [comment]
Once completed, need to add tests using the TypeRef from predeclared import `string`

**Comment by pcnfernando** [comment]
The issue was due to an ordering issue in JvmPackageGen. `lang.regexp` should be loaded before `lang.string`
