### ISSUE TITLE
[Bug]: Compilation failed due to an unhandled exception on 2201.1.2

### ISSUE THREAD

**Issue by yuk7hi** [ballerina-platform/ballerina-lang#37987]
### Description

I'm getting the following NullPointerException when compiling our code base [1] which used to run without any issues on `Ballerina Swan Lake 2201.1.1`. Since we updated to version `2201.1.2` the following error gets thrown at build time.
Further, I've updated the Salesforce connector to the latest version, [`7.0.0` -> `7.1.0`](which is used in the integration) since the error indicates it's thrown from our **salesforce** module. But the issue still persists.

[1] - https://github.com/wso2-enterprise/internal-app-entity-contact

```text
[2022-09-29 16:28:28,887] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1455)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.lambda$visit$32(DataflowAnalyzer.java:1827)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1827)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStringTemplateLiteral.accept(BLangStringTemplateLiteral.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1769)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:67)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:1500)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangErrorConstructorExpr.accept(BLangErrorConstructorExpr.java:50)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:2114)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangPanic.accept(BLangPanic.java:49)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.lambda$visit$5(DataflowAnalyzer.java:468)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:468)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:804)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangMatchClause.accept(BLangMatchClause.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeBranch(DataflowAnalyzer.java:2266)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:773)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:77)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:450)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeBranch(DataflowAnalyzer.java:2266)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:409)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.visit(DataflowAnalyzer.java:324)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyzeNode(DataflowAnalyzer.java:2284)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.DataflowAnalyzer.analyze(DataflowAnalyzer.java:294)
        at io.ballerina.projects.internal.CompilerPhaseRunner.dataflowAnalyze(CompilerPhaseRunner.java:200)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:124)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:428)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:201)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:147)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:103)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:252)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [contact.salesforce:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

### Affected Version(s)

Ballerina Swan Lake 2201.1.2

### Related area

-> Compilation

**Comment by gimantha** [comment]
Issue can be reproduced for the code below.

```bal
import ballerina/io;
enum FOO {
    A,
    B
}

public function main() {
    FOO 'type = A;
    int|string  g = 3;

    match 'type {
       A if g is string => {
        io:println('type);
       }
       B if g is string => {
        io:println('type);
       }
       _ => {
        io:println('type.toString());
       }
    }
}

```
