### ISSUE TITLE
[Bug]: ClassCastException in ExtractToFunctionCodeAction

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#38025]
### Description

Placing the cursor at the following cursor position gives a ClassCastException,

<img width="1198" alt="Screenshot 2022-10-03 at 13 02 16" src="https://user-images.githubusercontent.com/61020198/193523423-b495998e-5ad4-4a13-9a77-40ecdfa8e044.png">

```
[Error - 1:00:51 PM] CodeAction 'ExtractToFunctionCodeAction' failed! {, error: 'class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.BasicLiteralNode cannot be cast to class io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode (io.ballerina.compiler.syntax.tree.BasicLiteralNode and io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.isExpressionExtractable(ExtractToFunctionCodeAction.java:549)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.validate(ExtractToFunctionCodeAction.java:86)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$1(CodeActionRouter.java:94)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:88)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### Steps to Reproduce

```
type Student record {
    string fname;
    string lname;
    int age;
};

public function main() {
    Student st = {fname: "<cursor>",};
}
```

### Affected Version(s)

2201.2.x

### Related area

-> Editor

**Comment by gayalkuruppu** [comment]
Missing parenthesis in `validate()` method in `ExtractToFunctionCodeAction` already fixed in master with https://github.com/ballerina-platform/ballerina-lang/pull/38010, should fix in `2201.2.x`
