### ISSUE TITLE
[Bug]: InvalidPathException during the code coverage generation in Windows

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#38075]
### Description

```
[2022-10-04 09:25:07,184] SEVERE {b7a.log.crash} - Illegal char <*> at index 182: D:\a\module-ballerina-http\module-ballerina-http\ballerina-tests\target\cache\tests_cache\coverage\bin\ballerina\http\2\$value$(ballerina$0047http$00582$0058$anonType$Method$$delete$**$_2 & readonly).class 
java.nio.file.InvalidPathException: Illegal char <*> at index 182: D:\a\module-ballerina-http\module-ballerina-http\ballerina-tests\target\cache\tests_cache\coverage\bin\ballerina\http\2\$value$(ballerina$0047http$00582$0058$anonType$Method$$delete$**$_2 & readonly).class
```

Found in HTTP PR build on windows. 

```
at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:116)
    at org.ballerinalang.test.runtime.entity.CoverageReport.addCompiledSources(CoverageReport.java:302)
    at org.ballerinalang.test.runtime.entity.CoverageReport.generateReport(CoverageReport.java:139)
    
```    

### Steps to Reproduce

Build the HTTP package in windows

Checkout to : https://github.com/chamil321/module-ballerina-http/tree/exit

Cmd : 
```
./gradlew clean build -x http-native:test -x :http-ballerina-tests:startLdapServe -x :http-ballerina-tests:stopLdapServer -x :http-compiler-plugin-tests:test -x :http-ballerina-tests:commitTomlFiles -x :http-ballerina:commitTomlFiles
```

### Related area

-> Runtime

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38081
