### ISSUE TITLE
[Bug]: Test don't fail when label parsing fails

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38089]
### Description

$title. When the "Labels" header isn't specified, an exception is thrown and/but says the tests passed.

### Steps to Reproduce

```
Test-Case: output
Description: Test logical expression output.
fooLabels: logical-expr

function init() {
    io:println(true || true); // @output true
    io:println(false || true); // @output true
    io:println(true || false); // @output true
    io:println(false || false); // @output false
}
```

Note the error in "Labels".

Throws an NPE, but says "BUILD SUCCESSFUL".

```
ballerina-spec-conformance-test-suite > jballerina-spec-conformance-test > org.ballerinalang.test.TestRunner STANDARD_ERROR
    [Utils] [ERROR] [Error] java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.&lt;init&gt;(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1261)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1334)
        at org.ballerinalang.test.TestRunnerUtils.readTestFile(TestRunnerUtils.java:124)
        at org.ballerinalang.test.TestRunnerUtils.readTestFile(TestRunnerUtils.java:107)
        at org.ballerinalang.test.TestRunner.lambda$dataProvider$2(TestRunner.java:114)
        ...
```

### Related area

-> Other Area

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/38125.
