### ISSUE TITLE
[Bug]: CCE when a type reference is used for stream types

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#38100]
### Description

```bal
type MyIntStream stream<int, error?>;

type MYStreamUnion MyIntStream|stream<string>;

public function main() {
    var intGenObj = object {
        int number = 0;
        public isolated function next() returns record {|int value;|}|error? {
            self.number += 1;
            return {value: self.number};
        }
    };

    MyIntStream c = new(intGenObj);
}
```

Gives

```
[2022-10-06 17:50:31,897] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BStreamType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BStreamType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BStreamType (org.wso2.ballerinalang.compiler.semantics.model.types.BTypeReferenceType and org.wso2.ballerinalang.compiler.semantics.model.types.BStreamType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarStreamTypeInit(Desugar.java:6903)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6811)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8873)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1474)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8848)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1610)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8848)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8892)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1377)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8848)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1423)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8848)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:829)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:174)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8848)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:471)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
```

### Affected Version(s)

2201.3.0-stage

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
This works in 2201.2.0. Seems to be a regression due to https://github.com/ballerina-platform/ballerina-lang/pull/37793

**Comment by rdulmina** [comment]
> This works in 2201.2.0. Seems to be a regression due to #37793

Yes
