### ISSUE TITLE
[Bug]: `java.lang.NoSuchFieldError` when using error constructor expression

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#38124]
### Description

$title

### Steps to Reproduce

```bal
public function main() {
    distinct error err = error("err");
}
```
gives
```
Compiling source
        iss.bal
WARNING [iss.bal:(4:5,4:39)] unused variable 'err'

Running executable

[2022-10-07 15:24:15,147] SEVERE {b7a.log.crash} - $type$$anonType$_0 
java.lang.NoSuchFieldError: $type$$anonType$_0
        at iss.main(iss.bal:4)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:569)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:303)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:270)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Affected Version(s)

Ballerina 2201.2.0 (Swan Lake Update 2)

### Related area

-> Runtime

**Comment by Nadeeshan96** [comment]
This snippet anyway gives this same error
```bal
import ballerina/io;

type ListenerError distinct error;

public function main() {
    ListenerError err1 = error ListenerError("err1");
    io:println(err1 is distinct error);
}
```

**Comment by Nadeeshan96** [comment]
`distinct error` is a proper subtype of `error`. Hence the statement 
```bal
distinct error err = error("err");
```
should give a compilation error. Same applies for the below one also.
```bal
type DistinctError distinct error;
DistinctError err = error("err");
```
