### ISSUE TITLE
[Bug]: Compiler crash with possible invalid Ballerina code

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#38132]
### Description

The program below that might be invalid Ballerina program (type declaration mismatch):

- doesn't report the problem in the VS Code
- compiler crashes

### Steps to Reproduce

```
$ cat issue.bal 
public function main() {
    record {|int x;|} x = table [];
}
```

```
$ bal run issue.bal 
Compiling source
	issue.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-10-10 11:49:42,848] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTableType (org.wso2.ballerinalang.compiler.semantics.model.types.BType and org.wso2.ballerinalang.compiler.semantics.model.types.BTableType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTableType (org.wso2.ballerinalang.compiler.semantics.model.types.BType and org.wso2.ballerinalang.compiler.semantics.model.types.BTableType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:2177)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTableConstructorExpr.accept(BLangTableConstructorExpr.java:70)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1569)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1063)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:732)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:692)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:331)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:331)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:271)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:447)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:168)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:151)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to: class org.wso2.ballerinalang.compiler.semantics.model.types.BType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BTableType (org.wso2.ballerinalang.compiler.semantics.model.types.BType and org.wso2.ballerinalang.compiler.semantics.model.types.BTableType are in unnamed module of loader 'app')
WARNING [issue.bal:(2:5,2:36)] unused variable 'x'
error: compilation contains errors
```

### Affected Version(s)

```
$ bal version
Ballerina 2201.2.0 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10
```

### Related area

-> Compilation

**Comment by gimantha** [comment]
@KavinduZoysa We have fixed this in https://github.com/ballerina-platform/ballerina-lang/issues/35110, Shall we verify this and add tests if not available?
