### ISSUE TITLE
[Bug]: VSCode crashes when there is a cyclic dependency

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#38181]
### Description

When the package has a cyclic dependency, the LS crashes with the following exception. The reason is that, if there are cyclic dependencies, the compilation is skipped and hence the semantic model is not accessible.
```
java.lang.IllegalStateException: Semantic model cannot be retrieved when the module is in compilation state. This is an internal error which will be fixed in a later release.
	at io.ballerina.projects.PackageCompilation.getSemanticModel(PackageCompilation.java:145)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:75)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:59)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:51)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:108)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:61)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:283)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:251)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:238)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:62)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Steps to Reproduce

1. Create a package with two modules
    `bal new foo && bal add mod1`
2. Import foo in mod1 and vise versa

### Affected Version(s)

2201.2.1

### Related area

-> Editor

**Comment by azinneera** [comment]
Currently, in the package resolution phase, diagnostics with the severity `ERROR` are only reported for severe issues such as version incompatibilities and cyclic dependencies in which case compilation cannot be continued.
Therefore in the CLI implementation, if there are errors in package resolution, we print the diagnostics and exit without continuing to compilation. I think we should do the same for language servers

**Comment by malinthar** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/37496 we have prevented access to the semanticModel when we have a  `DiagnosticErrorCode.BAD_SAD_FROM_COMPILER`. We can follow a similar approach here. In this particular case, LS does not crash, it simply returns an exception thrown when trying to access the semantic model. When we remove the cyclic dependency it works fine. However, as long as the cyclic dependency is there no features which depends on the semantic model will not work as it can't be accessed.
