### ISSUE TITLE
[Bug]: No such element exception thrown in ConvertToQueryExpressionCodeAction for var-decl nodes with no initializer

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38248]
### Description

$subject

```ballerina
import ballerinax/mongodb;

public function main() {
    string somethingResult = doSomething();
    mongodb:Client mo<cursor>ngo
}

function doSomething() returns string {
    return "";
}
```

At <cursor> we get the following error:
```java
[Error - 11:29:41 AM] CodeAction 'ConvertToQueryExpressionCodeAction' failed! {, error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.ballerinalang.langserver.codeaction.providers.ConvertToQueryExpressionCodeAction.getLhsAndRhsSymbolInfo(ConvertToQueryExpressionCodeAction.java:178)
	at org.ballerinalang.langserver.codeaction.providers.ConvertToQueryExpressionCodeAction.getCodeActions(ConvertToQueryExpressionCodeAction.java:86)
```

### Steps to Reproduce

See description

### Related area

-> Editor

### Related issue(s) (optional)

#37350

**Comment by IMS94** [comment]
This has been fixed in 2201.3.2-rc1, but now a new issue is observed: https://github.com/ballerina-platform/ballerina-lang/issues/38980
