### ISSUE TITLE
[Bug]: Getting a NPE when compiling code in choreo

### ISSUE THREAD

**Issue by darshanasbg** [ballerina-platform/ballerina-lang#38511]
### Description

Getting NPE [1] when running code [2], when its updated to [3] the issue NPE getting resolved. Anyhow even with the wrong logic [2], NPE in compiler should be avoided.

[1] error
```
ompiling source
        darshana/greetings:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-11-02 05:09:28,625] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:169)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:452)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:131)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:131)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:410)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:108)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:108)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:88)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:84)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:272)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:447)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:130)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [greetings:(1:1,1:1)] Compilation failed due to an unhandled exception
HINT [service.bal:(29:15,29:37)] unnecessary condition: expression will always evaluate to 'true'
error: compilation contains errors
```

[2] Code with the issue
```
import ballerinax/github;
import ballerina/http;
import ballerina/io;

configurable string pat = ?;

type repo record {|
    string name;
    int? stars;
|};

service / on new http:Listener(9090) {
    # + name - the input string Organization name
    # + return - 5 repos with highest stars or error
    resource function get repos(string name) returns string[]|error {
        if name is "" {
            return error("Organization name should not be empty!");
        }

        github:Client githubEp = check new (config = {
            auth: {
                token: pat
            }
        });

        stream<github:Repository, error?> getRepositoriesResponse = check githubEp->getRepositories(name);

        repo[]? repos = check from var i in getRepositoriesResponse 
        where i is github:Repository
        select {name: i.name, stars: i.stargazerCount};

        string[] sortedrepos = [];
        if (repos is repo[]) {
            sortedrepos = from var r in repos
            order by r.stars descending
            limit 5
            select name;
            io:println(sortedrepos);
        }

        return sortedrepos;
    }
}
```

[3] Fixed Code
```
import ballerinax/github;
import ballerina/http;
import ballerina/io;

configurable string pat = ?;

type repo record {|
    string name;
    int? stars;
|};

service / on new http:Listener(9090) {
    # + name - the input string Organization name
    # + return - 5 repos with highest stars or error
    resource function get repos(string name) returns string[]|error {
        if name is "" {
            return error("Organization name should not be empty!");
        }

        github:Client githubEp = check new (config = {
            auth: {
                token: pat
            }
        });

        stream<github:Repository, error?> getRepositoriesResponse = check githubEp->getRepositories(name);

        repo[]? repos = check from var i in getRepositoriesResponse 
        where i is github:Repository
        select {name: i.name, stars: i.stargazerCount};

        string[] sortedrepos = [];
        if (repos is repo[]) {
            sortedrepos = from var r in repos
            order by r.stars descending
            limit 5
            select r.name;
            io:println(sortedrepos);
        }

        return sortedrepos;
    }
}

```

### Steps to Reproduce

Run the code [2] above in choreo.

### OS, DB, other environment details and versions

Ran the code in Choreo

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
May relate to https://github.com/ballerina-platform/ballerina-lang/issues/32710
