### ISSUE TITLE
[Task]: Add code action support for regular expressions

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#38568]
### Description

The following code actions don't work with regular expressions. Identify and fix if there are any other similar code actions.

1. Create function code action

`string:RegExp regex = getRegex();`

2. Change variable type code action

`string regex2 = re ``;`

3. Change return type code action 

```
function test() returns string {

    return re ``;
}
```
4. Fill record fields code action and completion item

```
type rec record {|
    string:RegExp regex;
    string str;
|};

function test() {
    rec r = {};

}
```

### Related area

-> Editor

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/38095

**Comment by mohanvive** [comment]
Same with create variable code action, 

```
[Error - 3:04:24 PM] CodeAction 'CreateVariableCodeAction' failed! {, error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:148)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:116)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:134)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:169)
	at org.ballerinalang.langserver.common.utils.FunctionGenerator.generateTypeSignature(FunctionGenerator.java:51)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypeSymbols(CodeActionUtil.java:312)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:195)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCreateVariableTextEdits(CreateVariableCodeAction.java:155)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCodeActions(CreateVariableCodeAction.java:94)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:123)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by LakshanWeerasinghe** [comment]
Need to add this as well #39249.
