### ISSUE TITLE
[Bug]: GraalVM native-image fails for locks inside a loop

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#38665]
### Description

$subject
The following code fails for the graalVM native build.
error log : 
```
Error: Non-reducible loop requires too much duplication. Setting MaxDuplicationFactor to a value higher than 40.0 may resolve this.
Detailed message:
Call path from entry point to ballerina.in_memory_hub$0046dispatcher/1.dispatcher.syncDispatcherState(Strand): 
	at ballerina.in_memory_hub$0046dispatcher.1.dispatcher.syncDispatcherState(dispatcher.bal)
	at ballerina.in_memory_hub.1.start_hub.$syncDispatcherState$lambda$_0$(start_hub.bal:24)
	at ballerina.in_memory_hub.1.start_hub$$Lambda$944/0x00000007c2041040.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.concurrent.LinkedBlockingQueue$LBQSpliterator.tryAdvance(LinkedBlockingQueue.java:930)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:256)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback_handle_e21486683ddb969ec67d269d0970fda063b7e350(generated:0)
```

### Steps to Reproduce

```ballerina
isolated map<int[]> m = {};

public function main() {
    int i = 0;
    while (i < 2) {
        lock {
            foreach string k in m.keys() {
                lock {
                    _ = m.get(k);
                }
            }
        }
        i = i + 1;
    }
}
```

### Affected Version(s)

2201.3.0

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/38072

**Comment by HindujaB** [comment]
The fix (https://github.com/ballerina-platform/ballerina-lang/pull/37659) is merged with the master and will be available for `2201.4.0`. 
Hence closing this.
