### ISSUE TITLE
[Bug]: StrandDumpTest.testStrandDumpDuringBalTest is failing intermittently

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#38676]
### Description

The test `StrandDumpTest.testStrandDumpDuringBalTest` is failing intermittently during PR builds. 
https://scans.gradle.com/s/t5dsxumapbwts

error log :
```
org.ballerinalang.test.context.BallerinaTestException: Failure to obtain the expected strand dump.	
Expected regular expression: Ballerina Strand Dump \[\d*/\d*/\d* \d*:\d*:\d*\]	
Obtained strand dump:	
Compiling source	
	testOrg/testPackageWithModules:0.1.0	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.verifyObtainedStrandDump(StrandDumpTest.java:174)	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.startProcessAndVerifyStrandDump(StrandDumpTest.java:154)	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.testStrandDumpDuringBalTest(StrandDumpTest.java:92)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:566)	
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)	
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)	
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)	
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	
at java.util.concurrent.FutureTask.run(FutureTask.java:264)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
at java.lang.Thread.run(Thread.java:829)
```

### Affected Version(s)

current master

### Related area

-> Runtime

**Comment by HindujaB** [comment]
The output seems to be changing from time to time. 
https://scans.gradle.com/s/prulm44yvzdam/tests/overview?outcome=failed
```
org.ballerinalang.test.context.BallerinaTestException: Failure to obtain the expected strand dump. |  
  | Expected regular expression: Total strand group count \t:\t6 |  
  | Obtained strand dump: |  
  | Compiling source |  
  | testOrg/testPackageWithModules:0.1.0 |  
  |   |  
  | Running Tests |  
  |   |  
  | testPackageWithModules |  
  | Ballerina Strand Dump [2022/11/16 02:18:20] |  
  | =========================================== |  
  |   |  
  | Total strand group count 	:	3 |  
  | Total strand count       	:	0 |  
  | Active strand group count	:	0 |  
  | Active strand count      	:	0 |  
  |   |  
  | =========================================== |  
 ```

**Comment by Nadeeshan96** [comment]
This is intermittently failing probably due to a long delay in starting a new process during the integration test. Due to that even after 20 s of compiling and running the tests, it has not come to the expected steady state. Above strand dumps show the strand dumps which may get during the early stages. Hence will increase the timeout to 28 s and check several times whether this will fail again.
