### ISSUE TITLE
[Bug]: Bad sad error when build a package with `observabilityIncluded = true`

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#38695]
### Description

Sample code

```
import sasindudilshara/proj1;
import ballerina/io;

public function main() {
    proj1:E2 e = error("", body = ""); // OK
    error e2 = error proj1:E2("", body = ""); // compilation error: cannot create a new error value from 'myproj:E2'
    io:println(e);
    io:println(e2);
}
```

sample package (sasindudilshara/proj1) - `main.bal`

```
public type E1 distinct error;

public type E2 distinct (E1 & error<record {|anydata body;|}>);
```

sample package (sasindudilshara/proj1) - `Ballerina.toml`

```
[package]
org = "sasindudilshara"
name = "proj"
version = "0.1.0"
distribution = "2201.2.0"

[build-options]
observabilityIncluded = true

```

Compiler crash with

```
Compiling source
        test2.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-11-16 12:55:01,735] SEVERE {b7a.log.crash} - Graph cannot be null in the built-in package: ballerinai/observe:0.0.0 
java.lang.IllegalStateException: Graph cannot be null in the built-in package: ballerinai/observe:0.0.0
        at io.ballerina.projects.internal.ResolutionEngine.lambda$getBuiltInPkgDescDepGraph$1(ResolutionEngine.java:263)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.ballerina.projects.internal.ResolutionEngine.getBuiltInPkgDescDepGraph(ResolutionEngine.java:262)
        at io.ballerina.projects.internal.ResolutionEngine.mergeGraph(ResolutionEngine.java:234)
        at io.ballerina.projects.internal.ResolutionEngine.populateStaticDependencyGraph(ResolutionEngine.java:185)
        at io.ballerina.projects.internal.ResolutionEngine.resolveDependencies(ResolutionEngine.java:94)
        at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:335)
        at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:251)
        at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:108)
        at io.ballerina.projects.PackageResolution.from(PackageResolution.java:116)
        at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:266)
        at io.ballerina.projects.Package.getResolution(Package.java:164)
        at io.ballerina.projects.Package.runIDLGeneratorPlugins(Package.java:253)
        at io.ballerina.projects.Package.runIDLGeneratorPlugins(Package.java:232)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:88)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Related area

-> Central

**Comment by azinneera** [comment]
I believe this comes with the jballerina-tools distribution. In that case, it is expected since we do not have `ballerinai/observe` in ballerina-lang repo now. You need to copy the bala into the distribution manually.

**Comment by SasinduDilshara** [comment]
> I believe this comes with the jballerina-tools distribution. In that case, it is expected since we do not have `ballerinai/observe` in ballerina-lang repo now. You need to copy the bala into the distribution manually.

Ok. Thank you

**Comment by keizer619** [comment]
Since it works in final pack this will be closed. Please feel free to reopen if there are any concerns
