### ISSUE TITLE
[Bug]: NullPointer exception when test:Mock functionName field is invalid

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#38693]
### Description

When the name of a non-existent function is passed as the `functionName` parameter of the `test:Mock` annotation, a null pointer exception pops out. 

A proper error displaying that the provided function does not exist would be more appropriate.

Here is the test code used.

``` ballerina
import ballerina/test;
import ballerina/sql;
import ballerinax/java.jdbc;

@test:Mock {
    functionName: "createJdbcClient1" // non existent method
}
function getMockClient() returns jdbc:Client|sql:Error {
        return test:mock(jdbc:Client);
}

```

It produces the following error stacktrace.
```
Compiling source
        gayaldassanayake/nulltest1:0.1.0
[2022-11-16 15:41:34,198] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.getQualifiedClassName(MockAnnotationProcessor.java:390)
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.process(MockAnnotationProcessor.java:236)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$3(CompilerPluginRunner.java:204)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:353)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:204)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:192)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$1(CompilerPluginRunner.java:160)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:158)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:174)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:138)
        at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:212)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:144)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:455)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:404)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:203)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:242)
        at io.ballerina.projects.Package.getCompilation(Package.java:156)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:333)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:129)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:303)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Steps to Reproduce

1. Create a ballerina project with a test file containing above code snippet.
2. Run `bal test` within the project.

### Affected Version(s)

2201.2.3, 2201.3.0

### OS, DB, other environment details and versions

MacOS Monterey, Macbook pro 14'' (m1 pro)

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
In the class `MockAnnotationProcessor` the variable `functionToMockType` becomes null since the `functionName` we are passing is incorrect. We correctly add an error diagnostic `could not find functions in module`. 

However after the diagnostic, we continue along the flow rather than exiting at that point.This leads to the null pointer exception. 

Adding a `break` after the diagnostic report fixes this issue.

**Comment by gayaldassanayake** [comment]
Tested the functionality of the language server. The diagnostics are shown properly
