### ISSUE TITLE
[Bug]: SEVERE {b7a.log.crash} - null 

### ISSUE THREAD

**Issue by dnnaji** [ballerina-platform/ballerina-lang#38732]
### Description

Error when trying to run code on local machine: https://github.com/ramith/snowflakedemo

[2022-11-20 16:38:49,474] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
        at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:750)
        at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:604)
        at org.wso2.ballerinalang.compiler.bir.codegen.split.constants.JvmUnionTypeConstantsGen.add(JvmUnionTypeConstantsGen.java:89)
        at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmConstantsGen.getTypeConstantsVar(JvmConstantsGen.java:124)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:435)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCastGen.checkCast(JvmCastGen.java:1339)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCastGen.generateJToBCheckCast(JvmCastGen.java:509)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCastGen.generatePlatformCheckCast(JvmCastGen.java:154)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generatePlatformIns(JvmInstructionGen.java:592)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2181)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:563)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:497)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:242)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.ExternalMethodGen.genJMethodForBExternalFunc(ExternalMethodGen.java:79)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:162)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:446)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1126)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:397)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:807)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:309)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:476)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:384)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:171)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)

### Steps to Reproduce

Clone https://github.com/ramith/snowflakedemo and bal run

### OS, DB, other environment details and versions

macOS M1

### Related area

-> Compilation

**Comment by gabilang** [comment]
This is an intermittent issue due to the use of `computeIfAbsent()` method of `TreeMap`. This issue has been observed with some of the Red-hat based Linux OS earlier as well and fixed with https://github.com/ballerina-platform/ballerina-lang/pull/37554. The fix will be available in `2201.3.0`.

**Comment by dnnaji** [comment]
Thanks, I will look forward to the `2201.3.0` drop.

**Comment by gabilang** [comment]
Closing this since the fix has been already merged.
