### ISSUE TITLE
[Bug]: Compiler crashes for invalid non-const non-var ref expressions in const annotations

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38746]
### Description

$title.

### Steps to Reproduce

```ballerina
public const annotation record {| int increment = 1; |} v25 on source type;

int x = 1;

@v25 {
    increment: x + 1
}
type Foo record {|
    int x;
|};
```

Happens with other kinds of expressions too. E.g., unary expression with a non-const expression (`-x`)

### Affected Version(s)

2201.3.0-RCs

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
>    increment: 1 + 2     // Current error message is "expression is not a constant expression". 
>                        // Should be changed to reflect only literals are allowed.

Well, in the spec we refer to literals as follows: https://ballerina.io/spec/lang/master/#section_6.5

```
literal :=
   nil-literal
   | boolean-literal
   | numeric-literal
   | string-literal
   | byte-array-literal
```

Here, we can have unary-expression, and variable references. Hence, IMO the current error message is correct.

**Comment by lochana-chathura** [comment]
Following crashing with a CCE,

```bal
type Rec record {|
    int increment;
|};

public const annotation Rec v25 on source type;

const int c = 1;

Rec r = {"increment": c};

@v25 {
    ...r
}
type Foo record {|
    int x;
|};
```

<details>
  <summary><b>crash-log</b>  (<i>click to expand</i>)</summary>

```
[2023-06-16 15:49:12,297] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordVarNameField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordVarNameField are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordVarNameField (org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordSpreadOperatorField and org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangRecordVarNameField are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$checkAnnotConstantExpression$39(SemanticAnalyzer.java:4381)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.checkAnnotConstantExpression(SemanticAnalyzer.java:4374)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.validateAnnotationAttachmentExpr(SemanticAnalyzer.java:4619)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1092)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangAnnotationAttachment.accept(BLangAnnotationAttachment.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$6(SemanticAnalyzer.java:640)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:634)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:122)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4290)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4264)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:334)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:211)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:301)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:433)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:204)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:188)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:241)
        at io.ballerina.projects.Package.getCompilation(Package.java:150)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:319)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:142)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```
</details>

**Comment by MaryamZi** [comment]
@lochana-chathura, shall we create a separate issue for the CCE with the spread field?

**Comment by lochana-chathura** [comment]
> shall we create a separate issue for the CCE with the spread field?

Created #40733
