### ISSUE TITLE
[Bug]: Compiler crashes when resource access actions are used inside query expressions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38757]
### Description

Consider the following code:
```ballerina
return from var [customerId, sales] in salesTotals.entries()
        let var customer = check customersClient->/[customerId]
        limit x
        select customer;
```
Compiler crashes with the following:
```
Compiling source
        balHack/problem_3_5:1.0.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-11-21 19:34:41,513] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:1068)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation$BLangResourceAccessInvocation.accept(BLangInvocation.java:291)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.acceptNode(QueryDesugar.java:2256)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1948)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:65)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.acceptNode(QueryDesugar.java:2256)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1567)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangReturn.accept(BLangReturn.java:48)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.lambda$visit$5(QueryDesugar.java:1481)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1481)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1466)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1453)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLambdaFunction.accept(BLangLambdaFunction.java:64)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.addNestedFromFunction(QueryDesugar.java:606)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.buildStream(QueryDesugar.java:439)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.desugar(QueryDesugar.java:389)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8450)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangQueryAction.accept(BLangQueryAction.java:47)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8867)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1471)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1607)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:826)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:469)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:289)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Steps to Reproduce

See description

### Affected Version(s)

2201.3.0-rc2

### Related area

-> Editor

**Comment by hasithaa** [comment]
According to the spec, we can't use an action inside a let expression. This should result a compile time error.

**Comment by hasithaa** [comment]
@IMS94 By bad, it is a valid code, because return allows `action-or-expression`. So this is a valid code.

**Comment by gimantha** [comment]
Original PR fixes a part of the problem, and not all the cases are fixed with the PR. There is a workaround to the above issue
 

```bal
return from var [customerId, sales] in salesTotals.entries()
        let var customer = check callClient(myClient, customerId)
        limit x
        select customer;

function callClient(MyClient myClient, int customerId) returns string|error {
    return myClient->/[customerId];
}
```

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38900
