### ISSUE TITLE
[Bug]: Client resource method in a query expression returns an unexpected error

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#38839]
### Description

When a client resource method is invoked in a query expression, an NPE is thrown from compiler.

**Note:** This error occurs only for client resource method with path as a variable i.e `client->[variable]`

### Steps to Reproduce

Run the following ballerina sample :
```ballerina
public isolated client class Client {

    resource isolated function get [int number]() returns string {
        return string`data${number}`;
    }
}

function getNumberData(int[] numbers) returns string[] {
    Client clientEP = new;
    return from int number in numbers select clientEP->/[number];
}
```

```
$ bal run

Compiling source
        test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-11-27 21:00:33,437] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:464)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$3(BIROptimizer.java:121)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:121)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:422)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:107)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:107)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:86)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:83)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:287)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

### Affected Version(s)

Ballerina SwanLake Update 3 - RC3

### OS, DB, other environment details and versions

Mac OS

### Related area

-> Compilation

**Comment by gimantha** [comment]
Related https://github.com/ballerina-platform/ballerina-lang/issues/38757

**Comment by gimantha** [comment]
Wrapping the client resource function invocation inside a function will workaround this issue.

```bal
public isolated client class Client {

    resource isolated function get [int number]() returns string {
        return string `data${number}`;
    }
}

function getNumberData(int[] numbers) returns string[] {
    Client clientEP = new;
    return from int number in numbers
        select callClient(clientEP, number);
}

function callClient(Client myClient, int number) returns string {
    return myClient->/[number];
}

```

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38900
