### ISSUE TITLE
[Bug]: NPE in reference finder for an intermediate source code

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38869]
### Description

Consider:

```ballerina
import ballerina/http;

function demo() {
}

service / on new http
# This returns list of services in all namespaces.
# + return - list of services in namespaces.
function getServicesListFromK8s() returns ServiceList|error {
    return {list: getServicesList(), pagination: {total: getServicesList().length()}};
}

function myFunc() {

}
```
Copy the above code and make any text edit, and you will see the following error log in plugin logs.
```java
[Info  - 4:21:36 PM] Operation 'text/didChange' {fileUri: 'file:///home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test2.bal'} updated
[Error - 4:21:36 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test2.bal', error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:295)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:235)
	at io.ballerina.compiler.api.impl.ReferenceFinder.lambda$visit$2(ReferenceFinder.java:278)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.ballerina.compiler.api.impl.ReferenceFinder.visit(ReferenceFinder.java:278)
	at org.wso2.ballerinalang.compiler.tree.BLangCompilationUnit.accept(BLangCompilationUnit.java:101)
	at io.ballerina.compiler.api.impl.ReferenceFinder.find(ReferenceFinder.java:235)
	at io.ballerina.compiler.api.impl.ReferenceFinder.findReferences(ReferenceFinder.java:226)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.getReferences(BallerinaSemanticModel.java:283)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:272)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:674)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:949)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:652)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Affected Version(s)

See description

### OS, DB, other environment details and versions

2201.3.0-rc3

### Related area

-> Editor

**Comment by DamithaSenevirathne** [comment]
Reason for the this issue is in the current implementation we are not checking the object compatibility if there is an semantic error. In PR : https://github.com/ballerina-platform/ballerina-lang/pull/39763 this is addressed and there are few failing jballerina unit test cases (negative testcase) that need to be updated.
