### ISSUE TITLE
[Bug]: "Create variable" code action not suggested for `array:enumerate` usage

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38868]
### Description

$title. Only "Ignore return value" is suggested.

### Steps to Reproduce

```ballerina
public function main() {
    string[] greetings = ["Hello", "Bonjour", "Hola", "Ciao"];
    greetings.enumerate();
}
```

### Affected Version(s)

2201.3.0-RCs

### Related area

-> Editor

**Comment by IMS94** [comment]
Following NPE is thrown in this occasion:
```java
[Error - 1:55:53 PM] CodeAction 'CreateVariableCodeAction' failed! {, error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.symbols.BallerinaArrayTypeSymbol.memberTypeDescriptor(BallerinaArrayTypeSymbol.java:55)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:299)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCreateVariableTextEdits(CreateVariableCodeAction.java:136)
	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCodeActions(CreateVariableCodeAction.java:91)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:124)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:120)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by malinthar** [comment]
> Following NPE is thrown in this occasion:
> 
> ```java
> [Error - 1:55:53 PM] CodeAction 'CreateVariableCodeAction' failed! {, error: 'java.lang.NullPointerException'}
> java.lang.NullPointerException
> 	at io.ballerina.compiler.api.impl.symbols.BallerinaArrayTypeSymbol.memberTypeDescriptor(BallerinaArrayTypeSymbol.java:55)
> 	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:299)
> 	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCreateVariableTextEdits(CreateVariableCodeAction.java:136)
> 	at org.ballerinalang.langserver.codeaction.providers.createvar.CreateVariableCodeAction.getCodeActions(CreateVariableCodeAction.java:91)
> 	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:134)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:124)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
> 	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:120)
> 	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
> 	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
> 	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
> 	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ```

Seems to be the cause for the issue. Created https://github.com/ballerina-platform/ballerina-lang/issues/39020

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/39020
