### ISSUE TITLE
[Bug]: Unhandled exceptions in MockAnnotationProcessor related to Function Mocking

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#38880]
### Description

There are a several unhandled exceptions in the class MockAnnotationProcessor that needs to be fixed.
1. For single file projects, function mocking is not supported. Should provide a proper diagnostic for that. This is also tracked by https://github.com/ballerina-platform/ballerina-lang/issues/38720
2. When the provided `functionName` for function mocking is not found in the project, a proper diagnostic should be given. A part of this is fixed with https://github.com/ballerina-platform/ballerina-lang/issues/38693. However there are cases where the fix is not applicable to.
    ```ballerina
    @test:Mock { functionName: "intAdd1" }  // intAdd1 is non-existent
    test:MockFunction intAddMockFn = new();
    ```
  3. A function to be mocked should be in a file that is not a test file. If we do not find a function with the name provided with `functionName` in the non-test files we do not give a proper error diagnostic as long as a function with that name is in a test file. However this leads to the following runtime error.
    ``` bash
        [2022-11-30 09:51:02,866] SEVERE {b7a.log.crash} - Mock Function and Function to Mock cannot be null 
        java.lang.IllegalStateException: Mock Function and Function to Mock cannot be null
                at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunction(MockDesugar.java:162)
                at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunctions(MockDesugar.java:117)
    ```

### Related area

-> Test Framework

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/38720
https://github.com/ballerina-platform/ballerina-lang/issues/38693

**Comment by azinneera** [comment]
Another issue issue related to this: https://github.com/ballerina-platform/ballerina-lang/issues/38972

**Comment by gayaldassanayake** [comment]
Another issue - `@test:Mock` without the annotation the moduleName, functionName also causes an NPE & compiler plugin crashes.

``` ballerina
@test:Mock // no MockConfig record
test:MockFunction mock_intAdd = new ();
```

**Comment by azinneera** [comment]
> Another issue - `@test:Mock` without the annotation the moduleName, functionName also causes an NPE & compiler plugin crashes.
> 
> ```ballerina
> @test:Mock // no MockConfig record
> test:MockFunction mock_intAdd = new ();
> ```

This also must issue an error

**Comment by gayaldassanayake** [comment]
> Another issue - `@test:Mock` without the annotation the moduleName, functionName also causes an NPE & compiler plugin crashes.
> 
> ```ballerina
> @test:Mock // no MockConfig record
> test:MockFunction mock_intAdd = new ();
> ```

Updated the same PR with the fix
