### ISSUE TITLE
[Bug]: testTestBalFileWithPeriods test in TestCommandTest is failing in the master branch 

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-lang#38893]
### Description

`testTestBalFileWithPeriods` test in `TestCommandTest` is failing in the master branch.
```
Running Tests
	sample.tests.bal
error: failed to load test execution class :sample.tests
commands-test-suite > command-tests > io.ballerina.cli.cmd.TestCommandTest > testTestBalFileWithPeriods FAILED
    io.ballerina.cli.launcher.BLauncherException
        at io.ballerina.cli.launcher.LauncherUtils.createLauncherException(LauncherUtils.java:66)
        at io.ballerina.cli.task.RunTestsTask.execute(RunTestsTask.java:243)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:303)
        at io.ballerina.cli.cmd.TestCommandTest.testTestBalFileWithPeriods(TestCommandTest.java:107)
```

### Steps to Reproduce

Run the `testTestBalFileWithPeriods` test inside the master branch.

### Affected Version(s)

2201.4.0-SNAPSHOT (latest master)

### Related area

-> Test Framework

**Comment by ShammiL** [comment]
This issue was again mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/38990 and was resolved by https://github.com/ballerina-platform/ballerina-lang/pull/39009
