### ISSUE TITLE
[Bug]: Goto def doesn't work for `stringArray.push()` method

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38925]
### Description

```ballerina
public function main() {
    string[] greetings = ["Hello", "Bonjour", "Hola", "Ciao"];
    greetings.push("")
}
```
Here when we try to go to the definition of `push()` method, following error is thrown:
```java
[Error - 11:12:58 AM] Operation 'text/definition' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/projects/multi_mod_project/main.bal', [3:17], error: 'Index 0 out of bounds for length 0'}
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.ballerinalang.langserver.definition.DefinitionUtil.getFilePathForLanglib(DefinitionUtil.java:137)
	at org.ballerinalang.langserver.definition.DefinitionUtil.getLocation(DefinitionUtil.java:103)
	at org.ballerinalang.langserver.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:87)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$3(BallerinaTextDocumentService.java:231)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Affected Version(s)

2201.3.0-rc3

### Related area

-> Editor

**Comment by IMS94** [comment]
Noticed that this gets reproduced only in build projects. Not in single file projects.
