### ISSUE TITLE
[Bug]: NPE is thrown when a mocked method is not found

### ISSUE THREAD

**Issue by piraveena** [ballerina-platform/ballerina-lang#38972]
### Description

NPE is thrown when a mocked method is not found in the ballerina project
``` 
Compiling source
        wso2/authz_management_service:0.1.0
[2022-12-06 12:24:28,782] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.getClassName(MockAnnotationProcessor.java:412)
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.getImportedFunctionClassName(MockAnnotationProcessor.java:403)
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.getQualifiedClassName(MockAnnotationProcessor.java:392)
        at org.ballerinalang.testerina.core.MockAnnotationProcessor.process(MockAnnotationProcessor.java:136)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$8(CompilerPluginRunner.java:240)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:349)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:240)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:191)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$1(CompilerPluginRunner.java:159)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:157)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:137)
        at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:212)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:144)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:428)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:201)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:147)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:103)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:277)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
error: compilation failed: The compiler extension in package 'ballerina:sql:1.4.1' failed to complete. null

```

### Steps to Reproduce

1. Create a mocked dbclient.
2. Create a method that is not found for the db layer.

```
jdbc:Client dbClient = check getClient();
final string url = string `jdbc:postgresql://${config:dbHostName}:${config:dbPort.toString()}/${config:databaseName}`;

function getClient() returns jdbc:Client|error =>
    new (
            url,
            config:dbUserName,
            config:dbPassword
        );

public function selectRolesByApp(string appId, string organizationId) returns utils:RoleDO[]|error {

    return roles ?: [];
}
```

In the test class, create a mock method `deleteRoleById` that is not existing 
```
@test:Mock {
    moduleName: "authz_management_service.dao",
    functionName: "getClient"
}
function getDBMockClient() returns jdbc:Client|error {
    log:printInfo("Mocking DB client by using an inmemory h2 db");
    return new ("jdbc:h2:mem:mockTestDB");
}

@test:Mock {
    moduleName: "authz_management_service.dao",
    functionName: "selectRolesByApp"
}
test:MockFunction selectRolesByAppMockFn = new ();

public function mockSelectRolesByApp(string appId, string organizationId) returns utils:RoleDO[]|sql:Error? {
    utils:RoleDO role1 = {role_name: TEST_ROLE1, org_id: organizationId, app_id: appId};
    utils:RoleDO role2 = {role_name: TEST_ROLE2, org_id: organizationId, app_id: appId};
    return [role1, role2];
}

@test:Mock {
    moduleName: "authz_management_service.dao",
    functionName: "deleteRoleById"
}
test:MockFunction deleteRoleByIdMockFn = new ();

public function mockdeleteRoleById(string roleName, string appId, string organizationId) returns sql:Error? {
    return ();
}
```

3. Run your project using `bal run`
4. You can see above error logs in the service.

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment]
This issue is fixed for the master and 3.x (2201.3.1 onwards) with https://github.com/ballerina-platform/ballerina-lang/issues/38693.
