### ISSUE TITLE
[Bug]: NPE when ignoring the detail mapping in an error binding using `_` 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#38998]
### Description

$title

### Steps to Reproduce

```ballerina
type SampleErrorData record {|
   string info;
   boolean fatal;
|};
 
type SampleError error<SampleErrorData>;
 
public function main() {
   SampleError sampleErr = error("Transaction Error", info = "commit failed", fatal = true);
 
   var error(reason, _) = sampleErr;
}
```
Error log
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1468)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1607)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1601)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1593)
        at org.wso2.ballerinalang.compiler.tree.BLangErrorVariable.accept(BLangErrorVariable.java:78)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1711)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangErrorVariableDef.accept(BLangErrorVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:826)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:469)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Affected Version(s)

2201.3.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/39691.

Test - https://github.com/ballerina-platform/ballerina-lang/pull/39691/files#diff-4a67181327cb8d0ad6f3f929aae7efc708bfb5f6506f1a6b83656737a3bfc1ceR81
