### ISSUE TITLE
[Bug]: GraalVM native image build failed with retry transaction block

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#39142]
### Description

$title

Gives the following.
```
Generating executable with Native image
========================================================================================================================
GraalVM Native Image: Generating 'retry_trans_func_file' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (9.3s @ 0.42GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 2 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.ballerina.stdlib.crypto.svm.BouncyCastleFeature
[2/7] Performing analysis...  []                                                                        (16.1s @ 3.69GB)
  11,294 (93.69%) of 12,055 classes reachable
  29,417 (66.74%) of 44,076 fields reachable
  51,217 (84.17%) of 60,852 methods reachable
     856 classes,     0 fields, and     0 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing retry_trans_func_file.main(io.ballerina.runtime.internal.scheduling.Strand) 
Parsing context:
   at retry_trans_func_file.main(retry_trans_func_file.bal)
   at $_init.$lambda$main$(.)
   at $_init$$Lambda$775/0x0000000801f8a040.apply(Unknown Source)
   at ballerina.lang$0046query.0.$value$_DoFunction.process(types.bal:691)
   at ballerina.lang$0046query.0.$value$_DoFunction.call(types.bal)
   at ballerina.lang$0046query.0.creators.$_objects.createObjectValue1(Unknown Source)
   at ballerina.lang$0046query.0.creators.$_objects.createObjectValue0(Unknown Source)
   at ballerina.lang$0046query.0.creators.$_objects.createObjectValue(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultStaticInvokeTypeFlow.update(DefaultStaticInvokeTypeFlow.java:64)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.debug.GraalError: Frame states being merged are incompatible: mismatch in rethrowException flag
 This frame state: [locals: [1,591,592,593,594,859,596,597,598,599,#,600,601,_,54731,604,605,606,607,608,_,610,611,54733,613,614,615,616,54734,54735,54736,54737,54738,54739,54740,54741,54742,_,_,54744,54745,54746,_,630,631,632,633,634,54747,636,637,638,639,640,_,641,_,642,_,_,_,644,_] stack: [54795] locks: [] rethrowException]
Other frame state: [locals: [1,591,592,593,594,55429,596,597,598,599,#,600,601,_,55430,604,605,606,607,608,_,610,611,55431,613,614,615,616,55430,55432,55433,55434,55435,55436,55437,55438,55439,_,_,55430,55440,55441,_,630,631,632,633,634,55442,636,637,638,639,640,_,641,_,642,_,_,_,644,_] stack: [55443] locks: []]
Parser context: retry_trans_func_file.foo(retry_trans_func_file.bal:0) [bci: 2256, intrinsic: false]
2256: ldc_w         #373        // 1
2259: istore        13
2261: getstatic     #76         // constants.$_string_constants.$bString8:io.ballerina.runtime.api.values.BString
2264: astore        5
2266: aload         18

        at jdk.internal.vm.compiler/org.graalvm.compiler.java.FrameStateBuilder.checkCompatibleWith(FrameStateBuilder.java:399)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.FrameStateBuilder.merge(FrameStateBuilder.java:431)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createTarget(BytecodeParser.java:3133)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createTarget(BytecodeParser.java:3033)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createExceptionDispatch(BytecodeParser.java:3288)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3188)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:179)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
        ... 12 more
------------------------------------------------------------------------------------------------------------------------
                        2.4s (9.0% of total time) in 21 GCs | Peak RSS: 4.64GB | CPU load: 5.20
========================================================================================================================
Failed generating 'retry_trans_func_file' after 25.6s.
Error: Image build request failed with exit status 1
error: unable to create native image
```

### Steps to Reproduce

Do `bal build --native` with the latest master branch for the following code.
```bal
import ballerina/io;

public function main() returns error? {
    retry transaction {
        check doStage1();
        check doStage2();
        check commit;
    }
}

function doStage1() returns error? {
    io:println("Stage1 completed");
}

function doStage2() returns error? => error 'error:Retriable("Stage2 failed");
```

### Affected Version(s)

Latest master branch

### OS, DB, other environment details and versions

Both MacOS and Ubuntu

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/38826

**Comment by gabilang** [comment]
This issue has been observed with retry transaction which contains check-expr inside it. It's happening after done a fix to solve method too large errors which happened when a block has check-expr statements inside it and on-fail nodes added to the block. The above stacktrace observed when we have the retry-transaction block inside the `main` function (It is being observed with resource and remote functions as well). It's giving Non-reducible loop error with native-image build when the retry transaction block has been moved to a simple ballerina function other than main. From those observations it seems the above error somewhat has a correlation with Observability. 
Furthermore the error vanishes if an on-fail node added to the retry-transaction block.

**Comment by Nadeeshan96** [comment]
Need to improve the changes reverted in https://github.com/ballerina-platform/ballerina-lang/pull/39309.
