### ISSUE TITLE
[Bug]: Error occurs when doing a `bal test` for a multi-module ballerina package

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-lang#39154]
### Description

When I try to test a package with modules(each module has a test case). I'm getting following error.

```
Running Tests

        simple_test_w_module
error: 'void io.ballerina.runtime.internal.types.BTypeReferenceType.<init>(java.lang.String, io.ballerina.runtime.api.Module)'

        simple_test_w_module.util2


                1 passing
                0 failing
                0 skipped

        simple_test_w_module.util1


                1 passing
                0 failing
                0 skipped
error: there are test failures
```

stacktrace

```
Running Tests

        simple_test_w_module
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: 'void io.ballerina.runtime.internal.types.BTypeReferenceType.<init>(java.lang.String, io.ballerina.runtime.api.Module)'
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.run(TesterinaFunction.java:97)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.directInvoke(TesterinaFunction.java:68)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.startSuite(TesterinaUtils.java:165)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.execute(TesterinaUtils.java:151)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:99)
        at org.ballerinalang.test.runtime.BTestMain.startTestSuit(BTestMain.java:147)
        at org.ballerinalang.test.runtime.BTestMain.main(BTestMain.java:127)
Caused by: java.lang.NoSuchMethodError: 'void io.ballerina.runtime.internal.types.BTypeReferenceType.<init>(java.lang.String, io.ballerina.runtime.api.Module)'
        at ballerina.io.1.constants.$_typeref_type_constants.$typeref_type_init0(Unknown Source)
        at ballerina.io.1.constants.$_typeref_type_constants.<clinit>(Unknown Source)
        at ballerina.io.1.types.$_record_types.$populate$type$$anonType$_0$addField$(Unknown Source)
        at ballerina.io.1.types.$_record_types.$populate$type$$anonType$_0(Unknown Source)
        at ballerina.io.1.types.$_types.$createTypes(Unknown Source)
        at ballerina.io.1.$_init.$currentModuleInit(io)
        at ballerina.io.1.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at luheerathan.simple_test_w_module$test.0.$configurationMapper.$configureInit(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.run(TesterinaFunction.java:91)
        ... 6 more

        simple_test_w_module.util2


                1 passing
                0 failing
                0 skipped

        simple_test_w_module.util1


                1 passing
                0 failing
                0 skipped

```

### Affected Version(s)

2201.4.0 (master branch)

### Related area

-> Runtime

**Comment by Thevakumar-Luheerathan** [comment]
This is a caching issue. It works once the cache is cleared.
