### ISSUE TITLE
[Bug]: Test summary is not printed with `bal test --native` for APK service

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39399]
### Description

$Subject

### Steps to Reproduce

1. Clone the [APK repository](https://github.com/tharindu1st/apk/tree/main).
2. Go to the [`runtime-domain-service`](https://github.com/tharindu1st/apk/tree/main/runtime/runtime-domain-service) and build the project(`./graldew clean build -x test`).
3. Then go inside the [`runtime-domain-service/ballerina`](https://github.com/tharindu1st/apk/tree/main/runtime/runtime-domain-service/ballerina) directory and **delete the `Dependencies.toml` file**.
4. Then execute the following commands with the `bal` command obtained from the latest distribution(You can build the `ballerina-distribution` master to obtain the distribution zip and unzip it to use the `bal` command) :

```console
$ echo "NativeImageArgs = --report-unsupported-elements-at-runtime -H:+AddAllCharsets" > default.properties 
```

```console
$ bal test
```

**output** : 
```console
Running Tests

        runtime_domain_service
ballerina: HTTP trace log enabled
time = 2023-01-26T11:48:19.354+05:30 level = INFO module = wso2/runtime_domain_service message = "Initializing Runtime Domain Service.."
time = 2023-01-26T11:48:19.387+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-1078-8b1d-4f0e08a98bc5 state: true"
time = 2023-01-26T11:48:19.391+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\",\"object\":{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"kind\":\"ServiceMapping\",\"metadata\":{\"creationTimestamp\":\"2022-12-13T09:45:47Z\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:apiRef\":{\".\":{},\"f:name\":{},\"f:namespace\":{}},\"f:serviceRef\":{\".\":{},\"f:name\":{},\"f:namespace\":{}}}},\"manager\":\"ballerina\",\"operation\":\"Update\",\"time\":\"2022-12-13T09:45:47Z\"}],\"name\":\"01ed7aca-eb6b-1178-a200-f604a4ce114a-servicemapping\",\"namespace\":\"apk-platform\",\"resourceVersion\":\"5834\",\"selfLink\":\"/apis/dp.wso2.com/v1alpha1/namespaces/apk-platform/servicemappings/01ed7aca-eb6b-1178-a200-f604a4ce114a-servicemapping\",\"uid\":\"79d280d6-df31-4017-911f-3229955fdb55\"},\"spec\":{\"apiRef\":{\"name\":\"01ed7aca-eb6b-1178-a200-f604a4ce114a\",\"namespace\":\"apk-platform\"},\"serviceRef\":{\"name\":\"backend\",\"namespace\":\"apk\"}}}}"
time = 2023-01-26T11:48:19.412+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d41-3a02-1078-bb1e-800292ed7db6 state: true"
time = 2023-01-26T11:48:19.417+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-1078-bb1e-800292ed7db6 state: true"
time = 2023-01-26T11:48:19.421+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\", \"object\":{\"kind\":\"Service\", \"apiVersion\":\"v1\", \"metadata\":{\"name\":\"backend\", \"namespace\":\"apk\", \"selfLink\":\"/api/v1/namespaces/apk/services/backend\", \"uid\":\"275b00d1-722c-4df2-b65a-9b14677abe4b\", \"resourceVersion\":\"1514\", \"creationTimestamp\":\"2022-12-13T08:25:09Z\", \"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Service\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"backend\\\",\\\"namespace\\\":\\\"apk\\\"},\\\"spec\\\":{\\\"ports\\\":[{\\\"name\\\":\\\"http\\\",\\\"port\\\":80,\\\"targetPort\\\":80}],\\\"selector\\\":{\\\"app\\\":\\\"httpbin\\\"}}}\"}, \"managedFields\":[{\"manager\":\"kubectl-client-side-apply\", \"operation\":\"Update\", \"apiVersion\":\"v1\", \"time\":\"2022-12-13T08:25:09Z\", \"fieldsType\":\"FieldsV1\", \"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{}, \"f:kubectl.kubernetes.io/last-applied-configuration\":{}}}, \"f:spec\":{\"f:ports\":{\".\":{}, \"k:{\\\"port\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{}, \"f:name\":{}, \"f:port\":{}, \"f:protocol\":{}, \"f:targetPort\":{}}}, \"f:selector\":{\".\":{}, \"f:app\":{}}, \"f:sessionAffinity\":{}, \"f:type\":{}}}}]}, \"spec\":{\"ports\":[{\"name\":\"http\", \"protocol\":\"TCP\", \"port\":80, \"targetPort\":80}], \"selector\":{\"app\":\"httpbin\"}, \"clusterIP\":\"10.98.200.176\", \"type\":\"ClusterIP\", \"sessionAffinity\":\"None\"}, \"status\":{\"loadBalancer\":{}}}}"
time = 2023-01-26T11:48:19.441+05:30 level = DEBUG module = wso2/runtime_domain_service message = "ServiceWebsocket Client connection closed conectionId: 01ed9d41-3a02-1078-bb1e-800292ed7db6"
time = 2023-01-26T11:48:19.453+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Reinitializing client.."
time = 2023-01-26T11:48:19.458+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d41-3a02-1078-ba30-c37e98607600 state: true"
time = 2023-01-26T11:48:19.460+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-1078-ba30-c37e98607600 state: true"
time = 2023-01-26T11:48:19.463+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\", \"object\":{\"kind\":\"Service\", \"apiVersion\":\"v1\", \"metadata\":{\"name\":\"backend-1\", \"namespace\":\"apk\", \"selfLink\":\"/api/v1/namespaces/apk/services/backend\", \"uid\":\"275b00d1-722c-4df2-b65a-9b14678abe4b\", \"resourceVersion\":\"1517\", \"creationTimestamp\":\"2022-12-13T08:30:09Z\", \"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Service\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"backend-1\\\",\\\"namespace\\\":\\\"apk\\\"},\\\"spec\\\":{\\\"ports\\\":[{\\\"name\\\":\\\"http\\\",\\\"port\\\":80,\\\"targetPort\\\":80}],\\\"selector\\\":{\\\"app\\\":\\\"httpbin\\\"}}}\\n\"}, \"managedFields\":[{\"manager\":\"kubectl-client-side-apply\", \"operation\":\"Update\", \"apiVersion\":\"v1\", \"time\":\"2022-12-13T08:25:09Z\", \"fieldsType\":\"FieldsV1\", \"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{}, \"f:kubectl.kubernetes.io/last-applied-configuration\":{}}}, \"f:spec\":{\"f:ports\":{\".\":{}, \"k:{\\\"port\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{}, \"f:name\":{}, \"f:port\":{}, \"f:protocol\":{}, \"f:targetPort\":{}}}, \"f:selector\":{\".\":{}, \"f:app\":{}}, \"f:sessionAffinity\":{}, \"f:type\":{}}}}]}, \"spec\":{\"ports\":[{\"name\":\"http\", \"protocol\":\"TCP\", \"port\":80, \"targetPort\":80}], \"selector\":{\"app\":\"httpbin\"}, \"clusterIP\":\"10.98.200.176\", \"type\":\"ClusterIP\", \"sessionAffinity\":\"None\"}, \"status\":{\"loadBalancer\":{}}}}"
time = 2023-01-26T11:48:19.477+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d41-3a02-1078-ba30-c37e98607600 state: true"
time = 2023-01-26T11:48:19.482+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-1078-ba30-c37e98607600 state: true"
[2023-01-26 11:48:19,490] SEVERE {b7a.log.crash} - no cases registered for member function 'readMessage' of object type '$anonType$_3'. 
io.ballerina.runtime.internal.util.exceptions.BallerinaException: no cases registered for member function 'readMessage' of object type '$anonType$_3'.
        at org.ballerinalang.testerina.natives.mock.GenericMockObjectValue.call(GenericMockObjectValue.java:77)
        at wso2.runtime_domain_service.0.watchServices.readServiceEvents(watchServices.bal:176)
        at wso2.runtime_domain_service.0.watchServices.$lambda$_8(watchServices.bal:54)
        at wso2.runtime_domain_service.0.$value$ServiceTask.$lambda$_8$lambda0$(watchServices.bal:33)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
time = 2023-01-26T11:48:19.611+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-1078-9707-e6f9d79cc6bc state: true"
time = 2023-01-26T11:48:19.639+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\",\"object\":{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"kind\":\"API\",\"metadata\":{\"creationTimestamp\":\"2022-12-13T18:51:26Z\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:apiDisplayName\":{},\"f:apiType\":{},\"f:apiVersion\":{},\"f:context\":{},\"f:definitionFileRef\":{},\"f:prodHTTPRouteRef\":{}}},\"manager\":\"ballerina\",\"operation\":\"Update\",\"time\":\"2022-12-13T18:51:26Z\"}],\"name\":\"01ed7b16-90f7-1a88-8113-a7e71796d460\",\"namespace\":\"apk-platform\",\"resourceVersion\":\"28702\",\"selfLink\":\"/apis/dp.wso2.com/v1alpha1/namespaces/apk-platform/apis/01ed7b16-90f7-1a88-8113-a7e71796d460\",\"uid\":\"8a1eb4f9-efab-4682-a051-4df4050812d2\"},\"spec\":{\"apiDisplayName\":\"pizzashackAPI6\",\"apiType\":\"HTTP\",\"apiVersion\":\"1.0.0\",\"context\":\"/pizzashack6/1.0.0\",\"organization\":\"carbon.super\",\"definitionFileRef\":\"01ed7b16-90f7-1a88-8113-a7e71796d460-definition\",\"prodHTTPRouteRef\":\"01ed7b16-90f7-1a88-8113-a7e71796d460-production\"}}}"
time = 2023-01-26T11:48:19.668+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Websocket Client connection closed conectionId: 01ed9d41-3a02-1078-9707-e6f9d79cc6bc state: false"
time = 2023-01-26T11:48:19.686+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Reinitializing client.."
time = 2023-01-26T11:48:19.694+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d41-3a02-107e-83b5-519636b853ee state: true"
time = 2023-01-26T11:48:19.696+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-107e-83b5-519636b853ee state: true"
time = 2023-01-26T11:48:19.699+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\",\"object\":{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"kind\":\"API\",\"metadata\":{\"creationTimestamp\":\"2022-12-14T18:51:26Z\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:apiDisplayName\":{},\"f:apiType\":{},\"f:apiVersion\":{},\"f:context\":{},\"f:definitionFileRef\":{},\"f:prodHTTPRouteRef\":{}}},\"manager\":\"ballerina\",\"time\":\"2022-12-13T09:45:47Z\",\"operation\":\"Update\",\"fieldsType\":\"FieldsV1\"}],\"name\":\"01ed7b16-90f7-1a88-8114-a7e71796d460\",\"namespace\":\"apk-platform\",\"resourceVersion\":\"28712\",\"selfLink\":\"/apis/dp.wso2.com/v1alpha1/namespaces/apk-platform/apis/01ed7b16-90f7-1a88-8114-a7e71796d460\",\"uid\":\"8a1eb4f9-efab-4682-a051-4df4050812d2\"},\"spec\":{\"apiDisplayName\":\"DemoAPI\",\"apiType\":\"HTTP\",\"apiVersion\":\"1.0.0\",\"context\":\"/demoapi/1.0.0\",\"definitionFileRef\":\"01ed7b16-90f7-1a88-8114-a7e71796d460-definition\",\"prodHTTPRouteRef\":\"01ed7b16-90f7-1a88-8114-a7e71796d460-production\",\"organization\":\"carbon.super\"}}}"
time = 2023-01-26T11:48:19.705+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d41-3a02-107e-83b5-519636b853ee state: true"
[2023-01-26 11:48:19,706] SEVERE {b7a.log.crash} - no cases registered for member function 'readMessage' of object type '$anonType$_3'. 
io.ballerina.runtime.internal.util.exceptions.BallerinaException: no cases registered for member function 'readMessage' of object type '$anonType$_3'.
        at org.ballerinalang.testerina.natives.mock.GenericMockObjectValue.call(GenericMockObjectValue.java:77)
        at wso2.runtime_domain_service.0.watchApis.readAPIEvent(watchApis.bal:123)
        at wso2.runtime_domain_service.0.watchApis.$lambda$_6(watchApis.bal:53)
        at wso2.runtime_domain_service.0.$value$APIListingTask.$lambda$_6$lambda0$(watchApis.bal:34)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 


                30 passing
                0 failing
                0 skipped
```

```console
$ NATIVE_IMAGE_CONFIG_FILE=$(pwd)/default.properties  bal test --native
```

**output** :
```console
Running Tests

        runtime_domain_service
ballerina: HTTP trace log enabled
time = 2023-01-26T12:56:39.966+05:30 level = INFO module = wso2/runtime_domain_service message = "Initializing Runtime Domain Service.."
time = 2023-01-26T12:56:39.968+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d4a-c5cc-161e-8090-4f45c53e4d9c state: true"
time = 2023-01-26T12:56:39.968+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\",\"object\":{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"kind\":\"ServiceMapping\",\"metadata\":{\"creationTimestamp\":\"2022-12-13T09:45:47Z\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:apiRef\":{\".\":{},\"f:name\":{},\"f:namespace\":{}},\"f:serviceRef\":{\".\":{},\"f:name\":{},\"f:namespace\":{}}}},\"manager\":\"ballerina\",\"operation\":\"Update\",\"time\":\"2022-12-13T09:45:47Z\"}],\"name\":\"01ed7aca-eb6b-1178-a200-f604a4ce114a-servicemapping\",\"namespace\":\"apk-platform\",\"resourceVersion\":\"5834\",\"selfLink\":\"/apis/dp.wso2.com/v1alpha1/namespaces/apk-platform/servicemappings/01ed7aca-eb6b-1178-a200-f604a4ce114a-servicemapping\",\"uid\":\"79d280d6-df31-4017-911f-3229955fdb55\"},\"spec\":{\"apiRef\":{\"name\":\"01ed7aca-eb6b-1178-a200-f604a4ce114a\",\"namespace\":\"apk-platform\"},\"serviceRef\":{\"name\":\"backend\",\"namespace\":\"apk\"}}}}"
time = 2023-01-26T12:56:39.970+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d4a-c5cc-161e-9b11-5591fbdd6a42 state: true"
time = 2023-01-26T12:56:39.970+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d4a-c5cc-161e-9b11-5591fbdd6a42 state: true"
time = 2023-01-26T12:56:39.970+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\", \"object\":{\"kind\":\"Service\", \"apiVersion\":\"v1\", \"metadata\":{\"name\":\"backend\", \"namespace\":\"apk\", \"selfLink\":\"/api/v1/namespaces/apk/services/backend\", \"uid\":\"275b00d1-722c-4df2-b65a-9b14677abe4b\", \"resourceVersion\":\"1514\", \"creationTimestamp\":\"2022-12-13T08:25:09Z\", \"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Service\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"backend\\\",\\\"namespace\\\":\\\"apk\\\"},\\\"spec\\\":{\\\"ports\\\":[{\\\"name\\\":\\\"http\\\",\\\"port\\\":80,\\\"targetPort\\\":80}],\\\"selector\\\":{\\\"app\\\":\\\"httpbin\\\"}}}\"}, \"managedFields\":[{\"manager\":\"kubectl-client-side-apply\", \"operation\":\"Update\", \"apiVersion\":\"v1\", \"time\":\"2022-12-13T08:25:09Z\", \"fieldsType\":\"FieldsV1\", \"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{}, \"f:kubectl.kubernetes.io/last-applied-configuration\":{}}}, \"f:spec\":{\"f:ports\":{\".\":{}, \"k:{\\\"port\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{}, \"f:name\":{}, \"f:port\":{}, \"f:protocol\":{}, \"f:targetPort\":{}}}, \"f:selector\":{\".\":{}, \"f:app\":{}}, \"f:sessionAffinity\":{}, \"f:type\":{}}}}]}, \"spec\":{\"ports\":[{\"name\":\"http\", \"protocol\":\"TCP\", \"port\":80, \"targetPort\":80}], \"selector\":{\"app\":\"httpbin\"}, \"clusterIP\":\"10.98.200.176\", \"type\":\"ClusterIP\", \"sessionAffinity\":\"None\"}, \"status\":{\"loadBalancer\":{}}}}"
time = 2023-01-26T12:56:39.971+05:30 level = DEBUG module = wso2/runtime_domain_service message = "ServiceWebsocket Client connection closed conectionId: 01ed9d4a-c5cc-161e-9b11-5591fbdd6a42"
time = 2023-01-26T12:56:39.972+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Reinitializing client.."
time = 2023-01-26T12:56:39.973+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d4a-c5cc-161e-940e-efab6003b276 state: true"
time = 2023-01-26T12:56:39.973+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d4a-c5cc-161e-940e-efab6003b276 state: true"
time = 2023-01-26T12:56:39.974+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\", \"object\":{\"kind\":\"Service\", \"apiVersion\":\"v1\", \"metadata\":{\"name\":\"backend-1\", \"namespace\":\"apk\", \"selfLink\":\"/api/v1/namespaces/apk/services/backend\", \"uid\":\"275b00d1-722c-4df2-b65a-9b14678abe4b\", \"resourceVersion\":\"1517\", \"creationTimestamp\":\"2022-12-13T08:30:09Z\", \"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Service\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"backend-1\\\",\\\"namespace\\\":\\\"apk\\\"},\\\"spec\\\":{\\\"ports\\\":[{\\\"name\\\":\\\"http\\\",\\\"port\\\":80,\\\"targetPort\\\":80}],\\\"selector\\\":{\\\"app\\\":\\\"httpbin\\\"}}}\\n\"}, \"managedFields\":[{\"manager\":\"kubectl-client-side-apply\", \"operation\":\"Update\", \"apiVersion\":\"v1\", \"time\":\"2022-12-13T08:25:09Z\", \"fieldsType\":\"FieldsV1\", \"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{}, \"f:kubectl.kubernetes.io/last-applied-configuration\":{}}}, \"f:spec\":{\"f:ports\":{\".\":{}, \"k:{\\\"port\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{}, \"f:name\":{}, \"f:port\":{}, \"f:protocol\":{}, \"f:targetPort\":{}}}, \"f:selector\":{\".\":{}, \"f:app\":{}}, \"f:sessionAffinity\":{}, \"f:type\":{}}}}]}, \"spec\":{\"ports\":[{\"name\":\"http\", \"protocol\":\"TCP\", \"port\":80, \"targetPort\":80}], \"selector\":{\"app\":\"httpbin\"}, \"clusterIP\":\"10.98.200.176\", \"type\":\"ClusterIP\", \"sessionAffinity\":\"None\"}, \"status\":{\"loadBalancer\":{}}}}"
time = 2023-01-26T12:56:39.975+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Intializd new Client Connection conectionId: 01ed9d4a-c5cc-161e-940e-efab6003b276 state: true"
time = 2023-01-26T12:56:39.975+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d4a-c5cc-161e-940e-efab6003b276 state: true"
[2023-01-26 12:56:39,976] SEVERE {b7a.log.crash} - no cases registered for member function 'readMessage' of object type '$anonType$_3'. 
io.ballerina.runtime.internal.util.exceptions.BallerinaException: no cases registered for member function 'readMessage' of object type '$anonType$_3'.
        at org.ballerinalang.testerina.natives.mock.GenericMockObjectValue.call(GenericMockObjectValue.java:77)
        at wso2.runtime_domain_service/0.watchServices.readServiceEvents(watchServices.bal:176)
        at wso2.runtime_domain_service/0.watchServices.$lambda$_8(watchServices.bal:54)
        at wso2.runtime_domain_service/0.$value$ServiceTask.$lambda$_8$lambda0$(watchServices.bal:33)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at io.ballerina.runtime.internal.scheduling.Scheduler.start(Scheduler.java:278)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.startSuite(TesterinaUtils.java:178)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.execute(TesterinaUtils.java:156)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:100)
        at org.ballerinalang.test.runtime.BTestMain.startTestSuit(BTestMain.java:147)
        at org.ballerinalang.test.runtime.BTestMain.main(BTestMain.java:127)
 
time = 2023-01-26T12:56:39.977+05:30 level = DEBUG module = wso2/runtime_domain_service message = "Using Client Connection conectionId: 01ed9d4a-c5cc-161e-8d40-83d9a5d1ccf4 state: true"
time = 2023-01-26T12:56:39.977+05:30 level = DEBUG module = wso2/runtime_domain_service message = "{\"type\":\"ADDED\",\"object\":{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"kind\":\"API\",\"metadata\":{\"creationTimestamp\":\"2022-12-13T18:51:26Z\",\"generation\":1,\"managedFields\":[{\"apiVersion\":\"dp.wso2.com/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\".\":{},\"f:apiDisplayName\":{},\"f:apiType\":{},\"f:apiVersion\":{},\"f:context\":{},\"f:definitionFileRef\":{},\"f:prodHTTPRouteRef\":{}}},\"manager\":\"ballerina\",\"operation\":\"Update\",\"time\":\"2
```

### Affected Version(s)

Ballerina Swan Lake Update 4

### OS, DB, other environment details and versions

MacOS with x64 architecture

### Related area

-> Test Framework

**Comment by Thevakumar-Luheerathan** [comment]
Similar issue(#39391) is identified in windows too. Logs are printed partially.
