### ISSUE TITLE
[Bug]: Compiler crashes for erronous regexp

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#39438]
### Description

_ = re `(?!`;

### Steps to Reproduce

```
[Error - 11:37:53 PM] Operation 'text/codeAction' failed! {uri: '/Users/chiran/Desktop/Test/bbe.bal', [45:21]- [45:21], error: 'For input string: ""'}
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:702)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.checkValidityOfOccurrences(BLangNodeBuilder.java:5572)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5563)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReBracedQuantifierNode.apply(ReBracedQuantifierNode.java:63)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5529)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReQuantifierNode.apply(ReQuantifierNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.lambda$transform$17(BLangNodeBuilder.java:5521)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5520)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReAtomQuantifierNode.apply(ReAtomQuantifierNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReSequenceNode.apply(ReSequenceNode.java:46)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createReDisjunctionNode(BLangNodeBuilder.java:5487)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createRegExpTemplateLiteral(BLangNodeBuilder.java:5478)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2454)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5421)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5394)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2977)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5293)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1664)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:63)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1567)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1545)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1523)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:653)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:552)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:419)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:202)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:312)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:339)
	at org.ballerinalang.langserver.codeaction.CompilerPluginCodeActionExtension.execute(CompilerPluginCodeActionExtension.java:87)
	at org.ballerinalang.langserver.codeaction.CompilerPluginCodeActionExtension.execute(CompilerPluginCodeActionExtension.java:71)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Affected Version(s)

2201.3.2

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
_ = re \`(?=abc)*\`;

Crashes with

```
[Error - 12:10:01 AM] CodeAction 'ExtractToFunctionCodeAction' failed! {, error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:148)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:116)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:134)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:169)
	at org.ballerinalang.langserver.common.utils.FunctionGenerator.generateTypeSignature(FunctionGenerator.java:51)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypeSymbols(CodeActionUtil.java:312)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:195)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleTypes(CodeActionUtil.java:180)
	at org.ballerinalang.langserver.codeaction.CodeActionUtil.getPossibleType(CodeActionUtil.java:151)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.getCodeActionsForStatements(ExtractToFunctionCodeAction.java:154)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.getCodeActions(ExtractToFunctionCodeAction.java:107)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$1(CodeActionRouter.java:104)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:95)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by pcnfernando** [comment]
```ballerina
  string a = "abc";
 _ = re `[${a}]`;
```

```
[Error - 9:22:12 AM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/chiran/Desktop/Test/bbe.bal', error: 'Syntax kind is not supported: INTERPOLATION_START_TOKEN'}
java.lang.RuntimeException: Syntax kind is not supported: INTERPOLATION_START_TOKEN
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2395)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.Token.apply(Token.java:114)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5798)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReCharSetRangeNoDashNode.apply(ReCharSetRangeNoDashNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5778)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReCharSetRangeNoDashWithReCharSetNode.apply(ReCharSetRangeNoDashWithReCharSetNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5724)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReCharSetAtomNoDashWithReCharSetNoDashNode.apply(ReCharSetAtomNoDashWithReCharSetNoDashNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5706)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReCharSetAtomWithReCharSetNoDashNode.apply(ReCharSetAtomWithReCharSetNoDashNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5684)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReCharacterClassNode.apply(ReCharacterClassNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5517)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReAtomQuantifierNode.apply(ReAtomQuantifierNode.java:51)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5498)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ReSequenceNode.apply(ReSequenceNode.java:46)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createReDisjunctionNode(BLangNodeBuilder.java:5487)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createRegExpTemplateLiteral(BLangNodeBuilder.java:5478)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2454)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5421)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5394)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2977)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2952)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5293)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1664)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:63)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1567)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1545)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1523)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:653)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:513)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:552)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:419)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:202)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:312)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:339)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:276)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:225)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:950)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:658)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by SasinduDilshara** [comment]
Compiler crash for following code as well

```
public function main() {
   string a = "GB";
  string:RegExp x7 = re `[A\sA-${a}\WC\DJ-Kd\\]*`;
}

```

**Comment by SasinduDilshara** [comment]
Compiler crash for following code as well.

```
public function main() {
  string a = "ABC";
  int aa = 1;
  string:RegExp x7 = re `([?m-i:\?${a})]`;
  io:println(x7.findAll(":ABCabc").toBalString());
}

```

**Comment by pcnfernando** [comment]
```ballerina
    _ = re `${1,2`;
    _ = re `${1,2}`;
```

```
[2023-02-16 09:59:51,203] SEVERE {b7a.log.crash} - Syntax kind is not supported: DECIMAL_INTEGER_LITERAL_TOKEN 
java.lang.RuntimeException: Syntax kind is not supported: DECIMAL_INTEGER_LITERAL_TOKEN
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2401)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.LiteralValueToken.apply(LiteralValueToken.java:40)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createRawTemplateLiteral(BLangNodeBuilder.java:5469)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2458)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5427)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5400)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3116)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ExpressionStatementNode.apply(ExpressionStatementNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5299)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1670)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:63)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1573)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1551)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1529)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:654)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:553)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:419)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:202)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:148)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:256)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:126)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
