### ISSUE TITLE
[Bug]: Compiler crash in nested from-clause

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#39497]
### Description

```ballerina
public function main() {
    var input = [{name: "Saman", price: 11}];
    var res = from var {name} in input
                select from var {price} in input
                        select {name, price}; 
}
```
This code crashes with following stacktrace.
```
[2023-02-02 20:42:12,051] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.createFunctionInfoArray(MainMethodGen.java:341)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.loadCLIArgsForMain(MainMethodGen.java:298)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateUserMainFunctionCall(MainMethodGen.java:273)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateMainMethod(MainMethodGen.java:167)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:428)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1040)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:399)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:810)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:317)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Steps to Reproduce

Check the description

### Affected Version(s)

Ballerina 2201.3.0 (Swan Lake Update 3)

### Related area

-> Compilation

**Comment by hasithaa** [comment]
@TharushiJay Hope you are addressing this as well, https://github.com/ballerina-platform/ballerina-lang/issues/39506
