### ISSUE TITLE
[Bug]: Nested from clauses cause compiler crash with NegativeArraySizeException

### ISSUE THREAD

**Issue by ImeshBalasuriya** [ballerina-platform/ballerina-lang#39506]
### Description

The following code fails to compile and the compiler crashes with an error message.

```ballerina
import ballerina/io;

type House record {|
    string address;
    boolean owner;
|};

type Person record {
    string name;
    int age;
    House[] houses;
};

type HomeOwner record {|
    string name;
    string primaryAddress;
|};

isolated function selectHomeOwners(Person[] people) 
    returns HomeOwner[] => (
    from var person in people
        where person.age >= 18
        
        let string[] ownedHouses = from var house in person.houses
            where house.owner
            select house.address
        where ownedHouses.length() > 0

        select {
            name: person.name,
            primaryAddress: ownedHouses[0]
        }
);

public function main() {
    Person[] people = [
        {name:"Mark", age:14, houses:[]},
        {name:"Watson", age:40, houses:[{address:"221B Baker Street", owner:false}]},
        {name:"Walter", age:23, houses:[{address:"308 Negra Arroyo Lane", owner: true}]}
    ];

    HomeOwner[] homeOwners = selectHomeOwners(people);

    foreach var person in homeOwners {
        io:println(person);
    }

}
```

*Compiler Crash Log:*
```
[2023-02-06 10:31:24,467] SEVERE {b7a.log.crash} - -1 
java.lang.NegativeArraySizeException: -1
        at org.objectweb.asm.Frame.merge(Frame.java:1222)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:303)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:173)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:446)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1040)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:399)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:810)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:317)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

However, extracting the nested `from` clause into a separate function as follows prevents the crash and the code runs as expected.
```ballerina
isolated function selectHomeOwners(Person[] people) 
    returns HomeOwner[] => (
    from var person in people
        where person.age >= 18
        
        let string[] ownedHouses = selectOwnedHouses(person.houses)
        where ownedHouses.length() > 0

        select {
            name: person.name,
            primaryAddress: ownedHouses[0]
        }
);

isolated function selectOwnedHouses(House[] houses) returns string[] {
    return from var house in houses
        where house.owner
        select house.address;
}
```

Removing the `where person.age >= 18` clause also seems to prevent the crash. However, this changes the functionality of the code so it is not a viable workaround.

### Affected Version(s)

2201.3.2 (Swan Lake Update 3)

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/39497
https://github.com/ballerina-platform/ballerina-lang/issues/35254

**Comment by lochana-chathura** [comment]
This is already fixed in update 6. A test case was added with #39955
