### ISSUE TITLE
[Bug]: CCE in HoverSymbolResolver

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#39538]
### Description

```ballerina
public class Context {

    private Context? originalCtx;
    private map<valu<cursor>e:Cloneable> 
}
```
Hover over the cursor. I get the following error:
```java
[Error - 1:30:34 PM] Operation 'text/hover' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test2.bal', [5:20], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaMapTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaMapTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaMapTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaMapTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.hover.HoverSymbolResolver.findAndSetSymbolConstructKind(HoverSymbolResolver.java:84)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.hover.HoverSymbolResolver.transform(HoverSymbolResolver.java:75)
	at org.ballerinalang.langserver.hover.HoverSymbolResolver.transform(HoverSymbolResolver.java:43)
	at io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode.apply(QualifiedNameReferenceNode.java:54)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:101)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:172)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Affected Version(s)

2201.4.0-SNAPSHOT

### Related area

-> Editor

**Comment by mindula** [comment]
This will be fixed with #39712
