### ISSUE TITLE
[Bug]: IllegalArgumentException in extract to function and local variable code actions

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#39537]
### Description

Consider the following scenario,

<img width="650" alt="Screenshot 2023-02-08 at 10 37 41" src="https://user-images.githubusercontent.com/61020198/217439437-ee01b510-f260-46ff-8c2f-59e5b70bd512.png">

When the cursor is positioned as shown above, it throws an IllegalArgumentException.

```
[Error - 10:37:21 AM] CodeAction 'ExtractToFunctionCodeAction' failed! {, error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:149)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:116)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:134)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:169)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.getFunction(ExtractToFunctionCodeAction.java:426)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.getCodeActionsForExpressions(ExtractToFunctionCodeAction.java:380)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToFunctionCodeAction.getCodeActions(ExtractToFunctionCodeAction.java:104)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$1(CodeActionRouter.java:104)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:95)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[Error - 10:37:21 AM] CodeAction 'ExtractToLocalVarCodeAction' failed! {, error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:149)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:116)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:134)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:169)
	at org.ballerinalang.langserver.codeaction.providers.ExtractToLocalVarCodeAction.getCodeActions(ExtractToLocalVarCodeAction.java:128)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$1(CodeActionRouter.java:104)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:95)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### Steps to Reproduce

```
function testRegExp(string:RegExp name) {
    string:RegExp letExpr = let string:RegExp it<cursor>em = re `${name}` in re `car, van`;
}
```

### Related area

-> Editor

**Comment by mindula** [comment]
In both extract to function and extract to variable code actions, we take the signature of typeSymbol and the signature of regex is null. Hence, this issue occurs in both code actions. 
This issue might get fixed with #39509.

**Comment by IMS94** [comment]
@mindula shall we verify if this is fixed? The mentioned PR had been merged.

**Comment by mindula** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39509
