### ISSUE TITLE
[Bug]: Mapping binding pattern fails for anonymous record type

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#39633]
### Description

Consider the following code
```ballerina
import ballerina/io;

type Representation record {
    string __typename;
};

public function main() returns error? {
    Representation representation = {__typename: "Product", "variation": {id: "10"}};
    record {
        string id?;
        string sku?;
        string package?;
        record {string id;} variation?;
    } {id, sku, package, variation} = check representation.ensureType(); // this crashes

    io:println(id, variation?.id);
}
```
The above code crashes with following error
```
[2023-02-16 12:59:49,370] SEVERE {b7a.log.crash} - $typedesc$$anonType$_0 
java.lang.NoClassDefFoundError: $typedesc$$anonType$_0
	at test.main(test.bal:0)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: $typedesc$$anonType$_0
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```

### Affected Version(s)

2201.4.0 RC2, 2201.3.0

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
We can simplify this issue as follows
```ballerina
type Representation record {
    string __typename;
};

public function main() returns error? {
    Representation representation = {__typename: "Product"};
    record {} {} = check representation.ensureType(); // this crashes
}
```
If the type is a type definition, it is working fine. The issue arises from not creating a typedesc for the anonymous record connect with mapping binding pattern

```ballerina
type Representation record {
    string __typename;
};

type Foo record {
    
};
public function main() returns error? {
    Representation representation = {__typename: "Product"};
    Foo {} = check representation.ensureType(); //Compile without crashing
}
```
