### ISSUE TITLE
[Bug]: NPE when printing Ballerina error stacktrace in ballerina-1.2.x

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#39954]
### Description

$title
Relevant stacktrace:
```
[2023-03-15 13:07:44,673] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException

        at org.ballerinalang.jvm.BallerinaErrors.filterStackTraceElement(BallerinaErrors.java:255)

        at org.ballerinalang.jvm.values.ErrorValue.getStackTrace(ErrorValue.java:192)

        at org.ballerinalang.jvm.values.ErrorValue.getPrintableStackTrace(ErrorValue.java:208)

        at org.ballerinalang.net.http.HttpUtil.handleFailure(HttpUtil.java:415)

        at org.ballerinalang.net.http.HttpCallableUnitCallback.notifyFailure(HttpCallableUnitCallback.java:42)

        at org.ballerinalang.jvm.scheduling.Scheduler.postProcess(Scheduler.java:324)

        at org.ballerinalang.jvm.scheduling.Scheduler.run(Unknown Source)

        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Unknown Source)

        at java.base/java.lang.Thread.run(Unknown Source)
```

### Affected Version(s)

ballerina-1.2.x

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/wso2-enterprise/internal-support-ballerina/issues/292

**Comment by gabilang** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39924
