### ISSUE TITLE
[Bug]: `NullPointerException` at `JvmDesugarPhase.encodeTypeDefIdentifiers`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#40083]
### Description

$title

### Steps to Reproduce

```bal
public type Data Symbol|boolean|int|float|decimal|String|Data[];

type Relation "assert<"|"assert<>"|"assert=";
type Assertion [Relation, Type, Type];
type NameAtom [string, Atom];
type BoundAssertion ["let", NameAtom[], Assertion];
type Test Assertion|BoundAssertion;

public type sexprString readonly & record {|
    string s;
|};

public type Field [sexprString, Type];
public type Atom ["list", Type[]] | ["list", Type[], Type] | ["array", Type] | ["array", Type, int] | ["min-length-list", Type[], int] | ["min-length-list", Type[], int, Type] |
                 ["map", Type] | ["mapping", Field[]] | ["mapping", Field[], Type] |
                 ["cell", Type, CellMutability] |
                 ["function", Type[], Type];

public type Array ["array", Type];
public type ArrayFixedSize ["array", Type, int];
public type NonRepeatingTuple ["list", Type[]];

public type Type AtomRef | Union | Intersection | Not |
                 Nil |
                 Boolean | BooleanSingleShape |
                 Int | IntSingleShape | IntRange |
                 Float | FloatSubtype |
                 Decimal | DecimalSubtype |
                 String | StringSingleShape |
                 Error | ErrorSubtype |
                 Function | FunctionSubtype |
                 List |
                 Mapping |
                 Table | TableSubtype |
                 Xml | XmlSubtype |
                 Any | Readonly | Never;

public type AtomRef string;
public type Union ["|", Type...];
public type Intersection ["&", Type...];
public type Not ["!", Type...];
public type Nil Data[0];
public final Nil NIL_SEXPR = [];
public type Boolean "boolean";
public type BooleanSingleShape boolean;
public type Int "int";
public type IntRange ["int-range", int, int];
public type IntSingleShape int;
public type Float "float";
public type FloatSubtype ["float", sexprString];
public type Decimal "decimal";
public type DecimalSubtype ["decimal", sexprString];
public type StringSingleShape sexprString;
public type String "string";
public type Error "error";
public type ErrorSubtype ["error", Type];
public type Function "function";
public type FunctionSubtype ["function", Type[], Type];
public type List "list";
public type Mapping "mapping";
public type Table "table";
public type TableSubtype ["table", Type];
public type Xml "xml";
public type XmlBuiltinSubtypeNames "text"|"element_ro"|"pi_ro"|"comment_ro"|"element_rw"|"pi_rw"|"comment_rw"|"element"|"pi"|"comment";
public type XmlSubtype ["xml", 1|"*", XmlBuiltinSubtypeNames...]|["xml", 0];

public type Cell ["cell", Type, CellMutability];
public type CellMutability "none"|"limited"|"unlimited";

public type Any "any";
public type Readonly "readonly";
public type Never "never";

public type Symbol string;

public function main() {
    Data testSexpr = ["let",[["int-none-cell",["cell","int","none"]],["int-limited-cell",["cell","int","limited"]],["byte-unlimited-cell",["cell",["int-range",0,255],"unlimited"]],["byte-limited-cell",["cell",["int-range",0,255],"limited"]]],["assert<",["&","int-none-cell","int-limited-cell","byte-unlimited-cell"],"byte-limited-cell"]];
    Test test = checkpanic testSexpr.cloneWithType();
}
```
gives
```
Compiling source
        nbalfail.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

[2023-04-03 18:58:54,152] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmDesugarPhase.encodeTypeDefIdentifiers(JvmDesugarPhase.java:192)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmDesugarPhase.encodeModuleIdentifiers(JvmDesugarPhase.java:179)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:93)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:318)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:171)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:191)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Affected Version(s)

Ballerina 2201.5.0 (Swan Lake Update 5) snapshot

### Related area

-> Compilation

**Comment by HindujaB** [comment]
Simplified code
```ballerina
public type Data int|Data[];

public type Type "string" | EmptyArray;

public type EmptyArray Data[0];

public function main() {
}
```

**Comment by HindujaB** [comment]
Fixing https://github.com/ballerina-platform/ballerina-lang/issues/40422 will fix this issue.

**Comment by prakanth97** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/39589
