### ISSUE TITLE
[Bug]: Using xml namespace gives bad sad in `1.2.x`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#40107]
### Description

```bal
import ballerina/io;
public function main() {
    io:println(xmlWithDefaultNamespace());
}

public function xmlWithDefaultNamespace() returns string {
    xmlns "http://atestorgthatdoesntexist.org/";
    xml body2 = xml `<Add>
                     <intA foo="bar">12</intA>
                   </Add>`;
    string s2 = body2.toString();
    return s2;
}
```

Gives

```
[2023-04-04 18:22:54,976] SEVERE {b7a.log.crash} - failed to get xml as string: error occurred during writing the message to the output stream: {ballerina/lang.xml}XMLOperationError 
org.ballerinalang.jvm.util.exceptions.BallerinaException: failed to get xml as string: error occurred during writing the message to the output stream: {ballerina/lang.xml}XMLOperationError
	at org.ballerinalang.jvm.values.XMLValue.handleXmlException(XMLValue.java:136)
	at org.ballerinalang.jvm.values.XMLItem.stringValue(XMLItem.java:499)
	at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:91)
	at org.ballerinalang.langlib.value.ToString.toString(ToString.java:43)
	at ballerina.lang_value.value.toString(value.bal:86)
	at test.xmlWithDefaultNamespace(test.bal:21)
	at test.main(test.bal:13)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:489)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:261)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:229)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Seem this is fixed in SL Update 4, but exists in 1.2.37. Need to enable `XMLLiteralTest.xmlWithDefaultNamespace` after fixing this in `ballerina-1.2.x` branch

### Affected Version(s)

1.2.37

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment]
In the `BallerinaXMLSerializer`, the constant `XML_NS_URI_PREFIX` was incorrectly set and was not used properly. Hence, fixed that with https://github.com/ballerina-platform/ballerina-lang/pull/40301.

**Comment by Nadeeshan96** [comment]
This issue is caused due to a bug in the front-end before the Desugar phase. If we see the `BLangPackage` which goes into the Desugar phase, there the namespace URI is incorrectly set for the xml value `body2`. Hence during the codegen when creating the `XMLQName`s, it passes the above "http://atestorgthatdoesntexist.org/" instead of `null` for the namespace URI.
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/33286289/234808938-596e503f-97cc-4e65-9a81-ab0b7cc1d609.png">
If I set each of the irrelevant `namespaceURI` and `nsSymbol` as `null`, the issue get fixed.
 
The issue is fixed in the swan lake version and the following can be seen.
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/33286289/234821102-7420dd8c-ab07-4ef9-b7c5-bf3390410039.png">
