### ISSUE TITLE
[Bug]: Crash match-stmt in side do-clause

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#40200]
### Description

$subject

### Steps to Reproduce

```ballerina
public function main() {
    var input = [{name: "Saman", price1: [11, 12]}, 
                    {name: "Saman", price1: [19, 20]}];
    _ = from var {name, price1} in input
                do {
                    match name {
                        var a => {}
                    }
                };
}
```

### Affected Version(s)

2201.4.1

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
Seems the visotr in QueryDesugar has not been implemented. Getting an AssertionError
```
[2023-07-06 10:22:26,232] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:378)
        at org.wso2.ballerinalang.compiler.tree.matchpatterns.BLangVarBindingPatternMatchPattern.accept(BLangVarBindingPatternMatchPattern.java:40)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.acceptNode(QueryDesugar.java:2746)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:2499)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangMatchClause.accept(BLangMatchClause.java:60)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.acceptNode(QueryDesugar.java:2746)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:2494)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:77)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.rewrite(QueryDesugar.java:2754)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.rewrite(QueryDesugar.java:2763)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1636)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.rewrite(QueryDesugar.java:2754)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1620)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.rewrite(QueryDesugar.java:2754)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.visit(QueryDesugar.java:1603)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLambdaFunction.accept(BLangLambdaFunction.java:64)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.addDoFunction(QueryDesugar.java:952)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.buildStream(QueryDesugar.java:556)
        at org.wso2.ballerinalang.compiler.desugar.QueryDesugar.desugar(QueryDesugar.java:400)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8538)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangQueryAction.accept(BLangQueryAction.java:47)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8961)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2525)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8936)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8974)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8980)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1379)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8936)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1425)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8936)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:829)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8936)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:173)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:142)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:120)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:119)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:225)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:56)
```
