### ISSUE TITLE
[Bug]: Getting `BadSadError` for error sub typing with intersection

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#40273]
### Description

$Subject

### Steps to Reproduce

Run the following sample:
```bal
type ListenerError distinct error;

type BadRequestError distinct error;

type QueryParameterBindingError distinct ListenerError & BadRequestError;

type QueryParameterValidationError distinct QueryParameterBindingError;

public function main() {
    QueryParameterValidationError err = error QueryParameterValidationError("Invalid query parameter");
}
```

```console
$ bal run

Compiling source
        tharmigan/constraint_tests:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-04-21 13:19:16,284] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:395)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:350)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExprSilent(TypeChecker.java:3609)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:3481)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:214)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangErrorConstructorExpr.accept(BLangErrorConstructorExpr.java:55)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:409)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:377)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1207)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4291)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4265)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2199)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:55)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4291)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4265)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4237)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:585)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4291)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:564)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4291)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4265)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:364)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:252)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:211)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:301)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:432)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:203)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:187)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:148)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:309)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:139)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [constraint_tests:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

### Affected Version(s)

Ballerina SwanLake 2201.5.0

### OS, DB, other environment details and versions

Mac OS with arm64

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
The compiler crashes for the below scenario as well. These two may be related.
```ballerina
type Error1 error;

type Error2 error;

type Error3 Error1|Error2;

type Error4 error & Error3;
```

<img width="1458" alt="Screenshot 2023-04-26 at 00 21 26" src="https://user-images.githubusercontent.com/46857198/234374626-8439c599-48ef-4fce-b0dc-fae21ff989b6.png">

**Comment by TharmiganK** [comment]
@rdulmina can I get a ETA for this? This seems to be a blocker for a feature we are planning for update 6

**Comment by rdulmina** [comment]
> @rdulmina can I get a ETA for this? This seems to be a blocker for a feature we are planning for update 6

Will provide a fix by this week

**Comment by rdulmina** [comment]
This issue is already fixed within a work that will be included in update 6 hence we decided to wait for that fix instead of fixing this separately since that is the ideal fix to do. https://github.com/ballerina-platform/ballerina-lang/pull/39589. This will be merged in may second week as earliest or at lease may 3rd week

**Comment by prakanth97** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/39589
