### ISSUE TITLE
[Bug]: Invalid JWT decode error

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [ballerina-platform/ballerina-lang#40408]
### Description

I tried to decode an invalid JWT and the following error got thrown.

[2023-05-12 10:35:22,303] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
        at xxx.$0046auth.1.auth.retrieveAuthInfo(auth.bal:22)
        at xxx.1.$value$RequestInterceptor.$default$^^(service.bal:21)
        at xxx.1.$value$RequestInterceptor.call(service.bal)
        at io.ballerina.runtime.api.Runtime.lambda$getFunction$1(Runtime.java:265)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)

### Steps to Reproduce

Used the following code. sent a invalid JWT as a payload.

do {
        [jwt:Header, jwt:Payload]|jwt:Error [_, payload] = jwt:decode(authHeader);
        return check imposeGlobalRules(payload);
    } on fail error err {
        log:printWarn(string `JWT authentication failed with: ${err.message()}`);
        return utils:getHTTPUnauthorizedRequestResponse("JWT authentication failed");
    }

### Affected Version(s)

Ballerina 2201.4.1

### Related area

-> Runtime

**Comment by MaryamZi** [comment]
This is because of the following line

```ballerina
[jwt:Header, jwt:Payload]|jwt:Error [_, payload] = jwt:decode(authHeader);
```

A list binding pattern can be used only when the type is the list (tuple). This should have resulted in a compilation error and is being tracked in https://github.com/ballerina-platform/ballerina-lang/issues/39690.

Handling the error and changing the type will resolve the issue,

```ballerina
[jwt:Header, jwt:Payload] [_, payload] = check jwt:decode(authHeader); // changed the type and used check
```
