### ISSUE TITLE
[Bug]: bal pack with different org name/ package name results in NPE if the target is not cleared

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#40478]
### Description

`bal pack` with different org name/ package name results in NPE if the target is not cleared. Clearing the target and re-trying fixes issue.

### Steps to Reproduce

- Build a ballerina package using `bal pack`
- Rename the org name, package name of the package and re-build
- results in the following error

```
[2023-05-19 20:13:05,919] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
    at io.ballerina.projects.util.ProjectUtils.isProjectUpdated(ProjectUtils.java:994)
    at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:240)
    at java.base/java.util.Optional.ifPresent(Optional.java:183)
    at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### OS, DB, other environment details and versions

Ballerina SL 2201.5.0

### Related area

-> Other Area

**Comment by Thevakumar-Luheerathan** [comment]
We couldn't reproduce the issue. Please reopen the issue if it persists
