### ISSUE TITLE
[Bug]: Compiler crash for regex with interpolations

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40499]
### Description

Following code

```
const string:RegExp INVALID_PLANAR_PATTERN = re `([\w|\s]*[\-|\?|:|] [\w|\s]*)|([\w|\s]* #[\w|\s]*)|([,|\[|\]|\{|\}|&\*|!\||>|\'|\"|%|@|${"`"}][\w|\s]*)`;

public function main() {
    _ = INVALID_PLANAR_PATTERN.find("");
}
```

Crashes the compiler

```
Compiling source
        test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-05-24 14:21:42,237] SEVERE {b7a.log.crash} - Syntax kind is not supported: INTERPOLATION_START_TOKEN 
java.lang.RuntimeException: Syntax kind is not supported: INTERPOLATION_START_TOKEN
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2401)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.Token.apply(Token.java:114)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5727)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ReCharSetAtomNoDashWithReCharSetNoDashNode.apply(ReCharSetAtomNoDashWithReCharSetNoDashNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5729)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ReCharSetAtomNoDashWithReCharSetNoDashNode.apply(ReCharSetAtomNoDashWithReCharSetNoDashNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5729)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ReCharSetAtomNoDashWithReCharSetNoDashNode.apply(ReCharSetAtomNoDashWithReCharSetNoDashNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5729)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ReCharSetAtomNoDashWithReCharSetNoDashNode.apply(ReCharSetAtomNoDashWithReCharSetNoDashNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:5729)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
```

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
Simplified form of this pattern is,
```ballerina
string:RegExp INVALID_PLANAR_PATTERN = re `[\]${"`"}]`;
```

**Comment by LakshanWeerasinghe** [comment]
Below is another compiler crash,

```ballerina
string:RegExp _ = re `\[${"ABC"}`;
```

The compiler crash occurs because it mistakenly interprets the escaped open bracket token as the start of a no-nterpolation context , thereby preventing the processing of interpolations after the open bracket.
