### ISSUE TITLE
[Bug]:  Multiple LS operations fail with `CANNOT_INFER_TYPE_FOR_PARAM` exception

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-lang#40647]
### Description

LS features are not working properly when using the package 'ballerinax:java.jdbc:1.5.0' with the following logs

```
[Error - 11:40:41] Operation 'text/hover' failed! {uri: '/Users/tharinduu/Ballerina/ballerina-registry/projects/ballerina_update_tool_api/ballerina_update_tool.bal', [236:43], error: 'The compiler extension in package 'ballerinax:java.jdbc:1.5.0' failed to complete. CANNOT_INFER_TYPE_FOR_PARAM'}
io.ballerina.projects.ProjectException: The compiler extension in package 'ballerinax:java.jdbc:1.5.0' failed to complete. CANNOT_INFER_TYPE_FOR_PARAM
	at io.ballerina.projects.SyntaxNodeAnalysisTask.perform(SyntaxNodeAnalysisTask.java:62)
	at io.ballerina.projects.SyntaxTreeVisitor.runAnalysisTasks(SyntaxTreeVisitor.java:93)
	at io.ballerina.projects.SyntaxTreeVisitor.visitSyntaxNode(SyntaxTreeVisitor.java:80)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:295)
	at io.ballerina.compiler.syntax.tree.RemoteMethodCallActionNode.accept(RemoteMethodCallActionNode.java:61)
	
```

### Affected Version(s)

Checked with Ballerina versions: 2201.4.2, 2201.5.0
VSCode extension: 4.2.3

### Related area

-> Editor

**Comment by malinthar** [comment]
Simplified version of the above

```ballerina
import ballerinax/java.jdbc;
import ballerina/cache;
import ballerina/sql;
import ballerina/os;

configurable string updateToolDbUrl = ?;
configurable string updateToolDbUsername = ?;
configurable int maxPoolSize = ?;

final jdbc:Client dbClient = check new (
    updateToolDbUrl,
    updateToolDbUsername,
    os:getEnv("UPDATE_TOOL_DB_PASSWORD"),
    connectionPool = {
        maxOpenConnections: maxPoolSize
    },
    options = {
        requestGeneratedKeys: jdbc:EXECUTE
    }
);

# Checks whether the latest tool version is compatible with the current tool version
#
# + currentToolVersion - The current tool version
# + return - True if compatible
public isolated function checkBackwardCompatibility(string releasesAfterCurrent) returns boolean|error {
    sql:ParameterizedQuery query = `SELECT compatibility FROM [dbo].latests WHERE version IN (1.0)`;
    string compatibilityList = dbClient->query(query);
    boolean compatibility = true;
    return compatibility;
}
```

`bal build` fails with the following error
![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/bacf7d2b-f7c3-456b-8961-7edd6ba8431a)

Ballerina.toml
```toml
# AUTO-GENERATED FILE. DO NOT MODIFY.

# This file is auto-generated by Ballerina for managing dependency versions.
# It should not be modified by hand.

[ballerina]
dependencies-toml-version = "2"
distribution-version = "2201.5.0"

[[package]]
org = "ballerina"
name = "cache"
version = "3.5.0"
dependencies = [
	{org = "ballerina", name = "constraint"},
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "task"},
	{org = "ballerina", name = "time"}
]
modules = [
	{org = "ballerina", packageName = "cache", moduleName = "cache"}
]

[[package]]
org = "ballerina"
name = "constraint"
version = "1.2.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]

[[package]]
org = "ballerina"
name = "io"
version = "1.4.1"
dependencies = [
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "lang.value"}
]

[[package]]
org = "ballerina"
name = "jballerina.java"
version = "0.0.0"

[[package]]
org = "ballerina"
name = "lang.object"
version = "0.0.0"

[[package]]
org = "ballerina"
name = "lang.regexp"
version = "0.0.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]

[[package]]
org = "ballerina"
name = "lang.string"
version = "0.0.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "lang.regexp"}
]

[[package]]
org = "ballerina"
name = "lang.value"
version = "0.0.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]

[[package]]
org = "ballerina"
name = "observe"
version = "1.0.7"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]

[[package]]
org = "ballerina"
name = "os"
version = "1.6.0"
dependencies = [
	{org = "ballerina", name = "io"},
	{org = "ballerina", name = "jballerina.java"}
]
modules = [
	{org = "ballerina", packageName = "os", moduleName = "os"}
]

[[package]]
org = "ballerina"
name = "sql"
version = "1.5.0"
dependencies = [
	{org = "ballerina", name = "io"},
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "lang.object"},
	{org = "ballerina", name = "time"}
]
modules = [
	{org = "ballerina", packageName = "sql", moduleName = "sql"}
]

[[package]]
org = "ballerina"
name = "task"
version = "2.3.2"
dependencies = [
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "time"}
]

[[package]]
org = "ballerina"
name = "time"
version = "2.2.5"
dependencies = [
	{org = "ballerina", name = "jballerina.java"}
]

[[package]]
org = "ballerinai"
name = "observe"
version = "0.0.0"
dependencies = [
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "observe"}
]
modules = [
	{org = "ballerinai", packageName = "observe", moduleName = "observe"}
]

[[package]]
org = "ballerinax"
name = "java.jdbc"
version = "1.5.0"
dependencies = [
	{org = "ballerina", name = "io"},
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "lang.string"},
	{org = "ballerina", name = "sql"},
	{org = "ballerina", name = "time"}
]
modules = [
	{org = "ballerinax", packageName = "java.jdbc", moduleName = "java.jdbc"}
]

[[package]]
org = "malintha"
name = "jdbc_issue"
version = "0.1.0"
dependencies = [
	{org = "ballerina", name = "cache"},
	{org = "ballerina", name = "os"},
	{org = "ballerina", name = "sql"},
	{org = "ballerinai", name = "observe"},
	{org = "ballerinax", name = "java.jdbc"}
]
modules = [
	{org = "malintha", packageName = "jdbc_issue", moduleName = "jdbc_issue"}
]

```

**Comment by malinthar** [comment]
> I am unable to reproduce the exact error message. However, there is an error in the sample code above.
> 
> The [query](https://lib.ballerina.io/ballerinax/java.jdbc/1.5.0#Client-query) method is used to retrieve a stream of records. And the return type must be the same.
> 
> In this use case, if you are trying to retrieve a single string, the [queryRow](https://lib.ballerina.io/ballerinax/java.jdbc/1.5.0#Client-queryRow) method should be used. This method will retrieve only the first result from the resultSet (if exists).
> 
> ```ballerina
> string compatibilityList = check dbClient->queryRow(query);
> ```
> 
> If you are trying to retrieve a list (stream or array) of strings, you would have to do as follows
> 
> ```ballerina
> stream<record {| string compatibility; |}, sql:Error?> compatibilityStream = dbClient->query(query);
> string[] compatibilityList = check from record {|string compatibility;|} item in compatibilityStream
>     select item.compatibility;
> ```

Although there is an error in the code, it should be reported via a diagnostic. Here the compilation fails with an exception. Could you ensure that you are using java.jdbc 1.5.0 and sql 1.5.0 versions.
