### ISSUE TITLE
[Bug]: MockDesugar throws NPE with legacy function mocking

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#40731]
### Description

When using legacy function mocking to mock a function in another module, for a multi-module project, it results in an NPE when trying to find the function to be mocked in `MockDesugar` level. 

### Steps to Reproduce

- Checkout the package at https://github.com/Dilhasha/MockIssue
- do `bal build`
- this throws the below NPE

```
[2023-06-16 13:47:29,269] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.getInvokableSymbol(MockDesugar.java:214)
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.getImportFunction(MockDesugar.java:196)
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunction(MockDesugar.java:159)
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunctions(MockDesugar.java:131)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:774)
```

### Affected Version(s)

2201.6.0

### Related area

-> Test Framework

**Comment by Dilhasha** [comment]
Anyway, the recommendation is to use the legacy function mocking implementation only when mocking final clients (https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/#mock-final-clients)

Instead of the following code 

```
@test:Mock {
    moduleName: "app1.dao",
    functionName: "getClient"
}
function getDBMockClient() returns jdbc:Client|error {
    return new ("");
}
```

It can be done using the below.

```
@test:Mock {
    moduleName: "app1.dao",
    functionName: "getClient"
}
test:MockFunction getClientMockFn = new ();

function getDBMockClient() returns jdbc:Client|error {
    return new ("");
}

@test:Config {}
function testFunction() {
    test:when(getClientMockFn).thenReturn(getDBMockClient());
    .....
}
```

**Comment by Dilhasha** [comment]
> Anyway, the recommendation is to use the legacy function mocking implementation only when mocking final clients (https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/#mock-final-clients)
> 
> Instead of the following code
> 
> ```
> @test:Mock {
>     moduleName: "app1.dao",
>     functionName: "getClient"
> }
> function getDBMockClient() returns jdbc:Client|error {
>     return new ("");
> }
> ```
> 
> It can be done using the below.
> 
> ```
> @test:Mock {
>     moduleName: "app1.dao",
>     functionName: "getClient"
> }
> test:MockFunction getClientMockFn = new ();
> 
> function getDBMockClient() returns jdbc:Client|error {
>     return new ("");
> }
> 
> @test:Config {}
> function testFunction() {
>     test:when(getClientMockFn).thenReturn(getDBMockClient());
>     .....
> }
> ```

This does not work as we are trying to mock a global variable in another module.

**Comment by Dilhasha** [comment]
If we add the import `dilhashanazeer/app1.dao` as a null import, the issue gets resolved.
We need to handle the NPE to provide a meaningful error.
