### ISSUE TITLE
[Bug]: Compiler crash found in Collect statement in Query Expressions

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40784]
### Description

Following code 

```
import ballerina/io;

type User record {|
    int id;
    string name;
|};

type Login record {|
    int userId;
    string time;
|};

public function main() {
    User[] users = [
        {id: 1234, name: "Keith"},
        {id: 6789, name: "Anne"}
    ];

    Login[] logins = [
        {userId: 6789, time: "20:10:23"},
        {userId: 1234, time: "10:30:02"},
        {userId: 3987, time: "12:05:00"}
    ];

    // Inner equijoin.
    var joinResult = from var login in logins
                          join var user in users
                          on login.userId equals user.id
                          group by user
                          collect user.name;
    io:println(joinResult);
}
```

gives a compiler crash

```
[2023-06-20 17:11:40,438] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at main.$streamLambda$_4(main.bal:30)
        at main.$streamLambda$_4$lambda4$(main.bal:30)
        at ballerina.lang$0046query.0.$value$_CollectFunction.process(types.bal:744)
        at ballerina.lang$0046query.0.$value$_CollectFunction.call(types.bal)
        at ballerina.lang$0046query.0.types.$gen$$anon$method$delegate$_StreamFunction$0046process$0(types.bal:93)
        at ballerina.lang$0046query.0.$value$_StreamPipeline.$gen$$anon$method$delegate$_StreamFunction$0046process$0$lambda0$(types.bal)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
error: java.lang.NullPointerException
        at main:$streamLambda$_4(main.bal:30)
           ballerina.lang.query.0._CollectFunction:process(types.bal:744)
           ballerina.lang.query.0:$anon$method$delegate$_StreamFunction.process$0(types.bal:93)
```

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
Workaround into use something like this


```
import ballerina/io;

type User record {|
    int id;
    string name;
|};

type Login record {|
    int userId;
    string time;
|};

public function main() {
    User[] users = [
        {id: 1234, name: "Keith"},
        {id: 6789, name: "Anne"}
    ];

    Login[] logins = [
        {userId: 6789, time: "20:10:23"},
        {userId: 1234, time: "10:30:02"},
        {userId: 3987, time: "12:05:00"}
    ];

    // Inner equijoin.
    var joinResult = from var login in logins
                          join var user in users
                          on login.userId equals user.id
                          group by user
                          let var name = user.name
                          collect [name];
    io:println(joinResult);
}

```
