### ISSUE TITLE
[Bug]: Parser goes fail safe for invalid code

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#40839]
### Description

```bal
function foo() {
    a->.post;
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>
<p>

```
Exception in thread "main" java.lang.AssertionError: fail safe reached
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:126)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:111)
	at io.ballerina.compiler.internal.parser.BallerinaParser.recover(BallerinaParser.java:19179)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseSemicolon(BallerinaParser.java:3246)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseActionStatement(BallerinaParser.java:8864)
	at io.ballerina.compiler.internal.parser.BallerinaParser.getExpressionAsStatement(BallerinaParser.java:8772)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpressionStatement(BallerinaParser.java:8680)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4418)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4326)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4288)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseStatement(BallerinaParser.java:4285)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBodyBlock(BallerinaParser.java:2963)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionBody(BallerinaParser.java:2926)
	at io.ballerina.compiler.internal.parser.BallerinaParser.createFunctionDefinition(BallerinaParser.java:1489)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrMethodDeclEnd(BallerinaParser.java:1400)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionDefinition(BallerinaParser.java:1292)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDescRhs(BallerinaParser.java:1318)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFunctionKeywordRhs(BallerinaParser.java:1351)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFuncDefOrFuncTypeDesc(BallerinaParser.java:1282)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:935)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:923)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:566)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:498)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:402)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:101)
	at io.ballerinalang.compiler.parser.test.TestParser.testParser(TestParser.java:46)
	at io.ballerinalang.compiler.parser.test.TestParser.main(TestParser.java:40)
```
</p>
</details> 

This is a blocker for #40381. A test case is failing due to this.

**Comment by lochana-chathura** [comment]
Also, we have the following diff for `client_resource_access_action_source_06.bal`

<img width="1188" alt="Screenshot 2023-06-27 at 11 48 57" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/75a6d92d-5f02-442b-8586-65739eefb256">

**Comment by lochana-chathura** [comment]
> Also, we have the following diff for `client_resource_access_action_source_06.bal`
Reason seem to be error handler sees `(a->function).post(arg1, arg2);` to be a valid grammar while at parser we return after `a->function` as it is an action.
