### ISSUE TITLE
[Bug]: NullPointerException when invoking a service resource with optional parameter containing keyword

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#41057]
### Description

Invoking the following getPackage resource without `limit` results in a null pointer exception. 

```ballerina
import ballerina/http;

listener http:Listener webAPIEP = new (9090);

service / on webAPIEP {

    isolated resource function get packages(int? 'limit = (), string? package = (), boolean? user\-packages = false) returns http:Ok|http:BadRequest|http:InternalServerError|http:Unauthorized {
        return <http:Ok>{
            body: "hello"
        };
    }

}
```

Following curl results in a null pointer.

```
curl http://localhost:9090/packages\?package=jbl
```

```
[2023-07-19 14:55:42,625] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at bctestorg.hellowin.0.creators.$_function_calls.call(Unknown Source)
	at bctestorg.hellowin.0.$_init.call(hellowin)
	at io.ballerina.runtime.internal.scheduling.AsyncUtils.lambda$callDefaultValueFunction$0(AsyncUtils.java:218)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
	at java.base/java.lang.Thread.run(Thread.java:829)

error: java.lang.NullPointerException

```

Invoking with limit parameter works.
```
curl http://localhost:9090/packages\?limit\=1\&package=jbl
hello%
```

### Affected Version(s)

2201.7.0

### Related area

-> Runtime

**Comment by HindujaB** [comment]
The issue happens due to this change
https://github.com/ballerina-platform/ballerina-lang/pull/39779/commits/adb76332c41bf1cb71a17f09ae2b5777ddfee81d
