### ISSUE TITLE
[Bug]: NPE when a variable from a structured binding pattern is used in an anonymous function expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#41236]
### Description

$title.

### Steps to Reproduce

```ballerina
type Doctor record {
    string name;
    string category;    
};

function addDoctor(Doctor doctor, string[] categories) returns error? {
    var {category} = doctor; // also getting an unused variable warning
    if !categories.some(
        existingCategory => existingCategory == category) {
        
    }
}
```

or

```ballerina
type Doctor record {
    string name;
    string category;    
};

function addDoctor(Doctor doctor, string[] categories) returns error? {
    var {category} = doctor; // also getting an unused variable warning
    if !some(categories, existingCategory => existingCategory == category) {
        
    }
}

function some(string[] arr, function (string s) returns boolean func) returns boolean {
    foreach string item in arr {
        if func(item) {
            return true;
        }
    }
    return false;
}
```

```cmd
[2023-08-18 09:22:48,015] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1323)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2141)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1760)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2336)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:591)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:558)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:274)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:175)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:433)
        at java.base/java.util.HashMap.forEach(HashMap.java:1337)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:388)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:800)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:321)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:173)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:142)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:120)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:119)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:56)
```

### Affected Version(s)

2201.7.1

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
```ballerina
type Doctor record {
    string name;
    string category;
};

function addDoctor(Doctor doctor, string[] categories) {
    var {category} = doctor;
    var addCategory = function() {
        _ = category;
    };
}

```
When considering the above example, we desugared it as follows:
```ballerina
type Doctor record {
    string name;
    string category;
};

function addDoctor(Doctor doctor, string[] categories) {
    {
        map<(any|error)> recordVar_1 = <map<(any|error)>> doctor;
        string category = <string> recordVar_1["category"];
    }
    
    var addCategory = function() {
        _ = category;
    };
}
```
Since we added `category` variable to a block scope, we can't access `category` within the function scope. In the above example, after desugaring, we use `category` in the lambda scope, but there is no way to access `category` because it is defined in the block scope. So IMO, we should address this issue in the desugaring phase.

**Comment by chiranSachintha** [comment]
During offline discussion, We decide to replace the block statement with a simple variable definition and a statement expression.

In the given example, the record variable definition(`var {category} = doctor;`) is replaced with:

```
string category = `stmtExpr`
```

Here, `stmtExpr` contains the statement:
```
map<(any|error)> recordVar_1 = <map<(any|error)>> doctor
```
And it returns `recordVar_1["category"]` as an expression.
