### ISSUE TITLE
[Bug]: NPE in SymbolFactory

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#41293]
### Description

$title.

### Steps to Reproduce

```ballerina
import ballerina/http;
import ballerina/log;

type Patient record {|
    string name;
    string dob;
    string ssn;
    string address;
    string phone;
    string email;
|};

type ReservationRequest record {|
    record {|
        *Patient;
        string cardNo;
    |} patient;
    string doctor;
    string hospital_id;
    string hospital;
    string appointment_date;
|};

type Doctor record {|
    string name;
    string hospital;
    string category;
    string availability;
    decimal fee;
|};

type Appointment record {|
    int appointmentNumber;
    Doctor doctor;
    Patient patient;
    decimal fee;
    boolean confirmed;
    string hospital;
    string appointmentDate;
|};

type Fee record {|
    string patientName;
    string doctorName;
    string actualFee;
|};

type ReservationStatus record {|
    int appointmentNo;
    string doctorName;
    string patient;
    int actualFee;
    int discount;
    decimal discounted;
    string paymentID;
    string status;
|};

configurable int port = 8290;
configurable string hospitalServicesBackend = "http://localhost:9090";

final http:Client hospitalServicesEP = check initializeHttpClient();

function initializeHttpClient() returns http:Client|error => new (hospitalServicesBackend);

service /healthcare on new http:Listener(port) {
    resource function post categories/[string category]/reserve(ReservationRequest payload) 
            returns ReservationStatus|http:NotFound|http:InternalServerError {
        log:printInfo("Initiating reservation process", specialization = category);
        
        ReservationRequest {
            patient: {cardNo, ...patient},
            doctor, 
            hospital,
            hospital_id,
            appointment_date
        } = payload;

        Appointment|http:ClientError appointment = 
            hospitalServicesEP->/[hospital_id]/categories/[category]/reserve.post({patient, doctor, hospital, appointment_date});
        if appointment !is Appointment {
            log:printError("Appointment reservation failed", appointment);
            if appointment is http:ClientRequestError {
                return <http:NotFound> {body: string `unknown hospital, doctor, or category`};
            }
            return <http:InternalServerError> {body: appointment.message()};
        }

        Fee|http:ClientError fee = hospitalServicesEP->/[hospital_id]/categories/appointments/[appointment.appointmentNumber]/fee;
        if fee !is Fee {
            log:printError("Retrieving fee failed", fee);
            if fee is http:ClientRequestError {
                return <http:NotFound> {body: string `unknown appointment ID`};
            }
            return <http:InternalServerError> {body: fee.message()};
        }

        decimal|error actualFee = decimal:fromString(fee.actualFee);
        if actualFee is error {
            return <http:InternalServerError> {body: "fee retrieval failed"};
        }

        int appointmentNumber = appointment.appointmentNumber;

        ReservationStatus|http:ClientError status = hospitalServicesEP->/healthcare/payments.post( {
            appointmentNumber,
            doctor: appointment.doctor,
            patient,
            fee: actualFee,
            confirmed: false,
            card_number: cardNo
        });
        if status !is ReservationStatus {
            log:printError("Payment failed", status);
            if status is http:ClientRequestError {
                return <http:NotFound> {body: string `unknown appointment ID`};
            }
            return <http:InternalServerError> {body: status.message()};
        }

        log:printInfo("Appointment reservation successful", 
                      name = patient.name, appointmentNumber = appointmentNumber);
        return status;
    }
}
```

```
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.SymbolFactory.getBField(SymbolFactory.java:767)
	at io.ballerina.compiler.api.impl.SymbolFactory.createRecordFieldSymbol(SymbolFactory.java:391)
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:169)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.lookupSymbol(BallerinaSemanticModel.java:440)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:181)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.processSymbols(SemanticTokensVisitor.java:456)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:191)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.accept(SimpleNameReferenceNode.java:41)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:151)
	at io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode.accept(FieldAccessExpressionNode.java:49)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:421)
	at io.ballerina.compiler.syntax.tree.NamedArgumentNode.accept(NamedArgumentNode.java:49)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:152)
	at io.ballerina.compiler.syntax.tree.FunctionCallExpressionNode.accept(FunctionCallExpressionNode.java:53)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:91)
	at io.ballerina.compiler.syntax.tree.ExpressionStatementNode.accept(ExpressionStatementNode.java:45)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:323)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.accept(FunctionBodyBlockNode.java:58)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:137)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:233)
	at io.ballerina.compiler.syntax.tree.ServiceDeclarationNode.accept(ServiceDeclarationNode.java:82)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:966)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:665)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Affected Version(s)

2201.7.2

### Related area

-> Compilation

**Comment by poorna2152** [comment]
Minimal code to reproduce the error, 
```
import ballerina/log;

type User record {|
    string name;
|};

type Payload record {|
    record {|
        *User;
        string cardNo;
    |} patient;
|};

function foo(Payload payload) {
    Payload {patient: {...patient}} = payload;
    log:printInfo("Appointment reservation successful", name = patient.name);
}

public function main() {
    Payload request = {
        patient: {name: "jack", cardNo: "1"}
    };
    foo(request);
}
```
