### ISSUE TITLE
[Bug]: `ConcurrentModificationException` when multiple users send requests to a simple rest API while profiling it

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#41298]
### Description

$title

### Steps to Reproduce

Profile the service using `bal profile`
```bal
import ballerina/http;

listener http:Listener httpListener = new (8080);

service / on httpListener {
    resource function get greeting() returns string { 
        return "Hello, World!"; 
    }
}
```
Sending multiple requests concurrently gives
```
================================================================================
Ballerina Profiler: Profiling...
================================================================================
Note: This is an experimental feature, which supports only a limited set of functionality.
[1/6] Initializing...
[2/6] Copying executable...
[3/6] Performing analysis...
[4/6] Instrumenting functions...
 ○ Instrumented module count: 44
 ○ Instrumented function count: 2921
[5/6] Running executable...
error: java.util.ConcurrentModificationException
        at ballerina.http.2:externCreateNewResEntity(http_response.bal:548)
           ballerina.http.2.Response:createNewEntity(http_response.bal:54)
           ballerina.http.2.Response:init(http_response.bal:47)
           ballerina.http.2.Caller:returnResponse(http_connection.bal:142)
[2023-08-28 11:59:25,188] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at io.ballerina.runtime.profiler.runtime.ProfileAnalyzer.removeDuplicates(ProfileAnalyzer.java:78)
        at io.ballerina.runtime.profiler.runtime.ProfileAnalyzer.start(ProfileAnalyzer.java:110)
        at ballerina.mime.2.$value$Entity.get(natives.bal)
        at io.ballerina.stdlib.mime.util.MimeUtil.getContentTypeWithParameters(MimeUtil.java:111)
        at io.ballerina.stdlib.http.api.HttpUtil.setEntity(HttpUtil.java:240)
        at io.ballerina.stdlib.http.api.nativeimpl.ExternResponse.setEntityAndUpdateContentTypeHeader(ExternResponse.java:52)
        at ballerina.http.2.http_response.externSetResEntityAndUpdateContentTypeHeader(http_response.bal:556)
        at ballerina.http.2.$value$Response.setEntityAndUpdateContentTypeHeader(http_response.bal:87)
        at ballerina.http.2.$value$Response.call(http_response.bal)
        at ballerina.http.2.$value$Response.setTextPayload(http_response.bal:404)
        at ballerina.http.2.$value$Response.call(http_response.bal)
        at ballerina.http.2.http_connection.setPayload(http_connection.bal:332)
        at ballerina.http.2.$value$Caller.returnResponse(http_connection.bal:172)
        at ballerina.http.2.$value$Caller.call(http_connection.bal)
        at io.ballerina.runtime.internal.BalRuntime.lambda$getFunction$1(BalRuntime.java:260)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
error: java.util.ConcurrentModificationException
        at ballerina.http.2:externSetResEntityAndUpdateContentTypeHeader(http_response.bal:556)
           ballerina.http.2.Response:setEntityAndUpdateContentTypeHeader(http_response.bal:87)
           ballerina.http.2.Response:setTextPayload(http_response.bal:404)
           ballerina.http.2:setPayload(http_connection.bal:332)
           ballerina.http.2.Caller:returnResponse(http_connection.bal:172)
[2023-08-28 11:59:25,454] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at io.ballerina.runtime.profiler.runtime.ProfileAnalyzer.removeDuplicates(ProfileAnalyzer.java:78)
        at io.ballerina.runtime.profiler.runtime.ProfileAnalyzer.start(ProfileAnalyzer.java:96)
        at ballerina.lang$0046array.0.$value$ArrayIterator.$init$(internal.bal)
        at ballerina.lang$0046array.0.$value$ArrayIterator.call(internal.bal)
        at ballerina.lang$0046array.0.array.iterator(array.bal:67)
        at ballerina.http.2.auth_desugar.getResourceAuthConfig(auth_desugar.bal:218)
        at ballerina.http.2.auth_desugar.getListenerAuthConfig(auth_desugar.bal:183)
        at ballerina.http.2.auth_desugar.authenticateResource(auth_desugar.bal:37)
        at nadeeshand.restfulapi.0.$value$$anonType$_0.$get$greeting(main.bal:72)
        at nadeeshand.restfulapi.0.$value$$anonType$_0.call(main.bal)
        at io.ballerina.runtime.internal.BalRuntime.lambda$getFunction$1(BalRuntime.java:260)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
error: java.util.ConcurrentModificationException
        at ballerina.lang.array.0:iterator(array.bal:67)
           ballerina.http.2:getResourceAuthConfig(auth_desugar.bal:218)
           ballerina.http.2:getListenerAuthConfig(auth_desugar.bal:183)
           ballerina.http.2:authenticateResource(auth_desugar.bal:37)
           nadeeshand.restfulapi.0.$anonType$_0:$get$greeting(main.bal:72)
error: Connection between remote client and host is closed
error: Connection between remote client and host is closed
[6/6] Generating output...
 ○ Execution time: 22 seconds 
 ○ Output: target/bin/ProfilerOutput.html
```

You can use the following `jmx` with with `jmeter` to send requests.
[http-get-request-simple.jmx.zip](https://github.com/ballerina-platform/ballerina-lang/files/12451016/http-get-request-simple.jmx.zip)

### Affected Version(s)

2201.8.0-snapshot

### Related area

-> Other Area

**Comment by HindujaB** [comment]
Need to address these comments in the PR
- https://github.com/ballerina-platform/ballerina-lang/pull/41322#discussion_r1319422329
- https://github.com/ballerina-platform/ballerina-lang/pull/41322#discussion_r1319428912

**Comment by HindujaB** [comment]
The stack trace after the improvements in the profiler. 
```
[2023-09-12 10:42:43,381] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
        at io.ballerina.runtime.profiler.runtime.ProfileAnalyzer.start(ProfileAnalyzer.java:92)
        at ballerina.http.2.auth_desugar.getResourceAuthConfig(auth_desugar.bal)
        at ballerina.http.2.auth_desugar.getListenerAuthConfig(auth_desugar.bal:183)
        at ballerina.http.2.auth_desugar.authenticateResource(auth_desugar.bal:37)
        at hinduja.profiler_concurrent.0.$value$$anonType$_0.$get$greeting(main.bal:6)
        at hinduja.profiler_concurrent.0.$value$$anonType$_0.call(main.bal)
        at io.ballerina.runtime.internal.BalRuntime.lambda$getFunction$1(BalRuntime.java:260)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
error: java.util.ConcurrentModificationException
        at ballerina.http.2:getListenerAuthConfig(auth_desugar.bal:183)
           ballerina.http.2:authenticateResource(auth_desugar.bal:37)
           hinduja.profiler_concurrent.0.$anonType$_0:$get$greeting(main.bal:6)
```
