### ISSUE TITLE
[Bug]: Crashing while loading Configstoml

### ISSUE THREAD

**Issue by nadheesh** [ballerina-platform/ballerina-lang#41368]
### Description

App crashes when loading the `Config.toml`. Seems some configs values are without quotes and it causes the Ballerina app to crash giving a Java error. 

I got this error 

```
[2023-09-11 03:30:35,996] SEVERE {b7a.log.crash} - Index: '555', Size: '554' 
java.lang.IndexOutOfBoundsException: Index: '555', Size: '554'
    at io.ballerina.tools.text.LineMap.positionRangeCheck(LineMap.java:72)
    at io.ballerina.tools.text.LineMap.linePositionFrom(LineMap.java:44)
    at io.ballerina.tools.text.TextDocument.linePositionFrom(TextDocument.java:48)
    at io.ballerina.toml.syntax.tree.Node.lineRange(Node.java:142)
    at io.ballerina.toml.syntax.tree.NodeLocation.lineRange(NodeLocation.java:39)
    at io.ballerina.toml.semantic.ast.TomlNode.reportSyntaxDiagnostics(TomlNode.java:89)
    at io.ballerina.toml.semantic.ast.TomlNode.<init>(TomlNode.java:48)
    at io.ballerina.toml.semantic.ast.TopLevelNode.<init>(TopLevelNode.java:35)
    at io.ballerina.toml.semantic.ast.TomlTableNode.<init>(TomlTableNode.java:49)
    at io.ballerina.toml.semantic.ast.TomlTransformer.createRootTable(TomlTransformer.java:124)
    at io.ballerina.toml.semantic.ast.TomlTransformer.transform(TomlTransformer.java:78)
    at io.ballerina.toml.api.Toml.read(Toml.java:135)
    at io.ballerina.toml.api.Toml.read(Toml.java:80)
    at io.ballerina.runtime.internal.configurable.providers.toml.ConfigToml.getTomlRootFromFile(ConfigToml.java:74)
    at io.ballerina.runtime.internal.configurable.providers.toml.ConfigToml.tomlAstNode(ConfigToml.java:62)
    at io.ballerina.runtime.internal.configurable.providers.toml.TomlFileProvider.getConfigTomlData(TomlFileProvider.java:55)
    at io.ballerina.runtime.internal.configurable.providers.toml.TomlFileProvider.initialize(TomlFileProvider.java:47)
    at io.ballerina.runtime.internal.configurable.ConfigResolver.resolveConfigs(ConfigResolver.java:71)
    at io.ballerina.runtime.internal.launch.LaunchUtils.initConfigurableVariables(LaunchUtils.java:121)
    at choreo.testgpt.1.$configurationMapper.$configureInit(Unknown Source)
    at choreo.testgpt.1.$_init.main(testgpt)
 
cat: can't open 'ballerina-internal.log': No such file or directory
```

### Affected Version(s)

2201.7.2

### Related area

-> Compilation

**Comment by HindujaB** [comment]
Reproducible with the following code.
```ballerina
configurable string dottedValue = ?;
configurable string stringValue = ?;
```

In `Config.toml`
```toml
dottedValue = test.net
stringValue = "string value"
```

Happening due to a bug in the native TOML parser. It should throw the correct error instead of crashing.
@xlight05 Please note
