### ISSUE TITLE
[Bug]: Build crashes at desugar when downgrading Ballerina version and building with the `sticky` option

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#41365]
### Description

$title.

Fails gracefully when `sticky` is not used.

### Steps to Reproduce

```ballerina
import ballerinax/salesforce;

configurable salesforce:ConnectionConfig config = ?;

public function main() returns error? {
    salesforce:Client _ = check new (config);
}
```

1. Add the above snippet in a package and build using `2201.7.2`
2. Then switch to `2201.6.1` and build with the `sticky` option

Fails with

```
[2023-09-08 14:48:22,394] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:6902)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6878)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1608)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8494)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:8426)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8354)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1380)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1426)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:830)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:282)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:57)
```

But, when `sticky` is not used, fails with

```
ERROR [main.bal:(1:1,1:30)] cannot resolve module 'ballerinax/salesforce'
ERROR [main.bal:(3:14,3:41)] invalid type for configurable variable: expected a subtype of 'anydata'
ERROR [main.bal:(3:14,3:41)] undefined module 'salesforce'
ERROR [main.bal:(3:14,3:41)] unknown type 'ConnectionConfig'
ERROR [main.bal:(6:5,6:22)] undefined module 'salesforce'
ERROR [main.bal:(6:5,6:22)] unknown type 'Client'
ERROR [main.bal:(6:33,6:45)] cannot infer type of the object from '(other|error)'
```

### Related area

-> Compilation

**Comment by gabilang** [comment]
Observed the following when created a project with `2201.6.0`, then built it with `2201.7.0` (using `bal build`) and then build again with `--sticky` option in `2201.6.0`. 
Ballerina code - simple hello-world program
```ballerina
import ballerina/io;

public function main() returns error? {
    io:println("Hello, World!");
}
```
Observed stacktrace:
```
[2023-09-13 15:52:38,556] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:829)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:786)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:769)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:498)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:358)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:570)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:274)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:175)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:433)
        at java.base/java.util.HashMap.forEach(HashMap.java:1337)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:388)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:800)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:318)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:478)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:278)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

**Comment by Thevakumar-Luheerathan** [comment]
> ### Description
> $title.
> 
> Fails gracefully when `sticky` is not used.
> 
> ### Steps to Reproduce
> ```ballerina
> import ballerinax/salesforce;
> 
> configurable salesforce:ConnectionConfig config = ?;
> 
> public function main() returns error? {
>     salesforce:Client _ = check new (config);
> }
> ```
> 
> 1. Add the above snippet in a package and build using `2201.7.2`
> 2. Then switch to `2201.6.1` and build with the `sticky` option
> 
> Fails with
> 
> ```
> [2023-09-08 14:48:22,394] SEVERE {b7a.log.crash} - null 
> java.lang.NullPointerException
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:6902)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6878)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:65)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
>         at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
>         at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1608)
>         at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8494)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:8426)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8354)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:65)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
>         at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
>         at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1380)
>         at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1426)
>         at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:830)
>         at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
>         at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
>         at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
>         at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
>         at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
>         at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
>         at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
>         at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
>         at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
>         at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
>         at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
>         at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
>         at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
>         at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:282)
>         at java.base/java.util.Optional.ifPresent(Optional.java:183)
>         at io.ballerina.cli.launcher.Main.main(Main.java:57)
> ```
> 
> But, when `sticky` is not used, fails with
> 
> ```
> ERROR [main.bal:(1:1,1:30)] cannot resolve module 'ballerinax/salesforce'
> ERROR [main.bal:(3:14,3:41)] invalid type for configurable variable: expected a subtype of 'anydata'
> ERROR [main.bal:(3:14,3:41)] undefined module 'salesforce'
> ERROR [main.bal:(3:14,3:41)] unknown type 'ConnectionConfig'
> ERROR [main.bal:(6:5,6:22)] undefined module 'salesforce'
> ERROR [main.bal:(6:5,6:22)] unknown type 'Client'
> ERROR [main.bal:(6:33,6:45)] cannot infer type of the object from '(other|error)'
> ```
> 
> ### Affected Version(s)
> _No response_
> 
> ### OS, DB, other environment details and versions
> _No response_
> 
> ### Related area
> -> Compilation
> 
> ### Related issue(s) (optional)
> _No response_
> 
> ### Suggested label(s) (optional)
> _No response_
> 
> ### Suggested assignee(s) (optional)
> _No response_


I obtained  following output when I built the above code with ballerina-lang 2201.6.1-stage branch. Instead of null, I got some error message.(I am not sure why the error message is showing as null for the actual distribution while a complete error message is obtained with ballerina-lang branch.)
```
Compiling source
        luheerathan/test1:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-11-09 11:39:48,560] SEVERE {b7a.log.crash} - Cannot read field "symbol" because "org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(org.wso2.ballerinalang.compiler.semantics.model.types.BType).tsymbol.generatedInitializerFunc" is null 
java.lang.NullPointerException: Cannot read field "symbol" because "org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(org.wso2.ballerinalang.compiler.semantics.model.types.BType).tsymbol.generatedInitializerFunc" is null
        at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:6902)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6878)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1608)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8494)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:8426)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8354)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8942)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1477)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1614)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8955)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8961)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1380)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1426)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:830)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8917)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:282)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:57)
 
ERROR [test1:(1:1,1:1)] Compilation failed due to: Cannot read field "symbol" because "org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(org.wso2.ballerinalang.compiler.semantics.model.types.BType).tsymbol.generatedInitializerFunc" is null
error: compilation contains errors
```

**Comment by Thevakumar-Luheerathan** [comment]
> Observed the following when created a project with `2201.6.0`, then built it with `2201.7.0` (using `bal build`) and then build again with `--sticky` option in `2201.6.0`. Ballerina code - simple hello-world program
> 
> ```ballerina
> import ballerina/io;
> 
> public function main() returns error? {
>     io:println("Hello, World!");
> }
> ```
> 
> Observed stacktrace:
> 
> ```
> [2023-09-13 15:52:38,556] SEVERE {b7a.log.crash} - null 
> java.lang.NullPointerException
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:829)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:786)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:769)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:498)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:358)
>         at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:570)
>         at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:274)
>         at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:175)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:433)
>         at java.base/java.util.HashMap.forEach(HashMap.java:1337)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:388)
>         at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:800)
>         at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
>         at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
>         at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:318)
>         at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:478)
>         at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
>         at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
>         at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
>         at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
>         at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
>         at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
>         at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
>         at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
>         at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
>         at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
>         at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:278)
>         at java.base/java.util.Optional.ifPresent(Optional.java:183)
>         at io.ballerina.cli.launcher.Main.main(Main.java:53)
> ```

Here is the output obtained with ballerina-lang 2201.6.0-stage branch.
```
Compiling source
        luheerathan/test1:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-11-09 13:09:46,092] SEVERE {b7a.log.crash} - Cannot read field "type" because "funcSymbol" is null 
java.lang.NullPointerException: Cannot read field "type" because "funcSymbol" is null
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:829)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:786)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:769)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:498)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:358)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:570)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:274)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:175)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:433)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:388)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:800)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:318)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:478)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:278)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
 
```

**Comment by tharindu-nw** [comment]
Added [this change](https://github.com/wso2-enterprise/ballerina-registry/pull/2305) to filter incompatible packages when resolving in the hard locking mode

**Comment by Thevakumar-Luheerathan** [comment]
Closing this issue as this is working with dev central as expected.
