### ISSUE TITLE
[Bug]: NPE when the function is being mocked is directly assigned to a module level variable 

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#41376]
### Description

$title

### Steps to Reproduce

in main.bal
```ballerina
public function foo() returns int|error { 
    return 1;
}

int intVal = check foo();
```

in test file
```ballerina
@test:Mock {
    functionName: "foo"
}
test:MockFunction mock_foo = new();
```

error log:
```
[2023-09-12 13:22:18,602] SEVERE {b7a.log.crash} - Cannot invoke "io.ballerina.runtime.api.values.BObject.set(io.ballerina.runtime.api.values.BString, Object)" because "gabilan.support_checks$test.0.$_init.mock_foo" is null 
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.api.values.BObject.set(io.ballerina.runtime.api.values.BString, Object)" because "gabilan.support_checks$test.0.$_init.mock_foo" is null
        at gabilan.support_checks$test.0.support_checks.$MOCK_foo(support_checks:1)
        at gabilan.support_checks.0.main.foo(main.bal)
        at gabilan.support_checks.0.$_init.$gen$$0046$0060init$0062(support_checks:40)
        at gabilan.support_checks$test.0.$_init.$moduleInit(support_checks)
        at gabilan.support_checks$test.0.$_init.$moduleExecute(support_checks)
        at gabilan.support_checks$test.0.$_init.$lambda$$moduleExecute$(support_checks)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Related area

-> Runtime

**Comment by HindujaB** [comment]
Could be related to https://github.com/ballerina-platform/ballerina-lang/issues/41330

**Comment by HindujaB** [comment]
As per the offline discussion, the proper usage of Mock function is recommended here. 
https://ballerina.io/learn/test-ballerina-code/mocking/#mock-functions

Therefore, closing the issue and keeping the original to track the improvements.
