### ISSUE TITLE
[Bug]: `bal pack` crashes when `[[dependency]]` section is missing in the CompilerPlugin.toml file

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#41418]
### Description

$Subject
When a Ballerina project has `CompilerPlugin.toml` file with no `[[dependency]]` sections specified, executing `bal pack` gives the following crash log:

```
[2023-09-20 15:19:48,152] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at io.ballerina.projects.JBallerinaBalaWriter.addCompilerPlugin(JBallerinaBalaWriter.java:121)
        at io.ballerina.projects.BalaWriter.populateBalaArchive(BalaWriter.java:135)
        at io.ballerina.projects.BalaWriter.write(BalaWriter.java:108)
        at io.ballerina.projects.JBallerinaBackend.emitBala(JBallerinaBackend.java:241)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:218)
        at io.ballerina.cli.task.CreateBalaTask.execute(CreateBalaTask.java:79)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:256)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

Add an empty `CompilerPlugin.toml` file or with only `[plugin]` section to a Ballerina project. 

`CompilerPlugin.toml`
```toml
[plugin]
id = "id"
class = "path.to.class"
```

### Affected Version(s)

ballerina-lang master, update-8 RC1
NPE observed with earlier versions when an empty `CompilerPlugin.toml` file added. 

### Related area

-> Compilation

**Comment by azinneera** [comment]
@Shadow-Devil Assigning you to this as requested in the issue #42120

**Comment by azinneera** [comment]
@Shadow-Devil can you comment on this issue so that I can assign you?

**Comment by Shadow-Devil** [comment]
Sure, please assign me :)
