### ISSUE TITLE
[Bug]: Error message in bal pack when the token is invalid

### ISSUE THREAD

**Issue by NirashaSewwandi** [ballerina-platform/ballerina-lang#41785]
### Description

I used `bal new --template lib hello` to make a library and try to do `bal pack`. I had a invalid token in the Settings.toml
Got this error
[2023-11-29 09:40:50,990] SEVERE {b7a.log.crash} - closed 
java.lang.IllegalStateException: closed
        at okio.RealBufferedSource.select(RealBufferedSource.kt:221)
        at okhttp3.internal.Util.bomAwareCharset(Util.java:467)
        at okhttp3.ResponseBody.string(ResponseBody.java:181)
        at org.ballerinalang.central.client.CentralAPIClient.handleUnauthorizedResponse(CentralAPIClient.java:1707)
        at org.ballerinalang.central.client.CentralAPIClient.resolveDependencies(CentralAPIClient.java:895)
        at io.ballerina.projects.internal.repositories.RemotePackageRepository.fromPackageResolutionResponse(RemotePackageRepository.java:364)
        at io.ballerina.projects.internal.repositories.RemotePackageRepository.getPackageMetadata(RemotePackageRepository.java:294)
        at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackageMetadata(DefaultPackageResolver.java:170)
        at io.ballerina.projects.internal.ResolutionEngine.resolveDirectDependencies(ResolutionEngine.java:248)
        at io.ballerina.projects.internal.ResolutionEngine.populateStaticDependencyGraph(ResolutionEngine.java:173)
        at io.ballerina.projects.internal.ResolutionEngine.resolveDependencies(ResolutionEngine.java:97)
        at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:290)
        at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:232)
        at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:103)
        at io.ballerina.projects.PackageResolution.from(PackageResolution.java:110)
        at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:251)
        at io.ballerina.projects.Package.getResolution(Package.java:154)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:112)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:256)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)

### Steps to Reproduce

`bal new --template lib hello`
Use a invalid token in Settings.toml
`bal pack`

### Related area

-> Compilation

**Comment by Thevakumar-Luheerathan** [comment]
This issue occurs when we try to consume the body from already closed response. Consuming body again and again from a Response is not possible.
