### ISSUE TITLE
[Bug]: Compiler crash when passing arguments where an empty list constrcutor

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#41818]
### Description

$subject

Compiling the below code will give a compiler crash.

```

[2023-12-04 11:14:01,690] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeArgIsolatedness(IsolationAnalyzer.java:2331)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeInvocation(IsolationAnalyzer.java:2082)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:1422)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:128)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:322)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:580)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:322)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:449)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:322)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:431)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyzeNode(IsolationAnalyzer.java:322)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.visit(IsolationAnalyzer.java:368)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.IsolationAnalyzer.analyze(IsolationAnalyzer.java:331)
        at io.ballerina.projects.internal.CompilerPhaseRunner.isolationAnalyze(CompilerPhaseRunner.java:204)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:129)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:435)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:208)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:192)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:242)
        at io.ballerina.projects.Package.getCompilation(Package.java:150)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:319)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:142)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
ERROR [issues:(1:1,1:1)] Compilation failed due to: Index 0 out of bounds for length 0
error: compilation contains errors
```

### Steps to Reproduce

```ballerina
public isolated function last(any v, any... vs) {
}

public function main() {
     _ = last(...[]);
}
```

### Affected Version(s)

2201.8.3

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
```ballerina
public function last(any v, any... vs) {
}

public function main() {
     _ = last(...[]);
}
```
If the function is not isolated, then this is working fine.


Here, we correctly define the type of the list constructor expression as `[any, any...]` tuple type. However, in the isolation phase, we analyze the first argument of the function call to determine if it is isolated, based on whether we provide a value for it.
