### ISSUE TITLE
[Bug]: Compilation Error about query expressions, tuple arrays and spread operator

### ISSUE THREAD

**Issue by Shadow-Devil** [ballerina-platform/ballerina-lang#41832]
### Description

While doing day 3 of the advent of code in Ballerina I got a compile error:
```
Compiling source
        fschn/aoc2023:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-12-05 19:45:08,526] SEVERE {b7a.log.crash} - Cannot read field "name" because "varDcl" is null 
java.lang.NullPointerException: Cannot read field "name" because "varDcl" is null
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1369)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2184)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1803)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2385)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:596)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:623)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:341)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:182)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:425)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:384)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:793)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:325)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:174)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:143)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:121)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:120)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

```ballerina
import ballerina/regex;

public function main() {
    [int, int][] points = [];
    foreach [int, string] [y,line] in ["abc", "def"].enumerate() {
        [int, int][] tmp = from [int, string] [x, char] in regex:split(line, "").enumerate() select [x, y];
        points.push(...tmp);
    }
}
```

### Affected Version(s)

Swan Lake Update 7 and Swan Lake Update 8.4

### OS, DB, other environment details and versions

Docker image "ballerina/ballerina-devcontainer:2201.7.0" on Windows

### Related area

-> Compilation

**Comment by Shadow-Devil** [comment]
This equivalent code works:
```ballerina
import ballerina/regex;

public function main() returns error? {
    [int, int][] points = [];
    foreach [int, string] [y,line] in ["abc", "def"].enumerate() {
        foreach [int, string] [x, char] in regex:split(line, "").enumerate() {
            points.push([x, y]);
        }
    }
}
```

**Comment by Shadow-Devil** [comment]
This again doesn't work, so it's probably not an issue with the query expression:
```ballerina
import ballerina/regex;

public function main() {
        foreach [int, string] [y, line] in ["abc", "def"].enumerate() {
            foreach [int, string] [x, c] in regex:split(line, "").enumerate() {
                if [""].every(other => other != c) {
                    points.push([x, y]);
                }
            }
        }
}
```

**Comment by MaryamZi** [comment]
May be related to https://github.com/ballerina-platform/ballerina-lang/issues/41236.
