### ISSUE TITLE
[Bug]: Language Server shuts down when using a Ballerina project with large files

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-lang#41862]
### Description

When working with a Ballerina project that includes large files, particularly generated from an OpenAPI specification, the Ballerina Language Server unexpectedly shuts down, resulting in a "Stopping server timed out" error. This issue appears to be triggered when attempting to work with the generated Ballerina files.

**Output log:**
```bash
[Error - 16:53:27] Stopping server failed
Error: Stopping the server timed out
    at /Users/nuvindu/.vscode/extensions/wso2.ballerina-4.5.6/dist/extension.js:2:997853
```

### Steps to Reproduce

1. Download the OpenAPI spec from [here](https://drive.google.com/file/d/1Fh56QnWt21jbcFpwuUnr7xajk2th4pB5/view?usp=sharing).
2. Create a new Ballerina project.
3. Run the `bal openapi -i esignature.rest.swagger-v2.1.json --mode client --client-methods resource` command to generate client.bal, types.bal, and utils.bal files.
4. Use the generated Ballerina project in the VS Code environment.

**Comment by nipunayf** [comment]
The error is due to an out-of-memory issue occurring during the project build. The following error message is generated when we execute the `bal build` command.

```
[2023-12-13 13:22:19,567] SEVERE {b7a.log.crash} - Java heap space 
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:241)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:685)
        at java.base/java.lang.StringBuffer.append(StringBuffer.java:393)
        at java.base/java.io.StringWriter.write(StringWriter.java:122)
        at com.google.gson.stream.JsonWriter.string(JsonWriter.java:642)
        at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
        at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:832)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:725)
        at com.google.gson.internal.Streams.write(Streams.java:73)
        at com.google.gson.JsonElement.toString(JsonElement.java:323)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.generateSyntaxTreeJsonString(DefaultObservabilitySymbolCollector.java:208)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:92)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:140)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:121)
        at io.ballerina.projects.JBallerinaBackend$$Lambda$523/0x0000000301363148.apply(Unknown Source)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
```

**Comment by NipunaMadhushan** [comment]
This is related to issue https://github.com/ballerina-platform/ballerina-lang/issues/41725. This has been fixed with `2201.8.3` version along with PR https://github.com/ballerina-platform/ballerina-lang/pull/41569

**Comment by nipunayf** [comment]
I am using `2201.8.4`, and still, the issue exists. We can build the project by disabling `observabilityIncluded` in the `Ballerina.toml`.

**Comment by KavinduZoysa** [comment]
The issue happens at this point.

https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/observability-symbol-collector/src/main/java/org/ballerinalang/observability/anaylze/DefaultObservabilitySymbolCollector.java#L208

According to this example, at this point, the syntax tree JSON element of `types.bal` is converted to a string using `toString()`. `types.bal` file containing `37403` lines.

**Comment by NipunaMadhushan** [comment]
Seems like the above fix (https://github.com/ballerina-platform/ballerina-lang/pull/41569) I mentioned, is still not enough for this use case.

**Comment by KavinduZoysa** [comment]
One thing we can do here is to split large files into separate files. In this case, we have to do that from the open API side. 

Another one is,
Here we use StringBuilder to get the JSON format of the syntax tree to write to a file. We can keep the JsonElement as it is and write element by element into the file(We may need a separate method for that). Still, there is a possibility for OOM because JsonElement is exponentially large.

@NipunaMadhushan, @lnash94, @Nuvindu

**Comment by Nuvindu** [comment]
@KavinduZoysa I have manually split the `types.bal` file into separate files. It fixes the lang server shutting down issue but still the same out of memory issue will occur when building the ballerina project.

**Comment by KavinduZoysa** [comment]
> @KavinduZoysa I have manually split the `types.bal` file into separate files. It fixes the lang server shutting down issue but still the same out of memory issue will occur when building the ballerina project.

Can you please attach your project?

**Comment by Nuvindu** [comment]
@KavinduZoysa You can download the project from [here](https://drive.google.com/file/d/1MNjby1TxN5Zlmo_QkWayAY2Pxmf_XLLn/view?usp=sharing)

**Comment by NipunaMadhushan** [comment]
There is an issue created to fix this https://github.com/ballerina-platform/ballerina-lang/issues/42001.

This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/42002.
