### ISSUE TITLE
[Bug]: Ballerina get crashed for nested query expressions

### ISSUE THREAD

**Issue by shayanmalinda** [ballerina-platform/ballerina-lang#42073]
### Description

When I was trying to run 02 nested query expressions, Ballerina crashed at compilation time.
This was working fine, when I remove the nested query expression.

### Steps to Reproduce

Below get failed

```
    return from types:GitHubRelease gitHubRelease in gitHubReleases
        where gitHubRelease.prerelease == isPreRelease || isPreRelease is ()
        select {
            id: gitHubRelease.id,
            name: gitHubRelease.name,
            tagName: gitHubRelease.tag_name,
            body: gitHubRelease.body,
            url: gitHubRelease.html_url,
            preRelease: gitHubRelease.prerelease,
            assets: from types:GitHubReleaseAsset gitHubReleaseAsset in gitHubRelease.assets
                select {
                    id: gitHubReleaseAsset.id,
                    name: gitHubReleaseAsset.name,
                    createdAt: gitHubReleaseAsset.created_at,
                    updatedAt: gitHubReleaseAsset.updated_at,
                    downloadUrl: gitHubReleaseAsset.browser_download_url
                }
        };
```

Below works fine
```
    return from types:GitHubRelease gitHubRelease in gitHubReleases
        where gitHubRelease.prerelease == isPreRelease || isPreRelease is ()
        select {
            id: gitHubRelease.id,
            name: gitHubRelease.name,
            tagName: gitHubRelease.tag_name,
            body: gitHubRelease.body,
            url: gitHubRelease.html_url,
            preRelease: gitHubRelease.prerelease,
            assets: []
        };
```

### Affected Version(s)

2201.8.2

### Related area

-> Compilation

**Comment by shayanmalinda** [comment]
Please find the relevant log output

```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-01-31 10:06:44,073] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:620)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:71)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.generateMappingConstructorEntries(BIRGen.java:2994)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1561)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral$BLangMapLiteral.accept(BLangRecordLiteral.java:336)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1573)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1092)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:739)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:699)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:348)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:348)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:288)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:173)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:142)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:120)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:119)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:223)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
ERROR [modules/github/engineering_entity.github:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

**Comment by shayanmalinda** [comment]
Provided [suggestion](https://github.com/wso2-enterprise/internal-support-ballerina/issues/572#issuecomment-1918401420) works as expected. Thanks @LakshanWeerasinghe .

**Comment by LakshanWeerasinghe** [comment]
The reason for the issue is type binding is not type checked correctly in the nested query level. The type of the `asserts` filed is `GitHubAsset` and the user given type is `GitHubReleaseAsset`.

**Comment by LakshanWeerasinghe** [comment]
Below is the minimal reproducible example.
```ballerina
type T1 record {|
    int p1;
    T2[] t2s;
|};

type T2 record {|
    int p3;
|};

function getResult() {
    T1[] t1s = [];
    _ = from T1 t1 in t1s
        select {
            a1: t1.p1,
            a2s: from T3 t3 in t1.t2s
                select {
                    id: t3.id
                }
        };
};
```

**Comment by LakshanWeerasinghe** [comment]
Below is another valid sample code which gives different error at compile time.

Error message : `error: jVM generation is not supported for type other`

```ballerina
public type T1 record {|
    int p1;
    T2[] t2s;
|};

public type T2 record {|
    int p3;
|};

function getResult() {
    T1[] t1s = [];
    _ = from T1 t1 in t1s
        select {
            a1: t1.p1,
            a2s: from T3 t3 in t1.t2s
                select t3
        };
};
```
