### ISSUE TITLE
[Bug]: Building a project with a corrupted Dependencies.toml causes a bad sad error for some cases

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-lang#42106]
### Description

When there's corrupted Dependencies.toml file in a Ballerina package(this could be a missing field or an invalid value in a field), and the project is built, the build will fail with the following bad sad error.
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-02-02 14:49:07,734] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: module_sample 
java.lang.IllegalStateException: Cannot find the generated jar library for module: module_sample
        at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$5(JBallerinaBackend.java:531)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:530)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:298)
        at io.ballerina.projects.JBallerinaBackend.createManifest(JBallerinaBackend.java:429)
        at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:536)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:219)
        at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:114)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

At the end, the Dependencies.toml is generated again correcting the fields that were missing/invalid.

### Related area

-> Other Area

**Comment by Thevakumar-Luheerathan** [comment]
Can you share the project directory? I tried a few examples(changed some unavailable versions, and removed a few dependencies etc), but I couldn't reproduce it.

**Comment by Thevakumar-Luheerathan** [comment]
This bad sad error occurs when we don't generate the thin jar for the package inside `./target/cache/<org>/<packagename>/<version>/<platform>` directory because of corrupted `Dependencies.toml`. To resolve this issue, we decided to eliminate the corrupted `Dependencies.toml` and continue the build without `Dependencies.toml`.
