### ISSUE TITLE
[Bug]: java.lang.NoClassDefFoundError when running tests with lang master build

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#42122]
### Description

When tests are run with a build of the lang master, there is a bad sad error.

However, I noticed that this is not reproduciable in `2201.8.x` that suggests that the bug was introduced after that.

### Steps to Reproduce

1. Create a simple ballerina project with, `bal new sample_project`.
2. Add a simple test under tests/test.
3. Run `bal test`.

The following error will be received. 

```
bal test
Compiling source
        gayaldassanayake/testddt:0.1.0

Running Tests

        testddt
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-02-06 18:38:47,587] SEVERE {b7a.log.crash} - ballerina/lang$0046array/0/constants/$_typeref_type_constants 
java.lang.NoClassDefFoundError: ballerina/lang$0046array/0/constants/$_typeref_type_constants
        at ballerina.io.1.constants.$_array_type_constants.$populate$arrayType7(Unknown Source)
        at ballerina.io.1.constants.$_array_type_constants.$populate_array_types(Unknown Source)
        at ballerina.io.1.types.$_types.$createTypeConstants(Unknown Source)
        at ballerina.io.1.types.$_types.$createTypes(Unknown Source)
        at ballerina.io.1.$_init.$currentModuleInit(io)
        at ballerina.io.1.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at gayaldassanayake.testddt$test.0.$configurationMapper.$configureInit(Unknown Source)
        at gayaldassanayake.testddt$test.0.$_init.main(testddt)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.runTestModuleMain(TesterinaUtils.java:141)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.startSuite(TesterinaUtils.java:130)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.execute(TesterinaUtils.java:124)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:93)
        at org.ballerinalang.test.runtime.BTestMain.startTestSuit(BTestMain.java:151)
        at org.ballerinalang.test.runtime.BTestMain.main(BTestMain.java:133)
Caused by: java.lang.ClassNotFoundException: ballerina.lang$0046array.0.constants.$_typeref_type_constants
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 18 more
 
error: there are test failures
```

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
This seems to be occuring due to the dependencies of U9 not being published yet. Everything works fine when the distribution is built and used. Hence closing the issue.
