### ISSUE TITLE
[Bug]: Bad sad error occurs when I try to pull a non-existing tool from local repository

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-lang#42235]
### Description

`bal tool pull gaals:1.2.0 --repository=local` with this command below error occurs.(Here, `gaals` tool doesn't exist in local repository)

```
[2024-02-28 09:28:23,939] SEVERE {b7a.log.crash} - Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null 
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at io.ballerina.cli.cmd.ToolCommand.isToolAvailableInLocalRepo(ToolCommand.java:498)
	at io.ballerina.cli.cmd.ToolCommand.pullToolAndUpdateBalToolsToml(ToolCommand.java:462)
	at io.ballerina.cli.cmd.ToolCommand.handlePullCommand(ToolCommand.java:253)
	at io.ballerina.cli.cmd.ToolCommand.execute(ToolCommand.java:174)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Affected Version(s)

2201.8.5 and master

### Related area

-> Other Area

**Comment by Thevakumar-Luheerathan** [comment]
Related release issue : https://github.com/ballerina-platform/ballerina-release/issues/2629

**Comment by Dilhasha** [comment]
I faced a similar issue when trying to push a tool to local repository as well.

[2024-03-06 22:04:05,458] SEVERE {b7a.log.crash} - Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at io.ballerina.cli.cmd.PushCommand.createLocalToolsJsonIfLocalTool(PushCommand.java:433)
	at io.ballerina.cli.cmd.PushCommand.pushBalaToCustomRepo(PushCommand.java:402)
	at io.ballerina.cli.cmd.PushCommand.pushPackage(PushCommand.java:282)
	at io.ballerina.cli.cmd.PushCommand.execute(PushCommand.java:186)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)

**Comment by Thevakumar-Luheerathan** [comment]
> I faced a similar issue when trying to push a tool to local repository as well.
> 
> [2024-03-06 22:04:05,458] SEVERE {b7a.log.crash} - Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null at io.ballerina.cli.cmd.PushCommand.createLocalToolsJsonIfLocalTool(PushCommand.java:433) at io.ballerina.cli.cmd.PushCommand.pushBalaToCustomRepo(PushCommand.java:402) at io.ballerina.cli.cmd.PushCommand.pushPackage(PushCommand.java:282) at io.ballerina.cli.cmd.PushCommand.execute(PushCommand.java:186) at java.base/java.util.Optional.ifPresent(Optional.java:178) at io.ballerina.cli.launcher.Main.main(Main.java:58)

This issue occurred when the tool_id, a mandatory field, is missing from bal-tools.json.  https://github.com/Xenowa/ballerina-tool-extension-methods/blob/0eca890c85470a8e11b8191b358d01a1de39df11/BridgeCommand/tool-bridge/BalTool.toml#L2 contains some  inappropriate chracters. That's why it's not parsed properly.
