### ISSUE TITLE
[Bug]: Stacktrace in output when doing concurrent transactions

### ISSUE THREAD

**Issue by buehlefs** [ballerina-platform/ballerina-lang#42241]
### Description

When transactions are executed concurrently sometimes the following stacktrace appears in the console output without noticable effects on execution.
```
[2024-02-28 13:56:28,238] SEVERE {b7a.log.crash} - Cannot invoke "io.ballerina.runtime.api.values.BObject.get(io.ballerina.runtime.api.values.BString)" because "twopcTxn" is null 
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.api.values.BObject.get(io.ballerina.runtime.api.values.BString)" because "twopcTxn" is null
        at ballerinai.transaction.0.commons.$lambda$_1(commons.bal:102)
        at ballerinai.transaction.0.commons.$lambda$_1$lambda16$(commons.bal:94)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce

The issue should be reproducible with the test code in issue #41281
It seems to be more likely to occur if both transactions are rolled back but can also occur if both transactions commit without errors.

### Affected Version(s)

Ballerina 2201.8.5 (Swan Lake Update 8)
Ballerina 2201.8.4

### OS, DB, other environment details and versions

OS: Ubuntu 20.04 running inside WSL2

JDBC Connector used:
```toml
[[platform.java11.dependency]]
artifactId="sqlite-jdbc"
version="3.36.0.1"
groupId="org.xerial"
```

### Related area

-> Compilation

**Comment by dsplayerX** [comment]
Hi @buehlefs,

I was unable to reproduce this issue on Ballerina 2201.8.6, as it appears to have already been resolved. It's possible the cause is the same one I mentioned [here](https://github.com/ballerina-platform/ballerina-lang/issues/41281#issuecomment-1970808531).

Would you be able to test on your end to see if the issue persists in 2201.8.6?

**Comment by buehlefs** [comment]
That may be the case. I could not reproduce it on 2201.8.6. We can probably close this for now.
