### ISSUE TITLE
[Bug]: Test failure with `NoSuchFieldError` for latest lang master in `kafka`

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-lang#42408]
### Description

The following exception is thrown when running the kafka module tests using GraalVM. 
```
[2024-03-26 04:34:00,580] SEVERE {b7a.log.crash} - ballerinax.kafka$test.3.frames.$frame$transactionalProducerWithAbortTest._371 
java.lang.NoSuchFieldError: ballerinax.kafka$test.3.frames.$frame$transactionalProducerWithAbortTest._371
	at ballerinax.kafka$test.3.tests.producer_client_tests.transactionalProducerWithAbortTest(tests/producer_client_tests.bal:268)
	at ballerinax.kafka$test.3.tests.test_execute-generated_1.transactionalProducerWithAbortTest$lambda142$(tests/test_execute-generated_1.bal:146)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
 

	transactionalProducerWithAbortTest has failed.
```
Failed workflow - https://github.com/ballerina-platform/module-ballerinax-kafka/actions/runs/8425199587/job/23070739985#step:10:940

Related test case - https://github.com/ballerina-platform/module-ballerinax-kafka/blob/master/ballerina/tests/producer_client_tests.bal#L221

### Related area

-> Runtime

**Comment by dilanSachi** [comment]
This is passing with the timestamp - 2201.9.0-20240318-204500-991f718f
So the issue should be after this

**Comment by dilanSachi** [comment]
Please note that this is reproducible for normal build as well with latest lang master - https://github.com/ballerina-platform/module-ballerinax-kafka/actions/runs/8478222418/job/23230221983?pr=1100#step:5:1077

The lang timestamp is 2201.9.0-20240329-102900-48a9e694
