### ISSUE TITLE
[Bug]: Runtime crashes for worker message passing when the workers are within a conditional block

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42515]
### Description

$title.

### Steps to Reproduce

```ballerina
import ballerina/io;

public function main() {
    execute(false);
}

function execute(boolean isForked) {
    if isForked {
        fork {
            worker A {
                5 -> B;
                string value = <- B;
                io:println(string `Received string '${value}' from worker B`);
            }

            worker B {
                int value = <- A;
                io:println(string `Received int '${value}' from worker A`);
                "a" -> A;
            }
        }
    }
}
```

```cmd
[2024-04-09 15:32:27,308] SEVERE {b7a.log.crash} - Cannot read field "functionInvocation" because "parent" is null 
java.lang.NullPointerException: Cannot read field "functionInvocation" because "parent" is null
        at org.ballerinalang.langlib.internal.WorkerChannels.autoClose(WorkerChannels.java:40)
        at ballerina.lang&0046__internal.0.auto-close-channels.autoClose(auto-close-channels.bal:22)
        at temp.execute(temp.bal:0)
        at temp.main(temp.bal:5)
        at $_init.$moduleExecute(.)
        at $_init.$lambda$$moduleExecute$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Affected Version(s)

2201.9.x branch

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
Problem seems to be in the autoclose lang lib invocation we assume channel information is always available in the immediate parent strand. However, in this sample, there isn't an immediate parent strand. The current strand holds the channels.
