### ISSUE TITLE
[Bug]: NPE with the Ballerina strand dump tool

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42567]
### Description

Getting a NullPointerException when trying to get a strand dump for a Ballerina application

### Steps to Reproduce

1. Run the following application:

```bal
import ballerina/http;

service /api on new http:Listener(9090) {

    resource function get greeting(http:Request req) returns string {
        return "Hello, World!";
    }
}
```

2. Generate a strand dump before making any requests - This is working

3. Make a cURL request to this endpoint:

```console
$ curl http://localhost:9090/api/greeting
```

4. Generate the strand dump again and you will see the following NPE:
```bal
tharmigan@tharmigan sample % bal run
Compiling source
        tharmigan/sample:0.1.0

Running executable

Ballerina Strand Dump [2024/04/17 13:24:56]
===========================================

Total strand group count        :       3
Total strand count              :       2
Active strand group count       :       0
Active strand count             :       0

===========================================



Exception in thread "SIGTRAP handler" java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.scheduling.ItemGroup.getId()" because the return value of "io.ballerina.runtime.internal.scheduling.Strand.getStrandGroup()" is null
        at io.ballerina.runtime.internal.troubleshoot.StrandDump.populateAvailableStrandGroups(StrandDump.java:77)
        at io.ballerina.runtime.internal.troubleshoot.StrandDump.getStrandDump(StrandDump.java:46)
        at io.ballerina.runtime.internal.launch.LaunchUtils.lambda$startTrapSignalHandler$0(LaunchUtils.java:80)
        at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
        at java.base/jdk.internal.misc.Signal$1.run(Signal.java:219)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Affected Version(s)

Ballerina SwanLake Update 9

### OS, DB, other environment details and versions

MacOS

### Related area

-> Runtime

### Related issue(s) (optional)

May be a regression from this issue: https://github.com/ballerina-platform/ballerina-lang/issues/42566

### Suggested assignee(s) (optional)

@HindujaB

**Comment by TharmiganK** [comment]
Note that when I remove the `http:Request` from the resource signature, it is working as expected

**Comment by TharmiganK** [comment]
This seems to be a regression issue from this issue: https://github.com/ballerina-platform/ballerina-lang/issues/42566

This issue is fixed with the above issue's fix

**Comment by rdulmina** [comment]
Closing as fixed with https://github.com/ballerina-platform/ballerina-lang/issues/42566
