### ISSUE TITLE
[Bug]: Compiler crash when using `xml:map` with an xml union type 

### ISSUE THREAD

**Issue by poorna2152** [ballerina-platform/ballerina-lang#42771]
### Description

Consider the following code,

```ballerina
public function main() {
    xml<xml:Element>|xml<xml:Comment> x1 = xml `<a><b><c><e>foo</e></c></b><d><g>bar</g></d></a>`;
    xml x2 = <xml> x1;
    _ = xml:map(xml:elements(x2), v => xml:getChildren(v));
}
```

When run this program crashes with the following log, 

```
[2024-05-17 15:01:15,937] SEVERE {b7a.log.crash} - _1 
java.lang.NoSuchFieldError: _1
        at poorna.xmlns_def.0.main.main(main.bal:183)
        at poorna.xmlns_def.0.$_init.$moduleExecute(xmlns_def)
        at poorna.xmlns_def.0.$_init.$lambda$$moduleExecute$(xmlns_def)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Affected Version(s)

2201.9.0

### Related area

-> Runtime

**Comment by Thushara-Piyasekara** [comment]
Following is a simplified version of the code snippet,

```ballerina
public function main() {
    xml:Element|xml:Text x1 = xml `<a></a>`;
    _ = xml:map(xml:elements(<xml>x1), v => xml:getChildren(v));
}
```

**Comment by poorna2152** [comment]
https://github.com/ballerina-platform/ballerina-release/issues/2699
