### ISSUE TITLE
[Bug]: Bad sad error when query inside a for each loop

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#43154]
### Description

```
map<json> queryParams = {
};

public function main() returns error? {
    foreach [string, json] [key1, value1] in queryParams.entries() {
        var a = from string _ in []
            select key1;
    }
}
```

The above code gives

```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-07-23 11:19:47,715] SEVERE {b7a.log.crash} - Cannot read field "name" because "varDcl" is null 
java.lang.NullPointerException: Cannot read field "name" because "varDcl" is null
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1369)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2184)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1803)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2385)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:596)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:623)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:341)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:182)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:425)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:384)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:793)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:317)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:166)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:119)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:118)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:223)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
This is resolved with https://github.com/ballerina-platform/ballerina-lang/issues/40615
