### ISSUE TITLE
[Bug]: Compiler crashed when running bal build

### ISSUE THREAD

**Issue by KATTA-00** [ballerina-platform/ballerina-lang#43286]
### Description

I'm currently developing a Ballerina connector for the [OpenAI Fine-tunes API](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes). While writing the examples, I attempted to use the connector by pushing it to my repository and then running the examples. However, when I tried to run bal build on the project, I encountered the following error:

> ballerina: Oh no, something really went wrong. Bad. Sad.
> 
> We appreciate it if you can report the code that broke Ballerina in 
> https://github.com/ballerina-platform/ballerina-lang/issues with the
> log you get below and your sample code.
> 
> We thank you for helping make us better.
> 
> [2024-08-14 16:53:56,078] SEVERE {b7a.log.crash} - Cannot read field "flags" because "type.tsymbol" is null 
> java.lang.NullPointerException: Cannot read field "flags" because "type.tsymbol" is null
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2809)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:70)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3605)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3296)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:70)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3605)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1707)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
>         at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:217)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:355)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:344)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:332)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
>         at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:217)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:320)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:192)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
>         at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:435)
>         at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
>         at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
>         at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
>         at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:244)
>         at io.ballerina.projects.Package.getCompilation(Package.java:151)
>         at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:324)
>         at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:156)
>         at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:295)
>         at java.base/java.util.Optional.ifPresent(Optional.java:178)
>         at io.ballerina.cli.launcher.Main.main(Main.java:58)
> 
> ERROR [Sarcastic_bot:(1:1,1:1)] Compilation failed due to: Cannot read field "flags" because "type.tsymbol" is null

**main.bal:**
 
> import ballerina/io;
> import ballerina/lang.runtime;
> import ballerinax/openai.finetunes;
> 
> configurable string token = ?;
> const SERVICE_URL = "https://api.openai.com/v1";
> const TRAINING_FILENAME = "training.jsonl";
> const VALIDATION_FILENAME = "validation.jsonl";
> const TRAINING_FILEPATH = "./data/" + TRAINING_FILENAME;
> const VALIDATION_FILEPATH = "./data/" + VALIDATION_FILENAME;
> 
> final finetunes:ConnectionConfig config = {auth: {token}};
> final finetunes:Client openAIFinetunes = check new finetunes:Client(config, SERVICE_URL);
> 
> public function main() returns error? {
> 
>     byte[] trainingFileContent = check io:fileReadBytes(TRAINING_FILEPATH);
>     byte[] validationFileContent = check io:fileReadBytes(VALIDATION_FILEPATH);
> 
>     finetunes:CreateFileRequest trainingFileRequest = {
>         file: {fileContent: trainingFileContent, fileName: TRAINING_FILENAME},
>         purpose: "fine-tune"
>     };
>     finetunes:CreateFileRequest validationFileRequest = {
>         file: {fileContent: validationFileContent, fileName: VALIDATION_FILENAME},
>         purpose: "fine-tune"
>     };
> 
>     finetunes:OpenAIFile trainingFileResponse =
>         check openAIFinetunes->/files.post(trainingFileRequest);
>     finetunes:OpenAIFile validationFileResponse =
>         check openAIFinetunes->/files.post(validationFileRequest);
> 
>     string trainingFileId = trainingFileResponse.id;
>     string validationFileId = validationFileResponse.id;
>     io:println("Training file id: " + trainingFileId);
>     io:println("Validation file id: " + validationFileId);
> 
>     finetunes:CreateFineTuningJobRequest fineTuneRequest = {
>         model: "gpt-3.5-turbo",
>         training_file: trainingFileId,
>         validation_file: validationFileId,
>         hyperparameters: {
>             n_epochs: 15,
>             batch_size: 3,
>             learning_rate_multiplier: 0.3
>         }
>     };
> 
>     finetunes:FineTuningJob fineTuneResponse =
>         check openAIFinetunes->/fine_tuning/jobs.post(fineTuneRequest);
>     string fineTuneJobId = fineTuneResponse.id;
>     io:println("Fine-tuning job id: " + fineTuneJobId);
> 
>     finetunes:FineTuningJob fineTuneJob =
>         check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
> 
>     io:print("Validating files...");
>     while fineTuneJob.status == "validating_files" {
>         io:print(".");
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         runtime:sleep(1);
>     }
> 
>     io:print("\nFiles validated successfully.");
>     while fineTuneJob.status == "queued" {
>         io:print(".");
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         runtime:sleep(1);
>     }
> 
>     io:println("\nTraining...");
>     finetunes:ListFineTuningJobEventsResponse eventsResponse;
>     while fineTuneJob.status == "running" {
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         eventsResponse = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId]/events.get();
>         io:println(eventsResponse.data[0].message);
>         runtime:sleep(1);
>     }
> 
>     if fineTuneJob.status != "succeeded" {
>         io:println("Fine-tuning job failed.");
>         return;
>     }
> 
>     io:println("\nFine-tuning job details: ");
>     io:println("Fine-tuned Model: ", fineTuneJob.fine_tuned_model);
>     io:println("Model: ", fineTuneJob.model);
>     io:println("Fine-tuning job completed successfully.");
> }

`bal pack` and `bal push --repository local` were used to push the connector to the local repository and used the below config in the Ballerina.toml
> [[dependency]]
> org = "ballerinax"
> name = "openai.finetunes"
> version = "1.0.5"
> repository = "local"

Finally, after deleting the local cache (.ballerina\repositories\local) and repeating the entire process, the issue did not occur again. It seems like there was a conflict with the local cache when pushing to it. 

### Steps to Reproduce

1. **Set Up the Environment**:
   - Ensure you have Ballerina installed on your system.
   - Clone or download the Ballerina connector for the OpenAI Fine-tunes API from [this repository](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes).

2. **Write the Example Code**:
   - Create a new Ballerina project.
   - Use the provided example code (`main.bal`) in your project.
   - Ensure you have the required files, such as `training.jsonl` and `validation.jsonl`, in the appropriate directories.

3. **Build and Push the Connector**:
   - Run `bal pack` in the connector project to create a `.bala` file.
   - Push the connector to the local repository using the command:
     ```bash
     bal push --repository local
     ```
   - Update your `Ballerina.toml` file in your example project with the following dependency:
     ```toml
     [[dependency]]
     org = "ballerinax"
     name = "openai.finetunes"
     version = "1.0.5"
     repository = "local"
     ```

4. **Attempt to Build the Project**:
   - Run `bal build` on your project where you are using the connector.
   - This should trigger the error you described.

**Comment by rdulmina** [comment]
I could not reproduce the issue using both ballerina 2201.9.2 and 2201.10.0. However, added a null check before accessing `tsymbol.flags` #43733

**Comment by rdulmina** [comment]
This can be reproduced by removing the colon in the client initialization line
`final finetunes:Client openAIFinetunes = check new finetunesClient(config, SERVICE_URL);` Note the colon is removed from the RHS side

**Comment by rdulmina** [comment]
Can be reproduced with the following sample
```bal
class A {};

final A openAIFinetunes = check new f();
```

**Comment by rdulmina** [comment]
The following sample gives `error: jVM generation is not supported for type other` when compiling due to same issue

```bal
int[] a = [1, 2, 3, 4, 5];

int[] b = from var i in a select <B> i;
```
