### ISSUE TITLE
[Bug]: Error occurs when using observability tracing with wso2.controlplane module

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-lang#43342]
### Description

The following runtime error occurs when we use observability tracing with wso2.controlplane module.

```
ballerina: started publishing traces to Jaeger on localhost:4317
[2024-09-02 09:50:19,379] SEVERE {b7a.log.crash} - Cannot read field "span" because "parentSpan" is null 
java.lang.NullPointerException: Cannot read field "span" because "parentSpan" is null
        at io.ballerina.runtime.observability.tracer.BSpan.start(BSpan.java:120)
        at io.ballerina.runtime.observability.tracer.TracingUtils.startObservation(TracingUtils.java:54)
        at io.ballerina.runtime.observability.tracer.BallerinaTracingObserver.startClientObservation(BallerinaTracingObserver.java:35)
        at io.ballerina.runtime.observability.ObserveUtils.startCallableObservation(ObserveUtils.java:411)
        at ballerinax.wso2&0046controlplane.1.init.registerInDashboardServer(init.bal:48)
        at ballerinax.wso2&0046controlplane.1.init.$lambda$_0(init.bal:23)
        at ballerinax.wso2&0046controlplane.1.lambdas.$_generated5init.$lambda$_0$lambda0$(init.bal:22)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce

Use the following Ballerina code.

```ballerina
import ballerina/http;
import ballerinax/jaeger as _;
import ballerina/io;
import ballerina/lang.runtime;
import ballerinax/wso2.controlplane as _;

service / on new http:Listener(8091) {
    resource function get echo(http:Caller caller, http:Request req) returns error? {
        http:Response res = new;
        res.setTextPayload("Hello, World from service /echo");
        var result = caller->respond(res);
        if (result is error) {
            io:println("Error sending response");
        }
    }
}
```

You should configure the `Ballerina.toml` as follows.

```toml
[build-options]
observabilityIncluded = true
remoteManagement=true
```

Your `Config.toml` file should consist the following configurations.
```toml
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="localhost"  # Optional Configuration. Default value is localhost
agentPort=4317             # Optional Configuration. Default value is 55680

[ballerinax.wso2.controlplane.dashboard]
url = "https://localhost:9743/dashboard/api"
heartbeatInterval = 10
groupId = "group1"
mgtApiUrl ="https://localhost:9264/management/"
nodeId = "Social Media Service"
```

### Related area

-> Observability

**Comment by NipunaMadhushan** [comment]
I have tested with similar scenarios such as following which includes client invokes in the `init()` function as well as a declared variable.

```ballerina
import ballerina/http;
import ballerinax/jaeger as _;
import ballerina/io;
import ballerina/lang.runtime;
import ballerinax/wso2.controlplane as _;

http:Client clientEP = check new("www.google.com");
http:Response res = check getResponse();  

function getResponse() returns http:Response|error {
    return check clientEP->/;
}

service / on new http:Listener(8091) {
    isolated function init() returns error? {
        worker w1 returns error? {
            check sendRequest();
        }
    }

    resource function get echo(http:Caller caller, http:Request req) returns error? {
        http:Response res = new;
        res.setTextPayload("Hello, World from service /echo");
        var result = caller->respond(res);
        if (result is error) {
            io:println("Error sending response");
        }
    }
}

isolated function sendRequest() returns error? {
    while (true) {
        http:Client clientEP = check new("www.google.com");
        http:Response res = check clientEP->/; 
        runtime:sleep(3);
    }
}

This is very similar to the function we have used in wso2.controlplane module [init method](https://github.com/ballerina-platform/module-ballerinax-wso2.controlplane/blob/main/ballerina/init.bal#L21). I have included a worker as well but couldn't recreate the issue so far.

**Comment by NipunaMadhushan** [comment]
I was able to recreate the issue with a sample project import to another. The sample project I used as follows.

```ballerina
import ballerina/io;
import ballerina/http;

isolated function init() {
    worker w1 returns error? {
        io:println("Init worker started");
        check sendRequest();
    }
}

isolated function sendRequest() returns error? {
    http:Client clientEP = check new("www.google.com");
    http:Response res = check clientEP->/; 
    io:println("Response: ", res.statusCode);
}
```

Then I imported this to another project and the issue occurred.

I have noticed that this issue occurs only when we use a client invoke inside a worker in an imported module init method.

**Comment by NipunaMadhushan** [comment]
When I was looking into the issue further, I noticed that, when we use tracing only, the issue does not occur. When we use both metrics and tracing, the issue occurs. 

When I was debugging, I noticed that the observer context was created but the span was not set for the parent. That is why the issue occurred.
