### ISSUE TITLE
[Bug]: Getting NPE when accessing a field with a default value which is generated from rest binding with the optional field

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#43359]
### Description

I am creating a record A using a rest binding with another record B. The record B and record A has the same record typed field, but in record B the field is optional and in record A that field has a default value. When accessing a member of this fiedl from record A, I am getting a NPE. But it worked in in Ballerina SwanLake Update 8(2201.8.x)

### Steps to Reproduce

Use the following code to reproduce the issue:
```bal
import ballerina/http;
import ballerina/io;

public type ConnectionConfig record {|
    http:BearerTokenConfig|http:OAuth2RefreshTokenGrantConfig auth;
    http:HttpVersion httpVersion = http:HTTP_2_0;
    http:ClientHttp1Settings http1Settings?;
    http:ClientHttp2Settings http2Settings?;
    decimal timeout = 60;
    string forwarded = "disable";
    http:PoolConfiguration poolConfig?;
    http:CacheConfig cache?;
    http:Compression compression = http:COMPRESSION_AUTO;
    http:CircuitBreakerConfig circuitBreaker?;
    http:RetryConfig retryConfig?;
    http:ResponseLimitConfigs responseLimits?;
    http:ClientSecureSocket secureSocket?;
    http:ProxyConfig proxy?;
    boolean validation = true;
|};

public function main() {
    ConnectionConfig connectionConfig = {
        auth: {
            refreshToken: "mockRefreshToken",
            clientId: "mockClientId",
            clientSecret: "mockClientSecret",
            refreshUrl: "mockRefreshUrl"
        }
    };
    http:ClientConfiguration config = {...connectionConfig};
    io:println(config.cache.enabled);
}
```

Run the file:
```console
$ bal run test.bal

Compiling source
        test.bal

Running executable

[2024-09-04 12:38:39,740] SEVERE {b7a.log.crash} - Cannot invoke "io.ballerina.runtime.internal.values.MapValueImpl.getUnboxedBooleanValue(io.ballerina.runtime.api.values.BString)" because "<local37>" is null 
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.values.MapValueImpl.getUnboxedBooleanValue(io.ballerina.runtime.api.values.BString)" because "<local37>" is null
        at test_service.main(test_service.bal:32)
        at $_init.$moduleExecute(.)
        at $_init.$lambda$$moduleExecute$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Affected Version(s)

Ballerina SwanLake Update9(2201.9.x) and Update10(2201.10.x)

### Related area

-> Runtime

**Comment by heshanpadmasiri** [comment]
Simplified example
```
iimport ballerina/io;

type Inner record {|
    int foo;
|};

type Outer record {|
    Inner inner?;
|};

type OuterXBase record {
    Inner inner = {foo: 10};
};

type OuterX record {|
    *OuterXBase; // <- default value must come from the inclusion
|};

public function main() {
    Outer o = {};
    OuterX ox = {...o}; // <- without spread this works
    io:println(ox.inner.foo);
}
```

**Comment by heshanpadmasiri** [comment]
The fix will be released with the 10.1 patch versions as well.

https://github.com/ballerina-platform/ballerina-release/issues/2751

**Comment by Nuvindu** [comment]
https://github.com/ballerina-platform/ballerina-release/issues/2750
