### ISSUE TITLE
[Bug]: Intermittent test failures in the daily full build pipeline

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-lang#43375]
### Description

A test case intermittently fails in full build pipeline workflows
https://github.com/ballerina-platform/ballerina-release/actions/workflows/daily-full-build-2201.10.x.yml
https://github.com/ballerina-platform/ballerina-release/actions/workflows/daily-full-build-2201.9.x.yml

**Error Log**: https://github.com/ballerina-platform/ballerina-release/actions/runs/10786735888/job/29914114989#step:7:8175

### Related area

-> Compilation

**Comment by Nuvindu** [comment]
Found another intermittent test failure in jballerina tests.

https://github.com/ballerina-platform/ballerina-release/actions/runs/10806352425/job/29974994888#step:7:2549

```
[2024-09-11 06:58:08,203] SEVERE {org.ballerinalang.test.packaging.ModuleExecutionFlowTests} - testListenerStopHandlerAsyncCall: FAILED -> Timeout expired waiting for matching log: calling gracefulStop for dynamic listener of current module 

jBallerina-Test-Suite > ballerina-packerina-tests > org.ballerinalang.test.packaging.ModuleExecutionFlowTests > testListenerStopHandlerAsyncCall FAILED
    org.ballerinalang.test.context.BallerinaTestException: Timeout expired waiting for matching log: calling gracefulStop for dynamic listener of current module
        at app//org.ballerinalang.test.context.LogLeecher.waitForText(LogLeecher.java:119)
        at app//org.ballerinalang.test.packaging.ModuleExecutionFlowTests.testListenerStopHandlerAsyncCall(ModuleExecutionFlowTests.java:269)
```
