### ISSUE TITLE
[Bug]: Dead code elimination mark the annotation type as unused

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#43580]
### Description

> $Subject

### Steps to Reproduce

Testing protobuf package with the dead code elimination and when I run the tests without any external dependency annotation. I am getting the following error:
```console
        protobuf.types.any
[2024-11-13 17:16:37,531] SEVERE {b7a.log.crash} - $typedesce$MessageDescriptor 
java.lang.NoSuchFieldError: $typedesce$MessageDescriptor
        at ballerina.protobuf&0046types&0046any$test.1.tests.any_msg_pb.$annot_func$_911(tests/any_msg_pb.bal:25)
        at ballerina.protobuf&0046types&0046any$test.1.$_init.$gen$&0046&0060init&0062(protobuf.types.any:2)
        at ballerina.protobuf&0046types&0046any$test.1.$_init.$moduleInit(protobuf.types.any)
        at ballerina.protobuf&0046types&0046any$test.1.$_init.$moduleExecute(protobuf.types.any)
        at ballerina.protobuf&0046types&0046any$test.1.$_init.$lambda$$moduleExecute$(protobuf.types.any)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

This `MessageDescriptor` is the type of the annotation and [the annotation is present in the test source code](https://github.com/ballerina-platform/module-ballerina-protobuf/blob/77c53b163ccacf6db1ecb90daf392dc70369685b/ballerina/modules/types.any/tests/any_msg_pb.bal#L25)

### Affected Version(s)

Ballerina SwanLake Update 11

### OS, DB, other environment details and versions

Mac OS

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Seems like this happens when the annotation is defined in the default module and a non-default module's tests use the annotation. 

test_proj

```ballerina
public type Config record {|
    int value;
|};

public annotation Config annot on type;

public function main() {
    
}
```

test_proj.mod's tests

```ballerina
import ballerina/test;
import test_proj;

@test_proj:annot {
    value: 100
}
type TestType record {|

|};

@test:Config
function testFn() {
}
```

```cmd
$ bal test --eliminate-dead-code --dead-code-elimination-report
Compiling source
        maryamm/test_proj:0.1.0
Duration for unused BIR node analysis : 1ms
    maryamm/test_proj:0.1.0 : 1ms


Running Tests

        test_proj.mod
[2024-11-14 13:26:57,174] SEVERE {b7a.log.crash} - $typedesce$Config 
java.lang.NoSuchFieldError: $typedesce$Config
        at maryamm.test_proj&0046mod$test.0.tests.mod_test.$annot_func$_816(tests/mod_test.bal:4)
        at maryamm.test_proj&0046mod$test.0.$_init.$gen$&0046&0060init&0062(test_proj.mod:2)
        at maryamm.test_proj&0046mod$test.0.$_init.$moduleInit(test_proj.mod)
        at maryamm.test_proj&0046mod$test.0.$_init.$moduleExecute(test_proj.mod)
        at maryamm.test_proj&0046mod$test.0.$_init.$lambda$$moduleExecute$(test_proj.mod)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by MaryamZi** [comment]
In `io.ballerina.projects.JBallerinaBackend#registerUnusedBIRNodes`, the module gets sorted to the end, and then `shouldOptimize(moduleContext) && (isRootModule(moduleContext) || moduleContext.isUsed())` evaluates to false for the module.

https://github.com/ballerina-platform/ballerina-lang/blob/feature-codegen-optimizer/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java#L253

**Comment by Thushara-Piyasekara** [comment]
The reason for this behavior is because we added a constraint to not analyze non parent packages of testable packages during DCE. This was done to avoid false positive test results (see https://docs.google.com/document/d/1WNBN9hI7rbCL6wpozDAwImagUrM-sn7F/ for more details). 

In the implementation, the logic for handling those scenarios was to stop the analysis if we refer to a non parent package node from a testable package. 

![image](https://github.com/user-attachments/assets/bdcbbccf-2f0e-4e10-9ba3-dd8ea14031c0)

Even though we stop the analysis, since the dependencies of testable packages are not optimized, the code will work. But in this case the logic used to determine testable pkg to build pkg usages fails. 

![image](https://github.com/user-attachments/assets/e2892716-b457-447b-92dc-d094a637b589)

We will have to update the logic to handle these cases or not support such cases. 

I vaguely remember a having a conversation with @hasithaa about whether we should allow running tests from non build pkg modules with DCE flags. If I remember correctly the conclusion was not to allow such cases. But I cant remember the exact reasoning. I will look into this more and update.

**Comment by Thushara-Piyasekara** [comment]
> In `io.ballerina.projects.JBallerinaBackend#registerUnusedBIRNodes`, the module gets sorted to the end, and then `shouldOptimize(moduleContext) && (isRootModule(moduleContext) || moduleContext.isUsed())` evaluates to false for the module.
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/feature-codegen-optimizer/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java#L253

We can fix this by allowing the analyzer to enter the non default modules with testable pkgs by checking for `moduleContext.bLangPackage().hasTestablePackage()` condtion. 

But this will not fully fix the issue because even though the analyzer goes inside the pkg it will stop analyzing the type reference because the following condition fails.

https://github.com/ballerina-platform/ballerina-lang/blob/092cc69d06e1332a36c70e7970bc9825a6bd1c41/compiler/ballerina-lang/src/main/java/io/ballerina/projects/UsedTypeDefAnalyzer.java#L185 

This condition only works for testable pkg's parent pkg references. We will have to introduce a new mechanism to determine build pkg references from non default testable pkgs.

Also we will have to update the logic in a similar manner for function invocations as well. 
https://github.com/ballerina-platform/ballerina-lang/blob/092cc69d06e1332a36c70e7970bc9825a6bd1c41/compiler/ballerina-lang/src/main/java/io/ballerina/projects/UsedBIRNodeAnalyzer.java#L471

**Comment by chiranSachintha** [comment]
> Seems like this happens when the annotation is defined in the default module and a non-default module's tests use the annotation.
> 
> test_proj
> 
> ```ballerina
> public type Config record {|
>     int value;
> |};
> 
> public annotation Config annot on type;
> 
> public function main() {
>     
> }
> ```
> 
> test_proj.mod's tests
> 
> ```ballerina
> import ballerina/test;
> import test_proj;
> 
> @test_proj:annot {
>     value: 100
> }
> type TestType record {|
> 
> |};
> 
> @test:Config
> function testFn() {
> }
> ```
> 
> ```batchfile
> $ bal test --eliminate-dead-code --dead-code-elimination-report
> Compiling source
>         maryamm/test_proj:0.1.0
> Duration for unused BIR node analysis : 1ms
>     maryamm/test_proj:0.1.0 : 1ms
> 
> 
> Running Tests
> 
>         test_proj.mod
> [2024-11-14 13:26:57,174] SEVERE {b7a.log.crash} - $typedesce$Config 
> java.lang.NoSuchFieldError: $typedesce$Config
>         at maryamm.test_proj&0046mod$test.0.tests.mod_test.$annot_func$_816(tests/mod_test.bal:4)
>         at maryamm.test_proj&0046mod$test.0.$_init.$gen$&0046&0060init&0062(test_proj.mod:2)
>         at maryamm.test_proj&0046mod$test.0.$_init.$moduleInit(test_proj.mod)
>         at maryamm.test_proj&0046mod$test.0.$_init.$moduleExecute(test_proj.mod)
>         at maryamm.test_proj&0046mod$test.0.$_init.$lambda$$moduleExecute$(test_proj.mod)
>         at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
>         at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
>         at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
>         at java.base/java.lang.Thread.run(Thread.java:840)
> ```

Encountering the following error with latest changes with the `feature-optimizer-codegen` branch.
```
[2024-11-26 11:32:12,484] SEVERE {b7a.log.crash} - Compile the module first! 
java.lang.IllegalStateException: Compile the module first!
        at io.ballerina.projects.ModuleContext.getBLangPackageOrThrow(ModuleContext.java:227)
        at io.ballerina.projects.ModuleContext.bLangPackage(ModuleContext.java:214)
        at io.ballerina.projects.JBallerinaBackend.markTestDependenciesForDuplicateBIRGen(JBallerinaBackend.java:294)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:193)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:180)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:150)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:179)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:149)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:137)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:242)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:415)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:63)
```
Create an issue for this https://github.com/ballerina-platform/ballerina-lang/issues/43652
