### ISSUE TITLE
[Task]: Enable `workerVariableVisibilityTest` debugger test 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#43636]
### Description

$subject

### Describe your task(s)

This debugger test is disabled due to failing intermittently.
Error log
```
debugger-intg-test-suite > debugger-intg-tests > org.ballerinalang.debugger.test.adapter.variables.VariableVisibilityTest > workerVariableVisibilityTest FAILED
    org.ballerinalang.test.context.BallerinaTestException: Error occurred when fetching debug hit variables
        at app//org.ballerinalang.debugger.test.utils.DebugTestRunner.fetchVariables(DebugTestRunner.java:547)
        at app//org.ballerinalang.debugger.test.adapter.variables.VariableVisibilityTest.workerVariableVisibilityTest(VariableVisibilityTest.java:561)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
            at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
            at org.ballerinalang.debugger.test.utils.client.DAPRequestManager.variables(DAPRequestManager.java:192)
            at org.ballerinalang.debugger.test.utils.client.DAPRequestManager.variables(DAPRequestManager.java:186)
            at org.ballerinalang.debugger.test.utils.DebugTestRunner.fetchVariables(DebugTestRunner.java:540)
            ... 1 more
```

### Related area

-> Debugger

**Comment by keizer619** [comment]
Need to check restore this
