### ISSUE TITLE
[Bug]: HashCode Exception When Nested Records Contain Duplicate Field Names

### ISSUE THREAD

**Issue by Ajai-Suvendran** [ballerina-platform/ballerina-lang#43673]
### Description

While performing data mapping in Ballerina, an issue arises when a record contains two fields, one of which is another nested record. If the nested record has a field with the same name as a field in the outer record, it causes a hashCode exception, as seen in the following stack trace:
at java.base/java.util.Objects.hashCode(Objects.java:103)
at org.wso2.ballerinalang.compiler.bir.model.BirScope.hashCode(BirScope.java:29)
This issue may occur due to duplicate field names in the hierarchy, leading to a conflict during compilation or runtime.

### Steps to Reproduce

[test.zip](https://github.com/user-attachments/files/17988681/test.zip)

### Affected Version(s)

2202.10.1

### Related area

-> Runtime

**Comment by ravinperera00** [comment]
Seems to be a compiler frontend issue. @gimantha will be looking into this.

**Comment by gimantha** [comment]
@Ajai-Suvendran I can compile and run the project successfully. Should I do any changes to the project? 

<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/e80c2d3a-91a2-44be-9077-de66cdc863f8" />

**Comment by gimantha** [comment]
Closing the issue as we cannot reproduce this issue. Please reopen if you need any help
