### ISSUE TITLE
[HTTP] NPE: when the request is sent with a wrong veb

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#4481]
I see the below stacktrace when the request is sent with a wrong http verb. As you can see in the bal service I have constrained it to HTTP Get. But I sent a post request. Even though I get the expected response, I do see the below NPE stacktrace. 

**Service** - 

import ballerina.net.http;

@http:configuration {basePath:"/echo"}
service<http> echo {

    @http:resourceConfig {
        methods:["GET"],
        path:"/{foo}"
    }
    resource echo (http:Request req, http:Response resp, string foo) {
        string payload = req.getStringPayload();
        payload = payload + foo;
        resp.setStringPayload(payload);
        _ = resp.send();
    }
}

**Request** 

curl -v "http://localhost:9090/echo/bar" -d foo

**Stacktrace**

[2018-01-23 11:34:58,646] ERROR {org.ballerinalang.net.http.HttpUtil} - Method not allowed  
[2018-01-23 11:34:58,652] ERROR {org.wso2.transport.http.netty.listener.SourceHandler} - Error while notifying listeners 
java.lang.NullPointerException
	at org.ballerinalang.net.http.HttpDispatcher.getSignatureParameters(HttpDispatcher.java:134)
	at org.ballerinalang.net.http.BallerinaHTTPConnectorListener.onMessage(BallerinaHTTPConnectorListener.java:55)
	at org.wso2.transport.http.netty.contractimpl.HttpWsServerConnectorFuture.notifyHttpListener(HttpWsServerConnectorFuture.java:69)
	at org.wso2.transport.http.netty.listener.SourceHandler.notifyRequestListener(SourceHandler.java:149)
	at org.wso2.transport.http.netty.listener.SourceHandler.channelRead(SourceHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.wso2.transport.http.netty.listener.WebSocketServerHandshakeHandler.channelRead(WebSocketServerHandshakeHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pubudu91** [comment]
Tried the following on v0.970.2-SNAPSHOT and it's working properly. Did not observe the above mentioned stack trace. Hence closing this.
```ballerina
import ballerina/http;
import ballerina/config;

endpoint http:Listener listener {
    port:9090
};

@http:ServiceConfig {
    basePath:"/hello"
}
service<http:Service> hello bind listener {

    @http:ResourceConfig {
        path:"/{foo}",
        methods: ["GET"]
    }
    sayHello (endpoint outboundEP, http:Request request, string foo) {
        http:Response response = new;
        string payload = check request.getPayloadAsString();
        payload += foo;
        response.setPayload(payload);
        _ = outboundEP -> respond(response);
    }
}
```
