### ISSUE TITLE
NPE when migrating caching tests

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#5397]
**Description:**
```
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:322)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:303)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:549)
	at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:91)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineInvokableSymbolParams$43(SymbolEnter.java:817)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineInvokableSymbolParams(SymbolEnter.java:820)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineInvokableSymbol(SymbolEnter.java:798)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:458)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:237)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:237)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:166)
	at org.wso2.ballerinalang.compiler.PackageLoader.definePackage(PackageLoader.java:221)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadAndDefinePackage(PackageLoader.java:144)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:324)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:78)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$0(SymbolEnter.java:195)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:195)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:166)
	at org.wso2.ballerinalang.compiler.PackageLoader.definePackage(PackageLoader.java:221)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:120)
	at org.wso2.ballerinalang.compiler.Compiler.define(Compiler.java:153)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:97)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:209)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:183)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:102)
	at org.ballerinalang.test.caching.CachingTest.setup(CachingTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by uthaiyashankar** [comment]
This problem was there previously. It is no longer there. Should have been fixed..
