### ISSUE TITLE
EmptyStackException

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#5406]
**Description:**
```
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.endFunctionDef(BLangPackageBuilder.java:1079)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitFunctionDefinition(BLangParserListener.java:348)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$FunctionDefinitionContext.exitRule(BallerinaParser.java:1480)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:458)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:102)
	at org.wso2.ballerinalang.compiler.parser.Parser.lambda$parse$0(Parser.java:77)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:77)
	at org.wso2.ballerinalang.compiler.PackageLoader.sourceCompile(PackageLoader.java:176)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:229)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:233)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadAndDefinePackage(PackageLoader.java:139)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:324)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:78)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$0(SymbolEnter.java:195)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:195)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:166)
	at org.wso2.ballerinalang.compiler.PackageLoader.definePackage(PackageLoader.java:221)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:120)
	at org.wso2.ballerinalang.compiler.Compiler.define(Compiler.java:153)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:97)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:209)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:183)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:102)
	at org.ballerinalang.test.streaming.AggregationTest.setup(AggregationTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by uthaiyashankar** [comment]
This problem was there previously. It is no longer there. Should have been fixed..
