### ISSUE TITLE
"Internal error occured" when trying to get a value from cache which is not exist

### ISSUE THREAD

**Issue by dnwick** [ballerina-platform/ballerina-lang#5717]
**Description:**
when trying to run following ,
var cacheReturn = cache.get("Name");  <= cache do not have a Name.

Getting following error log in bre.log

[2018-03-22 16:48:28,903] ERROR {org.ballerinalang.launcher.Main} - ballerina: internal error occurred
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:654)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation$BLangAttachedFunctionInvocation.accept(BLangInvocation.java:205)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1504)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1104)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1504)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:434)
        at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:91)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:471)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1528)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:460)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:744)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1528)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:460)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:581)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:85)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1528)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:460)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1518)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:322)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1535)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:267)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:179)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1484)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:226)
        at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:153)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:129)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:87)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:81)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:77)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:65)

I'm expecting a error thrown but getting above internal error occured

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Tried the following program on v0.970.0-alpha1-SNAPSHOT.
```ballerina
import ballerina/io;
import ballerina/caching;

function main(string[] args) {
    caching:Cache cache = caching:createCache("test", 60000, 1024, 0.25);
    var entry = cache.get("Name");
}
```
Got the following error:
```
error: ballerina.runtime:CallFailedException, message: call failed
	at .:main(5717.bal:6)
caused by error, message: 'null' cannot be cast to 'ballerina.caching:CacheEntry'
	at ballerina.caching:get(caching.bal:140)
```

**Comment by uthaiyashankar** [comment]
Now it returns (). 

```
import ballerina/io;
import ballerina/cache;

function main(string... args) {
    cache:Cache cache = new (expiryTimeMillis = 60000, capacity=1024, evictionFactor=0.25);
    var entry = cache.get("Name");
    match entry {
        () => {io:println("Cache empty");}
        any a => {}
    }
}
```

output 

```
Cache empty

Process finished with exit code 0
```
