### ISSUE TITLE
Compiling with syntax error throws and compiler level nullpointerexception 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#6137]
**Description:**
When try to add a struct field in the following ballerina program in composer compiler throws an error. There are facts to believe that this happens because of we are not passing a custom error strategy and handle the error. But need to look in to how to suppress these kind of exceptions using the default error strategy. 

###### Program
```
struct people{
    int age;
}

function <people p> name () {
    
}
```

###### Error
```
2018-03-30 10:25:24 WARN  MSF4JHttpConnectorListener:242 - Unmapped exception
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.endFunctionDef(BLangPackageBuilder.java:1086)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitFunctionDefinition(BLangParserListener.java:348)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$FunctionDefinitionContext.exitRule(BallerinaParser.java:1471)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:459)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:103)
	at org.wso2.ballerinalang.compiler.parser.Parser.lambda$parse$0(Parser.java:77)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:77)
	at org.wso2.ballerinalang.compiler.PackageLoader.sourceCompile(PackageLoader.java:306)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageFromEntity(PackageLoader.java:300)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:210)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:199)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:69)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:65)
	at org.ballerinalang.composer.service.ballerina.parser.service.util.ParserUtils.compile(ParserUtils.java:855)
	at org.ballerinalang.composer.service.ballerina.parser.service.util.ParserUtils.compile(ParserUtils.java:815)
	at org.ballerinalang.composer.service.ballerina.parser.service.BallerinaParserService.validateAndParse(BallerinaParserService.java:419)
	at org.ballerinalang.composer.service.ballerina.parser.service.BallerinaParserService.validateAndParseBFile(BallerinaParserService.java:167)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:217)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
(Remove the try catch in compile() in ParserUtil.java to get the exception)

1. Add a struct and a struct bound function.
2. Try to type in a new field to struct.

this also affect the whitespace parser.

**Comment by hevayo** [comment]
Issue is no longer valid since structs are removed from language after 0.970.0
