### ISSUE TITLE
Composer went OOM when running infinite loop

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6317]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 11:02 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3599_

----

Composer went OOM.
### code 
```ballerina
import ballerina.lang.system;

function main (string[] args) {
    int counter =0;
    while (counter < 500) {
        system:println("yes");
    }
}
```
### Error

java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /home/yasassri/QA_STUFF/current_work/0.94Release/ballerina-tools-0.93.1-SNAPSHOT/logs/heap-dump-tool.hprof ...
Heap dump file created [1448246764 bytes in 24.688 secs]
Exception in thread "Thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Class.newReflectionData(Class.java:2511)
	at java.lang.Class.reflectionData(Class.java:2503)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2577)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:150)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.pushMessageToClient(LaunchManager.java:295)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.pushMessageToClient(LaunchManager.java:305)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.streamOutput(LaunchManager.java:168)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager$1.run(LaunchManager.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 11:19 GMT_

----

**Environment**

Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/hemikak"><img src="https://avatars0.githubusercontent.com/u/4398820?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hemikak](https://github.com/hemikak)**
_Thursday Oct 12, 2017 at 12:17 GMT_

----

Can we get the ballerina source code for this ?

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yasassri](https://github.com/yasassri)**
_Friday Oct 13, 2017 at 04:54 GMT_

----

@hemikak This occurred several times, and the ballerina service was a simple main function with some system outs.  I will share the bal files when this happens again.

**Comment by hemikak** [comment]
Composer does not hang. Capable of stopping the program from running as well.
