### ISSUE TITLE
Can't parse B7a service using LSParserUtils

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#7295]
**Description:**
Consider following directory structure,

bal_project
|__.ballerina
|__servpkg
 __|__pet_service.bal

Assume my current working directory is `bal_project`. Now if I try to generate swagger for `pet_service.bal`, I'll get bellow error.
```
[2018-04-16 09:36:31,164] ERROR {org.ballerinalang.launcher.Main} - ballerina: internal error occurred 
java.lang.NullPointerException
	at org.ballerinalang.ballerina.swagger.convertor.service.SwaggerConverterUtils.generateOAS3Definitions(SwaggerConverterUtils.java:107)
	at org.ballerinalang.ballerina.swagger.convertor.service.SwaggerConverterUtils.generateOAS3Definitions(SwaggerConverterUtils.java:148)
	at org.ballerinalang.swagger.cmd.SwaggerCmd.exportFromBal(SwaggerCmd.java:159)
	at org.ballerinalang.swagger.cmd.SwaggerCmd.execute(SwaggerCmd.java:100)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```
However, if I try to do the same from a directory which doesn't contain a `.ballerina` directory, this works fine and I can get the output. Reason for this is LSParserUtils get confused with `.ballerina` in working directory and assume auto generated /tmp source root already have a `.ballerina` directory.

**Steps to reproduce:**
`cd bal_project`
`ballerina swagger export servepkg/pet_service.bal` => ballerina: internal error occurred

**Affected Versions:**
ballerina-tools-0.970.0-beta0

**OS, DB, other environment details and versions:**
Linux/Ubuntu

**Comment by praminda** [comment]
Issue not reproducible and scenario works as expected in latest master build: f801e6f01021be39bff1a7738a1473b60b247a15
