### ISSUE TITLE
XA transactions with mysql fail

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#7963]
**Description:**
Say there are two operations in the transaction block. When performing the second one, transaction fails and gets retried. Following exception can be observed at [1] when debugging. i.e. for some reason it is not possible to use the xid created when starting the first resource, to start the second resource which participates in the same transaction.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/v0.970.0-beta14/bvm/ballerina-core/src/main/java/org/ballerinalang/util/transactions/TransactionResourceManager.java#L215

```bash
com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_DUPID: The XID already exists
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:581)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:566)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.start(MysqlXAConnection.java:507)
	at org.ballerinalang.util.transactions.TransactionResourceManager.beginXATransaction(TransactionResourceManager.java:215)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.getDatabaseConnection(SQLDatasourceUtils.java:1498)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.executeUpdate(AbstractSQLAction.java:144)
	at org.ballerinalang.database.sql.actions.Update.execute(Update.java:62)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:322)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:195)
	at org.ballerinalang.bre.bvm.CPU.invokeVirtualFunction(CPU.java:2888)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:403)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:143)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:254)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:202)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:182)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:125)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:108)
	at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:72)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:118)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:111)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:258)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.sql.SQLException: XAER_DUPID: The XID already exists
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:560)
	... 23 more

```
This works with h2. Tried with mysql 5.6 and 5.7, observed the same behavior.

**Steps to reproduce:**
Run [1]. Transaction will get retried until the limit and aborted.

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/xa-transactions/xa_transactions.bal
**EDIT:** Above mentioned url is not valid for this scenario now. Therefore adding a url of a released tag. Please note that the syntax might differ from current versions.
https://github.com/ballerina-attic/ballerina-examples/blob/release-0.970.0-beta12/examples/distributed-transactions/distributed-transactions.bal

**OS, DB, other environment details and versions:**
mysql

**Comment by Manuri** [comment]
According to [1] we are always passing TMNOFLAGS[2] regardless of whether we are initiating a transaction or joining an existing transaction. According to [3] when joining a transaction, should have passed TMJOIN[4] flag. However, I tried passing TMJOIN flag but it seems mysql does not support that[5]. Exception [6] was observed.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-core/src/main/java/org/ballerinalang/util/transactions/TransactionResourceManager.java#L215

[2] https://docs.oracle.com/javaee/7/api/javax/transaction/xa/XAResource.html#TMNOFLAGS

[3] https://docs.oracle.com/javaee/7/api/javax/transaction/xa/XAResource.html#start-javax.transaction.xa.Xid-int-

[4] https://docs.oracle.com/javaee/7/api/javax/transaction/xa/XAResource.html#TMJOIN

[5] https://bugs.mysql.com/bug.php?id=78498

[6] 
```bash
com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_INVAL: Invalid arguments (or unsupported command)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:583)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:568)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.start(MysqlXAConnection.java:509)
	at org.ballerinalang.util.transactions.TransactionResourceManager.beginXATransaction(TransactionResourceManager.java:217)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.getDatabaseConnection(SQLDatasourceUtils.java:1498)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.executeUpdate(AbstractSQLAction.java:144)
	at org.ballerinalang.database.sql.actions.Update.execute(Update.java:62)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:322)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:195)
	at org.ballerinalang.bre.bvm.CPU.invokeVirtualFunction(CPU.java:2888)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:403)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:143)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:254)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:202)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:182)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:125)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:108)
	at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:72)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:122)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:115)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:258)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
Caused by: java.sql.SQLException: XAER_INVAL: Invalid arguments (or unsupported command)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:562)
	... 23 more
```

**Comment by Manuri** [comment]
According to [1],
>For XA START, the JOIN and RESUME clauses are not supported.
>For XA END the SUSPEND [FOR MIGRATE] clause is not supported.

So, for MySQL, sending TMJOIN flag at [2] wouldn't help. 
Also, it seems MySQL's isSameRM functionality is also incorrect[3][4]

Therefore, this cannot be fixed from Ballerina side. However, for the resource managers that do support JOIN flag, need to implement join logic appropriately. 

Created a separate issue[5] to track that. 

[1] https://dev.mysql.com/doc/refman/5.6/en/xa-statements.html
[2] https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.0/bvm/ballerina-core/src/main/java/org/ballerinalang/util/transactions/TransactionResourceManager.java#L268
[3] https://bugs.mysql.com/bug.php?id=72036
[4] https://forums.mysql.com/read.php?39,606354,606354
[5] https://github.com/ballerina-platform/ballerina-lang/issues/12803
