### ISSUE TITLE
Some HTTPS request calls failed due to "javax.net.ssl.SSLException: Received close_notify during handshake"

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8319]
**Description:**
When an HTTPS service is invoked with Jmeter client (thread count = 100) observed that some of the requests failed due to "javax.net.ssl.SSLException: Received close_notify during handshake" exception

**Steps to reproduce:**
1. Use the artefacts in to reproduce the issue - https://github.com/sashikamw/ballerina-stabilitytest/tree/master/ServiceScenarios/Scenario05_HTTPS/released 

**Affected Versions:**
ballerina-runtime-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Observations**
1. Some of the HTTPS calls are failing

```
summary +    880 in 00:00:30 =   29.4/s Avg:  3403 Min:  1549 Max: 10759 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  22485 in 00:12:46 =   29.3/s Avg:  3395 Min:  1405 Max: 27986 Err:     6 (0.03%)
summary +    895 in 00:00:30 =   29.8/s Avg:  3348 Min:  1506 Max: 22261 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  23380 in 00:13:16 =   29.4/s Avg:  3394 Min:  1405 Max: 27986 Err:     6 (0.03%)
summary +    892 in 00:00:30 =   29.8/s Avg:  3371 Min:  1516 Max: 11212 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  24272 in 00:13:46 =   29.4/s Avg:  3393 Min:  1405 Max: 27986 Err:     6 (0.02%)
summary +    892 in 00:00:30 =   29.7/s Avg:  3364 Min:  1464 Max: 12046 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  25164 in 00:14:16 =   29.4/s Avg:  3392 Min:  1405 Max: 27986 Err:     6 (0.02%)
```
2. Client Side error (Jmeter)

```
javax.net.ssl.SSLException: Received close_notify during handshake
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1901)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2002)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
	at org.apache.jmeter.protocol.http.sampler.LazySchemeSocketFactory.connectSocket(LazySchemeSocketFactory.java:97)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.jmeter.protocol.http.sampler.hc.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:318)
	at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.open(MeasuringConnectionManager.java:114)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:697)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:455)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1189)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1178)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:490)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sashikamw** [comment]
Passthrough service and the backend service have following logs

Passthrough Service
```
[2018-05-08 13:01:10,197] ERROR {org.wso2.transport.http.netty.sender.channel.TargetChannel} - Remote host closed the connection before completing outbound request 
java.io.IOException: Remote host closed the connection before completing outbound request
	at org.wso2.transport.http.netty.sender.channel.TargetChannel.lambda$notifyIfFailure$3(TargetChannel.java:269)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at org.wso2.transport.http.netty.sender.channel.TargetChannel.notifyIfFailure(TargetChannel.java:265)
	at org.wso2.transport.http.netty.sender.channel.TargetChannel.writeOutboundRequest(TargetChannel.java:245)
	at org.wso2.transport.http.netty.sender.channel.TargetChannel.lambda$null$1(TargetChannel.java:202)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Backend Service
```
 
[2018-05-08 16:06:24,221] WARN  {org.wso2.transport.http.netty.listener.SourceHandler} - Idle timeout triggered while reading inbound request  
[2018-05-08 16:06:24,222] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-05-08 16:06:24,223] ERROR {org.wso2.transport.http.netty.common.Util} - Remote client closed the connection before completing outbound response 
java.io.IOException: Remote client closed the connection before completing outbound response
	at org.wso2.transport.http.netty.common.Util.lambda$checkForResponseWriteStatus$9(Util.java:599)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at org.wso2.transport.http.netty.common.Util.checkForResponseWriteStatus(Util.java:595)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponseHeaderAndBody(HttpOutboundRespListener.java:187)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponse(HttpOutboundRespListener.java:138)
	at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.lambda$null$35(HttpOutboundRespListener.java:94)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

[ballerina-internalHTTPSBackedn.log.gz](https://github.com/ballerina-platform/ballerina-lang/files/1983493/ballerina-internalHTTPSBackedn.log.gz)
[ballerina-internal-HTTPSPassthrough.log.gz](https://github.com/ballerina-platform/ballerina-lang/files/1983494/ballerina-internal-HTTPSPassthrough.log.gz)

**Comment by Bhashinee** [comment]
javax.net.ssl.SSLException: Received close_notify during handshake indicates the termination of the ssl connection. This issue can depend on the performance of the machine and due to network issues. For example this issue will not happen in a high performing machines for a concurrency like 100 threads. But still there is a possibility to get this exception in those when there are longevity situations with high concurrency.
