### ISSUE TITLE
NPE thrown when building the ballerina-lang 15th May 2018

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8557]
**Description:**
NPE thrown when building the ballerina-lang 15th May 2018

**Steps to reproduce:**
1.run mvn clean install -Dmaven.test.skip=true inside ballerina-lang after taking a git pull
**Affected Versions:**

```
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack-dependencies) @ stdlib-compile ---
[INFO] Unpacking /home/shavantha/products/ballerina/ballerina-lang/stdlib/ballerina-builtin/target/ballerina-builtin-0.970.2-SNAPSHOT.zip to /home/shavantha/products/ballerina/ballerina-lang/stdlib/stdlib-compile/target/ballerina-source with includes "**/*.bal" and excludes ""
[INFO] Unpacking /home/shavantha/products/ballerina/ballerina-lang/stdlib/ballerina-http/target/ballerina-http-0.970.2-SNAPSHOT.zip to /home/shavantha/products/ballerina/ballerina-lang/stdlib/stdlib-compile/target/ballerina-source with includes "**/*.bal" and excludes ""
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ stdlib-compile ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ stdlib-compile ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/shavantha/products/ballerina/ballerina-lang/stdlib/stdlib-compile/src/main/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ stdlib-compile ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/shavantha/products/ballerina/ballerina-lang/stdlib/stdlib-compile/target/classes
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/shavantha/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/shavantha/.m2/repository/org/slf4j/slf4j-simple/1.7.22/slf4j-simple-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[INFO] 
[INFO] >>> spotbugs-maven-plugin:3.1.1:check (analyze-compile) > :spotbugs @ stdlib-compile >>>
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.1:spotbugs (spotbugs) @ stdlib-compile ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.1:check (analyze-compile) < :spotbugs @ stdlib-compile <<<
[INFO] 
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.1:check (analyze-compile) @ stdlib-compile ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (gen-balo) @ stdlib-compile ---
error: builtin:0.0.0/docs.bal:21:1: redeclared builtin symbol 'docData'
error: builtin:0.0.0/tablelib.bal:89:1: redeclared builtin symbol 'TableConfig'
error: builtin:0.0.0/errors.bal:18:5: redeclared builtin symbol 'message'
error: builtin:0.0.0/errors.bal:19:5: redeclared builtin symbol 'cause'
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:106)
	at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupMemberSymbol(SymbolResolver.java:527)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:654)
	at org.wso2.ballerinalang.compiler.tree.types.BLangUserDefinedType.accept(BLangUserDefinedType.java:66)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:385)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:376)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.validateFuncReceiver(SymbolEnter.java:1496)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:504)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineRecordInitFunction(SymbolEnter.java:1233)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineRecordFields$31(SymbolEnter.java:973)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineRecordFields(SymbolEnter.java:971)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:227)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:190)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:167)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:345)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:241)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:120)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:132)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:76)
	at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ stdlib-compile ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ stdlib-compile
```

**Comment by SupunS** [comment]
This is no longer reproducible in the master branch. Hence closing the issue.
