### ISSUE TITLE
[Performance] Nullpointer exception when 100KB message is sent with higher concurrency

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8639]
**Description:**
Observed the following Nullpointer exception in when 100KB message is sent with high concurrency.

**Steps to reproduce:**
1. Use the pass-through scenario (100kb json message is sent to netty backend - HTTP)

**Affected Versions:**
ballerina-platform-0.970.1

**Observations**
```
[2018-05-17 19:40:52,161] ERROR {org.ballerinalang.net.http.BallerinaHTTPConnectorListener} - Error in http server connectornull 
java.lang.NullPointerException
	at org.wso2.transport.http.netty.listener.SourceHandler.handleIdleErrorScenario(SourceHandler.java:286)
	at org.wso2.transport.http.netty.listener.SourceHandler.userEventTriggered(SourceHandler.java:269)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:494)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-05-17 19:40:56,665] ERROR {org.ballerinalang.net.http.BallerinaHTTPConnectorListener} - Error in http server connectornull 
java.lang.NullPointerException
	at org.wso2.transport.http.netty.listener.SourceHandler.handleIdleErrorScenario(SourceHandler.java:286)
	at org.wso2.transport.http.netty.listener.SourceHandler.userEventTriggered(SourceHandler.java:269)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:494)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```
[ballerina-passthorugh-round1-100k.log.zip](https://github.com/ballerina-platform/ballerina-lang/files/2016579/ballerina-passthorugh-round1-100k.log.zip)

**Comment by VijithaEkanayake** [comment]
This issue is fixed with the PR[1]. Carried out a load test for 100 KB messages with concurrency of 100 for 30mins and didn't encounter any issues. Following is the summary of the test. Fixed version: 0.980

Label | # Samples | Average | Min | Max | Std. Dev. | Error % | Throughput | Received KB/sec | Sent KB/sec | Avg. Bytes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HTTP Request | 5058545 | 35 | 1 | 10757 | 68.89 | 0.000% | 2780.43626 | 272235.66 | 272032.02 | 100261
TOTAL | 5058545 | 35 | 1 | 10757 | 68.89 | 0.000% | 2780.43626 | 272235.66 | 272032.02 | 100261

[1]. https://github.com/wso2/transport-http/pull/179
