### ISSUE TITLE
[Performance] Few request failures due to "Remote client closed the connection before completing outbound response"

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8640]
**Description:**
Observed few requests getting failed due to "Remote client closed the connection before completing outbound response" when the throughput is around 1000, 2000 range

**Steps to reproduce:**
Passthrough HTTP service, with netty backend

**Affected Versions:**
ballerina-platform-0.970.1

**Observations**
```
[2018-05-17 01:34:13,149] WARN  {org.wso2.transport.http.netty.sender.TargetHandler} - Idle timeout triggered while reading inbound response
[2018-05-17 01:34:13,150] WARN  {org.wso2.transport.http.netty.sender.TargetHandler} - Idle timeout has reached hence closing the connection 39a5e871
[2018-05-17 01:34:13,151] ERROR {org.wso2.transport.http.netty.common.Util} - Remote client closed the connection before completing outbound response
java.io.IOException: Remote client closed the connection before completing outbound response
        at org.wso2.transport.http.netty.common.Util.lambda$checkForResponseWriteStatus$9(Util.java:599)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
        at org.wso2.transport.http.netty.common.Util.checkForResponseWriteStatus(Util.java:595)
        at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponseBody(HttpOutboundRespListener.java:198)
        at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.writeOutboundResponse(HttpOutboundRespListener.java:149)
        at org.wso2.transport.http.netty.contractimpl.HttpOutboundRespListener.lambda$null$35(HttpOutboundRespListener.java:102)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

[ballerina-passthroug-round1.log.zip](https://github.com/ballerina-platform/ballerina-lang/files/2016578/ballerina-passthroug-round1.log.zip)

**Comment by riyafa** [comment]
The default idle timeout is 60s and when the idle timeout is reached while reading or before reading the response it will close the connection. After the connection is closed if we try to send a message then this exception is thrown. This is to be expected. This might be because the backend is slow. Try increasing`timeoutMillis` in the client config to fix this.
