### ISSUE TITLE
[Performance] "NotSslRecordException: not an SSL/TLS record" warning with HTTPS passthrough scenario

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8661]
**Description:**
Observed few "io.netty.handler.ssl.NotSslRecordException" WARNs when executing HTTPs passthrough scenario. However, did not observe any errors in the jtl files.

**Steps to reproduce:**
1. Following scenario is used - https://github.com/sashikamw/performance-ballerina/blob/master/distribution/scripts/ballerina-scripts/bal/https_passthrough.bal 

**Affected Versions:**
ballerina-platform-0.970.1

**Observations**
```
[2018-05-19 13:23:51,748] WARN  {io.netty.channel.DefaultChannelPipeline} - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. 
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0300002a25e00000000000436f6f6b69653a206d737473686173683d546573740d0a0100080003000000
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0300002a25e00000000000436f6f6b69653a206d737473686173683d546573740d0a0100080003000000
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1138)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 16 more
```

Also, the following warning message was logged

```
[2018-05-19 10:39:24,359] WARN  {io.netty.util.concurrent.DefaultPromise} - An exception was thrown by org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1$$Lambda$45/1758686810.operationComplete() 
java.lang.IllegalArgumentException: Duplicate handler name: idleStateHandler
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1071)
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:302)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:259)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
	at org.wso2.transport.http.netty.sender.channel.TargetChannel.setEndPointTimeout(TargetChannel.java:166)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.prepareTargetChannelForHttp(DefaultHttpClientConnector.java:226)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.startExecutingOutboundRequest(DefaultHttpClientConnector.java:197)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.lambda$null$5(DefaultHttpClientConnector.java:184)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpClientConnector$1.lambda$onSuccess$6(DefaultHttpClientConnector.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:832)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
[ballerina-https-passthrough-round1.log.zip](https://github.com/ballerina-platform/ballerina-lang/files/2021912/ballerina-https-passthrough-round1.log.zip)

**Comment by Bhashinee** [comment]
These 2 exceptions occur when you are trying to connect to a https server using an http url. When going through the ballerina service you have given you are trying to connect to a HTTP netty client from this endpoint. https://github.com/sashikamw/performance-ballerina/blob/master/distribution/scripts/ballerina-scripts/bal/https_passthrough.bal#L14 . Is that netty server a HTTP one?
Can you give further details on how you have implemented **HTTPS passthrough** scenario and at what time this occurs?

**Comment by sashikamw** [comment]
@Bhashinee These warnings were observed during the performance test when executing the above-given https passthrough service [1]. The backend is an HTTP netty echo service.

The scenario is automated to use different payload sizes, backend latency and concurrent users. For example : 
Payload sizes: 50B, 1K, 10K
backend latency (ms) : 0,30,500,1000
concurrency: 100, 200, 300, 1000, 2000

[1] https://github.com/sashikamw/performance-ballerina/blob/master/distribution/scripts/ballerina-scripts/bal/https_passthrough.bal

**Comment by Bhashinee** [comment]
Tested in ballerina-0.976.1-SNAPSHOT with a similar netty echo server backend locally with a 40 K payload for concurrency 100, 300, 500 for 30 mins each. This was not reproduced in this latest ballerina version.
