### ISSUE TITLE
[Windows][v0.970.1.]Can not connect to  localhost:5010

### ISSUE THREAD

**Issue by rswijesena** [ballerina-platform/ballerina-lang#8695]
Hello,

I am trying to run hello_service.bal using the composer on windows env. When I just try to run the file I am getting this error. From where this 5010 port is coming ?

[2018-05-23 14:31:11,029] ERROR {org.ballerinalang.launcher.Main} - failed to connect to localhost:5010 
java.lang.RuntimeException: failed to connect to localhost:5010
	at org.ballerinalang.logging.BLogManager.setHttpTraceLogHandler(BLogManager.java:163)
	at org.ballerinalang.logging.BLogManager.loadUserProvidedLogConfiguration(BLogManager.java:111)
	at org.ballerinalang.launcher.LauncherUtils.loadConfigurations(LauncherUtils.java:313)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:79)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.util.logging.SocketHandler.connect(Unknown Source)
	at java.util.logging.SocketHandler.<init>(Unknown Source)
	at org.ballerinalang.logging.BLogManager.setHttpTraceLogHandler(BLogManager.java:157)

**Comment by pahans** [comment]
@rswijesena 5010 port is a port composer use to communicate with running service to get trace logs.
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8706
