### ISSUE TITLE
Registering struct out params gives errors due to unimplemented method in Postgres driver

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#8700]
**Description:**
$subject. Following is the error.

```bash
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgCallableStatement.registerOutParameter(int,int,String) is not yet implemented.
	at org.postgresql.Driver.notImplemented(Driver.java:683)
	at org.postgresql.jdbc.PgCallableStatement.registerOutParameter(PgCallableStatement.java:519)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.registerOutParameter(HikariProxyCallableStatement.java)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.setArrayValue(SQLDatasourceUtils.java:667)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.setParameter(AbstractSQLAction.java:685)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.setParameter(AbstractSQLAction.java:597)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.createProcessedStatement(AbstractSQLAction.java:584)
	at org.ballerinalang.database.sql.actions.AbstractSQLAction.executeProcedure(AbstractSQLAction.java:213)
	at org.ballerinalang.database.sql.actions.Call.execute(Call.java:65)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:322)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:195)
	at org.ballerinalang.bre.bvm.CPU.invokeVirtualFunction(CPU.java:2888)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:403)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:143)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:254)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:202)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:182)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:125)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:108)
	at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:97)
	at org.ballerinalang.launcher.util.BRunUtil.invoke(BRunUtil.java:192)
	at org.ballerinalang.test.connectors.sql.SQLActionsTest.testArrayInOutParameters(SQLActionsTest.java:504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```

**OS, DB, other environment details and versions:**
postgresql 9.6.8
driver version: 42.2.1

Can be reproduced by running test function [1].

[1] https://github.com/ballerina-platform/ballerina-lang/blob/v0.971.0/tests/ballerina-test/src/test/resources/test-src/connectors/sql/sql_actions_test.bal#L1158

**Comment by Manuri** [comment]
This is not supported with the official driver. Not a bug in Ballerina jdbc client, hence closing.
