### ISSUE TITLE
[Performance] "Error while waiting and releasing the content" with 100K message and 1000 concurrency

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8767]
**Description:**
Observed "ERROR {org.wso2.transport.http.netty.message.BlockingEntityCollector} - Error while waiting and releasing the content io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1" when 100k message payload is used with 1000 concurrency. 

Scenario - Transforming 100K JSON payload to XML and send to the netty backend (echo service)

https://github.com/sashikamw/performance-ballerina/blob/master/distribution/scripts/ballerina-scripts/bal/transformation.bal 

**Affected Versions:**
ballerina-platform-0.972.0. (1G heap)

**Observations**
Server goes OOM after some time.
```
[2018-05-29 09:42:31,130] ERROR {org.wso2.transport.http.netty.message.BlockingEntityCollector} - Error while waiting and releasing the content 
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:94)
	at org.wso2.transport.http.netty.message.BlockingEntityCollector.waitAndReleaseAllEntities(BlockingEntityCollector.java:191)
	at org.wso2.transport.http.netty.message.HTTPCarbonMessage.waitAndReleaseAllEntities(HTTPCarbonMessage.java:326)
	at org.ballerinalang.net.http.DataContext.notifyInboundResponseStatus(DataContext.java:59)
	at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.sendOutboundRequest(AbstractHTTPAction.java:267)
	at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction.executeNonBlockingAction(AbstractHTTPAction.java:256)
	at org.ballerinalang.net.http.actions.httpclient.Post.execute(Post.java:57)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:330)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:195)
	at org.ballerinalang.bre.bvm.CPU.invokeVirtualFunction(CPU.java:2894)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:409)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:144)
	at org.ballerinalang.bre.bvm.BLangScheduler$WorkerExecutor.run(BLangScheduler.java:255)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by riyafa** [comment]
Based on the heap dump obtained in this test it can be noted that this performance issue is not related to outbound throttling. The OOM in this case is because of the high concurrency and the JSON to xml conversion performed on a 100kB payload.

**Comment by riyafa** [comment]
Because of the high concurrency this issue can be resolved by using a higher heap size or by limiting concurrency before reaching ballerina. Hence closing the issue.
