### ISSUE TITLE
Fix failing tests in TableTest on Postgres

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#9024]
**Description:**
Following are the failing 46 tests.

```
[ERROR] testAssignNilToNonNillableBinary(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.023 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableBinary(table_nillable_mapping_negative.bal:193)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableBinary(TableTest.java:1019)

[ERROR] testAssignNilToNonNillableBlob(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableBlob(table_nillable_mapping_negative.bal:189)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableBlob(TableTest.java:1011)

[ERROR] testAssignNilToNonNillableBoolean(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.01 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableBoolean(table_nillable_mapping_negative.bal:157)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableBoolean(TableTest.java:947)

[ERROR] testAssignNilToNonNillableClob(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableClob(table_nillable_mapping_negative.bal:185)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableClob(TableTest.java:1003)

[ERROR] testAssignNilToNonNillableDate(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.007 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableDate(table_nillable_mapping_negative.bal:197)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableDate(TableTest.java:1027)

[ERROR] testAssignNilToNonNillableDateTime(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableDateTime(table_nillable_mapping_negative.bal:205)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 27
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableDateTime(TableTest.java:1043)

[ERROR] testAssignNilToNonNillableDecimal(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableDecimal(table_nillable_mapping_negative.bal:177)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableDecimal(TableTest.java:987)

[ERROR] testAssignNilToNonNillableDouble(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableDouble(table_nillable_mapping_negative.bal:153)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableDouble(TableTest.java:939)

[ERROR] testAssignNilToNonNillableFloat(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableFloat(table_nillable_mapping_negative.bal:149)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 24
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableFloat(TableTest.java:931)

[ERROR] testAssignNilToNonNillableInt(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableInt(table_nillable_mapping_negative.bal:141)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 22
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableInt(TableTest.java:915)

[ERROR] testAssignNilToNonNillableLong(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.007 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableLong(table_nillable_mapping_negative.bal:145)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableLong(TableTest.java:923)

[ERROR] testAssignNilToNonNillableNumeric(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableNumeric(table_nillable_mapping_negative.bal:165)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableNumeric(TableTest.java:963)

[ERROR] testAssignNilToNonNillableReal(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.01 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableReal(table_nillable_mapping_negative.bal:181)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableReal(TableTest.java:995)

[ERROR] testAssignNilToNonNillableSmallint(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.007 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableSmallint(table_nillable_mapping_negative.bal:173)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 27
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableSmallint(TableTest.java:971)

[ERROR] testAssignNilToNonNillableString(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableString(table_nillable_mapping_negative.bal:161)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableString(TableTest.java:955)

[ERROR] testAssignNilToNonNillableTime(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableTime(table_nillable_mapping_negative.bal:201)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableTime(TableTest.java:1035)

[ERROR] testAssignNilToNonNillableTimeStamp(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableTimeStamp(table_nillable_mapping_negative.bal:209)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 28
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableTimeStamp(TableTest.java:1051)

[ERROR] testAssignNilToNonNillableTinyInt(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Trying to assign a Nil value to a non-nillable field.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignNilToNonNillableTinyInt(table_nillable_mapping_negative.bal:169)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignNilToNonNillableField(table_nillable_mapping_negative.bal:221)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignNilToNonNillableTinyInt(TableTest.java:979)

[ERROR] testAssignToInvalidUnionBinary(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionBinary(table_nillable_mapping_negative.bal:285)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionBinary(TableTest.java:1149)

[ERROR] testAssignToInvalidUnionBlob(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionBlob(table_nillable_mapping_negative.bal:281)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionBlob(TableTest.java:1142)

[ERROR] testAssignToInvalidUnionBoolean(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.007 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionBoolean(table_nillable_mapping_negative.bal:249)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionBoolean(TableTest.java:1086)

[ERROR] testAssignToInvalidUnionClob(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionClob(table_nillable_mapping_negative.bal:277)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionClob(TableTest.java:1135)

[ERROR] testAssignToInvalidUnionDate(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionDate(table_nillable_mapping_negative.bal:289)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionDate(TableTest.java:1156)

[ERROR] testAssignToInvalidUnionDateTime(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionDateTime(table_nillable_mapping_negative.bal:297)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 27
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionDateTime(TableTest.java:1170)

[ERROR] testAssignToInvalidUnionDecimal(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionDecimal(table_nillable_mapping_negative.bal:269)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionDecimal(TableTest.java:1121)

[ERROR] testAssignToInvalidUnionDouble(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionDouble(table_nillable_mapping_negative.bal:245)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionDouble(TableTest.java:1079)

[ERROR] testAssignToInvalidUnionFloat(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionFloat(table_nillable_mapping_negative.bal:241)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 24
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionFloat(TableTest.java:1072)

[ERROR] testAssignToInvalidUnionInt(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionInt(table_nillable_mapping_negative.bal:233)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 22
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionInt(TableTest.java:1058)

[ERROR] testAssignToInvalidUnionLong(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.011 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionLong(table_nillable_mapping_negative.bal:237)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionLong(TableTest.java:1065)

[ERROR] testAssignToInvalidUnionNumeric(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionNumeric(table_nillable_mapping_negative.bal:257)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionNumeric(TableTest.java:1100)

[ERROR] testAssignToInvalidUnionReal(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.012 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionReal(table_nillable_mapping_negative.bal:273)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionReal(TableTest.java:1128)

[ERROR] testAssignToInvalidUnionSmallint(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.008 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionSmallint(table_nillable_mapping_negative.bal:265)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 27
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionSmallint(TableTest.java:1107)

[ERROR] testAssignToInvalidUnionString(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.011 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionString(table_nillable_mapping_negative.bal:253)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 25
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionString(TableTest.java:1093)

[ERROR] testAssignToInvalidUnionTime(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionTime(table_nillable_mapping_negative.bal:293)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 23
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionTime(TableTest.java:1163)

[ERROR] testAssignToInvalidUnionTimeStamp(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionTimeStamp(table_nillable_mapping_negative.bal:301)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 28
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionTimeStamp(TableTest.java:1177)

[ERROR] testAssignToInvalidUnionTinyInt(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.009 s  <<< FAILURE!
org.testng.TestException: 

The exception was thrown with the wrong message: expected ".*Corresponding Union type in the record is not an assignable nillable type.*" but got "error: ballerina.runtime:CallFailedException, message: call failed
	at testAssignToInvalidUnionTinyInt(table_nillable_mapping_negative.bal:261)
caused by error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 26
	at testAssignToInvalidUnionField(table_nillable_mapping_negative.bal:342)

"
	at org.ballerinalang.test.types.table.TableTest.testAssignToInvalidUnionTinyInt(TableTest.java:1114)

[ERROR] testBlobData(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.014 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: execute query failed: ERROR: relation "complextypes" does not exist
  Position: 23
	at testBlobData(table_type.bal:667)

	at org.ballerinalang.test.types.table.TableTest.testBlobData(TableTest.java:519)

[ERROR] testBlobInsert(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.021 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: execute query failed: ERROR: relation "complextypes" does not exist
  Position: 23
	at testBlobInsert(table_type.bal:723)

	at org.ballerinalang.test.types.table.TableTest.testBlobInsert(TableTest.java:539)

[ERROR] testComplexTypeInsertAndRetrieval(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.017 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: error in set binary value to statement: Large Objects may not be used in auto-commit mode.
	at testComplexTypeInsertAndRetrieval(table_type.bal:1111)

	at org.ballerinalang.test.types.table.TableTest.testComplexTypeInsertAndRetrieval(TableTest.java:693)

[ERROR] testGetComplexTypes(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: execute query failed: ERROR: relation "complextypes" does not exist
  Position: 45
	at testGetComplexTypes(table_type.bal:428)

	at org.ballerinalang.test.types.table.TableTest.testGetComplexTypes(TableTest.java:277)

[ERROR] testMappingNullToNillableTypes(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.006 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 249
	at testMappingNullToNillableTypes(table_nillable_mapping.bal:293)

	at org.ballerinalang.test.types.table.TableTest.testMappingNullToNillableTypes(TableTest.java:901)

[ERROR] testMappingToNillableTypeFields(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.01 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: error, message: execute query failed: ERROR: relation "datatypetablenillable" does not exist
  Position: 196
	at testMappingToNillableTypeFields(table_nillable_mapping.bal:110)

	at org.ballerinalang.test.types.table.TableTest.testMappingToNillableTypeFields(TableTest.java:795)

[ERROR] testToJsonComplex(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.021 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BallerinaException: Error in building JSON node: This connection has been closed.
	at org.ballerinalang.test.types.table.TableTest.testToJsonComplex(TableTest.java:257)

[ERROR] testToJsonComplexWithStructDef(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BallerinaException: Error in building JSON node: This connection has been closed.
	at org.ballerinalang.test.types.table.TableTest.testToJsonComplexWithStructDef(TableTest.java:269)

[ERROR] testToXmlComplex(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BallerinaException: failed to get xml as string: Trying to write END_DOCUMENT when document has no root (ie. trying to output empty document).
	at org.ballerinalang.test.types.table.TableTest.testToXmlComplex(TableTest.java:221)

[ERROR] testToXmlComplexWithStructDef(org.ballerinalang.test.types.table.TableTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BallerinaException: failed to get xml as string: Trying to write END_DOCUMENT when document has no root (ie. trying to output empty document).
	at org.ballerinalang.test.types.table.TableTest.testToXmlComplexWithStructDef(TableTest.java:241)

```

**OS, DB, other environment details and versions:**
Postgres 9.6.8

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/9023

**Comment by Manuri** [comment]
A set of tests in this issue will be fixed by #9808 
Rest of the tests (which are blob related) will be tracked by #9818
