### ISSUE TITLE
[HTTP2] Memory leak occurred when payload is not consumed by Ballerina server

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#9290]
**Description:**
An error occurred while a load testing with Ballerina HTTP/2 server. It is observed that only the ERROR message is displayed at `ballerina-internal.log` but the process can be continued.

**Steps to reproduce:**
This was reproducible for 100 concurrency with a small (1KB) or large (40KB) JSON payload after invoking for around 1 minute. Lesser the concurrency, take more than 1 minute to reproduce.

There are 2 possible scenarios to reproduce.
1. Jmeter HTTP1 Client -> Ballerina HTTP2 passthrough service -> Ballerina HTTP2 service.
2. Jmeter HTTP2 Client -> Ballerina HTTP2 service with SSL enabled.

### Scenario 1

**Ballerina HTTP2 passthrough service**
```
import ballerina/http;
import ballerina/log;

endpoint http:Listener passthroughEP {
    port:9090
};

endpoint http:Client nyseEP {
    url:"http://localhost:9191",
    httpVersion:"2.0"
};

@http:ServiceConfig {basePath:"/passthrough"}
service<http:Service> passthroughService bind passthroughEP {

    @http:ResourceConfig {
        path:"/"
    }
    passthrough (endpoint outboundEP, http:Request clientRequest) {
        var response = nyseEP -> forward("/nyseStock/stocks", clientRequest);
        match response {
            http:Response httpResponse => {
                _ = outboundEP -> respond(httpResponse);
            }
            error e => {
                http:Response errorResponse = new;
                log:printError("Error", err = e);
                json errMsg = {"error":"error occurred while invoking the service"};
                errorResponse.setJsonPayload(errMsg);
                _ = outboundEP -> respond(errorResponse);
            }
        }
    }
}
```
**Ballerina HTTP2 service**
```
import ballerina/http;
import ballerina/runtime;
import ballerina/io;

endpoint http:Listener passthroughEP {
    port:9191,
    httpVersion:"2.0"
};


@http:ServiceConfig {basePath:"/nyseStock"}
service<http:Service> nyseStockQuote bind passthroughEP {

    @http:ResourceConfig {
        path:"/stocks"
    }
    stocks (endpoint outboundEP, http:Request clientRequest) {
        http:Response res = new;
	var payload = clientRequest.getJsonPayload();
        match payload {
            json j => res.setJsonPayload(j);
            error err => io:println(err);
        }
        _ = outboundEP -> respond(res);
    }
}
```

### Scenario 2
**Ballerina HTTP2 service with SSL enabled**
```
import ballerina/http;
import ballerina/runtime;
import ballerina/io;

endpoint http:Listener passthroughEP {
    port:9191,
    httpVersion:"2.0",
    secureSocket: {
       keyStore: {
          path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
          password: "ballerina"
       }
   }
};


@http:ServiceConfig {basePath:"/nyseStock"}
service<http:Service> nyseStockQuote bind passthroughEP {

    @http:ResourceConfig {
        path:"/stocks"
    }
    stocks (endpoint outboundEP, http:Request clientRequest) {
        http:Response res = new;
        json payload = {"foo":"bar"};
        res.setJsonPayload(payload);
        _ = outboundEP -> respond(res);
    }
}
```

**Observations**
```
[2018-06-28 17:34:06,405] ERROR {io.netty.util.ResourceLeakDetector} - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
```

**Affected Versions:**
Ballerina-Platform-0.975.0

**Comment by ldclakmal** [comment]
The following log was observed under the **Scenario 1**.
```
[2018-06-28 17:57:09,217] WARN  {org.wso2.transport.http.netty.listener.SourceErrorHandler} - Exception occurred :failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)  
[2018-06-28 17:57:09,225] WARN  {org.wso2.transport.http.netty.listener.SourceErrorHandler} - Remote client closed connection while reading inbound request  
[2018-06-28 17:57:09,246] WARN  {org.wso2.transport.http.netty.listener.SourceErrorHandler} - Exception occurred :failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)  
.....
[2018-06-28 17:57:10,061] ERROR {org.ballerinalang.net.http.BallerinaHTTPConnectorListener} - Error in HTTP server connector: Remote client closed connection before initiating inbound request  
[2018-06-28 17:57:10,061] WARN  {io.netty.channel.DefaultChannelPipeline} - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. 
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 ....
```
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2145482/ballerina-internal.log)

**Comment by ldclakmal** [comment]
The issue occurred because of responding from Ballerina server side before the request body receives. So that `waitAndReleaseAllEntities` method is called before `addHttpContent` method in `BlockingEntityCollector`. Hence, some of `HttpContent` objects are not get released.

**Comment by ldclakmal** [comment]
With the above temporarily fix, the above-mentioned issue gets resolved, but the following issue gets reproduced. It is retrieved at the _Ballerina HTTP2 passthrough service_, not from the _Ballerina HTTP2 service_.

This is the error displayed at `ballerina-internal.log` of _Ballerina HTTP2 passthrough service_. This error gets repeated multiple times after the first one occurs and JMeter get hangs without sending requests.
```
[2018-07-25 09:59:55,335] ERROR {org.wso2.transport.http.netty.listener.WebSocketServerHandshakeHandler} - Error during WebSocket server handshake 
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:285)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1079)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1072)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1062)
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ldclakmal** [comment]
This issue was completely fixed by the following PR.
https://github.com/wso2/transport-http/pull/192/

But the changes of `BlockingEntityCollector.java` reverted back due to hanging of build in https://github.com/ballerina-lang/ballerina. That revert made this memory leak occurs.

The reason for hanging of build is due to state malfunction of ballerina-transport. It needs to be resolved first.

The follwing are the success screenshots of the load test run, after applying the changes of above PR. The load test were carried out for about an hour and there were about 23M successfull requests with 0% error rate.

![jmeter](https://user-images.githubusercontent.com/9639050/44595289-41058e80-a7e6-11e8-9651-d4cfbf8ef504.png)
![jvisualvm](https://user-images.githubusercontent.com/9639050/44595306-46fb6f80-a7e6-11e8-89bf-ba887ded0fbd.png)

**Comment by ldclakmal** [comment]
Few method of following test cases get failed due to the changes of  above mentioned PR.
- `FailoverClientTestCase`
- `ResponseNativeFunctionSuccessTest`
- `RetrySampleTestCase`
- `ServiceChainingSampleTestCase`

The reason was due to the state malfunction of `BlockingEntityCollector` in ballerina-transport because of the changes.

**Comment by ldclakmal** [comment]
With the above implementation of State-Machine also the server side issue which is mentioned below could be resolved.
```
[2018-06-28 17:34:06,405] ERROR {io.netty.util.ResourceLeakDetector} - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
```

But still the the error get displayed at `ballerina-internal.log` of Ballerina HTTP2 passthrough service. 
```
[2018-09-27 15:13:42,960] ERROR {org.wso2.transport.http.netty.contractimpl.listener.WebSocketServerHandshakeHandler} - Error during WebSocket server handshake 
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ldclakmal** [comment]
The load test was run for **12 hours** with **8KB payload**, **100 concurrency** and a **constant throughput of 1700/sec** (which is the throughput when the payload is consumed by the backend). Then the OOM issue was not reporduced.

![screenshot from 2018-10-11 09-48-29](https://user-images.githubusercontent.com/9639050/46792657-7ef04f00-cd61-11e8-94df-5852b364529b.png)

**Comment by ldclakmal** [comment]
The original issue and reason for this OOM is non-handling of HTTP/2 channel pool to distribute the workload among channels. The OOM is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/11858. Closing this issue, since a new issue is created to handle the original issue,
https://github.com/ballerina-platform/ballerina-lang/issues/11368
