### ISSUE TITLE
[gRPC] Proto-to-Ballerina tool is not working in windows 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#9607]
**Description:**
Referring to the issue reported by @gocoolp
When running proto-to-ballerina tool in windows to generate client stub, get below error.

> [2018-07-11 23:05:27,881] ERROR {org.ballerinalang.launcher.Main} -
> \gprc-service\guide\desc_gen\target\grpc\orderMgt-descriptor.desc: No such file or directory
> org.ballerinalang.protobuf.exception.BalGenToolException:
> C:\Gokul\Learning\VSCodeWorkspace\gprc-service\guide\desc_gen\target\grpc\orderMgt-descriptor.desc: No such file or directory
> at org.ballerinalang.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:103)
> at org.ballerinalang.protobuf.utils.BalFileGenerationUtils.getProtoByteArray(BalFileGenerationUtils.java:150)
> at org.ballerinalang.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:152)
> at java.util.Optional.ifPresent(Optional.java:159)
> at org.ballerinalang.launcher.Main.main(Main.java:66)

Need to find to root cause for this.

**Affected Versions:**
0.980.0 RC

**OS, DB, other environment details and versions:**
windows

**Related Issues (optional):**
#8889

**Suggested Labels (optional):**
bug

**Comment by daneshk** [comment]
Steps for reproduce
* Run below command in windows env
> ballerina grpc --input target/grpc/HelloWorld.proto --output client
