### ISSUE TITLE
Ballerina Composer Build Fails with Node.js 10

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#9682]
**Steps to reproduce:**
build with `mvn clean install -Dmaven.test.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true`

**Affected Versions:**
0.980.1-SNAPSHOT (master) on 19/July/2018

**OS, DB, other environment details and versions:**
Windows 10

$ npm --version
6.1.0

$ node --version
v10.6.0

BuildLog.
```[INFO] --- exec-maven-plugin:1.5.0:exec (npm run build (compile)) @ ballerina-composer-web ---

> ballerina-composer@0.980.1 build C:\git\ballerina\composer\modules\web
> cross-env NODE_ENV=production webpack --config webpack.config.js

(node:8560) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[BABEL] Note: The code generator has deoptimised the styling of "C:/git/ballerina/composer/modules/web/node_modules/monaco-editor/esm/vs/language/css/_deps/vscode-css-languageservice/data/browsers.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/git/ballerina/composer/modules/web/node_modules/monaco-editor/esm/vs/language/typescript/lib/lib-ts.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/git/ballerina/composer/modules/web/node_modules/monaco-editor/esm/vs/language/typescript/lib/lib-es6-ts.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/git/ballerina/composer/modules/web/node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js" as it exceeds the max of "500KB".
clean-webpack-plugin: C:\git\ballerina\composer\modules\web\dist has been removed.
clean-webpack-plugin: 1 file(s) excluded - themes
C:\git\ballerina\composer\modules\web\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readF

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at Compiler.<anonymous> (C:\git\ballerina\composer\modules\web\webpack.config.js:198:24)
    at Compiler.applyPlugins (C:\git\ballerina\composer\modules\web\node_modules\tapable\lib\Tapable.js:61:14)
    at C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\Compiler.js:484:8
    at Compiler.applyPluginsAsyncSeries (C:\git\ballerina\composer\modules\web\node_modules\tapable\lib\Tapable.js:195:46)
    at Compiler.compile (C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\Compiler.js:481:7)
    at C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\Compiler.js:236:10
    at Compiler.readRecords (C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\Compiler.js:388:10)
    at C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\Compiler.js:233:9
    at next (C:\git\ballerina\composer\modules\web\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.compiler.plugin (C:\git\ballerina\composer\modules\web\node_modules\webpack\lib\CachePlugin.js:35:59)
    at next (C:\git\ballerina\composer\modules\web\node_modules\tapable\lib\Tapable.js:204:14)
    at C:\git\ballerina\composer\modules\web\node_modules\webpack-webfont\dist\WebfontPlugin.js:139:24
    at Immediate.<anonymous> (C:\git\ballerina\composer\modules\web\node_modules\nodeify\index.js:15:9)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ballerina-composer@0.980.1 build: `cross-env NODE_ENV=production webpack --config webpack.config.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ballerina-composer@0.980.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hasitha\AppData\Roaming\npm-cache\_logs\2018-07-19T05_57_01_100Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 7 (Exit value: 7)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Ballerina - Parent 0.980.1-SNAPSHOT ................ SUCCESS [ 18.124 s]
[INFO] Ballerina - Toml Parser ............................ SUCCESS [  7.570 s]
[INFO] Ballerina - Lang ................................... SUCCESS [ 44.336 s]
[INFO] Ballerina - Library creation utility ............... SUCCESS [  1.435 s]
[INFO] Ballerina - Config API ............................. SUCCESS [  1.736 s]
[INFO] Ballerina - Streaming - Parent ..................... SUCCESS [  0.464 s]
[INFO] Ballerina - Streaming - Siddhi Query API ........... SUCCESS [  9.845 s]
[INFO] Ballerina - Streaming - Siddhi Query Compiler ...... SUCCESS [ 14.802 s]
[INFO] Ballerina - Streaming - Siddhi Annotations ......... SUCCESS [  7.262 s]
[INFO] Ballerina - Streaming - Siddhi Core ................ SUCCESS [ 30.265 s]
[INFO] Ballerina - Core ................................... SUCCESS [ 30.030 s]
[INFO] Ballerina - Built-in Implementation ................ SUCCESS [ 14.366 s]
[INFO] Ballerina - Runtime ................................ SUCCESS [ 10.451 s]
[INFO] Ballerina - System ................................. SUCCESS [  3.717 s]
[INFO] Ballerina - Config API ............................. SUCCESS [  9.489 s]
[INFO] Ballerina - Crypto ................................. SUCCESS [  5.591 s]
[INFO] Ballerina - Task ................................... SUCCESS [  6.334 s]
[INFO] Ballerina - Time ................................... SUCCESS [  9.543 s]
[INFO] Ballerina - Cache .................................. SUCCESS [  5.315 s]
[INFO] Ballerina - Logging ................................ SUCCESS [  4.302 s]
[INFO] Ballerina - Log API ................................ SUCCESS [  5.789 s]
[INFO] Ballerina - I/O .................................... SUCCESS [ 12.652 s]
[INFO] Ballerina - File ................................... SUCCESS [  4.081 s]
[INFO] Ballerina - Internal ............................... SUCCESS [ 11.444 s]
[INFO] Ballerina - Auth ................................... SUCCESS [  8.742 s]
[INFO] Ballerina - MIME Implementation .................... SUCCESS [ 10.872 s]
[INFO] Ballerina - Math ................................... SUCCESS [  5.502 s]
[INFO] Ballerina - Reflect ................................ SUCCESS [  7.207 s]
[INFO] Ballerina - Http/WS ................................ SUCCESS [ 29.331 s]
[INFO] Ballerina - Swagger ................................ SUCCESS [  4.528 s]
[INFO] Ballerina - Transactions Implementation ............ SUCCESS [ 14.881 s]
[INFO] Ballerina - gRPC Implementation .................... SUCCESS [ 11.754 s]
[INFO] Ballerina - sql .................................... SUCCESS [  9.358 s]
[INFO] Ballerina - jdbc ................................... SUCCESS [  5.230 s]
[INFO] Ballerina - WebSub ................................. SUCCESS [ 17.222 s]
[INFO] Ballerina - JMS .................................... SUCCESS [ 14.060 s]
[INFO] Ballerina - MB ..................................... SUCCESS [  5.276 s]
[INFO] Ballerina - Observability .......................... SUCCESS [  8.757 s]
[INFO] Ballerina - h2 ..................................... SUCCESS [  3.572 s]
[INFO] Ballerina - mysql .................................. SUCCESS [  7.478 s]
[INFO] Ballerina - Streams ................................ SUCCESS [  4.503 s]
[INFO] Ballerina - Launcher ............................... SUCCESS [  3.072 s]
[INFO] Ballerina - Language Server - Parent ............... SUCCESS [  0.803 s]
[INFO] Ballerina - Language server - Compiler ............. SUCCESS [  9.272 s]
[INFO] Ballerina - Language server - Core ................. SUCCESS [ 14.908 s]
[INFO] Ballerina - Swagger Tooling - Parent ............... SUCCESS [  0.704 s]
[INFO] Ballerina - Swagger Tooling - Ballerina To Swagger . SUCCESS [ 11.559 s]
[INFO] Ballerina - Swagger Tooling - Swagger to Ballerina . SUCCESS [ 12.643 s]
[INFO] Ballerina - Testerina - Parent ..................... SUCCESS [  0.384 s]
[INFO] Ballerina - Testerina - Core ....................... SUCCESS [ 13.109 s]
[INFO] Ballerina - Packerina .............................. SUCCESS [  8.677 s]
[INFO] Ballerina - Protobuf to Ballerina Tool ............. SUCCESS [  2.885 s]
[INFO] Ballerina - Metrics Extensions - Parent ............ SUCCESS [  0.307 s]
[INFO] Ballerina - Metrics Extension ...................... SUCCESS [  2.875 s]
[INFO] Ballerina - Unit Test Module ....................... SUCCESS [01:09 min]
[INFO] Ballerina - Compiler plugin tests .................. SUCCESS [ 49.527 s]
[INFO] Ballerina - Cli Utils .............................. SUCCESS [ 43.985 s]
[INFO] Ballerina - Language server - Stdio launcher ....... SUCCESS [ 54.354 s]
[INFO] Ballerina - Language server - Launchers ............ SUCCESS [  1.304 s]
[INFO] Ballerina - Docerina ............................... SUCCESS [ 18.971 s]
[INFO] Ballerina - Maven Plugins - Parent ................. SUCCESS [  0.444 s]
[INFO] Ballerina - Docerina Maven Plugin .................. SUCCESS [ 25.382 s]
[INFO] Ballerina - Swagger Tooling - Client Generator ..... SUCCESS [  7.819 s]
[INFO] Ballerina - Prometheus Extension for Metrics ....... SUCCESS [ 14.183 s]
[INFO] Ballerina - Tracing Extensions - Parent ............ SUCCESS [  0.364 s]
[INFO] Ballerina - Jaeger Tracing Extension ............... SUCCESS [  3.915 s]
[INFO] Ballerina - Strip - Bouncycastle ................... SUCCESS [ 20.768 s]
[INFO] Ballerina - Composer ............................... SUCCESS [  0.634 s]
[INFO] Ballerina - Composer - Server Parent ............... SUCCESS [  0.429 s]
[INFO] Ballerina - Composer - Server Core ................. SUCCESS [  4.677 s]
[INFO] Ballerina - Composer - Server Launcher ............. SUCCESS [ 13.965 s]
[INFO] Ballerina - Composer - Services Parent ............. SUCCESS [  1.295 s]
[INFO] Ballerina - Composer - File System Service ......... SUCCESS [  3.321 s]
[INFO] Ballerina - Composer - Logging Service ............. SUCCESS [  6.902 s]
[INFO] Ballerina - Composer - Ballerina Parser Service .... SUCCESS [ 14.055 s]
[INFO] Ballerina - Composer - Ballerina Launcher Service .. SUCCESS [  6.087 s]
[INFO] Ballerina - Composer - Ballerina To Swagger Service  SUCCESS [  4.966 s]
[INFO] Ballerina - Composer - Ballerina TryIt Service ..... SUCCESS [  9.874 s]
[INFO] Ballerina - Composer - Ballerina LangServer Service  SUCCESS [  9.743 s]
[INFO] Ballerina - Composer - Server Distribution ......... SUCCESS [ 35.914 s]
[INFO] Ballerina - Composer - Web ......................... FAILURE [02:46 min]
[INFO] Ballerina - Composer - Integration Tests ........... SKIPPED
[INFO] Ballerina - Composer - Electron Sources ............ SKIPPED
[INFO] Ballerina - Distribution ........................... SKIPPED
[INFO] Ballerina - Tools Distribution ..................... SKIPPED
[INFO] Ballerina - Observability - Tracing Test Utils ..... SKIPPED
[INFO] Ballerina - Integration Test Utils ................. SKIPPED
[INFO] Ballerina - Integration Test ....................... SKIPPED
[INFO] Ballerina - Tools Integration Test ................. SKIPPED
[INFO] Ballerina - Plugin VSCode Server ................... SKIPPED
[INFO] Ballerina - Plugin VSCode .......................... SKIPPED
[INFO] Ballerina - VSCode Plugin - Parent ................. SKIPPED
[INFO] Ballerina - Microbenchmarks 0.980.1-SNAPSHOT ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:38 min
[INFO] Finished at: 2018-07-19T11:27:03+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (npm run build (compile)) on project ballerina-composer-web: Command execution failed.: Process exited with an error: 7 (Exit value: 7) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ballerina-composer-web
```

**Comment by pahans** [comment]
I was able to reproduce this issue in Linux by building ballerina with node 10

**Comment by pahans** [comment]
This was due to some of the dependencies in composers are not yet updated to node.js. Will check them and send PRs
