### ISSUE TITLE
invalid END header

### ISSUE THREAD

**Issue by bmaltais** [ballerina-platform/ballerina-lang#9687]
**Description:**
Trying to follow the tutorial on windows and running the command "ballerina pull wso2/twitter" return ballerina: Oh no, something really went wrong. Bad. Sad.

**Steps to reproduce:**
ballerina pull wso2/twitter

package already exists in the home repository
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

Log file contain:

[2018-07-19 08:28:16,349] ERROR {org.ballerinalang.launcher.Main} - invalid END header (bad central directory offset) 
java.util.zip.ZipError: invalid END header (bad central directory offset)
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1045)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.initFS(ZipConverter.java:56)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.pathWithinZip(ZipConverter.java:45)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.resolveIntoArchive(ZipConverter.java:33)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.combine(ZipConverter.java:27)
	at org.wso2.ballerinalang.compiler.packaging.converters.ZipConverter.combine(ZipConverter.java:19)
	at org.wso2.ballerinalang.compiler.packaging.Patten.callReduceForEach(Patten.java:93)
	at org.wso2.ballerinalang.compiler.packaging.Patten.lambda$convert$33(Patten.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.ballerinalang.packerina.cmd.PullCommand.execute(PullCommand.java:119)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

**Affected Versions:**
Ballerina 0.980.1

**OS, DB, other environment details and versions:**
Windows 10 64 bit

suggest possible assignees-->

**Comment by NatashaWso2** [comment]
This issue can exist if the twitter package pulled is corrupted. Can you delete the twitter package from your home repository (.ballerina) and try pulling it again?

**Comment by pubudu91** [comment]
@NatashaWso2 If that is the case, it should not result in the BVM crashing right?

**Comment by bmaltais** [comment]
That fixed it ;-) Probably adding a function to delete and redownload the package when corruption is suspected would make things easier ;-)

**Comment by NatashaWso2** [comment]
Sure @bmaltais  will consider the option of adding such a function. Closing this issue since it is resolved.

**Comment by Anoukh** [comment]
@NatashaWso2 I too experienced the same. Is there any way we can handle such a case without getting the BVM to crash? Since we now have the uninstall command we can give meaningful instructions to the user as well
