### ISSUE TITLE
Issues using constrained maps in the match statement

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#9705]
**Description:**

**Scenario 1:**
```bal
import ballerina/io;

function main (string... args) {
    any m = getMap();

    match (m) {
        map<string> ms => io:println("MS");
        map myMap => io:println("M");
        any => io:println("any");
    }
}

function getMap() returns any {
    map<string> m;
    return m;
}
```

Expected Output:
```cmd
MS
```

Current Behaviour:
Causes a Bad. Sad. error with the following error in the internal log:
```
[2018-07-23 11:02:40,507] ERROR {org.ballerinalang.launcher.Main} - org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:2283)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:2247)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2232)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2202)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:873)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1943)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:549)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:429)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1950)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:295)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:255)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:196)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:167)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:87)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
```
Error occurs only when the match statement is used with the value specified in the constrained map clause, i.e., works with
```bal
 map<string> => io:println("MS");
```
Works as expected when the assignment is changed to 
```bal
any|map m = getMap();
```

**Scenario 2:**
```bal
import ballerina/io;

function main (string... args) {
    any m = getMap();

    match (m) {
        map myMap => io:println("M");
        any => io:println("any");
    }
}

function getMap() returns any {
    map<string> m;
    return m;
}
```

Expected Output:
```cmd
M
```

Current Output:
```cmd
any
```

**Reproducible With:**
0.980.1

**Comment by MaryamZi** [comment]
Works with 0.990.0-SNAPSHOT, with the new `is` check.

```ballerina
import ballerina/io;

public function main (string... args) {
    any m = getMap();

    if (m is map<string>) {
        io:println("MS", m);
    } else if (m is map<any>) {
        io:println("M", m);
    }  else {
        io:println("any", m);
    }
}

function getMap() returns any {
    map<string> m = { "one": "first" };
    return m;
}
```
