### ISSUE TITLE
XA transactions fail with Postgres

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#9740]
**Description:**
$subject.

Following is the stacktrace can be observed at [1] when debugging.

```bash
java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.postgresql.xa.PGXADataSource to javax.sql.DataSource
        at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:113)
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:330)
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
        at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
        at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1222)
        at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDBClient(SQLDatasourceUtils.java:1163)
        at org.ballerinalang.database.jdbc.CreateClient.execute(CreateClient.java:50)
        at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
        at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:389)
        at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:260)
        at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:411)
        at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:153)
        at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:81)
        at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:320)
        at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:267)
        at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:247)
        at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:467)
        at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:138)
        at org.ballerinalang.util.program.BLangFunctions.invokeEntrypointCallable(BLangFunctions.java:110)
        at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:70)
        at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:124)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:117)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.lang.ClassCastException: Cannot cast org.postgresql.xa.PGXADataSource to javax.sql.DataSource
        at java.lang.Class.cast(Class.java:3369)
        at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:102)
        ... 27 more
```
Apparently PGXADataSource class does not implement the javax.sql.DataSource class like other XA datasource implementations do. This has been discussed in a postgres forum but couldn't find a proper conclusion in that discussion[2]. 

[1] https://github.com/ballerina-platform/ballerina-lang/blob/v0.980.0/stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasource.java#L200
[2] https://www.postgresql.org/message-id/4629234B.8050507%40enterprisedb.com

**Steps to reproduce:**
Can be reproduced by following ballerina program.

```ballerina
import ballerina/io;
import ballerina/jdbc;

// Create an endpoint for the first database named testdb1. Since this endpoint
// participates in a distributed transaction, the `isXA` property should be true.
endpoint jdbc:Client testDB1 {
    url: "jdbc:postgresql://localhost:5432/testdb1",
    username: "postgres",
    password: "123",
    poolOptions: { maximumPoolSize: 5, isXA: true }
};


// Create an endpoint for the second database named testdb2. Since this endpoint
// participates in a distributed transaction, the `isXA` property should be true.
endpoint jdbc:Client testDB2 {
    url: "jdbc:postgresql://localhost:5432/testdb2",
    username: "postgres",
    password: "123",
    poolOptions: { maximumPoolSize: 5, isXA: true }
};

function main(string... args) {
    // Create the table named CUSTOMER in the first database.
    var ret = testDB1->update("CREATE TABLE CUSTOMER (ID SERIAL, NAME VARCHAR(30))");
    handleUpdate(ret, "Create CUSTOMER table");
    // Create the table named SALARY in the second database.
    ret = testDB2->update("CREATE TABLE SALARY (ID INT, VALUE FLOAT)");
    handleUpdate(ret, "Create SALARY table");

    // Begins the transaction.
    transaction with oncommit = onCommitFunction,
    onabort = onAbortFunction {
    // This is the first action to participate in the transaction. It inserts
    // customer name to the first DB and gets the generated key.
        var retWithKey = testDB1->updateWithGeneratedKeys("INSERT INTO CUSTOMER(NAME) OUTPUT INSERTED.ID VALUES ('Anne')", ());
        string generatedKey;
        match retWithKey {
            (int, string[]) y => {
                var (count, ids) = y;
                generatedKey = ids[0];
                io:println("Inserted row count: " + count);
                io:println("Generated key: " + generatedKey);
            }
            error err => io:println("Insert to student table failed: "
                    + err.message);
        }

        //Converte the returned key into integer.
        ret = <int>generatedKey;
        int key = -1;
        match ret {
            int retInt => key = retInt;
            error err => io:println("Converting key to string failed: "
                    + err.message);
        }
        io:println("Generated key for the inserted row: " + key);
        // This is the second action to participate in the transaction. It inserts the
        // salary info to the second DB along with the key generated in the first DB.
        ret = testDB2->update("INSERT INTO SALARY (ID, VALUE) VALUES (?, ?)",
            key, 2500);
        handleUpdate(ret, "Insert to SALARY table");
    } onretry {
        io:println("Retrying transaction");
    }

    // Drop the tables created for this sample.
    ret = testDB1->update("DROP TABLE CUSTOMER");
    handleUpdate(ret, "Drop Table CUSTOMER");

    ret = testDB2->update("DROP TABLE SALARY");
    handleUpdate(ret, "Drop Table SALARY");

    // Close the connection pool.
    testDB1.stop();
    testDB2.stop();
}

function onCommitFunction(string transactionId) {
    io:println("Transaction: " + transactionId + " committed");
}

function onAbortFunction(string transactionId) {
    io:println("Transaction: " + transactionId + " aborted");
}

// Function to handle return of the update operation.
function handleUpdate(int|error returned, string message) {
    match returned {
        int retInt => io:println(message + " status: " + retInt);
        error err => io:println(message + " failed: " + err.message);
    }
}

```

**Affected Versions:**
ballerina 0.980.0

**OS, DB, other environment details and versions:**
Postgres DB version 10.3
Postgres driver version 42.2.1

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Manuri** [comment]
Closing since this is not possible to do with the current generic implementation we have. Need to implement this in the future when it comes to a point that we implement database specific clients.
