### ISSUE TITLE
runtime code failure

### ISSUE THREAD

**Issue by rpalenik** [ballerina-platform/ballerina-lang#9794]
**Description:**
Code failed at runtime with following message:

ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

**Steps to reproduce:**

Run This code. I have probably omitted keyword "SELECT" in forever statement. The log file, though, is present in the current directory.

The code:

`import ballerina/log;
import ballerina/http;
import ballerina/io;
import ballerina/time;
import ballerina/internal;

type Trade record {
    string eventType;
    string eventTime;
    string symbol;
    string tradeId;
    string price;
    string quantity;
    string buyerOrderId;
    string sellerOrderId;
    string tradeTime;
    !...
};
@final map<string> mapTrade = {
    eventType: "e",
    eventTime: "E",
    symbol: "s",
    tradeId: "t",
    price: "p",
    quantity: "q",
    buyerOrderId: "b",
    sellerOrderId: "a",
    tradeTime: "T"

};
@final int KINESIS_BATCH_SIZE=500;

stream<Trade> kinesisData;
function printStreamItem(json item){
    io:println(item);
}
//kinesisData.subscribe(printStreamItem);
//
endpoint http:Client awsEP {
    url:"http://localhost:8000/firehose"
};

public function send_batch_kinesis(string strm, json batch)  {
    http:Request req;
    json payload = {"stream": strm, "data": batch};
    req.setTextPayload(payload.toString());
    io:println(payload.toString());
    var resp = awsEP->post("/put_record_batch", req);

    match resp {
    http:Response response => {
        // Retrieve the text message from the response.
        json jsonData = check response.getJsonPayload();
        log:printInfo("Response: " +  jsonData.toString());
    }
    // If an error occurs when getting the response, log the error.
    error err => log:printError(err.message);
}
}

function translateJSON(map<string> mapStruct, json jsonInput) returns(Trade){
    json output = {};
    foreach key, value in mapStruct {
        output[key] = jsonInput[value];
    }
    Trade result = check <Trade>output;
    return result;
}

endpoint http:WebSocketClient wsClientEp {
    url: "wss://stream.binance.com:9443/stream?streams=neobtc@trade/ethbtc@trade",
    callbackService: clientCallbackService // register callback service
};

service <http:WebSocketClientService> clientCallbackService {
    json[] batch;
    onText(endpoint ep, string data) {
        json jsonData = check internal:parseJson(data);
        Trade output = translateJSON(mapTrade, jsonData.data);
        kinesisData.publish(output);
        
        //send_batch_kinesis("cryptoExchangeData", [jsonOutput]);
        //io:println(jsonOutput);
    }
}

function main (string... args) {
    kinesisData.subscribe(printStreamItem);
    forever {
        from kinesisData
        window timeBatch(10)
        => (Trade[] batch) {
            io:println(batch);
        }
    }
}
`

Log output:

[2018-07-31 13:21:54,031] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.checkOutputAttributes(SemanticAnalyzer.java:1823)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1220)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForever.accept(BLangForever.java:51)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1198)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$126(SemanticAnalyzer.java:518)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:518)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1198)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:1165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:318)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1198)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$analyzeFunctions$106(SemanticAnalyzer.java:257)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeFunctions(SemanticAnalyzer.java:257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:240)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:224)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:180)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:147)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

**Affected Versions:**
MacOS High Sierra, Ballerina 0.980.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
Hi @rpalenik 
We are looking into this.

**Comment by mohanvive** [comment]
Fix added in https://github.com/ballerina-platform/ballerina-lang/pull/10119.
