### ISSUE TITLE
Swagger Annotations - ERROR {org.ballerinalang.launcher.Main} - null

### ISSUE THREAD

**Issue by jimk-osu** [ballerina-platform/ballerina-lang#9802]
**Description:**
In validating the swagger annotations for a working ballerina service I found that adding the swagger annotations and running `ballerina swagger export this.bal` works as defined.

With the swagger annotations in place and `ballerina run this.bal --config this.toml` the following error is thrown:

```
[2018-07-31 11:48:38,941] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.ballerinalang.code.generator.model.EndpointContextHolder.extractDetails(EndpointContextHolder.java:84)
	at org.ballerinalang.code.generator.model.EndpointContextHolder.buildContext(EndpointContextHolder.java:60)
	at org.ballerinalang.code.generator.model.ClientContextHolder.buildContext(ClientContextHolder.java:52)
	at org.ballerinalang.code.generator.util.ClientGeneratorPlugin.process(ClientGeneratorPlugin.java:62)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$175(CompilerPluginRunner.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:291)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:163)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:210)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$170(CompilerPluginRunner.java:130)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:130)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:118)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:192)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:162)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
```

If I comment out the swagger annotations there are no errors and the service runs normal.

**Steps to reproduce:**`
- Create working service with `ballerina/config`
- Add Swagger annotations
- `ballerina swagger export this.bal` works
- `ballerina run this.bal --config this.toml`
  - Confirm error in logs
- Comment out swagger annotations
- `ballerina run this.bal --config this.toml`
  - service runs normally

**Affected Versions:**
`Ballerina 0.980.1`

**OS, DB, other environment details and versions:**
OS: `Darwin`
VS Code: `Version 1.24.1 (1.24.1)`
  - Ballerina Extension: `0.980.0`

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by jimk-osu** [comment]
Using the `Ballerina 0.980.2-SNAPSHOT` nightly in other testing the problems persists.

I have noticed its specifically the ` @swagger:ClientEndpoint` annotation causing the exception. When that is commented out, the `ballerina run` works as normal.

**Comment by DimalChandrasiri** [comment]
Hi @jimk-osu 

Please apologize for the late reply from our end regarding the issue you created. We've tried to recreate the aforementioned issue and have failed to recreate it on our end. We tried with the mentioned version of `ballerina` as well as the `latest version`.

Would it be possible for you to post the  relevant `.bal` file and the `.toml` file you used in order for us to get a better look at the issue?
