### ISSUE TITLE
testing basic db connection and table use

### ISSUE THREAD

**Issue by vgiargia** [ballerina-platform/ballerina-lang#9878]
**Description:**

basic test to an oracle jdbc connection using ojdbc6.jar 

**Steps to reproduce:**

just point to an oracle db the endpoint connection
the fault is related to the run command in to the ide

**Affected Versions:**
0.980.1
**OS, DB, other environment details and versions:**
windows 10
oracle on centOs 
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

THE CODE
```ballerina
import ballerina/io;
import ballerina/jdbc;
import ballerina/sql;

endpoint jdbc:Client testDB {
    url: "jdbc:oracle:thin:@tst-test-odb01.isola.csi.it:1521:INTEROP",
    username: "INTEROP1",
    password: "MYPASS",

    poolOptions: { maximumPoolSize: 5 }
};

type Account record {
    int id,
    int amount,
    string nome,
};

type MyRec record {
    int id,
    string name,
    float rank,
};

function main(string... args) {

    int|error result = testDB->update("drop table myTest");

    io:println("drop table returns, ",result);

    result = testDB->update("create table myTest (id number(12),name varchar2(40),age number(3), rank number(5,2))");

    io:println("create table returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",1,"alpha",1.01);
    io:println("insert returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",2,"beta",1.31);
    io:println("insert returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",3,"eta",0.33);
    io:println("insert returns, ",result);

    table|error sr = testDB->select("SELECT * FROM myTest",Account);

    io:println("select: ",sr);

    match sr {
        table t => {
            foreach e in t {
                io:println(e);
            }
        }
        error e => io:println("error ",e);
    }

    var selectRet = testDB->select("SELECT * FROM BancAccount",Account);

    io:println("statement executed");
    table<Account> dt;
    match selectRet {
        table tableReturned => dt = tableReturned;
        error err => io:println("Select data from Account table failed: " + err.message);
    }

    foreach entry in dt {
        io:println("id:" + entry.id);
        io:println("amount:" + entry.amount);
 //       io:println("name:" + entry.nome);
    }

}
```

**Comment by vgiargia** [comment]
import ballerina/io;
import ballerina/jdbc;$ cat ./programs/Ballerina/project/jdbc/ballerina-internal.log
[2018-08-02 15:12:28,584] ERROR {org.ballerinalang.launcher.Main} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writeInstructions(PackageInfoWriter.java:604)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writePackageInfo(PackageInfoWriter.java:209)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.getPackageBinary(PackageInfoWriter.java:147)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getPackageBinaryContent(CodeGenerator.java:3623)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:365)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:200)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:172)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.launcher.Main.main(Main.java:66)

[2018-08-02 15:15:30,684] ERROR {org.ballerinalang.launcher.Main} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writeInstructions(PackageInfoWriter.java:604)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writePackageInfo(PackageInfoWriter.java:209)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.getPackageBinary(PackageInfoWriter.java:147)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getPackageBinaryContent(CodeGenerator.java:3623)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:365)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:200)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:172)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.launcher.Main.main(Main.java:66)



import ballerina/sql;

endpoint jdbc:Client testDB {
    url: "jdbc:oracle:thin:@tst-test-odb01.isola.csi.it:1521:INTEROP",
    username: "INTEROP1",
    password: "MYPASS",

    poolOptions: { maximumPoolSize: 5 }
};

type Account record {
    int id,
    int amount,
    string nome,
};

type MyRec record {
    int id,
    string name,
    float rank,
};

function main(string... args) {

    int|error result = testDB->update("drop table myTest");

    io:println("drop table returns, ",result);

    result = testDB->update("create table myTest (id number(12),name varchar2(40),age number(3), rank number(5,2))");

    io:println("create table returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",1,"alpha",1.01);
    io:println("insert returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",2,"beta",1.31);
    io:println("insert returns, ",result);

    result = testDB->update("insert into myTest (id,name,rank) values(?,?,?)",3,"eta",0.33);
    io:println("insert returns, ",result);

    table|error sr = testDB->select("SELECT * FROM myTest",Account);

    io:println("select: ",sr);

    match sr {
        table t => {
            foreach e in t {
                io:println(e);
            }
        }
        error e => io:println("error ",e);
    }

    var selectRet = testDB->select("SELECT * FROM BancAccount",Account);

    io:println("statement executed");
    table<Account> dt;
    match selectRet {
        table tableReturned => dt = tableReturned;
        error err => io:println("Select data from Account table failed: " + err.message);
    }

    foreach entry in dt {
        io:println("id:" + entry.id);
        io:println("amount:" + entry.amount);
 //       io:println("name:" + entry.nome);
    }

}

**Comment by vgiargia** [comment]
the log

$ cat ./programs/Ballerina/project/jdbc/ballerina-internal.log
[2018-08-02 15:12:28,584] ERROR {org.ballerinalang.launcher.Main} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writeInstructions(PackageInfoWriter.java:604)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writePackageInfo(PackageInfoWriter.java:209)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.getPackageBinary(PackageInfoWriter.java:147)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getPackageBinaryContent(CodeGenerator.java:3623)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:365)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:200)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:172)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.launcher.Main.main(Main.java:66)

[2018-08-02 15:15:30,684] ERROR {org.ballerinalang.launcher.Main} - null
java.lang.NullPointerException
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writeInstructions(PackageInfoWriter.java:604)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.writePackageInfo(PackageInfoWriter.java:209)
        at org.wso2.ballerinalang.programfile.PackageInfoWriter.getPackageBinary(PackageInfoWriter.java:147)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.getPackageBinaryContent(CodeGenerator.java:3623)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:365)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:200)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:172)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.launcher.Main.main(Main.java:66)

**Comment by vgiargia** [comment]
thanks for the info

**Comment by Manuri** [comment]
Created a separate issue with a simple example to track the NPE issue.
https://github.com/ballerina-platform/ballerina-lang/issues/9899
