### ISSUE TITLE
Bad Sad Error for duplicate resources in a Service

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#9945]
The following error is logged in ballerina-internal.log. The program to get this error is attached herewith.

[2018-08-08 10:30:06,859] ERROR {org.ballerinalang.launcher.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.reportDiagnostic(BLangDiagnosticLog.java:106)
	at org.wso2.ballerinalang.compiler.util.diagnotic.BLangDiagnosticLog.error(BLangDiagnosticLog.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.isUniqueSymbol(SymbolResolver.java:206)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.checkForUniqueSymbol(SymbolResolver.java:149)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineSymbol(SymbolEnter.java:1007)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineInvokableSymbol(SymbolEnter.java:955)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:666)
	at org.wso2.ballerinalang.compiler.tree.BLangResource.accept(BLangResource.java:30)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:173)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$null$93(SymbolEnter.java:948)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineServiceMembers$94(SymbolEnter.java:948)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineServiceMembers(SymbolEnter.java:941)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:221)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:173)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:166)
	at org.wso2.ballerinalang.compiler.PackageLoader.define(PackageLoader.java:388)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:282)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$44(Compiler.java:147)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:148)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:87)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

[sample.txt](https://github.com/ballerina-platform/ballerina-lang/files/2268972/sample.txt)

**Comment by SupunS** [comment]
There seems to be two resources with same name `employee`. The error is thrown when the compiler is trying to report the error (diagnostic position is null).

**Comment by lafernando** [comment]
Ah yes, I noticed this in my scenario later, forgot to update the issue.

Anyway, can this be fixed in the compiler, so a meaningful error is given
to the user.

Cheers,
Anjana.

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9951
